### ISSUE TITLE
Error when trying to unsubscribe

### ISSUE THREAD

**Issue by ChristianHuff-DEV** [knadh/listmonk#100]
I started a campaign which included the `{( UnsubscribeURL ))` as a link.

After sending the mail and clicking the link to unsubscribe I see the following error: `{"message":"Not Found"}`.

I didn't find a reliable way to reproduce it. Most of the times it works. The error is only encountered sometimes.

Are there additional logs (other than the once of the Docker container itself) to find the cause?

**Comment by knadh** [comment]
Hm, that's strange. It should either work or it shouldn't. `Not found` means there's something off with routing and it's not hitting the right URI. Can you paste the unsubscribe URL that you're getting here?

**Comment by ChristianHuff-DEV** [comment]
The URL of the link in the mail is: http://localhost:8086/subscription/12adc165-15ac-42ee-a224-7597cff08258/19dbaf04-6fe2-44dc-a11a-e12a72863e01

**Comment by knadh** [comment]
Were you able to figure this out? This can only happen if the routing is off (broken URI somehow?). Have been unable to reproduce this.

**Comment by ChristianHuff-DEV** [comment]
Since I put listmonk behind a reverse proxy I haven't encountered the issue again.

Is listmonk generating any logs (I'm running it in a Docker container) I could check if the error occurs again?

**Comment by knadh** [comment]
listmonk logs internal errors to stdout, but it does not have access logs where we can look for 404s though.
