### ISSUE TITLE
Idk:Error

### ISSUE THREAD

**Issue by vldtz12** [knadh/listmonk#1000]
Hi. I am not a programmer but I am having trouble connecting my mail server to listmonk. My server is on Linode (Mail In A Box) and it works. When I try to connect to my server via listmonk I get the error "error sending SMTP test (Test connection): mail: no address". I tried to google something like this but I can't find it. Sorry for the stupid question but I would really appreciate it if someone could help me out. Thank you

**Comment by knadh** [comment]
Is the `From email` in Settings -> General empty? It shouldn't be.

![image](https://user-images.githubusercontent.com/547147/198204163-c6e06a6a-ce16-4547-8a85-3366bf034130.png)
