### ISSUE TITLE
Analytics for transaction emails 

### ISSUE THREAD

**Issue by shravankumar-suvarna** [knadh/listmonk#1001]
Hey @knadh, listmonk is just awesome. Thank you for building this for us. 

Q1 - Is there a way to track analytics (views/clicks) for transactional emails as well? It is not getting stored in the database as well. 

Q2 - Since I'm able to view analytics for campaigns. I was curious to understand if there's a way to send personalized emails. All I want is something like {{ .Tx.Data.* }} in my campaign template. Is that possible?

**Comment by knadh** [comment]
Thanks @shravankumar-suvarna.

1) Please see https://github.com/knadh/listmonk/issues/907

2) Yes. In fact, that's exactly how it works. eg: [`{{ .Tx.Data.order_id }}`](https://github.com/knadh/listmonk/blob/master/static/email-templates/sample-tx.tpl#L93)

**Comment by shravankumar-suvarna** [comment]
@knadh, thanks for the prompt reply. 
I agree, tracking transactional email is not required. I had a different use case in my mind. I wanted to send personalised newsletter (For eg, send user A content X, user B content Y and so forth) based on some unique attributes. This I wanted to do via API from backend. 

I thought transaction emails can be useful as there's parameter named 'data'. But I wanted to track user behaviour and change the future content based on the same. 

Anyway, I plan to use subscriber attributes and normal campaign to achieve my use case. 

Apparently, the documentation does not show that we can update the attributes via an api. Details are not available for the following endpoint -- PUT | /api/subscribers/:id | Updates a subscriber by ID.

I'm closing this issue. Thanks again for this wonderful tool. Love it!
