### ISSUE TITLE
Subject is empty if there is no template variable in it [transactional template]

### ISSUE THREAD

**Issue by diverzija** [knadh/listmonk#1003]
**Version:**
 - listmonk: v2.2.0
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**
If you set subject line of transactional template without template variable, mail will be with empty subject.

**Screenshots:**
No screenshots.

**Comment by knadh** [comment]
This is already fixed. Please see https://github.com/knadh/listmonk/issues/963 for more details and a temporary workaround.
