### ISSUE TITLE
import problem: blocked over 100 subscriber

### ISSUE THREAD

**Issue by bonushenricus** [knadh/listmonk#1005]
Hello
meanwhile, congratulations for listmonk, very easy to use.
However, I have a problem that I do not understand where it comes from: I have about 150 emails to import into the lists, but in addition to 100 it is not possible: the import tool fails, but no error log appears.
I did a railway deploy. I have not exceeded the limits of my plan.

**Comment by knadh** [comment]
Thanks @bonushenricus. listmonk can import hundreds of thousands of rows in a CSV file just fine. This could possibly be connected to the Raleway environment, maybe a file upload size limit in their proxy. If there's no error message in the log, most likely, it's not an error produced by listmonk itself.

`the import tool fails, but no error log appears.`

Can you share a screenshot of what you see? Possible to use the browser request inspector and check the response body on the failed request?

**Comment by bonushenricus** [comment]
Thank you.
I wrote to them about railway before and they replied that it wasn't their problem. Yet just now I have tried again and now it works! I must have fixed something for them!
Excuse. The issue can be canceled.
