### ISSUE TITLE
how to upgrade to latest version of listmonk

### ISSUE THREAD

**Issue by smaranr** [knadh/listmonk#1006]
i have tried stopping the existing container but am getting the error "root@ip-172-31-25-37:~# sudo docker stop 3fe46d3b358d
Error response from daemon: cannot stop container: 3fe46d3b358d: permission denied" 

tried using loggin in the user but not able to login with the error "Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth: dial unix /var/run/docker.sock: connect: permission denied"

Please help with steps to upgrade. Also it would be so helpful if upgrade is available via UI as feature enhancement.

**Comment by mr-karan** [comment]
This isn't a listmonk issue. Your user isn't added to `docker` group so it's unable to reach the UNIX socket running by docker daemon. 

https://docs.docker.com/engine/install/linux-postinstall/

**Comment by smaranr** [comment]
![image](https://user-images.githubusercontent.com/16491433/198829115-65474539-5bf1-484a-b498-615c1926725e.png)

facing the above error. I am accessing through root user only.

**Comment by mr-karan** [comment]
Just noticed that it's installed via `snap`. Did you run `sudo snap enable docker`? (https://snapcraft.io/docker)

**Comment by smaranr** [comment]
i see the below. 
![image](https://user-images.githubusercontent.com/16491433/199011849-0245c188-c89e-4f46-8182-2122c7094e8f.png)

In the beginning i followed steps from https://github.com/yasoob/listmonk-setup.

now am also seeing the below couldn't load the old version also now. 
![image](https://user-images.githubusercontent.com/16491433/199012235-093d3db9-8c71-4713-8e23-8ac11083de24.png)

Am stuck here now:
![image](https://user-images.githubusercontent.com/16491433/199012687-8c3662ec-c02e-44d3-a7cb-0654581096cf.png)
