### ISSUE TITLE
Listmonk Require Authorization on View In Browser / Unsubscribe

### ISSUE THREAD

**Issue by herng77** [knadh/listmonk#1007]
**Version:**
 - listmonk: [eg: v1.0.0]
 - OS: [e.g. Fedora]

**Description of the bug and steps to reproduce:**

**Screenshots:**

Hello ListMonk Developer,

I am new to listmonk, tried to do a campaign, however, when I click view in browser / unsubscribe, it is prompting login.

Please refer to the screenshot below. I saw a post where removing all images works but it is still prompting. 

![Captu2re](https://user-images.githubusercontent.com/33309010/198889658-a5db38eb-4410-4e1a-adfd-208eca963a17.PNG)

**Comment by knadh** [comment]
Seems like this page is sending a request to an admin endpoint, which it should.

1) What is the root URL you've configured in settings?

2) Are there any custom proxy (eg: Nginx) rules that are changing certain paths?
