### ISSUE TITLE
SendGrid bounce is not recording

### ISSUE THREAD

**Issue by charlesmudy** [knadh/listmonk#1009]
Hello,

Trying to setup the bounce but not sure why it's not recording.

I am using the Key from this screenshot:
<img width="1085" alt="Screenshot 2022-11-04 at 05 59 50" src="https://user-images.githubusercontent.com/1445007/199891419-501bac51-fbd2-4ad3-b860-226653a28a1b.png">

And I have inserted it here:
<img width="991" alt="Screenshot 2022-11-04 at 05 55 15" src="https://user-images.githubusercontent.com/1445007/199891076-d79f8333-14ed-43ea-a1e4-1200f62fc196.png">

But the Bounce report is empty but I get this in the log: `bounces.go:74: bounced subscriber ( / 12345bukky12345@yahoo.co.uk) not found`

**Comment by knadh** [comment]
The error says that the subscriber `12345bukky12345@yahoo.co.uk` was not found in the subscribers DB. Is that right?

**Comment by charlesmudy** [comment]
Of course the subscriber is there. Other emails on the list was sent, this one failed then Bounce function is struggling to record it somehow

**Comment by charlesmudy** [comment]
@knadh I honestly don't know why I have this code or where it came from:

`
WITH sub AS (
    SELECT subscribers.id, subscribers.status
	FROM subscribers, campaigns
	WHERE $3 != '' AND campaigns.uuid = $3::UUID
	AND CASE WHEN $1 != '' THEN subscribers.uuid = $1::UUID ELSE subscribers.email = $2 END
),
`

Instead of:

`
WITH sub AS (
    SELECT id, status FROM subscribers WHERE CASE WHEN $1 != '' THEN uuid = $1::UUID ELSE email = $2 END
),
`

... All good now, closing this ticket.
