### ISSUE TITLE
Opt-In page doesn't show subscribed lists

### ISSUE THREAD

**Issue by sudomk** [knadh/listmonk#1011]
Version:

    listmonk: 2.2.0
    OS: Docker (listmonk/listmonk:latest)

Description of the bug and steps to reproduce:

I've just set up a private list with double opt-in enabled. When sending out opt-in mails the subscribed lists are shown correctly in the confirmation email. But on the opt-in page (after clicking on the confirm button) it doesn't show the lists the user subscribed to. In the `HTML` I can see, that the `<ul>` was generated but not the `<li>`-tags for each list a user subscribed to. I also tested it with an public subscription list and it had the same problem.

![image](https://user-images.githubusercontent.com/80150728/200179446-938303bd-6346-42ed-a236-04e204b37c80.png)

I had a look into the related part inside the `optin.html` but couldn't figure out what the problem might be.

**Comment by knadh** [comment]
This has already been fixed and will be available in the next release. Please see https://github.com/knadh/listmonk/issues/940 for a temporary work around.
