### ISSUE TITLE
Unclear on API for unsubscribing: Response either "Invalid ID(s)" or "No IDs given."

### ISSUE THREAD

**Issue by paulrudy** [knadh/listmonk#1012]
The example in the docs for the PUT request for modifying a user's list membership says:

```
curl -u "username:username" -X PUT 'http://localhost:9000/api/subscirbers/lists/:1' \
--data-raw '{"action": "add", "target_list_ids": [4, 5, 6], "status": "confirmed"}'
```

(I made a [PR](https://github.com/knadh/listmonk-site/pull/34) for fixing the typo "subscirbers")

When I use this as a template, with typo fixed, like this:

```
curl -u "username:username" -X PUT 'http://localhost:9000/api/subscribers/lists/:140' \
--data-raw '{"action": "unsubscribe", "target_list_ids": [1]}'
```

The response is `{"message":"Invalid ID(s)"}`. I've made sure that the user id is correct, and the list id is correct.

It's unclear if these instances were mistakes, but I've seen multiple places in the github issues where someone has left the colon, like this:  `'http://localhost:9000/api/subscribers/lists/140'`. When I use that format, I get `{"message":"No IDs given."}`.

No matter what, I'm unable to unsubscribe the user via this PUT request. Any help would be appreciated.

**Comment by Chikanz** [comment]
I'm also getting this error. I think this [line ](https://github.com/knadh/listmonk/blob/95b8df29182e16b9e321d8a1ec69e292f5f69844/cmd/subscribers.go#L349) might be the issue but I'm not sure. Adding SubscriberIDs to the request body still returns the same error 🤔

**Comment by knadh** [comment]
`'http://localhost:9000/api/subscribers/lists/:140'`

It should be `140` not `:140`.

**Comment by paulrudy** [comment]
> It should be `140` not `:140`.

Thanks for the clarification. Still, without the colon, the response is `{"message":"No IDs given."}`

**Comment by paulrudy** [comment]
> I'm also getting this error. I think this [line ](https://github.com/knadh/listmonk/blob/95b8df29182e16b9e321d8a1ec69e292f5f69844/cmd/subscribers.go#L349) might be the issue but I'm not sure. Adding SubscriberIDs to the request body still returns the same error 🤔

While we're waiting for fixing or clarification on this API method for a single subscriber, the [other API method](https://listmonk.app/docs/apis/subscribers/#put-apisubscriberslists) for changing one or more subscribers' list memberships works fine, and in that method you put the subscriber id's in the request body.

**Comment by knadh** [comment]
Some of these APIs aren't documented. I haven't had the time, unfortunately. You can invoke these options from the admin UI and check the exact payload in the network requests tab. The API that's exposed and the API used by the admin UI are the same.

**Comment by Chikanz** [comment]
> While we're waiting for fixing or clarification on this API method for a single subscriber, the [other API method](https://listmonk.app/docs/apis/subscribers/#put-apisubscriberslists) for changing one or more subscribers' list memberships works fine, and in that method you put the subscriber id(s) in the request body.

Much better, thanks!
