### ISSUE TITLE
'AxiosError' error on Analytics page

### ISSUE THREAD

**Issue by mohamed-ea** [knadh/listmonk#1014]
**Version:**
 - listmonk: v2.2.0
 - OS: Centos 7

**Description of the bug and steps to reproduce:**
Where i visite the analytics page of any compaign i got a popup saying "AxiosError" and the charts are all broken (shoing nothing, just a infinit spinner)

Listmonk is hosted on a vps using dockercompose behind an nginx proxy

Here is my docker-compose.yml:
<pre>version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  ports:
    - "9000:9000"
  networks:
    - listmonk
  environment:
    - TZ=Etc/UTC

x-db-defaults: &db-defaults
  image: postgres:13
  ports:
    - "9432:5432"
  networks:
    - listmonk
  environment:
    - POSTGRES_PASSWORD=xxxx
    - POSTGRES_USER=xxxx
    - POSTGRES_DB=xxxx
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    <<: *app-defaults
    container_name: listmonk_app
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml

  demo-db:
    container_name: listmonk_demo_db
    <<: *db-defaults

  demo-app:
    <<: *app-defaults
    container_name: listmonk_demo_app
    command: [sh, -c, "yes | ./listmonk --install --config config-demo.toml && ./listmonk --config config-demo.toml"]
    depends_on:
      - demo-db

networks:
  listmonk:

volumes:
  listmonk-data:
</pre>

and here is the nginx reverse proxy to this docker container:
<pre>server {
   listen 80;
	listen 443 ssl http2;
    server_name emailing.MYDOMAIN.com;

    #SSL-START SSL related configuration, do NOT delete or modify the next line of commented-out 404 rules
    ...
    #SSL-END

    proxy_buffers 16 64k;
    proxy_buffer_size 128k;
    location / {
        proxy_pass http://127.0.0.1:9000;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}</pre>

**Screenshots:**

<img width="721" alt="Analytics : listmonk 2022-11-08 09-20-51" src="https://user-images.githubusercontent.com/315904/200512316-11913c79-a698-48bc-83c1-40e837e6a93c.png">

**Comment by knadh** [comment]
Seems like a browser extension incorrectly blocking the request. Do you have something like uBlock Origin installed?

**Comment by MaximilianKohler** [comment]
> Seems like a browser extension incorrectly blocking the request. Do you have something like uBlock Origin installed?

Yep, that was it. Thanks.
