### ISSUE TITLE
Bounce report for Sendgrid needs extra parameter

### ISSUE THREAD

**Issue by charlesmudy** [knadh/listmonk#1015]
**Version:**
 - listmonk: [eg: v2.3.0]

**Description of the bug and steps to reproduce:**
So I noticed the bounce report for Sendgrid SMTP isn't working, it was missing the campaign ID.

Here is what I did to solve it:

Inside sendgrid.go file, add `CampaignUUID: strings.ToLower(n.CampaignUUID),` to line 66

Then when sending your campaign, add `"X-SMTPAPI" {"unique_args": {"campaign_uuid": campaign_uuid }}` to your header

Ideally, @knadh if this header thing can be done from the library to set `X-SMTPAPI` for all SMTP request from sendgrid ... that would be great but the above works as well.

**Comment by knadh** [comment]
> Then when sending your campaign, add "X-SMTPAPI" {"unique_args": {"campaign_uuid": campaign_uuid }} to your header

We can't add a vendor specific header into the core though. Is Sendgrid completely ignoring the `X-Listmonk*` headers in the bounce reports?

**Comment by charlesmudy** [comment]
I understand so maybe instruction for those using Sendgrid.

Not sure how relevant `X-Listmonk*` is ... The webhook response from Sendgrid without the extra header parameter:

`
[{"ip": "192.254.118.000", "tls": 0, "type": "blocked", "email": "epjgonserm@sina.com", "event": "bounce", "reason": "550 Too many recipients.", "status": "550", "smtp-id": "<1667651292874015763.812611.4383912277526945455@mail.XXXXXXX.com>", "timestamp": 1667730535, "sg_event_id": "Ym91bmNlLTI4LTIzNDAwNzU3LXo5bG1iRVRiU3ZTYVctTklXNVhPeGctMA", "sg_message_id": "z9lmbETbSvSaW-NIW5XOxg.filterdrecv-595fc4d6bf-hnhsz-1-636656DC-3D.0", "bounce_classification": "Technical"}]
`

You can see it's missing the `campaign_uuid` which is required by Listmonk? But with the header parameter as stated above, you will get this:

`
[{"email": "lily@email.com", "event": "processed", "send_at": 0, "smtp-id": "<1667736340123837667.935625.4712866261918458050@mail.XXXXXXXX.com>", "timestamp": 1667736340, "sg_event_id": "cHJvY2Vzc2VkLTIzNDAwNzU3LWN5bTVsdlZ3U0llamhWY2IzRUtBa3ctMA", "campaign_uuid": "7e056357-c605-44d5-9bb6-218f8957e189", "sg_message_id": "cym5lvVwSIejhVcb3EKAkw.filterdrecv-6d7758597-tlzwr-1-6367A314-2F.0"}]
`
Which then makes sense for Listmonk. Read this https://docs.sendgrid.com/for-developers/sending-email/building-an-x-smtpapi-header

**Comment by charlesmudy** [comment]
Yes I saw the setting for that but apparently it doesn't see it if this is not sent `X-SMTPAPI` with the necessary objects. Can we add it here?

`
h := textproto.MIMEHeader{}
h.Set(models.EmailHeaderCampaignUUID, msg.Campaign.UUID)
h.Set(models.EmailHeaderSubscriberUUID, msg.Subscriber.UUID)
`

**Comment by knadh** [comment]
`X-SMTPAPI` is SendGrid specific and we shouldn't be hard coding it into listmonk.

Not ideal, but this can be set for each campaign manually in Campaign -> Custom headers field.
