### ISSUE TITLE
AxiosError — Frequent error when querying listmonk dB.

### ISSUE THREAD

**Issue by Mattifyed** [knadh/listmonk#1019]
![image](https://user-images.githubusercontent.com/56337463/200763487-35d72466-a211-4a1b-b458-4c4a4bdf47bf.png)

I frequently see this error when loading listmonk pages that query the subscriber dB. For example the /campaigns page and the /subscribers page.

**Comment by knadh** [comment]
`504` = timeout. Large amounts of data, queries slowing down. Will investigate this.

**Comment by profmatheuspassos** [comment]
Same happening here.

**Comment by knadh** [comment]
@profmatheuspassos how many subscribers and campaigns do you have, roughly?

**Comment by profmatheuspassos** [comment]
Almost 8k subscribers, 20 campaigns (19 finalized, 1 draft).

Also, I keep receiving the “EOF” and “time out” erros, unfortunately :/

**Comment by knadh** [comment]
Ah, the DB bottleneck should only be visible when there are several million subscribers.

EOF and timeout is on sending e-mails or page loads? EOF typically happens when the SMTP server abruptly terminates connections. If that's the case, you could try adjusting the send rates in Performance setttings.

**Comment by profmatheuspassos** [comment]
Sorry - I wasn’t clear on my previous answer :P

The axious message usually appears when I open the “Campaign/all campaigns” panel, and only after I start a new campaign.

EOF and time out are happening while sending e-mails - although it was with 10 concurrency and 10 message rate, and 100 batch size. In SMTP settings I use 10 max connections, 2 retries, 2 min idle timeout and 5 min wait timeout.

Using listmonk via Cloudron (automatic install).

**Comment by profmatheuspassos** [comment]
Just as a follow-up.

Just ran a campaign to a list with 809 subscribers.

1) As soon as I started the campaign, I noticed the “axios” error again (but wasn’t able to print screen).

2) While running the campaign, here are some of the logs. The campaign stopped frequently (because I asked it to do so, in settings). I was following the campaign and it seems that as soon as listmonk receives an error, it stops sending the e-mails. Please note that before I took these prints with the settings, the max erros was set up to 100, but it stopped sending e-mails although the campaign continued “alive”.

￼￼￼￼￼￼

Thanks!

**Comment by knadh** [comment]
The logs you tried to embed in the above comment didn't come through.

**Comment by profmatheuspassos** [comment]
Sorry - here it goes

![Screenshot 2023-02-27 at 12 25 13](https://user-images.githubusercontent.com/40068795/221546668-3f07ae2a-95a9-4e35-a734-b2af70ed0220.png)
![Screenshot 2023-02-27 at 12 27 21](https://user-images.githubusercontent.com/40068795/221546682-49e144b5-7465-4200-ad02-0d500a8294dc.png)
![Screenshot 2023-02-27 at 12 29 37](https://user-images.githubusercontent.com/40068795/221546688-8fd8de29-8d3a-49e7-bd23-8f3a2eeffbfb.png)
![Screenshot 2023-02-27 at 12 31 20](https://user-images.githubusercontent.com/40068795/221546691-df57c5d2-e1ab-4645-b0c8-3505c3f8fc59.png)
![Screenshot 2023-02-27 at 12 31 24](https://user-images.githubusercontent.com/40068795/221546693-cba52da4-2f21-45d6-968f-5a4145f15d1b.png)
![Screenshot 2023-02-27 at 12 32 57](https://user-images.githubusercontent.com/40068795/221546695-e89c1841-72d5-422e-9c44-3e6a72374572.png)

**Comment by knadh** [comment]
This is definitely a network issue. EOF, timeout, "connection reset by peer". It could be the upstream or a firewall or something else in between.

**Comment by profmatheuspassos** [comment]
Strange - it's all on the same server (using cloudron)

**Comment by knadh** [comment]
Maybe something to do with the Docker environment (assuming that's what it is).

**Comment by gramakri** [comment]
I am the author of the Cloudron package. @profmatheuspassos Have you already tried giving PostgreSQL more memory (under Services -> PostgreSQL -> bump memory limit) and the app as well (in the Resources view) ? Otherwise, I can invesitgate if there is an issue in the Cloudron package itself.

**Comment by gramakri** [comment]
@Mattifyed are you also on Cloudron?

**Comment by knadh** [comment]
Don't think it's a memory issue. EOF, "connection reset by peer" indicate the upstream connection being closed abruptly by the SMTP.

**Comment by profmatheuspassos** [comment]
@gramakri I increased the memory to 512 (instead of the standard 256). But haven't changed the Postgre more memory. Just did that (to 1GB) and I'll run another campaign in the same format in the next 2-3 days, then come back to you if the problem continues. Many thanks!

**Comment by profmatheuspassos** [comment]
Hey guys, this is a follow-up: The problem was with my e-mail server. I switched to smtp2go, and it worked fine. I even changed the performance settings to the original ones, and "voilà" everything worked as it should. Thanks for your attention!
