### ISSUE TITLE
Some config values are not read from environment variables

### ISSUE THREAD

**Issue by mawalu** [knadh/listmonk#102]
I tried to configure listmonk using env variables but some of them seemed to be ignored. The SMTP server config worked but `LISTMONK_from_email` was always set to the default value so my server denied sending the messages. `config.js` also contained the default values for all settings although I have overwritten them. 

Switching from env variables to a config file fixed the problem.

**Comment by knadh** [comment]
Looks like the Wiki page was wrong. The correct env variable should be `LISTMONK_app__from_email`. Updated all keys here: https://github.com/knadh/listmonk/wiki/Configuration
