### ISSUE TITLE
Opt-in confirmation email subscribed to list is empty

### ISSUE THREAD

**Issue by kongeor** [knadh/listmonk#1022]
**Version:**
 - listmonk: [v2.2.0]
 - OS: Debian

**Description of the bug and steps to reproduce:**
1. Create a subscription list
2. Add a user to this subscription list
3. Send a opt-in confirmation email. The subscription list appears empty.

**Screenshots:**
I have added a user to a subscription list and sending an opt-in confirmation email from this screen:
![image](https://user-images.githubusercontent.com/2270851/201527109-feb73139-ca0e-48db-803d-268f2ad8862f.png)

The email the user receives appears like this:
![image](https://user-images.githubusercontent.com/2270851/201527219-ebea50e4-a602-49a2-aa24-c2cc8b512cb4.png)

The subscription form is displaying the list propertly:
![image](https://user-images.githubusercontent.com/2270851/201527250-41d53f3c-d850-4cef-90d7-7fefdb48ba1b.png)

**Comment by kettenbach-it** [comment]
Same here

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/issues/1011

This was fixed recently and will be available in v2.3.0 coming out this week. Thanks!
