### ISSUE TITLE
View In Browser / Sharing Campaigns

### ISSUE THREAD

**Issue by elronalds** [knadh/listmonk#1023]
Is it possible to view a campaign in the web browser, similar to the View in Browser link at the bottom of the emails.  I would like this to not have the unsubscribe link on the web page verson.  Basically if I share that link to someone that isn't subscribed then they would be able to unsubscribe the UID which the link contains.  

Would it also be possible to have a link that always shows the latest campaign that has been sent?  Something like `https://[listmonk-installation-url]/campaign/latest` This could then load the latest campaign without any unsubscribe links that would remove people form the list.

**Comment by knadh** [comment]
This is done and will be available in the new release this weel: https://github.com/knadh/listmonk/issues/745
