### ISSUE TITLE
Allow import "email only" blocklist

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1024]
**Is your feature request related to a problem? Please describe.**

I have a blocklist of emails I need to import. Some have names, others don't. When I imported the list it skipped the ones without a name. Names aren't necessary for block lists, so many people may not have the names. 

**Describe the solution you'd like**

I could create fake names, but it would be nice to be able to import (or just copy-paste) a list of emails.

**Comment by knadh** [comment]
Name can't be an optional field because of the reasons discussed here: https://github.com/knadh/listmonk/issues/967

**Comment by tricoos** [comment]
Well, then you can simply and automatically set the name to UNDISCLOSED and the import of the blocked contacts will work. Now facing the same issue, unfortunately. It just doesn't make sense when importing blocklist contacts to store more than required from a privacy perspective (think GDPR).
