### ISSUE TITLE
Open rates are inaccurate

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1025]
**Version:**
 - listmonk: latest
 - OS: I'm on Windows 10 x64, Listmonk is installed on latest version of Ubuntu server on AWS EC2. 

**Description of the bug and steps to reproduce:**
As soon as I send a campaign, the open rate hits 50% within a minute or two. If working "normally" the open rate should start off at 10% or lower, and throughout the next 24 hours rise to around 60-70% as people open their emails. 

I've been recently testing lots of other email programs such as Mailerlite, Getresponse, Convertkit, Sender, SendPulse, Mergo, and more. They all work "normally". But I experienced this same problem with Sendy (which also sends through AWS SES), which is what lead me to want to see if Listmonk has the same issue (it does). 

I also read about this on the Mailwizz (another SES UI) forums:
- 2021 https://forum.mailwizz.com/threads/inaccurate-open-tracking.7557/page-2
- 2022 https://forum.mailwizz.com/threads/incorrect-open-rates-are-the-single-biggest-issue-plaguing-mailwizz.8111/ 

And it sounds like they **may** have fixed it by blacklisting some bot IPs that automatically scan emails & links. I have yet to test Mailwizz to confirm though. 

---

EDIT: and to clarify, I'm referring to the "more accurate" open rate & percentage listed on the campaign analytics page, not the less accurate "views" listed on the "all campaigns" page.

**Comment by MaximilianKohler** [comment]
> If bots are rendering messages and loading the image (not sure if that's a common scenario), it'll be counted as a legitimate hit.

So can you try blocking known bots? For some reason, the vast majority of email marketing providers have "normal open rates" and this is only an issue with the few SES UI options. 

Maybe it's because of the top comment here? https://forum.mailwizz.com/threads/inaccurate-open-tracking.7557/page-2

> Mainly because if you're sending through smtp, you can't collect this type of info. 

Maybe this "bgsound" comment is useful? https://forum.mailwizz.com/threads/inaccurate-open-tracking.7557/page-2#post-47358

**Comment by knadh** [comment]
Not feasible to integrate bot blocking in listmonk. It's outside the scope of the project. You can run some sort of a web application firewall (WAF) or proxy in front of listmonk that does this.

**Comment by ajoslin** [comment]
So a firewall rule on Cloudflare with block known bots could work?

https://developers.cloudflare.com/firewall/known-issues-and-faq/#caution-about-potentially-blocking-bots

🤔

**Comment by MaximilianKohler** [comment]
>So a firewall rule on Cloudflare with block known bots could work?

Based on the discussions I linked to that doesn't seem like a valid option. Quote:

> in my case, when i opened the email personally, not just that I got google's IP address, but i also got google's image proxy user agent.
> 
> So while I did the open, a legit open, there is no indication here that I did it, it's just the google bot.
