### ISSUE TITLE
skip certificate verrification

### ISSUE THREAD

**Issue by ebartz** [knadh/listmonk#103]
Is there something that I can set in the config so that liskmonk ignores selfsigned certificates of my mailserver?

```
2020/05/16 13:04:04 manager.go:292: error sending message 'Confirm subscription': x509: certificate signed by unknown authority
```

**Comment by knadh** [comment]
Not currently, but this is possible. Will add this in the upcoming release along with the new SMTP pool that just got integration. ~2 days.

**Comment by knadh** [comment]
Apologies. Was unable to include this in [v0.6.0-alpha](https://github.com/knadh/listmonk/releases/tag/v0.6.0-alpha).

**Comment by knadh** [comment]
`tls_enabled, tls_skip_verify` are available in [v0.6.1-alpha](https://github.com/knadh/listmonk/releases/tag/v0.6.1-alpha).

**Comment by ebartz** [comment]
Thanks @knadh for working on this so quickly!

Actually this does not yet solve my problem. With the following settings:
``` toml
tls_skip_verify = false
tls_enabled = true
```

I still get this message:
```
2020/05/18 13:56:03 manager.go:289: error sending message 'Confirm subscription': x509: certificate signed by unknown authority
```

**Comment by knadh** [comment]
`tls_skip_verify` should be true in your case. You want to skip the verification of the self-signed certificate.

**Comment by ebartz** [comment]
Yep it was me doing it wrong. Was so excited that you updated it that fast that I mixed it up...

After another test it works well for me!

Thanks for putting work into this project and opensouring it!
