### ISSUE TITLE
Spurious "Unsubscribe" and "View in browser" links in archive

### ISSUE THREAD

**Issue by Sjors** [knadh/listmonk#1031]
Post on the archive page should not have an unsubscribe button. The "View in browser" link also doesn't make sense there.

<img width="654" alt="Scherm­afbeelding 2022-11-16 om 19 58 47" src="https://user-images.githubusercontent.com/10217/202269424-115833c9-035e-46a5-933d-75f4de2123ee.png">

Example archived post:
https://list.btcwip.com/archive/45b21ec6-ac66-4001-9066-1025b30d2723

**Comment by knadh** [comment]
You can clone your main template, remove the link, and use that template on archives. That's why we've made templates selectable on archives so that they can act completely differently from e-mail templates.
