### ISSUE TITLE
See All and Subscribe buttons on archived post page

### ISSUE THREAD

**Issue by Sjors** [knadh/listmonk#1032]
When viewing a post on the public archive, it would be great to have a button to subscribe as well as a link back to `/archive`.

**Comment by knadh** [comment]
Archives render custom templates that you select. You can add such a button on your template.

**Comment by Sjors** [comment]
I tried adding `SubscribeURL` in the template, but that didn't work:

<img width="1137" alt="Scherm­afbeelding 2022-11-17 om 11 18 45" src="https://user-images.githubusercontent.com/10217/202420503-9cd4bf1d-e010-493d-a1b5-2ca60afdf353.png">

However a hardcoded link to the subscription page works fine.

**Comment by Sjors** [comment]
Update: `{{ OptinURL }}` is the right one.
