### ISSUE TITLE
Social media preview for archived posts

### ISSUE THREAD

**Issue by Sjors** [knadh/listmonk#1035]
Now that public archive posts exist, these pages can be improved to make them easier to share.

There's a bunch of sites where you can preview what it looks like, e.g. https://socialsharepreview.com/

In particular I would suggest [Open Graph](https://ogp.me) tags.
1. Campaign title. This might Just Work(tm) once #1034 is implemented, otherwise it needs the `og:title` meta tag.
2. `og:type`: `article` is probably a good start
3. First paragraph, maybe capped at 200 characters, should go into `og:description`
4. `og:image` for the first image of the post (if any)

Specific social networks also have their own tag, not sure how many you want to support.

Maybe add a way for users to add more `og` tags (wide wide, or article specific).

**Comment by knadh** [comment]
You can add all of this in a template and use that on the archive page. That's why we've made the archive template selectable :)

**Comment by Sjors** [comment]
I'll give that a try and open a new ticket is something specific is missing.

**Comment by Sjors** [comment]
I ended up with this:

```html
<meta property="og:title" content="{{ .Campaign.Subject }}" />
<meta property="og:type" content="article" />
<meta property="og:description" content='{{ regexReplaceAll "#(.|\n)*" (abbrev 200 .Campaign.Body) "" }}' />
<meta property="og:image" content='{{ default "https:// (fallback image)" .Subscriber.Attribs.Image }}' />
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content='{{ default "https:// (fallback image)" .Subscriber.Attribs.Image }}' />
<meta name="twitter:site" content="@me">
<meta name="twitter:title" content="{{ .Campaign.Subject }}">
<meta name="twitter:description" content='{{ regexReplaceAll "#(.|\n)*" (abbrev 200 .Campaign.Body) "" }}'>
```

This requires setting an `image` attribute campaign that has an image (otherwise it picks the fallback):

```json
"attribs": {
        "image": "https://....jpeg"
    }
```

This involves duplicating the URL, because afaik you can't render an image with `![]({{ .Subscriber.Attribs.Image }})` in the markdown. But that's not the end of the world.
