### ISSUE TITLE
error adding subscriptions by query: sql: converting argument $3 type: unsupported type []int, a slice of int

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1037]
**Version:**
 - listmonk: latest
 - OS: Listmonk is on ubuntu

**Description of the bug and steps to reproduce:**
* go to lists
* click on the number of subscribers in a list
* select all in list
* click Manage lists 
* add them to another list
* error pops up at the top `error adding subscriptions by query: sql: converting argument $3 type: unsupported type []int, a slice of int`

**Screenshots:**
If needed.

**Comment by knadh** [comment]
This was fixed in https://github.com/knadh/listmonk/issues/897.

**Comment by MaximilianKohler** [comment]
It was fixed in August, but I just installed the latest version and I'm experiencing it?

**Comment by knadh** [comment]
`v2.3.0` comes out this week.
