### ISSUE TITLE
{"message":"Invalid email."}

### ISSUE THREAD

**Issue by chestnutbak** [knadh/listmonk#1038]
curl -F 'data => {"email":"info@johnsmith.com","name":"John Smith","lists":[11],"status":"enabled"}' -u 'user:pass' https://mailing.mydomain.com/api/subscribers

This curl and any other attempt to communicate with the API returns {"message":"Invalid email."}.

Any thoughts on what I need to be looking at to get this working correctly?
Thanks!

**Comment by knadh** [comment]
Hi @chestnutbak. You've to send a JSON request. Please refer to the example in the docs: https://listmonk.app/docs/apis/subscribers/#post-apisubscribers
