### ISSUE TITLE
message.html - separate into more templates

### ISSUE THREAD

**Issue by LK-ML** [knadh/listmonk#1040]
**Is your feature request related to a problem? Please describe.**

Hi - when customizing Listmonks templates, all is fine except the message.html. It used for different functions - to request double opt-in confirmation, to confirm an opt-in or an opt-out. This makes customization impossible and limits Listmonks use.

**Describe the solution you'd like**

Would you mind considering separating message.html into different templates as you did with the other templates? 
Example: a double-optin-request.html, a optin-success.html, a opt-out-sucess.html? :)

**Comment by knadh** [comment]
That would be difficult to maintain, unfortunately. `message.html` is a generic template that's used in a number of places to show arbitrary success/error messages.

There is one hack you could add. Add conditional templating based on the page title (.Data.Title) or message (.Data.Message).

`if eq .Data.Title (L.T "public.subConfirmedTitle") ...`

**Comment by LK-ML** [comment]
Thank you - that works for me. Great suggestion :).
