### ISSUE TITLE
German Translation (formal)

### ISSUE THREAD

**Issue by LK-ML** [knadh/listmonk#1044]
Not familiar with pull requests yet - so as per your request on the translation site, I am using an Issue. Itranslated the frontend text to use formal German ("Sie" instead of "Du").  https://github.com/LK-ML/listmonk-formal-german

Explanation: The current translation is using the informal translation, which is not appropriate for any more formal relationship in a professional setting.

**Comment by knadh** [comment]
Hi @LK-ML. Please see refer to this older issue: https://github.com/knadh/listmonk/pull/593

**Comment by LK-ML** [comment]
Understood - sorry for not checking out the issues before writing :).
