### ISSUE TITLE
[Bug] Subscriber Id is null in postgreSQL in link_view and campaign_views table.

### ISSUE THREAD

**Issue by niraj-ranjan-comprinno** [knadh/listmonk#1047]
**Version:**
 - listmonk: [eg: v2.2.0]
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**
In table link_view and campaign_views, There is column call subscriber_id which is null.

**Screenshots:**

<img width="986" alt="Screenshot 2022-11-21 at 7 33 45 PM" src="https://user-images.githubusercontent.com/64660855/203119071-901af378-dcbc-4ff3-a5e1-b7760208c9bc.png">

**Comment by knadh** [comment]
Hi @niraj-ranjan-comprinno. Individual subscriber tracking is disabled by default in `Settings -> Privacy`. Enabling that will start recording subscriber IDs.

**Comment by niraj-ranjan-comprinno** [comment]
Wow!! Thank you so much for quick reply.
