### ISSUE TITLE
issues after restoring database

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1048]
**Version:**
 - listmonk: v2.2.0
 - OS: ubuntu

**Description of the bug and steps to reproduce:**
* Backed up listmonk with this command: `pg_dump -U listmonk -h localhost -p 9432 listmonk > pglistmonkdb.sql`
* Wiped my EC2 drive, reinstalled ubuntu, docker, listmonk, etc.
* Ran these commands to restore the DB:

```
psql -h 127.0.0.1 -p 9432 -U listmonk
drop schema public cascade;
create schema public;
\q
psql -h 127.0.0.1 -p 9432 -U listmonk -W listmonk < pglistmonkdb.sql
```

Everything LOOKS normal. Except the analytics pages all say 100% instead of 70-80%.

I tried to send a new campaign and it didn't send. I went to the SMTP settings to test and got an error (see screenshot) suggesting there is still some default data left behind even though everything **looks** back to normal. 

**Errors:**

```
2022/11/21 17:26:58start processing campaign (Thanks 05-800)
2022/11/21 17:27:03error sending message in campaign Thanks 05-800: subscriber 4bc1ef99-3020-4bcf-bff7-5057625a257d: dial tcp 172.67.156.222:25: i/o timeout

2022/11/21 17:33:51error sending message in campaign Thanks 05-800: subscriber 71520918-01c0-416d-aae5-4f5980998f93: timed out waiting for free conn in pool

2022/11/21 17:39:42error sending SMTP test (Test connection): 554 Message rejected: Email address is not verified. The following identities failed the check in region US-WEST-1: noreply@listmonk.yoursite.com, listmonk <noreply@listmonk.yoursite.com>
```

**Screenshots:**

![smtp err](https://user-images.githubusercontent.com/3606996/203128330-7b5c681b-561c-434e-8c69-29a27457924a.png)
![general](https://user-images.githubusercontent.com/3606996/203128340-dbd98453-0f22-4bb9-86f2-aa55d89b99eb.png)

**Comment by MaximilianKohler** [comment]
I created a new DB export with `pg_dump -U listmonk -h localhost -p 9432 listmonk > pglistmonkdb.sql` and it has no search result for "noreply@listmonk.yoursite.com". So Listmonk isn't getting that from the DB.

**Comment by knadh** [comment]
You can search the listmonk codebase for the string. Apart from installation script and UI placeholders, it doesn't appear anywhere else. I don't know where this is coming from.

**Comment by MaximilianKohler** [comment]
Seems to be working now. Possibly `sudo docker-compose restart app db nginx` solved it. Perhaps that command is required after restoring the postgres DB.
