### ISSUE TITLE
Subscription form to save other information as attribs

### ISSUE THREAD

**Issue by malv007** [knadh/listmonk#1051]
Hi,

I can see that the subscription form can be customized, but I am not sure it is possible for the subscription form to persist information other than the name, email, and lists.

Is it possible to save other attributes? I was thinking of having in the form the postal code where the subscriber lives, so I can collect that information, store it the "attribs" JSON, and then use it to segment the subscribers.

Would you consider to add this as an enhancement in case this isn't possible already via template customization?

Thanks so much!

**Comment by knadh** [comment]
Hi @malv007. Saving attributes from the public form without proper backend validation is dangerous. You can create your own form+backend by integrating with the [listmonk APIs](https://listmonk.app/docs/apis/subscribers/).

**Comment by NessDan** [comment]
I came across this searching for something I'm trying to do.

Was this related to adding custom attributes via a programmatically added email? e.g.

```js
  const formData = new FormData();

  formData.append("email", email);
  formData.append("l", "0a0d8ba4-a10a-4af7-9f6f-630d23f6c1cd"); // TEST
  formData.append("attribs", JSON.stringify({ test: "test" })); // Doesn't add custom attribute ☹️
  formData.append("name", "");
  formData.append("nonce", "");

  let response;

  response = await fetch("https://mail.keyboard.gg/subscription/form", {
    method: "POST",
    body: formData,
  });
```

**Comment by knadh** [comment]
The public API doesn't support arbitrary attributes for security reasons. If you want to store custom attribs with a subscription, you should use the authenticated `/api/subscribers` endpoint behind your application.
