### ISSUE TITLE
Short Subscriber names, fails to include in Subscriber.Name tag or find in search

### ISSUE THREAD

**Issue by cb3inco** [knadh/listmonk#1052]
**Version:**
 - listmonk: [v2.2.0]
 - OS: Ubuntu with Docker Community Edition - 20.10.21

**Description of the bug and steps to reproduce:**
It appears that short names such as Al (short for Albert), when used are being truncated when using the {{ .Subscriber.Name }} option in a template and reverts to using the Lastname only. 

For example, if I use **Al Jenkins** as a subscribers name, the email sent will say 'Dear Jenkins'. 

Additionally if I try to search for the name **Al** in the subscription list it won't find any results until I start including the last name.

**Screenshots:**

Subscriber Name:
![image](https://user-images.githubusercontent.com/14948644/203472103-9873f12e-7f61-4250-bc90-b0719e648d9a.png)

Sent Email:
![image](https://user-images.githubusercontent.com/14948644/203471944-d5cf7a4d-9404-4f99-8c80-81f4994e57d9.png)

Modified username to include 3 characters (Alb instead of Al)
![image](https://user-images.githubusercontent.com/14948644/203472201-dfecd2f2-dd33-4e2f-8d78-888a985ca835.png)

**Comment by knadh** [comment]
The `.FirstName()` and `.LastName()` shortcut functions are designed to specifically do this. The (imperfect) logic excludes initials.

You can instead use `.Subscriber.Name` to get the full name, or use one of the [Sprig string functions](http://masterminds.github.io/sprig/strings.html) on `.Subscriber.Name` to transform it any way you want.

**Comment by cb3inco** [comment]
I should mention that I am using that tag in my template. I misspoke that I was using the {{ .Subscriber.Name }} option.

![image](https://user-images.githubusercontent.com/14948644/203476796-7128bdf0-98dd-4121-8d3f-c1e11790a754.png)

**Comment by knadh** [comment]
> It seems the .FirstName() can't handle a name shorter than 3 characters.

Yeah.

> The .FirstName() and .LastName() shortcut functions are designed to specifically do this. The (imperfect) logic excludes initials.

We can make it two letters, but then initials might show up as the first name. As I said, you can use `.Subscriber.Name` with one of the Sprig functions to render it the way you want.

**Comment by cb3inco** [comment]
Ok. Thanks. I'm not sure how to do that, but I'll have to look into one of these days.

**Comment by knadh** [comment]
`{{ index (splitList " " .Subscriber.Name) 0 }}`

^ Splits the name by a space and prints the first chunk (0).
