### ISSUE TITLE
535 Authentication Credentials Invalid

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1053]
Providing a fix for anyone who searches this issue. Amazon's setup for this is absolute trash and totally misleading and unintuitive. You should use the "send feedback" option to castigate them. 

https://stackoverflow.com/questions/45653939/amazon-ses-535-authentication-credentials-invalid-trying-to-rotate-access-key

You can't rotate access keys. You have to create a new SMTP user, or use some script to transform the access keys.

**Comment by tristam15** [comment]
I read this but I still don't understand it.

Are we supposed to use the access keys as username and password in the SMTP section of Listmonk or are we supposed to use the console login ID and password? 

I've spent about 2 hours trying to figure this out and I am moving in circles. Nothing clear yet.

**Comment by MaximilianKohler** [comment]
>Are we supposed to use the access keys as username and password in the SMTP section of Listmonk or are we supposed to use the console login ID and password?

Yes, there are tutorials in the listmonk docs.

**Comment by Midhunnnk** [comment]
Thanks for the hetzner headsup, i was doingport 465, for hetnzer server use port 2465 thanks for tip
