### ISSUE TITLE
Enhancement: Delete Campaigns

### ISSUE THREAD

**Issue by cb3inco** [knadh/listmonk#106]
The ability to delete campaigns, particularly test ones would be great. 

Just wanted to submit a feature request.

**Comment by knadh** [comment]
It was a conscious decision to disallow deleting of campaigns that have already been processed (as they've already created external side effects and also serve like audit-logs). The super admin can of course be allowed as they may have DB access anyway. The user/permission system has not been built yet, but I guess this can just be added now without waiting for that.

Will add to the next release. Thanks.

**Comment by knadh** [comment]
This is merged to master https://github.com/knadh/listmonk/commit/f81d75a787ca163feb949de20afa0784c4ac8ee5. Available in the upcoming release [v0.8.0](https://github.com/knadh/listmonk/milestone/1).
