### ISSUE TITLE
Unauthorized access on public archive when clicking links with TrackLink configured

### ISSUE THREAD

**Issue by elronalds** [knadh/listmonk#1067]
**Version:**
 - listmonk: v2.3.0
 - OS: Docker

**Description of the bug and steps to reproduce:**
When using the latest Linkmonk 2.3.0 with the public archives, if the template contains links with link tracking then when clicking those links they require HTTP authorization, e.g. link is `https://[hostname]/link/[linkUUID]/[campUUID]/`. 

What's the expected behaviour for this and to have TrackLinks working in the public archives without triggering the basic auth?

**Comment by elronalds** [comment]
Clicking the links from the `MessageURL` address within the actual email through the View In Browser option works fine.  Just they aren't working from the archive pages.

**Comment by knadh** [comment]
Hi @elronalds. Apologies for the late response. The default campaign template isn't meant to be used as the archive template. Archive template should not have the unsubscribe link, "view message" link etc. You can clone your default template, remove the links, and use it as the archive template.

I vividly remember adding a default template specifically for this in the install + upgrade routines, but going through the commits, I can't find them. This is either a false memory or I never merged a feature branch. Will add a default template in the next version.

Thanks.

**Comment by elronalds** [comment]
@knadh Yes, I have a custom template for the archive with those links removed.  This error happens on links in the campaign content that have the TrackLink configured within the message content.  I think the archive should be bypassing the TrackLink.

The issue only occurs when the Individual subscriber tracking setting is enabled, when that setting is disabled the links work fine.  I guess Individual subscriber tracking should be disabled on archive pages.
