### ISSUE TITLE
Subscription form doesn't notify the admin of new subscriber

### ISSUE THREAD

**Issue by charlesmudy** [knadh/listmonk#1071]
**Is your feature request related to a problem? Please describe.**
When people subscribe through the subscription form, the admin doesn't get any notification for new subscriber, you just have to keep checking the dashboard.

**Describe the solution you'd like**
It would be ideal to send email notification to the admin or any given email that there is a new subscriber. I think this is standard for most emailing platforms.

**Comment by knadh** [comment]
Maybe this can be a part of the [webhooks proposal](https://github.com/knadh/listmonk/issues/658) which can be used to trigger alerts. Adding notifications specifically for subscription doesn't seem important.
