### ISSUE TITLE
Cannot save new template : "The placeholder {{ template "content" . }} should appear exactly once in the template." error

### ISSUE THREAD

**Issue by egaillot** [knadh/listmonk#1075]
**Version:**
 - listmonk: [eg: v2.3.0]
 - OS: Linux (Debian)

**Description of the bug and steps to reproduce:**
- Create a new template from scratch
- Copy-paste the [Example Template from documentation](https://listmonk.app/docs/templating/#example-template)
- Hit "Save" button
- An error message appears on top of page saying `The placeholder {{ template "content" . }} should appear exactly once in the template.` – while it does appear once and only once in the pasted text.

Also, maybe related or not related, when hitting the "Preview" button, some (sort of) unrelated text appears.

**Screenshots:**
<img width="1036" alt="Screenshot 2022-11-30 at 20 26 40" src="https://user-images.githubusercontent.com/105624/204891486-d7940fb4-026b-42fb-ada0-de03f4360b42.png">
<img width="1036" alt="Screenshot 2022-11-30 at 20 27 16" src="https://user-images.githubusercontent.com/105624/204891494-d3e3890d-5493-4b9d-b3af-e2c256c42d50.png">

**Comment by egaillot** [comment]
Update: The preview seems to describe the data representing another template I have – which I cannot update despite Listmonk confirmation messages. (This is actually what got me onto the path of creating a new template, with no luck.)

**Comment by knadh** [comment]
Sorry, just seeing this now. Were you able to resolve this? Can you paste the template's exact raw source here? Confused by this because if this were the case, template creation wouldn't work outright for anyone.

**Comment by egaillot** [comment]
The problem sorted out by itself… not sure exactly what happened 😓
