### ISSUE TITLE
TrackLink not working inside range block

### ISSUE THREAD

**Issue by malv007** [knadh/listmonk#1077]
**Is your feature request related to a problem? Please describe.**
The golang function {{ TrackLink }} doesn't seem to be working when used inside a "range" block. I think there is a regular expression that updates the TrackLink invocation to add a second parameter ".", but because we are inside a "range" block the "." is referencing something that the function isn't expecting.

We need to use TrackLink inside a range, so we can create trackable links for urls that we have inside an array.

**Describe the solution you'd like**
I am not sure what would be the best solution for this. Perhaps have two TrackLink functions, one that doesn't get replaced by the regular expression (TrackLinkInt ??), and the other that gets replaced by the regular expression ( TrackLink would get replaced with TrackLinkInt). That way we would have more control over what parameters to pass.

Thanks!

**Comment by knadh** [comment]
Sorry, missed this. The RegEx expands `{{ TrackLink "https://link" }}` to `{{ TrackLink "https://link" . }}`.

If you use `{{ TrackLink "https://link" . }}`, the RegEx doesn't kick in. However, the `.` has to refer to the `Message` context internally. Outside your range, you can maybe do`$m := .` and then in the loop, something `{{ TrackLink "https://link" $m }}`.

**Comment by malv007** [comment]
Thanks for looking into this! We tried your suggestion, but it causes the error below, it looks like the function isn't expecting that extra argument.


campaigns.go:445: error sending test message: code=404, message=Error rendering message: template: content:13:68: executing "content" at <TrackLink>: wrong number of args for TrackLink: want 2 got 3

________________________________

**Comment by knadh** [comment]
Can you share the exact snippet you're trying?

**Comment by malv007** [comment]
Here it is. Thanks again!

{{ $msg := . }}

<p>Hi {{ .Subscriber.Name }}</p>

<dl>
{{range $section := .Subscriber.Attribs.data}}

{{ $url := $section.SourceUrl }}
<dt><b>{{.CompanyNumber}}</b> {{.CompanyName}}</dt>
<dd>{{.EventTitle}} <a href="{{ TrackLink $url $msg }}">Ver fuente</a></dd>

{{end}}
</dl>

And this is the error we get when testing the campaign, same error will happen if we actually start the campaign:

[cid:973d6d4b-fde9-4a6c-a62e-6126ed21e846]

________________________________

**Comment by malv007** [comment]
Hi @knadh ! Sorry to bug you again, I am sure you are a very busy person. Did you get a chance to take a look at the snippet? Are we doing anything wrong in that go script? We aren't go experts by any stretch of the imagination
