### ISSUE TITLE
Unsubscribe rates are suspiciously high

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1078]
I've been using other email marketing and mail merge platforms for a long time to send responses to people. I'm sending the exact same emails to the same type of lists. With Listmonk the unsubscribe (full blocklisted) rate is around 20-25 per 1000. With the others it was around 1-8 per 1000. 

I tested Sendy for a brief period before Listmonk, and I sent the campaigns to myself too (same with Listmonk). I noticed that I erroneously got unsubscribed once automatically. Their support said it was due to "one-click unsubscribe headers" and the solution was "_Double opt-out_". 

I think Listmonk's "_Unsubscribe from all future e-mails_" checkbox works similarly. I also do *not* have `Include List-Unsubscribe header` enabled in Listmonk's options. I noticed that gmail automatically started putting an "unsubscribe" header in one of the emails I receive campaigns to, but I've clicked it multiple times and it brings me to the same/normal Listmonk unsub page where I have to confirm to unsub. 

I'm wondering if this might be related to #1025 bot issue, since I guess that's what the cause was with Sendy (?). It seems unlikely that bots would continue clicking things in external links, but I really have no idea. 

The unsubscribe links in the mail merge platform I used have zero confirmation and I didn't experience this with them. 

I searched Mailwizz and only found this 
>I'm repeatedly ghost unsubscribing from my own lists https://forum.mailwizz.com/threads/im-repeatedly-ghost-unsubscribing-from-my-own-lists.5572/

I found this on Mautic 
>Anyone know why outlook.com email are automatically unsubscribing members https://forum.mautic.org/t/anyone-know-why-outlook-com-email-are-automatically-unsubscribing-members/25025/6 

which says it's Outlook users. But looking at my unsub lists there are plenty of gmail and others. 

Also found this 
>perhaps some spam filters and so on accidentally unsubscribe my users https://forum.mautic.org/t/possible-unsubscribe-error/24786/2 

which covers the same "double opt out" rec. 

---

Oh wow, I just realized that it's largely or solely because Listmonk counts bounced and unsubbed as the same... *facepalm*. I guess I'll still submit this to save someone else time if they search for this in the future...

Glad that dawned on me before scrolling through 300 more https://github.com/mautic/mautic/issues?q=is%3Aissue+unsubscribe search results...

**Comment by Seneral** [comment]
I think this is still an issue since soft bounces (e.g. auto-replies when somebody is absent) should not count as a blacklist.
I'm using Amazon SES and their test emails, and the auto-reply one gets blocklisted, which should not happen. My current solution would be to rely on amazons supression list for things like this, but optimally I'd like listmonk to handle soft bounces differently.

**Comment by MaximilianKohler** [comment]
> I tested Sendy for a brief period before Listmonk, and I sent the campaigns to myself too (same with Listmonk). I noticed that I erroneously got unsubscribed once automatically. Their support said it was due to "one-click unsubscribe headers" and the solution was "_Double opt-out_". 

FYI,  Listmonk's `Include List-Unsubscribe header` option should not have the same problem where it causes bots to unsubscribe. The difference is that clicking Sendy's "unsubscribe" button brings you to a page that says _"You're unsubscribed. Re-subscribe?"_. Whereas listmonk's "unsubscribe" button brings you to a page where you have to click "unsubscribe". So listmonk has "double opt-out" by default.
