### ISSUE TITLE
debug logging ? "AxiosError: Network Error"

### ISSUE THREAD

**Issue by spacecabbie** [knadh/listmonk#1079]
trying to figure out why this error shows up (campaign-> test)

But logs show nothing how do i enable debug logging ?

**Comment by jorge-vitrubio** [comment]
same here, with running version  [Listmonk 2.2.0](https://github.com/knadh/listmonk/releases/tag/v2.2.0)  on Debian 11 Bullseye running the [listmonk_2.2.0_linux_amd64.tar.gz](https://github.com/knadh/listmonk/releases/download/v2.2.0/listmonk_2.2.0_linux_amd64.tar.gz)

**Comment by jorge-vitrubio** [comment]
problem persist after upgrade to   [Listmonk 2.3.0](https://github.com/knadh/listmonk/releases/tag/v2.3.0)  running the [listmonk_2.3.0_linux_amd64.tar.gz](https://github.com/knadh/listmonk/releases/download/v2.3.0/listmonk_2.3.0_linux_amd64.tar.gz)

**Comment by kvanbiesen** [comment]
Same here, 

console say: 

 GET https://xxxxxxxx/api/campaigns/analytics/views?id=7&from=2022-11-29T23%3A00%3A00.468Z&to=2022-12-07T22%3A59%3A00.468Z net::ERR_BLOCKED_BY_CLIENT

disabled addblocker but no change (this is on chrome, on firefox it works witouth issues)

**Comment by knadh** [comment]
Looks like an adblocker plugin is blocking requests. Please add the domain to the plugin's allowlist.

**Comment by jorge-vitrubio** [comment]
Yes, it is https://github.com/gorhill/uBlock blocking the url, if I do disable it for my domain it works fine.

Actually Listmonk it is installed in: `https://newsletter.MYDOMAIN.tdl` and uBlock allows also `https://MYDOMAIN.tdl`

the `https://newsletter.MYDOMAIN.tdl` is using LetsEncrypt wildcard for the whole domain.

it might be some CORS configuration in our side, but I haven't got time to investigate it.

I'll try to get back to this later next month
