### ISSUE TITLE
error fetching lists: missing destination name description in *[]models.List

### ISSUE THREAD

**Issue by jorge-vitrubio** [knadh/listmonk#1080]
**Version:**
 - listmonk: [eg: v2.2.0]
 - OS: Debian 11 Bullseye

**Description of the bug and steps to reproduce:**
Every time I clck on **Lists -> All Lists** wich URL is `<DOMAIN>/admin/lists` i get this error appearin in a popup and also readable in the logs
```
error fetching lists: missing destination name description in *[]models.List
```
Then I can proceed to edit the list or create a new one, but every time I click on save changes or to go back the same message error appears.

If changes are made to the list, they are not shown in this moment and interface is not refreshed.

If I reload the page changes are shown.

**Screenshots:**

Also, while on the **All lists** view, each list shows 0 Subscribers but it is now true, they are full of addresses.

![image](https://user-images.githubusercontent.com/524471/205182748-c07a4fb4-c230-4474-90ca-6a0eb48d2950.png)

if I click in the 0 susbscribers then I can see all of them.

![image](https://user-images.githubusercontent.com/524471/205183112-2cb4bd49-f8f7-4966-96ea-ad4f3a33abb8.png)

**Comment by jorge-vitrubio** [comment]
After successfull upgrade this bug is not pressent any more, please follow instructions in https://github.com/knadh/listmonk/issues/1069

thanks

**Comment by knadh** [comment]
The existing listmonk instance has to be stopped, and the new binary started, after the upgrade. The issue here seems to be that the database was upgraded but the running listmonk instance was not restarted.
