### ISSUE TITLE
Error with the production easy docker install script

### ISSUE THREAD

**Issue by FormindRTR** [knadh/listmonk#1083]
**Version:**
 - listmonk: v2.3.0
 - OS: MacOS Ventura 13.0

**Description of the bug and steps to reproduce:**
Error when I use the production Easy Docker install:

`➜  listmonk sh -c "$(curl -fsSL https://raw.githubusercontent.com/knadh/listmonk/master/install-prod.sh)"
>  checking for an existing docker db volume
>  fetching config.toml from listmonk repo
>  fetching docker-compose.yml from listmonk repo
>  generating a random password
>  modifying config.toml
sed: 1: "config.toml": command c expects \ followed by text`

<img width="379" alt="Capture d’écran 2022-12-05 à 16 24 04" src="https://user-images.githubusercontent.com/116070773/205675638-66672de3-76b6-48bd-9e23-aec86775f8c4.png">

I've already follow the previous issue with no success.

Thank you in advance for your help :)

**Comment by mr-karan** [comment]
@FormindRTR Looks like the `sed` that is installed in your system is different from GNU sed.

Can you try installing GNU sed as mentioned [here](https://stackoverflow.com/a/34815955/709452) or [here](https://stackoverflow.com/a/41416710/709452)

**Comment by FormindRTR** [comment]
Hi, 

Thanks for the answer. Unfortunately, I have the same error after I've installed gsed and make an alias:

`->  listmonk which sed
sed: aliased to gsed
  ->  listmonk sh -c "$(curl -fsSL https://raw.githubusercontent.com/knadh/listmonk/master/install-prod.sh)"

>  checking for an existing docker db volume
>  fetching config.toml from listmonk repo
>  fetching docker-compose.yml from listmonk repo
>  generating a random password
>  modifying config.toml
sed: 1: "config.toml": command c expects \ followed by text`

Then I've replaced sed command with gsed and in get this:

`➜  listmonk git:(master) ✗ bash install-prod.sh 

>  checking for an existing docker db volume
>  fetching config.toml from listmonk repo
>  fetching docker-compose.yml from listmonk repo
>  generating a random password
>  modifying config.toml
>  modifying docker-compose.yml
>  running migrations
yaml: invalid trailing UTF-8 octet`

I've had the line "# encoding: utf-8" to the docker-compose.yml and remove the "get_containers" from the install-prod.sh.

Everything was fine until another error, which has already been addressed, so I'm done here :) 

Thank you for your help guys!

**Comment by hdmoreland** [comment]
Old issue - but I ran into this when attempting to deploy the production version on a 2023 MacBook Pro (M2 Pro) running Ventura 13.2.1.

My solution was similar, but a little different. 

1. Installed gnu-sed with ```brew install gnu-sed```
2. Modified the ```install-prod.sh``` script and added the following line at the top, which creates an alias so sed corresponds to gnu-sed (aka gsed):
```alias sed="/opt/homebrew/bin/gsed"```

It might be beneficial to either add notes to the Install Guide for this issue or to add a check to the check_dependencies() function to ensure the correct version of sed is installed/being used based on the OS. I would assume this is likely an issue for everyone running MacOS Ventura.
