### ISSUE TITLE
Not allowing to preview the template

### ISSUE THREAD

**Issue by AshnaSabu123** [knadh/listmonk#1093]
**Version:**
 - listmonk: [v2.3.0]
 

**Description of the bug and steps to reproduce:**
While creating a campaign when we click on the preview button its showing bad gateway and also the campaigns are not send to the required list. But while giving a text in the content box the campaigns are sent.

Please have  a look on the issue.

**Comment by knadh** [comment]
Thanks for reporting @AshnaSabu123. This issue was fixed just a couple of days ago: https://github.com/knadh/listmonk/issues/1085
