### ISSUE TITLE
From header is ignored

### ISSUE THREAD

**Issue by thecodrr** [knadh/listmonk#1095]
**Version:**
 - listmonk: v2.3.0
 - OS: Linux

**Description of the bug and steps to reproduce:**

I am sending this JSON to `/api/tx`:
```json
{
  "subscriber_email": "some_email@email.com",
  "template_id": 5,
  "data": { ... },
  "content_type": "html",
  "headers": [
    { "From": "Name <nn@example.com>" },
  ]
}
```

While I do receive the email, it has the wrong From field (the default one set in Listmonk settings). I am using AWS SES as SMTP provider.

How do I force Listmonk to use the From header from the POST request payload?

**Comment by knadh** [comment]
Hi @thecodrr. You can set the `from_email` parameter. Just realised that this was missed in the docs. Added it here: https://listmonk.app/docs/apis/transactional/
