### ISSUE TITLE
Cold Email Server Warm Up Request

### ISSUE THREAD

**Issue by crypt0affiliat3** [knadh/listmonk#1097]
First of all, Thank You for an excellent product.

Would it be possible to enhance the performance section of settings to include a percentage increase in the sliding window?

I'd like to be able to use ListMonk to warm up a cold email server automatically rather than manually. For instance, using a subscriber list of 10,000 users, starting at 200 users and increasing by 10-50% per 24hr period until all 10,000 are sent the campaign.

i.e. for a campaign with a sliding window of 15% starting at 200 users:
Day 1: 200 / Day 2: 230 / Day 3: 265 / Day 4: 305 / Day 5: 351..... etc until 10000 is reached.

I hope I've explained this correctly.

Colin.

**Comment by knadh** [comment]
Hi Colin. A mechanism like this would significantly complicate listmonk's internals. Also, since this isn't a common usecase or requirement, it wouldn't be feasible to consider this right now. Thank you.
