### ISSUE TITLE
`per_page=all` query param broke in 2.3.0

### ISSUE THREAD

**Issue by davidmehren** [knadh/listmonk#1098]
**Version:**
 - listmonk: 2.3.0
 - OS: Docker on Debian 11

**Description of the bug and steps to reproduce:**
Commit https://github.com/knadh/listmonk/commit/3d263666209db8755711236b2546ebe8b7bdf1ea, which got released with 2.3.0 removed the `per_page=all` support, as the new external pagination lib does not support this.

This is a breaking change of the API and the old behavior is still documented, e.g. in https://listmonk.app/docs/apis/campaigns/#parameters

**Comment by knadh** [comment]
Ouch, this is a miss. Will fix this. Thanks for reporting.
