### ISSUE TITLE
Linking LISTMONK to a (sub)domain on another server

### ISSUE THREAD

**Issue by Mathis-Guichard** [knadh/listmonk#1099]
Hello there, I'm not sure where I should ask this so I'm posting it here. I hope I got it right.

I've installed ListMonk and so far, so good. However, instead of having it on `SERVER1:9000`, I'd like to put it on `SUB.DOMAIN.COM`, located on `SERVER2`. while using an encrypted tunnel to avoid any IP leaks from `SERVER1`

Being a beginner, I've tried looking around and I've paid a visit to [CloudFlare Tunnel Service - Zero Trust](https://dash.cloudflare.com/login) which I've already used to link another service the same way - However, it seems like I can't configure ListMonk to do so, or (more likely) I am not doing it right or just not looking at the right place.

Eventually looking to do such a scheme, which is the one we are using for another service :
![dssdfdsfsdfdsffd](https://user-images.githubusercontent.com/42196562/207168134-acdc0117-c8a3-4233-8cac-f60e5ba94c90.png)

Does someone know / could help me out with this one? Or just point me in the right direction :)
Thanks ;)
Mat'.

**Comment by knadh** [comment]
Hi. I'm not familiar with Cloudflare tunnel. You can run listmonk on a public facing server anywhere and point your sub domain's A record (DNS) to this server's IP. This is not specific to listmonk, but any web application in general.

You may want to run a webserver like Nginx to get SSL certificates working. A tutorial like this may be useful: https://yasoob.me/posts/setting-up-listmonk-opensource-newsletter-mailing/

**Comment by Mathis-Guichard** [comment]
> Hi. I'm not familiar with Cloudflare tunnel. You can run listmonk on a public facing server anywhere and point your sub domain's A record (DNS) to this server's IP. This is not specific to listmonk, but any web application in general.
> 
> You may want to run a webserver like Nginx to get SSL certificates working. A tutorial like this may be useful: https://yasoob.me/posts/setting-up-listmonk-opensource-newsletter-mailing/

Hey, thanks for stoping by, I'll keep on trying with this in mind, thanks

**Comment by MaximilianKohler** [comment]
@Mathis-Guichard How have you faired with Cloudflare? I'm thinking of switching to their nameservers so I can [hide my IP behind their proxy](https://developers.cloudflare.com/dns/manage-dns-records/reference/proxied-dns-records), and I was searching to see if that would cause any problems with things like statistics (open rates) or even cause people to get a captcha prompt when clicking "unsubscribe" and thus be more likely to mark emails as spam.
