### ISSUE TITLE
listmonk --install shouldn't clobber an existing installation

### ISSUE THREAD

**Issue by RaghavSood** [knadh/listmonk#110]
I'm trying to package listmonk for NixOS. Being able to run `listmonk --install` as a `ExecPreStart` systemd unit option would be ideal.

However, that requires that running it does not delete the existing data.

I suspect this might also be useful for other automated management systems where requiring a manual run of install out of band is less than ideal.

If there's another reason why install clobbers the db, I'm looking at writing a bash script to run in `ExecPreStart` that connects to the db, checks if a listmonk table exists, and only runs install if it doesn't - would also be happy if there's a separate `--install-no-clobber` option in addition to the regular `--install` if the current beheviour is useful too

**Comment by knadh** [comment]
Hi @RaghavSood,
Not deleting existing data while installing is tricky as installation as it is a one-time (global) process. The schema itself thus incorporates the wipe + create behaviour.

I'm not familiar with NixOS, but is tying a destructive action like `--install` to a hook like `ExecPreStart` appropriate?

Without much context, I'd be inclined to think that running `--install` should be left to the user as a one-time setup exercise.

Also, how does `config.toml` fit in here?

**Comment by mr-karan** [comment]
> should be left to the user as a one-time setup exercise.

Yep. @RaghavSood  If you want to add a systemd unit, you should consider a separate unit altogether, with `Type=oneshot` and run the application as `Type=simple`.

**Comment by RaghavSood** [comment]
When using the nix package manager, programs like listmonk are split up into two parts: You have the `nixpkg` which defines the binary compilation (a simple `buildGoModule` in this case), and a nix module which encompasses things like `config.toml`, the systemd unit file, whether the program has any other runtime dependencies (postgres in this case).

As the final execution of the program is handled by the nix package manager via the systemd unit file, all set up is done there - there is no real option for something like `if config.database has changed, run install`.

It's generally also considered non-idiomatic in the nix ecosystem to add a program binary systemwide (or even to a particular user's `$PATH`) unless there's a very good reason to. Thus, by default, the listmonk binary would only be available to a user created solely to run listmonk, and not to the actual sysadmin user.

@mr-karan Running a oneshot systemd unit for the set up works, until someone tries to change the database config on an existing deployment - it won't run install since the oneshot has already completed. That might be a reasonable limitation though.

**Comment by knadh** [comment]
> @mr-karan Running a oneshot systemd unit for the set up works, until someone tries to change the database config on an existing deployment - it won't run install since the oneshot has already completed. That might be a reasonable limitation though.

This sounds like a good tradeoff. If the user wishes to re-install, they could always just run `--install` manually, right?

**Comment by RaghavSood** [comment]
@knadh Yeah, technically, they could (provided their user has permission to read config.toml) - that seems like a reasonable trade off.

The only downside here would be if: 

1. The initial values provided to config.toml are wrong, so the oneshot fails, but doesn't run again when you fix your db settings
2. I'd need a lock file in the oneshot that ensure the service isn't run again after a reboot - since the majority of NixOS systems are read-only, this is a bit hard, but doable

**Comment by RaghavSood** [comment]
As a follow up question, once `--install` is run, are any future db schema updates applied automatically during the normal execution of listmonk? Or does a db update require dropping the entire db?

**Comment by knadh** [comment]
`--install` is meant only for fresh installations. Schema changes will eventually come via automatic updates (and DB migrations), once all of that's built of course.

**Comment by RaghavSood** [comment]
Perfect, appreciate the quick help!
