### ISSUE TITLE
The 'From address' appears broken on Outlook desktop versions

### ISSUE THREAD

**Issue by SonalikaG** [knadh/listmonk#1100]
We observed that when we trigger a campaign via Listmonk, the recipients with Outlook desktop versions receive a '**From address**' which is different from the original '**From address**' which was added in Listmonk.

For example, if we set the '**From address**' as `xyz <contact+abc@domain.com>` in the Create Campaign form in Listmonk, the recipient receives it as `contact+abc=domain.com@mail.domain.com on behalf of xyz`

OR

`contact+abc=domain.com@mail.domain.com <contact+abc=domain.com@mail.domain.com> on behalf of xyz`

@knadh, could you please help us out with the solution to the above mentioned issue. Thank you.

**Comment by knadh** [comment]
What SMTP server are you using? This is something either the SMTP server is doing our Outlook is doing. listmonk doesn't make any changes to the address.
