### ISSUE TITLE
Add an option to lists to publish the subscriber count

### ISSUE THREAD

**Issue by ffraenz** [knadh/listmonk#1101]
## Problem

I am using listmonk as a privacy-friendly email marketing solution for my indie project [ciphereditor](https://ciphereditor.com/). I've added links to the project's social media channels (incl. listmonk) to the footer together with a counter for each of them. This should improve click through rate (and keep me motivated).

The services Twitter, GitHub, and Discord all provide a way to retrieve the follower, stargazer, and member count without requiring authentication. However, to retrieve the subscriber count from listmonk requires the same basic auth login that you need to access the admin backend.

To show the subscriber count of a listmonk list I would need to
- add the admin login to the build pipeline of the frontend app (which I try to avoid due to the risk of leaking it) or
- host a backend service that uses the admin login to retrieve and respond with the subscriber count (added complexity and cost – my current solution).

## Proposed Solution

I would love to have an option for each list to set whether to publish the subscriber count or not. If enabled, the subscriber count appears on public pages (e.g. subscription forms) as well as in public API responses.

**Comment by knadh** [comment]
Hi @ffraenz. Showing the subscriber count next to a mailing list publicly seems like a very niche usecase. Discord, GitHub etc. are all public social platforms, so displaying those numbers is a part of their core proposition, unlike a self-hosted mailing list run by an individual or an org. To add that to the core with a toggle option on the UI doesn't seem right.

While there's additional effort, this can still be achieved with the API with which you can create fully cutomized public pages.
