### ISSUE TITLE
Strange bug when searching "all subscribers"

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1102]
**Version:**
 - listmonk: (v2.3.0)
 - OS: ubuntu

**Description of the bug and steps to reproduce:**

I pasted in an email to search and it came up with 0 results. I discovered that when the email has a number before the "@" it does something strange. The "@" changes up/down. 

Go to `/admin/subscribers` and type in `test913@` in the search box. Now type `t` after `@`. You can see the shift. This somehow causes the email to not be recognized. 

IE: if I'm looking for an email `test913@gmail.com` it will not find it. If I search `test913@` it will find it. 

`testasdf@gmail.com` has no issues.

**Comment by knadh** [comment]
I'm unable to reproduce this. `test913` and `test913@` both work.

![image](https://user-images.githubusercontent.com/547147/209461780-1e1302b8-fc2a-48c1-aefe-4346ab4d9c77.png)

![image](https://user-images.githubusercontent.com/547147/209461785-9de14589-aca3-4def-bb98-8aeefb5a6e6c.png)

**Comment by MaximilianKohler** [comment]
> I'm unable to reproduce this. `test913` and `test913@` both work.

Yes, both of those should work. Do you see the shift when you type `g` after the `@`? 

`test913@g`  and `test913@gmail.com` are what shouldn't work.

**Comment by MaximilianKohler** [comment]
I think I figured it out. It seems to have to do with copy-paste. It's not stripping the formatting (is my guess) and thus not searching the plain string. 

See screenshot below. If I hover and click "copy" I can paste that in the search and it will come up. But if I copy the underlined text in the email and paste that in the search it will not show up. 

![bug formatting](https://user-images.githubusercontent.com/3606996/210204186-964f325f-3b74-4f7e-b288-7fd8a5655d73.png)
