### ISSUE TITLE
does listmonk offer the ability to send in sequence?

### ISSUE THREAD

**Issue by ajmandourah** [knadh/listmonk#1103]
is it able to send a list of campaigns in a set period of time to subscribers? for example a monthly or weekly matter.?

**Comment by knadh** [comment]
You can schedule individual campaigns to be send at a specific dates (and time).

**Comment by ajmandourah** [comment]
Thanks for the prompt reply.

I tried the demo and saw that . My idea was to have a set number of campaigns (around 300 or more in my case) to be sent to new subscribers in a timely basis. so every subscriber will get the same content but in a different time frame

**Comment by knadh** [comment]
Ah no, this isn't possible out of the box. If you're looking for automation, maybe something like Mautic is more appropriate.
