### ISSUE TITLE
Custom headers not working (SES issue?)

### ISSUE THREAD

**Issue by simenghe** [knadh/listmonk#1104]
**Version:**
 - listmonk: v.2.20
 - OS: Ubuntu 20.04

**Description of the bug and steps to reproduce:**
Custom Headers of BCC are not working with Amazon SES. I am not receiving the email when adding BCC headers

**Screenshots:**

![image](https://user-images.githubusercontent.com/28720612/207939200-b6a8f215-3293-426c-b03f-776c277d66e2.png)

**Comment by knadh** [comment]
I'm unsure what's happening here. Does SES give a log of e-mails that you can inspect to see if the header's getting there (it should be).
- Just to be sure, please try case-sensitive `Bcc`.
- The `To` and `Bcc` e-mails aren't the same, right? If they're, BCC won't be delivered.

**Comment by simenghe** [comment]
> I'm unsure what's happening here. Does SES give a log of e-mails that you can inspect to see if the header's getting there (it should be).
> 
>     * Just to be sure, please try case-sensitive `Bcc`.
> 
>     * The `To` and `Bcc` e-mails aren't the same, right? If they're, BCC won't be delivered.

SES does not automatically store logs of the emails. I have confirmed that the two addresses are not the same.
