### ISSUE TITLE
Store IP addresses for double opt-in

### ISSUE THREAD

**Issue by jfilter** [knadh/listmonk#1106]
**Is your feature request related to a problem? Please describe.**

To be GDPR-compliant, I have to store the IP address (1) of a user signup and also (2) when the user opens the confirmation link. I need to be able to prove that a user actually signed up. German lawyers tell me that is mandatory to get the IP address. Via the IP address and the ISP, it's (theoretically) possible to determine the user.

**Describe the solution you'd like**

I pointed out in https://github.com/knadh/listmonk/issues/315  that you do want to store IP address. Unfortunately, the GDPR requires storing the IP address :/. So, I guess a solution would be to enable the IP storage optionally for double opt-in lists.

### Source 1

> German Double Opt-In Requirements

[..]

> the first entry should be logged (IP address of the recipient, timestamp, etc.)

> The last point is one of the most important aspects. In the event of a dispute, the sender of the advertising email must be able to prove that the recipient has actually agreed to receive the mail. A double opt-in can, in theory, prevent emails from being sent without the agreement of the receiver.

<https://en.ryte.com/wiki/Double_Opt-In>

### Source 2

> Detailed logging of consent

> A user must give explicit and unambiguous consent to receiving email communications. Consent must also be given before an online business can collect personal data (for example via cookies). In addition, consent must be logged. Under GDPR (data protection regulations applicable to businesses in the European Union), consent logging must include details of time, date, and [IP address](https://www.seobility.net/en/wiki/IP_Address).

https://www.seobility.net/en/wiki/Double_Opt-in

**Comment by knadh** [comment]
listmonk's subscriber attributes support arbitrary values. You can design a custom signup form and use the subscriber APIs to record the IP address or any other details during subscription. It wouldn't be feasible to bake in this functionality into listmonk's core as discussed in #315 though.

**Comment by jfilter** [comment]
This was implemented in https://github.com/knadh/listmonk/issues/1329.
