### ISSUE TITLE
Sending transactional e-mail to users who are not subscribers yet

### ISSUE THREAD

**Issue by jarzi25** [knadh/listmonk#1108]
Hi @knadh,

I was trying out the transactional e-mail API using the curl command documented [here ](https://listmonk.app/docs/apis/transactional/)and it worked perfectly.

But when I tried to send an transactional e-mail to a user who is not a subscriber in listmonk then I started getting an error `{"message":"Subscriber not found"}`. I tried this to check if I can send a "Welcome" transactional  e-mail to a new user who is not added as a subscriber yet.

Is it possible to send an email to a user who is not a subscriber?

Thank you.

**Comment by knadh** [comment]
Hi @jarzi25. You've to register the user as a subscriber first. There's a pending PR that sends messages to unregistered users, but this requires some thinking before letting unregistered e-mails be processed. For instance:

- Templates that use subscriber attributes will be blank for unregistered e-mails and will behave differently compared to registered users.

**Comment by NicoHood** [comment]
Is there an automated way to send a welcome message? I mean that is a very common usecase, I would appreciate that without any external API or service.

**Comment by knadh** [comment]
Not currently. We can consider a welcome mail feature for the next version.

**Comment by NicoHood** [comment]
Please! :)

**Comment by Facecube** [comment]
> Hi @jarzi25. You've to register the user as a subscriber first. There's a pending PR that sends messages to unregistered users, but this requires some thinking before letting unregistered e-mails be processed. For instance:
> 
> * Templates that use subscriber attributes will be blank for unregistered e-mails and will behave differently compared to registered users.

Hello,

any update on that PR?
This would be a feature I need.

Would also be happy to contribute if you could point me to that PR.
The different behaviour for unsubscribed users would not be a problem for me and I also think it is reasonable for the specific properties to be unavailable.

Thanks in advance.

**Comment by Facecube** [comment]
Thanks a lot @ugd for merging the commit!
