### ISSUE TITLE
Question: One subscriber receives a campaign e-mail three times

### ISSUE THREAD

**Issue by samuelT2** [knadh/listmonk#1109]
Hi all

No doubts, listmonk is a wonderful tool and I love working with it.

An issue which I observed during the last two campaigns bothers me a bit: I have a list of 10 subscribers. If I create and send a campaign for this list, there is a single subscriber which gets the same e-mail three times, though he's subscribed only once.

What could be the reason for this and where should I start debugging?

Thank you very much for your tipps.

**Comment by knadh** [comment]
That is very very strange. Have never seen this behaviour in production. Haven't ever seen any reports either. Possibilities:

- Something's off with the SMTP and it's delivering multiple mails.
- Something's off with the SMTP where it returns an error, listmonk retries, but all mails are delivered anyway. You can try adjusting the retry count in settings to see if this makes a difference.
- Something's off with the mailbox for this particular user that's resulting in duplicate deliveries. Happens with IMAP sync issues sometimes.

**Comment by samuelT2** [comment]
Thank you @knadh - it already helps by knowing that you've never seen a similar behaviour. We had minor issues with our SMTP in the past, though in another context. I'll get in touch with the SMTP provider to get the logs.
