### ISSUE TITLE
Support for authenticated proxies

### ISSUE THREAD

**Issue by RaghavSood** [knadh/listmonk#111]
Since listmonk has no authentication, we're looking at running it behind [oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/)

While explicit support from listmonk is not necessary for this (authentication will work just fine even now), I'd like to bring it up so that it can be considered down the road when there's a proper user system with roles/scopes. Being able to inherit the user from an authenticating proxy would allow for easy SSO across multiple providers.

**Comment by mr-karan** [comment]
It's a planned feature. See [TODO](https://github.com/knadh/listmonk/blob/master/TODO.md)

**Comment by knadh** [comment]
Closing this as we'll cover this in the next major release with auth.

**Comment by alerque** [comment]
This should probably be re-opened, it is not addressed yet in any release or even Git HEAD that I can tell. You can disable the internal authentication and setup a custom one in the proxy, but there is no inheritance of the user information from the SSO.

I know there is a TODO item, but users can't subscribe to notifications on a TODO item, can't discuss the implementation, etc. An issue is a better place to track the request and get notified of any progress on the matter.

**Comment by knadh** [comment]
Opened an issue https://github.com/knadh/listmonk-site/issues/14 on the docs site.
