### ISSUE TITLE
Question: Unsubscribe header not showing in iOS Mail App

### ISSUE THREAD

**Issue by samuelT2** [knadh/listmonk#1110]
I have a general question, perhaps I misinterpreted the setting:

iOS Mail app shows the unsubscribe header within it's own section when viewing an e-mail. Eg. see notification e-mail from Github:
![Aw  knadhlistmonk  Question One subscriber receives a campaign e-mail three times (Issue #1109)](https://user-images.githubusercontent.com/10983143/208393730-8ecd4822-6abd-4100-b64e-20efbb40bd18.png)

I have this setting enabled in the privacy tab within listmonk as well:
![Screenshot 2022-12-19 103548](https://user-images.githubusercontent.com/10983143/208394384-138aca4d-2412-456d-aae7-c4c862d51850.png)

Though, this header is not appearing for any e-mail I send through a campaign on my iOS Mail app.

By comparing the two headers (the one from Github and a campaign e-mail), the only difference I can spot is that Github provides two possible ways to unsubscribe: Either with an e-mail to a unique e-mail address or with a get request, whereas listmonk provides a get request only. Is this diff preventing the unsubscribe header to appear on my device or is there any other configuration needed from my end which I missed?

![Screenshot 2022-12-19 104335](https://user-images.githubusercontent.com/10983143/208396333-76797ae4-8f50-43e0-be9c-2581083a5ee0.png)

**Comment by knadh** [comment]
There is no other configuration. Enabling that toggle adds two headers like shown below:
![image](https://user-images.githubusercontent.com/547147/208398678-59e5da8c-8e4a-4df9-8cf3-86e71d9a0114.png)

If they aren't in the delivered e-mails, either the mail client is stripping it or the SMTP server you're using for sending is.

**Comment by samuelT2** [comment]
Thanks @knadh - I see the header "List-Unsubscribe" in both e-mails, but "List-Unsubscribe-Post" is missing in both. But the behaviour of the e-mails are not the same: Github notification e-mail shows the unsubscribe header in the Mail app, the listmonk campaign e-mail doesn't trigger the header.

Since it's a nice to have and my configuration is correct, I assume that again my SMTP messes things up. Closing therefore.
