### ISSUE TITLE
Integration with LeadGenerator

### ISSUE THREAD

**Issue by mariuszmalek** [knadh/listmonk#1111]
Hello, I have started an open-source project for Lead Generator. I think that by I will be able to create an integration with Listmonk. Before that, I want to see if there will be any interested people.

Repository of the project: https://github.com/LeadBrowser/app

**Comment by phillipwilhelm** [comment]
Interested!

**Comment by phillipwilhelm** [comment]
Looks like this is no longer available? @mariuszmalek
