### ISSUE TITLE
How to stop listmonk for upgrade?

### ISSUE THREAD

**Issue by Servery** [knadh/listmonk#1113]
I installed listmonk on a vps as binary. Now I want to upgrade, but I cannot copy the new listmonk file. How can I stop listmonk?

**Comment by knadh** [comment]
Assuming you installed listmonk as a service, something like `sudo systemctl stop listmonk` or `sudo service listmonk stop` should work. Then you can overwrite the binary, run `--upgrade`, and `start` it back with the same commands.

If somehow it's not running as a service, `pkill -9 listmonk` will stop the listmonk process. How did you start the binary in the first place?

**Comment by Servery** [comment]
Thank you...

**Comment by MaximilianKohler** [comment]
@Servery I'm trying to find instructions for how to use listmonk without docker. Are there any directions for the way you set it up? If not, could you write out the basic steps?
