### ISSUE TITLE
Duplicating opt-in email campaigns with edited content isn't working properly.

### ISSUE THREAD

**Issue by jfilter** [knadh/listmonk#1114]
**Version:**
 - listmonk: v2.3.0

**Description of the bug and steps to reproduce:**

To replicate: 

0. Have a list with double opt-in.
1. Go to the list overview and click and click on "send opt-in campaign".
2. Adjust the rich text content, e.g., add a word.
3. Change the subject.
4. Send campaign.
5. Then duplicate the campaign that was sent. The changes done in 2. are gone while changes of 2. are persisted.

It has to with this line: https://github.com/knadh/listmonk/blob/832a426f4c9f01767a331a6701175a4c466caa4a/cmd/campaigns.go#L194

**Comment by knadh** [comment]
Tried  several times, but I'm unable to reproduce this behaviour. The code snippet you linked, that only kicks in when creating the campaign, not when updating or sending, so has no effect on the contents after the initial creation.

![image](https://user-images.githubusercontent.com/547147/209424024-dcec605e-d53c-46d2-9773-5f0dda0e3ae8.png)
