### ISSUE TITLE
Default "From" field generates 5.6.7 SMTP bounce on Google Workspace MX servers

### ISSUE THREAD

**Issue by etal37** [knadh/listmonk#1121]
**Version:**
 - listmonk: v2.3.0
 - OS: Debian 11u5

**Description of the bug and steps to reproduce:**
I sent myself an e-mail using the SMTP connection test tool (to a Google Workspace mailbox). I get [a 5.6.7 SMTP bounce](https://betterbounces.net/email-error/5.6.7) from the Google Workspace servers.

So given the nature of the 5.6.7 error, it's most likely related to the quotes between the sender name, like Listmonk does: `"Name" <name@email.com>`, since I tried exactly the same e-mail from another client (Evolution) that builds the From: field in the following way: `Name <name@email.com>` (without any quotes around the sender name) and the e-mail gets through without any issue.

How can I proceed from there? Write a patch?

Thank you in advance.

**Comment by knadh** [comment]
hm, listmonk works fine with Gmail (receiving) and with Gmail SMTP (sending). The quotes in the name section of the `from` address is valid and universal. This must have something to do with the connection test tool.
