### ISSUE TITLE
TrackLink is not working in listmonk

### ISSUE THREAD

**Issue by themockingjester** [knadh/listmonk#1124]
I am using TrackLink for tracking link clicks but every time I am clicking on link then a new tab opens and shows 
`{"message":"Not Found"}`

I am using list monk in development mode. 
I found related posts also on GitHub, and followed the same but still no change.

**Comment by themockingjester** [comment]
Fault was from our configuation of server

**Comment by frelle** [comment]
Hello
@themockingjester  I have the same issue. Can you please share how you fix yours? what to change in the server"s configuration

Thank you

**Comment by themockingjester** [comment]
> Hello @themockingjester I have the same issue. Can you please share how you fix yours? what to change in the server"s configuration
> 
> Thank you
> 
> EDIT solution in my case was to remove the trailing slash in the root URL (like it's displayed...)

Hi @frelle 
The issue was with internal routing I was using wrong URL
