### ISSUE TITLE
bad character U+003D '=' when submitting text containing @TrackLink from the API

### ISSUE THREAD

**Issue by brett-kimball** [knadh/listmonk#1125]
- listmonk: v2.3.0
 - OS: Debian

I have been using python requests to submit campaigns to listmonk's API.  Everything has been working fine until I decided to include the @TrackLink shorthand appended to each link href in the content body.  The full error I am seeing when attempting to preview or edit a campaign that has been created through the API is:
{"message":"Error compiling template: error compiling message: template: content:2: bad character U+003D '='"}

The error is also showing up in the listmonk logs and the campaign will not send.

If I open the API generated campaign in listmonk, select "Content", view the HTML source in the editor, click "Format HTML", "Save", then "Save Changes" to the campaign the issue is resolved.  The campaign becomes fully functional.

Attached is the "body" value that is returned by the API when the campaign is created.  If I remove "@TrackLink" from the hrefs the error goes away.
[body.txt](https://github.com/knadh/listmonk/files/10324407/body.txt)

**Comment by knadh** [comment]
This sounds like a UTF-8 character encoding issue when posting from Python. Could you investigate this along those lines? The same payload, does POSTing via curl work?

**Comment by sjoerdvanderhoorn** [comment]
To aid further investigation, I am having the same issue. I trimmed it down to just two lines of HTML that trigger the error in the UI.

1. Download [listmonk-1125.html.txt](https://github.com/knadh/listmonk/files/10414801/listmonk-1125.html.txt)
2. Rename it to `listmonk-1125.html`.
3. Open the file in your browser (I am using Chrome).
4. Press Ctrl-A followed by Ctrl-C to copy the content.
5. Open a campagne and edit the text.
6. Set Format to **Rich Text**.
7. Paste the content from the clipboard using Ctrl-V.
8. Save changes.
9. Error shows: `error compiling message: template: content:1: bad character U+003D '='`

**Comment by brett-kimball** [comment]
I got a chance to test with curl using both my original "body" payload as well as with the file provided by Sjoerd.  The results are the same, the unicode encoded '=' sign is still creating an error when the @TrackLink is used.

Both of the test payloads seem to be encoded properly.  Here is a partial hex dump of Sjoerd's file:
```
od --endian=big -a -x ./listmonk-1125.html.txt   |  head -n2
0000000   <   i   m   g  sp   s   r   c   =   "   h   t   t   p   s   :
           3c69    6d67    2073    7263    3d22    6874    7470    733a
```

The '=' is encoded as hex '3d' which is to be expected for the utf-8 equal sign.

**Comment by brett-kimball** [comment]
I think Sjoerd's contribution to testing this error has ruled out the JSON encoding/decoding of the API being the source of the problem, after all his example uses text that is pasted into the campaign editor.

As noted in my first post, using the "Format HTML" utility on the source view of the campaign resolves the issue.  This remains true when Joerd's campaign body is pasted into the editor rather than sent through the API.  I did an API GET of the campaign both before and after using "Format HTML".  The only change to the "body" reported by the API was the insertion of 'cr' 'nl' (0d 0a) line termination character sequence.  The encoding of the rest of the body characters remained the same, the '=' characters were still represented as utf-8 '3d'.  And yet after using "Format HTML" the parsing of the body by listmonk did not choke on those '3d' characters.

I did a further test following Joerd's instructions, but with one added step:
  7.5.  Edit the campaign source, insert the cursor after the 'img' tag and before the '<a href', press Enter, then Save the campaign.

Introduction of an additional line break into the body resolves the issue.  It looks listmonk's campaign parsing function requires some line breaks in the body.  Further testing revealed that the carriage return (0d) character is optional.  A simple newline (0a) will suffice to fix the problem.

**Comment by brett-kimball** [comment]
This does not work: 
```
curl  \
        -u "login:passwd" 'http://localhost:9000/api/campaigns' \
        -X POST \
        -H 'Content-Type: application/json;charset=utf-8' \
        --data-raw '{"name":"Test campaign","subject":"Hello, world","lists":[1],"from_email":"no-reply <no-reply@example.org>","content_type":"richtext","messenger":"email","type":"regular","tags":["test"],"template_id":1, "body": "<img src=\"https://listmonk.app/static/images/logo.svg\" width=\"16\" height=\"16\" style=\"margin-top: -4px;\"> <a href=\"https://www.google.com@TrackLink\" class=\"source\" target=\"_blank\">TEST</a>" }'
```
This works fine:
```
curl  \
        -u "login:passwd" 'http://localhost:9000/api/campaigns' \
        -X POST \
        -H 'Content-Type: application/json;charset=utf-8' \
        --data-raw '{"name":"Test campaign","subject":"Hello, world","lists":[1],"from_email":"no-reply <no-reply@example.org>","content_type":"richtext","messenger":"email","type":"regular","tags":["test"],"template_id":1, "body": "<img src=\"https://listmonk.app/static/images/logo.svg\" width=\"16\" height=\"16\" style=\"margin-top: -4px;\">\n<a href=\"https://www.google.com@TrackLink\" class=\"source\" target=\"_blank\">TEST</a>" }'
```
The only difference between the two examples is replacing the space between the <img...> and <a...> tags with a newline.

**Comment by knadh** [comment]
After a bunch of trial and error, figured that`@` is the culprit here. With `@TrackLink`, we see this behaviour. Without it, space, line breaks etc. do not make a difference. This is how the Go template parser behaves. Will see if there's any way to circumvent this.

**Comment by knadh** [comment]
Instead of the shorthand:
`<a href=\"https://www.google.com@TrackLink\" class=\"source\" target=\"_blank\">TEST</a>`

this can be used:

`<a href=\"{{ TrackLink \"https://www.google.com\" }} class=\"source\" target=\"_blank\">TEST</a>`

**Comment by sjoerdvanderhoorn** [comment]
Beter late than never, but I can confirm the `{{ TrackLink \"https://www.google.com\" }}` pattern works.

**Comment by christophcemper** [comment]
I came across this now also on 2.40 today.

I believe the analysis is wrong that the short hard was the problem, I could still fix and get around the issue by

1/ go to Source view
2/ click "Format HTML"
3/ save
4/ works 🤷
