### ISSUE TITLE
Reply-to option when creating a new campaign

### ISSUE THREAD

**Issue by paraswaykole** [knadh/listmonk#1126]
**Is your feature request related to a problem? Please describe.**
I wanted to send campaigns with reply-to header in mails, to receive email replies to sent some specific campaigns.

**Describe the solution you'd like**
It could be a global setting in general page, where reply-to email is mentioned and while creating a new campaign, just a checkbox to specify whether to include reply-to in headers or not.

**Comment by halms** [comment]
I think you can just set a custom `Reply-To` header. Either as a default in the settings per SMTP server, or per campaign (with `set custom headers` at the bottom).

**Comment by knadh** [comment]
Yep, like @halms said, you can just set `[{"Reply-To": "email@domain.com"}]` per campaign or in the global SMTP settings.

**Comment by paraswaykole** [comment]
Thanks @knadh  & @halms.
