### ISSUE TITLE
docker-compose: Avoid container_name to allow multiple instances

### ISSUE THREAD

**Issue by krumelmonster** [knadh/listmonk#1130]
As listmonk lacks multi-tenancy, I want to set up multiple instances of listmonk via docker. This is complicated by the fact that the docker-compose.yml makes use of the `container_name` option which will prevent creation of a second instance:

```
ERROR: for listmonk_db  Cannot create container for service db: Conflict. The container name "/listmonk_db" is already in use by container "so-and-so". You have to remove (or rename) that container to be able to reuse that name.
```

The documentation for `container_name` warns:

> Because Docker container names must be unique, you cannot scale a service beyond 1 container if you have specified a custom name. Attempting to do so results in an error.

If the `container_name` option is removed from docker-compose, the container name will be determined by the name of the directory that contains the docker-compose.yml. The database host in config.toml can be updated to `host = "db"`

**Comment by mr-karan** [comment]
Feel free to edit the `docker-compose` for your personal needs. Since this is not a common use case, it doesn't make sense to edit the docker-compose here.
