### ISSUE TITLE
API not working properly with PHP HTTP requests (Wordpress)

### ISSUE THREAD

**Issue by wouterch** [knadh/listmonk#1132]
**Version:**
 - listmonk: 2.2
 - OS: Wordpress

**Description of the bug and steps to reproduce:**
I have spent hours figuring out the API and in the end it doesn't work for me.

I can use POST to send subscriptions to the API, but only strings. Arrays and numbers never parse correctly. I am using http request php methods. Does anyone have a working solution for PHP or Wordpress? Is something going wrong with the Arrays and Json or is there just a bug in Listmonk API? 

CODE SNIPPET:

$body = [
        'email' => $email,
        'name'  => $name,
        'status' => 'enabled',
        'lists' => 2,
        'preconfirm_subscriptions' => true,
     ] ;

$response = wp_remote_post( $listmonk_url, array(
        'headers' => array(
            'Authorization' => 'Basic ' . base64_encode( $listmonk_username . ':' . $listmonk_password ),
        ),
        'body' => $body,
    ) );

Whatever I try, lists never get parsed, same goes for attribs as arrays.

When trying the /subscribers/lists API I also couldn't get any results: it kept saying Bad Request, no ids provided.

I really would love to use Listmonk so I hope this is resolvable. If anyone has curl working better, please let me know how.

**Comment by wouterch** [comment]
When using the WPGetAPI plugin for troubleshooting, I get the same errors when trying to input numbers for the list attribute (or attr). Empty arrays. 

            [attribs] => Array
                (
                )

            [status] => enabled
            [lists] => Array
                (
                )

Encoding as JSON gives an error too:

Array
(
    [message] => Invalid email.
)

**Comment by knadh** [comment]
I am not familiar with `wp_remote_post()` in WordPress, but a quick search shows that you're using it wrong. You're supposed to encode the JSON body into a JSON string before posting.

See this example: https://developer.wordpress.org/reference/functions/wp_remote_post/#comment-3495

**Comment by wouterch** [comment]
Thanks a lot for replying!

I have tried that as well, but every time I encode the JSON body before sending it to Listmonk, I get errors:

body] => {"message":"Invalid email."} [response] => Array ( [code] => 400 [message] => Bad Request ) [cookies] => Array ( ) [filename] => [http_response] => WP_HTTP_Requests_Response Object ( [response:protected] => Requests_Response Object ( [body] => {"message":"Invalid email."}

**Comment by wouterch** [comment]
> I am not familiar with `wp_remote_post()` in WordPress, but a quick search shows that you're using it wrong. You're supposed to encode the JSON body into a JSON string before posting.
> 
> See this example: https://developer.wordpress.org/reference/functions/wp_remote_post/#comment-3495



> I am not familiar with `wp_remote_post()` in WordPress, but a quick search shows that you're using it wrong. You're supposed to encode the JSON body into a JSON string before posting.
> 
> See this example: https://developer.wordpress.org/reference/functions/wp_remote_post/#comment-3495

Thanks a lot for replying!

I have tried that as well, but every time I encode the JSON body before sending it to Listmonk, I get errors:

body] => {"message":"Invalid email."} [response] => Array ( [code] => 400 [message] => Bad Request ) [cookies] => Array ( ) [filename] => [http_response] => WP_HTTP_Requests_Response Object ( [response:protected] => Requests_Response Object ( [body] => {"message":"Invalid email."}

**Comment by knadh** [comment]
Then either the `email` field is invalid, or the JSON fields are mangled and listmonk is unable to parse the fields properly.

The JSON requests and responses shown in the docs work (you can also inspect them in the browser on the admin UI). Whatever tool you're using, you just have to make sure that the JSON end result you're posting to listmonk is proper.

**Comment by wouterch** [comment]
This is an example of encoded body that gives 400 errors in Listmonk. Any ideas on what could be wrong?

{"name":"test","email":"atestemailaddress@test.com","status":"enabled","lists":2,"preconfirm_subscriptions":true}

**Comment by knadh** [comment]
`lists: 2` is incorrect. It should be an array. `lists: [2]`. With that, it works.

```shell
$ curl 'http://localhost:9000/api/subscribers' -H 'Content-Type: application/json' \
          --data '{"name":"test","email":"atestemailaddress@test.com","status":"enabled","lists": [2],"preconfirm_subscriptions":true}'

{"data":{"id":1004,"created_at":"2023-01-04T05:18:25.989632Z","updated_at":"2023-01-04T05:18:25.989632Z","uuid":"47f317af-9a27-46bd-b346-07129d010d45","email":"atestemailaddress@test.com","name":"test","attribs":{},"status":"enabled","lists":[{"subscription_status":"confirmed","subscription_created_at":"2023-01-04T05:18:25.989632+00:00","subscription_updated_at":"2023-01-04T05:18:25.989632+00:00","id":2,"uuid":"8332ee16-1855-45ee-af59-f4a200d95c47","name":"Opt-in list","type":"public","optin":"double","tags":["test"],"description":"","created_at":"2022-12-25T10:36:14.301461+00:00","updated_at":"2022-12-25T10:36:14.301461+00:00"}]}}
```

**Comment by wouterch** [comment]
Unfortunately I get exactly the same error without using the list option at all..
    $body = array('name' => 'john', 'email' => 'jan@jan.com', 'status' => 'enabled');
    $body = wp_json_encode($body);

Becomes in JSON:
{"name":"john","email":"jan@jan.com","status":"enabled"}

And I get this Listmonk response:
[body] => {"message":"Invalid email."} [response] => Array ( [code] => 400 [message] => Bad Request )

**Comment by knadh** [comment]
The `curl` example I shared shows that it works fine. Something to do with the PHP code or the lib you're using.
