### ISSUE TITLE
Underneeth items shouldn't be accessible when a modal is open.

### ISSUE THREAD

**Issue by shrilakshmishastry** [knadh/listmonk#1135]
**Description of the bug and steps to reproduce:**
Currently, beneath accessible items are accessible when the new subscriber form modal is open.

Steps to reproduce:

1. Open the list monk admin dashboard
2. goto Subscribers and all subscribers page
3. Select the New button a modal pop-up
4. Press the tab and shift-tab, and you will be able to access underneath items

**Screenshots:**
![image](https://user-images.githubusercontent.com/29778698/210934340-cdba4022-a758-497d-95eb-abde65c09a9a.png)

**Comment by knadh** [comment]
listmonk uses Buefy for the UI. Could you please take a look at this and confirm whether this is Buefy's behaviour or whether it's an implementation issue in listmonk?

https://buefy.org/documentation/modal/

**Comment by shrilakshmishastry** [comment]
**Below is my observation :** 

**Version of Buefy**
Current version of Buefy: [v0.9.22](https://github.com/buefy/buefy/releases/tag/v0.9.22)
Current version of Buefy at listmonk :   ^0.9.10


In the subsequent releases after 0.9.10 of Buefy, the accessibility has been taken care. 
In the current version, it's completely handled, you can check here [modal](https://buefy.org/documentation/modal) under the component. Try to access input tags using the tab and shift-tab, u will still be in the modal.

**Comment by shrilakshmishastry** [comment]
I have also noticed in list-monk we are using Vue 2.6.12 and the current version of vue is 3.2.45, is there any reason for not updating the version?

**Comment by knadh** [comment]
Will try out the latest version of Buefy. Thanks for investigating.

> I have also noticed in list-monk we are using Vue 2.6.12 and the current version of vue is 3.2.45, is there any reason for not updating the version?

VueJS 2 and VueJS 3 are very different frameworks. A simple upgrade is not possible and the project has to be refactored heavily to make it compatible with Vue 3. Not priority right now.

**Comment by shrilakshmishastry** [comment]
Hi @knadh  can I take up this task ?

**Comment by knadh** [comment]
Sure. Please feel free to give this a shot.
