### ISSUE TITLE
How to use image storage on S3 with CDN like Cloudfront

### ISSUE THREAD

**Issue by wouterch** [knadh/listmonk#1137]
I am trying to figure out how to best display images in my newsletters. Amazon S3 seems like a good option, but does the bucket need to be public for people to see the images in their email? Or can it be set on private, with permissions managed in another way?

Moreover, how do I use the Cloudfront CDN? I read in issue #505 that support was now added through the 'public url' at the S3 config page, but I am unsure how to use it without documentation.. Does anyone have a short description of a workflow that works like this and how to set it up? Would be highly appreciated!

**Comment by knadh** [comment]
> Amazon S3 seems like a good option, but does the bucket need to be public for people to see the images in their email? Or

Images are accessed directly via S3 links so it will have to have public access permissions. This is fine.

> Does anyone have a short description of a workflow that works like this and how to set it up? Would be highly appreciated!

You can try looking for a tutorial that explains how to use CloudFront + S3 (regardless of listmonk). Once you've achieved that with a custom domain, you can use that domain in the `Public URL` field in the settings.

Maybe this is a start:

https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-serve-static-website/
