### ISSUE TITLE
API campaign testing message not working

### ISSUE THREAD

**Issue by alexxsam** [knadh/listmonk#1144]
**Version:**
 - listmonk: v2.3.0
 - OS: from PikaPods

**Description of the bug:**
API / Campaigns "POST /api/campaigns/:campaign_id/test" seems not working

**Steps to reproduce:**
https://myurl.com/lists/1
Name : Default list
Type : Public / Single opt-in
Subscribers : 2 enabled subscribers

https://myurl.com/admin/campaigns/1
Status : Draft or Finished
Name Test campaign
Lists : Default list

with postman.co and Basic Auth :

PARAMETERS :
https://myurl.com/api/campaigns/1/test
POST
{
"name":"Test campaign",
"subject":"Hello, world",
"lists":[1],
"type":"regular",
"content_type":"html",
"body":"test", 
"messenger":"email"
}

RESPONSE :
{
    "message": "There are no subscribers to target."
}

however I have 2 enabled subscribers on list 1

**Comment by knadh** [comment]
Test e-mails are sent to individual subscribers, not entire lists. You've to send the `subscribers: ["a@a.com", "b@b.com"]` param.
