### ISSUE TITLE
Send email twice with different name

### ISSUE THREAD

**Issue by xam-ps** [knadh/listmonk#1146]
Hi all,

in our club (German "Verein") we have the situation, that some people share an email address, for example a wife and her husband. Legally we're obligated, to send some information (e. g. invitations) to every member. Is it somehow possible to send a campaign to an email address twice, using two different names?

Thanks in advance.

**Comment by knadh** [comment]
There's no direct way to do this in listmonk. Two possibilities.

1) `username@gmail.com` and `username+something@gmail.com` both point to `username@gmail.com`. The `+whatever` helps classify and filter mails. I don't know if other providers support this. If it's viable, there could be two subscriptions, one for the original e-mail and one for the alias with a `+something`.

2) Write a [custom messenger](https://listmonk.app/docs/messengers/) that receives a webhook POST from listmonk and sends the e-mail twice. The names of the people that the e-mail should go to could be in subscriber attribs.
