### ISSUE TITLE
Adding tracklink to mailto CTA

### ISSUE THREAD

**Issue by SonalikaG** [knadh/listmonk#1147]
We want to include a tracklink in our listmonk template using an HTML anchor tag, such as `<a href="mailto:someone@example.com?subject=Test Subject&body=Test body text@TrackLink">Send email</a>`. However, when a user clicks on the link, the text "@TrackLink" is being inserted into the email body. @knadh Can you provide a solution for adding track links to mailto attributes without this issue?

![image](https://user-images.githubusercontent.com/72000677/212630668-f83fc3db-0519-4d3f-be72-cdfacba1b2ea.png)

**Comment by knadh** [comment]
You could try something like this.

```html
{{ with $link := TrackLink "https://google.com" . }}
<a href="mailto:someone@example.com?subject=Test Subject&body=Test body text{{ $link }}">Send email</a>
{{ end }}
```

**Comment by SonalikaG** [comment]
Thank you. We tried the solution you provided but we are now getting this issue and also the click is not getting tracked.

![image](https://user-images.githubusercontent.com/72000677/212667192-daee55c8-f4fc-4541-af9e-23185ce46193.png)

**Comment by SonalikaG** [comment]
> You could try something like this.
> 
> ```
> {{ with $link := TrackLink "https://google.com" . }}
> <a href="mailto:someone@example.com?subject=Test Subject&body=Test body text{{ $link }}">Send email</a>
> {{ end }}
> ```

Thank you. We tried the solution you provided but we are now getting this issue and also the click is not getting tracked.

![image](https://user-images.githubusercontent.com/72000677/212667192-daee55c8-f4fc-4541-af9e-23185ce46193.png)

**Comment by knadh** [comment]
Works for me locally. Is `Individual Subscriber Tracking` turned on in `Settings -> Privacy`?

**Comment by daurpam** [comment]
Tested with `Individual Subscriber Tracking` ON and OFF, and not working. Still showing tracklink on the body and didn't get tracked on analytics.
