### ISSUE TITLE
Filter unconfirmed subscribers

### ISSUE THREAD

**Issue by Sjors** [knadh/listmonk#1150]
Since v2.3.0 it's possible to [prune unconfirmed subscribers](https://github.com/knadh/listmonk/issues/1020#issuecomment-1309912732), which is nice.

But I'd also like to be able to see them, so I can send a reminder or (if I recognise a name) even nag them through another channel to check their spam folder.

P.S. is the Subscribers count on the dashboard all confirmed? (for communication with e.g. advertisers it's nice to know the confirmed number)

**Comment by knadh** [comment]
> But I'd also like to be able to see them, so I can send a reminder or (if I recognise a name) even nag them through another channel to check their spam folder.

You can run a query like this on the subscribers page: `subscribers.id IN (SELECT subscriber_id FROM subscriber_lists WHERE status='unconfirmed')`

> P.S. is the Subscribers count on the dashboard all confirmed? (for communication with e.g. advertisers it's nice to know the confirmed number)

It's all subscribers in the database.

**Comment by Sjors** [comment]
Thanks, that query worked.
