### ISSUE TITLE
How to send FCM notifications and sms

### ISSUE THREAD

**Issue by guptadeepali39** [knadh/listmonk#1153]
Hi I am using listmonk for messaging for email, sms and fcm.
For sms and fcm I am using external endpoints by passing payload as mentioned in document.
Now my concern is the body in the payload is coming as html, then how can I use it for FCM and sms, because I need formatting as well like line breaks and emoticons
Can someone please guide.
@knadh

**Comment by knadh** [comment]
Create a plain text template in `Templates` without any HTML and use that on your campaigns.

**Comment by guptadeepali39** [comment]
@knadh but the problem is even if I am selecting plainText it is sending message in html format only in the below payload in key "body":
{
    "subject": "Welcome to listmonk",
    "body": "The message body",
    "content_type": "plain",
    "recipients": [{
        "uuid": "e44b4135-1e1d-40c5-8a30-0f9a886c2884",
        "email": "anon@example.com",
        "name": "Anon Doe",
        "attribs": {
            "phone": "123123123",
            "fcm_id": "2e7e4b512e7e4b512e7e4b51",
            "city": "Bengaluru"
        },
        "status": "enabled"
    }],
    "campaign": {
        "uuid": "2e7e4b51-f31b-418a-a120-e41800cb689f",
        "name": "Test campaign",
        "tags": ["test-campaign"]
    }
}

Please let me know if I am missing something

**Comment by knadh** [comment]
Did you create a template in Admin -> Templates with no HTML in it?
