### ISSUE TITLE
PostgreSQL - role "listmonk" does not exist

### ISSUE THREAD

**Issue by dlford** [knadh/listmonk#1154]
**Version:**
 - listmonk: v2.3.0
 - OS: Docker (Ubuntu)

**Description of the bug and steps to reproduce:**
Postgres DB logging out `FATAL:  role "listmonk" does not exist` every second. Everything seems to be working as expected, but it's filling up my log queues.

1. Set up with docker compose
2. Migrate to a new host and restore backed up data (not sure if this caused the issue or was unrelated?)
3. Check database logs

Happy to provide more info if needed.

**Comment by mr-karan** [comment]
> Migrate to a new host and restore backed up data (not sure if this caused the issue or was unrelated?)

Can you check if `listmonk` role exists in PostgreSQL? The default config uses `listmonk` user to connect: https://github.com/knadh/listmonk/blob/master/config.toml.sample#L19

**Comment by dlford** [comment]
I have changed the default user with `LISTMONK_db__user` environment variable, so I am guessing it does not exist in  PostgreSQL

**Comment by dlford** [comment]
The `listmonk` role does not exist in PostgreSQL, because the default user has been changed with `LISTMONK_db__user` environment variable.

```
listmonkdb=# \du
                                     List of roles
  Role name   |                         Attributes                         | Member of 
--------------+------------------------------------------------------------+-----------
 listmonkuser | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
```

**Comment by mr-karan** [comment]
Ah understood. It's the healthcheck then which is pinging if the connection is alive or not.

https://github.com/knadh/listmonk/blob/master/docker-compose.yml#L29 

Can you update `pg_isready -U listmonk` to `pg_isready -U listmonkuser` in your `docker-compose.yml` ?

**Comment by dlford** [comment]
@mr-karan That was it, sorry to waste your time on this silly oversight 🤦, I appreciate the help!

**Comment by tricoos** [comment]
More info: if your user is named `listmonkuser` but your database `listmonk` you would now get another error unless you change the command to `pg_isready -U listmonkuser -d listmonk`
