### ISSUE TITLE
How to load full configuration file?

### ISSUE THREAD

**Issue by diegovargasj** [knadh/listmonk#1156]
Hey! I'm just starting to use Listmonk and I'm having some problems loading all the settings from the config file. Some of them are being reflected in the GUI, but most are not. For instance the SMTP settings or the from_email, it only shows the default values. 
Maybe I'm doing something wrong, it would really help if there was a full config file with all the possible settings. 
Here is my non-working config file:
```
[app]              
address = "0.0.0.0:9000"
admin_username = "******"             
admin_password = "******"
batch_size = 1000   
check_updates = false
concurrency = 10   
enable_public_subscription_page = true
favicon_url = ""
from_email = "Test <noreply@*****>" 
lang = "en"        
logo_url = "http://localhost:9000/public/static/logo.png"
max_send_errors = 1000
message_rate = 10                            
message_sliding_window = false
message_sliding_window_duration = "1h"
message_sliding_window_rate = 10000
notify_emails = [ "******" ]
root_url = "http://localhost:9000"

[db]              
host = "postgres"        
port = 5432
user = "listmonk"            
password = "******"
database = "listmonk"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"

[smtp]
auth_protocol = "none"
email_headers = [ ]
enabled = true
hello_hostname = "******"
host = "smtp"
idle_timeout = "15s"
max_conns = 10
max_msg_retries = 2
password = ""
port = 25
strEmailHeaders = "[]"
tls_enabled = false
tls_skip_verify = true
username = ""
uuid = "2f2de335-7675-4d49-b108-fef911102a93"
wait_timeout = "5s"
```

[Edit] I'm using the latest release version 2.3.0.

**Comment by knadh** [comment]
Hi. This config is incorrect. Please refer to the sample config: https://github.com/knadh/listmonk/blob/master/config.toml.sample

**Comment by diegovargasj** [comment]
Hi @knadh 
Does that mean there is no way of configuring all the settings using the conf file?

**Comment by knadh** [comment]
Yes, that's right. Only `[db]` can be configured via the file.

**Comment by diegovargasj** [comment]
I see... Then it would be a great addition being able to fully configure it with the file!

**Comment by knadh** [comment]
That wouldn't be feasible, unfortunately. Please see this for context: https://github.com/knadh/listmonk/issues/412
