### ISSUE TITLE
axiosError: Network Error listmonk.

### ISSUE THREAD

**Issue by DanRaiss** [knadh/listmonk#1157]
**Version:**
lastest

**Description of the bug and steps to reproduce:**
When i star campain i got axiosError: Network Error listmonk. Anyone facing the same issue? I am using listmonk in docker desktop. Weird is that it was working pretty well at start (even test mail was succesfull), but after i created my 60 lists of subscribers it was broken. I cannot send any mails now, sometimes it whole crash and listmonk-app is restarting/not running.

**Screenshots:**
![image](https://user-images.githubusercontent.com/63979096/214950973-11eaf86d-f34a-4223-bbeb-c7a373311257.png)

**Comment by DanRaiss** [comment]
2023-01-26 22:07:53     /home/runner/work/listmonk/listmonk/cmd/main.go:224 +0x777
2023-01-26 22:07:59 panic: runtime error: invalid memory address or nil pointer dereference
2023-01-26 22:07:59 [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7977f0]
2023-01-26 22:07:59

**Comment by knadh** [comment]
Hi. This bug was fixed here https://github.com/knadh/listmonk/issues/1093. This happens when you have a campaign body that is empty.

**Comment by DanRaiss** [comment]
@knadh thanks for reply, anyway strange bug anyway, because I have the newest version. I use templates for campaign body so i do not need necessary extra content.
