### ISSUE TITLE
recently added hCaptcha support causes public page error when using --static-dir

### ISSUE THREAD

**Issue by dassels** [knadh/listmonk#1158]
**Version:**
 - listmonk: v2.3.0
 - OS: Debian 11

**Description of the bug and steps to reproduce:**
I copied all the latest static files to local as we needed to customize them. In particular "subscription-form.html" would return this error when loading the page:

root@server:user # ./listmonk --static-dir /etc/listmonk/static
2023/01/27 16:00:53 main.go:97: v2.3.0 (448f0e3 2022-11-27T17:52:51Z)
2023/01/27 16:00:53 init.go:132: reading config: config.toml
2023/01/27 16:00:53 init.go:259: connecting to db: localhost:5432/listmonk
2023/01/27 16:00:54 init.go:219: loading static files from: /etc/listmonk/static
2023/01/27 16:00:54 init.go:575: media upload provider: filesystem
2023/01/27 16:00:54 init.go:499: loaded email (SMTP) messenger: password@amazonaws.com
⇨ http server started on 127.0.0.1:9000
2023/01/27 16:01:17 handlers.go:62: template: index.html:32:23: executing "subscription-form" at <.Data.CaptchaKey>: can't evaluate field CaptchaKey in type interface {}

If I remove this code block:

            {{ if .Data.CaptchaKey }}
                <div class="captcha">
                    <div class="h-captcha" data-sitekey="{{ .Data.CaptchaKey }}"></div>
                    <script src="https://js.hcaptcha.com/1/api.js" async defer></script>
                </div>
            {{ end }}

It works fine.

**Comment by knadh** [comment]
The templates in `master` are for the upcoming version v2.4.0. For use for v2.3.0, please copy the templates from https://github.com/knadh/listmonk/tree/v2.3.0
