### ISSUE TITLE
Allow html comments in email-templates static files

### ISSUE THREAD

**Issue by dassels** [knadh/listmonk#1159]
**Is your feature request related to a problem? Please describe.**

Customizing templates for Microsoft Outlook require use of html comments like:

```
<!--[if mso]>
  <table>Show this part as a table with 
        <a href="{{ .URL}}" class="button" style="background: #0077cc;>link</a> 
        so Outlook can style it properly
  </table>
<![endif]-->

<!--[if !mso]><!-->
    <div>hides this from Outlook because it can't style it. Shows for everything else</div>
<!--<![endif]-->

```
However this is not possible since default GO behaviour is to strip out all html comments. Understandably this is for security but causes issues when trying to properly format emails for Outlook (in particular desktop) users.

**Describe the solution you'd like**

It appears there are workarounds, like creating a custom function that will allow insertion of comments to templates:

https://www.calhoun.io/intro-to-templates-p3-functions/  (see "HTML safe strings and HTML comments")

Perhaps something like this can be implemented without impacting security?

**Comment by knadh** [comment]
Hi @dassels. Please refer to this https://github.com/knadh/listmonk/issues/1088#issuecomment-1343838002.

**Comment by dassels** [comment]
Thanks! I did  search around for this issue but was unable to find it.. I'll try it with the 'safe' option.

**Comment by dassels** [comment]
This doesn't seem to work...

```

{{ "<!--[if mso]>
<table role="presentation" cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td style="border-radius: 4px; background: #0077cc;">
             <a class="button" href="{{ .OptinURL }}" style="background: #0077cc; font-family: sans-serif; font-size: 15px; line-hei>
        </td>
    </tr>
</table>
<![endif]-->" | Safe }}
```

After reloading server returns 503 error. 

listmonk@service.service - listmonk mailing list and newsletter manager (service)
     Loaded: loaded (/lib/systemd/system/listmonk@.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-01-28 14:28:58 UTC; 42s ago
    Process: 1018510 ExecStartPre=/usr/bin/mkdir -p ${HOME}/uploads (code=exited, status=0/SUCCESS)
    Process: 1018512 ExecStartPre=/usr/bin/listmonk --config /etc/listmonk/service.toml --upgrade --yes (code=exited, status>
    Process: 1018521 ExecStart=/usr/bin/listmonk --config /etc/listmonk/service.toml --static-dir /etc/listmonk/static (code>
   Main PID: 1018521 (code=exited, status=1/FAILURE)

**Comment by dassels** [comment]
Just putting this here in case anyone else has the same issue. The "safe" function requires all quotes to be escaped and there cannot be any line breaks. So the above should look like this:

`{{ "<!--[if mso]><table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"><tr><td style=\"border-radius: 4px; background: #0077cc;\"><![endif]-->" | Safe }}`

alternative you can write it like this:

`{{ Safe "<!--[if mso]><table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"><tr><td style=\"border-radius: 4px; background: #0077cc;\"><![endif]-->" }}`

Unfortunately this does make customization of Outlook emails a real PIA.
