### ISSUE TITLE
Importing CSV with attributes defined fails to import attributes

### ISSUE THREAD

**Issue by cb3inco** [knadh/listmonk#116]
I receive the following error when trying to import a user with the following attributes:

2020/05/27 07:32:43 skipping invalid attributes JSON on line 1 for 'name@domain.net': invalid character 'o' in literal null (expecting 'u')

My csv looks like this:
`email,name,attributes`
`name@domain.net,First Last,"{""NordVPN"": no, ""CrashPlan"": no}"`

Per your example in listmonk, it appears to be correct, however, it doesn't seem to import. Is this a known issue?

Update: 
I just tried from the individual user to insert:
`{"NordVPN": no, "CrashPlan": no}` 
and resulted in the following error:

`Invalid JSON in attributes
SyntaxError: JSON.parse: unexpected keyword at line 1 column 13 of the JSON data`

**Comment by cb3inco** [comment]
I guess 'no' is not valid? True or False?

**Comment by knadh** [comment]
`no` should be a string, `"no"`. Or you can use JSON bool: `"NordVPN": true`

**Comment by cb3inco** [comment]
Thanks @knadh I ended up using true / false
