### ISSUE TITLE
Make "List-Unsubscribe" settable to a "mailto" link

### ISSUE THREAD

**Issue by NessDan** [knadh/listmonk#1161]
**Is your feature request related to a problem? Please describe.**
The way I'm using List Monk is a little odd (loading the Docker container up locally to send an email blast that's rate-limited.)

Since List Monk isn't accessable to the publice, I'd like to manually unsubscribe my users and would prefer a `mailto:` version of the `List-Unsubscribe` but I'm running into some issues.

First, I've disabled all privacy options:

![image](https://user-images.githubusercontent.com/304269/215294355-c3d211e6-e992-4a46-b37d-f16b59992c9a.png)

Second, I added this custom header to my email:

```json
[
    {
        "List-Unsubscribe": "<mailto:unsubscribe@keyboard.gg?subject=Unsubscribe>"
    },
    {
        "List-Unsubscribe-Post": "List-Unsubscribe=One-Click"
    }
]
```

The email does not show an "Unsubscribe" link though:

| Message | Info |
|--------|---------|
| ![2023-01-28 17_38_34-Testing DKIM and DMARC - kaspro llc@gmail com - Gmail](https://user-images.githubusercontent.com/304269/215294293-d554197f-978d-4552-86a9-f95baf796aa8.png) | ![2023-01-28 17_38_43-Testing DKIM and DMARC - kaspro llc@gmail com - Gmail](https://user-images.githubusercontent.com/304269/215294292-d4032b80-3b2c-493b-b34c-a5fd370979a7.png) |

The headers for the email look like this (**take note of the `list-unsubscribe`s in there**):

```
Delivered-To: kaspro.llc@gmail.com
Received: by 2002:a92:260b:0:b0:304:ba0f:df6d with SMTP id n11csp1817211ile;
        Sat, 28 Jan 2023 14:31:37 -0800 (PST)
X-Google-Smtp-Source: AK7set8gkEYABc2GYcahIs+HU8HF9R5n2XqqN/xK93zItL9rHHGzkG32bSNL+fYVUPNsX2qI3MY3
X-Received: by 2002:a17:903:1208:b0:194:58c7:ab79 with SMTP id l8-20020a170903120800b0019458c7ab79mr3706839plh.63.1674945097514;
        Sat, 28 Jan 2023 14:31:37 -0800 (PST)
ARC-Seal: i=1; a=rsa-sha256; t=1674945097; cv=none;
        d=google.com; s=arc-20160816;
        b=DkBxslA2r/7dPCNEf4brivSfcmzYMA2vyfwQVpOxPfumoI4Y0hjcpXMh3pKFNi9e9W
         xDpxMW0GXvR8zaYyoqoy7yrWCULiLhTRuQ5amqQLmeM/xotAWBcwA9r/EUaToeH/YSD+
         N2pdgtp6iI95rCbYpgvSvPyRjqADIPMrWZuJjR1ZVwEVhp7H/2LyprNIsNOfnDViVXrA
         B8ZSemGFTjl1pAXHKy+NSclzi3nTlxYaCo1YYJm6qcGM6szUXXnijjlwiDGEAFJ8Ztex
         ia2/gz1wDvDsNic6btXxv5RpbPFvzxJBw2Bf2j3HGApOYGrX2r09+xee/9CBhiTtiLvA
         4+BA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=date:from:list-unsubscribe:mime-version:subject:to
         :content-transfer-encoding:list-unsubscribe-post:message-id
         :dkim-signature;
        bh=WFTiCZfrVXqXS9bGTIqtFti+asPWZ7B/MlsBhefwAF0=;
        b=uWzv9G7jNHEF6KzLFV3veFaS4Jo9zML9h4dDAL/9EYLJOiKFmpjlS41k05kG5Z9sU/
         9zbN5VYw0bdPdRAmxEQF629NcVBs8CnGuGDNydcvFXeGvdBCv68Tj/rFkkpJRF/Z5T40
         l/CraGHSvJkdu4z4U8ljuTMOdZNTqpNRSWNXgUyl//Keabow+1iSOU31QBqgP6WQc5W6
         76t+qdPnQaSA6cHc40qv4POKXKlUuvpHMC2feEYTsD+8d6Qm+y+kwVeyL+KQnnNuf9Nu
         BfI9HCFRGHviuzmh3MpOTzESGQXOyWrjkKxBAZlGxkw5AGSld7Q/pIO4EPEXOT68NMRr
         ZEzg==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@keyboard.gg header.s=default header.b=AgyRkl7Z;
       spf=pass (google.com: domain of dan@keyboard.gg designates 198.54.118.204 as permitted sender) smtp.mailfrom=dan@keyboard.gg;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=keyboard.gg
Return-Path: <dan@keyboard.gg>
Received: from MTA-13-3.privateemail.com (mta-13-3.privateemail.com. [198.54.118.204])
        by mx.google.com with ESMTPS id y2-20020a17090322c200b00186989178b0si10050628plg.132.2023.01.28.14.31.37
        for <kaspro.llc@gmail.com>
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Sat, 28 Jan 2023 14:31:37 -0800 (PST)
Received-SPF: pass (google.com: domain of dan@keyboard.gg designates 198.54.118.204 as permitted sender) client-ip=198.54.118.204;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@keyboard.gg header.s=default header.b=AgyRkl7Z;
       spf=pass (google.com: domain of dan@keyboard.gg designates 198.54.118.204 as permitted sender) smtp.mailfrom=dan@keyboard.gg;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=keyboard.gg
Received: from mta-13.privateemail.com (localhost [127.0.0.1]) by mta-13.privateemail.com (Postfix) with ESMTP id 07E4418000A5 for <kaspro.llc@gmail.com>; Sat, 28 Jan 2023 17:31:37 -0500 (EST)
Received: from localhost (d149-67-142-151.col.wideopenwest.com [67.149.151.142]) by mta-13.privateemail.com (Postfix) with ESMTPA id B876518000A0 for <kaspro.llc@gmail.com>; Sat, 28 Jan 2023 17:31:36 -0500 (EST)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=keyboard.gg; s=default; t=1674945096; bh=WFTiCZfrVXqXS9bGTIqtFti+asPWZ7B/MlsBhefwAF0=; h=To:Subject:List-Unsubscribe:From:Date:From; b=AgyRkl7ZwJQh4YjvAJprBgOH6vs+P0Rrrbmcq5XUrOpRm/GcwE86BH8cjuj4UsWOV
	 Vrr5xEdFv47rS8RchCy4YPd5H+oP3bS8qicDI2T9jK00Fd1KcKFRvDcs94mJluGLCh
	 QTWWE6dXYzCJv6d+5VFfsgafH+GIWFvdM5gsPbyxjbxjBNeKag/o9k1cZTF6ux6pk5
	 PbEYVCp8M6ld5eEnqppkIdLbzFRO+j5oT312NPQcJAlpTsL0bBQ3aphFO/slkx6Om5
	 Nie801FsKLTEV9+9mGr/BHlp0WQ0Bs6PuFw1Le8wz7eCuZ3sX+bLcMwP79jTPh1vvi
	 cjvcQIKXipBhg==
Message-Id: <1674945092688494325.1.8003063738867767310@86fbff095eab>
List-Unsubscribe-Post: List-Unsubscribe=One-Click
Content-Transfer-Encoding: quoted-printable
To: <kaspro.llc@gmail.com>
Subject: Testing DKIM and DMARC
Mime-Version: 1.0
X-Listmonk-Subscriber: e3c4e160-4acd-4840-9e4b-e523d2dc638b
List-Unsubscribe: <mailto:unsubscribe@keyboard.gg?subject=Unsubscribe>
X-Listmonk-Campaign: ce906994-eb8d-45aa-8f74-bb446fd5df8b
Content-Type: text/plain; charset=UTF-8
From: "Dan at Keyboard.gg" <dan@keyboard.gg>
Date: Sat, 28 Jan 2023 22:31:32 +0000
X-Virus-Scanned: ClamAV using ClamSMTP

Testing if DKIM and DMARC come through
```

**Describe the solution you'd like**
It would be nice if there was a setting to allow the `List-Unsubscribe` to be settable as a `mailto` address and to skip the `http://` version that's in there by default. (~~Would also like to know why the Unsubscribe link isn't showing up?~~ [It seems the reason it's not showing up is because my email reputation is not high enough.](https://stackoverflow.com/a/28500968/231730))

**Comment by knadh** [comment]
> It would be nice if there was a setting to allow the List-Unsubscribe to be settable as a mailto address

This would involve adding support for POP3 mailbox scanning and processing unsubscribe requests, which is a non-trivial feature. Since this mode of unsubscribing is rarely used anymore, there are no plans of adding this.

**Comment by MaximilianKohler** [comment]
>This would involve adding support for POP3 mailbox scanning and processing unsubscribe requests, which is a non-trivial feature. Since this mode of unsubscribing is rarely used anymore, there are no plans of adding this.

Are you sure about that? See https://github.com/knadh/listmonk/issues/1655#issuecomment-1879313727 where Google itself is using that method, as is the NYT and actionnetwork.org. Plus, [most email providers don't support the URL unsubscribe, only Gmail does](https://www.litmus.com/blog/the-ultimate-guide-to-list-unsubscribe).

Here's an email from actionnetwork.org that is using `List-Unsubscribe: <mailto:` and the popup says it sends an email to unsubscribe you:
![action network unsubscribe](https://github.com/knadh/listmonk/assets/3606996/d0d909e7-65b6-48b2-81c5-8191d076fec8)

I checked the header and it's: `List-Unsubscribe: <mailto:email_xxxxxx.xxxxxxxxxxxxxxx@inbound-parse.actionnetwork.org>`. Couldn't we set that to our personal/business email and the email would contain a listmonk `https://mysite.com/subscription/xxxxxxxxxxxxxxxxx/xxxxxxxxxxxxx` link that we could manually click ourselves? If it forwards/includes a copy of the original message then it could easily contain the listmonk `https://mysite.com/subscription/xxxxxxxxxxxxxxxxx/xxxxxxxxxxxxx` link that we can click.
