### ISSUE TITLE
Error uploading file: open uploads/Test.jpg: no such file or directory

### ISSUE THREAD

**Issue by Codzsters** [knadh/listmonk#1163]
**Version:**
 - listmonk: v2.3.0
 - OS: Railway App

**Description of the bug and steps to reproduce:**
I'm having issues uploading images when using Railway to host this. It just comes up with "Error uploading file: open uploads/Test.jpg: no such file or directory" with I try to upload any image.

Go to Campaigns > Media > drag or upload image into the box and I get the error.

**Comment by knadh** [comment]
I am not sure how storage works with Railway, or whether it's provisioned and attached to listmonk in their installation template. Could you please check with them and update here so that it helps other Railway users also?

**Comment by MaximilianKohler** [comment]
This is not unique to Railway. There are a bunch of threads on this:

- https://github.com/knadh/listmonk/issues/620 - my first.
- https://github.com/knadh/listmonk/issues/943 - UI path is /listmonk/uploads. Nathan9745354 fixed it.
- https://github.com/knadh/listmonk/issues/1169 - my screenshots & @mr-karan's cmds. 
- https://github.com/knadh/listmonk/issues/30 - conflicting info. 
- https://github.com/knadh/listmonk/issues/1163 - railway. 
- https://github.com/knadh/listmonk/issues/894 - mr-karan gives both options. 

I think this is the solution: https://github.com/knadh/listmonk/issues/1169#issuecomment-1674475945

I'll do a pull request for the docs when I get time.
