### ISSUE TITLE
Can someone post a revised listmonk.service file

### ISSUE THREAD

**Issue by tmerrill530** [knadh/listmonk#1167]
I am having some trouble editing up the listmon@.service file to be more generic or rather to reflect where I tossed the listmonk executable and the config.toml file. In my case I am attempting to use /opt/listmonk on a standard Ubuntu server.

**Comment by LarryLambert** [comment]
[Unit]
Description=listmonk
After=network.target

[Service]
Type=simple
ExecStart=/opt/listmonk/listmonk
WorkingDirectory=/opt/listmonk
Restart=always
RestartSec=5
User=listmonk
Group=listmonk

[Install]
WantedBy=multi-user.target

**Comment by alfredosola** [comment]
Hello,
Running Listmonk on Debian 11.
I found that in the `[Unit]` section, this was needed:
`After=postgresql.service`
Otherwise, it started before Postgres and understandably crashed.
