### ISSUE TITLE
Messenger header

### ISSUE THREAD

**Issue by nimabm** [knadh/listmonk#1170]
**Version:**
 - listmonk: [eg: v2.3.0]
 - OS: docker

**Description of the bug and steps to reproduce:**
We write a Messenger for sending SMS and expect when sms send successfully messenger return a 200 header and when sms sends an error messenger to return 400 headers, but it doesn't differ for Listmonk, always it counted in send the message as success.

**Comment by knadh** [comment]
listmonk records an error for non-200 responses from an HTTP postback server. Example:

`2023/02/04 11:33:14error sending message in campaign 2: subscriber b41e6a22-9983-44ec-a347-880c753877fd: non-OK response from Postback server: 400`

Make sure that your HTTP SMS application is returning a 400 to listmonk.

**Comment by nimabm** [comment]
yes I saw s message like this 
error sending message in campaign TEST: subscriber 1814efa1-11ec-41ab-a346-c644fe00d7fd: non-OK response from Postback server: 400

but how can I realize how many SMS are delivered (i mean how many got 200 and how many got 400)

**Comment by knadh** [comment]
Wouldn't the messenger you've written be tracking this? listmonk prints each error in the log, but ideally it should record the number of errors in the database somewhere. Will think about this.
