### ISSUE TITLE
Sendgrid and bounce processing

### ISSUE THREAD

**Issue by malv007** [knadh/listmonk#1177]
Does the SendGrid webhook associate bounces to a particular campaign? It looks like this only works with SES. Is that right? Is there a plan to implement the campaign header parsing/processing for the SendGrid webhook too?
Thanks!

**Comment by knadh** [comment]
It does indeed.

![image](https://user-images.githubusercontent.com/547147/217201606-14a26c32-1b86-48e7-8dd3-28165d4e661b.png)

**Comment by malv007** [comment]
Sorry, I don't think I explained myself correctly. Listmonk can receive bounces from SendGrid, and we can see the information in the Subscribers > Bounces menur, but they don't seem to get linked to a campaign.

Using the SES webhook we can see how the bounces getting linked to the campaign (method ProcessBounce):
https://github.com/knadh/listmonk/blob/eb9f6876b05cfa508977cb59eb049cd23f50a7ef/internal/bounce/webhooks/ses.go#L135 

But the SendGrid webhook doesn't seem to have any logic similar to that. Is there a plan to implement that? Is there a workaround to implement such a function?

We are already adding the X-SMTPAPI header to all of our campaigns in order for SendGrid to include the campaign UUID in their request (as "X-Listmonk-Campaign"), but since the SendGrid webhook in listmonk doesn't parse this information, like the SES one does, then the bounces don't get linked.

@knadh  Are we understanding this right?

**Comment by knadh** [comment]
Ah, understood. If I understand this correctly, you can configure SendGrid to send `X-SMTPAPI: {"X-Listmonk-Campaign": "xxx"}` which will be available in the webhook?

If yes, this should be easy to implement in the upcoming release.

**Comment by malv007** [comment]
No worries, I am sure having to go through all the request/questions isn't easy.

Yes, SendGrid can be configured to send back additional information.

But one thing we have noticed in the bounce information displayed in Listmonk, is that the dashes get eliminated and `X-Listmonk-Campaign` gets turned into `xListmonkCampaign` . See the attached screenshot. Is Listmonk doing that format change in order to display the information? If not it must be SendGrid making that format change.
![image](https://user-images.githubusercontent.com/36649875/217344652-9b89773c-39e6-4639-97bb-3daa80a82141.png)

But when I look at the SendGrid logs I can see the dashes. See screenshot.
![image](https://user-images.githubusercontent.com/36649875/217344900-5e9e181c-d77a-437b-9497-57cfa8ac077e.png)

It would be awesome to get this implemented. Let me know in case you need me to test anything. Thanks a lot!

**Comment by knadh** [comment]
That would be SendGrid stripping dashes. listmonk stores the metadata as-is.

This is straight forward to implement. Will include this in the upcoming version. Thanks for highlighting this.
