### ISSUE TITLE
enhancement: link view/click link with email addres (or user)

### ISSUE THREAD

**Issue by cb3inco** [knadh/listmonk#118]
I didn't see this asked anywhere, but would love to see views and link clicks associated with a user in the list as other services do. Not sure if this can be added to the to-do list or not. I'm by no means a developer so I wish I could help with this. 

Really liking this tool as I pushed my first campaign to 800+ users (internal) and it worked flawlessly. Thank you so much for making this available.

**Comment by knadh** [comment]
Cheers @cb3inco :) It's definitely on the to-do.

**Comment by knadh** [comment]
It just occurred to me, for the time being, you can use the `Export data` option on the subscriber popup to get this information.

![image](https://user-images.githubusercontent.com/547147/83413281-33f4e500-a439-11ea-9508-c4d5d631bd09.png)

**Comment by knadh** [comment]
The status on this issue has changed. Please see https://github.com/knadh/listmonk/issues/193.
