### ISSUE TITLE
Question about how the "Views" statistic works

### ISSUE THREAD

**Issue by michaelbutler** [knadh/listmonk#1180]
Relates to https://github.com/knadh/listmonk/issues/1025 I suppose; I have been experiencing my campaigns getting a total number of "Views" higher than how many were "Sent". 

For example, for one campaign, `573` "Sent" and I have `620` views. If I have more views than number sent, what could that mean? My guess is that for some end users, the server-side email software does an HTTP request for the tracking pixel at one IP Address / User Agent, then the user's own browser/device makes another HTTP request later for the tracking pixel, resulting in more than one view for a single distinct email message. Is this likely correct?

**Comment by knadh** [comment]
Hi @michaelbutler. That would be the same e-mail being viewed multiple times. This depends on the individual subscriber tracking privacy setting. Please refer to these:

https://github.com/knadh/listmonk/issues/676
https://github.com/knadh/listmonk/pull/680

**Comment by MaximilianKohler** [comment]
I've always had `Individual subscriber tracking` enabled yet I experience the same issue shown here https://github.com/knadh/listmonk/issues/676#issuecomment-1869815066.
