### ISSUE TITLE
Too many messages in this connection.

### ISSUE THREAD

**Issue by ulmeanu** [knadh/listmonk#1181]
I tried sending a campaign of 441 and it shows that there were all sent, however, the views/clicks/bounced are not updating and I got errors that they were never actually sent, as you can see here:

![listmonk1](https://user-images.githubusercontent.com/106371509/217627245-1679a115-878f-42d9-a83f-8cdc20faaecd.PNG)
![listmonk2](https://user-images.githubusercontent.com/106371509/217627258-d9f61446-b10a-4551-b40f-87384bad742f.png)

**Comment by knadh** [comment]
Your SMTP server is possibly throttling the messages. You can try adjusting the send rates in Settings -> Performance.

**Comment by ulmeanu** [comment]
I tested it before with 1/2 subscribers and it worked

**Comment by profmatheuspassos** [comment]
@ulmeanu you can change in the Performance tab, last option (it's in Portuguese in the image), then you adjust and asks it to send a maximum of 8 e-mails per minute - thus 8 e-mails x 60 min = 480 e-mails per hour.

![Captura de Tela 2023-02-25 às 09 32 50](https://user-images.githubusercontent.com/40068795/221345051-8934964f-1fbc-4992-b8f9-34fa750d8720.png)
