### ISSUE TITLE
Wrong day displayed, while date is correct

### ISSUE THREAD

**Issue by Turney1337** [knadh/listmonk#1182]
**Version:**
 - listmonk: 2.3.0
 - OS: Ubuntu Server 22.04 / official Docker

**Description of the bug and steps to reproduce:**
While listmonk uses the correct time and date, it display the wrong day.
For example: timestamp shows 09 Feb 23, which is a Thursday, but listmonk displays it as a Friday. (see screenshot)
While the date is correct, it seems to be one day too far in the future.

**Screenshots:**
![day](https://user-images.githubusercontent.com/91729207/217791930-f1c0b5d8-3173-44aa-b46e-81f986ad28e3.PNG)

**Comment by Margu86** [comment]
I have the same error on my machine

- listmonk: 2.3.0
- OS: Ubuntu 22.04.1
