### ISSUE TITLE
Campaign shows all sent but some messages failed

### ISSUE THREAD

**Issue by admoya** [knadh/listmonk#1183]
**Version:**
 - listmonk: v2.3.0
 - OS: Docker v20.10.17

First, thank you for the amazing project! I intend to contribute in the future where I can. 

**Description of the bug and steps to reproduce:**
I sent my first campaign to more than a couple of subscribers (60), and the UI reported that it completed and all messages were sent (60/60). However the logs showed 19 messages failed, and that the campaign completed while they were still sending. 

I then collected the 19 email addresses and sent them as test messages from the same campaign, but from that batch 2 failed with the same message. Finally I sent a test message to just those two and they went through. 

Other information:
* I am using Gmail SMTP, with my Google Workspace account and app authorization. 
* I left all the SMTP settings at the defaults for the Gmail preset
* I had the performance settings at default (Concurrency = 10, Message Rate = 10)

It feels like I got rate limited by Gmail, so I dropped those performance settings down, but I can't find any documentation from Google about an SMTP rate limit except for the daily Gmail send limits (which I am nowhere near). I have not yet tested with the lower performance settings. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/10676387/217856775-8178f71c-53ff-43fb-8c79-0ed6a8d8209e.png)

**Comment by knadh** [comment]
`EOF` typically means that the connection was abruptly closed by the target. An SMTP imposing a rate limit could just uncleanly terminate the connection throwing an EOF, but I'm not sure if Google behaves his way. Please do double check the port and TLS settings.

**Comment by admoya** [comment]
Thanks for responding so quickly @knadh. I checked that the settings are correct based on [this page from Google](https://support.google.com/mail/answer/7126229?hl=en#zippy=%2Cstep-change-smtp-other-settings-in-your-email-client).

Please correct me if I am wrong, but if this was a configuration issue like that, wouldn't the test emails also fail? 41/60 emails went through on the first try in this case, then 17/19 went through on the second try, and 2/2 the last try. 

Also, is it expected behavior that the campaign ends while messages are still not sent, and that the UI shows that they were all send even though some failed?

**Comment by admoya** [comment]
Just as an extra datapoint, I just ran a little experiment:
I added 60 variations of my email (`myemail+1@gmail.com, myemail+2@gmail.com, ...`) to a list, and sent two campaigns to that list with the following settings:
* Max connections = 5, Concurrency = 2, Message rate = 1 ---> success
* Max connections = 10, Concurrency = 10, Message rate = 10 (default) ---> five messages failed with the same error as above

So it does feel to me like some kind of rate limit or maximum connection limit on Google's end, but I don't know enough to be sure. However I still wonder if it is the expected behavior that Listmonk reports those emails as being sent even though they end with an error.
