### ISSUE TITLE
TrackLink not evaluating URL Template String parameters

### ISSUE THREAD

**Issue by NessDan** [knadh/listmonk#1184]
**Version:**
 - listmonk: 2.3.0
 - OS: Docker Linux

**Description of the bug and steps to reproduce:**
So when trying to setup a Stripe payment link with tracking, the prefilled email part of the URL stops working. Really simple test:

These both work when you send an email. The email is autofilled on Stripe too:
* Static email + tracklink: `<a href="https://buy.stripe.com/test_dR62bF8b47Bu3h6dQQ?prefilled_email=dan@keyboard.gg@TrackLink" target="_blank">Pay Here</a>`
* Dynamic email w/o tracklink: `<a href="https://buy.stripe.com/test_dR62bF8b47Bu3h6dQQ?prefilled_email={{.Subscriber.Email}}" target="_blank">Pay Here</a>`

This does NOT prefill the email:
* Dynamic email + tracklink: `<a href="https://buy.stripe.com/test_dR62bF8b47Bu3h6dQQ?prefilled_email={{.Subscriber.Email}}@TrackLink" target="_blank">Pay Here</a>`

And I think this is because the TrackLink is not letting the template string get processed (confirmed in 3rd screenshot I think.)

**Screenshots:**
![2023-02-10 00_59_51-keyboard gg](https://user-images.githubusercontent.com/304269/218014478-fdbb83fb-197f-4504-a399-d1de95bb69af.png)
![2023-02-10 00_59_30-keyboard gg](https://user-images.githubusercontent.com/304269/218014481-ff4e5533-b121-418b-99f2-2fa57789ade5.png)
![image](https://user-images.githubusercontent.com/304269/218014714-3e4011d9-c1fa-4b96-a2da-84c0f8802b21.png)

**Comment by knadh** [comment]
Please see this: https://github.com/knadh/listmonk/issues/1147

**Comment by titouan13** [comment]
Hi,

To achieve what you wanted @NessDan (it could be useful to somebody else), you can do:
`<a href="{{ TrackLink (cat "https://buy.stripe.com/test_dR62bF8b47Bu3h6dQQ?prefilled_email=" .Subscriber.Email) }}" target="_blank">Pay Here</a>`

That's the best way I found as #1147 doesn't solve this problem.
