### ISSUE TITLE
POP Bounce Mailbox - Leave a Copy on the Server

### ISSUE THREAD

**Issue by NessDan** [knadh/listmonk#1185]
**Is your feature request related to a problem? Please describe.**

I use my main email for campaigns because I want users to feel like they can respond back and start a discussion (which they often do!)

One issue I've run into is that bounced emails require manual work from me to remove. I tried setting up the "Bounce mailbox" POP feature, but realized too late that POP by default deletes all messages on a server. This is a problem for me because I'll often still be having email conversations with users and suddenly every email I had is deleted.

Because of that, I wanted to implement a common feature ([at least in mail clients](https://support.tigertech.net/lmos)) to _leave an email copy on the server_.

**Describe the solution you'd like**

Something like the below red toggle would be nice! I started looking into it already and [if this is the section of the POP code](https://github.com/knadh/listmonk/blob/49f20f33dbe2a25e10f773dc1ea3ca781a01672b/internal/bounce/mailbox/pop.go#L179) that deletes all the messages on the server, I could go and add a toggle option and wrap this in an `if-statement`!

![mail keyboard gg_admin_settings](https://user-images.githubusercontent.com/304269/218037633-41872375-c88c-4a5f-ac55-1149e01caeaf.png)

**Comment by knadh** [comment]
Hi @NessDan. It is not possible to scan a POP mailbox for bounces and not delete those messages. Unlike IMAP, pop has no state management (and can't tell between read and unread messages), so every scan will result in a full mailbox scan over the same messages every time.

The standard practice is to dedicate a mailbox specifically for bounces and set that address as the `From` address.

**Comment by bdezso** [comment]
Hi @knadh,
Why can't we leave the copy on the server? I understand that it's okay to use POP, which will delete the mail from the mailbox, but we could store it elsewhere, like in a database or a bucket, right?

For me, I would feel more at ease if I could occasionally check some bounce-back emails, just to ensure that everything is okay.

**Comment by knadh** [comment]
> It is not possible to scan a POP mailbox for bounces and not delete those messages. Unlike IMAP, pop has no state management (and can't tell between read and unread messages), so every scan will result in a full mailbox scan over the same messages every time.

@bdezso. If you really need to retain bounce e-mails, you should setup a filter/rule to copy it or forward it elsewhere in your mailbox provider.

**Comment by bdezso** [comment]
@knadh You're right, it can easily be resolved at the mailbox level, yet I still think it would be a nice feature to have built into Listmonk. If it's not on the roadmap, then I'll go with the forwarding workaround. Thanks for the fast response... and happy christmas! 🎅

**Comment by filipesmedeiros** [comment]
Hello. What I don't quite understand is why we need to delete _all_ messages, and not just the bounces. This seems, at least to me, to invalidate completely the option of using a "normal" POP3 inbox. It needs to be a dedicated one, or else we will have all our messages deleted, right?

**Comment by filipesmedeiros** [comment]
Update: this behaviour just deleted our entire inbox… luckily we have a backup.

But this should really have stronger warnings. It should be clearly stated that a designated/separated inbox must be used, otherwise you will delete your whole inbox.

I understand _why_ this is the case, but it is not obvious on first glance, I think.
