### ISSUE TITLE
Error PostgreSQL "duplicate key value violates unique constraint" when insert exist subscribers.

### ISSUE THREAD

**Issue by saginsa** [knadh/listmonk#1187]
**Version:**
 - listmonk: v.2.3.0

**Description of the bug and steps to reproduce:**
When we use API method to insert subscribers (POST /subscribers), Listmonk create insert without attempting to find such an email in the table.
If user exist - it create multiple error in postgres, and i means multiple empty strings in table.
Fact, that sequencions has +1 in his numeric.

I think it's important for system performance.

**How fix it? Find exist user before insert, and stop insert operation.**

**Screenshots:**
![image](https://user-images.githubusercontent.com/85064689/218591083-062f1256-4ed0-4aec-b02d-b7e05c5a87aa.png)

**PostgreSQL log-error:**

{
"backend_type":"client backend"
"command_tag":"SELECT"
"connection_from":"localhost:45944"
"context":""
"database_name":"listmonk"
"detail":"Key (email)\=(saginsa@yandex.ru) already exists."
"error_severity":"ERROR"
"hint":""
"hostname":"*******"
"internal_query":""
"internal_query_pos":"0"
"leader_pid":"0"
"location":""
"message":"duplicate key value violates unique constraint "subscribers_email_key""
"process_id":"2952327"
"query":"WITH sub AS ( INSERT INTO subscribers (uuid, email, name, status, attribs) VALUES($1, $2, $3, $4, $5) RETURNING id, status ), listIDs AS ( SELECT id FROM lists WHERE (CASE WHEN CARDINALITY($6::INT[]) > 0 THEN id\=ANY($6) ELSE uuid\=ANY($7::UUID[]) END) ), subs AS ( INSERT INTO subscriber_lists (subscriber_id, list_id, status) VALUES( (SELECT id FROM sub), UNNEST(ARRAY(SELECT id FROM listIDs)), (CASE WHEN $4\='blocklisted' THEN 'unsubscribed'::subscription_status ELSE $8::subscription_status END) ) ON CONFLICT (subscriber_id, list_id) DO UPDATE SET updated_at\=NOW(), status\=( CASE WHEN $4\='blocklisted' OR (SELECT status FROM sub)\='blocklisted' THEN 'unsubscribed'::subscription_status ELSE $8::subscription_status END ) ) SELECT id from sub;"
"query_id":"0"
"query_pos":"0"
"session_id":"63eaaa83.2d0c87"
"session_line_num":"276"
"session_start_time":"2023-02-14T00:24:19+03:00"
"sql_state_code":"23505"
"transaction_id":"19341791"
"user_name":"listmonk"
"virtual_transaction_id":"16/172786"
}

**Comment by knadh** [comment]
Can you share the the POST request? POSTing an existing e-mail address should return a clean message like this:

```shell
curl 'http://localhost:9000/api/subscribers' -X POST \
   --data-raw '{"email":"anon@example.com","name":"anon","status":"enabled","attribs":{}, "lists":[1]}'
```

```json
{"message":"E-mail already exists."}
```

**Comment by saginsa** [comment]
Yes we have report from API "message":"E-mail already exists." )))

```
curl 'http://localhost:9000/api/subscribers' -X POST \
   --data-raw '{"email":"saginsa@yandex.ru","name":"saginsa@yandex.ru","status":"enabled"}'
```

`{"message":"E-mail существует."}`

But if we see database logs - we have multiple log error.

I think it is logically wrong to try to insert data with an existing key into the database, and observe errors on the part of the database.

This clogs the logs, and inflates the table with erroneous inserts that were subsequently rolled back by the Base of this backward.

**Comment by knadh** [comment]
This is working as expected then.

> I think it is logically wrong to try to insert data with an existing key into the database, and observe errors on the part of the database.

Not at all. In fact, this is the correct use of unique keys in a relational database. You can try inserting a new record without knowing whether the e-mail exists in the database or not, inspect the error (unique key violation), and then act accordingly. `UPSERT` is an extension of this.

Otherwise, it would be necessary to get a record every time to check if it exists before it is inserted, which is expensive.
