### ISSUE TITLE
enhancement: Max message rate per rolling window

### ISSUE THREAD

**Issue by RaghavSood** [knadh/listmonk#119]
Many SMTP services such as AWS SES and other commercial options enforce a max message rate per rolling window (usually 24h).

This rate often tends to be in the 5000-50000 range for most accounts.

Currently, when emailing a large list, the lowest possible rate achievable on listmonk is 86400/day (`concurrency=1`, `message_rate=1`). 

Adding an option for a `max_message_rate` and `max_message_rate_window` would help simplify integration with such relay options.

**Comment by knadh** [comment]
Hadn't thought about moving windows. Will look into this.

**Comment by FelixDz** [comment]
Same stands for small shared hosting providers. Mine's having a per-hour limit so having the ability to configure rolling windows limits would be awesome. It also helps not beeing flagged as spam when your hosting provider isn't a well-known one.

**Comment by alehano** [comment]
+1

**Comment by FelixDz** [comment]
@knadh any news regarding this ? I'm new to Go, but if you can point me to the code responsible for queue population & sending, maybe I can try to work on this. Any useful resource would also be appreciated of course !

**Comment by knadh** [comment]
I haven't had time to look into this in detail, but it's a bit tricky. There are multiple async workers that send push out messages from multiple campaigns. Synchronising them to jointly wait for X time when hitting the window limit, have to figure this out. I'll try and look into this soon. In the meanwhile, you can take a look at `internal/manager/manager.go` if you'd like to give it a go.

**Comment by knadh** [comment]
This is done https://github.com/knadh/listmonk/commit/027261793f6971620b7e6ac5f5ae3b90880b8a72 and will be available in the next release. Figured out a simple way to achieve this across multiple campaigns.

![image](https://user-images.githubusercontent.com/547147/105623351-0a148680-5e3f-11eb-9e74-94863f9d0d5e.png)

**Comment by Hussienfahmy** [comment]
I enabled this feature and set it to 90 message and the duration is 1 hour, but listmonk does not respect that and keep sending!!

![Uploading Screenshot_2022-05-25-23-24-17-451_com.android.chrome.jpg…]()
