### ISSUE TITLE
More precise time for scheduled posts

### ISSUE THREAD

**Issue by TychoCeltCast** [knadh/listmonk#1195]
**Is your feature request related to a problem? Please describe.**
Whilst using the schedule tool for campaigns I get thrown off when the time is only shown in whole hours (unless it's less than 1 hour).
<img width="734" alt="Screenshot 2023-02-19 at 08 14 23" src="https://user-images.githubusercontent.com/107351632/219934392-cccf9d87-19e5-4282-ba8a-4a91616aac3d.png">
<img width="207" alt="Screenshot 2023-02-19 at 08 14 25" src="https://user-images.githubusercontent.com/107351632/219934400-5d025476-f023-49ef-bea3-e2876c42788e.png">

**Describe the solution you'd like**
I would like to see the minute time added for scheduled posts with less then 24h.
In example screenshot above it would show: 1 hour, 15 minutes.
Even nicer would be to use something like Moment.js toNow features
https://momentjs.com/docs/#/displaying/tonow/

Thank you for your consideration

**Comment by knadh** [comment]
Good spot :) Will fix this.

**Comment by knadh** [comment]
https://github.com/iamkun/dayjs/blob/dev/src/plugin/relativeTime/index.js

Looks like there's no easy way to do this with the dayjs/relativeTime plugin that listmonk uses. Will leave this open in case anyone wants to add a fix.
