### ISSUE TITLE
Add validator to email format

### ISSUE THREAD

**Issue by saginsa** [knadh/listmonk#1196]
I found in our ListMonk database multiple fail email.
For example:

- _ialyakina@cherbsl
- _info@bes
- _info@ed
- _info@fer
- _info@ferto
- _info@fertoing
- _info@lips
- _info@msk-energo.r
- _info@spb
- _info@the
- _info@thermotechno.r

Can we add email field verification to the regular season for subscribers you create?
For example simple variant - /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/

**Comment by knadh** [comment]
listmonk uses `mail.ParseAddress()` from the Go stdlib that validates the e-mails based on RFC 5322. The above e-mails are valid as per the standard.

If you're collecting subscriptions from an external form, you could setup a page that does custom validation and then posts it to listmonk using the API.
