### ISSUE TITLE
401 unauthorized when trying to use the listmonk API

### ISSUE THREAD

**Issue by flashdens** [knadh/listmonk#1197]
Hello,

I'm a newbie when it comes to programming in general and I'm encountering an issue which I think is easy to solve, but can't find any sources which could help me. 

Having installed listmonk, I launched it on localhost and I'm trying to write a simple program in JS that creates a new subscriber and adds them to a list. However, I'm struggling with the 401 unauthorized error, followed by a CORS „Access-Control-Allow-Origin missing header” error. I was trying to dig the web for a solution, but seem to be unable to find one. It seems like the server is responsible for handling the headers - is there a way to configure them on localhost?

I'd be grateful for a solution!
peace

**Comment by rikizkunn** [comment]
it not work on pico too, it says 401 Unauthorized

**Comment by satyamskillz** [comment]
Cors error usually occurs when the server (Listmonk) blocks requests coming from an unknown server or IP address. I think Listmonk allows requests from anywhere, you should try using the Postman desktop app to test APIs.

First, configure environment variables in the `config.toml` file
1. https://listmonk.app/docs/developer-setup/#first-time-setup
2. https://listmonk.app/docs/installation/#mounting-a-custom-configtoml
3. https://listmonk.app/docs/configuration/#environment-variables

These credentials are used to log in to the dashboard and call APIs with basic auth.  
admin_username = "listmonk"
admin_password = "listmonk"

If you are using NodeJS or ReactJS:
```
 axios.post("http://<Linkmonk Domain>/api/subscribers", {
		name: "Full Name of user",
		email: "user@gmail.com"
		attribs: {
                            age: 24,
                            gender: "male"
                },
		status: "enabled",
		lists: [3],
	},{
		auth: {
			username: LISTMONK_app__admin_username,
			password: LISTMONK_app__admin_password,
		},
	}
);
```
If you are still facing the error, let us know.

**Comment by knadh** [comment]
listmonk doesn't set any CORS headers. To customize, you'll have to put it behind something like Nginx and set the desired headers.

That said, please do not expose the subscription endpoint + API credentials to webpages! That exposes full admin access. There's a public API specifically for direct integration that you can use.

```
POST /api/public/subscription
{
name string,
email string
list_uuids []string
}
```

**Comment by flashdens** [comment]
I think this call is yet to be documented
