### ISSUE TITLE
Have the possibility to have email without name

### ISSUE THREAD

**Issue by yodatak** [knadh/listmonk#1202]
Hi thanks for this Awsome tool we want to use it to make newsletter for my trade union and sometimes workers don't want to share theirs name.

Do you think it a good idea or not to implement this?

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/issues/967

**Comment by yodatak** [comment]
Thanks when I use the CSV import the lack of filed name made the import failed so that's why I will think it's not optional sorry for duplicate

**Comment by knadh** [comment]
Yes, it isn't optional for the reasons mentioned in the previous issues. You could just use the same e-mail value in the name field in your CSV.
