### ISSUE TITLE
In the subscribe public form have the possibility to had attributes 

### ISSUE THREAD

**Issue by yodatak** [knadh/listmonk#1203]
Thanks again for your help and Awsome app, in my trade union we want to have workers to answer some question like where does you work (town) and in witch industry by exemple.

It could be useful for us to make specific newsletter for different people.

**Comment by knadh** [comment]
Thanks @yodatak. Please refer to this: https://github.com/knadh/listmonk/issues/105

The ideal way to achieve this is to create your own custom form page and use the listmonk API internally to record the subscriber information.
