### ISSUE TITLE
Problem loading custom i18n files

### ISSUE THREAD

**Issue by d-kersten** [knadh/listmonk#1204]
Hi,

I host listmonk on railway.app using this template: https://github.com/railwayapp-templates/listmonk

I have added an `i18n` folder to the repository and copied the `en.json` file into this folder while changing some texts inside the file. Additionally, for testing I added the same file as a new language, `en-US.json`.

I added the the `--i18n-dir=/path/to/dir` flag to the listmonk command as described here: https://listmonk.app/docs/i18n/#customizing-languages

I tried different things, currently the Dockerfile looks like this:

```
FROM listmonk/listmonk:latest
ARG PORT ADMIN_PASSWORD ADMIN_USERNAME PGDATABASE PGHOST PGPASSWORD PGPORT PGUSER
COPY config.sh ./config.sh
COPY i18n ./i18n
RUN chmod +x ./config.sh && ./config.sh
RUN ./listmonk --idempotent --yes --upgrade --i18n-dir=./i18n || ./listmonk --install --yes --upgrade --i18n-dir=./i18n

```

With this configuration, the deployment on railway.app works. The build log looks like this (excerpt):

```
#6 [2/5] COPY config.sh ./config.sh
﻿#6 sha256:e0059f3af563ca0dc97a6d92823c2f57d5842dbd54f264d92dffa98bceb8b5b3
﻿#6 CACHED
﻿ 
﻿#7 [3/5] COPY i18n ./i18n
﻿#7 sha256:f693fda28a77247244d9de2cd078ad7d74aae3a9a660a783dc0e72fb2f06bc3e
﻿ 
﻿#7 DONE 0.1s
﻿ 
﻿#8 [4/5] RUN chmod +x ./config.sh && ./config.sh
﻿#8 sha256:0898f9c5060ab6de75e4e3eacea967e4e78d807cd908b038867cdd3624022d3b
﻿ 
﻿#8 DONE 0.3s
﻿ 
﻿#9 [5/5] RUN ./listmonk --idempotent --yes --upgrade --i18n-dir=./i18n || ./listmonk --install --yes --upgrade --i18n-dir=./i18n
﻿#9 sha256:a26a080104adefe65c2e225f84503d7afbc6db55a7d72795412669f13cb62db1
﻿ 
﻿#9 0.416 2023/02/22 14:35:03 main.go:97: v2.3.0 (448f0e3 2022-11-27T17:52:51Z)
﻿#9 0.416 2023/02/22 14:35:03 init.go:132: reading config: config.toml
﻿#9 0.416 2023/02/22 14:35:03 init.go:259: connecting to db: containers-us-west-165.railway.app:5470/railway
﻿#9 0.486 2023/02/22 14:35:03 init.go:210: loading i18n files from: ./i18n
﻿#9 0.498 2023/02/22 14:35:03 upgrade.go:62: no upgrades to run. Database is up to date.
﻿#9 DONE 0.5s
```

And the deploy log like this:

```
2023/02/22 14:35:18 main.go:97: v2.3.0 (448f0e3 2022-11-27T17:52:51Z)
﻿2023/02/22 14:35:18 init.go:132: reading config: config.toml
﻿2023/02/22 14:35:18 init.go:259: connecting to db: containers-us-west-165.railway.app:5470/railway
﻿2023/02/22 14:35:18 init.go:575: media upload provider: filesystem
﻿2023/02/22 14:35:18 init.go:499: loaded email (SMTP) messenger: username@smtp.yoursite.com
﻿⇨ http server started on [::]:9000
```

Still my custom texts from `en.json` don't appear in the UI. Also the second language `en-US` that I added for testing purposes does not appear in the language dropdown on the admin settings page.

I can confirm that the language files have been copied from the repository and are available during build.

I found this script: https://github.com/knadh/listmonk/blob/master/scripts/refresh-i18n.sh

Do I need to run this somehow manually?

Thanks for reading and I'd be glad about any hint.

**Comment by knadh** [comment]
I am not familiar with the Railway environment, unfortunately. @mr-karan something to do with the Docker config?

**Comment by d-kersten** [comment]
I got it working. I had to add `./listmonk --i18n-dir=./i18n` as a start command to railway as described here: https://docs.railway.app//deploy/deployments#start-command
