### ISSUE TITLE
Opt-in workflow review

### ISSUE THREAD

**Issue by malv007** [knadh/listmonk#1205]
We have been using listmonk for a few months. We love how straight forward it is, and the fact that we could easily integrate it with our internal processes via the API. We recently sent a survey to our subscribers to gather feedback about our service, and one of the things we realized is that a relatively high percentage of users thought that they were subscribed to our newsletter service, when in fact they weren't. We dug a bit deeper and found out that when our subscribers clicked on the "confirm subscription" button, that is in the "Confirm, subscription" email, thought that they were already subscribed, when in fact they also needed to click on the "Confirm subscription" button on the following page. The current subscription workflow is:

1) Registration form: user enters info and click on button
2) Confirm subscription email: user clicks on button to confirm
3) Confirm subscription page: user click on button to confirm
4) Subscription confirmed page: subscription completed

We were wondering whether this workflow could be reviewed to reduce friction and maximize the number of users that complete the subscription process successfully.

We thought of two options, but it would be great if we could gather other ideas.

- Perhaps rewording some of the sentences will give users more clarity as to the step they are in within the subscription process
- Skip step 3 altogether, step 2 could take you directly to step 4

Thanks!

**Comment by knadh** [comment]
You can use this piece of Javsacript to auto-submit the confirmation form on page load. 

Paste in Settings -> Appearance -> Public [tab] -> Custom Javascript

```javascript
document.querySelectorAll('input[name=confirm]').forEach((e) => {
	e.closest('form').submit();
});
```

**Comment by malv007** [comment]
Thanks! We will try that out.

**Comment by les-les** [comment]
works pretty well ... 

1. Registration form: user enters info and click on button
2. Confirm subscription email: user clicks on button to confirm
3. Subscription confirmed page: subscription completed

THX ! a fine and simple double-opt in 

if your email client checks links ... you might be subscribed by your anti virus program ;) 


br LES

**Comment by knadh** [comment]
This is now a feature (https://github.com/knadh/listmonk/commit/45e85e3fb682ba9930c5f357ee740c29c3f73e04). Will be available in the next release.

<img width="442" height="158" alt="Image" src="https://github.com/user-attachments/assets/7f75117f-ed52-42c8-bf61-fd58df1d00f4" />
