### ISSUE TITLE
list-unsubscribe headers issue

### ISSUE THREAD

**Issue by rpmcoding** [knadh/listmonk#1206]
**Version:**
 - listmonk: v2.3.0
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**
Include list-unsubscribe header is enabled in settings at /admin/settings

I can see the headers are in the received email: 

List-Unsubscribe-Post: List-Unsubscribe=One-Click
List-Unsubscribe: <https://[redacted_for_privacy].com/subscription/42999a0f-bf14-4379-b55a-25472c2f15b4/48e09d05-9b46-4bc3-808a-41e6787151a2>

However, the unsubscribe link is not displayed next to the email address in Gmail as expected.

Also, if you click on report as spam in Gmail, I would expect it to offer you to unsubscribe rather than just report as spam/complaint.

**Comment by knadh** [comment]
Maybe Gmail doesn't show it for all senders. Found this old post that suggests this: https://www.zettasphere.com/gmail-email-unsubscribe-header/
