### ISSUE TITLE
Unable To Import CSV

### ISSUE THREAD

**Issue by thecodingrasta** [knadh/listmonk#1207]
**Version:**
 - listmonk: v2.3.0
 - OS: Docker (Railway App)

**Description of the bug and steps to reproduce:**
I am attempting to import a CSV file which is encoded in UTF-8 and follows the EXACT same format as the example. I select the List and I upload the file but nothing happens, no records are imported, no errors displayed, nothing.  

![image](https://user-images.githubusercontent.com/102020625/220940768-a4bd19c7-dd64-4349-838a-41f8173726de.png)

I also found another issue. When selecting 'Stop Import' and navigating away from the Import page, when I attempt to import a CSV file again I receive the below:

![image](https://user-images.githubusercontent.com/102020625/220940989-84057ec1-357f-4a05-bb61-7cfb0f704ebb.png)

I've mentioned these issues on #1201 but this has been closed, hence the new submission.

**Comment by thecodingrasta** [comment]
@knadh

**Comment by knadh** [comment]
Would it be possible to e-mail me (kailash [at] nadh [dot] in) the file with just a couple of records? I'm unable to reproduce this issue and entries with non-ASCII strings in name and e-mail also are imported just fine.

![image](https://user-images.githubusercontent.com/547147/221395024-ef9f0bda-c62c-4735-be9f-2dbb08ab8dd5.png)

**Comment by ralfonso-directnic** [comment]
I'm having the exact same issue, installed via docker compose, otherwise working fine. I've sent you a same of the import

**Comment by ralfonso-directnic** [comment]
@thecodingrasta @knadh I had the same issue, but downing the container and restarting fixed it.  Ymmv

**Comment by marciuz** [comment]
I experienced the same problem. 
I had the feeling that it was a rights issue. I then assigned the entire directory where the listmonk executable is located to a user 'listmonk'. The problem changed: now it seems that the file is imported, but it still stops at 40,000 users (out of 51,000 that I would like to import).

In any case, I ask that the issue be reopened, as it is not resolved at all.

**Comment by marciuz** [comment]
Uhm, I retried and now is freezed... 

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/1354643/233731974-8752c079-3b83-4f86-b590-b962ebafec7c.png">
