### ISSUE TITLE
Step-by-step guide on how install and set up Listmonk on a server

### ISSUE THREAD

**Issue by rameerez** [knadh/listmonk#1208]
I recently had to install Listmonk on a server. I ended up using an AWS Lightsail instance, and I actually spent quite a bit of time figuring out the right setup and making it work with Nginx, SSL, AWS S3 and AWS SES.

I did a writeup of the steps I took to get everything working – thought it might be useful for some of the folks here. It's technical, but I tried to make it as beginner-friendly as possible.

[Here](https://rameerez.com/free-mailchimp-alternative-email-marketing-service/#listmonk-tutorial) is the guide.

Please let me know any feedback!

**Comment by benstaf** [comment]
- I didn't find how to handle bounces and complaints with AWS SES
- How to set up the AWS SES API

**Comment by rameerez** [comment]
@benstaf:

 - If I'm not mistaken, Listmonk automatically handles bounces as long as the "Enable bounce processing" toggle in the "Bounces" tab in Settings is active. IIRC it's active by default and the default action seems to be to add the address to the blocklist after two bounces. You can also add avanced functionality if you'd like to further process bounces by listening to the [bounces webhook](https://listmonk.app/docs/bounces/), and you can also enable a bounce mailbox – but these advanced options are not covered in my "How to install Listmonk" tutorial
 
 - The AWS SES setup is covered in step 12: "Configure Listmonk to send email through AWS SES" – this sets up Listmonk to send email using SES. If I'm missing something you'd like to see implemented please let me know and I'll try to update the tutorial

**Comment by benstaf** [comment]
- handling bounces and complaints is usually done with AWS SNS, but I didn't find it in the tutorial:
- https://aws.amazon.com/blogs/messaging-and-targeting/handling-bounces-and-complaints/

- does Listmonk distinguishes between soft bounces and hard bounces? Hard bounces and complaints should be removed immediately, while soft bounces are not removed (don't count in the AWS bounce rate)

- the AWS SES setup is for SMTP not for API:
https://docs.aws.amazon.com/ses/latest/dg/send-email-api.html
https://docs.aws.amazon.com/ses/latest/dg/troubleshoot-throughput-problems.html

**Comment by johnblommers** [comment]
So I wanted to install listmonk locally. This is what I had to do to get it installed:

1. Download `listmonk_2.4.0_linux_amd64.tar.gz`
1. `tar xvfz listmonk_2.4.0_linux_amd64.tar.gz`
1. Three files appear, `LICENSE`, `README.md` and `listmonk` the application.
1. `mkdir $HOME/Applications/ListMonk`
1. `cp README.md listmonk $HOME/Applications/ListMonk/`
1. `cd $HOME/Applications/ListMonk`
1. `./listmonk --new-config` to generate the `config.toml` template
1. Edit `config.toml` set password to `abracadabra` in both places.
1. Now to install PostreSQL, create user `listmonk` and create database `listmonk`
1. `sudo apt install postgresql`
1. `sudo -u postgres createuser listmonk -d -P`
1. Type the password  "abracadabra" twice
1. sudo -u postgres createdb listmonk -O listmonk
1. `./listmonk --install`
1. `./listmonk`
1. Open web browser to localhost:9000
1. logon `listmonk:abracadabra`

Next you have to configure listmonk itself.

**Comment by kamikazechaser** [comment]
@rameerez If you run list monk on ec2 or elastic beanstalk, you should get a higher free limit:

> As part of [AWS Free Tier](https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all), AWS SES offers 62,000 Outbound Messages per month to any recipient when you call Amazon SES from an Amazon EC2 instance directly or through AWS Elastic Beanstalk

**Comment by MaximilianKohler** [comment]
@benstaf you can find that here https://github.com/knadh/listmonk/issues/120#issuecomment-1314110010

**Comment by electronicbits** [comment]
Thanks for this guide !

Do you see any disadvantage of using Cloudfront instead of NGINX ? 

I have an infrastructure already setup for other websites using Cloudfront.

**Comment by electronicbits** [comment]
Think I've got the answer to my own question.
I can create a new origin that points to the dns of the lightsail instance, therefore reusing the existing cloudfront distribution, and not needing an nginx server.
As far as I know, lightsail services run in its own network. You can't connect a lightsail instance to an non-lightsail RDS database due to networking restrictions
But if the dns is public, i don''t see why the distribution couldn't point to it.

**Comment by nrathi** [comment]
@rameerez can you add a section on how to renew the LetsEncrypt certificate? It looks like they expire after 90 days.

**Comment by nrathi** [comment]
It looks like this is the problem: https://docs.bitnami.com/aws/how-to/understand-bncert/

<img width="753" alt="image" src="https://github.com/knadh/listmonk/assets/3291034/de471e67-19af-4022-8a01-21419aa72a49">

But I'm not sure how to fix it, any advice?

**Comment by Khushi-patel16** [comment]
i want to use the git repo to setup the listmonk and in that,  i'm facing so much shit idk why as i want use source code for the customization and in Binary, i can't have those GO files....
