### ISSUE TITLE
Polish i18n - days abbreviation are not valid

### ISSUE THREAD

**Issue by opalczynski** [knadh/listmonk#1209]
**Version:**
 - listmonk: v2.3.0
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**

I just installed listmonk and in English version 24 of Feb 2023 is nicely abbreviated as Fri, however Polish version says it is Sob (which is Sobota, which is Saturday).

I took a look at the i18n directory in the github and we have this:

EN:

```
    "globals.days.0": "Sun",
    "globals.days.1": "Sun",
    "globals.days.2": "Mon",
    "globals.days.3": "Tue",
    "globals.days.4": "Wed",
    "globals.days.5": "Thu",
    "globals.days.6": "Fri",
    "globals.days.7": "Sat",
```

PL:

```
    "globals.days.0": "Pon",
    "globals.days.1": "Pon",
    "globals.days.2": "Wt",
    "globals.days.3": "Śr",
    "globals.days.4": "Czw",
    "globals.days.5": "Pt",
    "globals.days.6": "Sob",
    "globals.days.7": "Sob",
```

Which I think is not correct; 

Sunday is Polish Niedziela - So `Sun` should be `Niedz`
Mon - Pon
Tue - Wt
Wed - Śr
Thu - Czw
Fri - Pt
Sat - Sob

Additionally, correct Polish grammar rules says it should have `.` (dot) at the end, but his could be skipped, I think. 

Anyway, tell me what you think, if you do not have spare time to handle such small issue, I can introduce PR if you want. 

**Screenshots:**

**Comment by knadh** [comment]
Thanks for reporting this. Would you be able to send a PR with the corrections?

**Comment by knadh** [comment]
#1227 fixes this.

**Comment by opalczynski** [comment]
@knadh I think not, i the PR there is no PL fix; I will double check that, and if I will find some time (which I hope will happen soon), I will create PR, best, great piece of software :)
