### ISSUE TITLE
Support for custom email headers

### ISSUE THREAD

**Issue by RaghavSood** [knadh/listmonk#121]
SMTP relay services such as AWS SES and other commercial options use custom email headers to select various relay related configurations, such as which IP address to send from, which suppression lists to enforce, etc.

Being able to specify a list of additional email header and value pairs that are added to each email would help with integrating with such services. This would work best if added as an option to the SMTP blocks in the config, since each SMTP server may have different custom headers.

**Comment by knadh** [comment]
This should be straight forward to add. Will add in the next release.

**Comment by RaghavSood** [comment]
Seemed like an easy enough addition so I gave it a shot, I've opened a pull request. Appreciate all your help so far!

**Comment by OctavioXII** [comment]
Would this also work for the List-Unsubscribe header? This would help mitigate the bounce rate, it would be wonderful.

**Comment by knadh** [comment]
@OctavioXII The above mentioned feature is for static headers. `List-Unsubscribe` should contain the dynamic unsubscribe URL. This is available in the upcoming release.
