### ISSUE TITLE
Fresh install getting "nested MAIL command" when used with Mailcow (Postfix)

### ISSUE THREAD

**Issue by gellenburg** [knadh/listmonk#1211]
**Version:**
 - listmonk: 2.3.0
 - OS: Debian 11

**Description of the bug and steps to reproduce:**
Fresh install of Listmonk on a new Debian 11 server using the Docker "production" steps (not the demo steps).

Trying to do the initial configuration and testing the SMTP parameters but getting an error about "nested MAIL commands" being reported by Postfix when Listmonk attempts to connect to my Mailcow server (Postfix is the SMTP server).

**Screenshots:**
![image](https://user-images.githubusercontent.com/7026750/221284080-e76a62dc-6d6c-481d-9a42-270359cb1c33.png)

**Comment by knadh** [comment]
Hi @gellenburg. This was recently fixed and the fix will be available in the upcoming release: https://github.com/knadh/listmonk/issues/337#issuecomment-1409046046

**Comment by knadh** [comment]
By this weekend. You can also pull `master` and do a `make dist` to get the nightly binary.
