### ISSUE TITLE
api send campaign immediately

### ISSUE THREAD

**Issue by frelle** [knadh/listmonk#1218]
Hi

After searching a bit, I don't see the following feature. If this feature already exists, please tell me 

Using the API, when creating a campaign (using the POST api/campaigns endpoint), add a parameter to start sending the newsletter immediately

For now, I'm doing 3 steps : 

1. API create campaign (POST)
2. Get the campaign id 
3. API update campaign (PUT) using this campaign id

Thank you for this great repo!!

**Comment by knadh** [comment]
Sorry, missed responding to this. Sending the update API call is the correct way to start the campaign.

**Comment by frelle** [comment]
yes, it's what I'm actually using.
but if you can consider to add an argument/parameter in the Creaion campaign API endpoint to start the campaign immediately after the creation. that would be great

**Comment by knadh** [comment]
It's best not to mix functionality and keep the APIs granular and separate. An extra API call for this usecase has negligible cost.
