### ISSUE TITLE
How to pass html content as data param for transactional mails?

### ISSUE THREAD

**Issue by ujjwalbishnoi** [knadh/listmonk#1228]
params for api/tx
{
  "subscriberEmail": "abx@example.com",
  "templateId": 15,
  "data": {
    "subject" : "something",
    "message" : "<h1>hello world</h1>"
  }
}

I tried this. But it shows compiling error
{{ Safe .tx.data.message }}

**Comment by knadh** [comment]
There are no `subscriberEmail` or `templateId` fields in listmonk's API. It's `subscriber_email`, `template_id` etc. Please refer to this: https://listmonk.app/docs/apis/transactional/

**Comment by ujjwalbishnoi** [comment]
```
{
  "subscriber_email": "abx@example.com",
  "template_id": 15,
  "data": {
    "subject" : "something",
    "message" : "<p>hello world</p>"
  }
}
```

Actually, i passed this as params.


Can u tell me how to pass html content as data param

**Comment by knadh** [comment]
Content cannot be passed as data param. HTML content should be in the transactional template created on the admin UI. The data fields in `data` can then be injected in the template.

Please refer to the sample transactional template that's shipped in listmonk. It should be something like `{{ .Tx.Data.message }}`
