### ISSUE TITLE
bounced subscriber ( / ) not found

### ISSUE THREAD

**Issue by liangjaden** [knadh/listmonk#1229]
**Version:**
 - listmonk: [eg: v2.3.0]
 - OS: [e.g. Fedora]

Hi,

I am puzzled by the way bounce processing works. I have enabled the bounce processing and set bounce count to 1, and set action to delete. Also I have added a POP3 server for bounce mail box but I get this error in logs:
 bounced subscriber ( / ) not found

![image](https://user-images.githubusercontent.com/54787532/223093796-84a6eb7b-ca39-4650-857d-abbcfb381fbb.png)

**Comment by knadh** [comment]
Please see these: https://github.com/knadh/listmonk/issues/1162

https://github.com/knadh/listmonk/issues?q=pop3+bounce+is%3Aissue+is%3Aclosed+

**Comment by liangjaden** [comment]
I'm sorry, I don't understand where these two fields should be configured (X-Listmonk-Subscriber, Delivered-To, To). Should I configure them on my email server? I couldn't find any relevant configuration on Listmook.https://github.com/knadh/listmonk/issues/1162#issuecomment-1414140608

**Comment by knadh** [comment]
listmonk attaches those headers automatically. Ideally, the bounced mail should contain these headers which listmonk then extracts and uses to identify the subscriber and campaign. If the bounced mail doesn't have any of these headers (including the affected user's e-mail ID in `Delivered-To` or `To`), then listmonk can't figure out the subscriber.

Please inspect the bounced e-mails source to see if these exist. There may be some mail servers out there that strip out all this information.

**Comment by liangjaden** [comment]
Oh~ I understand, thank you very much for your answer
