### ISSUE TITLE
Automated warming up the mail server

### ISSUE THREAD

**Issue by SalahSaqr** [knadh/listmonk#123]
We know that warming up an IP (must) be implemented properly before we can target inboxes even when we use SMTP service like Amazon SES with a dedicated IP. Before we can start sending any email marketing campaigns using any SMTP service, we have to warm up our IP address.

I know you would say that this task is a mail server responsibility, I agree, but, what if the majority of them lack this feature? Wouldn't it be awesome if Listmonk got our back by taking care of this as a built-in feature or addon?

This free tool creates a good scheduling plan for warming up. The developer knows the best practices. https://h-educate.com/email-marketing-toolkit/

**I hope you can make something similar that it actually can controlling the amounts and frequency of our sending on 100% autopilot.**

**Comment by knadh** [comment]
listmonk has a `message_rate` param to control the number of e-mails that are sent out per second. I guess this could be used to orchestrate this manually for the time being.

**Comment by knadh** [comment]
I want to add that listmonk is a mailing list manager / newsletter tool. Marketing related features fall out of the scope really.

**Comment by SalahSaqr** [comment]
As for `message_rate` it will not be the ideal solution since we will need to (gradually increase) the sending limit manually.

Would you take it into consideration if I donate for this feature to be there?

**Comment by knadh** [comment]
Hi @SalahSaqr please spec out and propose features before you work on them so that they can be discussed and evaluated. Thanks.
