### ISSUE TITLE
SMTP servers deleted after restarting the server

### ISSUE THREAD

**Issue by profmatheuspassos** [knadh/listmonk#1230]
**Version:**
 - listmonk v2.3.0
 - OS: Ubuntu (Cloudron)

**Description of the bug and steps to reproduce:**
- Added two SMTP servers on the "SMTP" tab in settings (Amazon SES and SMTP2GO)
- After restarting the server, both servers were deleted and the app came back to its standard settings - which means, I have to add the SMPT servers again.
- Not the 1st time this happens.

**Comment by knadh** [comment]
Is this a Docker environment? Sounds like your DB is being destroyed and re-created when you restart. In the Docker environment, please follow the production steps so that the Postgres volumes are persisted.

**Comment by knadh** [comment]
Not familiar with Clouddron unfortunately. Seems like there is a setup issue there that destroys and recreates the DB on restart. Please try asking in the Cloudron community.

**Comment by profmatheuspassos** [comment]
Sure, thank you!

**Comment by gramakri** [comment]
@profmatheuspassos This is expected. By default, Cloudron will configure listmonk to use the internal SMTP server. If you want an external one, select `Do not configure app's mail delivery settings` in Email section of the app (in Cloudron dashboard). See https://docs.cloudron.io/apps/#mail-from-address . BTW, for Cloudron specific questions, you can ask them at our forum which has a listmonk section addressing packaging issues/questions like this - https://forum.cloudron.io/category/145/listmonk

**Comment by profmatheuspassos** [comment]
Thanks @gramakri - I'll make some tests in the next 3-4 days and then come back with the results.

**Comment by profmatheuspassos** [comment]
Just an update: I started using an external SMTP server, as indicated by @gramakri - working fine. Thanks.
