### ISSUE TITLE
Multiple SMTP servers - how to select them?

### ISSUE THREAD

**Issue by profmatheuspassos** [knadh/listmonk#1232]
Hello @knadh,

We have the possibility to set up multiple SMTP servers.

Is it possible to choose which one to use before starting a campaign? Or should I select/deselect manually before sending the campaign? Thank you!

**Comment by knadh** [comment]
Apologies @profmatheuspassos, missed this question. SMTP servers are enabled/disabled globally in settings and not per campaign. Not possible to choose per campaign right now.

**Comment by frelle** [comment]
Hello
Just asking, have you plan to integrate this feature anytime soon ? (end 2023 perhaps ? next year ? ) 
Thank you

**Comment by knadh** [comment]
Per-campaign SMTP is not planned, @frelle. Thank you.

**Comment by frelle** [comment]
ok, got it. I'll create multiple instances of listmonk to use multiple smtp. 
Your product is great, thank you for your time in dev it

**Comment by violoncelloCH** [comment]
Hi @knadh 
Sorry to comment on an old issue. I'm also interested in a feature allowing to select which smtp server to use to send out a campaign with, as this would allow to send out mails over multiple different domains served by different mail servers depending on the campaign.

Would this be a feature you'd consider accepting a pull request for?

As to how I'd see that feature working:
I would implement this in a way that the default behavior is to use all configured SMTP servers, as it is right now. 
Each SMTP server would have an additional setting (a switch, possibly just below the "enable" switch), allowing to mark the SMTP server as "default" (enabled by default).
On the campaign then, there would be an option allowing to choose which SMTP server to use. Again, the default here would be to simply select all the SMTP servers which have the "default" switch enabled.

What do you think about this idea?
Thanks in advance for your feedback!

**Comment by MaximilianKohler** [comment]
@frelle Are you hosting different listmonk instances on their own subdomain in order to do that? IE: listmonk1.domain.com, listmonk2.domain.com?
