### ISSUE TITLE
AxiosError: Network Error when going to statitics

### ISSUE THREAD

**Issue by yodatak** [knadh/listmonk#1234]
Hi thanks again ,

i got this AxiosError when i go to statistics and i don't show nothing on firefox
Uncaught (in promise) 
Object { message: "Network Error", name: "AxiosError", code: "ERR_NETWORK", config: {…}, request: XMLHttpRequest, response: XMLHttpRequest, stack: "" }
​
code: "ERR_NETWORK"
​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​​
adapter: function exports(t)
​​
baseURL: "/"
​​
data: undefined
​​
env: Object { FormData: null }
​​​
FormData: null
​​​
<prototype>: Object { … }
​​​​
__defineGetter__: function __defineGetter__()
​​​​
__defineSetter__: function __defineSetter__()
​​​​
__lookupGetter__: function __lookupGetter__()
​​​​
__lookupSetter__: function __lookupSetter__()
​​​​
__proto__: 
​​​​
constructor: function Object()
​​​​
hasOwnProperty: function hasOwnProperty()
​​​​
isPrototypeOf: function isPrototypeOf()
​​​​
propertyIsEnumerable: function propertyIsEnumerable()
​​​​
toLocaleString: function toLocaleString()
​​​​
toString: function toString()
​​​​
valueOf: function valueOf()
​​​​
<get __proto__()>: function __proto__()
​​​​
<set __proto__()>: function __proto__()
​​
headers: Object { Accept: "application/json, text/plain, */*" }
​​
loading: "campaigns"
​​
maxBodyLength: -1
​​
maxContentLength: -1
​​
method: "get"
​​
params: Object { id: (1) […], from: Date Thu Mar 02 2023 00:00:00 GMT+0100 (heure normale d’Europe centrale), to: Date Thu Mar 09 2023 23:59:00 GMT+0100 (heure normale d’Europe centrale) }
​​
paramsSerializer: function paramsSerializer(t)
​​
responseType: "json"
​​
timeout: 0
​​
transformRequest: Array [ transformRequest(t, e) ]
​​
transformResponse: Array [ transformResponse(t) ]
​​
transitional: Object { silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false }
​​
url: "/api/campaigns/analytics/views"
​​
validateStatus: function validateStatus(t)
​​
withCredentials: false
​​
xsrfCookieName: "XSRF-TOKEN"
​​
xsrfHeaderName: "X-XSRF-TOKEN"
​​
<prototype>: Object { … }
​
message: "Network Error"
​
name: "AxiosError"
​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​​
data: undefined
​​
mozAnon: false
​​
mozSystem: false
​​
onabort: function onabort()
​​
onerror: function onerror()
​​
onload: null
​​
onloadend: function _()
​​
onloadstart: null
​​
onprogress: null
​​
onreadystatechange: null
​​
ontimeout: function ontimeout()
​​
readyState: 4
​​
response: ""
​​
responseText: ""
​​
responseType: ""
​​
responseURL: ""
​​
responseXML: null
​​
status: 0
​​
statusText: ""
​​
timeout: 0
​​
upload: XMLHttpRequestUpload { onloadstart: null, onprogress: null, onabort: null, … }
​​
withCredentials: false
​​
<prototype>: XMLHttpRequestPrototype { open: open(), setRequestHeader: setRequestHeader(), send: send(), … }
​
response: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​
stack: ""
​
<prototype>: Object { constructor: r(t, e, n, i, r), toJSON: toJSON(), stack: "", … }

{
  "transitional": {
    "silentJSONParsing": true,
    "forcedJSONParsing": true,
    "clarifyTimeoutError": false
  },
  "transformRequest": [
    null
  ],
  "transformResponse": [
    null
  ],
  "timeout": 0,
  "xsrfCookieName": "XSRF-TOKEN",
  "xsrfHeaderName": "X-XSRF-TOKEN",
  "maxContentLength": -1,
  "maxBodyLength": -1,
  "env": {
    "FormData": null
  },
  "headers": {
    "Accept": "application/json, text/plain, */*"
  },
  "baseURL": "/",
  "withCredentials": false,
  "responseType": "json",
  "params": {
    "id": [
      6
    ],
    "from": "2023-03-01T23:00:00.690Z",
    "to": "2023-03-09T22:59:00.690Z"
  },
  "loading": "campaigns",
  "method": "get",
  "url": "/api/campaigns/analytics/views"
}

{}

**Comment by knadh** [comment]
Could be an ad-blocker plugin blocking the request. Please try disabling it on the site.

**Comment by yodatak** [comment]
Hi thanks it effectily a ublock origin issue in the easyprivacy line 727 that match this url "/analytics/view" 

https://easylist.to/easylist/easyprivacy.txt
