### ISSUE TITLE
Encoding mail body problem

### ISSUE THREAD

**Issue by saginsa** [knadh/listmonk#1236]
**Version:**
 - listmonk: v2.3

**Description of the bug and steps to reproduce:**
I send cyrilyc mail on simple template without anything.
![image](https://user-images.githubusercontent.com/85064689/225155045-0190d8ec-58f7-4bb4-afa0-19342adfe028.png)

and i get email with fatal encoding problem

![image](https://user-images.githubusercontent.com/85064689/225155146-2ff1bb39-1a2a-449f-92a8-acbeb885074d.png)

At the same time, it is not clear under what circumstances it appears, and how to bypass. Usually our letters leave normally. But in 5% of cases, we have an intractable problem.

**Comment by knadh** [comment]
Can you share the raw text to try and reproduce this locally?
