### ISSUE TITLE
Error when upgrade new version

### ISSUE THREAD

**Issue by mannm123** [knadh/listmonk#1238]
Hi Knah!
I am having trouble upgrading my listmonk version from 1 to 2.3.
Specifically when I run the command: ./litsmonk
it says the following: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa75acf]

goroutine 1 [running]:
main.prepareQueries(0xc000092300?, 0xc00031b6b0, 0xbd5675?)
        /home/mannminh/listmonk/cmd/init.go:301 +0xcf
main.init.0()
        /home/mannminh/listmonk/cmd/main.go:157 +0x5c5
Hope you can tell me what's wrong with it. Have a good day

**Comment by knadh** [comment]
Did you try running `./listmonk --upgrade`?

**Comment by mannm123** [comment]
Yes it is
Thank you very much
