### ISSUE TITLE
Error preparing query 'get-dashboard-stats': pq: relation "lists" does not exist

### ISSUE THREAD

**Issue by Vinutha-Garimella** [knadh/listmonk#124]
Hi, I am facing this issue with lismonk container
I have a postgress db container already where I created a database called `listmonk` and created a listmonk container by volume mounting the config.toml 

```
[db]
host = "db"
port = 5432
user = "listmonk"
password = "listmonk"
database = "listmonk"
ssl_mode = "disable"
```
db container 
`docker run -itd --name db --hostname db --network my-net -v db-test:/var/lib/postgresql/data -e POSTGRES_PASSWORD=listmonk -e POSTGRES_USER=listmonk -e POSTGRES_DB=listmonk --restart unless-stopped -p 5432:5432 postgres:11
`
listmonk container

`docker run -itd --name listmonk --hostname listmonk --network my-net -p 9000:9000  -v Desktop/config.toml:/listmonk/config.toml listmonk`

the listmonk container is not coming up and I see this error in listmonk container logs
```
2020/06/03 02:14:02 main.go:90: reading config: config.toml
2020/06/03 02:14:02 init.go:121: error preparing SQL queries: Error preparing query 'get-dashboard-stats': pq: relation "lists" does not exist
```

I am not using docker-compose command as specified in the document, I created a custom ```
```
Docker file to create a listmonk container
FROM ubuntu
RUN wget -O /tmp/listmonk_0.6.1-alpha_linux_amd64.tar.gz https://github.com/knadh/listmonk/releases/download/v0.6.1-alpha/listmonk_0.6.1-alpha_linux_amd64.tar.gz
RUN mkdir /listmonk && tar xvfz /tmp/listmonk_0.6.1-alpha_linux_amd64.tar.gz -C /listmonk && \
          rm -f /tmp/listmonk_0.6.1-alpha_linux_amd64.tar.gz
WORKDIR /listmonk
COPY config.toml /listmonk
CMD ["./listmonk"]
EXPOSE 9000
```

**Comment by knadh** [comment]
`Error preparing query 'get-dashboard-stats': pq: relation "lists" does not exist`

^ This implies that the database does not have the listmonk tables and relations. Have you run `--install` to do the initial setup?

**Comment by Vinutha-Garimella** [comment]
@knadh  thanks for the quick reply
 where do I have to run this `./listmonk --install` command

**Comment by knadh** [comment]
That's the listmonk binary with the config.toml pointing to your Postgres DB. You can execute it inside or outside the container. It's a one-time process that creates the necessary schema in your database.

**Comment by Vinutha-Garimella** [comment]
@knadh  to execute this command inside listmonk container the container should be up and running and I can't run this command from outside
`docker exec listmonk bash -c "listmonk --install"`
`Error response from daemon: Container 838278dcc87d56c4ecbc58c6a78bb98b5e3897e777 is not running`

**Comment by knadh** [comment]
You can download the binary from the releases page and run it, or download [schema.sql](https://github.com/knadh/listmonk/blob/master/schema.sql) and run it directly on your DB.

eg: `sudo -u postgres psql -d listmonk -f schema.sql`

**Comment by Vinutha-Garimella** [comment]
okay @knadh  I'll try to download the shema.sql and install in it db container

**Comment by Vinutha-Garimella** [comment]
@knadh I installed schema's in db container it's working fine now
The forms tab in listmonk webpage is throwing this error is it related to database

![image](https://user-images.githubusercontent.com/33555892/83628726-96bfbb00-a5b6-11ea-955b-afbe56953a2b.png)

**Comment by Vinutha-Garimella** [comment]
Understood the problem until and unless we have a list we don't get the forms page, thank you so much for your help @knadh

**Comment by Vinutha-Garimella** [comment]
@knadh can you please let me know how to add templates in listmonk container I referred  previous issue and executed this command `./listmonk --static-dir=static` 
![image](https://user-images.githubusercontent.com/33555892/83751389-634b6200-a684-11ea-8a54-f619aad14d20.png)
when I tried to add example template that was given in the document the the campaign page is not loading up  
`{"message":"Error fetching campaign: sql: Scan error on column index 12, name \"template_id\": converting NULL to int is unsupported"}
 `

**Comment by knadh** [comment]
Ah! I just realised, since you did not run `--install` and ran the schema directly, the default data would not have been populated. There's meant to be an un-deletable default template always. That's the constraint that is malfunctioning for you. `--static-dir` is not for campaign templates, but to customize the public pages of listmonk (like the unsubscription page).

Could you please drop the database, download the listmonk binary from the releases page, and run `--install` on that binary externally with your config.toml?

Apologies, I missed this when suggesting to run `schema.sql` directly.

**Comment by Vinutha-Garimella** [comment]
okay @knadh  will try this out and I'll let you know the result

**Comment by Vinutha-Garimella** [comment]
@knadh facing the same issue even after doing these steps

1. drop db 
2. run `./litmonk --install`
3. install the database `psql -U listmonk -d listmonk -f schema.sql`

**Comment by knadh** [comment]
`./listmonk --install` creates all the tables and inserts default data. You need not run `schema.sql` manually after that (which will recreate the schema, losing data).

**Comment by Vinutha-Garimella** [comment]
@knadh can you please explain the difference between `./lismonk` and `./listmonk --install`

**Comment by mr-karan** [comment]
`./lismonk` runs the application.

`./listmonk --install` wipes the DB (DB name is fetched from config) and applies DB schema + default data. This is ideally only a one time command you need to run.

**Comment by knadh** [comment]
`./listmonk --install` is meant to be run just once on an empty database. It install's listmonk's database schema required for it to function.

`./listmonk` is to run the app for production use after the installation. In your case, you'd be running it with the Docker container.

**Comment by Vinutha-Garimella** [comment]
okay @knadh thanks for the explanation I have changed my Dockerfile accordingly
one last question does listmonk use it's own SMTP to deliver emails or can we configure our smtp server in `config.toml [smtp] section` to deliver emails..?
