### ISSUE TITLE
Ability to filter or export or query confirmed (double opt in) emails

### ISSUE THREAD

**Issue by collegewap** [knadh/listmonk#1241]
**Is your feature request related to a problem? Please describe.**
Currently, the admin portal has no option to query/filter/export only confirmed emails.

**Describe the solution you'd like**
It could be great if there is any one of these features:

- Ability to query in the Advanced section
- Ability to filter out only confirmed emails
- A column in the export, which says confirmed or not.

**Comment by knadh** [comment]
Once you go inside a list (Lists -> Click on the subscriber count on the respective list), it's possible to query subscribers by status.

![image](https://user-images.githubusercontent.com/547147/226160114-1d081c46-6c08-49b6-b8c5-c9f863778e19.png)

However, I just discovered a bug that breaks the export for this query. Fixed it in #https://github.com/knadh/listmonk/commit/aaf5080a2733c925d9c9f4a80417251453773906 which will be available in the upcoming release (today).
