### ISSUE TITLE
How to modify subscriber by id?

### ISSUE THREAD

**Issue by sikvestor** [knadh/listmonk#1242]
I try to modify subscriber by id, (for exemple status) but I can't undarstand how to do it.
curl -u "xxxxxx:xxxxxxxx" -X PUT 'http://localhost:9000/api/subscribers/66'  --data-raw '{"status": "enabled"}'  
Could you please write me how can I do it...
Phanks.

**Comment by knadh** [comment]
```shell
curl 'http://localhost:9000/api/subscribers/99' -u 'user:pass' -X PUT \
	-H 'Content-Type: application/json' \
	--data-raw '{"email":"test@test.com","name":"Test","status":"enabled","attribs":{"planet":"earth"},"lists":[1, 2, 3]}'
```
