### ISSUE TITLE
Broken link at API / Subscribers

### ISSUE THREAD

**Issue by om-khade-algobulls** [knadh/listmonk#1251]
**Version:**
 - listmonk: [eg: v1.0.0]
 - OS: [e.g. Fedora]

**Description of the bug and steps to reproduce:**
The link for [querying and segmentation](https://listmonk.app/querying-and-segmentation#querying-and-segmenting-subscribers) is broken and page not found is shown on visiting the link.

Link can be found in this section of the docs
https://listmonk.app/docs/apis/subscribers/#get-apisubscribers_2

**Comment by knadh** [comment]
Fixed https://github.com/knadh/listmonk-site/commit/c84ef17bc0a41cb846710648ae7b5301e53d9a89.
