### ISSUE TITLE
listmonk app not accessible anymore

### ISSUE THREAD

**Issue by AntoineSoetewey** [knadh/listmonk#1252]
**Version:**
 - listmonk: I don't know
 - OS: Ventura 13.2.1 (22D68)

**Description of the bug and steps to reproduce:**
Hello,

I used to access the listmonk app for my newsletter via https://listmonk-statsandr.up.railway.app/:

![Screenshot 2023-03-22 at 11 30 27](https://user-images.githubusercontent.com/17910063/226889409-0baf4ecf-5ec0-491c-939b-61aa30802417.png)

This morning I received this email:

![Screenshot 2023-03-22 at 12 27 08](https://user-images.githubusercontent.com/17910063/226890655-e208780c-aa2f-48cd-9f06-49505b39570c.png)

So I added a payment method to be on the developer plan:

![Screenshot 2023-03-22 at 12 28 06](https://user-images.githubusercontent.com/17910063/226890818-352e2b8b-e9f3-4648-bace-593a1e139e0a.png)

However, I still cannot have access to https://listmonk-statsandr.up.railway.app/:

![Screenshot 2023-03-22 at 11 30 39](https://user-images.githubusercontent.com/17910063/226889752-2b057e2a-f10a-4f5c-9cf5-051ca147db18.png)

I have very little knowledge in Railway, Listmonk, their deployment, etc. (I struggled quite a lot to implement listmonk for my newsletter, I switched from from Mailchimp because it became too expensive for my usage), so I have no clue what is causing the issue and how to fix it.

Can anyone please help?

Regards,
Antoine

**Comment by knadh** [comment]
Hi @AntoineSoetewey. You'll have to write to Railway support to help you with this. Their billing system disabled your listmonk instance. Ideally it should've come back up when you paid, but they may have to bring it up manually from the backend.

**Comment by AntoineSoetewey** [comment]
Thanks for your prompt answer!

For those who have the same problem: You'll have to issue a redeploy in order to bring the instance back up in this case. Railway does not automatically restart shut-down services.
