### ISSUE TITLE
how to get last created subscriber, using listmonk api?

### ISSUE THREAD

**Issue by om-khade-algobulls** [knadh/listmonk#1255]
List monk has [/api/subscribers](https://listmonk.app/docs/apis/subscribers/#get-apisubscribers_1) API where we can pass SQL query to get subscribers, what SQL query should be passed to get last created customer?

I wanted to write following SQL query but it's giving error.
`ORDER BY  subscribers.created_at  DESC LIMIT 1`

**Comment by charlesmudy** [comment]
When you are making a request, you can pass `params: options` where your `options` will include `options.order_by` (created_at) and `options.per_page` (1)

**Comment by knadh** [comment]
`subscribers.id IN (select id FROM subscribers order by id DESC LIMIT 1)` works.
