### ISSUE TITLE
You can't use multiple SMTP connections

### ISSUE THREAD

**Issue by youssef1lam** [knadh/listmonk#1259]
- listmonk: v2.4.0
 - OS: Ubuntu 22.04 (Cloudron)

In the last version (v2.3), i was able to send email via multiple SMTP connections ( 2 mail servers with different domain names). suddenly with this new version (v2.4) i can't do it anymore, the app only send emails using the smtp weach From address present while setting up the campaigns. the other mail servers get ignored and give the error showed on the screenshot.

PS: I already did integrate the custom header on each SMTP with the right FROM email.

this is my settings :
![smtp settings](https://user-images.githubusercontent.com/125463331/227314009-b890c422-1816-4e55-ae2f-3e5eb3b7c94e.PNG)

this is my logs : as you can see the 2nd smtp give the error the first one deliver the email to my mailbox
![logs](https://user-images.githubusercontent.com/125463331/227314002-b97736c2-2258-4ffe-aa42-218b93e9e416.PNG)

**Comment by knadh** [comment]
Hi @youssef1lam. There are no changes in v2.4.0 that are related to multiple SMTPs. Error 452 is thrown when you've hit the rate limits of the SMTP server. You should contact your SMTP provider.

**Comment by youssef1lam** [comment]
Hello again @knadh. I did try 1 smtp server, and it send all the emails without any problem, also i had to change the Default `from` email to match my 1 smtp server then i can send emails, if not the server gives the same error at the logs page !!.
I'm so confused because i worked with the same config on the old version and all works fine.

**Comment by knadh** [comment]
Will investigate this.

**Comment by youssef1lam** [comment]
@knadh : there any update about this problem yet ??

**Comment by knadh** [comment]
Tested this. Was unable to reproduce this with multiple SMTP endpoints on the same campaign.
