### ISSUE TITLE
API to manage SMTP servers (undocumented?)

### ISSUE THREAD

**Issue by supersnager** [knadh/listmonk#1260]
**Is your feature request related to a problem? Please describe.**
I want to use listmonk to send notifications from external application using REST API.
For example, password reset links, welcome messages, reminders, etc.
I want to allow users to configure SMTP account directly in my application.
This configuration should be saved to the listmonk using the API.

**Describe the solution you'd like**
I would like to have an API endpoint to manage SMTP servers, just like other API endpoints (lists, subscribers, etc.)

I know the undocumented API endpoint /api/settings already exists because we can save settings from the UI.

The question is whether the endpoint is undocumented only because the API documentation is a work in progress or because this API endpoint for some reason should not be used?

**Comment by knadh** [comment]
Just haven't had a chance to document the /settings API. Please see this: https://github.com/knadh/listmonk/issues/950

**Comment by knadh** [comment]
Open to revisiting this in the future, but not right now as I'd explained in #950. Thanks @supersnager.

**Comment by supersnager** [comment]
Thanks @knadh !
