### ISSUE TITLE
Update on Railway

### ISSUE THREAD

**Issue by anaclumos** [knadh/listmonk#1264]
I am trying to update Listmonk on Railway. What are the recommended steps?

**Comment by knadh** [comment]
Hi @anaclumos. It'd be best to ask on the Railway forum. Please do share the answer here so that others can also find it.

**Comment by danfascia** [comment]
As long as the Dockerfile is pointed at the latest version of listmonk, simply trigger a redeploy from the railway dashboard

**Comment by anaclumos** [comment]
> As long as the Dockerfile is pointed at the latest version of listmonk, simply trigger a redeploy from the railway dashboard

Would that keep all of my information?

**Comment by anaclumos** [comment]
Yes. Redeploy updates Listmonk. Thanks.
