### ISSUE TITLE
Repo name not available

### ISSUE THREAD

**Issue by RitvikSardana** [knadh/listmonk#1265]
**Version:**
 - listmonk: 2.2.0
 - OS: Railways

**Description of the bug and steps to reproduce:**
I have created a repo in my org's GitHub account for Listmonk, and when I try to find the repo [https://railway.app/new/template/listmonk] in this URL, I get the error "repo name not available".

Even though the repo exists with the same name

P.S. - I have once deployed listmonk with railways on the same repo and then deleted it. Wanted to do it again, but getting this error

**Screenshots:**
![image](https://user-images.githubusercontent.com/65544983/227860582-6cae0461-80b8-4eab-aa37-ebfddff35d0a.png)

Any help on this would be appreciated. Thanks

**Comment by knadh** [comment]
Maybe because this is a private org or a private repo?
