### ISSUE TITLE
listmonk-site has been archived

### ISSUE THREAD

**Issue by NilsJacobsen** [knadh/listmonk#1266]
Hey folks, 

I wanted to add something to the docs in the listmonk-site repo, but it is archived now. 
I wanted to add the new i18n editor link to the i18n docs. How should I continue?

![image](https://user-images.githubusercontent.com/58360188/227882664-4bf947e4-13a5-475c-a789-48a9bfe827d3.png)

**Comment by knadh** [comment]
It's been merged to this repo: https://github.com/knadh/listmonk/tree/master/docs

**Comment by NilsJacobsen** [comment]
Oh sorry, I was a bit confused by the link t o listmonk-site.
Opened a new PR https://github.com/knadh/listmonk/pull/1267
