### ISSUE TITLE
Bug: `allow_wipe = true` in config does not enable the wipe endpoint

### ISSUE THREAD

**Issue by PhilippSeitz** [knadh/listmonk#127]
You can't access the `subscription/wipe/` endpoint, even when `allow_wipe` is set to `true` in the config.

---

Not sure if this is intended:

https://github.com/knadh/listmonk/blob/ae68bd2645f96b384ee72ad7bd5c51c241179eca/public.go#L402

Or if it can be replaced by this:

```go
// Is wiping allowed?
if !app.constants.Privacy.AllowWipe {
}
```

**Comment by knadh** [comment]
You're right. https://github.com/knadh/listmonk/commit/67eb3dbbbe1c10cdcd711525bb2d2ccc65832455 fixes this.
