### ISSUE TITLE
Azure Communication Service support 

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1271]
**Describe the solution you'd like**

I would like to use Azure Communication Service, but they don't have SMTP , only API and SDK:
https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/send-email?tabs=windows&pivots=platform-azcli

Is it on the roadmap?

**Comment by knadh** [comment]
Hi @benstaf, you could write an HTTP server that accept's listmonk's [Messenger](https://listmonk.app/docs/messengers/) postbacks and passes it on to Azure. Maybe @joeirimpan would be interested in adding support for this in his messenger implementation: https://github.com/joeirimpan/listmonk-messenger

This is not something we can consider hardcoding into listmonk's core though.

**Comment by oskari** [comment]
ACS these days has SMTP (PR #3002 related ) which makes it easy to use with Listmonk, but using the API (with go sdk) is still probably the best option. I'd be happy to look into implementing this support if the relevant bounce handling is accepted (PR #3001 ). 

Any update to your pointers about the implementation?  I don't see [listmonk-messenger](https://github.com/joeirimpan/listmonk-messenger) getting much updates lately so I'm not sure if that's best place to implement. I somewhat dislike the idea of needing to run own service for this (makes deploying complicated), but I guess the architecture of Listmonk and Messenger require that.
