### ISSUE TITLE
Subscriber Growth Data

### ISSUE THREAD

**Issue by anaclumos** [knadh/listmonk#1277]
Can we also extract & analyze how the subscribers are growing? Any kind of Ops-specific datapoints will help.

**Comment by knadh** [comment]
If you have an analysis tool like Metabase, you can connect it to the listmonk DB and easily query the `subscribers` table and produce visualisations.

**Comment by anaclumos** [comment]
![image](https://user-images.githubusercontent.com/31657298/230798775-84bcb086-12fd-4483-bf5c-9ef064c230ce.png)

Any more affordable alternatives? 😅 I'm a student 😭

**Comment by anaclumos** [comment]
Oh actually Metabase is OSS, I linked it to Railway and it's now working. Thanks!
