### ISSUE TITLE
Unconfirmed users (re)subscribing to a public list are not resent a confirmation email or told

### ISSUE THREAD

**Issue by earnestma** [knadh/listmonk#1280]
**Version:**
 - listmonk: v2.4.0
 - OS: Ubuntu via Docker

Unconfirmed users trying to subscribe again (whether to the same list or to another one) via the public form are shown - "Subscribe Subscribed successfully", and another confirmation email is not sent.

Expected: 
Send a new confirmation email to confirm subscription to the all the lists the user is unconfirmed for and let the user know

**Comment by knadh** [comment]
This was fixed last week https://github.com/knadh/listmonk/issues/1257.

**Comment by les-les** [comment]
v2.4.0

tested today seems not to be fixed. 

a subscribed but not confirmed user on a ( double opt in ) list 
who is subscribing again is not getting a message / information that 

-  Unconfirmed users (re)subscribing 
_(like hey $email you have already subscribed pleas check your spam folder or hit us with an email (link to contact form never hard coded mail)_ 
- send confirmation mail again 

br LES
