### ISSUE TITLE
 Error loading app config: Cannot parse admin_password and admin_username as uint

### ISSUE THREAD

**Issue by gezimbll** [knadh/listmonk#1282]
**Version:**
listmonk: v2.4.0
OS: Debian Bullseye

I encountered an error while trying to load the app config. The error message was related to parsing admin_password and admin_username as uint values.The app should also accept string values for these configurations as did for older versions.

*Logs*
```
2023/04/11 09:59:58 init.go:227: loading static files from: /home/gezim/listmonk/static
2023/04/11 09:59:58 init.go:357: error loading app config: 2 error(s) decoding:
* cannot parse 'admin_password[0]' as uint: strconv.ParseUint: parsing "user": invalid syntax
* cannot parse 'admin_username[0]' as uint: strconv.ParseUint: parsing "user": invalid syntax
```

**Comment by knadh** [comment]
Ah, this is in fact a bug in the `mapstructure` library in the latest version of koanf.  Investigating this.
