### ISSUE TITLE
3 Places where a Button (BACK ) or (EXIT) is needed

### ISSUE THREAD

**Issue by les-les** [knadh/listmonk#1289]
3 Places where a Button (BACK ) or (EXIT) is needed

Button **BACK** kicks you back to a specific place 
Button **EXIT** closes the tab or window (browser tap prefered) 

1) on confirm page an Exit Button or Back Button to home button is missing
2) on unsubscribe page an EXIT Button is Missing 
3) Subscribe / Subscribed Successfully Back and or Exit Button is missing

**Comment by knadh** [comment]
An `Exit` button to close the tab is unconventional and not necessary. All browsers offer multiple one-click ways to close tabs and windows.

**Comment by les-les** [comment]
and thats exactly what you DO NOT want a tap (information subscription success)  thats stays open for the rest of time 

no offense but that sucks ! 

the least is a working back button that kicks you back (to the whatever home base) 
working out of the box 

but seems that must be done by hand too ;) 

;)

LES

**Comment by knadh** [comment]
> and thats exactly what you DO NOT want a tap (information subscription success) thats stays open for the rest of time

Sorry, disagree :) By that logic, every single webpage should have an "Exit" button because you don't know which page should stay open and shouldn't. So that's left to the user to close the site using standard browser controls. If that wasn't the case, every webpage would have an exit button.

> the least is a working back button that kicks you back (to the whatever home base)

Will check this.

**Comment by les-les** [comment]
> By that logic, every single webpage should have an "Exit" button

Fair enough point taken


Maybe I m gonna add a back to homepage or subscribe link (button)

Have not looked into it how complex it is to close a tab without using close. Window()
Cuz it's not working.... But me and my coding kung fu... Not top shelf 😏
