### ISSUE TITLE
Support for "query lists"

### ISSUE THREAD

**Issue by RaghavSood** [knadh/listmonk#129]
Right, now, the ability to run a query on subscribers and add them to a list exists.

It would be nice to have this same feature the other way around: Define a query as a list, so that any new subscribers that match the query are automatically added, and any previous subscribers that no longer match the query are removed.

This can help with workflows such as "Email all users with the attribute `last_login` being >30 days ago" without having to create a new list each time.

Potentially, the query can be lazily evaluated only when a campaign is sending to that list

**Comment by knadh** [comment]
Sending campaigns without lists is not possible as they're tightly coupled. There was a plan to have a `Send campaign` button directly on query results by creating hidden and ephemeral lists that are removed after the campaign. But that wouldn't work with list unsubscription.

I think automation like that falls outside the scope of the project.  Lazy evaluation and automated campaigns, I think Mautic is specifically meant for that.

That said, listmonk's table structure is simple enough for this to be easily scripted outside though.

**Comment by RaghavSood** [comment]
My intention wasn't to send without a list, but rather to define a list as a query - that would allow us to do something like:

1. Define a list `Users using feature X` with a query to check is `x` is true in the subscriber attributes
2. Have the backend use the subscriber APIs to automatically update the subscriber attributes when a user starts using or stops using that feature
3. Campaigns related to feature X can then target the `Users using feature X` list. Each time a campaign is run, the list runs the query to get all the subscribers 

This way, the actual set of emails is dynamic, even though we're still targeting one list - the list itself is not ephmeral.

Agreed that it might be pushing for things out of scope of listmonk though. It can be done out of band via SQL, as you suggested.
