### ISSUE TITLE
Question: Setting up lists email address???

### ISSUE THREAD

**Issue by LavaTiger99** [knadh/listmonk#1292]
Hello,
I was wondering if I can create a custom domain email address and by emailing to that address, distribute a contact list without using the web interface?
For example using GMail to send an email to [students@lists.mydomain.com](mailto:students@lists.mydomain.com) or [instructors@lists.mydomain.com](mailto:instructors@lists.mydomain.com) for example, each of those which has a list of contacts?
Thanks!

**Comment by les-les** [comment]
interesting ... 
have not looked into that feature (if its avail) yet. 

but as far as i red up here -->
https://listmonk.app/docs/concepts/

this might not be possible.
lets have a look if someone can proof us wrong 

br LES

**Comment by candideu** [comment]
@LavaTiger99 If I understand correctly: you want the ability to email students@lists.mydomain.com, which then triggers a mass email to a mailing list from the students@lists.mydomain.com email?

**Comment by knadh** [comment]
listmonk doesn't support list mailboxes or many-to-many communication (like Mailman).

**Comment by les-les** [comment]
so question answered and closed ?
