### ISSUE TITLE
Gmail Email Variations Lead to Multiple Subscriptions and Potential Spam

### ISSUE THREAD

**Issue by prostheboss** [knadh/listmonk#1294]
**Version:**
 - 2.4.0

**Description of the bug and steps to reproduce:**
A vulnerability in listmonk allows users with Gmail addresses to sign up for newsletters multiple times, leading to potential spam and server abuse. Gmail permits variations in email addresses using dots and the plus sign, which are considered equivalent by Gmail, but listmonk treats them as separate addresses. This allows users to subscribe multiple times and continue receiving newsletters even after unsubscribing from one variation of their email address.

For example, a user can subscribe to a newsletter using both "my.email@gmail.com" and "myemail@gmail.com". Gmail considers these addresses equivalent, but listmonk does not. As a result, the user receives multiple copies of the same newsletter.

**Steps to reproduce**
- Sign up for a newsletter with a Gmail address (e.g., "my.email@gmail.com").
- Unsubscribe from the newsletter using the provided link.
- Sign up for the same newsletter again with a different variation of the same Gmail address (e.g., "myemail@googlemail.com").
- Observe that the user is subscribed again and receives the newsletter despite having previously unsubscribed.

**Expected behavior**
After unsubscribing, a user should not be able to sign up again for the same newsletter with a different variation of their Gmail address.

**Suggested fix**
One way to fix this issue is to normalize Gmail addresses before storing them in the database. The following regex can be used to identify and normalize Gmail addresses:

`^([a-zA-Z0-9._%+-]+)(\+[a-zA-Z0-9._%+-]+)?@(gmail|googlemail)\.com$`

When a Gmail address is detected, remove all dots before the '@' symbol and ignore any string after a plus sign. This will ensure that different variations of a Gmail address are treated as the same address, preventing multiple subscriptions and potential spam.

**Comment by knadh** [comment]
- I don't think it's ideal to hardcode this specific rule for a specific e-mail provider into the core.
- Dots and pluses may be legitimately used by users to classify incoming e-mails.

Also, the risk surface here is unclear. Why would a user knowingly enter multiple versions of their own address to receive multiple copies of the e-mail?

**Comment by prostheboss** [comment]
Regarding your first point, I agree to some extent, but gmail is very prevalent so it is not like a small random provider
and regarding point 2, normalizing them to the same myexample@gmail.com from whatever variation will prevent unsolicited opt in emails, I think the potential negative consequence outweighs the off chance that someone uses the dots and pluses to classify their incoming emails.

The risk surface that a malicious actor could use the connected mailing server to spam thousands of email signup requests to gmail accounts, flooding inboxes and thus getting reported, this could lead to the mail server getting blacklisted and all its future emails going to junk which can be detrimental for some people. 

I have personally created an intermediary API that does this on the off chance that a bad actor could try to sabotage our mailserver. It would be trivial for me to flood one persons gmail inbox with 10,000 opt-in request emails if the subscribing end point is public.

Maybe it is a non-issue and googles problem but I thought I'd point it out anyway.

**Comment by knadh** [comment]
Fair enough. However, hardcoding this behaviour is not desirable as there maybe some installations which may want the e-mail as-is, and some not. Now that would warrant a "Normalize Gmail addresses" switch in settings, which is not nice.

While not the ideal, like you've done, for installations that really need this, it is possible to script this via the API. Also, if somebody is able to send 10K form requests without any sort of rate limits, there are bigger issues at hand! (The hCAPTCHA integration prevents this scenario to a large extent).

Thanks for documenting this though.
