### ISSUE TITLE
Can subscribe to new lists (double-opt-in) if email already sbscribed to another (double-opt-in) but not getting email to confirm 

### ISSUE THREAD

**Issue by les-les** [knadh/listmonk#1299]
Aware the user trying to subscribe to another list is already confirmed in another list.
user A is Confirmed in LIST-XXX
user A wants now subscribe to  LIST-AAA

 
The user can subscribe to new lists (double-opt-in) if email already sbscribed & confirmed to another (double-opt-in) list 
but not getting email to confirm the subscription to the list.  --> this results in status unconfirmed 

(not usable for multi list use with double-opt in) 

in dashboard i can see the user subscribed to the new list but the subscription to the list is not confirmed. 
user A is Confirmed in LIST-XXX
user A is unConfirmed in   LIST-AAA

I Don't think that the option in 
Admin setting to toggle preference management on/off.
will get a bigger benefit. 

the user do not want to edit his settings ... (in some cases) they just want to simply subscribe to another service (list) 

seems a follow up to #316 
a closer look #1257
talkin about unconfirmed user in #1280

(gonna test this with the subscription to a public list) and add information here  04/22/23)

**Comment by knadh** [comment]
This is already fixed in https://github.com/knadh/listmonk/commit/152bd37c22133e03898772e90bd167cb867e16f3 in the master branch and will be available in the next release. If you need to access it now, you can clone the repository and compile a version locally.

**Comment by les-les** [comment]
Thx,
Cool thing!
Thx a lot!

Not sure if I dare to....
Better for me to wait till next release ;)


Thx les
