### ISSUE TITLE
Question about errors and logging.

### ISSUE THREAD

**Issue by jwoertink** [knadh/listmonk#13]
I just got this deployed to AWS elastic beanstalk. I have nginx sitting in front of it so I can do the basic auth stuff like suggested in some of the notes, and it's all running on Docker. When I visit my page, I get a 500, so I had some questions here.

~~1. How do I do logging?~~
~~2. Nginx error.log is reporting `crypt_r() failed (22: Invalid argument)`. Any idea if that's listmonk related or not?~~
3. Is there a way to configure where errors are logged?

**Comment by jwoertink** [comment]
1. ok, I guess logs were available through `docker logs -f`. 
2. Not really a listmonk error. I just need to configure nginx.

Those are answered, but the main thing I guess is, is there a way to configure where logs are sent?

**Comment by mr-karan** [comment]
@jwoertink docker logs to `/dev/stdout` and `/dev/stderr`. The logs are collected by the docker daemon and stored in your node's host path (by default). The same can be configured (`/etc/docker/daemon.json`) in your docker daemon settings to setup other logging drivers, logrotate policy and a bunch of other things, which you can read more [here](https://docs.docker.com/config/containers/logging/configure/).

**Comment by jwoertink** [comment]
Cool, thanks for the info!
