### ISSUE TITLE
504 {"message":"Method Not Allowed"}

### ISSUE THREAD

**Issue by Vinutha-Garimella** [knadh/listmonk#130]
Hi, I am trying to send `Confirm your subscription(s)` campaign emails to the subscribers from send-in-campaign tab. 
I am getting the following error in listmonk 
`Failed to load resource: the server responded with a status of 504 () upstream request timeout`
I have configured smtp section like this
```[smtp]
    [smtp.outbound]
        enabled = true
        host = "zonemta-outbound"
        port = 587

        # "cram", "plain", or "login". Empty string for no auth.
        auth_protocol = "plain"
        username = "admin"
        password = "*****"
        # Format to send e-mails in: html|plain|both.
        email_format = "both"

        # Optional. Some SMTP servers require a FQDN in the hostname.
        # By default, HELLOs go with "localhost". Set this if a custom
        # hostname should be used.
        hello_hostname = ""

        # Maximum concurrent connections to the SMTP server.
        max_conns = 10

        # Time to wait for new activity on a connection before closing
        # it and removing it from the pool.
        idle_timeout = "15s"

        # Message send / wait timeout.
        wait_timeout = "5s"

        # The number of times a message should be retried if sending fails.
            max_msg_retries = 2

        # Enable STARTTLS.
        tls_enabled = true
        tls_skip_verify = false```

**Comment by Vinutha-Garimella** [comment]
creating new campaign results in status finished but the mails has not been sent to any subscribers on the list (i.e Opt-in list)
![image](https://user-images.githubusercontent.com/33555892/84021853-f9dc9380-a9a2-11ea-9cc8-afb2ac1b584b.png)

**Comment by knadh** [comment]
This is strange. 504 happens when the request timed out. Either there's something off with the network configuration, or the DB request timed out (bad credentials?)

E-mails are handled on separate threads, so SMTP connectivity issues will not produce a 504 on the app. I'm not sure what's happening here. Seems something to do with your environment / configuration.

**Comment by Vinutha-Garimella** [comment]
@knadh  thank you for reply 
I have fixed the issue there was some smtp host configuration miss match in my `config.toml` file.
