### ISSUE TITLE
Find subscriber id by email through API

### ISSUE THREAD

**Issue by Loocos** [knadh/listmonk#1303]
**Is your feature request related to a problem? Please describe.**

I need to find the subscriber ID in order to add him in a given list. If already created in Listmonk, I get a 409 HTTP code which result to "This email address already exist" and it doesn't add the list ID to the current one.

**Describe the solution you'd like**
Two ways are possible : 
- Handle the modification if the subscriber already exist from the same API route to create a new subscriber or return the ID with the code error
- Create a new route to find a subscriber ID by email (or complex query)

**Comment by knadh** [comment]
- You can catch the 409 response and take action (update, for example).
- You can use the [`GET /api/subscribers` API](https://listmonk.app/docs/apis/subscribers/#get-apisubscribers_2) to issue an arbitrarily complex search query. In your case, `query: subscribers.email = $email`.

**Comment by Loocos** [comment]
Thank you @knadh !
