### ISSUE TITLE
It is not formatted correctly in Outlook.

### ISSUE THREAD

**Issue by micha141076** [knadh/listmonk#1305]
**Version:**
 - listmonk: v2.4.0
 - OS: Docker

Hello.
When I start a campaign, it is not formatted correctly in Outlook. 

 `<div class="wrap" style="background-color: #fff;padding: 30px;max-width: 325px;margin: 0 auto;border-radius: 5px;">` 
This doesn´t work. only in the browser.

Do I have to do something else?
BR Michael

**Comment by candidexmedia** [comment]
Hi BR,

Outlook is a pain to work with, email-wise...

Check out the resources I shared at the end of this issue: https://github.com/knadh/listmonk/issues/1231
