### ISSUE TITLE
Better installation documentation

### ISSUE THREAD

**Issue by 3DPixel** [knadh/listmonk#1306]
**Is your feature request related to a problem? Please describe.**
The documentation to install ListMonk is missing a lot of information and has a number of assumptions.
As someone who has never installed it before, I'm starting from the absolute bottom.
The documentation doesn't outline any prerequisites and expects you to know what they are.
For example, 
1. I've created a new linux install in Azure, I've downloaded the linux binary and extracted it.
2. I've run the ./linkmonk --new-config and edited the file, changed the default passwords to something more secure
3. Ran the ./linkmonk --install command and got:

2023/05/02 16:03:29 main.go:99: v2.4.0 (c668523 2023-03-20T13:50:31Z)
2023/05/02 16:03:29 init.go:138: reading config: config.toml
2023/05/02 16:03:29 init.go:266: connecting to db: localhost:5432/listmonk
2023/05/02 16:03:29 init.go:270: error connecting to DB: dial tcp 127.0.0.1:5432: connect: connection refused

Ok, I would have expected the config.toml to install anything that's missing and continue the install - it doesn't so I thought maybe I'll install PostgreSQL myself.

5. I installed PostgreSQL and re-ran ./linkmonk --install and got this error:

2023/05/02 16:08:28 main.go:99: v2.4.0 (c668523 2023-03-20T13:50:31Z)
2023/05/02 16:08:28 init.go:138: reading config: config.toml
2023/05/02 16:08:28 init.go:266: connecting to db: localhost:5432/listmonk
2023/05/02 16:08:28 init.go:270: error connecting to DB: pq: password authentication failed for user "listmonk"

Again, I would have expected the installer to sort all this out or if not, at least some indication what needed to be done BEFORE running the installer.

6. Ok, so I managed to figure out how to login to Postgre and create a user, which didn't work. so I just changed the password for the detail Postgre account, added that to the config.toml file.. Same error message as in Step 4.

**Describe the solution you'd like**
I'd like documentation that is an absolute step-by-step guide on how to install it, including any pre-requisites, including any other steps along the way that actually get it installed and running.
So far, I've spent/wasted 4 hours fighting with this and not getting anywhere.

**Comment by gegobyte** [comment]
I deployed it on railway instead. There is a direct link on main page to deploy on railway, everything gets setup in less than 2 minutes and you are good to go.

**Comment by MaximilianKohler** [comment]
This has been discussed, and I think we were waiting on them to create some place to list tutorials. See the end of #120.

In the meantime, I made a detailed tutorial here https://github.com/knadh/listmonk/issues/120#issuecomment-1314110010 and linked to another one.

**Comment by MaximilianKohler** [comment]
Now that there are a few guides made, I created a pull request https://github.com/knadh/listmonk/pull/1444 for the Installation page https://listmonk.app/docs/installation/ of the docs to create a "tutorials" section.
