### ISSUE TITLE
Filesystem uploads result in a partial URI for images in emails

### ISSUE THREAD

**Issue by RaghavSood** [knadh/listmonk#131]
This might be related to #104.

We have filesystem uploads enable - when we insert an image into a campaign using the richtext entry, it shows up fine during the preview. However, the email sent out has the URI as `https:///uploads/image.png`, which naturally fails.

**Comment by knadh** [comment]
Will investigate this. For now, if you're okay to switch to the HTML view on the editor, you can manually fix the URL before sending the campaign.

**Comment by RaghavSood** [comment]
We switched to an s3 bucket, which works fine - filesystem was just for testing the flow, so it doesn't actually impact us that much.

Happy to help pass over any logs/try out configs if you need help reproducing it.

**Comment by knadh** [comment]
The filesystem issue is fixed in [v0.7.0](https://github.com/knadh/listmonk/releases/tag/v0.7.0-alpha).
