### ISSUE TITLE
I´m getting unhandled encoding "8bits"

### ISSUE THREAD

**Issue by AngeloBestetti** [knadh/listmonk#1311]
**Version:**
 - listmonk: 2.4
 - OS: Docker

**Description of the bug and steps to reproduce:**
On my logs it´s showing: error scanning bounce mailbox: encoding error: unhandled encoding "8bits"

**Comment by knadh** [comment]
Seems like something is off with the POP mailbox. It should be `8bit`, not `8bits`.

**Comment by AngeloBestetti** [comment]
I just updated to 2.5.1 and the error still
