### ISSUE TITLE
Can't save the smtp server's password!

### ISSUE THREAD

**Issue by supundhanujaya** [knadh/listmonk#1316]
**Version:**
 - listmonk: Latest version
 - OS: Windows 10

I can't save the SMTP Server's password. When I start listmonk manually from cmd instead of runing a service
This popup in the cmd 

⇨ http server started on 127.0.0.1:9000
2023/05/09 05:22:26 init.go:768: reloading on signal ...
2023/05/09 05:22:26 init.go:737: HTTP server shut down
2023/05/09 05:22:26 init.go:760: error spawning process: not supported by windows

![image](https://user-images.githubusercontent.com/56984494/237024209-e484e7d2-0a23-49ba-8242-f8bdb9500941.png)
![image](https://user-images.githubusercontent.com/56984494/237024210-34c31e92-2d91-49db-bd08-641d9717f94a.png)

Please tell me how to fix this.

**Comment by knadh** [comment]
It looks like the settings are being saved and the program is trying to restart, but the automatic restart isn't happening. If you manually restart, the settings should've been saved.

I don't have access to a Windows system to test this quickly, unfortunately. Will debug this when I get a chance.

**Comment by supundhanujaya** [comment]
Any completely free way to deploy this without heroku, Or can we solve this from teamviewer or something 😟

**Comment by knadh** [comment]
You have to have a VPS, preferably Linux, somewhere to deploy listmonk. AWS has a free EC2 tier that you might want to explore.

**Comment by cnemaspis** [comment]
Hello, I have the same problem. I tried to set an environment variable before starting listmonk,exe:
set LISTMONK_SMTP_PASSWORD=my_smtp_password
but it does not work.

**Comment by cnemaspis** [comment]
> You have to have a VPS, preferably Linux, somewhere to deploy listmonk. AWS has a free EC2 tier that you might want to explore.

So you mean we can't run Listmonk on Windows without a VPS ?

**Comment by knadh** [comment]
@cnemaspis listmonk only supports env variables for config inside the TOML config file and not on the settings UI.

> So you mean we can't run Listmonk on Windows without a VPS ?

No. It said "preferably". But, the appropriate platform-specific listmonk binary can run wherever, on your desktop too, although not ideal.

**Comment by cnemaspis** [comment]
> 

Nice euphemism, "not ideal". It is simply not working, as the SMTP password cannot be saved. But thanks for your help.

**Comment by knadh** [comment]
Is the issue you're facing, this? https://github.com/knadh/listmonk/issues/1347

**Comment by cnemaspis** [comment]
> Is the issue you're facing, this? #1347

After several save attempts and manual restarts of listmonk, it worked!
I have no idea why it did not work before.

**Comment by mdio33** [comment]
Hello.
I'm trying out listmonk, in a Windows Server and everytime I try to save any config the listmonk abort with that message.
How I solve that?

Thanks.

**Comment by mdio33** [comment]
The way i solved the problem... create a batch file with:

:a
listmonk.exe
goto a:

It will still abort in every save, but load right away... stupid but it works... so far.
