### ISSUE TITLE
The `data` field missing in API spec (collections.yaml)

### ISSUE THREAD

**Issue by stargazer33** [knadh/listmonk#1317]
**Version:**
 - latest, see https://listmonk.app/docs/swagger/collections.yaml

The API specification in collections.yaml contains multiple errors:
There are many places where the `data` field is missing in the API response.

Here an example (line 700 in collections.yaml):
```
  "/lists/{list_id}":
    get:
      description: retrieves lists with additional metadata like subscriber counts. This may be slow.
      tags:
        - Lists
      parameters:
        - in: path
          name: list_id
          required: True
          description: The id value of the list you want to retreive.
          schema:
            type: number

      responses:
        "200":
          description: response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/List"
```
This creates the following documentation, see screenshot:
![listmonk app_docs_swagger_#_Lists_get_lists__list_id_](https://user-images.githubusercontent.com/161958/237055158-72ae39d9-fc9f-425d-a8b3-6931381b0996.png)

But this is all wrong, see the actual response from Listmonk (mind the `data` field in response):
```
{
  "data": {
    "id": 9,
    "created_at": "2023-05-08T19:09:58.043616+02:00",
    "updated_at": "2023-05-08T19:09:58.043616+02:00",
    "uuid": "d4cb3953-955a-4b24-8b8c-6dcc6df1553f",
    "name": "My cool list",
    "type": "public",
    "optin": "double",
    "tags": [
      "tag2",
      "W"
    ],
    "description": "",
    "subscriber_count": 0,
    "subscriber_statuses": {},
    "subscription_created_at": null,
    "subscription_updated_at": null
  }
}
```
There are **many** places in collections.yaml where the `data` field is missing!
I know about these places:
  POST /lists
  GET /lists/{list_id}
  PUT /lists/{list_id}
  
Please check the  collections.yaml, as far as I understand this `data` field should be in each and every response

**Comment by knadh** [comment]
Tagging @rohansh-tty who contributed the collection to the repo.

**Comment by stargazer33** [comment]
> There are **many** places in collections.yaml where the `data` field is missing! 
> I know about these places: POST /lists GET /lists/{list_id} PUT /lists/{list_id}

One more place where  `data` field is missing:
This is the *.yml file:
```
  /subscribers:
    ...
    post:
      description: handles creation of new subscriber
      tags:
        - Subscribers
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubscriberRegistrationInfo"
```

And this is the real JSON response:
```
{
  "data": {
    "id": 14,
    "created_at": "2023-05-10T00:32:14.907272+02:00",
    "updated_at": "2023-05-10T00:32:14.907272+02:00",
    "uuid": "028b7b88-df5a-464c-8579-aa7d68b4a363",
    "email": "test0005@mycoolemail",
    "name": "test0005@mycoolemail",
    "attribs": {},
    "status": "enabled",
    ...
```
