### ISSUE TITLE
How to connect multiple SMTP mail servers

### ISSUE THREAD

**Issue by youssef1lam** [knadh/listmonk#1318]
Hi guys, can someone provide any guide or documentation on how to link multiple SMTP server to the new listmonk v2.4.0, i can't do it and i have 3 question about this process:

1/What i should put in the SMTP settings Header field ?
![smtp settings HEADER](https://github.com/knadh/listmonk/assets/125463331/9260a20b-df5a-4d05-8366-898cb0019bf0)

2/What i should put in the campaign settings from email and header field ?
![campaign settings from email and header](https://github.com/knadh/listmonk/assets/125463331/db109d66-0402-4051-8b96-d020d40e2a41)

3/What i should put in the general settings from email field ?
![general settings from email](https://github.com/knadh/listmonk/assets/125463331/dfb72683-126f-46ef-a51b-35276cf67144)

Please anyone can help with this problem, it will be appreciated.

**Comment by knadh** [comment]
- Click on the `+ Add new` button on the SMTP settings page (bottom of the form) to add any number of SMTPs.
- SMTP headers / custom headers on campaigns are optional. You don't need to put anything there.
- When you send our e-mails, they've to go from a "From" address. If you use multiple SMTP servers, they should all accept this address (or the from address you specify on the campaign).
