### ISSUE TITLE
A/B multivariate mailings

### ISSUE THREAD

**Issue by tttp** [knadh/listmonk#132]
Hi,

Doing "simple" A/B tests on the subject line (ie sending two different subjects to 5% of your list and sending the best performing one to the rest) makes a big difference (we regularly see double digits improvements on the view/open rate)

Under the hook, I suppose we can already build on the the top of what's there with the go template
{{if .Subscriber.UUID modulo 2}} 
  Variant A
{{else}} 
  Variant B
{{end}}

However, 
1) can we use already go template on subject lines?
(I failed when I tried ;)
2) would it be easy to randomly select n% of the list, use that for the "trial" mailing, check the result and let the user decide which version to send to the remaining 1-n%?

**Comment by knadh** [comment]
1. Go templates are not supports on the subject line, but this should be straight forward to implement.
2. You could possibly use Postgres' `RANDOM()` in a segmentation query to copy subscribers to two different lists and send campaigns separately. A feature like this would be out of listmonk's scope though.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/64d44707c2828b8f6442d42d2fe8b7b966607310 adds `{{ templating }}` support to subject lines. Will be available in the upcoming release.
