### ISSUE TITLE
Recipient address rejected: User unknown in virtual mailbox table

### ISSUE THREAD

**Issue by xplosionmind** [knadh/listmonk#1324]
**Version:**
 - listmonk: 2.4.0
 - OS: [Yunohost](https://yunohost.org) (Debian 11)

**Description of the bug and steps to reproduce:**
When sending a SMTP test email to a specific email address, I get: `550 5.1.1 <******@*******>: Recipient address rejected: User unknown in virtual mailbox table`. The test email works for other addresses. It might be useful to note that the recipient provider is Proton Mail.

**Screenshots:**
![Screenshot from 2023-05-11 12-41-17](https://github.com/knadh/listmonk/assets/42862428/efcb9ee1-156b-46ec-8b63-08c5b77dad57)

**Comment by knadh** [comment]
hm, the error `Recipient address rejected: User unknown in virtual mailbox table` is the SMTP server complaining that the mailbox doesn't exist. Doesn't seem like a client (listmonk) related issue as it's working with other addresses. Maybe something to do with the `from` e-mai?

**Comment by xplosionmind** [comment]
> the SMTP server complaining that the mailbox doesn't exist. Doesn't seem like a client (listmonk) related issue as it's working with other addresses.

But it does exist, and I properly received emails with previous listmonk versions… could you help me troubleshoot this?

---

> Maybe something to do with the `from` e-mai?

I do not know… how can I verify?

**Comment by knadh** [comment]
I'm not sure what's happening here without being able to reproduce the issue. `from` e-mail, some mailserver have a from-to mapping where only specific `from` emails work for certain `to` mails. That's unlikely to be the case here I'm guessing.

**Comment by ArunJRK-KM** [comment]
If @xplosionmind  you are using postfix to send mails from a custom server it might be searching for the the mailbox in that particular server where postfix is situated at. This typically happens if you are using two services. One to send mail and another to receive mail. In this case follow this to disable local delivery of mail by postfix. https://support.plesk.com/hc/en-us/articles/12377846922775
