### ISSUE TITLE
"Not found" when sending transactional email using API

### ISSUE THREAD

**Issue by stargazer33** [knadh/listmonk#1325]
**Version:**
listmonk v2.4.0 (c668523 2023-03-20T13:50:31Z)

**Description of the bug and steps to reproduce:**
I am trying to send transactional Email using Listmonk API: (from my Java code, generated from [collections.yaml](https://listmonk.app/docs/swagger/collections.yaml)

From the client log:
```
POST http://localhost:9001/api/transactional
{"subscriber_email":"test0003@mycooltestdomain.com","template_id":3}

<-- 404 Not Found http://localhost:9001/api/transactional 
{"message":"Not Found"}
```

There are many problems with this call:
1. the error message should be improved. **What** is not found? email? template? something else?
2. It can not be email template id=3 because it exists:
![tx-template](https://github.com/knadh/listmonk/assets/161958/374e164e-b0f9-448d-a67a-c5647925fd11)

**Comment by knadh** [comment]
@stargazer33 let's not open new issues for problems in the Swagger collection. We can track them here https://github.com/knadh/listmonk/issues/1321. And as we've discussed on that thread, the Swagger collection has a lot of errors and cannot be relied on until they're fixed.
