### ISSUE TITLE
SMTP working fine in mailwizz, not with listmonk

### ISSUE THREAD

**Issue by mihairaulea** [knadh/listmonk#1328]
I have deployed listmonk using railway.app. I have configured the SMTP servers with the same credentials that i use with my mailwizz instances that are working fine.

1. Testing the connection by sending a test email works fine and listmonk says "Test message sent" 
2. The email is never received, although, again, in the mailwizz instance the emails are being sent
3. Starting a campaign in listmonk works, and the campaign goes into "Finished" state with no errors logged, although again the emails are not being sent.

Can you please help me figure this out?

**Comment by knadh** [comment]
If there are no errors logged in the `Settings -> Logs` console, that means that the target SMTP server is accepting the e-mail, returning OK, but silently failing them after.

**Comment by MaximilianKohler** [comment]
Sorry if this is off-topic, but I'm really curious why someone would switch from Mailwizz to Listmonk.

**Comment by mihairaulea** [comment]
Quality of UI. Ease of use. The ability to run it out of the box on
railway.app which makes this system scalable.

I am using this for my SaaS, abillionleads.com

**Comment by knadh** [comment]
Hi @mihairaulea,
If `Settings -> Logs` shows no errors, that means the mails were successfully delivered to the upstream SMTP. Seems like the SMTP is silently discarding them for some reason. Wouldn't be possible to figure this out from the client side, unfortunately.
