### ISSUE TITLE
Documentation missing for :subscriberId/optin

### ISSUE THREAD

**Issue by tricoos** [knadh/listmonk#1335]
The endpoint :subscriberId/optin to (re)send an opt-in e-mail is not yet documented.

**Comment by knadh** [comment]
Hi @tricoos. I, unfortunately, do not have time currently to look at the documentation. If you've spotted an error or missing information, would appreciate a PR with a fix.

**Comment by tricoos** [comment]
@knadh It's this doc here, correct? https://github.com/knadh/listmonk/blob/master/docs/docs/content/apis/subscribers.md

**Comment by knadh** [comment]
Yep, that's the one. Thanks!

**Comment by pratik-codes** [comment]
@tricoos If you can explain more about the documentation here I can create a PR for it. In case you are not working on the enhancement

**Comment by tricoos** [comment]
@pratik-codes I'm not working on it, feel free to do it - I found this method mentioned in an issue: https://github.com/knadh/listmonk/issues/927#issuecomment-1231459744
It works, but it's not documented.
