### ISSUE TITLE
Token-baed authentication for the API

### ISSUE THREAD

**Issue by tricoos** [knadh/listmonk#1336]
From a security perspective you should never ever use the API credentials on a website directly, because if your website gets hacked the intruder can login to your listmonk with these credentials and access all subscriber data which is the worst thing that can happen from a GDPR (EU) perspective. Of course he could also use the acount to send SPAM mails.

I therefore was forced to create my own REST API utilizing tokens I can easily revoke that is called by the website. The service then actually calls the listmonk API. If the website is hacked the only thing the user can do is send opt-in mails and subscribe or unsubscribe e-mail addresses - he can't even get access to the full list of users as I didn't implement that method on purpose.

Therefore instead of adding multi-user support I'd rather see token authentication for the API as an additional way of authentication. That should be quite easy to implement.

**Comment by knadh** [comment]
> Therefore instead of adding multi-user support I'd rather see token authentication for the API as an additional way of authentication.

Unless there are fine grained permissions per token, it would be the same as the single user login+token setup right now. To implement this properly, there has to be multi-user support (where some "users" are just tokens with limited permissions).

For now, you could use one of the many stand alone auth proxies and only allow the necessary API endpoints via it, eg: `POST /api/subscribers`.

**Comment by tricoos** [comment]
@knadh I think it depends on how it's implemented. Essentially you could just add some checkboxes to the backend for an API token and check in the URL paths for that and forbid access when the specific function is called not set for access for the token - I don't see any need for user management here.
I think that should be quite easy to implement and dramatically increase security when someone uses the API.

**Comment by LuigiClemente** [comment]
Why reinvent the wheel? Ory Kratos and Keto can be used in this project. It would save all the headache of implementing permission from scratch. It uses go, its lightweight and you can bootstrap all in docker together! https://www.ory.sh/docs/kratos/quickstart
