### ISSUE TITLE
Resend campaign to unopens

### ISSUE THREAD

**Issue by elronalds** [knadh/listmonk#1337]
It doesn't appear to be possible to re-send a campaign to unopens. It was discussed within #1107 regarding pruning these subscribers that haven't opened in x days.  When using other mailing list software we have been able to re-send to those that haven't opened the email and this would improve engagment for those.

It might useful to have an option to re-send the campaign to such subscribers.

**Comment by MaximilianKohler** [comment]
This is definitely a very useful feature if it could be implemented. Important to note that the accuracy would be quite limited due to inaccurate open tracking #1025,

**Comment by benstaf** [comment]
I would like to send campaign to opens, can subscribers be segmented in this way?

**Comment by MaximilianKohler** [comment]
Yes: https://github.com/knadh/listmonk/issues/1458#issuecomment-2034720098

**Comment by 1000i100** [comment]
is this query easly adaptable for unopened ?
https://github.com/knadh/listmonk/issues/1458#issuecomment-2034720098
`EXISTS(SELECT 1 FROM campaign_views WHERE campaign_views.subscriber_id=subscribers.id AND campaign_views.campaign_id=<put_id_of_campaign>)`
