### ISSUE TITLE
Enable multiple subscriber imports

### ISSUE THREAD

**Issue by mihairaulea** [knadh/listmonk#1338]
**Enable the possibility of performing multiple subscriber imports**

Replace 

[func initImporter(q *models.Queries, db *sqlx.DB, app *App) *subimporter.Importer {](https://github.com/knadh/listmonk/blob/cb2a57925227d0bc390e6ecfe406365ddf85513b/cmd/init.go#L471)

with 

```
func initImporter(q *models.Queries, db *sqlx.DB, app *App) []*subimporter.Importer {
	// Create a slice to hold multiple importer instances
	importers := []*subimporter.Importer{}

	// Create each importer instance with its own configuration
	for i := 0; i < app.constants.MaxConcurrentImports; i++ {
		importer := subimporter.New(
			subimporter.Options{
				DomainBlocklist:    app.constants.Privacy.DomainBlocklist,
				UpsertStmt:         q.UpsertSubscriber.Stmt,
				BlocklistStmt:      q.UpsertBlocklistSubscriber.Stmt,
				UpdateListDateStmt: q.UpdateListsDate.Stmt,
				NotifCB: func(subject string, data interface{}) error {
					app.sendNotification(app.constants.NotifyEmails, subject, notifTplImport, data)
					return nil
				},
			}, db.DB, app.i18n)

		// Append the importer instance to the slice
		importers = append(importers, importer)
	}

	return importers
}
```
and do the necessary changes in using it

[func handleImportSubscribers(c echo.Context) error {](https://github.com/knadh/listmonk/blob/cb2a57925227d0bc390e6ecfe406365ddf85513b/cmd/import.go#L17)

I am willing to do this but first i want a sanity check from @knadh

**Comment by knadh** [comment]
Multiple-concurrent imports would be a niche feature that introduces complexities that are probably not worth the effort. Multi-import UI, per-import status tracking, logs, cancellation. The importer uses a mutex right now for state management when it runs as a background job.
