### ISSUE TITLE
Pretty styling for raw html in campaign content views

### ISSUE THREAD

**Issue by RaghavSood** [knadh/listmonk#134]
Sometimes, it's necessary to edit the raw HTML (such as to add `{{ TrackLink "" }}`. It would be nice if the raw HTML could be pretty printed with indentation and syntax highlighting, which would help with preventing accidentally invalid HTML when editing too.

Would also be cool if you could set a `TrackLink` via the UI, or mark an entire campaign/template as `TrackLink`, which would automatically set all links to be tracked in it.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/dc4020679f21b0c8dde39529b200861a59e8e115 adds a syntax-highlighted HTML editor.

![image](https://user-images.githubusercontent.com/547147/86540376-5c816a80-bf22-11ea-92b3-9965b96ba1b0.png)

**Comment by RaghavSood** [comment]
Thank you! I'll try updating our install today and giving all the new features a try

**Comment by RaghavSood** [comment]
Just tested it out, highlighting works well!

Although, now if we have a Rich body of 

```
Test content 123
```

Then add a newline and add an image, it inserts the image between the text instead of after it - I'm not sure if that's related to this change though, if it isn't I'll open a new issue for it

**Comment by knadh** [comment]
Ouch, the image insertion is a (silly) bug. Will fix this.
