### ISSUE TITLE
Ability to provide a thumbnail and description for public archive page

### ISSUE THREAD

**Issue by tkadlec** [knadh/listmonk#1340]
For the public archive page, I would love to be able to provide a thumbnail for each campaign, and a brief 1-2 sentence description. These wouldn't be used in the email itself, only on the list of previously sent newsletters.

I thought I could _maybe_ use the attribs, but it looks like I can't, or I'm trying to reference them incorrectly.

![Screenshot 2023-05-17 at 10 00 21 AM](https://github.com/knadh/listmonk/assets/66536/b2aa4352-ea32-4a45-8f20-69dbf9edc88d)

Is this doable at all?

**Comment by knadh** [comment]
The attribs you've set are correct. You just have to render them in your archive template.

Edit the archive template your using in Admin -> Campaigns -> Templates and add this just before the `</head>` tag.

```
  {{ if .Subscriber.Attribs.thumb }}
    <meta property="og:image" content="{{ .Subscriber.Attribs.thumb }}" />
  {{ end }}
  {{ if .Subscriber.Attribs.description }}
    <meta property="og:description" content="{{ .Subscriber.Attribs.description }}" />
  {{ end }}
```

**Comment by tkadlec** [comment]
Thanks, @knadh! Quick follow-up: can I use them on the new public archive page too? Like so?

![Screenshot 2023-05-17 at 10 33 33 AM](https://github.com/knadh/listmonk/assets/66536/bd0d19ff-0a0d-4601-83dd-a7094d356a7a)

**Comment by knadh** [comment]
Actually, there's a simpler way to do this without using attribs even. If you use the campaign's UUID (copied from the campaigns page) in the filename, then it becomes easier to print it in any template. Eg: `180c7d25-f51a-40bd-8e61-122b2ef03f47.png`

In the archive template, you can use:
```
  {{ if .Subscriber.Attribs.thumb }}
    <meta property="og:image" content="http://site.com/path/{{ .Campaign.UUID }}.png" />
  {{ end }}
  {{ if .Subscriber.Attribs.description }}
    <meta property="og:description" content="{{ .Subscriber.Attribs.description }}" />
  {{ end }}
```

To customize the individual message template, you'll have load [custom templates from disk](https://listmonk.app/docs/templating/#system-templates).

You'll have to copy and override this template `/public/templates/archive.html`. And add the image somewhere around here: https://github.com/knadh/listmonk/blob/cb2a57925227d0bc390e6ecfe406365ddf85513b/static/public/templates/archive.html#L9

`<img src="http://site.com/path/{{ $c.UUID }}.png" />`

**Comment by tkadlec** [comment]
Super slick for the image, @knadh!

But that does leave the description out still, right? Is that possible to retrieve? Or would it require the archive_meta data to be added here? https://github.com/knadh/listmonk/blob/cb2a57925227d0bc390e6ecfe406365ddf85513b/cmd/archive.go#L16

**Comment by tkadlec** [comment]
To clarify, I'd like to add _both_ a thumbnail and a brief description to the public archive.html template.

**Comment by knadh** [comment]
`archive.html` is the page that lists all the individual messages. Do you mean adding description to the individual campaign/message page? That can be done with attribs as described in the original post.

**Comment by tkadlec** [comment]
No, sorry. I'm probably not being super clear. :) 

I mean the archive.html page. Right now, by default, the list is the title of the newsletter and the date. Example:
![Screenshot 2023-05-18 at 8 18 59 AM](https://github.com/knadh/listmonk/assets/66536/898f94ef-1f4b-4710-b9ff-aaf5ece876df)

I'd like to include a thumbnail and brief description for each, like so (fake data here, but of course I'd want distinct thumbs and descriptions for each).

![Screenshot 2023-05-18 at 8 23 34 AM](https://github.com/knadh/listmonk/assets/66536/67e5b89e-e759-41eb-a4a6-b629439b094b)
