### ISSUE TITLE
Send Transactional mail without using template 

### ISSUE THREAD

**Issue by mogili1402** [knadh/listmonk#1342]
I have to send different emails with different structure and content so i can't create template for every email so how can I send a transactional mail without a template

**Comment by knadh** [comment]
If you don't use a set of templates that are reused, then it would just be ad-hoc mails and not necessarily transactional e-mails. Templates are mandatory. You have to use conditional logic to make them as generic as possible for your usecase, I suppose.

**Comment by mogili1402** [comment]
my usecase, is to sent a newsletter containing some "n" number of article(have same format title,desc,image) but those n number is different for every user. So some predefined html template is not possible to create desired number of articles. I also tried replace entire raw html with a variable but the HTML is not rendered.all html code is visible in the mail when i do this. I didn't find an another way for this problem. I was stuck at this problem  last 3 days

**Comment by knadh** [comment]
To render HTML without being quoted, you can use `{{ Safe .yourfield }}`.

If you're generating separate e-mail content for every recipient, then maybe listmonk isn't the ideal solution for you. You've to connect to make one request with the tx API per e-mail to send individual e-mails anyway, might as well connect directly to your SMTP and send.

**Comment by mogili1402** [comment]
That working Thanks 🙂 . Last question that there is also no tracking for views and clicks for transactional mails .....Right ? but I  need tracking for views and clicks  transactional mails I am trying to tweak the code to get those metrics but I unsuccessful So far
 Is it possible or not ?

**Comment by knadh** [comment]
Nice! Tracking is only available for campaigns right now though.
