### ISSUE TITLE
API always returns "E-mail already exists."

### ISSUE THREAD

**Issue by parislettau** [knadh/listmonk#1343]
**Version:**
 - listmonk: v2.4.0
 - OS: [e.g. Fedora]

**Description of the bug and steps to reproduce:**
Adding subscriber via API returns message "E-mail already exists." even if the email (or user name etc.) certainly does not exist. This was working fine for several months and then one day just started doing this. I am not aware of any event that could have caused it.

The API call is made as follows:

```
        // https://listmonk.app/docs/apis/subscribers/#post-apisubscribers
        fetch(`${process.env.LISTMONK_API}/subscribers`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Basic ${process.env.LISTMONK_AUTH}`,
          },
          body: JSON.stringify({
            email: user.email,
            name: user.name ? user.name : user.email,
            status: "enabled",
            lists: [2], // add user to list id 2
            attribs: { ...user, ...account, ...profile },
          }),
        })
          .then((response) => response.json())
          .then(function (data) {
            if ((data.message = "E-mail already exists.")) {
              // TODO
              console.log(data);
          });
```

**Comment by knadh** [comment]
This is extremely strange. Unable to reproduce this. Could you perhaps e-mail me the exact payload you're sending (as a curl request) so that I can try and reproduce it locally?

**Comment by parislettau** [comment]
Problem solved. For some reason, my variable `LISTMONK_API=
https://domain/api` had the "/api" cut off in my Environment variables. So
the api request was being sent to "https://domain/subscribers" instead of "
https://domain/api/subscribers"

Would be good if appropriate data.message was returned (instead of "E-mail
already exists.").

**Comment by parislettau** [comment]
Problem solved. For some reason, my variable `LISTMONK_API=https://domain/api` had the `/api` cut off (something must have happened during a deployment of my app). So the api request was being sent to `https://domain/subscribers` instead of `https://domain/api/subscribers`

Would be good if appropriate data.message was returned (instead of "E-mail already exists.").

**Comment by knadh** [comment]
No problem.

> So the api request was being sent to https://domain/subscribers instead
> Would be good if appropriate data.message was returned (instead of "E-mail already exists.").

https://demo.listmonk.app/subscribers throws a 404 as that route doesn't exist in listmonk. There must've been a reverse proxy config in your environment that was routing that endpoint elsewhere.
