### ISSUE TITLE
SMTP Password Shortening Itself

### ISSUE THREAD

**Issue by LAG-Dan** [knadh/listmonk#1347]
- listmonk: v2.4.0
 - OS: Docker (VPS)

When inputting password for Gmail SMTP option it cuts the password down to 8 characters when I hit save. Is there any way to resolve this that I can't find?
![before_save](https://github.com/knadh/listmonk/assets/68863343/1393ef02-cc1c-47ef-b398-96df4aec51a3)
![after_save](https://github.com/knadh/listmonk/assets/68863343/fd0592bb-e5b4-4a8f-82fc-12ffb8265f80)

**Comment by knadh** [comment]
The password is saved in the DB and it's shortened only on the UI as a simple security practice (to avoid giving away the password length to a viewer).

**Comment by LAG-Dan** [comment]
> The password is saved in the DB and it's shortened only on the UI as a simple security practice (to avoid giving away the password length to a viewer).

ohhh i was confused, thank you :)
