### ISSUE TITLE
Error while installing: “server misbehaving” message

### ISSUE THREAD

**Issue by xplosionmind** [knadh/listmonk#135]
Hello everybody. I’m trying to install listmonk on my Ubuntu 20.04 server. I’m very much looking forward to use this service because it seems so awesome and useful.

Unfortunately, after running the `./listmonk --install` command, I get this message error:
```sh
2020/06/14 09:22:07 main.go:90: reading config: config.toml
2020/06/14 09:22:07 init.go:94: error connecting to DB: dial tcp: lookup demo-db on 127.0.0.53:53: server misbehaving
```

I was strictly following these two installation guides:
- [GitHub Wiki](https://github.com/knadh/listmonk/wiki/Configuration)
- [website documentation](https://listmonk.app/#getting-started)

Is there any way I can fix this error? I would really appreciate some advice.

Thanks a lot!

Tommi

**Comment by knadh** [comment]
`demo-db` is a dummy Postgres hostname. You should be pointing it to your Postgres server's address.
