### ISSUE TITLE
No possibility of adding more than 1M subscribers to the base. 

### ISSUE THREAD

**Issue by UstyuzhaninAV** [knadh/listmonk#1352]
**Version:**
 - listmonk: [v2.4.0]
 - OS: [Debian/docker]

**Description of the bug and steps to reproduce:**
No possibility of import more than 1M subscribers to the listmonk. They just don't show up in the sheets 
But a direct query to the database with a count of subscribers shows them.
Seems that this is web ui bug.

**Comment by knadh** [comment]
Can you describe the issue better? What do you see on the subscribers UI? Nothing at all? Or some subscribers? Do the pagination bars not appear? What is the output of `/api/subscribers`? Does it have the right `total` number?
