### ISSUE TITLE
Transactional API returns no error 

### ISSUE THREAD

**Issue by bmclean2** [knadh/listmonk#1353]
When I send a transactional email with the API that returns an error from SMTP server, I still get a 200 status code even though listmonk logs the error. Would it be possible for this to return an error code with a message? Or maybe it is supposed to do this, but it is not happening in my case. From my listmonk logs:

`error sending message 'You've Subscribed': 554 Message rejected: Email address is not verified. The following identities failed the check in region CA-CENTRAL-1: email@example.com`

**Comment by knadh** [comment]
listmonk accepts all tx requests instantly and queues them for sending asynchronously. The queue can drain at an arbitrary time, seconds later, or minutes later (if you have a campaign running). Therefore, it is not possible to return async SMTP errors at the point of API execution, unfortunately.
