### ISSUE TITLE
API Endpoint for getting system/listmonk information

### ISSUE THREAD

**Issue by klepptor** [knadh/listmonk#1354]
**Is your feature request related to a problem? Please describe.**

Hey there!

In my environment I need to always have an up-2-date overview of the software we are using. Therefore it would be nice if listmonk could offer an API endpoint, which returns the used version and maybe the database version (or even the used libs), too.

**Describe the solution you'd like**

New API endpoint /api/stats, which returns the version of listmonk and maybe other useful data (used database, sent messages, etc.)

Thx for your great work!

**Comment by knadh** [comment]
This is a good suggestion @klepptor. Will add an `/api/about` that exposes system info.

**Comment by knadh** [comment]
`GET /api/about`

```json
{
	"version": "v2.4.0",
	"build": "v2.4.0 (#5b40461 2023-06-24T07:31:53+0000)",
	"go_version": "go1.20.2",
	"go_arch": "amd64",
	"database": {
		"version": "PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit",
		"size_mb": 11
	},
	"system": {
		"num_cpu": 8,
		"memory_alloc_mb": 12,
		"memory_from_os_mb": 33
	},
	"host": {
		"os": "Linux",
		"os_release": "6.2.15-200.fc37.x86_64",
		"arch": "x86_64",
		"hostname": "nova"
	}
}
```
