### ISSUE TITLE
mail in

### ISSUE THREAD

**Issue by EtienneBerlin** [knadh/listmonk#1355]
is there a way to use listmonk like a mailinglist-software where listmonk would listen to an IMAP or POP mailaccount and process incoming mails to send them out as campaigns? would be great to have the simplicity and elegance of listmonk to build a small mailinglist ... thanks in advance, etienne

**Comment by knadh** [comment]
Hi @EtienneBerlin. This is not possible with listmonk, which is a one-way newsletter system.
