### ISSUE TITLE
Paginator MaxPerPage default value is too small since paginator was introduced in 2.3.0

### ISSUE THREAD

**Issue by r0ro** [knadh/listmonk#1356]
Hi,

We have a use case where we need to synchronize listmonk db with our main db.
For this we were retrieving batches of 100 000 subscribers calling `/api/subscribers` with `per_page=100000`.

Since the introduction of paginator lib with https://github.com/knadh/listmonk/commit/56a9836e865ff61a74d99edddc7e925ce1d5aa65, the default setting is `MaxPerPage: 50`.

**What could be improved**

- default setting silently restrict the number of entries returned to MaxPerPage meaning that it is not easy to detect the behaviour change
- maybe paginator could return an error when per_page exceed MaxPerPage setting
- when configured with `AllowAll: true` I don't see a rationale to enforce restriction on number of entries per page, but it might still be useful to iterate by batch.

**Describe the solution you'd like**
either:
- remove the MaxPerPage restriction when AllowAll: true 
- remove MaxPerPage in ListMonk paginator config
- increase MaxPerPage to a higher value

**Comment by knadh** [comment]
Thanks for reporting this @r0ro. You're right that if `Allowall=true`, then `MaxPerPage` shouldn't apply. This is merged in the paginator lib and here as well.

**Comment by r0ro** [comment]
Thanks @knadh for this quick response and for the fix
