### ISSUE TITLE
Shows sent even though it fails to send email. 

### ISSUE THREAD

**Issue by The-Real-Thisas** [knadh/listmonk#1358]
**Is your feature request related to a problem? Please describe.**
I tried sending a bunch of emails for two lists ~80 each via gmail (yes I know its a bad idea). It didn't work (obviously) but in the UI it shows it as a success and it shows it as sent.  

The UI shows 

<img width="121" alt="Screenshot 2023-06-02 at 2 05 47 PM" src="https://github.com/knadh/listmonk/assets/59698123/cf5e7329-f45f-4f05-875f-35edcead9600">
<img width="167" alt="Screenshot 2023-06-02 at 2 06 05 PM" src="https://github.com/knadh/listmonk/assets/59698123/1eb59e1b-d89a-42f6-9a44-18dda327f388">

but the logs indicate 

<img width="522" alt="Screenshot 2023-06-02 at 2 06 26 PM" src="https://github.com/knadh/listmonk/assets/59698123/7bc07b8d-2ad4-4241-9d0b-ac562b2d9175">

**Describe the solution you'd like**
Would save much pain if these errors would be shown in the frontend instead having to figure out these ghost emails.

**Comment by knadh** [comment]
Tracking this here: https://github.com/knadh/listmonk/issues/1250
