### ISSUE TITLE
Apache Web Server config sample

### ISSUE THREAD

**Issue by xplosionmind** [knadh/listmonk#136]
Hello everybody, sorry if I post two issues in a row but I’m kind of a noob and I don’t have very much confidence configuring stuff on a server. Thus, I know the bare-bones of Apache, but I can’t get my head around Nginx. Also, I configured everything on my Ubuntu 20.04 server with Apache, and I prefer not to mess stuff up by using Nginx, too.

I found out you provide [this](https://github.com/knadh/listmonk/wiki/Production-Nginx-config) Nginx sample configuration file, would you be so kind to publish a similar one, but with Apache?

I’d really appreciate your help and advice.

Thanks a lot in advance.

Tommi

**Comment by knadh** [comment]
Apache is not really meant to be a reverse proxy, but it can be done with `mod_proxy`. Can you confirm if you would be able to install and enable `mod_proxy` in your hosting environment?

**Comment by xplosionmind** [comment]
Honestly, I have no idea what this is. Nevertheless, if you give me some information, I think I will

**Comment by knadh** [comment]
https://www.digitalocean.com/community/tutorials/how-to-use-apache-as-a-reverse-proxy-with-mod_proxy-on-ubuntu-16-04

**Comment by knadh** [comment]
[v0.7.0](https://github.com/knadh/listmonk/releases/tag/v0.7.0-alpha) does not require a reverse proxy with auth in front of it anymore.

**Comment by alerque** [comment]
This issue should be re-opened, just because it is no longer *required* to use a proxy doesn't mean that documenting how to do so is not needed. You can even assign it to me if you'd like, I have a working Apache setup with a reverse proxy including authentication.

**Comment by knadh** [comment]
I don't think an open issue is the place for this, which essentially is a tutorial independent of listmonk's core functionality. This can be documented as a tutorial on the [docs](https://listmonk.app/docs) page though. The repo is [here](https://github.com/knadh/listmonk-site/tree/master/docs/docs) if you'd like to send a PR with an article.
