### ISSUE TITLE
Subscribe button on webpage always shows localhost

### ISSUE THREAD

**Issue by dac11011** [knadh/listmonk#1360]
**Version:**
 - listmonk: 2.4.0
 - OS: Ubuntu 22.04

Hi,

When configuring Listmonk running in Docker the webpage "Subscribe" and "Mail list archive" button always default to 'localhost'

Im guessing this is the setting app.root_url in the PostgreSQL settings table, but I can't change it because when I do listmonk always sets it back to localhost on start.  Anyway to fix this so I can put my own hostname in there?

Setting root_url in config.toml doesn't seem to help either.

Thanks for the help

**Comment by knadh** [comment]
> Im guessing this is the setting app.root_url in the PostgreSQL settings table, but I can't change it because when I do listmonk always sets it back to localhost on start

That shouldn't happen! Are you changing it from the admin UI? What environment is listmonk hosted in?
