### ISSUE TITLE
error sending SMTP test (Test connection): x509: certificate relies on legacy Common Name field, use SANs instead

### ISSUE THREAD

**Issue by carlosbernabeujuan** [knadh/listmonk#1363]
I've been struggling with this for a few days now. I'm able to send emails via my smtp in other clients, but I don't seem to get it to work in Listmonk. 

I seem to have a problem with my certificate. When I try to add the SMTP config in the settings tab, I get this error.

Question: is it referring to Listmonk's cert or to the SMTP server's cert? 

![Screenshot 2023-06-08 at 17 24 59](https://github.com/knadh/listmonk/assets/17138730/efc0dbe2-f04a-4668-8484-9be5903a3d02)

I'm using Caprover as my PaaS, which has a built-in support for Let's Encrypt

Any help is appreciated.

**Comment by knadh** [comment]
Hi @carlosbernabeujuan. listmonk use's Go's built-in SMTP client, which, it looks like, doesn't support the outdated `Common Name` field in the cert. That said, have you tried `TLS` instead of `STARTTLS` (with Skip enabled, although that is not recommended)?

**Comment by carlosbernabeujuan** [comment]
Yes, I've tried it to no avail. I was selfhosting Listmonk and iredmail and it seems iRedMail also creates the certs without the SANs, so I'm also stuck there also. I think I will use a managed SMTP for now and try to selfhost everything in the future when I don't have a time constraint. Thanks a lot for your help
