### ISSUE TITLE
Two emails per subscriber

### ISSUE THREAD

**Issue by bmclean2** [knadh/listmonk#1365]
How do you all handle the situation where a business client/stakeholder purposely provides two emails and would like to have emails sent to both. Is the most straightforward way to handle this to create two subscribers with the same name?

**Comment by knadh** [comment]
Hi @bmclean2, yes, that would be the right way to do it. Each e-mail ID is treated as a distinct subscriber. For readability, you could assign the same name to both. Names have no effect on how e-mails are sent.
