### ISSUE TITLE
"Error starting import: an import is already running" even after import process is finished

### ISSUE THREAD

**Issue by Arsenalist** [knadh/listmonk#1369]
**Version:**
 - listmonk:2.4
 - OS: Mac M1

I'm uploading to ListMonk using Node and even after I successfully call the import endpoint using Axios and all the records are written, the next time I call the API I get this error:

Error starting import: an import is already running

I have to make a DELETE call to `/api/import/subscribers` and only then can I upload again successfully.

**Comment by Arsenalist** [comment]
Here is the code that I'm using to upload the file. This is pretty easily reproducible:

```
const json = JSON.stringify({delim: ',',  mode: "subscribe", lists: [listId], overwrite: true})
const form = new FormData()
form.append("params", json)
form.append("file", fs.createReadStream(uploadedCsvFile.path), {filename: "import.csv"})
await axios.post(url('/api/import/subscribers'), form, {auth})
```

**Comment by Arsenalist** [comment]
More on this. This error happens even after I verify that the import has finished by calling `/api/import/subscribers/logs` which returns:

```json
{
    "data": "2023/06/12 15:14:14 importer.go:162: processing 'import.csv'\n2023/06/12 15:14:14 importer.go:329: imported finished\n"
}
```

**Comment by knadh** [comment]
The `DELETE` call was by design to retain the state of the last import so that it's visible on the import page until the admin comes and clears it manually. I'll explore separating the actual import session + state retention so that this explicit call isn't required.
