### ISSUE TITLE
Dynamic form creation

### ISSUE THREAD

**Issue by dabanhfreak** [knadh/listmonk#1375]
**Is your feature request related to a problem? Please describe.**
Right now listmonk is the most promising self-hosted solution available. However, the key missing feature that stops me using it is the very basic form building. Coming from Mailchimp and Mailerlite, the fact that I can't build the form is a no-go, particularly since I am a sole trader, and novice with HTML, and I have no idea how to implement JSON and APIs.

**Describe the solution you'd like**
Something that I can build visually which I can do in above mentioned paid services. This will then output a HTML output that I can copy/paste straight into my website. Copying (stealing) from paid services could work.
Alternatively, have an assortment of premade forms could work, where the HTML can be tweaked manually by those who can't write HTML but can _sort of_ read it. Generating code with integrated JSON/APIs would help non-techy users who have no idea how that stuff works.

**Comment by knadh** [comment]
https://demo.listmonk.app/admin/lists/forms <-- Is this what you're referring to?

**Comment by c-seeger** [comment]
Agree, we are currently evaluating listmonk for one of our companies. It looks very promising. Default form customization would be a great feature, although you can customize it by using your own html/css.
