### ISSUE TITLE
SMS/MMS support (with a gateway service like SignalWire, etc.)

### ISSUE THREAD

**Issue by heyakyra** [knadh/listmonk#138]
Mostly curious if this would ever be considered down the line (since it obviously wouldn't be a near-future goal). It would be extremely valuable to be able to store phone numbers for contacts that can be used for bulk SMS messages through a gateway like SignalWire, Plivo, Nexmo, or Twillio. 

More people actively engage and check SMS messages than email, but there are very few tools that hadle not only SMS (Spoke) and not only email (Listmonk, Ghost) but both (ERPNext, maybe Corteza). The CRMs that do both are a bit heavy, so something like Listmonk could be ideal for 95% of use cases.

**Comment by knadh** [comment]
Internally, listmonk has a generic `Messenger` interface that is meant to be extensible to any type of outgoing messages, not just e-mail. This isn't very easy, but is definitely on the cards.

**Comment by heyakyra** [comment]
Part of the challenge of this well be formatting of the phone numbers, since this differs by country and differs still based on the SMS gateway API provider being used

**Comment by knadh** [comment]
E-mail addresses will remain the primary identifier for subscribers. It's too ingrained. That should be fine though as other addresses such as phone numbers could be keys in subscriber attributes. eg: `{"phone": "+1 123 456"}`. The respective `Messenger` interface can be responsible for formatting different types of addresses.

**Comment by knadh** [comment]
This will be available soon. WIP: https://github.com/knadh/listmonk/tree/postback

**Comment by heyakyra** [comment]
Amazing, did not expect to see a start on this so soon! 

> E-mail addresses will remain the primary identifier for subscribers. It's too ingrained.

What about someday migrating to UUID's since people can have multiple email addresses, etc?

**Comment by knadh** [comment]
This is now complete and merged to master https://github.com/knadh/listmonk/commit/6cf43ea67493e771aa96c827b6ac3c37404138c4. Release shortly in [v0.8.0](https://github.com/knadh/listmonk/milestones/1).
