### ISSUE TITLE
Any way to add dynamic Feedback-ID header fields?

### ISSUE THREAD

**Issue by sezginriggs** [knadh/listmonk#1381]
Hello,

I want to add Feedback-ID header for Gmail Feedback Loop. Header has the following format.

`Feedback-ID: a:b:c:SenderId`

Here the "SenderId" is something mandatory and unique, and a, b, c fields are optional and can include things like campaign id, subscriber id etc.

I know I can add custom header for campaign but is there any way to insert dynamic subscriber id etc. to fields of this header?

**Comment by knadh** [comment]
This isn't possible currently, @sezginriggs.

**Comment by sezginriggs** [comment]
Thank you @knadh
