### ISSUE TITLE
Support for bulk recipents in Messengers

### ISSUE THREAD

**Issue by RtiM0** [knadh/listmonk#1382]
**Is your feature request related to a problem? Please describe.**
Listmonk sends thousands of requests to my backend server where I've set an endpoint to ingest postback messages. My backend can better handle a campaign if it has to send bulk messages.

**Describe the solution you'd like**
Messenger settings should have a switch which can send the list of all recipients in one go. One problem I see is incompatibility with personalised/templated messages but I'm sure there will be a workaround for that.

**Comment by knadh** [comment]
This is problematic. One request per message is a transaction which can be tracked atomically. Either it goes through or it fails. Batching many records no longer allows simple error tracking, retrying, timeouts etc. SMTP also does one one mail per transaction.

Also, listmonk opens keep alive connections. it's absolutely fine to open a few connections and send thousands of requests per second.
