### ISSUE TITLE
SMTP password resets + 504 5.7.4 Error Code

### ISSUE THREAD

**Issue by m33k333** [knadh/listmonk#1383]
-  listmonk: 2.4.0
 - OS: MacOS Monterey 12.1

Trying to integrate Protonmail via Proton Bridge using the SMTP tab in settings. Have updated everything correctly. However, when entering the password and hitting enter or pressing Save button, it saves but the characters of the password reset to the original filler pw every time. Then, when trying to send a test email, I receive this code (which I believe is related to incorrect PW):

504 5.7.4 Unsupported authentication mechanism

Screenshot descriptions:
1. All correct SMTP data entered but with the generic filler PW characters.
2. PW updated to reflect correct PW from protonmail server (reverts back to the first screenshot as soon as it is saved)
3. Error code when attempting to send test email.

Please help!

<img width="1095" alt="1" src="https://github.com/knadh/listmonk/assets/135166922/c1c47215-5140-4021-8086-00bd7392cdde">
<img width="1095" alt="2" src="https://github.com/knadh/listmonk/assets/135166922/44f3771c-5491-43d6-a59f-b2acc4237c24">
<img width="887" alt="3" src="https://github.com/knadh/listmonk/assets/135166922/fb1ce81d-ddb9-47d2-94fe-72332036001d">

**Comment by knadh** [comment]
Have you tried non-CRAM login methods?

Password shortening itself, that's just UI behaviour. Please see this: https://github.com/knadh/listmonk/issues/1347

**Comment by m33k333** [comment]
@knadh Yes, when I try all other auth protocols (login, plain & none) this is the error code I receive:

<img width="882" alt="4" src="https://github.com/knadh/listmonk/assets/135166922/f2df3544-d4c5-4856-971e-868d50cd163b">

So maybe the error is a separate issue than the password thing.

**Comment by m33k333** [comment]
Just following up. Any ideas how to fix this?

**Comment by knadh** [comment]
I tried this with the local Protonmail bridge and it works.

- 127.0.0.1 (port 1026)
- TLS: STARTTLS. Skip TLS verification: ON
- Auth protocol: PLAIN
- From e-mail (in Settings -> General): This should be your Proton e-mail ID. I think this is where it may be going wrong.

**Comment by hashborgir** [comment]
I can confirm the problem with the password field. It always overwrites the password field with the default filler password right after you hit save.

Sending test mails is a pain because of this.

**Comment by knadh** [comment]
@hashborgir you needn't hit `Save` to send test-emails. Saving removes the password from the UI for security reasons.

**Comment by hashborgir** [comment]
> @hashborgir you needn't hit `Save` to send test-emails. Saving removes the password from the UI for security reasons.

Oh well I'll be damned. It's just that everytime you go to send a test email, you have to type in the password. It it possible it can be saved? That retyping of the password every time you go to that tab is a pain.

**Comment by m33k333** [comment]
> I tried this with the local Protonmail bridge and it works.
> 
>     * 127.0.0.1 (port 1026)
> 
>     * TLS: STARTTLS. Skip TLS verification: ON
> 
>     * Auth protocol: PLAIN
> 
>     * From e-mail (in Settings -> General): This should be your Proton e-mail ID. I think this is where it may be going wrong.

This solved it (updating the from email in General)! Thank you so much. 

A few more questions now that it's up and running:

-Is it possible to remove the 'Powered by listmonk' notice at the bottom of each email?
-In analytics, "views" don't show up (assume this is email opens) but "clicks"(on tracked links) do, why might this be?
-I'm finding that, having attempted several test campaigns, they don't send everytime. The rate is about half when I use the "send test message" form on the side. I don't receive any errors in the terminal or notice of bounces in analytics - the email just sometimes won't show up. Is this a bug or can we be sure that when a campaign is live this won't happen?

Thanks for your time!

**Comment by knadh** [comment]
> -Is it possible to remove the 'Powered by listmonk' notice at the bottom of each email?

You can edit it out of the template. `Campaigns -> Templates`

>  -In analytics, "views" don't show up (assume this is email opens) but "clicks"(on tracked links) do, why might this be?

The e-mail client is not loading the pixel by default or an AdBlocker is blocking it. Both rightly so and expected.

> -I'm finding that, having attempted several test campaigns, they don't send everytime. The rate is about half when I use the "send test message" form on the side. I don't receive any errors in the terminal or notice of bounces in analytics - the email just sometimes won't show up. Is this a bug or can we be sure that when a campaign is live this won't happen?

If there are no errors in the log, it implies that the mail server accepted the mail and didn't deliver it (or it went to spam).

**Comment by ArchanaJanumpally** [comment]
> > [@hashborgir](https://github.com/hashborgir) you needn't hit `Save` to send test-emails. Saving removes the password from the UI for security reasons.
> 
> Oh well I'll be damned. It's just that everytime you go to send a test email, you have to type in the password. It it possible it can be saved? That retyping of the password every time you go to that tab is a pain.

@knadh  It would be great if you could answer this.  I am setting up smtp settings in the database but in UI when i want to test Test Connection UI is asking me to Re-Enter/Re-type Password SMTP password.  I completely agree retyping of the password every time you go to that tab is a pain. Do you have any workarounds or any suggestions to minimize this issue.

**Comment by knadh** [comment]
> I am setting up smtp settings in the database but in UI when i want to test Test Connection UI is asking me to Re-Enter/Re-type Password SMTP password. I completely agree retyping of the password every time you go to that tab is a pain.

This is a trade-off. Testing SMTP credentials can't be that frequent. Once they're tested and saved, unless the credentials are changing (at which point, new ones have to be pasted), when are they tested again? If it's just a general test, then the campaign test works.

Also, it is not possible to use the saved password from the DB for testing. When the config of a server is changed (say host/port etc.), then it's no longer the same server. There is no way the system can figure out if the server's identity itself is being changed or just basic config. The trade-off is just to enter the password again that's required for testing, again, because it's an infrequent action.
