### ISSUE TITLE
Configuring Listmonk with Postfix or something similar

### ISSUE THREAD

**Issue by briksb** [knadh/listmonk#1384]
Hi there!

I need to prepare a demo of an open source email marketing tool (which can run in Linux) for a computer science subject at my uni, and I've chosen Listmonk.

I just installed Listmonk on my Linux Mint xfce using Docker and I'm able to run it on localhost:9000.

The thing is, as part of the project, I need to send a newsletter to 5 recipients but I'm not able to configure the SMTP server properly. I tried using Postfix and Gmail.

When using Gmail I got an error saying that my credentials were wrong (they were correct).

When using Postfix, the connection to it also couldn't be established.

Can anyone tell me which would be the easiest way to run listmonk properly and being able to send this newsletter? That's all I need to do for the moment.

A simple step by step guide to get this thing up and running.

Many thanks in advance!

**Comment by knadh** [comment]
Postfix is not easy to host.

> When using Gmail I got an error saying that my credentials were wrong (they were correct).

With Gmail SMTP, you're not supposed to use your account's password. You've to generate an [app password](https://support.google.com/accounts/answer/185833?hl=en) instead.

**Comment by knadh** [comment]
Admin UI -> Settings -> General. Enter the URL of your installation.

**Comment by knadh** [comment]
You have to have a domain or sub-domain that points to your installation, eg: yoursite.com. If you don't have this and are running this in a private environment, then you cannot use link tracking.
