### ISSUE TITLE
Empty Log

### ISSUE THREAD

**Issue by dspandrea** [knadh/listmonk#1386]
Hi all,
i don't know why email are not sent (i sent few campaigns with no problems, and now there is something wrong).

But Settings->Logs is empty and i cannot investigate the issue.

In campaign settings it's all ok, statistics tell me that all email was sent, but i didn't receive nothing.

Thank you

**Comment by knadh** [comment]
That implies that the SMTP server accepted e-mails from listmonk without errors and then probably discarded them for some reason. You'll have to inspect your mail server logs or speak to the mail server provider.
