### ISSUE TITLE
Custom CSS and JavaScript Changes Not Taking Effect After Initial Save

### ISSUE THREAD

**Issue by hashborgir** [knadh/listmonk#1388]
**Version:**
- listmonk: v2.4.0
- OS: Ubuntu 22.04
- Docker: Latest official image

**Description of the Bug and Steps to Reproduce:**

Save custom CSS or Js. If you modify the contents, the custom fles content doesn't get updated.

1. Install the listmonk application.
2. Configure the application.
3. Ensure that the application is running correctly.
4. Go to `Settings > Appearance` in the application.
5. Enter custom CSS or JavaScript code in the provided fields.
6. Save the changes.
7. Two files are created: `/public/custom.css` and `/public/custom.js`.
8. Attempt to edit the content of these files through the `Apperance` tab again. Save changes.
9. Notice that any changes made and saved after the initial/first save are not taking effect.

**Additional Information:**

This bug has been confirmed and is reproducible on three separate installations of the listmonk application.

It prevents from successfully modifying the custom CSS and JavaScript files (`/public/custom.css` and `/public/custom.js`) after the initial save.

**Comment by hashborgir** [comment]
So I found out more. Changes seem to take effect hours after you save. How exactly does this work?
I expect changes to take effect immediately when updating the content of those two files.

**Comment by knadh** [comment]
This is either your browser cache (try a Ctrl+Shift+R after saving), or a CDN or reverse proxy that you have in front of the installation caching static assets (JS and CSS) coming from listmonk. If it's a CDN, you may have to manually clear its cache.

Good that this is brought up. A basic cache busting mechanism can be added to listmonk.

**Comment by hashborgir** [comment]
> This is either your browser cache (try a Ctrl+Shift+R after saving), or a CDN or reverse proxy that you have in front of the installation caching static assets (JS and CSS) coming from listmonk. If it's a CDN, you may have to manually clear its cache.
> 
> Good that this is brought up. A basic cache busting mechanism can be added to listmonk.

I see. I use something called nginx proxy manager and I'll double check for any caching. Thanks!

**Comment by SKJoy** [comment]
Using `CloudFlare > NginX > Docker` & can confirm disabling the CloudFlare proxy didn't help. It sometimes load & sometimes just don't. I hope it loads the customization in some hours and don't panic again.

**Comment by knadh** [comment]
This must be the Cloudflare asset cache. For now, please go to the Cloudflare dashboard and purge the cache for the listmonk domain.

Will figure out a way to add a cache breaker in listmonk when CSS/JS changes.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/0c9dc074791d81c0003d59dc4db4593285fbe90f implements cache breaking.
