### ISSUE TITLE
How can I utilize the Sendgrid API on Lismonk?

### ISSUE THREAD

**Issue by Arcelibs** [knadh/listmonk#1389]
Greetings! I employ the Sendgrid API for the purpose of sending emails.
However, I do not see a field in Settings > SMTP where I can enter the API.

Would anyone be able to tell me how to utilize the Sendgrid API in Lismonk?

**Comment by knadh** [comment]
You should use SendGrid's SMTP credentials to connect it to listmonk.

**Comment by Arcelibs** [comment]
Ah, I have discovered the solution. 
In the login field, should enter the "APIkey", and in the password field, you should enter the API. 
Then, simply set the TLS configuration to "off," and you should be all set.

**Comment by JasonWangA** [comment]
> Ah, I have discovered the solution. In the login field, should enter the "APIkey", and in the password field, you should enter the API. Then, simply set the TLS configuration to "off," and you should be all set.

could you pls show me how you config sendgrid "APIKEY" with login fiekd  more specifically? I have tried use apikey several times, while finally failed. Thanks
