### ISSUE TITLE
Allow use of S3-compatible storage buckets (e.g. Minio, Wasabi, etc.)

### ISSUE THREAD

**Issue by eddiewang** [knadh/listmonk#139]
Are there any plans to extend the S3 storage method to allow for a custom S3 endpoint url?

This would allow third-party S3-compatible storage systems to work in tadem with listmonk. This is especially ideal if for self-hosted environments.

**Comment by knadh** [comment]
@mr-karan?

**Comment by mr-karan** [comment]
Currently there are different "providers" for uploading media. These satisfy `media.Store` interface. Any new provider should do the same. I took a look at [Minio SDK](https://github.com/minio/minio-go) and the upload/get functions look similar to S3 provider.

I think we could add Minio to start with. Will add this to my TODO :+1:

**Comment by eddiewang** [comment]
awesome! glad to see it being prioritized. let me know if you need any assistance. from quickly gandering at the code it would be as simple as allowing the endpoint for the amazon s3 url to be custom set as an environment variable. don't think you would need to use the Minio SDK, since it should be compatible with all s3 clients.

**Comment by mr-karan** [comment]
Ah that makes it easier. Will try it out with [Minio playground](https://play.minio.io:9000/minio/).

**Comment by eddiewang** [comment]
hi @mr-karan were you able to get this working with the playground? if you need a dev instance, happy to provide u with one.

**Comment by mr-karan** [comment]
@eddiewang I was able to upload it by simply changing the endpoint. The `Get` handler would require some changes as we had made some changes specific to AWS S3. I'm exploring that further on how to provision for both of them semantically in one interface.

**Comment by eddiewang** [comment]
@mr-karan cool! Was the policy on the filet set correctly? Assuming we need a public bucket using ‘mc policy set download <instance>/<bucket>’ should do the trick.

**Comment by ifokeev** [comment]
Hi! What is about this feature? There are no option in settings to change the host

**Comment by knadh** [comment]
Ah, this isn't available on the settings UI in the current version. Will make it pluggable in the next release.

**Comment by joicemjoseph** [comment]
#231 is an attempt to add webdav.

**Comment by c-nv-s** [comment]
@knadh @mr-karan so can I just confirm that, despite this ticket being closed, there still isn't the possibility to add a custom s3-compatible provider in listmonk?
That is to say, there is no means via the UI or via environment variable to change the base (hard-coded) amazon url string to another custom one like minio?

**Comment by knadh** [comment]
Thanks for bringing this up @c-nv-s. This was missed. Will add the backend URL as a configurable field on the S3 settings UI in the upcoming version.

**Comment by selfagency** [comment]
> Thanks for bringing this up [@c-nv-s](https://github.com/c-nv-s). This was missed. Will add the backend URL as a configurable field on the S3 settings UI in the upcoming version.

When I try to modify this setting it is grayed out.
