### ISSUE TITLE
Question on list imports through API

### ISSUE THREAD

**Issue by amferreiro** [knadh/listmonk#1390]
Hello, im uploading a CSV file to bulk import subscribers, but im missing the status confirmed option like in the web. Is there a way to do this?

**Comment by knadh** [comment]
- `GET /api/import/subscribers` returns the status of an import.
- `GET /api/import/subscribers/logs` returns the logs of an import.
- Once an import ends (finished, failed etc.), you need to clear the state by sending a `DELETE /api/import/subscribers` before POSTing a new one. This behaviour is changing and there wouldn't be a need to do this in the upcoming release.
