### ISSUE TITLE
What happens after "Timed out waiting for free conn in pool" error?

### ISSUE THREAD

**Issue by sezginriggs** [knadh/listmonk#1392]
Hello,

When running campaign I'm getting "timed out waiting for free conn in pool" errors and I would like to learn what happens after that? Does listmonk try again later for these subscribers or are they just dropped and will never get the email?

Thank you very much....

**Comment by knadh** [comment]
The e-mail is retried N times (as set in SMTP settings) before being dropped and marked as an error.

**Comment by sezginriggs** [comment]
Thank you @knadh Are they counted as "Sent" on "Campaigns" screen? And what's the delay between two tries? I guess it's impossible to set that?

**Comment by MaximilianKohler** [comment]
There is no current delay, but there's a PR to add one: https://github.com/knadh/listmonk/pull/2309

I just got some of these errors at the start of a campaign, and the rest of the campaign seemed to send ok. I think a retry delay would resolve these.

I'm pretty sure they ARE counted as "sent" on the campaigns stats.
