### ISSUE TITLE
Campaign status "Finished" before all emails were sent 

### ISSUE THREAD

**Issue by hrs-23** [knadh/listmonk#1393]
# Campaign finished before sending all emails. 

We send campaigns to large audiences but number of the emails sent number is always less than the count in the list. 

We use a dedicated IP address.
These emails are sent from SES service using smtp credentials.

Impacting our communication plan during oeak of business season. Here is an example of the latest one: 
![LM](https://github.com/knadh/listmonk/assets/138872193/f63bd3b5-bf94-445f-a4cc-c3386128aa0d)

**Comment by knadh** [comment]
1) Are there errors in Admin -> Settings -> Logs? Mails are only skipped if there are errors even after the configured number of retries.

2) Have you checked SES stats for the number of mails sent?

**Comment by hrs-23** [comment]
1. Settings are all fine. We are on v2.4.0 
2. Yes, nothing unusual. We have only reached 52% of sending quota.

**Comment by runningnoodle** [comment]
Could this be related to issue #1155 ?

I am experiencing the same issue. I have multiple subscribers lists, and the issue occurs on all campaigns that use one of those lists. Campaigns that use another list are not affected.

I have not tried sending to that list recently so I can't check the logs, but I don't remember seeing error in the logs when that happened.

**Comment by shazril** [comment]
Experiencing same issue here. Using AWS SES to send the campaign.

Campaign finished instantly after clicking sending, without any email actually sent.

Using Listmonk 2.5.1
SES sending quota at 34% (32k email remaining).
No error in log, as in the video.

![msedge_Z3ZQ2J4npg](https://github.com/knadh/listmonk/assets/425112/2bce5940-2466-411e-95ef-688342d4d9d4)

https://github.com/knadh/listmonk/assets/425112/5bf37158-3c54-4f00-a908-bbc9dadc2cca

**Comment by MaximilianKohler** [comment]
Wow, this is a bad one. I'm glad I don't have this issue. 

I just noticed that some of my completed campaigns were showing "Sent 2000/2002", but I'm guessing that was due to a couple of the people being unsubscribed/blocklisted already. I can confirm that nothing shows in the logs, so we can only make guesses.

**Comment by knadh** [comment]
@shazril could you please e-mail me at kailash [at] nadh.in? Unable to reproduce this. Seems like a rare edge condition that only kicks in under certain conditions/environments. I think this has to be debugged in your environment.

**Comment by shazril** [comment]
Check your inbox, @knadh. Thanks.

**Comment by keybits** [comment]
I was getting similar behaviour. Instant finish and no messages sent, even to confirmed addresses.

Then I remembered I'd changed the list from single opt-in to double opt-in. Setting it back to single opt-in resulted in all emails being sent.

Not sure if this is intended behaviour, but maybe helpful in looking into the above.
