### ISSUE TITLE
Add Slug for Campaign URL

### ISSUE THREAD

**Issue by versun** [knadh/listmonk#1394]
**Is your feature request related to a problem? Please describe.**
Currently, when publishing a campaign, the URL address is automatically generated using a UUID. 
However, this may not be user-friendly or memorable for customers who want to visit the campaign page.

**Describe the solution you'd like**
I would like to request the ability to add a custom slug to campaigns before publishing. 
This would allow users to create their own URL addresses that are more user-friendly and memorable. 
For example, instead of a URL like "https://demo.listmonk.app/archive/468bbc7f-6880-4d61-bde0-5f6728ebb790", users could create a URL like "https://demo.listmonk.app/archive/welcome-to-listmonk". This would make it easier for customers to remember and share the URL with others.

Overall, I believe this feature would improve the user experience for both campaign creators and customers, as it would allow for more personalized and memorable URLs.

**Comment by knadh** [comment]
Whew, this was a non-trivial addition: https://github.com/knadh/listmonk/commit/0d319ad9fd95a50bf6cb62b2f6c8fa10c5de0a16

![image](https://github.com/knadh/listmonk/assets/547147/d15fdfe4-6529-4351-899a-ab3fc45aacb8)
