### ISSUE TITLE
Using listmonk also for mail discussions

### ISSUE THREAD

**Issue by ttjaden** [knadh/listmonk#1395]
Thanks for this great piece of software!

One question regarding the possibilities of listmonk:

- Is it possible to use lists for mailing discussion (as mailman or groups.io) ?
- It would be great if the was an option for single lists to choose if the members can reply to each other as a group

Is this possible or is listmonk "only" one way communication?

**Comment by knadh** [comment]
Hi @ttjaden. listmonk is only for one-way newsletters. Two-way mailing lists are a far more complex usecase and currently there are no plans for that.
