### ISSUE TITLE
Archive links lead to 'not found' page when individual tracking is enabled

### ISSUE THREAD

**Issue by sonologic** [knadh/listmonk#1396]
**Version:**
 - listmonk: v2.4.0
 - OS: docker container (listmonk/listmonk:latest)

**Description of the bug and steps to reproduce:**

When 'Individual subscriber tracking' is enabled, TrackingLinks in archived campaigns will lead to a 'not found' json response instead of linking through to the target url.

Steps to reproduce:
1. Enable 'Individual subscriber tracking'
2. Set up a list
3. Create a campaign with a TrackLink, enable public archiving of campaign with 'Campaign metadata' set to `{}`
4. Send out campaign
5. Go to public archive
6. Click the tracked link

**Screenshots:**

![image](https://github.com/knadh/listmonk/assets/694584/ee7490c8-2512-4211-b2df-c222a1c021c7)

**Comment by theyashwanthsai** [comment]
Hello, I am very new to open-source contributing. Can I work on this issue as I am confident in this? Thank you

**Comment by sonologic** [comment]
I figured out I can work-around this issue by creating a dummy user and use that user's UUID in the 'Campaign metadata':

```
{ "UUID": "5a837423-a186-5623-9a87-82691cbe3631" }
```

**Comment by sonologic** [comment]
I noticed a distinct lack of documentation on the archive feature. I'll try to write some and create an MR, including the use of campaign metadata.
