### ISSUE TITLE
DKIM support

### ISSUE THREAD

**Issue by JorikSchellekens** [knadh/listmonk#140]
Adding [DKIM](https://tools.ietf.org/html/rfc6376#section-3.7) support would make list monk the ideal minimal configuration email list manager for a small self hosted instance. Currently most email recipients are marking emails sent from listmonk as spam.

If I've missed a simple way to configure DKIM please let me know, in that case it might be nice to have some simple docs explaining how that would work.

DKIM support could also be supported by https://github.com/knadh/smtppool however I'm not sure that's in it's intended scope. As an example this might be a nice implementation:

```go
e := Email{
	From:    "John Doe <john@example.com>",
	To:      []string{"doe@example.com"},

	// Optional.
	Bcc:     []string{"doebcc@example.com"},
	Cc:      []string{"doecc@example.com"},

	Subject: "Hello, World",
	Text:    []byte("This is a test e-mail"),
	HTML:    []byte("<strong>This is a test e-mail</strong>"),

        BKIM: BKIM{
        PrivKey: &privKey,
            Headers: []string{"from"},
        }
}
```

Let me know whether this issue should be raised at https://github.com/knadh/smtppool aswell.

This would need some ui to manage DKIM private keys

**Comment by knadh** [comment]
DKIM signing is done by the SMTP servers centrally. It is uncommon for clients to do this (as a client could then write any signature with no bearing on the SMTP host's FQDN). What SMTP server are you using?
