### ISSUE TITLE
Caching in subscriber list

### ISSUE THREAD

**Issue by crossphoton** [knadh/listmonk#1400]
**Description of the bug and steps to reproduce:**
If I have greater than 20 subscriber list, pagination is applied on in the `All Lists` page and I get 21st and other list on the other page.

Now if I go to all subscribers, select all, and click manage lists, the `Lists to apply to` field only shows the lists last fetched on the `All Lists` page. If I left the `All Lists` page on page 2, I'll get only 21 and onwards list in the `Lists to apply to` field.

**Screenshots:**
Can't attach due to privacy issues.

**Comment by knadh** [comment]
Thanks for reporting this @crossphoton. Will investigate.
