### ISSUE TITLE
Import subscribers bug

### ISSUE THREAD

**Issue by rezasys2** [knadh/listmonk#1401]
**Version:**
 - listmonk: 2.4
 - OS: Ununtu 20

**Description of the bug and steps to reproduce:**
I have a correctly structured CSV file, when I want to import it, it says "Finished
0 / 29 records"
How shall I check the logs?

**Comment by rezasys2** [comment]
Here are the logs

data: {"id":"","type":"error","message":"2023/07/16 10:59:26 manager.go:422: error sending message 'Finished: a.csv import': dial tcp 188.114.97.3:25: i/o timeout\n","data":null}

data: {"id":"","type":"error","message":"2023/07/16 11:20:21 manager.go:422: error sending message 'Finished: a.csv import': timed out waiting for free conn in pool\n","data":null}

**Comment by rezasys2** [comment]
problem solved with running yarn build on frontend folder,
But I have 200,000 contacts and there is a 10,000 limitation

imported 10000

**Comment by knadh** [comment]
Sorry, confused as to how you're running this. Are you doing a custom compilation using `make dist`?

- There is no limitation in the number of records that can be imported. You can have a CSV with millions of rows and it'll be read and imported in batches.
- The log you shared is the admin notification for import failing as SMTP hasn't been configured. This doesn't affect the actual import.
- Import logs show up in the box below the import progress bar on the same page.

**Comment by rezasys2** [comment]
No i'm using the default settings.

**Comment by knadh** [comment]
Closing this as it has not been possible to reproduce this issue.
