### ISSUE TITLE
post /public/api/subscription always returns has_optin: false

### ISSUE THREAD

**Issue by ag1s** [knadh/listmonk#1402]
**Version:**
 - listmonk: [eg: v1.0.0]

**Description of the bug and steps to reproduce:**
I want to know if a user is already subscribed when doing a POST
**Screenshots:**

**Comment by knadh** [comment]
There is no `has_optin` field in the subscriber response. You can look at the `lists[..].subscription_status` field to see if it's `confirmed`.

**Comment by ag1s** [comment]
> There is no `has_optin` field in the subscriber response. You can look at the `lists[..].subscription_status` field to see if it's `confirmed`.

That's the output I get from calling the endpoint, since it's not documented it's hard to know what's the expected behaviour tho

<img width="919" alt="image" src="https://github.com/knadh/listmonk/assets/6601142/a6f52526-c70c-4c25-b87e-56d247e26321">
