### ISSUE TITLE
AxiosError: Request failed with status code 413 when uploading bigger size images

### ISSUE THREAD

**Issue by deamonkillerM** [knadh/listmonk#1404]
**Version:**
 - listmonk: [latest docker image]
 - OS: [Ubuntu]

**Description of the bug and steps to reproduce:**
1. Using S3 as Media Storage
2. Not able to upload an image whose size is 2.5MB. When I tried to upload that, getting **AxiosError: Request failed with status code 413**

**Screenshots:**
Added screenshots of error popup and developer tool console

![Screenshot from 2023-07-19 15-19-40](https://github.com/knadh/listmonk/assets/94852677/d5b40709-2044-4646-bdd6-549778d44e6d)
![Screenshot from 2023-07-19 15-14-11](https://github.com/knadh/listmonk/assets/94852677/81d824dc-ffcc-47e4-b8f9-257eb3b0fa6a)

**Comment by knadh** [comment]
Do you have a reverse proxy like Nginx in between? 413 is "entity too large", which means something is limiting the size of the file that is being uploaded.

**Comment by deamonkillerM** [comment]
Thanks @knadh 

Yes we use nginx, I fixed it by adding `client_max_body_size` in nginx config file and it's working.

Btw thanks for all the great work you're doing, one question, I'm so much distracted with many things while i was working, some random/stupid thoughts comes into my mind and that eats my day and making me lazy. How do you stay consistent, healthy, exercise and focus on things?
