### ISSUE TITLE
Settings are not persisting after clicking on save!!

### ISSUE THREAD

**Issue by venkateshreddy5353** [knadh/listmonk#1406]
**Version:**
 - listmonk: v2.4.0
 - OS: Almalinux 8

Followed docker installation steps given here https://listmonk.app/docs/installation/#production 
after adding the required configuration in the settings section, after clicking the save button, app is reloading and the saved changes are gone!!

**Screenshots:**
![image](https://github.com/knadh/listmonk/assets/62872395/a9db8521-3d45-4529-b68d-7aca7f227231)

changes are reverted
![image](https://github.com/knadh/listmonk/assets/62872395/bcd26e40-37b9-44a5-9b7c-e8d27665388b)

same is the case for SMTP configuration as well.

**Comment by knadh** [comment]
Sorry, missed this issue. Looks like the database is being reset (`--install`) on every restart. Please see this: https://github.com/knadh/listmonk/issues/1089
