### ISSUE TITLE
Question: Avoid views for test-messages?

### ISSUE THREAD

**Issue by samuelT2** [knadh/listmonk#1408]
Hi

Is it somehow possible to not count the views for test-messages? Whenever I sent a test message (which I do several times until a campaign is ready to send), it already counts towards the the views from the campaign. Or is that only achievable by using a copy from the same template, withouth the tracking link?

**Comment by knadh** [comment]
Forgot to update this. This was fixed in the last release, v2.5.1.

**Comment by samuelT2** [comment]
Hi @knadh - Is this really resolved? I still see view counts, though my campaign didn't start yet and I have only sent test messages. Can I help you with any debug info from my end? I'm running the latest version (v.2.5.1).

**Comment by knadh** [comment]
Can you share the URI of the pixel that loads in your test mail from the browser inspector? You can redact your domain name. It should end in `px.png`.

**Comment by samuelT2** [comment]
Sure, here it is. One thing - I usually copy the last campaign and edit it. Could this be the reason?

`<div>&nbsp;<img src="https://listmonk.johndoe.com/campaign/d314711c-445a-47fc-8534-755fdf9b2d5e/00000000-0000-0000-0000-000000000000/px.png" alt="" /></div>`
