### ISSUE TITLE
Error in adding unsubscribe url in transactional template 

### ISSUE THREAD

**Issue by D8thisland** [knadh/listmonk#1409]
listmonk 2.4 via docker
When I try to add {{ UnsubscribeURL }} to a transactional template I get the next error
{"message":"error compiling transactional template: template: base:802: function \"UnsubscribeURL\" not defined"}

In a normal campaign template theres no issue adding it.

**Comment by knadh** [comment]
Hi @D8thisland. Transactional e-mails are not mailing lists, hence there's no concept of unsubscribing. It's only relevant to campaign templates.
