### ISSUE TITLE
Opt-in not sent when adding existing user to new list

### ISSUE THREAD

**Issue by tobiasdierich** [knadh/listmonk#141]
**listmonk version:** v0.6.2-alpha

**Steps to reproduce:**

- Create a new user without subscribing them to any list -> save the user
- Add the user to a new double opt-in list

**Result:**

User will be subscribed to the list without receiving any double opt-in mail.

**Expected behavir:**

Existing users receive opt-in mail when you assign them to a double opt-in list.

Everything works as expected if I create a new subscriber and immediately assign them to a double opt-in list.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/75547b609d6328cd9c147e10d55f1ba25607e8ca fixes this. Will bundle this in the next release.
