### ISSUE TITLE
Under Attack? Spike in Bot Users

### ISSUE THREAD

**Issue by anaclumos** [knadh/listmonk#1413]
<img width="527" alt="Screenshot 2023-07-28 at 9 08 17 AM" src="https://github.com/knadh/listmonk/assets/31657298/76e16f09-e571-4a75-8e87-8227b6a03e4e">

I am experiencing a spike in subscribers with genuine-looking emails. However, they subscribed to the test mailing list, which is public but not embedded in a form anywhere other than the default newsletter website main page. This has not been linked anywhere and has "do not subscribe" in the name, so I assume these are bot users or someone targeting the server. Therefore, the assumption is that someone is attacking using the subscription API. I learned that the subscription API does not require authentication. Is this correct?

**Comment by knadh** [comment]
You can disable the `Enable public subscription page` option in Settings -> General if you don't want public signups. If you need it and you have a bot problem, you can enable CAPTCHA in Settings -> Security

**Comment by anaclumos** [comment]
@knadh Thank you so much!
