### ISSUE TITLE
Cost estimates for self-hosting Listmonk

### ISSUE THREAD

**Issue by pooriaarab** [knadh/listmonk#1415]
Heyy,

Just came across this from btw.so blog while searching for Convertkit open source alternatives. 

Curious what are some ways I can calculate the hosting cost we might incur for self-hosting Listmonk?

Based on rough estimates per 1,000 subscribers, per 10 campaigns, per 1 email sent daily (min/max)

And what server platforms are recommended?

**Comment by knadh** [comment]
listmonk is very light on resources. A single core instance with a few hundred MBs of RAM should be enough to process large number of e-mails. Basically, a $2 or $5 instance from any VPS provider like DigitalOcean or Vultr should work.
