### ISSUE TITLE
Subject Length Threshold?

### ISSUE THREAD

**Issue by anaclumos** [knadh/listmonk#1416]
Hi, I was trying to create some campaigns with the API. I got a response of `Invalid length for subject.` What is the limit of the subject? I cannot find any relevant source from the documentation.

**Comment by knadh** [comment]
There is a 200 char limit for subject. I realise that this isn't ideal. Will increase this to 1000 in the upcoming release.

**Comment by anaclumos** [comment]
Yes, I am not well-versed in how Go handles characters, but I feel like that's not even a Unicode character count. I had an i18n-ed newsletter with ~80 characters in JavaScript string, which returned me the above string.

**Comment by anaclumos** [comment]
@knadh When can we expect this change to roll out?

**Comment by knadh** [comment]
Final leg of testing's happening tomorrow, so in the next couple of days.
