### ISSUE TITLE
Create multiple accounts

### ISSUE THREAD

**Issue by m33k333** [knadh/listmonk#1417]
Curious if I'm able to make a variety of logins for different mailing lists/projects/instances while running them on the same machine (not simultaneously, obvs)? I saw the thread for multi-user support, but that seems to be related to giving different users access to the same instance with their own unique passwords. Any help is appreciated, thanks!

**Comment by knadh** [comment]
Are you referring to different DB installations?

**Comment by m33k333** [comment]
> Are you referring to different DB installations?

One installation on one machine, but different "accounts"/logins/projects.

**Comment by knadh** [comment]
This isn't possible right now, unfortunately as listmonk doesn't have multi-user support yet. This will continued to be tracked at https://github.com/knadh/listmonk/issues/543

**Comment by xeruf** [comment]
So https://github.com/knadh/listmonk/issues/543 and this are closed now, even though the original requests are not met - having different users create and manage their own mailing lists as I also mention in https://github.com/knadh/listmonk/issues/2395
