### ISSUE TITLE
Real Double-Opt In: Right now -> Single Opt-In or Triple Opt-In

### ISSUE THREAD

**Issue by activenode** [knadh/listmonk#1418]
**Is your feature request related to a problem? Please describe.**
People that started subscribing my newsletter were utterly confused that they have to click a link AND then again a button which is very unusual and leading to them not succesfully confirming.

The current situation hence is: Single Opt-In vs. Triple Opt-In instead of Double.

**Describe the solution you'd like**
Real double opt-in. But since it's a breaking change again I am offering to provide it as a feature flag in the settings. I will create a branch and provide the PR.

**Comment by knadh** [comment]
I personally don't like the idea of accidentally clicking a link in the e-mail and getting subscribed. I remember vaguely that in some jurisdictions, there's even legislation for explicit confirmation.

That said, you can do this: https://github.com/knadh/listmonk/issues/1205#issuecomment-1440436809

**Comment by activenode** [comment]
Hm totally get it man. The proposed solution is a solution. BUT: I would love to provide a PR that provides a checkbox that eases this. Like that wouldn't change the default behavior :)

**Comment by agvst** [comment]
> Hm totally get it man. The proposed solution is a solution. BUT: I would love to provide a PR that provides a checkbox that eases this. Like that wouldn't change the default behavior :)
> 
> Like just a toggle checkbox and we're all set and everybody is happy. Because my subscribers complained about this behaviour really.

In a side note, some mail clients like google/microsoft's can and will click links for you, so for example it's harder to track open rates for those emails.

If you send a clickable (by a bot) link without any other further human interaction, you get exposed to this

It's a hard UX balance I agree the current setup feels too cumbersome and most users will fall off the funnel and do not convert. They need to be really interested on subscribing to follow all the necessary steps.

**Comment by activenode** [comment]
@agvst i get what you're saying but I cannot imagine Mail clients randomly click links. For one simple reason: It would invalidate e.g. Magic Links sent for Logins immediately making them effectively useless.

So I'd assume that concern isn't real, however I am not aware of the exact details how they differentiate it. But I think they do open Images, yes.

**Comment by activenode** [comment]
@knadh are you okay with me opening a PR with a NON-breaking change leaving the defaults as IS and just introducing a safe variant to enable this for those who want it?

**Comment by agvst** [comment]
> @agvst i get what you're saying but I cannot imagine Mail clients randomly click links. For one simple reason: It would invalidate e.g. Magic Links sent for Logins immediately making them effectively useless.
> 
> So I'd assume that concern isn't real, however I am not aware of the exact details how they differentiate it. But I think they do open Images, yes.

It's an old problem and they might handle it better in 2023, you can defensively build on your site some defenses to the use case too, like adding a captcha

https://security.stackexchange.com/questions/211258/do-mail-servers-follow-links-in-emails-as-part-of-a-security-scan-before-inbox-d

**Comment by activenode** [comment]
Which I'd be willing to have a look  into as well. Or detecting the user-agent. I mean there are certain ways, even though with all those magic link nowadays I feel like this isn't a biggie. But again: Willing to find a non-breaking solution.

**Comment by rosano** [comment]
Was going to create an issue for this but I see there's this one and #2429 #1205 and #1876 – maybe worth having a preference toggle for this?

The UX conventions for systems like Ghost, or 2FA implementations on various sites tend to have "a button/link in an email that completes the action on click". I think the way it is now many people may assume it's done without actually finishing the process.

I think the way Ghost does it is a kind of token in the opt-in email URL which works only within the 3 minute period of requesting to subscribe `https://example.com/members/?token=alfa_bravo_charlie&action=signup&r=https%3A%2F%2Fexample.com%2F` – so perhaps if one clicks on it after it would prevent an accidental subscribe.

**Comment by jasenf** [comment]
Posting here because this seems to be the most active thread around this issue..

I know this has been closed a while, but IMHO this triple opt-in process is causing us to lose subscribers.  It's simply not a standard opt-in process for any newsletter I've ever seen.   None of the big newsletter providers operate this way (which I am currently trying to migrate away from).

User's clicking the link from their e-mail are not always expecting to have a follow-on 3rd event (final click on the page) to get access to the newsletter.     I know there are workarounds here, but it all feels very hacky.

Is there any interest in making this at least an optional feature?
