### ISSUE TITLE
Allow compiling and running the project on macOS and windows

### ISSUE THREAD

**Issue by gabriel-vasile** [knadh/listmonk#1421]
Hi, I'm trying to run the project locally, on macos, and I'm having trouble.

To reproduce my problem, you can try compiling the project for macos/windows:
```bash
# GOOS=darwin GOARCH=arm64 go build cmd/*.go
GOOS=windows GOARCH=amd64 go build cmd/*.go

cmd/init.go:705:19: undefined: syscall.Utsname
cmd/init.go:712:20: undefined: syscall.Uname
cmd/settings.go:302:19: undefined: syscall.Utsname
cmd/settings.go:307:20: undefined: syscall.Uname
```
`uname` syscall is only available for linux in golang. This code does not compile on macos/windows:
https://github.com/knadh/listmonk/blob/a440b79530ca9a73f24fd176be122eece98d5151/cmd/init.go#L703-L714

A more portable way to write that bit of code is to use [`Utsname` and `Uname`](https://pkg.go.dev/golang.org/x/sys/unix#Uname) from the `golang.org/x/sys/unix` package, but that does not work for windows.

**Comment by knadh** [comment]
Thanks for the PR. There was a broken import in it, which I've fixed and merged in a separate commit.

**Comment by gabriel-vasile** [comment]
Ah sorry, there were two places where `syscall.Uname` is used:
1. https://github.com/knadh/listmonk/commit/dcb87a39b7cf78fdc8aa49a4b84e745f7110b577
2. The code I linked in first message here

Second place is still blocking compilation on macos/win.

**Comment by anascann** [comment]
hello, @knadh syscall is still blocking the compilation for mac OSX. 
1. https://github.com/knadh/listmonk/blob/master/cmd/init.go#L705
2. https://github.com/knadh/listmonk/blob/master/cmd/init.go#L712

**Comment by knadh** [comment]
Had to get rid of the field altogether! https://github.com/knadh/listmonk/commit/104c4fc993358b7cfa25f34b0d63c2c40361cf6f

**Comment by gabriel-vasile** [comment]
Thank you!
