### ISSUE TITLE
Multilanguage transactional messages

### ISSUE THREAD

**Issue by davidesteve** [knadh/listmonk#1424]
Hi!

We realize Listmonk is not fully multilanguage yet, but we've seen some shortcuts such as for campaigns in https://github.com/knadh/listmonk/issues/685
 
Is there a way to make transactional messages (on screen and via email) work with multilanguage?

We have different lists, one for each language. When a subscriber signs up to a list, we would like the confirmation messages and opt-in messages to coincide with the chosen language.

We are currently not using the default `/subscription/form` but instead have a custom form for each language that includes the field.
```
<input id="f9d8e" type="checkbox" name="l" value="f9d8e9bb-a552-4c8f-900d-680ba9415d9e">
```
Any suggestion from your side will be really appreciated.

**Comment by knadh** [comment]
Are you referring to the `/tx` API for sending transactional e-mails? There, you can just create a template per language and pick the appropriate template when executing the transaction.

The system template (public and e-mail), it's a bit tricky. You can add `{{ if }}` conditions to system templates to check for list GUIDs/IDs and render the appropriate language string. Please [see this](https://listmonk.app/docs/templating/#system-templates) to see how to customize system templates.
