### ISSUE TITLE
Seeking Listmonk Postgres Migration Steps following Upgrade to Debian 12

### ISSUE THREAD

**Issue by PackMeister** [knadh/listmonk#1425]
Upgraded my Debian 11 server which hosts Listmonk to Debian 12.1

I now have **both** PostgreSQL 13 **and** 15 running on my Debian 12 server, using ports 5432 and 5433 respectively

I restarted and accessed Listmonk 2.4 which is obviously still using PostgreSQL 13.

As PostgreSQL 13 is no longer supported by Debian I'd like to migrate my Listmonk database and configuration to PostgreSQL 15 then delete the unsupported PostgreSQL 13 from my server.

As I can find no Listmonk application backup facilities to export subscribers, campaigns, etc. I presume any backups must be made directly by interacting with PostgreSQL 13 ...yes?

Are there any docs available describing how to backup a Listmonk database from an older PostgreSQL version and restoring it on a newer PostgreSQL version?

**Comment by knadh** [comment]
You can use `pg_dump` to dump the entire database to an .sql file and then re-import it into the new database. This is a standard practice and not unique to listmonk.
