### ISSUE TITLE
How Do I Use Uploaded Media Images In Campaigns?

### ISSUE THREAD

**Issue by PackMeister** [knadh/listmonk#1426]
To-date in all my Listmonk campaigns I've used either hand-crafted or compiled HTML/JS that I copied into each campaign as RAW HTML.   This included images I found online and whose URLs I included in the aforementioned HTML within IMAGE tags.

Going forward many of my campaigns will require custom images having no apriori internet sources or links.

I've attempted to upload some test images via Listmonk's media facility but haven't found any documented examples of how to link to these media in actual campaigns, whether to use absolute vs relative paths, whether I need Listmonk-specific tags/codes, etc.

Are there any downsides to using Listmonk-hosted images in campaigns?

**Comment by Mattifyed** [comment]
You can use the absolute path of the image in your campaign. You'll need to ensure the directory you're storing the media in isn't behind an auth.

**Comment by PackMeister** [comment]
I created my media folder in /opt/media and set its permissions to be same as listmonk executable, namely listmonk:123 via chown -R listmonk:123 /opt/media

However the image I'm trying to display via:

<img height="auto" src="/opt/media/Raincross-2.jpg" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" width="550" />

Yields a broken link....

Permissions on files uploaded to media directory are below:
root@hector:/opt/media# ls -al
total 1468
drwxr-xr-x 2 nixguy  123   4096 Aug  3 09:50 .
drwxr-xr-x 3 root   root   4096 Aug  3 09:48 ..
-rw-r--r-- 1 nixguy  123 119270 Aug  3 09:50 Raincross-1.jpg
-rw-r--r-- 1 nixguy  123 122741 Aug  3 09:50 Raincross-2.jpg
-rw-r--r-- 1 nixguy  123 149479 Aug  3 09:50 Raincross-4.jpg

Permissions for listmonk are below:
-rwxr-xr-x  1 nixguy  123 16132088 Mar 20 06:51 listmonk

What am I missing ?

**Comment by knadh** [comment]
`/opt/media/Raincross-2.jpg` is your local system path. It wouldn't work in a remote e-mail. The actual link will look like `https://listmonk.yoursite.com/uploads/Raincross-2.jpg`.

Please upload the image via the media manager in the admin and user the image icon in the e-mail editor to pick the image and insert from the gallery. That'll insert the image with the correct URL.

**Comment by PackMeister** [comment]
Doh!  You're right.

I was thinking in terms of access by the listmonk server , but email recipients will need a fully qualified URL for the image hosted back on the server.

**Comment by PackMeister** [comment]
That raises another question related to my backup inquiry earlier.
Do Listmonk media files have to be backed up and restored separately from Listmonk's PostgreSQL database?

**Comment by knadh** [comment]
>  Do Listmonk media files have to be backed up and restored separately from Listmonk's PostgreSQL database?

Yes, that's right. Images uploaded to the filesystem have to be backed up separately. A solution to this is to use an object storage system like Amazon S3 (or any S3 API compatible system) instead of the filesystem.
