### ISSUE TITLE
Send campaign to subscribers with certain attributes

### ISSUE THREAD

**Issue by Arsenalist** [knadh/listmonk#1427]
I'm trying to send campaigns to lists which have subscribers, and those subscribers have attributes in JSON like `{"city": "Toronto", "age": 35}`

When creating or starting a campaign, I would like to be also able to specify which subscribers in the list to send the campaign to. For example an expression like `attributes.city = "Toronto"` would only send the campaign to subscribers who have a city field with a value of Toronto in their attributes field.

Does this capability currently exist? If not, is it possible to add it. This would bring listmonk very much on par with offerings like Mailchimp and Wix.

**Comment by Mattifyed** [comment]
Once you run a query on the subscriber list, you'll be able to select all the results of your query on the UI and add them to a separate list using the "manage lists" option. You can then send an email to just that list.

In your example, the query would look something like "subscribers.attribs->>'city' = 'Toronto'.

**Comment by Arsenalist** [comment]
Thank you for that idea. I'm using listmonk entirely in a headless way with my own UI etc.  So is there a way to do what you just said via the API?

The only part that I see missing is creating a list using the `POST /api/lists` endpoint by passing in `"subscribers.attribs->>'city' = 'Toronto'"`

**Comment by Mattifyed** [comment]
I'd try this:

1. Create a list with `POST /api/lists`
2. Filter subscribers with `subscribers.attribs->>'city' = 'Toronto'`
3. Retrieve all subscriber IDs.
4. Update the lists for all results with `PUT /api/subscribers/lists`

**Comment by knadh** [comment]
It's not necessary to retrieve all subscriber IDs. I haven't unfortunately had a chance to document the bulk actions in the API docs, so kindly inspect the request on the UI and replicate that in your headless setup. It is possible to directly move all resulting subscribers from an SQL expression search (the "Select all" checkbox option on the UI) to a new list.

**Comment by Arsenalist** [comment]
Sounds good. Thank you for your guidance.

**Comment by carliblaz** [comment]
I can agree with @kettenbach-it it would be nice to have an option for providing SQL query on lists.
