### ISSUE TITLE
Daily email scheduling with changing campaign body

### ISSUE THREAD

**Issue by christopherpickering** [knadh/listmonk#1428]
Hi! This is a nice looking tool. Thanks for putting it out there!
I’m looking for a list manager to send a daily email to subscriber lists. 
the text from the daily email changes every day. I’m wondering if others have done this and have a suggestion for the easiest way.

my text is basically a subject and message stored in a separate database.
Is the best thing to use the api to create a new campaign every day? It seems like a lot of campaigns and I wonder if there is a way to modify the subject and body of a campaign via api and reuse it. 
That way I could also track the usage of the daily newsletter vs the weekly on..
Any ideas on this are appreciated.

**Comment by knadh** [comment]
You can use Sprig functions (you can find in the docs) in the subject and the e-mail body to generate dynamic content, however, once a campaign is sent, you'll have to create a new one.

Perhaps a system like Mautic is more ideal to your usecase than listmonk.

**Comment by christopherpickering** [comment]
Thank you!
