### ISSUE TITLE
Menu Glitch When Scrolling Outside the Menu

### ISSUE THREAD

**Issue by Gopikrishna-M-A** [knadh/listmonk#1430]
**Version:**
 - listmonk: [v2.4.0]

**Description of the bug and steps to reproduce:**

Upon opening the menu and scrolling the body outside of the menu area, the menu exhibits a glitch that affects its visual appeal. Although the functionality is not hindered, the menu takes approximately 3-4 seconds to fix itself, causing an undesirable visual experience for users.

**Screenshots:**
![IMG_20230804_101040.jpg](https://github.com/knadh/listmonk/assets/84523270/f6224c4f-f60b-46fc-a14d-4aee80272642)

**Comment by rudrapratap63** [comment]
can i contribute to this issue ?

**Comment by knadh** [comment]
Please feel free to send a PR.
