### ISSUE TITLE
Stuck running campaign

### ISSUE THREAD

**Issue by rezasys2** [knadh/listmonk#1433]
**Version:**
 - listmonk: 2.4
 - OS: Ubuntu 20

**Description of the bug and steps to reproduce:**
I'm trying to start a campaign for my 200k users, but it is stuck on 1000/200,000 sent. How do you think I could solve the issue?

**Comment by knadh** [comment]
Are there any errors in Settings -> Logs? It sounds like a batch of e-mails were pulled from the DB to be sent, but are stuck in the outbound SMTP queue. Is using the `Send test e-mail` option on the campaign page resulting in an instant delivery?
