### ISSUE TITLE
Sending opt-in campaign only to people who have been newly added to list

### ISSUE THREAD

**Issue by grssnbchr** [knadh/listmonk#1434]
Hello!

I currently maintain a double opt-in list where I manually add subscribers (no other possibility at the moment). So it's actually single opt-in, to be fair. After a bulk import of about 100 subs I sent an opt-in campaign with a custom template.

Now I noticed that subscribers that I *manually add afterwards* automatically get an email when that button where it says "When new subscribers signup or are added via the admin form, send an opt-in confirmation e-mail." is checked. 

I want to turn that off, because I don't like the style of the confirmation mail and don't have the possibility of modifying the HTML file at the moment, as described [here](https://listmonk.app/docs/templating/#system-e-mails).

So, it might be a bit theoretical and you might say: Just do this above thing and that will solve your problem. But let me still ask (if only for the sake of understanding listmonk a bit better):

Let's say I turn this automatic confirmation off: Is there a way of re-sending my opt-in campaign with the custom template  so only people who have not yet received a confirmation  mail will get it? Or what does another click on "send opt-in campaign" actually do? Resend it to everybody who has not yet double opted in?

Thank you for your help!
Timo

**Comment by knadh** [comment]
Hi @grssnbchr

> so only people who have not yet received a confirmation mail will get it?

This isn't possible. When sending an opt-in campaign, subscribers who have not **confirmed** will receive the e-mails. Keeping track of subscribers who have been e-mailed, but haven't confirmed, is complex. Then the question of "sent X times within X period etc, but not confirmed" come up.
