### ISSUE TITLE
Allow CC and BCC in api/tx

### ISSUE THREAD

**Issue by winterleitner** [knadh/listmonk#1435]
**Is your feature request related to a problem? Please describe.**
In some situations it would be beneficial to be able to send transactional messages to multiple recipients at once.

**Describe the solution you'd like**
Add additional parameters `cc_emails` and `bcc_emails` that both accept an optional array of email addresses.

**Comment by knadh** [comment]
You can use the `subscriber_emails[]` (or `subscriber_ids[]`) param to send an array of e-mails belonging to existing subscribers.

In addition, you can send arbitrary headers in the `headers` param.

**Comment by winterleitner** [comment]
Ok thanks, I will add that to documentation. 👍🏼
