### ISSUE TITLE
Features enabling collaboration among different teams

### ISSUE THREAD

**Issue by zeekhuge** [knadh/listmonk#1438]
Hi @knadh : Thanks for the amazing piece of software.

**Is your feature request related to a problem? Please describe.**
I want to use listmonk in enterprise setting. Allowing different team-members associated with different campaigns to be able to see different stats / templates etc, while at the same time, allow the admin to see everything.

**Describe the solution you'd like**
I would imagine something akin Trello.  A Workspace that could contain multiple Projects / Campaigns, where:
1. You could add individual members to each campaign/project
2. You could add individuals to the entire workspace.

Let me know if you need anymore info on this.

**Comment by knadh** [comment]
Thanks @zeekhuge. Multi-user/multi-tenancy is a big pending feature that's being tracked here: https://github.com/knadh/listmonk/issues/543

It'll happen, but I'm unable to give a timeline.
