### ISSUE TITLE
Edit custom attributes as separate forms

### ISSUE THREAD

**Issue by heyakyra** [knadh/listmonk#144]
Most users will only be able to use custom forms if they are able to view and edit custom attributes as forms (having the front-end parse the json) rather than editintg raw JSON

**Comment by knadh** [comment]
This is how I'd started out originally, but scrapped it as it's really difficult to represent lists, and of course, nested attributes on a UI. Wasn't worth the effort. JSON is simple enough even for non-technical users to quickly figure out.

**Comment by heyakyra** [comment]
Lists and such maybe can be handled as plain text (only handle the first level of the json object as a start). I thought this might be a nice task for me to try if I have some free time, once the new frontend port gets merged
