### ISSUE TITLE
Subscription stays unconfirmed when adding a new subscription from public page

### ISSUE THREAD

**Issue by jicho** [knadh/listmonk#1441]
**Version:**
 - listmonk: 2.4.0
 - OS: Official docker container

**Description of the bug and steps to reproduce:**
When a user subscribes successfully to, for example 2 lists, and subscribes to a 3th public (double opt-in) list the user does not gets an email with the "please confirm" request. In the backend the subscription keeps showing "unconfirmed".

Steps:
* Create multiple double opt-in lists
* Open up the public subscription page in settings
* Send "opt-in" confirmation option in settings
* Open a new browser and go to the subscriptions page
* Subscribe to 1 or 2 lists
* Confirm your email + lists confirmation (one and the same email)
* Go back to the subscriptions page (new browser)
* Subscribe to a new list
* The user does not receives an "confirm" email / in Listmonk the new list is added to the email address, but stays "unconfirmed"

I would expect that the user gets an "please confirm" mail OR that the new list is added and directly active (since the email address was already confirmed).

**Comment by bashmeester** [comment]
Experiencing the same issue with API functionality (version 2.5.1) and double opt-in lists.
`PUT /api/subscribers/lists` adds the existing subscribers to the list as unconfirmed.
No confirmation e-mails are sent.
