### ISSUE TITLE
Error on fileupload on docker (v2.5.0)

### ISSUE THREAD

**Issue by xam-ps** [knadh/listmonk#1443]
**Version:**
 - listmonk: v2.5.0
 - OS: Windows 11, Firefox 116.0.1

**Description of the bug and steps to reproduce:**
1. Clone existing campaign
2. Select file (.pdf, .jpg, .png)
3. Click on upload

Expected behaviour: File gets uploaded
Actual behaviour: I see an error message (see screenshot attached)

Same behaviour when I try to upload files in the "Media" section under "Campaigns"

**Screenshots:**

![Screenshot 2023-08-11 141001](https://github.com/knadh/listmonk/assets/19496449/706b7b9a-05ab-439a-869d-cf60e6df6a09)

**Comment by MaximilianKohler** [comment]
Was it working prior to updating to v2.5, or is this your first time trying to upload?

**Comment by xam-ps** [comment]
Good questions 🤔 Didn't use it for quite a long time. In the past it was working, but not sure if that was on docker already.

Found a solution here:
https://github.com/knadh/listmonk/issues/620#issuecomment-1411078998

The "uploads" folder was missing in my docker container. In the install instructions (https://listmonk.app/docs/installation/) I couldn't find any word about mounting an uploads folder inside the docker container. This could be made a little bit more clear in the instructions IMO or is needs to be created inside, while creating the docker container.

**Comment by MaximilianKohler** [comment]
I see. I don't know enough to understand that comment you linked to, so I didn't run their commands. I used the "easy docker install" and it already created a `listmonk` folder with `data` and `uploads` in it. 

I fixed mine a different way, one comment down in that same thread. I did a pull request on the docs https://listmonk.app/docs/configuration/#media-uploads to update them with what I figured out. If they're still missing info you should add it.
