### ISSUE TITLE
Possibility to use with SQLite

### ISSUE THREAD

**Issue by ribtoks** [knadh/listmonk#1447]
Hi

First of all, thank you so much for developing this awesome project!

I noticed docker-compose.yml only mentions Postgres environmental variables. Is it possible to use listmonk with SQLite? I think it will be enough for my use-cases.

Thank you

**Comment by knadh** [comment]
Hi @ribtoks. listmonk only supports Postgres. It's non-trivial to add SQLite support and currently there are no plans either. Some context here: https://github.com/knadh/listmonk/issues/368
