### ISSUE TITLE
Ability to enable TrackLink for an entire email

### ISSUE THREAD

**Issue by RaghavSood** [knadh/listmonk#145]
Just splitting this into an individual request from #134.

It would be nice to have the ability to mark an entire email as `{{ TrackLink }}` and have listmonk automatically add link tracking to all the links in the email.

Adding the TrackLink manually seems to break Rich Text editing (at least up to 693b939)

**Comment by knadh** [comment]
After looking into this, this is tricky. The HTML content will have to be parsed, links iterated and transformed, and the HTML constructed back. This is very error prone. Same thing with using regex.
