### ISSUE TITLE
Add description field to RSS items

### ISSUE THREAD

**Issue by Sjors** [knadh/listmonk#1455]
Thanks for adding the body the RSS feeds in #1033!

I noticed my RSS reader is showing HTML stuff in the summary:

<img width="1122" alt="Scherm­afbeelding 2023-08-14 om 10 30 18" src="https://github.com/knadh/listmonk/assets/10217/4ffc835f-0d01-4bfe-9fc6-9bb5e3c56b8a">

I think this can be be solved by filling out the `<description />` field, using the html-stripped first bit of the content.

I believe the hard limit is 500 characters, though 250 is probably enough.
https://stackoverflow.com/a/70426837/313633

**Comment by candidexmedia** [comment]
If there was a preheader field https://github.com/knadh/listmonk/issues/1240, it could have doubled as a description field for the RSS...
