### ISSUE TITLE
Auto update in Docker container

### ISSUE THREAD

**Issue by thueske** [knadh/listmonk#1456]
Hey,

I'm running Listmonk for sending bulk emails and I always have the problem when https://containrrr.dev/watchtower/ does an update of Listmonk, the whole instance is offline.

I have to go manually and run the upgrade command.

It would be cooler if this would happen automatically. Is there anything against this?

**Comment by knadh** [comment]
Hi @thueske. I'm not familiar with Watchtower and how it orchestrates upgrades. In an ideal scenario, when the container is upgraded, it should only take a couple of seconds for the updated container to come up.

@mr-karan ?

**Comment by thueske** [comment]
Hey @knadh, thanks.

Watchtower pulls the image and recreates the container. But in case of listmonk i have to execute `docker-compose run --rm app ./listmonk --upgrade` manually. That is worse for automated environments like mine (no other container image has this problem).

**Comment by mr-karan** [comment]
I don't think it's a good idea to automate DB upgrades without first backing up the DB (and I don't think watchtower handles that).

In any case, you can try setting `--include-restarting` (https://containrrr.dev/watchtower/arguments/#include_restarting) flag. In addition to that, you can simply update the `command` section of `listmonk` app container in your `docker-compose.yml` to be something like:

```
command: [sh, -c, "yes | ./listmonk --upgrade --config config.toml && ./listmonk --config config.toml"]
```

So, watchtower will check for newer updates, pull latest image, restart the container and the upgrade will be handled automatically whenever the container is restarted.

This should work for your usecase.

**Comment by thueske** [comment]
Thank you.
