### ISSUE TITLE
How to downgrade listmonk to a previous version?

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1457]
I discovered a major issue with the new version (v2.5.0): https://github.com/knadh/listmonk/issues/1454

I think I need to downgrade listmonk and also restore my old database. 

I have the commands for restoring the old database https://gist.github.com/MaximilianKohler/e5158fcfe6de80a9069926a67afcae11#restore but I can't find the commands for downgrading to v2.4.0. 

Upgrading, for reference: https://listmonk.app/docs/upgrade/

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/issues/1454#issuecomment-1679090643

**Comment by MaximilianKohler** [comment]
> **Downgrading**
> 
>     * Stop listmonk.
>     * Restore your pre-upgrade database.
>     * Assuming you're using docker-compose, edit it and change `listmonk:latest` to `listmonk:v2.4.0`.
>     * Restart

Ah, I found it: https://listmonk.app/docs/installation/#release-candidate-rc - you edit the `docker-compose.yml`.

So these are the commands?
```
sudo docker-compose down
```
Edit the `docker-compose.yml`:
```
x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:v2.4.0
```
```
psql -h 127.0.0.1 -p 9432 -U listmonk
drop schema public cascade;
create schema public;
\q
psql -h 127.0.0.1 -p 9432 -U listmonk -W listmonk < listmonk-preupgrade-db.sql
```
`sudo docker-compose up db`
`sudo docker-compose run --rm app ./listmonk --install`

**Comment by MaximilianKohler** [comment]
>So these are the commands?

>Is restoring the old version's db a requirement? Will it cause problems if you downgrade listmonk while keeping the current db?

@knadh if you don't want to answer could you reopen this so others can? 

I was especially not sure about the `sudo docker-compose run --rm app ./listmonk --install` command, so I tried to search it and found some [other possible options](https://rancher.com/docs/rancher/v1.6/en/cattle/upgrading/), including:
```
--upgrade, -u, --recreate | Upgrade if service has changed
--force-upgrade, --force-recreate | Upgrade regardless if service has changed
--confirm-upgrade, -c | Confirm that the upgrade was success and delete old containers
--rollback, -r | Rollback to the previous deployed version
```

I'll update the docs later for others.

**Comment by knadh** [comment]
I thought I already did on the other thread. To restore a previous version, you have to restore the DB for that particular version. DBs that have been upgraded with a particular version shouldn't be used with older versions. There may be DB changes that a new version brings that are incompatible with previous versions.

**Comment by MaximilianKohler** [comment]
>I thought I already did on the other thread.

See above. You gave the general outline, and I listed the details/commands above but I don't think I got everything correct.

**Comment by MaximilianKohler** [comment]
@knadh I send thousands of daily emails for work and I've had to take the whole week off due to the new bugs I discovered, and waiting to learn what the correct **commands** are for reverting back to an old version. 

I'm not sure what your mindset is when you say things like:

> * Stop listmonk.
> * Restore your pre-upgrade database.
> * Assuming you're using docker-compose, edit it and change `listmonk:latest` to `listmonk:v2.4.0`.
> * Restart

But it's not a solution. The **commands** I guessed at above would be a solution. And you closed the thread so others don't see it and can't weigh in. I spent hours doing web searches and reading, and could not find the solution anywhere. So I still have not been able to revert back to the old version and get back to work. I really need to. 

Hopefully you understand my position better now. I'm trying to improve the docs so that others don't have to go through the same thing.

**Comment by knadh** [comment]
> I've had to take the whole week off due to the new bugs I discovered

I'm sorry that you've had this trouble. However, the bugs you have reported, I have been unable to reproduce and the unsubscription issue isn't a bug. It's some 3rd party extension messing with e-mails.

> I'm not sure what your mindset is when you say things like:

You asked for the steps to restore a previous version of listmonk. I've outlined the steps. I am unfortunately not familiar with Docker stuff and I don't know the steps to follow offhand to interact with Postgres to restore a database. However, it should be possible to search and find solutions for the broad steps I've outlined as they're generic and not specific to listmonk.

> The outline you gave isn't correct anyway. You can't run the "restore database" commands after running sudo docker-compose down. You get:

I am not familiar with Docker steps, but here, if you stop the Postgres server, then it's obviously not posible to restore a database. Restoration of a Postgres DB typically involves invoking `psql` to pipe a `backup.sql` that you'd have taken. I'm not sure how you've taken or manage your backups.

> And you closed the thread so others don't see it and can't weigh in.

There are multiple threads with a lot of edits, so I've lost track, unfortunately. Which thread do you want to re-open.

Also, do understand that listmonk is built using the personal time I dedicate to it. I am not in a position to offer quick support, although I try my best to answer as many queries as possible.

Thanks.
