### ISSUE TITLE
[Feature Requests] Email Open & Link Click Analytics

### ISSUE THREAD

**Issue by kapilhypertrend** [knadh/listmonk#1458]
Description:
We propose adding a feature to List Monk that allows users to track two crucial aspects:

Who opened the email: Identify individual recipients who opened the email.
Link Interactions: Highlight which links within the email were clicked, and by whom.
Plus, for easy follow-ups and analysis, there should be an option to export this data.

Why This Matters:
By understanding who's interacting with emails and what content engages them, users can better tailor their communication, resulting in more successful campaigns.

Example:
Imagine sending a promotional email about a sale. With this feature, not only can you see that 200 out of 500 recipients opened the email, but you'll also know that 150 clicked on the "50% Off" link while only 20 clicked on the "New Arrivals" link. And if you want to send a thank-you note or a reminder, you can easily export a list of those 150 who showed interest in the sale.

@knadh please give it a thought, i would be more than happy to help anyway possible. <3

**Comment by knadh** [comment]
Hi @kapilhypertrend. listmonk already has the ability to track individual views and clicks (Settings -> Privacy -> Individual Subscriber Tracking) which is disabled by default.

Currently, there is no place on the UI that shows all the subscribers who clicked a link (as typically in a large campaign, there could be hundreds of thousands of clicks on a link). You can however query this data (using something like Metabase perhaps) out of `link_clicks` in the database.

**Comment by MaximilianKohler** [comment]
>Hi @kapilhypertrend. listmonk already has the ability to track individual views and clicks (Settings -> Privacy -> Individual Subscriber Tracking) which is disabled by default.

I've had that enabled for a long time but it doesn't seem to be in the UI anywhere? We have to use Metabase to view it?

**Comment by knadh** [comment]
For now, yes. Please see the answer above:

> Currently, there is no place on the UI that shows all the subscribers who clicked a link (as typically in a large campaign, there could be hundreds of thousands of clicks on a link). You can however query this data (using something like Metabase perhaps) out of link_clicks in the database.

**Comment by gaursachin1642001** [comment]
Hey I connect to metabase , but it still give any data

**Comment by CReimer** [comment]
@knadh How can this be 'closed as completed'?
Having to use an external tool can't be considered as problem solved.

**Comment by galinski** [comment]
I'm also looking for this feature, but it looks like this is possible directly from UI.

Go to Subscribers list, click on "Advanced" button to use SQL query, and put query like this:
`EXISTS(SELECT 1 FROM campaign_views WHERE campaign_views.subscriber_id=subscribers.id AND campaign_views.campaign_id=<put_id_of_campaign>)`

the results are only subscribers who shows the campaign email.

**Comment by kapil303196** [comment]
@knadh can we have this shown somewhere in the UI?

**Comment by etranger7** [comment]
As of v5.0.0 I'm seeing 0 views on my campaigns but clicks are still being recorded properly.
So here is a query that might help those who want to filter the subscribers who clicked on a link of a specific campaign.

```
EXISTS (
  SELECT 1
  FROM link_clicks
  WHERE link_clicks.subscriber_id = subscribers.id
    AND link_clicks.campaign_id = <put_id_of_campaign>
)
```
