### ISSUE TITLE
Container Unhealthy 

### ISSUE THREAD

**Issue by Tataukee** [knadh/listmonk#1459]
Can someone please help understand / correct this whole syntaxe ? 
I am trying to install from Portainer like this way ( see below ) and i am keeping getting an error : 
Error dependency failed to start : container Listmonk-DB is unhealthy .
Thanks in advance .

version: "3.9"
services:
  db:
    image: postgres
    container_name: Listmonk-DB
    hostname: listmonk-db
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "listmonk", "-U", "listmonkuser"]
      timeout: 10s
      interval: 5s
      retries: 6
    volumes:
      - /volume1/docker/listmonk/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: listmonk
      POSTGRES_USER: listmonkuser
      POSTGRES_PASSWORD: listmonkpass
    restart: on-failure:5

  listmonk:
    image: listmonk/listmonk:latest
    command: [sh, -c, "yes | ./listmonk --install"] # only first startup ! or the db wipe every time
    container_name: Listmonk
    hostname: listmonk
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9000/
    ports:
      - 9192:9000
    volumes:
      - /volume1/docker/listmonk/uploads:/listmonk/uploads:rw
    environment:
      TZ: some place in earth
      LISTMONK_app__address: 0.0.0.0:9000
      LISTMONK_app__admin_username: user
      LISTMONK_app__admin_password: userpass
      LISTMONK_db__host: listmonk-db
      LISTMONK_db__port: 5432
      LISTMONK_db__user: listmonkuser
      LISTMONK_db__password: listmonkpass
      LISTMONK_db__database: listmonk
      LISTMONK_db__ssl_mode: disable
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy

**Comment by pranav514** [comment]
I have limited knowledge in this project, but out of curiosity I am asking syntax you provided is for a Docker Compose YAML file?. used to define and manage multi-container Docker applications?

**Comment by Tataukee** [comment]
Hi,
Yes . This is intended to deploy in a Synology docker thru Portainer . Hope this can help .

**Comment by pranav514** [comment]
version: "3.9"
services:
  db:
    image: postgres
    container_name: Listmonk-DB
    hostname: listmonk-db
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: "1026:100"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "listmonk", "-U", "listmonkuser"]
      timeout: 10s
      interval: 5s
      retries: 6
    volumes:
      - /volume1/docker/listmonk/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: listmonk
      POSTGRES_USER: listmonkuser
      POSTGRES_PASSWORD: listmonkpass
    restart: on-failure:5

  listmonk:
    image: listmonk/listmonk:latest
    command: ["sh", "-c", "yes | ./listmonk --install"] # only first startup ! or the db wipe every time
    container_name: Listmonk
    hostname: listmonk
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: "1026:100"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9000/"]
      interval: 10s
      timeout: 10s
      retries: 6
    ports:
      - "9192:9000"
    volumes:
      - /volume1/docker/listmonk/uploads:/listmonk/uploads:rw
    environment:
      TZ: "some place in earth"
      LISTMONK_app__address: "0.0.0.0:9000"
      LISTMONK_app__admin_username: "user"
      LISTMONK_app__admin_password: "userpass"
      LISTMONK_db__host: "listmonk-db"
      LISTMONK_db__port: 5432
      LISTMONK_db__user: "listmonkuser"
      LISTMONK_db__password: "listmonkpass"
      LISTMONK_db__database: "listmonk"
      LISTMONK_db__ssl_mode: "disable"
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
may be this syntax may solve your error....
Changes made are:-
The healthcheck test command for the listmonk service was updated to use CMD-SHELL as specified in the official documentation.
Quoted values for the user and TZ environment variables to ensure proper parsing.
Ensured consistent quoting of environment variable values throughout the file.
Updated the indentation for the depends_on section to match the correct syntax.
Make sure to replace "some place in earth" with the appropriate time zone value, and ensure that the image names, database credentials, and paths match your actual setup.

**Comment by Tataukee** [comment]
Thank you so much .
I've tried several times and still didn't go thru .. I'm sure I am missing something ..
Please have a look in the following screenshots I took from my main portainer web editor , how I followed your instructions and got the same error message . 
Am I missing something ? 

![Screen 1](https://github.com/knadh/listmonk/assets/26170999/55b4a4e3-4349-41ca-a841-86c95566212a)
![Screen 2](https://github.com/knadh/listmonk/assets/26170999/38bcd71d-b17a-4d8c-9cf0-e7489aa47d58)
![Screen 3](https://github.com/knadh/listmonk/assets/26170999/3359635c-0038-4413-8a40-7c5bee9793fe)
![Screen 4](https://github.com/knadh/listmonk/assets/26170999/83a98d7a-cf6c-4e61-881e-95e3c18c6545)

**Comment by mr-karan** [comment]
Hi. Please share the logs from the DB container.

**Comment by Tataukee** [comment]
Hi , no logs are visible or generated as the containers are not deployed .

**Comment by mr-karan** [comment]
Unfortunately without logs it's not easy to help. Since you've changed a lot of stuff in your `docker-compose.yml` as well, we'll need logs to debug. 

My initial guess would be to do something around user permissions as you've given custom user_id on host/container to run. 

Can you try running the default/official `docker-compose.yml`? : https://listmonk.app/docs/installation/#manual-docker-install_1

**Comment by Tataukee** [comment]
@mr-karan Thank you for reminding me that ! stick to the rule of the procedure . I've actually followed the manual installation and voilà ! Listmonk is running since tree days now without any issue . I have managed to get it working by keeping the basics . 
Thank you so much @pranav514 @mr-karan and of course @knadh for this awesome tool .
