### ISSUE TITLE
Is there a log file?

### ISSUE THREAD

**Issue by typomedia** [knadh/listmonk#1462]
I hope this message finds you well. I've been using Listmonk and finding it quite useful for my needs. However, I've been trying to locate the `logfile` for Listmonk but haven't had much luck so far.

Could you provide some guidance on whether Listmonk generates logfiles and where I might be able to locate them?

I appreciate your efforts in developing and maintaining Listmonk, and I'm looking forward to your assistance with this matter. 
Thank you in advance for your help!

**Comment by knadh** [comment]
Hi @typomedia. listmonk logs to stdout. If you're running it in the Docker environment, you can view the logs using docker-compose. If you're running the binary, you can pipe the logs to a file, eg: `./listmonk > log.txt`.

Also, Settings -> Logs in admin shows the last 1000 lines of the standard log output.

**Comment by MaximilianKohler** [comment]
For the service file when running as a binary, I tried these but they didn't work:
```
ExecStart=/usr/bin/listmonk --config /etc/listmonk/config.toml --static-dir /etc/listmonk/static > /etc/listmonk/listmonk.log

ExecStart=/usr/bin/listmonk --config /etc/listmonk/config.toml --static-dir /etc/listmonk/static >> /etc/listmonk/listmonk.log 2>&1

ExecStart=/usr/bin/listmonk --config /etc/listmonk/config.toml --static-dir /etc/listmonk/static >>/etc/listmonk/listmonk.log
```

This worked:
`ExecStart=/bin/bash -ce "exec /usr/bin/listmonk --config /etc/listmonk/config.toml --static-dir /etc/listmonk/static >>/etc/listmonk/listmonk.log 2>&1"`

More info:
* https://stackoverflow.com/questions/37585758/how-to-redirect-output-of-systemd-service-to-a-file
* https://unix.stackexchange.com/questions/321709/redirect-systemd-service-logs-to-file
