### ISSUE TITLE
The sender hasn't authenticated this message

### ISSUE THREAD

**Issue by alexellis** [knadh/listmonk#1470]
Hi,

I am trying out listmonk on a recommendation from someone.

It's been set up with AWS SES as a sender, which is sending emails using credentials, the domain is confirmed with TXT records, however whenever someone receives emails, Gmail marks them as spam saying:

> The sender hasn't authenticated this message

Any suggestions?

https://support.google.com/mail/answer/1074268?hl=en-GB#zippy=%2Ci-dont-think-that-the-message-is-a-scam

![Screenshot_2023-08-21_at_15 56 45](https://github.com/knadh/listmonk/assets/6358735/3db34a3e-7054-47a1-a30d-04f01322efc9)

**Comment by MaximilianKohler** [comment]
Click the "down arrow" next to "to me". 
```
mailed-by:	
signed-by:	
security:
```
Click the three dots on the right, then "show original". Check SPF, DKIM, DMARC. You can do a web search for how to enable them with SES. There may be more details in here https://gist.github.com/MaximilianKohler/e5158fcfe6de80a9069926a67afcae11
