### ISSUE TITLE
Lists from which a subscriber cannot unsubscribe

### ISSUE THREAD

**Issue by tosie** [knadh/listmonk#1472]
I am using Listmonk in a context where subscribers are required to receive certain information as part of a mailing. This is not exactly a marketing/... campaign, think about it like sending information to employees.

Currently, Listmonk allows a subscriber to be unsubscribed from a list. In my mind it would be nice to not only have single-opt-in lists, but also lists from which a subscriber cannot "remove" themselves (= a new setting on lists).

Necessary changes would involve:

  - List settings
  - Template rendering (there would not be an unsubscribe URL)
  - Email headers (no `List-Unsubscribe`)
  - Possibly other places ...

What is the general opinion about such a feature?

**Comment by tosie** [comment]
For reference: https://github.com/knadh/listmonk/issues/673

**Comment by tosie** [comment]
I'll probably take a stab at this feature once #1385 is done.

**Comment by knadh** [comment]
Closing this and tracking it in #673 instead. Thanks.
