### ISSUE TITLE
Give Option to Disable Graph Break

### ISSUE THREAD

**Issue by anaclumos** [knadh/listmonk#1475]
![Capture-2023-08-21-113442](https://github.com/knadh/listmonk/assets/31657298/034088a0-17f0-49d1-a322-17076809ce07)

The graphs provided are misleading because of the Graph Breaks. Please give us an option to disable graph breaks.

**Comment by knadh** [comment]
Hi @anaclumos. Do you mean anchor the graph to 0 at the beginning of the axis? That can be done. However, any sort of configurability of the graph isn't possible.

**Comment by anaclumos** [comment]
> Hi @anaclumos. Do you mean anchor the graph to 0 at the beginning of the axis? That can be done. However, any sort of configurability of the graph isn't possible.

Anchoring 0 would suffice for now. How can I do that?

**Comment by knadh** [comment]
This has to be hardcoded in the frontend code. Will have to check the graph lib's documentation, figure it out, and make it available in the next release.
