### ISSUE TITLE
HEIC image files not visible

### ISSUE THREAD

**Issue by werfpsa** [knadh/listmonk#1478]
**Version:**
 - listmonk: [eg: v2.5.1]
 - OS: [docker]

I can now upload HEIC image files, but they are not yet 'visible' on the media screen (only see the word 'HEIC', but no image). And also in campaigns they are not 'visible'.

**Comment by knadh** [comment]
Hi @werfpsa. Checked this. Neither Firefox nor Chrome browsers support HEIC files. I don't think you should be using them in your e-mail campaigns.
