### ISSUE TITLE
Rich text alignment doesn't work in final emails

### ISSUE THREAD

**Issue by RaghavSood** [knadh/listmonk#148]
It seems that the rich text widget used does text alignment using its own classes (for example, `ql-align-center` for center aligned text).

This works fine in the preview and rich textbox, but doesn't actually work when you send the email since the `ql-align-center` css class is not part of the actual template.

If this is not avoidable (as in, we can't get the widget to use inline styling to set the text position), could we have a list of CSS classes that must be included in the template to allow full WYSIWG support?

**Comment by knadh** [comment]
Hm, maybe the Quill editor's behaviour has changed. Styles are meant to be inline. Will investigate.

**Comment by knadh** [comment]
This turned out to be quite complicated with QuillJS, but is fixed in [v0.7.0](https://github.com/knadh/listmonk/releases/tag/v0.7.0-alpha).
