### ISSUE TITLE
Change "variables font"

### ISSUE THREAD

**Issue by theRAGEhero** [knadh/listmonk#1481]
Hello,

I have a question that may seem unusual. Is it possible to change the font so that the entire newsletter has a consistent appearance?

`Dear {{ .Subscriber.LastName }},`

![image](https://github.com/knadh/listmonk/assets/39453005/209e7f42-d3bd-4e82-a097-a15cd2d578df)

As you can see, the _subscriber_ is using a different font. How can I make it look the same?

Thank you.

**Comment by knadh** [comment]
This entirely depends on how you've coded the template in Templates, where you can specify any font. Also, please do check the "Preview" on the campaign to see the final result.

**Comment by theRAGEhero** [comment]
thank you.
