### ISSUE TITLE
Can you drop some svg files in the static directory, and refer to those files url in the template?

### ISSUE THREAD

**Issue by alanomarsia** [knadh/listmonk#1483]
I have some static svg files, and I want to place them in the `static` directory and refer to them from  a template, but my issue is how to refer to them? 

using `/public/static/my-svg.svg` will make user mail agent prefix the base url automatically something like `mail.google.com/public/static/my-svg.svg`

so is there a go template function that will allow me to get the url of the host machine, Or I have to hardcode them?

**Comment by knadh** [comment]
> using /public/static/my-svg.svg will make user mail agent prefix

This shouldn't be done! It has to be the full URL with your domain name.

> so is there a go template function that will allow me to get the url of the host machine, Or I have to hardcode them?

There isn't one now, but thanks for the suggestion. Will add a `RootURL` param in the upcoming release.

**Comment by knadh** [comment]
Sorry, I just realised, `{{RootURL }}` is already available in the public templates.

**Comment by violoncelloCH** [comment]
okay, so I took an attempt of implementing that: #1812
