### ISSUE TITLE
Allow setting default sending method

### ISSUE THREAD

**Issue by symroe** [knadh/listmonk#1486]
First off, thanks for Listmonk :sunglasses: 

I'm having some problems with SES and SMTP connection timeouts that I can't get to the bottom of (more on that in other issues when I can figure out more about what's going on). As I can't figure it out, I decided to use `listmonk-messenger`'s SES integration, using the AWS API (this does work correctly).

Now I have a working set up for sending emails, I want the SES messenger to be the _default_ for all campaigns. In fact, ideally I'd not have any SMTP config at all, as the only way I'm ever going to send emails (until I can fix SMTP) is via the messenger.

There are two things I noticed here:

1. I can't disable SMTP (and the message is "At least one SMTP block should be enabled" when I think this means _must_)
2. When another messenger is enabled, "email" is still the default sending option for all campaigns.

It seems reasonable (and not a scope change for the project) that people might want to _only_ use a particular messenger / API for sending messages via ListMonk. Given that I've been thinking about a few different solutions, from simple to the most complex (I assume)

1. Allow setting a default option in settings. This shouldn't need more than a new setting in `general` that lets the user pick between SMTP server(s), and and enabled messengers. The campaign drop down adds `selected` to the value of this setting.
2. Support installations with no SMTP server at all, as long as there's at least one valid way to send messages (one of SMTP config and messengers)
3. Consider SMTP to be a first class form of messenger and internally use the same API, force at least one messenger to be enabled 

I've not spent loads of time reading the source code, so I don't really understand how complex each of these are, but I suspect option 1 is reasonably easy. I'd be willing to make a PR for this, if you'd accept it?

More broadly, I can see the "messenger backend" approach to be cleaner. Yes, SMTP will be the most common form (and it should be bundled), but it feels cleaner to have all methods of sending things be the same class of thing (even if 3rd parties use HTTP to communicate). 

Edit: I'm on `v2.5.1 (a6a2b69 2023-08-15T15:49:28Z, linux/amd64)`

**Comment by symroe** [comment]
I should say that I've managed to hack this (and it is a hack) with the following custom JS:

```js
function remove_email() {
  var messenger_select = document.getElementsByName("messenger");
  if (messenger_select.length > 0) {
    messenger_select[0].querySelector("option[value=email]").remove();
    messenger_select[0].querySelector("option").selected = true;
  }
}

document.addEventListener("click", () => {

  setTimeout(() => {
    remove_email();
  }, 1000);

});
```

Not proud, but I couldn't find another way to hood into the forms (side note: exposing the Vue events to other scripts in some way would be neat).

**Comment by knadh** [comment]
Hi @symroe. The messenger interfaces were added much later where as smtp is integrated in listmonk's core. Admin notifications also by default go via smtp. Ideally, like you said, smtp should fit into the exact same messenger interface. This requires significant architectural changes, but, nonetheless, I'll keep this in mind.

The hack's an alright way of doing this for now. Instead of setting a default messenger (and creating UIs, DB changes, handlers etc.), it's easier to add a bit of frontend code that remembers the last messenger selection on the campaign UI. Not foolproof, but might be okay for most usecases. Will consider this for the next version.

**Comment by symroe** [comment]
Thanks for the prompt reply!

I think remembering the last selection per campaign is useful, but I'm also considering the case where other members of the team create campaigns. At the moment (without my JS hack), they can create a new campaign, keep the form defaults and it will attempt to send via SMTP when this is known not to work in my install. 

I understand that making SMTP work would be ideal in my case, but you can see a situation where you would always need to tell users to change the default option for new campaigns. I think this justifies a new setting to change the default. 

Points taken about SMTP being baked in...I did find this when I tried deleting the SMTP settings in the database to change the default :see_no_evil: :)
