### ISSUE TITLE
Enhancement: Better Scheduling options

### ISSUE THREAD

**Issue by cb3inco** [knadh/listmonk#149]
Love Listmonk for my needs. 

Today I tested out scheduling and found it a little limited. I'd love to see improvements in the following:

- Ability to 'unschedule'/stop
- Ability to edit schedule
- Ability to know what timezone or what time the server sees and will be sending at to properly schedule
- Ability to see when the schedule is scheduled for and how much time left before it sends.

**Comment by knadh** [comment]
> * Ability to 'unschedule'/stop
> * Ability to edit schedule

These are fixed in the latest version (pending release on the `master branch`).

> * Ability to know what timezone or what time the server sees and will be sending at to properly schedule
> * Ability to see when the schedule is scheduled for and how much time left before it sends.

These are easy to add. Will do shortly.

**Comment by cb3inco** [comment]
Thank you. I did realize some of this is possible, but it's a bit confusing. If I flip the switch to send later to off by re-editing the campaign it actually turns off the schedule, but it says that it's still do scheduled. I was able to reschedule by turning it back on and setting a time.

**Comment by knadh** [comment]
Improved in [v0.7.0](https://github.com/knadh/listmonk/releases/tag/v0.7.0-alpha).
