### ISSUE TITLE
API call to start or send a listmonk campaigns

### ISSUE THREAD

**Issue by rami213671** [knadh/listmonk#1491]
Hi, I'm trying to create an api call to start or send a campaings, I tried the following but it didn't work, can you please share with the correct syntax?:

curl -u "admin:listmonk" -X PUT 'http://localhost:9000/api/campaigns/9/status' --header 'Content-Type: application/json' --data-raw '{"status":"started"}'
{"message":"Error updating Campaign: pq: invalid input value for enum campaign_status: \"started\""}

**Comment by knadh** [comment]
Hi. The status is `running`, not `started`. Please refer to the docs.

**Comment by rami213671** [comment]
Thanks @knadh! it worked.
