### ISSUE TITLE
"from address" is not used when sending

### ISSUE THREAD

**Issue by pietrodicaprio** [knadh/listmonk#1493]
**Version:**
 - listmonk: v2.5.1
 - OS: official Docker image on Ubuntu host

**Description of the bug and steps to reproduce:**
I set the SMTP auth on a Microsoft 365 account and the emails are sent with no problem but the "from address" is not really used.\
The account I set is a service account (`service@domain.tld`) with multiple aliases binded in order to allow it to send with a different address than what's used to login, for example `noreply@project.one` and `noreply@project.two`. In a test campaign I set the _from address_ for the project but the emails are sent with the address that is used for the login.\
The same issue happens in the test email when configuring the SMTP: it's not using the default _from address_ setting.

**Screenshots:**
![image](https://github.com/knadh/listmonk/assets/37634431/5cdb9159-8f91-4785-9f0c-e3f73a3c3093)

![image](https://github.com/knadh/listmonk/assets/37634431/5edd8a4e-9784-4d45-9080-60e94b98a26c)

**Comment by knadh** [comment]
Hi @pietrodicaprio. It's possible that Office 365 is ignoring the `from` header and using the auth e-mail. If `from` didn't work, it would've been reported in large scale (and shown up in our own production setups, of course). Could you investigate this?

**Comment by MaximilianKohler** [comment]
@pietrodicaprio it may be a setting unique to Microsoft 365 SMTP because Amazon SES works fine. You can look up and link here the documentation Microsoft provides for setting up their SMTP. Or just a general guide someone else wrote.

**Comment by pietrodicaprio** [comment]
> @pietrodicaprio it may be a setting unique to Microsoft 365 SMTP because Amazon SES works fine. You can look up and link here the documentation Microsoft provides for setting up their SMTP. Or just a general guide someone else wrote.

https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353

here they say it's possible: https://learn.microsoft.com/en-us/exchange/architecture/edge-transport-servers/address-rewriting?view=exchserver-2019 \
but the documentation is for Exchange Server 2019 and when you try to select `Exchange Online > Worldwide` from the top left menu you are sent back to Exchange Server 2019 because the same page does not exists for M365/O365/Exchange Online.

It looks like they don't support the feature in Exchange Online?\
Meanwhile I'm going to try to override the `from` using a _rule_ in the Exchange control panel.
