### ISSUE TITLE
Disabling SMTPUTF8

### ISSUE THREAD

**Issue by vikky1992** [knadh/listmonk#1495]
Hi, 
Is there a way to disable the SMTPUTF8 support? Currently the tool enforces it and lot of the Yahoo addresses are getting bounced back. 
Below is the response that we have recieved on the SMTP for all the yahoo addresses from the sending list. 

`failed,5.6.7 (destination does not support SMTPUTF8 required for message delivery), destination does not support SMTPUTF8 required for message delivery,mx-apac.mail.gm0.yahoodns.net`

**Comment by vikky1992** [comment]
We have our own SMTP server setup using PowerMTA tool. 

We have enabled both SMTPUTF8 and processing 8BITMIME. 

![image](https://github.com/knadh/listmonk/assets/16080218/a7015e7e-e9db-4ed2-ab3d-e54ecfa6683d)
![image](https://github.com/knadh/listmonk/assets/16080218/045e8c29-3f2d-45c0-a6ed-27a851dd04b5)

**Comment by knadh** [comment]
Did some digging and this seems to do with configuration on SMTP servers running on Windows. Linux SMTP servers deliver e-mails to Yahoo just fine. Closing this as it has to be handled in the server config. Thank you.

**Comment by turboMaCk** [comment]
We do experience similar issues on Linux with protonmail and hey. We use [postfix](https://www.postfix.org) server. The error is same as what is described above - for instance:

```
SMTPUTF8 is required, but was not offered by host mail.protonmail.ch[176.119.200.128]
```

We're sending emails from our application code using the same mailserver just fine. Only mails from listmonk seem to be failing.

**Comment by Power-MTA** [comment]
🙌🙌🙌 latest version powermta / pmta available with lifetime license key.
+ another tools available
Skype: salimrezabd04
Telegram: salimrezabd
Telegram: salimrezabd1

**Comment by GTAdoum** [comment]
Same thing here, PostFix on Linux works fine with SMTPUTF8, except with listmonk...

**Comment by turboMaCk** [comment]
If I'm correct we managed to isolate the problem. If my recollection correct it was caused by attachement whos name was not ASCII but used, in our case, 2byte UTF characters from czech alphabeth like ř ů í etc. Have a look if your situation is not similar.
