### ISSUE TITLE
Listmonk would keep sleeping indefinitely

### ISSUE THREAD

**Issue by rafalsk** [knadh/listmonk#1496]
**Version:**
v2.5.1 running through Docker (official package)

Logs:
`2023/08/30 07:01:56messages exceeded (40) for the window (1h0m0s since 30 Aug 23 07:00 +0000). Sleeping for 58m23s.
2023/08/30 08:00:20error sending message in campaign Introduction to Investors (pre-listing): subscriber 4262: write tcp 172.18.0.3:35044->150.254.5.18:587: write: broken pipe
2023/08/30 08:01:09messages exceeded (40) for the window (1h0m0s since 30 Aug 23 08:00 +0000). Sleeping for 59m10s.
2023/08/30 09:00:20error sending message in campaign Introduction to Investors (pre-listing): subscriber 4304: write tcp 172.18.0.3:57764->150.254.5.18:587: write: broken pipe
2023/08/30 09:01:08messages exceeded (40) for the window (1h0m0s since 30 Aug 23 09:00 +0000). Sleeping for 59m11s.`

**Comment by rafalsk** [comment]
I need to reboot docker container for the campaign to resume...

**Comment by knadh** [comment]
Looks like you've set limits in Settings -> Performance. Have you tried tweaking those?

**Comment by rafalsk** [comment]
I've set limits but how does it matter? There are 40 e-mail to be dispatched within an hour.

The app is supposed to sleep for an hour after having sent 40 e-mails it does so ONCE.. it would resume after an hour and after that it dies.. it would keep reporting to be 'running..' but it would continue sleeping indefinitely without anything in logs.

**Comment by rafalsk** [comment]
the idle-time out in smtp is set to 15s

I don't get it.. what does the idle-timeout has to do with the other settings. I would suppose the connection to the smtp server be re-initialized on demand as needed??

**Comment by rafalsk** [comment]
after settingthe SMTP timeout to 2 hours (120m) the result does not get any better:"2023/08/30 17:21:55start processing campaign (Introduction to Investors (pre-listing))
2023/08/30 17:22:42messages exceeded (40) for the window (1h0m0s since 30 Aug 23 17:21 +0000). Sleeping for 59m8s.
2023/08/30 18:21:51error sending message in campaign Introduction to Investors (pre-listing): subscriber 4872: write tcp 172.18.0.3:39258->150.254.5.18:587: write: broken pipe
2023/08/30 18:22:39messages exceeded (40) for the window (1h0m0s since 30 Aug 23 18:21 +0000). Sleeping for 59m11s.
2023/08/30 19:21:51error sending message in campaign Introduction to Investors (pre-listing): subscriber 4913: write tcp 172.18.0.3:42956->150.254.5.16:587: write: broken pipe
2023/08/30 19:22:39messages exceeded (40) for the window (1h0m0s since 30 Aug 23 19:21 +0000). Sleeping for 59m11s."

**Comment by rafalsk** [comment]
finally it's killed for good:
2023/08/31 05:52:42error counted exceeded 10. pausing campaign Introduction to Investors (pre-listing)
2023/08/31 05:52:42set campaign (Introduction to Investors (pre-listing)) to paused

**Comment by knadh** [comment]
Could you please code-format the error logs you've pasted? It's hard to read. I'm unable to understand what exactly is going wrong.

> does anyone actually manage to use the current build? some time ago it used to work without issues (almost).

We use it at work to send out ~12 million e-mails a week just fine.

**Comment by rafalsk** [comment]
`
2023/08/31 13:12:53v2.5.1 (a6a2b69 2023-08-15T15:49:28Z, linux/amd64)
2023/08/31 13:12:53reading config: config.toml
2023/08/31 13:12:53connecting to db: listmonk_db:5432/listmonk
2023/08/31 13:12:53media upload provider: filesystem
2023/08/31 13:12:53loaded email (SMTP) messenger: rafal.skowronski@put.poznan.pl@poczta.put.poznan.pl
2023/08/31 13:12:58start processing campaign (Introduction to Investors (pre-listing))
2023/08/31 13:13:46messages exceeded (40) for the window (1h0m0s since 31 Aug 23 13:12 +0000). Sleeping for 59m7s.
2023/08/31 14:12:54error sending message in campaign Introduction to Investors (pre-listing): subscriber 5838: write tcp 172.18.0.3:59468->150.254.5.16:587: write: broken pipe
2023/08/31 14:13:43messages exceeded (40) for the window (1h0m0s since 31 Aug 23 14:12 +0000). Sleeping for 59m10s.
2023/08/31 15:12:54error sending message in campaign Introduction to Investors (pre-listing): subscriber 5879: write tcp 172.18.0.3:35334->150.254.5.18:587: write: broken pipe
2023/08/31 15:13:43messages exceeded (40) for the window (1h0m0s since 31 Aug 23 15:12 +0000). Sleeping for 59m10s.
2023/08/31 16:12:54error sending message in campaign Introduction to Investors (pre-listing): subscriber 5920: write tcp 172.18.0.3:54114->150.254.5.18:587: write: broken pipe
2023/08/31 16:13:44messages exceeded (40) for the window (1h0m0s since 31 Aug 23 16:12 +0000). Sleeping for 59m9s.
2023/08/31 17:12:54error sending message in campaign Introduction to Investors (pre-listing): subscriber 5961: write tcp 172.18.0.3:37410->150.254.5.18:587: write: broken pipe
2023/08/31 17:13:52messages exceeded (40) for the window (1h0m0s since 31 Aug 23 17:12 +0000). Sleeping for 59m1s.
2023/08/31 18:12:54error sending message in campaign Introduction to Investors (pre-listing): subscriber 6003: write tcp 172.18.0.3:47586->150.254.5.18:587: write: broken pipe
2023/08/31 18:13:43messages exceeded (40) for the window (1h0m0s since 31 Aug 23 18:12 +0000). Sleeping for 59m11s.`

**Comment by rafalsk** [comment]
also there are a couple of things to investigate
1) the software seem to be having trouble with the keep-alive mechanism/ time-out mechanics of SMTP connections.

The software SHOULD re-initialize SMTP connections when and as needed. The software should account for all the settings and if limits on one tab are incompatible with limits in another tab, then the software SHOULD auto-adjust the other settings are AT LEAST warn the user.

The situation in which the software dies, no matter what the settings are, while throwing 'broken pipe' errors with user wondering whether the emails were actually sent or not IS NOT acceptable.

Do notice that for the above logs I had to increase BOTH of the SMTP limits to 120m while the main rolling time window delay is set to one hour in the other. Had I set only the first time out to 2 hours it wouldn't even attempt to send the e-mails. The other timeout which I recall was about for how long the connection is to remain open while no now e-mails are enqueued was needed to be increased as well.

There is little to no point of letting the user adjust these timeouts, the only reason would be to save on TCP connections/ RAM utilization of both the client and server but that's a small price to pay had the connections be open constantly, with your software managing these on demand and ensuring these are ALWAYS open. Now, with manual adjustments, well you need to make sure the connections are up and running when needed. There's no way around it.

**Comment by rafalsk** [comment]
the main question is - if there is an error on the grounds of a broken pipe and if email are not dispatched then why the software keeps marking those recipients as already processed, is that the case?
