### ISSUE TITLE
command out of sequence

### ISSUE THREAD

**Issue by vikky1992** [knadh/listmonk#1497]
**Version:**
 - listmonk: v2.5.1
 - OS: linux/amd64 Ubuntu LTS

**Description of the bug and steps to reproduce:**
Message delivery getting failed with the below error

2023/08/30 14:28:22 error sending message in campaign testcampaign: subscriber 1588229: 503 5.5.1 command out of sequence in "MAIL FROM:<example@oursending_domain.in> BODY=8BITMIME SMTPUTF8"

Let me know if any further details are required.

**Comment by knadh** [comment]
Hi @vikky1992. What SMTP server are you using?

**Comment by vikky1992** [comment]
Hi @knadh 

Thanks for your response. 

We have our own PowerMTA setup for relaying the emails. 

I have some more deatils from the further investigation that I did on the issue which could help you in understanding the problem statement. 

On the PowerMTA we are using the `suppression-lists` directive to suppress emails. Hence our SMTP gives us a response as below when we attempt to send the emails to these ids. 

`2023-08-31 18:29:52 (in 2283)<<< 550 5.7.1 recipient is in suppression list "suppressBadDomains": <abc@example.com> in "RCPT TO:<abc@example.com>"`
When this occures all the further messages on the campaign will fail.  Luckily we have a throushold which can be set on the tool which will pause the campaign which is saving our day. 

FYR: 
![image](https://github.com/knadh/listmonk/assets/16080218/699a8d6e-e70e-4dbd-9308-e04d866d9cb6)

**Comment by knadh** [comment]
Ah, that's very helpful. I'll investigate how the smtp library is treating this particular error. In the meanwhile, is it possible for you to configure PowerMTA to silently discard suppressed e-mails instead of throwing an error?

**Comment by vikky1992** [comment]
ya. We have done that for now. 
two cents: I am not sure if this is a standard error or a custom error,  But this error message is thrown from one of the biggest MTA provider (PowerMTA), handling this error on the platform make sense.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/a6d55d63b16a0e9819eb452b67d0288d2f23c671 should address this.
