### ISSUE TITLE
error sending message in campaign Thanks 2023-08-28 2k: subscriber 472311: EOF

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1498]
What is this?

**Comment by MaximilianKohler** [comment]
Did it only happen to one subscriber? So it failed to send to one subscriber and then I assume it retried and sent successfully? Is there any place to verify that? This is the first time I've noticed this, is there more I could/should be looking at to diagnose it?

**Comment by knadh** [comment]
It would've retried and resent. If that also failed, that would also show up in the log.
