### ISSUE TITLE
Extending functionality / plugin system

### ISSUE THREAD

**Issue by ally9335** [knadh/listmonk#1500]
Does the service support extending its functionality without modifiying the existing code? Namely, via a plugin system, or via something similar. 

If not, how would I still properly extend it **for myself, locally** and properly such that it wouldn't  conflict with the updated code from here?

**Comment by knadh** [comment]
Hi @ally9335. Compiled Go programs don't have a straight forward way of supporting plugins. So listmonk doesn't have a plugin system.

But if you're referring to extending functionality beyond sending e-mails, the Messenger HTTP webhook interface allows you to transmit messages to any external endpoint (SMS, Whatsapp etc.)

See: https://listmonk.app/docs/messengers/
