### ISSUE TITLE
[SSL] Need help to setup autorenew of letsencrypt certificate

### ISSUE THREAD

**Issue by Techievena** [knadh/listmonk#1501]
I have followed this doc to setup listmonk - https://yasoob.me/posts/setting-up-listmonk-opensource-newsletter-mailing/. 

**First of all thanks a lot!** 

Is there any accompanying documentation to setup auto-renew of ssl certs and keep the setup running without the requirement of any developer intervention in future?

**Comment by knadh** [comment]
You can use a reverse proxy like Caddy that supports LetsEncrypt certificates and put listmonk behind it.

**Comment by MaximilianKohler** [comment]
I'm not familiar with Caddy, but I found this tutorial that looks like it would work similarly to the yasoob link you shared https://www.youtube.com/watch?v=qj45uHP7Jmo

If you want to stick with the yasoob instructions, he's simply missing some commands and a line in the docker-compose.yml. I added them to my guide in the listmonk docs:

* https://listmonk.app/docs/installation/#tutorials
* https://gist.github.com/MaximilianKohler/e5158fcfe6de80a9069926a67afcae11#ssl

**Comment by Techievena** [comment]
Thanks a lot @MaximilianKohler!

**Comment by harshavmb** [comment]
If you are selfhosting & happen to run `nginx`, you could use `certbot` supported officially by `EFF` which manages `letsencrypt`. 
You could refer documentation [here](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04). 

The above doc covers renewal too. I've been using for sometime, not even once I looked at certificate renewal, it was always renewed & nginx configuration was reloaded with new SSL certificate.
