### ISSUE TITLE
The functionality of a newsletter?

### ISSUE THREAD

**Issue by ally9335** [knadh/listmonk#1502]
I've run ListMont locally but I haven't used it with the real users yet. 

Does it support the functionality of a newsletter? Namely:

  * ever changing list of the subscribers
  * sending a newsletter with a certain interval, let's say, once in a week, 2 weeks or a month - any option
  * or at least on the certain dates which I'd choose manually
  * and then actually sending out an email to the list, automaticly
  * preparing and scheduling a new email-newsletter for a certain date, for the future

**Comment by knadh** [comment]
Ever changing, yes, of course.

You can also schedule newsletters to be sent out at a particular time.

**Comment by ally9335** [comment]
@knadh all in all,  ListMonk **can** be used for sending a newsletter, correct?

Or some of the points I've listed won't be met?

**Comment by ally9335** [comment]
@knadh piu piu
