### ISSUE TITLE
Customising HTML of public pages

### ISSUE THREAD

**Issue by arielelkin** [knadh/listmonk#1503]
I'd like to customise the public pages (e.g. the public subscription form and the subscription confirmation form)

![image](https://github.com/knadh/listmonk/assets/1756909/b1c58175-2ead-48fb-80a2-a9080c84ed19)

Here I'd like to edit the text and the layout. 

I realise you can apply custom CSS to them (via Settings --> Appearance --> Public), but I'm interested in editing the HTML as well. Is that possible? 

Thanks 🙏

**Comment by knadh** [comment]
Hi @arielelkin. You can load custom static templates into listmonk -- https://listmonk.app/docs/templating/#system-templates
