### ISSUE TITLE
Editor for custom static templates

### ISSUE THREAD

**Issue by arielelkin** [knadh/listmonk#1508]
**Is your feature request related to a problem? Please describe.**
Currently, custom static templates can only used in listmonk if we make a copy of the `static` directory, modify the contents, and then pass a path to it.

This is a cumbersome process, and is not consistent with how other HTML content is created in listmonk (e.g campaigns can be created using an HTML/markdown editor). 

**Describe the solution you'd like**
An HTML editor to create and edit custom static templates, like for campaigns.

**Comment by knadh** [comment]
Please see this discussion: https://github.com/knadh/listmonk/issues/409#issuecomment-876156035

TLDR; A static HTML template editor for system files is very difficult technically to implement and the trade-off isn't worth it because so few installations want to heavily customize static templates (which is typically a one time affair and can be done manually anyway).

**Comment by knadh** [comment]
Because static template change rarely, and rarely do installations change it at all, I don't think it's worthwild building an uploader when it is easy enough to load it directly from disk.

**Comment by LukasCZ** [comment]
Just chiming in on this. I am a big fan of listmonk, thank you for all your work on it @knadh . Currently the confirmation email looks kind of bland, especially when added to a private list. It would be amazing if it was easier to change the default confirmation email in the admin panel. As it is now, when using Docker and Docker Compose, it involves making changes in so many places.

**Comment by Freundschaft** [comment]
it would also be good to be able to edit the opt in confirmation email because apparently the default one now triggers a spam detection pattern at google
