### ISSUE TITLE
Query, ANY keyword doesn't work

### ISSUE THREAD

**Issue by FournyP** [knadh/listmonk#1509]
**Version:**
 - listmonk: 2.4.0
 - OS: Windows 11 (WSL 2)

**Description of the bug and steps to reproduce:**
I try to get some lists using the API thanks to the `query` parameter.
My query is very simple : `'alerts' = ANY(lists.tags)` in order to find lists that contains the tag `alerts`

Firstly, the request didn't work and I found this issue : #1471.
So I've added `\` before parentheses and it worked, I got a 200 status. 
But the result is not what I expected, it's not the same result as the database (see screenshots)

**Screenshots:**
![image](https://github.com/knadh/listmonk/assets/64586968/1ad539f2-5f36-4797-a6bc-ed812a4dae7b)
![image](https://github.com/knadh/listmonk/assets/64586968/bf799cba-60a1-4ebe-9b2b-734fe0ab3d68)

As you can see, the result is empty but in my database, I got one row with the `alerts` tag

Here the request that I use : `http://localhost:9000/api/lists?query=%27alerts%27%3DANY%5C%28lists.tags%5C%29`

If you want to reproduce, here my listmonk container from my docker-compose :
```
listmonk:
    image: listmonk/listmonk:v2.4.0
    container_name: ezexchange.api.listmonk
    ports:
      - "9000:9000"
    networks:
      - listmonk-tier
      - database-tier
    environment:
      - TZ=Etc/UTC
    command: # Comment this config if you don't want to initialize the database
      [
        sh,
        -c,
        "yes | ./listmonk --install --config /listmonk/config.toml && ./listmonk --config /listmonk/config.toml",
      ]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./listmonk.toml:/listmonk/config.toml
```

And I've just add the `alerts` tag manually in the database

Have a good day ;)

**Comment by FournyP** [comment]
I just try using listmonk 2.5.1 and it also don't work.

I try also this expression : `lists.tags @> '{alerts}'` using this request `http://localhost:9000/api/lists?query=lists.tags%20%3D%20%27%7Balerts%7D%27` but I got a error message :
![image](https://github.com/knadh/listmonk/assets/64586968/03f04bc6-5109-4060-8da7-69b2920c34c9)

I have the felling that the query don't take in account `{` and `}` according to the response

**Comment by knadh** [comment]
Hi @FournyP. Apologies for the delay in responding.

The `query` param in lists doesn't in fact support SQL expressions. It's a full text name search. The right way to filter by tags would be to add support for `?tag=x&tag=y...`

**Comment by FournyP** [comment]
Hi @knadh 

Why we must use syntax like this `?tag=x&tag=y...` ? Because to filter by name, we don't use `?name=x` but `?query=x`
And for subscribers, we can use `query` for override the entire WHERE clause. 

In my opinion, it doesn't make sense.

Is this a paradigm shift that you are gradually updating or is it an architectural inconsistency that will not be corrected?

Have a good day

**Comment by knadh** [comment]
`query` or `search` or `q` (or whatever generic parameter) is typically used for unstructured text/full text search on unstructured fields like name/description etc,

`tags` is not an unstructured field. `tags` are enums, not unstructured strings. A clean API should handle those semantics well. Eg: `?query=somename&tag=big&type=optin` etc.

**Comment by FournyP** [comment]
I understand your point but it's not the case for the parameter `query` for the GET subscribers endpoint : https://listmonk.app/docs/apis/subscribers/#get-apisubscribers_2

And that's why I lost some hours on the `query` parameter on the GET lists endpoint. I was expecting the same behaviour as GET subscribers endpoint until reading the documention deeply.

**Comment by FournyP** [comment]
Hi @knadh 

Any news about my previous comment ?

**Comment by knadh** [comment]
Hi @FournyP. Apologies, I haven't had time to think about this and evaluate it properly against what listmonk currently offers. I've added this to my to-do and will evaluate it at some point.
