### ISSUE TITLE
Sending bulk emails through SMTP relays with low single connection transaction limits

### ISSUE THREAD

**Issue by arielelkin** [knadh/listmonk#1518]
[My SMTP relay (Mailersend) has a fixed, single connection transaction limit set at 5](https://developers.mailersend.com/smtp-relay.html#limitations), so it can send up to 5 emails per SMTP connection. 

If I try to send more emails, I get errors like the following: 
```
2023/09/09 07:28:56 campaign (campaign-name) finished
2023/09/09 07:28:56 error sending message in campaign campaign-name: subscriber 31: 421 Service not available, closing transmission channel.
2023/09/09 07:28:56 error sending message in campaign campaign-name: subscriber 29: EOF

```

And many emails don't get sent (even though they're marked as sent by listmonk). 

Is there a way to address this SMTP limitation?

**Comment by MaximilianKohler** [comment]
It tells you in the link you shared:

>To send bulk emails use our [Bulk Email API](https://developers.mailersend.com/api/v1/email.html#send-bulk-emails)

In listmonk you'd have to limit it to 5 via the settings -> "Concurrency & message rate".

**Comment by MaximilianKohler** [comment]
I think so. Not too sure. Try and let us know.

**Comment by arielelkin** [comment]
This failed unfortunately, still got the same error.

**Comment by MaximilianKohler** [comment]
There's another setting on the SMTP tab. You can try lowering that too.
