### ISSUE TITLE
Error while upgrading to version 2.5.1

### ISSUE THREAD

**Issue by AshnaSabu123** [knadh/listmonk#1519]
**Version:**
 - listmonk:v2.5.1

**Description of the bug and steps to reproduce:**
While trying to upgrade the listmonk app version from 2.4.0 to 2.5.1 the below error is getting. Please have a check on it.

2023/09/05 11:56:17 upgrade.go:70: running migration v2.5.0
2023/09/05 11:56:17 upgrade.go:72: error running migration v2.5.0: pq: UPDATE requires a WHERE clause

Awaiting for your response

**Comment by knadh** [comment]
Hi Ashna. What version of Postgres are you running?
