### ISSUE TITLE
docker-compose error connecting to DB

### ISSUE THREAD

**Issue by francoisromain** [knadh/listmonk#152]
Hello, I try to start the project with docker-compose with the example `docker-compose` file. 

then: `docker-compose up app db`

it shows this error: 

```
app_1       | 2020/07/08 15:44:04 init.go:94: error connecting to DB: dial tcp: lookup demo-db on 127.0.0.11:53: no such host
```
with `docker-compose run --rm app ./listmonk --install`, 

it makes this error: 

```
2020/07/08 15:51:58 init.go:94: error connecting to DB: dial tcp: lookup demo-db on 127.0.0.11:53: no such host
```

what am I doing wrong here?

**Comment by mr-karan** [comment]
You are expected to tweak the `config.toml` to give the correct hostname for DB `demo-db`. If you want to spin up to just try it out, you can use `docker-compose up demo-app demo-db`.

**Comment by francoisromain** [comment]
I don't understand why it wants to connect to `demo-db` when I am trying to start the actual app?

**Comment by mr-karan** [comment]
It's coming from [config.toml](https://github.com/knadh/listmonk/blob/master/config.toml.sample#L76).

**Comment by francoisromain** [comment]
ok. So how can I set `config.toml` when I start the app from docker compose?

**Comment by mr-karan** [comment]
You mount it via a volume.

```
    volumes:
       - config.toml:/listmonk/config.toml
```

https://docs.docker.com/compose/compose-file/

**Comment by francoisromain** [comment]
Ok thank you. 
So I copied the default `config.toml` file in my directory. 
I changed to 
```
host = "db"
port = 9432
```
then added the volume to `docker-compose` like so: 
```
  app:
    <<: *app-defaults
    volumes:
      - ./config.toml:/listmonk/config.toml
```

But it still makes the same error: 
```
docker-compose run --rm app ./listmonk --install
Starting listmonk_db_1 ... done
2020/07/08 16:13:04 main.go:90: reading config: config.toml
2020/07/08 16:13:04 init.go:94: error connecting to DB: dial tcp: lookup db on 127.0.0.11:53: no such host
```

Is there something else I should do?

**Comment by mr-karan** [comment]
Yeah, you are not running the DB. `docker-compose run db`

**Comment by francoisromain** [comment]
ok thank you for your quick help.

I finally have it working at `localhost:9000`. 

May I ask why the `config.toml` / docker volume trick is not in the docs?

**Comment by mr-karan** [comment]
It's not a trick. It's a standard practice to tweak the config, since the file explicitly says it's a sample config file. 
Apart from that, the README also hints at tweaking config using env vars:

> together using Docker (also see configuring with environment variables).

With that being said, I'll send a PR to add relevant doc to make it more obvious :)

**Comment by francoisromain** [comment]
do you mean that env variables override the config.toml setup?

**Comment by francoisromain** [comment]
one more question: is there a docker-compose example with a nginx reverse proxy with basic auth?

**Comment by mr-karan** [comment]
You can find an example NGINX config [here](https://github.com/knadh/listmonk/wiki/Production-Nginx-config). To add NGINX, you can simply add another container under `services` of `docker-compose` and mount the NGINX config file.

I feel providing this here would be out of scope for this project.
