### ISSUE TITLE
Allow for CORS Origin fixation or bypass

### ISSUE THREAD

**Issue by duraki** [knadh/listmonk#1521]
It would be good to have some kind of CORS settings from within app, for example spoofing/bypassing based on user-provided CORS value. A lot of times you will see no support for header settings from reverse proxy, therefore this would come handy for all users.

I remember Ackee Analytics [implemented](https://docs.ackee.electerious.com/#/docs/CORS%20headers#platforms-as-a-service-configuration) optional `.env` key which allows user to configure accepted origins.

**Comment by knadh** [comment]
Please see this issue that was just closed. https://github.com/knadh/listmonk/issues/1523

I think it's best for this to be in the reverse proxy and not in listmonk's core for now.

**Comment by duraki** [comment]
> A lot of times you will see no support for header settings from reverse proxy

what .. have you read what I've even wrote 🥲

**Comment by candidexmedia** [comment]
Good news: https://github.com/knadh/listmonk/pull/2000#issuecomment-3446420585

**Comment by duraki** [comment]
@candidexmedia thanks for the headups! Was fucking time fosho.

**Comment by knadh** [comment]
CORS 'allowed origins' can now be configured in Settings -> Security in [v6.0.0](https://github.com/knadh/listmonk/releases/tag/v6.0.0).
