### ISSUE TITLE
Campaigns sent to Gmail addresses not recording views

### ISSUE THREAD

**Issue by BRBDev** [knadh/listmonk#1524]
First off, solid piece of software.  Thanks for the time put into this!

I recently installed listmonk to do some testing and found that campaigns I send to Gmail addresses aren't recording views.   I think Gmail might be blocking the tracking pixel from being downloaded.  View tracking works on other email platforms like Office 365 and Yahoo mail.  

Using Chrome developer tools, I hover over the tracking pixels and it says it could not be downloaded, which makes me think it's Gmail.

Has anyone else run into this issue and if so, is there any way to get this working?  

Thanks in advance for any advice.

**Comment by knadh** [comment]
Yep, it's entirely possible that Gmail is re-writing the pixel URL to point to a proxy.
