### ISSUE TITLE
Campaigns -> Media upload file shows localhost when viewing

### ISSUE THREAD

**Issue by dac11011** [knadh/listmonk#1525]
**Version:**
 - listmonk: 2.4.0
 - OS: Docker

When going to Campaigns -> Media and uploading a file (image) it works fine.  But then clicking on the link to the image below that I uploaded it always uses "localhost" like http://localhost:9000/uploads/file.png

Yes I do have Root URL set in settings to my own domain.  But this still shows "localhost:9000" - How do I make this show my own domain?

Any help would be much appreciated.  Thanks

**Comment by knadh** [comment]
Can you share the configuration values you have in Settings -> Media uploads?

**Comment by dac11011** [comment]
Yes:

Provider: Filesystem
Upload Path: uploads
Upload URI:  /uploads

**Comment by dac11011** [comment]
Running in dev mode was the problem.
