### ISSUE TITLE
Change colour scheme on subscription page

### ISSUE THREAD

**Issue by ukdanmc** [knadh/listmonk#1528]
Hi,

Can anybody help with the CSS required to the changes the background, icon colour of the subscription page?

**Comment by abhinandkakkadi** [comment]
I will be glad to do that @ukdanmc , what is the class/id name of that tag. And to what colour does the change need to be done. Also do the change in colour need to be done when hovering also?

**Comment by ukdanmc** [comment]
thanks @abhinandkakkadi I managed to find another post which had what I needed. Here it is to if it helps anyone in the future.

body {
  background: #FFFFFF;
}

.button {
  background-color: #479E9E;
}

footer.container {
  display: none;
  color: #81d8d0;
}

footer.container a {
  display: none;
  color: #81d8d0;
}

input[type="checkbox"] {
  accent-color: #81d8d0;
}

.header .logo img {
  display: block;
  margin: auto;
}
.button:hover { 
  background-color: #479E9E !important;
}
