### ISSUE TITLE
error sending message ... 503 Sender already specified.

### ISSUE THREAD

**Issue by etranger7** [knadh/listmonk#1530]
**Version:**
 - listmonk: v2.4.0
 - OS: Debian 11 - 5.10.0-23-amd64

**Description of the bug and steps to reproduce:**
We're sending email using SMTP via Amazon SES.
I ran a campaign sending a newsletter to about 3000 subscribers with no issues.

Then I ran another campaign targeting a list of about 50K subscribers.
During that run, the campaign automatically paused multiple times after receiving this following error:

"error sending message in campaign [name of campaign] subscriber fa161fd4-7576-4dbb-9284-bccbdd08ea90: 503 Sender already specified."
but 100s of it.

My error threshold was set to 100 initially. Then I resumed the campaign and I got the same problem. After about 8 - 10 tries, I got through the entire list.
Our SES sending limit is 50K at 14 emails per second.
In between each try, I tweaked the concurrency and message rate. tried 4/3, 3/4, 3/3 to no avail.
My original batch size was 1000, I tried changing to 720 and I tried error threshold 200 again with no noticeable difference in how often the campaign automatically paused.

I ran a duplicates search in my list and nothing came up.

At the end of the campaign, my sent stats were 50,627/50,604 on Listmonk.
I also received 4,760 bounce reports to Listmonk from Amazon.

When I look at Amazon's metrics, I see 44,839 sends and 4,637 bounces.
And finally in my DMARC reports, I see about 23K emails being reported as delivered, all passing SPF and DKIM.

I would really appreciate if someone could help me understand what this error was and why I have such a discrepancy between Lismonk and Amazon's numbers.

**Screenshots:**
![image](https://github.com/knadh/listmonk/assets/5760298/6c748ddc-d459-432a-bc01-6aaecefa2a2e)

**Comment by etranger7** [comment]
We ran another large campaign and paid closer attention the when this is happening.

I noticed that we get a flurry of errors right at the same time there is a sharp increase in the number of bounces.  
We're using Amazon SES to send the mails and I set up Amazon SES bounce webhook as detailed in here:  
[https://listmonk.app/docs/bounces/](https://listmonk.app/docs/bounces/)  
which actually uses Amazon's notification service, SNS. I don't know Listmonk's inner workings and how it interacts with SES enough to make an educated guess but I have a feeling this has to do something with the bounce processing and the sending not being in sync.  
  
Another intersting thing to note is that if I resume the campaign right after it's paused, then it runs into errors again righ away and gets paused. So each time I have to wait a bit to resume the campaign.

Our bounce rate is pretty high, a little less than 2% and I'm not sure if that has anything to do with this issue.

**Comment by knadh** [comment]
[6f93552](https://github.com/knadh/smtppool/commit/6f93552458dfbeeb5b7d1b43899eac1970260e68) addresses this.

**Comment by MaximilianKohler** [comment]
Check https://github.com/knadh/listmonk/issues/1629#issuecomment-1879822419, it seems to have to do with the `list-unsubscribe` headers.

**Comment by astick360** [comment]
@knadh 
Hi, I've run into the same issue, but i can't update my listmonk with the 6f93552 and a6d55d6 commits, unless you release new version to the docker. It's because I'm using listmonk on https://www.pikapods.com/ and they can't update it without new version. I already have v2.5.1.  Could you release version with the changes as new release?
