### ISSUE TITLE
API Auth

### ISSUE THREAD

**Issue by xxJeevesxx** [knadh/listmonk#1531]
Love the package. Thank you for putting everything together :).

**Describe the solution you'd like**
Using the API with Basic Auth is really insecure. Hoping that it can be upgraded to use something more secure. Even as token generated through the admin interface or something. Any thoughts?

**Comment by knadh** [comment]
Hi @xxJeevesxx. Using BasicAuth (with a long token) doesn't make it inherently insecure from an auth standpoint. That admin login and API auth use the same credentials isn't ideal. This is a larger, pending project that's being tracked here: https://github.com/knadh/listmonk/issues/543

**Comment by xxJeevesxx** [comment]
Understood. Thanks for the reply! Can wait to see what comes next. Thanks for all your work on this :)!
