### ISSUE TITLE
Unable to import subscribers from csv file having 4000 records

### ISSUE THREAD

**Issue by ahsan722505** [knadh/listmonk#1532]
The import process works fine if the file has small number of records like 500.

**Comment by ahsan722505** [comment]
Our machine specs:
![image](https://github.com/knadh/listmonk/assets/79001785/b1a9fb67-1d55-44cd-8ece-f698c56d38ad)

**Comment by knadh** [comment]
Please describe the issue you're facing. Is there an error? What exactly happens?
