### ISSUE TITLE
API/Transactional  .Tx.Data. html value question

### ISSUE THREAD

**Issue by xewonder** [knadh/listmonk#1534]
Hello,
I need to send html code via the api and render it as html in the email.

i.e ({{ .Tx.Data.myhtml }}
`curl -u "listmonk:listmonk" "http://localhost:9000/api/tx" -X POST \
     -H 'Content-Type: application/json; charset=utf-8' \
     --data-binary @- << EOF
    {
        "subscriber_email": "xxxxxx@xxxxx.com",
        "template_id": 3,
        "data": {"myhtml": "<p>This is a test email.</p><p>This is a new line.</p><p><strong>This is in BOLD</strong></p><p><strong>The end</strong></p>"},
        "content_type": "html"
    }
EOF`

![image](https://github.com/knadh/listmonk/assets/14354903/1bd7aaeb-70f2-4705-a5c9-717fdca9dd12)

Is it possible?

**Comment by knadh** [comment]
That should be fine. In your tx template, you can try the `safeHtml` filter. 

Eg: `{{ .Tx.Data.myhtml | safeHtml }}`.

**Comment by xewonder** [comment]
Hello,

Thank you. but i get this:

![image](https://github.com/knadh/listmonk/assets/14354903/a9a8bbed-7f01-4b1c-99da-3af7a29f6817)

**Comment by knadh** [comment]
My bad, it's `{{ .Tx.Data.myhtml | Safe }}` not `safeHtml`.

**Comment by xewonder** [comment]
EXCELLENT!

Thank you so much!

**Comment by chsanto2712** [comment]
Hi, I am unable to send an Transactional Email to my Subscriber using ListMonk

For testing, I am using Postman Client Server

![Screenshot 2023-10-20 112800](https://github.com/knadh/listmonk/assets/92885371/e60b526a-da8f-497c-93db-de2bbb4ff310)

This is my ListMonk Transactional Template

![Screenshot 2023-10-20 112915](https://github.com/knadh/listmonk/assets/92885371/e7e40a99-2f3f-4d9d-a310-07e1b193b440)

This is what I am getting error when I send request though I got success Message in the response in Postman

![Screenshot 2023-10-20 113232](https://github.com/knadh/listmonk/assets/92885371/d73f65b7-2d6a-4467-97c0-878236dcede4)
