### ISSUE TITLE
Images are not displayed at the receiver end

### ISSUE THREAD

**Issue by sunnyrai87** [knadh/listmonk#1535]
**Version:**
 - listmonk: [eg: v1.0.0]
 - OS: [e.g. Fedora]

**Description of the bug and steps to reproduce:**
Hi Kailash - There is one issue which I found in email template.
I have added image in template and clicked on preview, it is visible clealy below is the screenshot
![image](https://github.com/knadh/listmonk/assets/145941463/46072a9e-8107-494a-8e9c-660b6e37755e)

**Problem**

Now when I sent the email image is not visible at all. I have tried multiple times
![image](https://github.com/knadh/listmonk/assets/145941463/afb23f24-2e21-4863-a35f-7666f3a0bae8)

Please check and suggest. Kindly note that images are added from the uploads folder which I created in my desktop. Thanks

**Comment by knadh** [comment]
Where are you hosting listmonk? Is the correct domain name configured in `Settings -> General`.

> uploads folder which I created in my desktop. 

If you're running listmonk on your desktop and the URL points to `http://localhost`, then remote images will obviously not work. For that to work, you've to host listmonk on a server somewhere where a domain name points to it, or if you want to continue using your desktop, use the S3 file backend (Settings -> Media) to store files instead of your desktop so that they're resolvable over the internet.

**Comment by sunnyrai87** [comment]
Hi Kamal , 

Please find my comments below 

**_Where are you hosting listmonk? Is the correct domain name configured in Settings -> General_**

Answer - I am hosting on **_http://localhost:9000/_** Please find the below screen it is running on server only 
**_CMD started - listmonk on server_**
1st image
![listmonk_CMD_started on my computer](https://github.com/knadh/listmonk/assets/145941463/f2484c57-345a-4953-a38c-9462bb6616c5)

2nd image - Settings -> local host- localhost:9000
![listmonk hosting screenshot](https://github.com/knadh/listmonk/assets/145941463/e7bfd8cb-1d93-466f-9619-ed22017a55a0)

3rd image - http://localhost:9000/admin/settings - configured 
![name configured in Settingsgeneral](https://github.com/knadh/listmonk/assets/145941463/8b16c7a0-5b58-4b35-8aeb-0c8cefd85725)

**_If you're running listmonk on your desktop and the URL points to http://localhost, then remote images will obviously not work. For that to work, you've to host listmonk on a server somewhere where a domain name points to it, or if you want to continue using your desktop, use the S3 file backend (Settings -> Media) to store files instead of your desktop so that they're resolvable over the internet._**

I am running listmonk on server only - Images is already uploaded on media below screenshot 
![media images_uploaded](https://github.com/knadh/listmonk/assets/145941463/87d64931-a8f0-4550-a3ba-6b6dde279f7b)

As per this all steps followed correctly and in preview also it showing otherwise why the image is visible on preview.
Please suggest

**Comment by knadh** [comment]
The preview is showing fine because it refers to `localhost:9000` which is the system you're viewing it from. When the e-mail goes out, it of course refers to `localhost` which is invalid. Your server should be connected to an actual domain name, eg: `yourmailinglist.com` for this to work.

**Comment by sunnyrai87** [comment]
Hi Kamal

Thanks for your reply , 

Please check the below image which clearly shown that my hosting and server is correct as words are showing here but images are not getting displayed. 

![image](https://github.com/knadh/listmonk/assets/145941463/db860dc3-3926-4860-ade7-426d047f88fe)

**Comment by MaximilianKohler** [comment]
@sunnyrai87 There are guides/tutorials here https://listmonk.app/docs/installation/#tutorials

**Comment by sunnyrai87** [comment]
> @sunnyrai87 There are guides/tutorials here https://listmonk.app/docs/installation/#tutorials

@MaximilianKohler @knadh   - I have followed all instructions and guidelines.  and SMTP has been set up for gmail account.
While sending mail only I can see the text . Images are not getting displayed. I have tested many times. 
This is a bug which should be resolved or else can you do testing testing and show me images are getting displayed

**Comment by knadh** [comment]
@sunnyrai87 this is not a bug. Please see this comment https://github.com/knadh/listmonk/issues/1535#issuecomment-1732996516

"localhost" will only work on your system in your preview. Anywhere else, like in a Gmail inbox, it won't work. 

Connect your listmonk instance to a publicly resolvable domain name.
