### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by gaurishhs** [knadh/listmonk#1536]
**Is your feature request related to a problem? Please describe.**
Listmonk's api design is something really hard to work with. Specifically the data object and the results array. 

**Describe the solution you'd like**
I suggest designing the api as per a specification for example [OpenAPI Specification](https://swagger.io/specification/) or removing the results array / data object and sending data directly would be a better idea

**Comment by knadh** [comment]
Hi Gauri. A `data` field acting as an envelope is a reasonably common convention. I disagree that it makes an API "hard". Either way, there's no merit to changing the API structure and breaking compatibility.

OpenAPI spec doesn't prescribe any specific API response structures. The listmonk API is already available as an OpenAPI/Swagger spec here: https://github.com/knadh/listmonk/blob/master/docs/swagger/collections.yaml
