### ISSUE TITLE
Please investigate - Images not displayed at receiver end

### ISSUE THREAD

**Issue by sunnyrai87** [knadh/listmonk#1537]
@knadh -

Need to bring to your notice that text messages can be sent from listmonk but images are not getting displayed even after changing the root URL
![image](https://github.com/knadh/listmonk/assets/145941463/131cba2e-19d6-49e5-9c56-d536ea3fa920)

**Comment by knadh** [comment]
https://listmonk.www.hitcb.com is an invalid domain, clearly. It hasn't been configured. As I said on the other issue, this is not specific to listmonk. Please figure out how to point a domain to a webserver and have it resolve and refrain from opening further issues here.

**Comment by sunnyrai87** [comment]
> https://listmonk.www.hitcb.com is an invalid domain, clearly. It hasn't been configured. As I said on the other issue, this is not specific to listmonk. Please figure out how to point a domain to a webserver and have it resolve and refrain from opening further issues here.

@knadh    - if it is invalid domain then why you are showing in listmonk example in the below format   https://listmonk.yoursite.com  -  It is means it is an incorrect example which is displayed over in Listmonk 

![image](https://github.com/knadh/listmonk/assets/145941463/69787edd-46e4-41e3-9a2a-1b99a681f606)

**Comment by knadh** [comment]
Sorry, but are you trolling? It's an example! You should configure your FQDN, point it's DNS to your server, for all of this work.

**Comment by MaximilianKohler** [comment]
@sunnyrai87 I shared a link to many tutorials. You should look through them since you're struggling with the very basics.
