### ISSUE TITLE
exporting bounces

### ISSUE THREAD

**Issue by etranger7** [knadh/listmonk#1539]
Is there a way to export bounces?  
I don't see the "export" option on the bounce page.  
I also don't see the option to "select all" from multiple pages.  
Am I missing something?

**Comment by MaximilianKohler** [comment]
Use search first https://github.com/knadh/listmonk/issues?q=is%3Aissue+export+bounces

https://github.com/knadh/listmonk/issues/863

**Comment by etranger7** [comment]
Sorry I missed that.  
Here's the syntax of the curl command I used  
curl -u 'user:pass' -o 'bounces.json' '[https://example.url.com/api/bounces?campaign_id=1&per_page=all&page=1](https://newsletter.utherverse.io/api/bounces?campaign_id=14&per_page=100&page=1)'  
  
The response contained the entirety of the bounce messages, as intended not just the email addresses.  
I imagine querying the database would provide cleaner results but I don't have much experience with that so I used a script to parse out just the email addresses from the bounces.json file.  
If anyone has a more elegant solution. Please feel free to re-open and add it to this thread.
