### ISSUE TITLE
Importing 426 lines from csv does not end working, no error messages

### ISSUE THREAD

**Issue by ghmon** [knadh/listmonk#1540]
**Version:**
 - listmonk: 2.5.1
 - OS: debian 11 buster

Import new subscribers in freshly created list. list attached below. the import does not stop. no error messages. forever message "processing '2023-09-26-EUTB-all-adresses-listmonk-uniq.csv'"

EDIT: Removed the attached file as it contains private information.

**Comment by knadh** [comment]
Unable to reproduce this. Also, please delete the attached file as it contains private information!

![image](https://github.com/knadh/listmonk/assets/547147/3f1af46d-0ad7-41d2-92ba-a0b079f4363a)

**Comment by ghmon** [comment]
Thanks for the investigation. The "private information" was scraped completely from public, not protected web pages. So i decided it is ok to deliver them as test data.

Will look further what is the reason.

**Comment by ghmon** [comment]
Problem solved! Started listmonk via docker as background process ("docker compose up app **&**"). Doing so the interface works as expected, and (as i remember correctly) also other imports worked.

Started it as a foreground app now - "docker compose up app", and import worked.
