### ISSUE TITLE
Using Gmail SMTP, what are the settings to configure keeping in mind gmail account policies?

### ISSUE THREAD

**Issue by harsharavi1629** [knadh/listmonk#1541]
I have installed listmonk and I want to start my marketing campaigns. The email address is less than a month old and I have some questions regarding the same. 
- I will be sending out around 150 emails per day. At what rate should I warm up my email?
- To avoid getting restricted on gmail (w.r.t they're strict anti spam policies), what are the settings I should configure? Considering that my recipients will not be opting in to receive my emails because I'm doing cold email outreach 
- please provide instructions on setting up my root domain and a tracking pixel
- Any general inputs on the best practices to follow would be really helpful

**Comment by knadh** [comment]
https://support.google.com/mail/answer/22839?hl=en#zippy=%2Cyou-have-reached-a-limit-for-sending-mail
