### ISSUE TITLE
Option to disable successful import notifications

### ISSUE THREAD

**Issue by Insprill** [knadh/listmonk#1542]
**Is your feature request related to a problem? Please describe.**
I have a script that automatically imports users from Square into Listmonk daily at midnight using the `api/import/subscribers` endpoint. Because of this, every day I get an email about a successful import, which causes unnecessary noise in my inbox.

**Describe the solution you'd like**
I'd love to have an option to disable notifications for successful imports while keeping them for unsuccessful ones.

**Comment by MaximilianKohler** [comment]
You can set up a gmail filter to delete the email.

**Comment by knadh** [comment]
@Insprill this would be too niche an option to add to the core that serves a very niche usecase.

**Comment by Insprill** [comment]
While this one option is pretty niche, a better way to go about it could be to implement general settings for admin notifications that would allow you to toggle what notifications you'd like to receive and possibly further expanded upon if more notification methods are implemented (in-app, sms, etc).
