### ISSUE TITLE
Create new list, go to "import subscribers", list doesnt show up in drop down

### ISSUE THREAD

**Issue by ghmon** [knadh/listmonk#1543]
Version: listmonk: 2.5.1
OS: debian 11 bullseye

Create new list, go to "import subscribers", list doesnt show up in drop down menu. Refreshing the page => there it is.

No network proxy (system) or browser proxy used. Checked with latest firefox, opera, google chrome on the remote system (Ubuntu 22.04.3 LTS).

**Comment by MaximilianKohler** [comment]
https://github.com/knadh/listmonk/issues/1076#issuecomment-1364720799

>There are benefits to the current behavior (_easy/quick access to the specific lists you want_), so I wouldn't mind it staying as is.

**Comment by etranger7** [comment]
Yep refreshing the page will update the list with the latest addition(s) for me. I hope that solves your problem as well.

**Comment by ghmon** [comment]
> I hope that solves your problem as well.

Yes, it's only a minor issue. I close this!
