### ISSUE TITLE
Filtering subscribers in a list (10) but not in a list (13)

### ISSUE THREAD

**Issue by fehmi** [knadh/listmonk#1544]
I have multiple lists. Some users belong to both. When I browse subscribers in first list (10), I want to filter them by belong to (10) but not (13). I tried below filter, but it still shows all subscribers.

`subscriber_lists.list_id != 13`

I want to select them and move to another list. Because I don't want to send the same email to one person more than once. 

Do you know how to do? Any help is appreciated.

**Comment by knadh** [comment]
You can use this SQL expression to filter subscribers by N number of lists specified by their IDs (comma separated).

```sql
id IN (SELECT subscriber_id FROM subscriber_lists WHERE list_id IN (1, 2, 3))
```
