### ISSUE TITLE
Use cid: reference in template for attached images

### ISSUE THREAD

**Issue by supportdesk-si** [knadh/listmonk#1545]
**ISSUE**
Currently, using `<img src="cid:0123">` is the only way to make sure layout of the email with images is preserved in all mail clients (Outlook [desktop|mobile], Apple, Gmail [app|web], etc.). Using HTML editor, it is possible to enter `<img src="cid:my-image.png">` and in some cases Outlook will show the image. Gmail, however, is still failing to recognize the embedded image.

**SOLUTION**
It would be a great addition to have a cid reference id. For example, after attaching the image, create uuid v4 reference and allow to copy it. Then, when forming the email, attach and reference the image using `<img src="cid:76cdf28e-efbb-4565-b749-1ab4fb89ba09" alt="Download on the Google Play">`. It will break the preview (can be fixed with css) but will ensure the images are viewable in 100% of the mail clients.

Sample layout image attached.
![image](https://github.com/knadh/listmonk/assets/51302932/2e667093-8848-4d76-9a60-ab3003ba286f)

**Comment by supportdesk-si** [comment]
After spending a little more time on the process review, here is what should be happening. When image inserted into the preview, its code may look like this.
`
<img
    src="https://aware.scheduleinterpreter.com/uploads/google-app-store-light.png"
    cid="76cdf28e-efbb-4565-b749-1ab4fb89ba09"
    alt="" width="210" height="55" 
/>
`

Then, during the mail out process, the src attribute is replaces with "cid:76cdf28e-efbb-4565-b749-1ab4fb89ba09" and then when image is attached its ID is changed. Not knowing GO here is an abstract attachment structure:

`
{
    Type : "image/png",
    Id  : "76cdf28e-efbb-4565-b749-1ab4fb89ba09",
    Path : "/uploads/google-app-store-light.png"
}
`

This will solve both, the preview, manageability and deliverability to any client. If the delivery is too heavy, option to not include images can be added in the settings of a campaign.

**Comment by tosie** [comment]
Have had something like this on my mind, but didn't have the time to implement it. The idea is good and I like the automatic replacement of URLs before sending.

A feature like this would also need to accommodate templated. Let's say I wanted to include a logo in my template. A data URI would be really nice, but GMail does not support this. The next best solution would be attachments and cid references. For that to work it would be necessary to have "template attachments" or pre-computed CIDs for uploads so that they can be referenced in a template. Really wonderful would be an automatic conversion of data URIs into attachments and CID references.

**Comment by supportdesk-si** [comment]
It's actually a relatively trivial implementation as each file is referenced in DB. If UUID is not an option, file DB ID can work. In fact, this is how we built it in our platform and it is very simple.

**Comment by funktionslust** [comment]
Hi,

I needed this feature, so I implemented it.

In the attachments modal you can click-to-copy the CID:

<img width="863" alt="cid2" src="https://github.com/user-attachments/assets/f0412fa9-3e7a-48f6-abac-e737e2ba9d9b">

... so you can use it in the content:

`<img src="cid:preview.png_4@example.com" />`

The content-id attachment header has been added, so the html image is rendered

----

Decisions:

 - Don't use UUID to keep UI cleaner (maybe exposing ID is considered bad practice here)
 - Don't store CID in DB to maintain backwards compatibility
 - Use fromEmail to achieve RFC 2392 compliance 
 - Don't replace `src` values automagically, user should have full control (RichText doesn't display cid images ofc, this could be done by replacing cid `src`s with actual image URLs for in frontend during WYSIWYG rendering)


If you're interested, I can create a MR
https://github.com/knadh/listmonk/commit/74125ddffdc75bdecb082a2775cf9244c1d493f4

**Comment by knadh** [comment]
Hi @funktionslust.

> Don't use UUID to keep UI cleaner (maybe exposing ID is considered bad practice here)

Exposing UUID (it's random) is fine. That eliminates all the logic required generate a custom CID. 

That said, a large number of function signatures have changed to accept `fromEmail`. We just need to get it to `MakeAttachmentHeader()` and don't need to make `ContentID` a part of the API response.
