### ISSUE TITLE
Allow empty names in import

### ISSUE THREAD

**Issue by kousu** [knadh/listmonk#1547]
**Is your feature request related to a problem? Please describe.**

I am often bulk importing emails using `/admin/subscribers/import` (to workaround #1546) of pre-existing subscribers, and I wish I didn't have to fill in a name field, especially since I'm unchecking "Overwrite".

I end up using files like

```
email,name,attributes
a@example.com,"name","{}"
b@hotmail.com,"name","{}"
c@gmail.com,"name","{}"
d@gmail.com,"name","{}"
```

but why is this a legal file

```
email,name,attributes
a@example.com,"name",
b@hotmail.com,"name",
c@gmail.com,"name",
d@gmail.com,"name",
```

but this isn't?

```
email,name,attributes
a@example.com,,"{}"
b@hotmail.com,,"{}"
c@gmail.com,,"{}"
d@gmail.com,,"{}"
``` 

The latter causes

```
skipping line 1: a@example.com: Invalid name.
skipping line 2: b@hotmail.com: Invalid name.
skipping line 3: c@gmail.com: Invalid name.
skipping line 3: d@gmail.com: Invalid name.
```

**Describe the solution you'd like**

Allow empty names during import. If that's not okay, allow it at least when "overwrite" is unchecked.

**Comment by knadh** [comment]
Please see this: https://github.com/knadh/listmonk/issues/967
