### ISSUE TITLE
Change the successful page after user subscribes

### ISSUE THREAD

**Issue by ramsrisantosh2712** [knadh/listmonk#1549]
Hi. After entering the details of the form The user is being navigated to a successful page which I don't want to display. Here's the screenshot after the user entered the form details

![Screenshot 2023-10-05 110515](https://github.com/knadh/listmonk/assets/144328378/98f4fbd9-5dff-4ee5-8880-45f9c7c30e51)

Is there any way to change the page?

**Comment by knadh** [comment]
Yes. You can either use JS (admin > Settings > Appearance) or fully customise the templates using the `—static-dir` flag. Please refer to the templating section in the  documentation.
