### ISSUE TITLE
Why not use Mailgun, Mailjet, Sendgrid, Postmark directly rather than via ListMonk?

### ISSUE THREAD

**Issue by tabatinga0x00** [knadh/listmonk#1551]
What value does ListMonk add onto these, except Gmail, Amazon SES and my own SMTP server?:

![Screenshot_20231006_104550](https://github.com/knadh/listmonk/assets/143210671/0f9afb29-8263-4250-b053-144fe262519e)

Why not use any of these providers directly? One would have to pay anyway, whether one uses them directly (their web interface), or via API (ListMonk). 

Don't they support management of the email lists, campaign, bounces... and other features that ListMonk does?

**Comment by MaximilianKohler** [comment]
In my case, they're much more expensive than Amazon SES, and SES doesn't have its own GUI, which is what Listmonk provides.

**Comment by tabatinga0x00** [comment]
@MaximilianKohler  in case of SES it's more or less clear, yes. But one also has to get verified by SES first, to be allowed to use it, and lately there have been rejections more often than it used to be.

But what about the other ones? Whether you use them directly or via API, the price remains the same.

**Comment by Scorpil** [comment]
Ability to switch at will with minimal effort.

**Comment by tabatinga0x00** [comment]
Between what and what? Why? How often do you usually do it? @Scorpil

**Comment by Scorpil** [comment]
Between different email service providers @tabatinga0x00. If I have an account on Sedgrid and manage my lists with a built in interface, subscribe/unsubscribe link, and proprietary templates it would be a pain to transfer all of that to, say, Postmark.

**Comment by tabatinga0x00** [comment]
@Scorpil agreed, 1 reason. But how often would you or an average user need to do it in order to justify to use ListMonk instead of the likes of MailChimp directly?

**Comment by Scorpil** [comment]
Can't say what average user wants @tabatinga0x00, I just know that I personally find listmonk valuable for avoiding vendor lock and taking care of user's data.

**Comment by kousu** [comment]
We felt that people who signed up for our mailing lists were trusting us with their demographic data, in a way that wouldn't be fair to pass on to Amazon of MailChimp. Instead of being shady to save ourselves some headaches, we found a self-hosted mailing list manager, and that is listmonk.

**Comment by tabatinga0x00** [comment]
@kousu how could you possibly measure the extent of their feeling? As well as compare it to what the same people would've felt if they were to sign up to other email service. Perhaps you delude yourself to justify your choice of ListMonk?
