### ISSUE TITLE
How to delete or export thousands of subscribers on particular lists?

### ISSUE THREAD

**Issue by beckend** [knadh/listmonk#1553]
I don't understand how to do it while matching lists?

**Comment by yuvraj9011** [comment]
> I don't understand how to do it while matching lists?

Hope this helps you
[screen-capture (2).webm](https://github.com/knadh/listmonk/assets/62428304/eb390a5a-a9e6-4f34-b26e-7a409603b644)

**Comment by beckend** [comment]
This deletes all chosen, from all lists, I only want 1 list.

**Comment by yuvraj9011** [comment]
Hello, 
please follow the steps outlined below:
1. Go to https://demo.listmonk.app/admin/lists.
2. You will find the available lists there.
3. Click on "Subscribers" to be redirected to the subscriber list page.
4. From there, you can delete or export subscribers.
For more detailed instructions, please refer to the attached video.
Thank you.
[screen-capture (3).webm](https://github.com/knadh/listmonk/assets/62428304/b590a38b-2251-49ef-8f5f-225ba8c10169)

**Comment by beckend** [comment]
I forgot to reply, sorry.
What you showed worked.

**Comment by yuvraj9011** [comment]
No worries!
I'm glad to hear that the solution worked for you.

All the best!!
