### ISSUE TITLE
SPAM abuse reports due to bots adding emails to my list and confirmation emails being marked as spam. What can I do about it?

### ISSUE THREAD

**Issue by elgatopanzon** [knadh/listmonk#1559]
I started getting these emails about Abuse reports from email providers, something called an FBL?

> We have received a complaint via a Feedback Loop (FBL) for an email that was sent from your IP

What seems to be happening is that bots add emails of real users to my newsletter, my newsletter then sends them the confirmation email for double-optin. That message is then marked as spam by the user, and the Abuse complaint is filed.

What can I do to stop the root of the issue: bots adding people to my list?
Thanks

**Comment by MaximilianKohler** [comment]
Use captcha. It's integrated to listmonk.

**Comment by elgatopanzon** [comment]
Thanks, upgraded my instance and enabled the Captcha. Hopefully resolves the issue!
