### ISSUE TITLE
Can I deploy listmonk under /listmonk URL?

### ISSUE THREAD

**Issue by jorgeteixe** [knadh/listmonk#1560]
I am trying to deploy listmonk under /listmonk path, because on my cloud I have everything configured this way.

I tried setting this environment variables without success, it fails with 404:
      - VUE_APP_ROOT_URL='https://cloud.example.org/listmonk'
      - BASE_URL='https://cloud.example.org/listmonk'

I did not found anything related on the documentation related to this.

Thanks in advance!

**Comment by knadh** [comment]
The way the frontend framework functions, this is extremely tedious (if it’s viable at all out of the box) unfortunately.

Please see https://github.com/knadh/listmonk/issues/174
