### ISSUE TITLE
How to query subscribers.attribs in templates?

### ISSUE THREAD

**Issue by gatonero** [knadh/listmonk#1565]
In German, when addressing subscribers, a distinction is made between male and female. How do I include such a query in a template? 

The query looks like this: If male, then 'Dear Mr. {{ .subscriber.name }}', if female, then 'Dear Ms.' {{ .subscriber.name }}'

The query looks like this: `subscribers.attribs->>'gender' = 'female'`

**Comment by knadh** [comment]
Something like this should work.

```go
Dear 
{{ if eq .subscriber.attribs->>'gender' "male" }}
Mr. 
{{ else if eq .subscriber.attribs->>'gender' "female" }}
Ms.
{{ end }}
{{ .subscriber.name }},
```

**Comment by gatonero** [comment]
@knadh thank you very much!
