### ISSUE TITLE
Problem in Transactional Email

### ISSUE THREAD

**Issue by chsanto2712** [knadh/listmonk#1566]
I am unable to send an Transactional Email to my Subscriber using ListMonk

For testing, I am using Postman Client.

![Screenshot 2023-10-20 112800](https://github.com/knadh/listmonk/assets/92885371/e60b526a-da8f-497c-93db-de2bbb4ff310)

This is my ListMonk Transactional Template

![Screenshot 2023-10-20 112915](https://github.com/knadh/listmonk/assets/92885371/e7e40a99-2f3f-4d9d-a310-07e1b193b440)

This is what I am getting error when I send request though I got success Message in the response in Postman

![Screenshot 2023-10-20 113232](https://github.com/knadh/listmonk/assets/92885371/d73f65b7-2d6a-4467-97c0-878236dcede4)

_Originally posted by @chsanto2712 in https://github.com/knadh/listmonk/issues/1534#issuecomment-1772133592_

**Comment by chsanto2712** [comment]
I resolved it... Thanks

**Comment by MaximilianKohler** [comment]
You should explain how you resolved it so that if someone else experiences the same issue they can fix it.

**Comment by chsanto2712** [comment]
So the main problem is that I haven't setup the SMTP server. So I came to know that Gmail provides us an SMTP server. I created an SMTP server using Gmail and finally I have set it up on the settings tab in listmonk
Thank you
