### ISSUE TITLE
Cannot query attributes: -> turns to →

### ISSUE THREAD

**Issue by SaschaValentin** [knadh/listmonk#1567]
The input field for query attributes behaves in a very strange manner. When I input -> as a selector for attribute values it immediately converts this input into →. So it is impossible for me to query for attributes.

First I thought it was matter of setting of the browser and therefore I tried different brothers. But the input field always react the same way.

In fact it's the same for all one line input fields. It only works on the multi-line fields where you can enter custom CSS or JavaScript.

Has anyone the same issue and knows how to solve it?

**Comment by knadh** [comment]
This is just the browser rendering the sequence of `-` and `>`as a "ligature" as a UX improvement. It shouldn't break your query. Is it actually breaking your query and throwing an error? If yes, please share the error.

**Comment by SaschaValentin** [comment]
Hello Kailash,

thanks for your help. You´re absolutely right. It works as you said. Perfect!
