### ISSUE TITLE
Prevent Search engine indexing?

### ISSUE THREAD

**Issue by DavidIlie-Raul** [knadh/listmonk#1568]
Hello there, i was wondering if there is a way to stop ListMonk from showing up in search results for search engines, i added a noindex meta tag to the html of the public pages using the static files mod, but i am not sure if there is anything else i could do, the main issue is that the listmonk installation is indexed using my server's ip address, instead of a subdomain that it has assigned to it.

Thanks in advance!

**Comment by knadh** [comment]
That should do it. If you have listmonk behind a reverse proxy behind Nginx, you can add a `robots.txt` that disallows all indexing.

**Comment by holtwick** [comment]
I achived this by adding this to my nginx configuration:

```
location = /robots.txt {
   add_header Content-Type text/plain;
   return 200 "User-agent: *\nDisallow: /\n";
}
```

Found here https://serverfault.com/a/751841/543412

**Comment by MaximilianKohler** [comment]
`add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";` seems simpler. 
https://stackoverflow.com/questions/44212339/how-to-prevent-google-indexing-my-https-urls
