### ISSUE TITLE
Support for AMP emails

### ISSUE THREAD

**Issue by vikky1992** [knadh/listmonk#1569]
Hi Team,  

Is there a plan on the roadmap for supporting AMP emails?  

[amp.dev](https://amp.dev/about/email)

**Comment by knadh** [comment]
Hi @vikky1992. There are no specific plans, but if it's just HTML + JS + CSS, you should be able to compose the markup elsewhere and send it with listmonk as-is (raw HTML).

**Comment by subhash-ngowda** [comment]
Hello @knadh ,

I have setup the domain with spf, dkim and dmarc as per the amp requirements. I have also added the sending email address in gmail as an approved amp sender.

I tried to send the email as raw html in V5. But looks like the content-type is not being applied as per the custom header. 
[
  {"Content-Type": "text/x-amp-html; charset=UTF-8"}
]

After i send the email by selecting raw html, on gmail i see the content type as Content-Type: text/html; charset=UTF-8 and only the html content is getting showed. Is there a way to add the other content types as well?

[
  {"Content-Type": "multipart/alternative"},
  {"Content-Type": "text/plain; charset=UTF-8"},
  {"Content-Type": "text/html; charset=UTF-8"},
  {"Content-Type": "text/x-amp-html; charset=UTF-8"}
]



Below is the sample html

```
<!doctype html>
<html ⚡4email>
  <head>
    <meta charset="utf-8">
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.2.js"></script>
    <script async custom-element="amp-img" src="https://cdn.ampproject.org/v0/amp-img-0.1.js"></script>
    <style amp4email-boilerplate>body{visibility:hidden}</style>
    <style amp-custom>
      body { font-family: sans-serif; padding: 20px; }
      amp-carousel { background: #f9f9f9; border-radius: 8px; }
      .carousel-img { border-radius: 8px; }
    </style>
  </head>
  <body>
    <h2>Featured Images</h2>
    <amp-carousel width="300" height="200" layout="responsive" type="slides" autoplay delay="3000" loop>
      <amp-img src="https://something/listmonk_images/lizard-9574714_640.jpg?text=Image+1" width="300" height="200" layout="responsive" class="carousel-img" alt="Image 1"></amp-img>
      <amp-img src="https://something/listmonk_images/tiger-9574724_640.jpg?text=Image+2" width="300" height="200" layout="responsive" class="carousel-img" alt="Image 2"></amp-img>
      <amp-img src="https://something/listmonk_images/beach-9556784_640.jpg?text=Image+3" width="300" height="200" layout="responsive" class="carousel-img" alt="Image 3"></amp-img>
    </amp-carousel>
    <noscript>
      <h2>Featured Images</h2>
      <p>AMP not supported. View images below:</p>
      <img src="https://something/listmonk_images/lizard-9574714_640.jpg?text=Image+1" alt="Image 1"><br>
      <img src="https://something/listmonk_images/tiger-9574724_640.jpg?text=Image+2" alt="Image 2"><br>
      <img src="https://something/listmonk_images/beach-9556784_640.jpg?text=Image+3" alt="Image 3">
    </noscript>
  </body>
</html>
```
