### ISSUE TITLE
Sparkpost Transmission API

### ISSUE THREAD

**Issue by prashant-bidgely** [knadh/listmonk#1570]
Is there any plan of integrating the transmission api from sparkpost or is it already integrated given that it provides wrapping multiple email payloads in a single call (upto 10k)?

**Comment by knadh** [comment]
Hi @prashant-bidgely. There is no plan to integrate any external delivery services into listmonk's core. You can use SparkPost's SMTP interface with list. If you specifically want to use their API, you can write a messenger WebHook service for that and plug that into listmonk Messengers.
