### ISSUE TITLE
What folder/directory should listmonk be installed in?

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1571]
The docs https://listmonk.app/docs/installation/#production say 
```
mkdir listmonk
sh -c "$(curl -fsSL https://raw.githubusercontent.com/knadh/listmonk/master/install-prod.sh)"
```
This guide https://rameerez.com/free-mailchimp-alternative-email-marketing-service/#listmonk-tutorial says 
```
mkdir listmonk && cd listmonk
sh -c "$(curl -fsSL https://raw.githubusercontent.com/knadh/listmonk/master/install-prod.sh)"
```
and cites https://github.com/knadh/listmonk#production, which also says `mkdir listmonk && cd listmonk`. 

Is `mkdir listmonk && cd listmonk` right and the docs are wrong?

On ubuntu I installed mine without `&& cd listmonk`. Maybe that's why I experienced some issues?

My `config.toml` and `docker-compose.yml` are not in my listmonk directory. My listmonk directory has two empty folders in it: `static` and `uploads`. 

## On ubuntu:
It installed to `/home/ubuntu/listmonk`.

## On CentOS 7:
I recently set up a forum on a CentOS server and it gets installed to `/home/nginx/domains/mysite.com/public`.

I can't find info on how that directory compares to the ubuntu one. I'm not sure if I should be installing listmonk into the `public` directory. 

`config.toml` and `docker-compose.yml` should definitely not be public right? Or does it not matter and it's handled automatically via the read, write, execute file permissions?

**Comment by knadh** [comment]
@mr-karan ?

**Comment by mr-karan** [comment]
> Is mkdir listmonk && cd listmonk right and the docs are wrong?

There's no standard here, it can be downloaded in any directory. The docs are missing a small `cd listmonk`  step, which I guess we can add.

`docker-compose.yml` and `config.toml` have to be present in the same directory, whichever directory you create. 

> config.toml and docker-compose.yml should definitely not be public right? Or does it not matter and it's handled automatically via the read, write, execute file permissions?

You don't need w/x permissions for both of these files. Read only is enough. It's best to consider your environment's risk and there's no generic answer here.
