### ISSUE TITLE
Views and clicks done by subscribers

### ISSUE THREAD

**Issue by yash-git-dev** [knadh/listmonk#1574]
I tried to access the campaign_views table but found blank data under subscriber_id column, on looking up the schema.sql found out that it was getting set by the register-campaign-view, but again unable to see the view under public profile. @knadh sir, any way to check out the subscriber id in both campaign_views and link_clicks table?

**Comment by knadh** [comment]
You've to enable individual subscriber tracking in `Settings -> Privacy`.
