### ISSUE TITLE
Easiest Way to Change Listmonk Homepage?

### ISSUE THREAD

**Issue by TheDanHealy** [knadh/listmonk#1575]
Hi all,

First, thanks for the great product! I am interested in the easiest way to modify the homepage (`/`). I'd want the homepage to be more subscriber focused instead of a large LOGIN button for admins. Are there any "templates" that you're using for the homepage? I see a page about CSS and JS, but I'd rather have something availably like HTML or such.

**Comment by knadh** [comment]
Yep, the system templates are fully customisable. Please see https://listmonk.app/docs/templating/#system-templates
