### ISSUE TITLE
timed out waiting for free conn in pool / connection refused / i/o timeout

### ISSUE THREAD

**Issue by abugaevcto** [knadh/listmonk#1579]
**Version:**
 - listmonk: [eg: v2.4.0]
 - OS: Ubuntu 20.04
 - Binary (not docker)

**Description of the bug and steps to reproduce:**
We've been sending 500-700 transactional emails daily with our own SMTP server via Listmonk. Once in a while in Listmonk logs we notice errors like this: `timed out waiting for free conn in pool`. Listmonk stop sending emails until we reload it. Reloading usually helps, but this time after reload there was a different error.

`2023/11/02 17:24:14error sending message 'Subject': dial tcp OUR_SMTP_IP:466: connect: connection refused`

We tried to reload, but the error was still there. We changed SMTP server to the trusted one, but there was another issue: `i/o timeout`

Nothing we tried made any difference. 

Then we sent an email from command line to rule out the possibility of firewall and network issues.

root@server:/home/ubuntu# sendemail -f $FROM -t $TO -o message-charset=utf-8  -u $SUBJECT -m $BODY -s $SMTP -o tls=auto -xu $FROM -xp $PASSWORD

Email was sent successfully, so we blame Listmonk for the errors above. 

Any suggestions?

**Comment by knadh** [comment]
Hi @abugaevcto. What SMTP server are you using? Could you also share the config (concurrency, max conns, timeout values etc.) you're using?

> timed out waiting for free conn in pool

This happens when all the connections in the pool are busy. Given that you're only sending ~700 e-mails in a day, this ideally should never happen. Please share the config in use to help debug this. Could be an edge case in listmonk's SMTP lib.


> dial tcp OUR_SMTP_IP:466: connect: connection refused
> i/o timeout

These errors come from the network (TCP) layer, not from listmonk's SMTP lib. "Connection refused" is typical for a firewall or IP tables block. As your `sendemail` command did work from the same host, I'm not sure what's happening here. Could be something like AppArmour/SELinux on the host?

**Comment by abugaevcto** [comment]
> timed out waiting for free conn in pool

> Hi @abugaevcto. What SMTP server are you using? Could you also share the config (concurrency, max conns, timeout values etc.) you're using?

We're using iRedMail. 

```
smtp_helo_timeout = 300s
smtp_mail_timeout = 300s
smtp_quit_timeout = 300s
smtp_rcpt_timeout = 300s
smtp_rset_timeout = 20s
smtpd_upstream_proxy_timeout = 5s

# Concurrency per recipient limit.
smtp-amavis_destination_recipient_limit = 1

# mlmmj - mailing list manager
mlmmj_destination_recipient_limit = 1

default_destination_concurrency_limit = 20
initial_destination_concurrency = 5
local_destination_concurrency_limit = 2
```

This problem is still bothering us, because it occur unexpectedly and we did not start sending campaigns yet, just transactional. The only time when we send a campaign on 200-300 users at the same time, this error was there immediately. 


> dial tcp OUR_SMTP_IP:466: connect: connection refused
> i/o timeout

This one is solved, and the reason behind it is laughable. I hope you will fix it in future releases. There's a full description of our case below:

1. There was the error `timed out waiting for free conn in pool`, and I opened mobile version of Listmonk (android, latest chrome) to reload the app, so that our emails continue to work, because it always worked before.
2. When I scrolled through to the SMTP configuration to save something and reload the app, I did hold my finger on "+" around SMTP port, and it started to increase, although that segment was disabled (I have multiple smtp accounts). So when I clicked Save, Listmonk updated my port and I did not know that.
3. After reloading Listmonk stopped sending my mail because smtp port was incorrect and it took me hours to find that.

So I expect when scroll something, form components must not be changed by themselves. 

Thank you and I hope you can help us with `timed out waiting for free conn in pool`.

**Comment by knadh** [comment]
Could you share the SMTP config (Settings -> SMTP) and performance config (Settings -> Performance) that you've set in listmonk?

**Comment by shaunakv1** [comment]
I can confirm we are running into the same issue. We are using Google SMTP. Here are the settings. 

![image](https://github.com/knadh/listmonk/assets/732604/0a660c44-6f90-4606-a310-5a2a27ee5710)

![image](https://github.com/knadh/listmonk/assets/732604/ad936d1b-5c75-4ca9-ae11-9530e8250dc5)


Interesting thing is, according to list monk database, campaigns are finished, but we can confirm that most of the emails didn't go out after the first few. 

![image](https://github.com/knadh/listmonk/assets/732604/60d38ab3-2bc4-4a2b-82c3-afee79c1ccbe)

**Comment by abugaevcto** [comment]
SMTP config

![image](https://github.com/knadh/listmonk/assets/62311881/5b0e88a1-0b02-4d86-8012-0cad8cd9c2a1)

Perfomance config

![image](https://github.com/knadh/listmonk/assets/62311881/037c3686-fb9b-4974-954b-e17b85958721)

**Comment by Parado2X** [comment]
I am experiencing same issue with the **"timed out waiting for free conn in pool"**. 
The restart of a Listmonk solve the issue for some time but then in a few days the campaign will stop automatically because of more than 1000 errors.

**Comment by SKJoy** [comment]
Happening over here as well. Using 10 remote SMTPs (ListMonk is in Docker and the SMTP server is with the host) with SSL. Campaigns are not working after a while with this error message.

**Performance**: 2 workers with 1 per second = 2 per second throughput
**Batch size**: 1000
**Slide window limit**: Disabled
SMTP sever send out limit: 7000 / Hr

**Comment by abugaevcto** [comment]
Any updates here? Still can't use Listmonk because of that error.

**Comment by knadh** [comment]
I've been unable to reproduce this ;( Our prod setup sends tens of thousands of mails per minute without any hiccups with our self-hosted SMTP.

**Comment by knadh** [comment]
Currently testing the core concurrent queue manager that has been fully rewritten. While I was unable to reproduce this issue, I'm hoping that this will address it in case it was a subtle bug. Will available in the upcoming release. https://github.com/knadh/listmonk/compare/master...fix-campaign-sent

**Comment by shaunakv1** [comment]
@knadh this fell off my radar for a while, but I can report that the issue is squarly with google's SMTP and throttling policies and **not with listmonk**

We ran some at scale tests using other self hosted smtp servers and things work just fine and with listmonk running on minimal resources too.  So we ended up just using an internal SMTP. 

We have come to believe, unless someone else can authoritatively refute this that Google's SMPT is not meant to send bulk bursts out like this.  It works for application mailing just fine. 

If any thing, only issue I can think of on listmonk end is that it makes it look like the mails went out, when they are getting dropped at google. Unsure if there anyway to fix that, but that's what caused the confusion in the first place.

**Comment by abugaevcto** [comment]
@shaunakv1 @knadh we've been using internal SMTP for a while, but this issue is still with us (v3.0.0). We tried everything, but sometimes we can send 3-4k emails without problems, sometimes there's error after sending 200-300 emails, I don't see any pattern.

**Comment by AshPowell** [comment]
Just had this also - Amazon SES though, an app reboot seems to have fixed it for now.

I wonder if something is keeping connections open / allowing them to be kept open when they shouldn't be.

**Comment by MaximilianKohler** [comment]
I also just experienced this with Amazon SES and listmonk v2.5.1. It was a small campaign of ~3k recipients. It looks like the errors popped up a few seconds after the campaign began and then resolved itself. I send similar campaigns daily, with the same settings, without any issue, usually.

It started with `context deadline exceeded` errors then `timed out waiting for free conn in pool`, and ended with one `451 4.4.2 Timeout waiting for data from client`.

I'm going to set my SMTP max conns & timeout limits much higher, as suggested here: https://github.com/knadh/listmonk/issues/734

<details><summary>Logs</summary>

```
2026/01/28 08:00:02start processing campaign (<campaign name>)

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 123908: context deadline exceeded

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 577027: context deadline exceeded

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 125025: context deadline exceeded

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 388008: context deadline exceeded

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 463231: context deadline exceeded

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 242891: context deadline exceeded

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 603347: context deadline exceeded

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 627567: context deadline exceeded

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 677843: context deadline exceeded

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812465: context deadline exceeded

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812694: timed out waiting for free conn in pool

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812693: timed out waiting for free conn in pool

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812655: timed out waiting for free conn in pool

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812658: timed out waiting for free conn in pool

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812528: timed out waiting for free conn in pool

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812692: timed out waiting for free conn in pool

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812553: timed out waiting for free conn in pool

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812732: timed out waiting for free conn in pool

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812728: timed out waiting for free conn in pool

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812698: timed out waiting for free conn in pool

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812701: timed out waiting for free conn in pool

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812696: timed out waiting for free conn in pool

2026/01/28 08:00:08error sending message in campaign <campaign name>: subscriber 2812730: timed out waiting for free conn in pool

2026/01/28 08:00:17error sending message in campaign <campaign name>: subscriber 463773: 451 4.4.2 Timeout waiting for data from client.

```
</details>
