### ISSUE TITLE
WHMCS Module

### ISSUE THREAD

**Issue by mbh-dev** [knadh/listmonk#1582]
Hi,

Does anyone have experience with WHMCS? In particular, a module that would integrate with Listmonk, similar to Mailchimp's (see: https://docs.whmcs.com/Mailchimp)

This module in theory, would be able to link users who register/purchase a service being added into Listmonk for the purpose of comms and marketing.

It would be great to have this feature, as it would help move away form Mailchimp, see as their T's & C's have become somewhat problematic with the introduction of AI.

Thanks.

**Comment by MaximilianKohler** [comment]
I think Mautic has that kind of stuff.
