### ISSUE TITLE
Bruteforce protection

### ISSUE THREAD

**Issue by aqua-pro** [knadh/listmonk#1583]
Hello!

First of all, thank you for the amazing software! It works really well!

I'd like to ask a security question. I am using listmonk in a public setting - people can access the web app, and I am concerned of someone trying to get my login credentials by bruteforce. I haven't seen anything related anywhere, so I'd like to ask - is there any natively implemented bruteforce protection? Or maybe fail2ban can be implemented easily?

Thank you very much
Best regards

**Comment by knadh** [comment]
There is no built in brute-force protection. Using a long password should be good enough. As listmonk is typically behind a proxy like nginx or Caddy, you can always easily add rate limits to the `/admin/*` endpoints.

**Comment by golightlyb** [comment]
for nginx, see e.g. `ngx_http_limit_req_module`
