### ISSUE TITLE
Incremental campaign

### ISSUE THREAD

**Issue by kettenbach-it** [knadh/listmonk#1584]
Many years ago I took a look at PHPList. 
It has a very nice feature: you can resend a campaign that has already been sent once and mails are then sent to those subscribers who were not yet subscribed to the selected list when it was last sent!

This is exactly the feature I would like to have with Listmonk!
In this way you could, for example, send the newsletter from the beginning of the month to the new subscribers during the course of the month - with Listmonk it is currently only possible to send to everyone again.

**Comment by knadh** [comment]
There's a crude, tedious way of achieving this right now.

- Create a new temporary list.
- Filter subscribers with `id IN (SELECT subscriber_id FROM subscriber_lists WHERE created_at >= '2023-11-11' AND list_id=1)` (subscribers added to a certain list after a date)
- Add the resulting subscribers to the new list.
-  Send campaign to this list. Delete list.

**Comment by kettenbach-it** [comment]
But it's better than nothing! Thanks!

**Comment by lefuturiste** [comment]
I may be interested into contributing code on a PR for this useful feature I would want to have.

**Comment by macpijan** [comment]
> I may be interested into contributing code on a PR for this useful feature I would want to have.

Have you tried anything yet @lefuturiste 

We are also interested in this feature. Can we hope for some hints from maintainers if/how this could be approached?

**Comment by lefuturiste** [comment]
I've not tried anything.
But first we need to plan the feature.
For me, I would like to have a boolean settings like "auto-send the campaigns from the last eg. 1 week when the user register" (configurable duration).
Then I would trigger a new job when a user register and it have pending campaign.

**Comment by macpijan** [comment]
We are using this feature in [mailtrain](https://github.com/Mailtrain-org/mailtrain) so it might be a reasonable reference.

**Comment by 1000i100** [comment]
> There's a crude, tedious way of achieving this right now.
> 
>     * Create a new temporary list.
> 
>     * Filter subscribers with `id IN (SELECT subscriber_id FROM subscriber_lists WHERE created_at >= '2023-11-11' AND list_id=1)` (subscribers added to a certain list after a certain date)
> 
>     * Add the resulting subscribers to the new list.
> 
>     * Send campaign to this list. Delete list.

Could the query be adapted to catch not from a date but as unsent ?
Like this-one for unopened : https://github.com/knadh/listmonk/issues/1337#issuecomment-2185477862

**Comment by MaximilianKohler** [comment]
@1000i100 yes, it should work if you just replace the 2nd line with the other command.
