### ISSUE TITLE
Documentation Layout Broken

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#1585]
Check this, the table is broken:
https://listmonk.app/docs/apis/campaigns/#get-apicampaigns

![image](https://github.com/knadh/listmonk/assets/6888294/5e74b084-ee04-4a00-b355-6c70d66b7db1)

Should be quite easy to fix I guess.

**Comment by NicoHood** [comment]
Thanks! Is there a sample query to filter campaigns by an exact name match? I query my campaigns by a unique name instead of using the id (we use the date as unique name)

**Comment by knadh** [comment]
There isn't currently. The right way to achieve this would be to attach specific tags to campaigns and then query by tags. Will add querying campaigns by tags in the upcoming release. I've added this to my to-do.

**Comment by NicoHood** [comment]
Can we track this in a specific issue please, so I can subscribe and be notified if it completes?

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/issues/1631

**Comment by NicoHood** [comment]
Thanks. But my request was about querying by the name of the campaign, not the tags. So this would be another request I guess

**Comment by knadh** [comment]
Ah, I think I misunderstood your earlier question. listmonk already supports querying a campaign by name. `/api/campaigns/?query=YOUR_QUERY`.

If you're using a date like ` 2023-12-30 `, then you can find it with `/api/campaigns?query=2023-12-30`.
