### ISSUE TITLE
Newly created lists don't show up under "Import subscribers" 

### ISSUE THREAD

**Issue by pswapneel** [knadh/listmonk#1589]
**Version:**
 - listmonk: v2.5.1
 - OS: Ubuntu 22.04.3 LTS

**Description of the bug and steps to reproduce:**
After upgrading the v2.5.1, it appears newly created lists don't show up under "Import subscribers" > List (drop-down)

Settings > Logs contain,

```
2023/11/04 13:27:28v2.5.1 (a6a2b69 2023-08-15T15:49:28Z, linux/amd64)
2023/11/04 13:27:28reading config: config.toml
2023/11/04 13:27:28connecting to db: localhost:5432/newsletter
2023/11/04 13:27:28media upload provider: filesystem
2023/11/04 13:27:28loaded email (SMTP) messenger: email@mydomain.tld@smtp.gmail.com
2023/11/04 13:27:28WARNING: error getting database version: pq: database "listmonk" does not exist
2023/11/10 15:34:08start processing campaign (Test)
2023/11/10 15:34:08campaign (Test) finished
```

Also, even after restarting "listmonk" process, the issue persists. 

Any inputs, suggestions to resolve this will be much appreciated. Thanks!

**Comment by knadh** [comment]
After creating a list, can you try a `Ctrl + Shift + R` on the import page? A restart not changing anything indicates that this could be the browser caching the JSON API responses on the frontend.

**Comment by MaximilianKohler** [comment]
This has been reported a few times. You have to refresh (F5) the page. https://github.com/knadh/listmonk/issues/1076#issuecomment-1364720799

**Comment by codiflow** [comment]
For me the only solution was to logout and login again. Afterwards all newly created lists were available.

**Comment by talk2sohail** [comment]
I have also been seeing this issue more frequently since the time I started using the app. I think we should pin this issue until we come up with the solution?

For me, sometimes page refresh or logging in after after logout worked!

**Comment by pswapneel** [comment]
Apologies for the delayed response. @knadh That didn't work. @MaximilianKohler unfortunately, refresh doesn't work for me. 

The only solution that's working is to logout and login back again.

**Comment by MaximilianKohler** [comment]
How about control+F5 instead of just F5? What browser are you using? Do you have many addons installed?
