### ISSUE TITLE
override transactional email templates

### ISSUE THREAD

**Issue by sweetppro** [knadh/listmonk#159]
I'd like to be able to create my own template for use with the confirmation email, and confirmation pages.
Is it possible to add a settings page for changing the theme for all these internal pages/emails.

thx

**Comment by knadh** [comment]
You can use the `--static-dir` param to load your own templates as explained on the [Wiki](https://github.com/knadh/listmonk/wiki/Configuration).

**Comment by sweetppro** [comment]
nice!
I was looking through the [docs](https://listmonk.app/docs/), and didn't see any references to the wiki
