### ISSUE TITLE
Unable to --install database. Invalid host header. 

### ISSUE THREAD

**Issue by Nikto655** [knadh/listmonk#1591]
I had listmonk running previous for a while with no issues, I cant remember exactly how I installed it but I ran everything in docker and got it all to work. 

Today I removed everything and wanted to do a fresh install, however Im unable to get the database correctly installed. 
When I run `docker compose run --rm app ./listmonk --install` I get an error: `http: invalid Host header`

Unsure what to do from here or how to fix.

**Comment by Nikto655** [comment]
I was able to bypass this problem through a really backwards method to get the database schema installed. I believe something somewhere is off with the advertised method of installing.

**Comment by mr-karan** [comment]
Can you share full logs for more context, alongside the docker-compose.yml/config.toml if modified?

**Comment by jaideep2** [comment]
Probably related to https://github.com/docker/cli/issues/4437#issuecomment-1637715017
