### ISSUE TITLE
My inline styles are being removed :(

### ISSUE THREAD

**Issue by jonyTF** [knadh/listmonk#1595]
**Version:**
 - listmonk: v2.5.1
 - OS: PikaPods

**Description of the bug and steps to reproduce:**
When I add styles to my email (i.e. text color, justify-content: center), they do not appear in the resulting email.
I am using the AWS SES smtp server, and I am opening the email in gmail. 

**Screenshots:**
This is the HTML code for my template:

![image](https://github.com/knadh/listmonk/assets/16812809/39ab828d-d513-4d28-ab53-c81bc219f0d6)

This is how it shows in the preview:

![image](https://github.com/knadh/listmonk/assets/16812809/cce0631d-edfd-4bbb-85ac-2d705044fa0f)

This is what it looks like when the email is sent to my inbox:

![image](https://github.com/knadh/listmonk/assets/16812809/1df75b8e-3990-4eac-a708-66ff2c589ee1)

And this is how it looks when I inspect the image in my inbox:

![image](https://github.com/knadh/listmonk/assets/16812809/bd0bc7b0-5124-4f60-be70-42b196b7a875)

As you can see, the `justify-content: center;` inline style is removed from the email for whatever reason.

Is this a problem with AWS SES, or is it a problem with listmonk?

**Comment by knadh** [comment]
Sorry, missed this. listmonk does not to any HTML processing.

**Comment by MaximilianKohler** [comment]
I use centered content with SES and gmail, so it's probably something unique to the `div style justify-content`.

I use:
`<p style="text-align: center; line-height: 1.2;"><span style="font-size: small; font-family: verdana, geneva, sans-serif;">`

**Comment by jonyTF** [comment]
OMG the `text-align: center` style worked! Thank you so much
