### ISSUE TITLE
Add support for functions to transactional email templates

### ISSUE THREAD

**Issue by peterjcarroll** [knadh/listmonk#1596]
I would like to be able to use the functions listed in the documentation at https://listmonk.app/docs/templating/#functions in my templates for transactional emails.

I am especially interested in using TrackLink, TrackView, and UnsubscribeURL.

I saw in issue #1409, you felt that unsubscribe urls don't apply to transactional emails, but it my case they do. I'm sending transactional emails to my mailing list users via the API because Listmonk doesn't support sending an email triggered by a new subscription. 

I also know that normally the unsubscribe link has the campaign uuid in the url, but in the opt-in emails, the unsubscribe link just uses a uuid of all zeros instead of a campaign uuid. The unsubscribe url for transactional emails could be done the same way.

Thanks for your hard work on Listmonk!

**Comment by javierarce** [comment]
I was about to request the same thing when I discovered that the following URL works. I used it to unsubscribe from a system email: `{{ RootURL }}/subscription/{{ .Subscriber.UUID }}/{{ .Subscriber.UUID }}`.

P.S.: I'm new to this, and I haven't tested this in a transactional email.

**Comment by LordPraslea** [comment]
This is usefull in a way things like TrackLink would be usefull for transactional emails
