### ISSUE TITLE
List subscribers when clicked on specifc list in "All Lists" page 

### ISSUE THREAD

**Issue by talk2sohail** [knadh/listmonk#1597]
**Is your feature request related to a problem? Please describe.**
I see it as anti-pattern when I click on the list name, it opens a pop up that tells me to edit the list details. Although we have a button to edit the list details.

Below are the 2 reasons that I see fit for this use case:

1. I believe user would want to see the subscriber listed under the list when they click on the list name.
2. Even if I go to the "Subscriber" tab and want to see the user/subscribers under a specific list. I do not see any for this.

**Describe the solution you'd like**
When I go the "All Lists" tab, It will list all the predefined list there. It is quiet intuitive for me to see the subscriber under that list. Then I can perform actions like add/remove/edit subscribers and so on.

Thanks to the team for the clear documentation, I was able to deploy the app within no time using railway service providers.

List tab page:
![Screenshot from 2023-11-20 22-46-25](https://github.com/knadh/listmonk/assets/37415268/0852230a-e951-42e4-b8a8-84fc511fd09c)

Subscriber page:
![Screenshot from 2023-11-20 23-35-38](https://github.com/knadh/listmonk/assets/37415268/c80ec749-4815-405f-b5ae-aca0ddc097e2)

**Comment by knadh** [comment]
Clicking on the number of subscribers shows the subscribers under the list.
