### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by PCC17** [knadh/listmonk#160]
I really love using listmonk.

But a thing I am extremly missing is the ability for translation.
I need to send my users pure German emails. Most of this can be done by using the static templates.

Nevertheless some things cant be changed: for example the email Subject 'Confirmed'

Wouldn't it be great to add basic multiple language support by using some kind of config files?

**Comment by knadh** [comment]
Thanks @PCC17. i18n is on my list of things to do after the upcoming release. Should be reasonably straight forward to implement.

**Comment by m42e** [comment]
I am not that experienced in go, but would you accept a PR regarding this topic?

**Comment by diogotcorreia** [comment]
+1
Would love to see this implemented! Thanks for the awesome work you have by now :)
I wouldn't mind translating things into Portuguese if needed

**Comment by FelixDz** [comment]
Same here ! I can do the translation into French, would be a pleasure to help :)

**Comment by knadh** [comment]
Have started working on this. Added to the [v0.8.1-beta](https://github.com/knadh/listmonk/milestone/2) milestone.

**Comment by knadh** [comment]
Update: Have almost finished building the English language pack. Should be able to push to master next week.

Will setup a https://traduora.com instance to manage translations and contributions.

**Comment by knadh** [comment]
i18n support is [added](https://github.com/knadh/listmonk/tree/i18n/i18n). I've also setup a [Traduora](https://i18n.listmonk.app) instance so that the translation can be done on a UI. Might just be quicker to copy the [JSON file](https://github.com/knadh/listmonk/tree/i18n/i18n) and translate the strings.

@diogotcorreia @FelixDz would you be interested in adding Portugese and French translations?

**Comment by diogotcorreia** [comment]
@knadh For sure! I'll do them as soon as I have some time :)

**Comment by diogotcorreia** [comment]
@knadh I've signed up on Traduora, could you add me to the project? My email is in my GitHub profile.

**Comment by knadh** [comment]
@diogotcorreia Added you to the project.

Traduora's UI is a bit clunky, for instance, for every string, it shows a big box on the screen and only 10 such boxes spread across a large number of pages. Ideally, one should be able to rapidly just TAB into the subsequent lines while translating them. I'll see if I can quickly make a simple single page UI for translating listmonk's strings.

**Comment by knadh** [comment]
@diogotcorreia please ignore Traduora. It's too tedious.

I've made a simple single page UI here to manage listmonk translations: https://listmonk.app/i18n/

You can use it to write the translation, and once you're done, you can copy the raw JSON, add send a `pt.json` PR to the repository. Thanks.

**Comment by diogotcorreia** [comment]
@knadh Thanks, that is so much better.

Meanwhile, I found a wrong message in the i18n English file: `settings.general.fromEmailHelp`.
It has the same content as `settings.general.logoURLHelp`, but it's obviously not related.

I'm already past half of the translations, so they should be ready very soon 😄

**Comment by knadh** [comment]
Great! Fixed the typo: https://github.com/knadh/listmonk/commit/d737e5d92bea12ab3111c17b0fb02edbe2593e01

**Comment by FelixDz** [comment]
@knadh thanks for the tool you setup for easy translation, and sorry for the long silence on my behalf. I just submitted a PR for french translations !
