### ISSUE TITLE
Use from-address without sender name

### ISSUE THREAD

**Issue by relikd** [knadh/listmonk#1602]
I would like to use plain email senders for our setup.

1. Default email sender (settings) does not allow to set plain email text, only named email (e.g. `Example <mail@example.org>` but not `mail@example.org`). 
2. Setting `mail@example.org <mail@example.org>` will fail to send emails because of smtp server error "expected one email sender".

In a campaign you can set `mail@example.org`, however the email client will show it as `<mail@example.org>` instead of a plain email address.

**Comment by knadh** [comment]
Hi @relikd. I'm a bit confused. Are you referring to campaigns -> Content -> Format [Plain text]? Because any campaign can be HTML/Markdown/Plain text.

**Comment by relikd** [comment]
No, I am talking about the email FROM field. Settings -> General -> Default from email ... and Campaign -> Campaign -> From address
