### ISSUE TITLE
Campaigns clicks always 0, individual subscriber tracking turned off

### ISSUE THREAD

**Issue by post-duif** [knadh/listmonk#1604]
**Version:**
 - listmonk: v2.5.1
 - OS: Ubuntu, docker 

**Description of the bug and steps to reproduce:**
I expect clicks for each campaign I run to be larger than zero. If I click links myself, they are also not counted towards the 'clicks' metric. 

I have "Individual subscriber tracking" turned off, but shouldn't clicks still be counted in general?
**Screenshots:**

I have links included in each campaign, but as you can see in the screenshot the count is always 0.

<img width="177" alt="Screenshot 2023-11-24 at 11 24 17" src="https://github.com/knadh/listmonk/assets/126626953/9312dcdc-3f52-4728-8a10-494b5070181a">
<img width="901" alt="Screenshot 2023-11-24 at 11 25 48" src="https://github.com/knadh/listmonk/assets/126626953/56b00915-412d-4c39-8271-dd0daf123ec7">

**Comment by knadh** [comment]
Can you run `SELECT COUNT(*) FROM link_clicks WHERE campaign_id=$campaign_id;` on the Postgres DB and verify whether clicks are being recorded at all?

**Comment by post-duif** [comment]
How do I do that? The command doesn't work in "advanced" SQL query tab on the admin/subscribers page.

**Comment by knadh** [comment]
Ah, you'll have to run this using `psql` on the database directly. If you are running listmonk using docker compose, executing the following command in the directory where you have the `docker-compose.yml` file should work.

```bash
docker-compose exec db psql -U listmonk -d listmonk -c "SELECT COUNT(*) FROM link_clicks WHERE campaign_id=1;"
```

**Comment by post-duif** [comment]
Results:

 count 
-------
     0
(1 row)

**Comment by knadh** [comment]
So there aren't any clicks being recorded. You're wrapping links in the e-mail with `{{ TrackLink }}` right? (or the track checkbox in the richtext editor that automatically add this to the links). You can verify this by check the link in the delivered e-mail. It should start with your listmonk domain, and not the actual link.

PS: You did replace `campaign_id=1` with your campaign's numeric ID, correct?
