### ISSUE TITLE
Easy way to see unsubscribers? 

### ISSUE THREAD

**Issue by nrathi** [knadh/listmonk#1609]
<img width="254" alt="image" src="https://github.com/knadh/listmonk/assets/3291034/b2c12281-3113-49d0-8779-82487737cf0c">

Is there an easy way to figure out who these 28 people are? They're not blocklisted, just unsubscribed from one list.

Thanks!

**Comment by MaximilianKohler** [comment]
No. I think in the next update you'll be able to sort the list by "status" and see blocklisted people. But even downloading the list won't show "unsubscribed". https://github.com/knadh/listmonk/issues/738 https://github.com/knadh/listmonk/issues/863

**Comment by knadh** [comment]
This feature is added in https://github.com/knadh/listmonk/commit/51af75cfef2c1ecbc2587ccb99778a9d1262248f. The `unsubscribed`, `unconfirmed` etc. numbers on the lists UI are now clickable, which leads to a filtered subscribers view.

A `?subscription_status=$status` query param has been added to `GET /api/subscribers` as well.

**Comment by MaximilianKohler** [comment]
The new feature is only per-list right? I have hundreds of lists and I need to be able to blocklist everyone who has unsubscribed from any of them.
