### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by heinrichreimer** [knadh/listmonk#161]
Currently we can translate user-facing HTML, but not the messages displayed within.
This is done via the `--static-dir` argument.
It would be awesome to be able to localize all texts, including the admin UI.

**Comment by knadh** [comment]
Hi @heinrichreimer. Issue https://github.com/knadh/listmonk/issues/160 is exactly this. Closing this so that we can track the status in one place.

**Comment by heinrichreimer** [comment]
I'm sorry, should have searched the existing issues more thoroughly!
Thanks for this great software, and let me know if I can help you with anything.
