### ISSUE TITLE
When scheduling multiple campaigns at the exact same time, not all complete

### ISSUE THREAD

**Issue by sjoerdvanderhoorn** [knadh/listmonk#1616]
**Version:**
 - listmonk: 2.4.0
 - OS: Docker

**Description of the bug and steps to reproduce:**
When scheduling multiple campaigns to send at the exact same time, the status of all of them changes to "running" as the scheduled time occurs, but only a portion of them will fully send and change their status to "finished".

This has happened to me multiple times. The last time was earlier today, where only 8 out of 28 scheduled campaigns completed.

Pausing and resending a campaign does not resolve the issue or send the emails. Note that pausing, cancelling, or restarting a campaign is not added to the logs either.

**Screenshots:**

Below is an anonymous copy of the log for the campaigns that were supposed to send this morning. As you can see, 28 campaigns were started but only 8 finished.

> 2023/12/04 05:30:04start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:04campaign (XXXXXXXX-2023-12-04-YYYY) finished
2023/12/04 05:30:04start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:04campaign (XXXXXXXX-2023-12-04-YYYY) finished
2023/12/04 05:30:04start processing campaign (XXXXXXXX-2023-49-YYYY)
2023/12/04 05:30:04campaign (XXXXXXXX-2023-49-YYYY) finished
2023/12/04 05:30:04start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:04start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-49-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05campaign (XXXXXXXX-2023-12-04-YYYY) finished
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05campaign (XXXXXXXX-2023-12-04-YYYY) finished
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05campaign (XXXXXXXX-2023-12-04-YYYY) finished
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05campaign (XXXXXXXX-2023-12-04-YYYY) finished
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05start processing campaign (XXXXXXXX-2023-12-04-YYYY)
2023/12/04 05:30:05campaign (XXXXXXXX-2023-12-04-YYYY) finished

**Comment by knadh** [comment]
This is fixed in [2efa5a5](https://github.com/knadh/listmonk/commit/2efa5a5947ac385df15a77f2be7ef0b6a1711daa).

**Comment by sjoerdvanderhoorn** [comment]
Thanks! I can confirm this fix works like intended.
