### ISSUE TITLE
Admin UI branding

### ISSUE THREAD

**Issue by heinrichreimer** [knadh/listmonk#162]
We'll be using listmonk for our public mailing list.
We would like to change the logo and title in the admin UI, and maybe tweak some CSS. Is there a mechanism similar to `--static-dir` available for branding the admin UI?

**Comment by knadh** [comment]
Unfortunately no. The admin UI is a compiled React (and Vue in the upcoming release) Javascript application bundled by Webpack. There aren't any provisions to customize it. You could always fork and change the CSS/images and re-bundle.

**Comment by heinrichreimer** [comment]
I see, this is fine.
Is there any chance to use the `logo_url` and `favicon_url` configuration to display a logo?
Maybe even add a `title` configuration to be able to change the company name?

**Comment by knadh** [comment]
Not currently. It's uncommon for the admin UIs of apps to be customizable, but I'll see if this is easy enough to provision in one of the upcoming updates.

**Comment by heinrichreimer** [comment]
You're right. I'm looking forward to it.

**Comment by knadh** [comment]
Closing this issue as it isn't straight forward to implement, and as I mentioned before, is out of the scope of the project. Thanks.

**Comment by spss20** [comment]
Why this is not implemented till date, it is required sometimes. Sometimes, I need to whitelabel the product and take full advantage of open source.

**Comment by knadh** [comment]
@spss20, "whitel-abelling" is not in listmonk's goals or roadmap. You could use Settings -> Appearance -> Admin CSS/JS to use CSS and JS to customize the appearance of the admin panel though.
