### ISSUE TITLE
docker-compose run --rm app ./listmonk --install fails

### ISSUE THREAD

**Issue by RapidRotator** [knadh/listmonk#1620]
I'm following the instructions at https://listmonk.app/docs/installation/#easy-docker-install_1.  `$ docker compose up -d db` brought up the postgress container without problems, but 

```
docker compose run --rm app ./listmonk --install
```
fails after:
```
Creating listmonk_app_run ... done
2023/12/09 17:09:23 main.go:102: v2.5.1 (a6a2b69 2023-08-15T15:49:28Z, linux/amd64)
2023/12/09 17:09:23 init.go:145: reading config: config.toml
2023/12/09 17:09:23 init.go:273: connecting to db: listmonk:5432/listmonk
2023/12/09 17:09:23 init.go:277: error connecting to DB: dial tcp: lookup listmonk on 127.0.0.11:53: no such host
ERROR: 1
```
It seems like the ip mentioned is hardcoded somewhere, while docker-compose makes sure services can be called by name. Is there a workaround?

**Comment by MaximilianKohler** [comment]
A search for that IP:port https://www.ecosia.org/search?q=127.0.0.11%253A53 shows other people having the same issues and some suggested solutions having to do with your config or possibly firewall.

**Comment by RapidRotator** [comment]
Indeed. Changing the value op host in config.toml to the IP docker gave the postgres instance allowed the script to finish successfully. Thanks.

**Comment by MaximilianKohler** [comment]
That's strange. Maybe it's a reverse proxy issue? Are you running nginx?

**Comment by RapidRotator** [comment]
As I understood from the link you mentioned above, docker's DNS does not always work as documented. So replacing the hostname in the configuration that the script seems to use to the correct IP allowed it to find the postgress instance.
