### ISSUE TITLE
Archive not allowing tracked links to be followed

### ISSUE THREAD

**Issue by jacobholes** [knadh/listmonk#1625]
**Version:**
 - listmonk: 2.5.1
 - OS: Ubuntu Server 22.04.3

**Description of the bug and steps to reproduce:**
Create a campaign with tracked links, view the archive, every link clicked shows the message: "Not Found"

To work around this, I share a link to the newsletter that was sent to my inbox and then share that as the archive. Would it be possible to disable link tracking on the archive and just allow the links to be clicked and take users to the destination? 

**Screenshots:**
![Not Found](https://github.com/knadh/listmonk/assets/1165989/810f0182-fdd0-4099-bbcb-c78eae0f96af)

**Comment by knadh** [comment]
I am unable to reproduce this. Tried `https://listmonk.app@TrackLink` and `{{ TrackLink "https://listmonk.app" }}`. Both correctly render and redirect on the public archive page.

Can you share the actual URL that's being rendered on the archive page?

**Comment by jacobholes** [comment]
I apologize for the delayed response, the URL is: http://newsletter.centroidcnc.com:9000/archive/cc368b3e-8217-48f0-814c-0382170bfc27

I'm using @TrackLink for tracking links.

**Comment by jacobholes** [comment]
I see this issue is still closed. I updated to 3.0.0 today and the issue has changed but still remains an issue. Tracked Links now go to a 404 page when clicked. URL is still: http://newsletter.centroidcnc.com:9000/archive/cc368b3e-8217-48f0-814c-0382170bfc27

**Comment by abnogz** [comment]
Hi! I'm having this same issue. I'm using tracked links with @TrackLink appended to the URL, and when clicked on the public archive the response is a 404 error page. 

Here's an example campaign currently published:
https://difusion.cec.es/archive/68950d75-d06d-4e05-ae83-23fd89515939

Currently I'm using version 4.0.1 on a Debian system.
