### ISSUE TITLE
Is there a way to avoid being blocked by uBlock Origin (and maybe other similar)

### ISSUE THREAD

**Issue by sangdth** [knadh/listmonk#1626]
First of all thanks for the great works! I can spawn up an instance and use it with just a few clicks. Totally love the app!

Btw I have a small concern. When I click on the confirmation link (after submitting into a subscribe list), I got blocked by uBO. Of course I know my site so I can confidently press Proceed, but normal users might stop there. Is there any work around?

![Screenshot 2023-12-12 at 23 59 54](https://github.com/knadh/listmonk/assets/1083478/9960aa3b-c294-40c0-baed-c8c3c28b0daf)

Thanks.

**Comment by MaximilianKohler** [comment]
It's blocking `pstmrk.it`. That has nothing to do with listmonk.

> Postmark uses the pstmrk.it domain to deliver a variety of analytics to the users of our email service.
> 
> [Learn more about Postmark](http://postmarkapp.com/)
> 
> [What is pstmrk.it?](https://postmarkapp.com/support/article/1059-what-is-pstmrk-it)
> Made with ♥ at [ActiveCampaign](https://www.activecampaign.com/?utm_source=postmark&utm_medium=referral&utm_campaign=pstmrk_it)

You would need to take it up with Peter Lowe https://pgl.yoyo.org/adservers/

```
# For more information about this list, see: https://pgl.yoyo.org/adservers/
# ----
# last updated:   Fri, 08 Dec 2023 10:16:08 GMT
# entries:        3776
# format:         hosts (hosts -- in hosts file format)
# credits:        Peter Lowe - pgl@yoyo.org - https://pgl.yoyo.org/ - https://twitter.com/pgl
# this URL:       https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext
# Patreon:        https://patreon.com/blocklist
# other formats:  https://pgl.yoyo.org/adservers/formats.php
# policy:         https://pgl.yoyo.org/adservers/policy.php
```

**Comment by sangdth** [comment]
Ah, it's true that I use Postmark. Thanks for detailed explaination. I will contact Postmark support and let's see if they can sort this out.
