### ISSUE TITLE
error fetching lists: missing destination name description in *[]models.List

### ISSUE THREAD

**Issue by alcaldj** [knadh/listmonk#1627]
**Version:**
 - listmonk: [v2.1.0]
 - OS: [Docker Image (latest)]

**Description of the bug and steps to reproduce:**
I get this error on logs when i try to list all "Lists" from darshboard. Lists are not displayed

**Screenshots:**
![image](https://github.com/knadh/listmonk/assets/5969983/af53d616-8391-4100-b801-b5973e418297)

**Comment by knadh** [comment]
That's extremely weird. Is this a fresh installation with no changes? Has the database schema been altered by any chance?
