### ISSUE TITLE
Listmonk logs a lot of errors '503 5.5.0 Sender already specified' and campaign only sent out partially

### ISSUE THREAD

**Issue by sonologic** [knadh/listmonk#1629]
**Version:**
 - listmonk: 2.5.1
 - OS: Docker (listmonk/listmonk:latest) on Debian 10.13

**Description of the bug and steps to reproduce:**
I have a low volume list of about 750 subscribers. Listmonk is configured to send through my sendmail server running on FreeBSD. When sending a campaign, I get a lot of errors of the form:

`2023/12/15 19:20:15 manager.go:398: error sending message in campaign Newsletter 2023-12-15: subscriber 123: 503 5.5.0 Sender already specified`

Last time I sent out a campaign, there were 507 of them. I'm also getting complaints that people or not receiving the newsletter, and looking at the mailserver logs I can see a lot less emails are delivered than claimed by listmonk.
I can't find the error in the maillog, which suggests it's not sendmail generating this error but something inside lismonk.

I'm aware this has been posted before (#1530, and the closed tickets #1192 and #300), but those other issues mention AWS SES. I am not using that, so I thought I'd create a separate ticket. However, it might be the same root cause.

I'm not sure how to debug this.

* Set up listmonk from the docker container
* Configure SMTP server (sendmail on FreeBSD)
* Create list of 750 subscribers
* Create campaign
* Send

**Screenshots:**

**Comment by sonologic** [comment]
I have now created a new list with the 507 subscribers that did not get the newsletter in the first run. Changed the settings to:
* Concurrency: 1
* Message rate: 5
* Max connections: 1
And then resent the campaign to the new list, and that went out without issue it seems.

**Comment by MaximilianKohler** [comment]
>I have now created a new list with the 507 subscribers that did not get the newsletter in the first run

How did you do that?

**Comment by sonologic** [comment]
> > I have now created a new list with the 507 subscribers that did not get the newsletter in the first run
> 
> How did you do that?

Created an empty list, looked up the id from the list in the database (it was 5 in this case).

Then took the log from listmonk and created insert statements to add all those subscribers from the log:

`cat log | cut -d\: -f 6 | sed 's/ subscriber //g' | xargs -irepl echo "insert into subscriber_lists (subscriber_id, list_id, status) values (repl, 5, 'confirmed');" > sql`

And fed that into the database.

**Comment by knadh** [comment]
This should fix it: https://github.com/knadh/listmonk/commit/a6d55d63b16a0e9819eb452b67d0288d2f23c671

**Comment by sonologic** [comment]
Awesome, I'll try and build the docker container with this fix included and use that for my next run. I just sent out a new run with the current latest docker image, and with the settings I mentioned above, and got a lot of these errors again.

**Comment by sonologic** [comment]
Well, managed to build a docker image in a vm with all the latest greatest build dependencies installed, but now listmonk complains about the database not being up to date, yet running `listmonk --upgrade` tells me there is nothing to upgrade.

**Comment by knadh** [comment]
I've just pushed `listmonk/listmonk:v3-rc-2`. Could you try that?

**Comment by MaximilianKohler** [comment]
@knadh I just discovered that this has to do with the `Include List-Unsubscribe header` option! I enabled it for the first time ever, and I got a bunch of the `503 Sender already specified` errors. I sent a campaign to 3k people:
```
2024/01/05 17:57:55 main.go:102: v2.5.1 (a6a2b69 2023-08-15T15:49:28Z, linux/amd64)
2024/01/05 17:57:55 init.go:145: reading config: /etc/listmonk/config.toml
2024/01/05 17:57:55 init.go:273: connecting to db: localhost:5432/listmonk
2024/01/05 17:57:55 init.go:232: loading static files from: /etc/listmonk/static
2024/01/05 17:57:55 init.go:593: media upload provider: filesystem
2024/01/05 17:57:55 init.go:517: loaded email (SMTP) messenger: xxxxxx@email-smtp.us-west-1.amazonaws.com
⇨ http server started on 127.0.0.1:9011
2024/01/06 08:40:00 manager.go:507: start processing campaign (Thanks 2024-01-06 3k)
2024/01/06 08:42:18 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 695968: 501 Invalid RCPT TO address provided
2024/01/06 08:42:18 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 695971: 503 Sender already specified.
2024/01/06 08:42:18 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 695974: 503 Sender already specified.
2024/01/06 08:42:18 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 695976: 503 Sender already specified.
2024/01/06 08:42:18 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 695981: 503 Sender already specified.
2024/01/06 08:42:18 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 695983: 503 Sender already specified.
2024/01/06 08:42:18 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 695986: 503 Sender already specified.
2024/01/06 08:42:18 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 695989: 503 Sender already specified.
2024/01/06 08:42:19 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 695993: 503 Sender already specified.
2024/01/06 08:42:19 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 695996: 503 Sender already specified.
2024/01/06 08:42:19 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 695998: 503 Sender already specified.
2024/01/06 08:42:19 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696002: 503 Sender already specified.
2024/01/06 08:42:19 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696007: 503 Sender already specified.
2024/01/06 08:42:19 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696009: 503 Sender already specified.
2024/01/06 08:42:19 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696014: 503 Sender already specified.
2024/01/06 08:42:19 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696019: 503 Sender already specified.
2024/01/06 08:42:19 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696022: 503 Sender already specified.
2024/01/06 08:42:20 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696025: 503 Sender already specified.
2024/01/06 08:42:20 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696033: 503 Sender already specified.
2024/01/06 08:42:20 manager.go:686: campaign (Thanks 2024-01-06 3k) finished
2024/01/06 08:42:20 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696042: 503 Sender already specified.
2024/01/06 08:42:21 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696047: 503 Sender already specified.
2024/01/06 08:42:21 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696051: 503 Sender already specified.
2024/01/06 08:42:21 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696054: 503 Sender already specified.
2024/01/06 08:42:21 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696055: 503 Sender already specified.
2024/01/06 08:42:21 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696058: 503 Sender already specified.
2024/01/06 08:42:22 manager.go:398: error sending message in campaign Thanks 2024-01-06 3k: subscriber 696060: 503 Sender already specified.
```
Notice how the errors continued after the campaign said it was finished and that there's one `Invalid RCPT TO address provided` error at the start which I've never seen before. I'm using the binary.

**Comment by MaximilianKohler** [comment]
I disabled the `Include List-Unsubscribe header` option and as expected, I did not get those errors again. Can others who are getting this error confirm this?

**Comment by MaximilianKohler** [comment]
Ah, @knadh I may have discovered the issue. I used [the commands to get the IDs from the logs and insert them into a new list](https://github.com/knadh/listmonk/issues/1629#issuecomment-1879822419) and I saw that one of the emails has Chinese characters: `fname.lname.2023騧⮡랬@gmail.com` which may have triggered the `501 Invalid RCPT TO address provided`.

**Comment by MaximilianKohler** [comment]
**It has nothing to do with the  `Include List-Unsubscribe header`. It was a pure coincidence.** It was that I accidentally opened and then saved a UTF-8 file as UTF-7, which corrupted characters and that triggers the `501 Invalid RCPT TO address provided` error, which triggers the other errors.

I will edit my other comments to remove the bad info. The correct info is in my last comment above.

**Comment by zwolf** [comment]
> I've just pushed `listmonk/listmonk:v3-rc-3`. Could you try that?

I am deploying Listmonk with docker and this image made it easy to test the changes, thanks. Using that image (v3.0.0), I've sent out three campaigns via SES: two with 75k subscribers each and one with around 700k. The 503 errors are totally gone and each campaign was successful the first time. The problem seems to be fixed with the smtppool update. Thanks!

**Comment by sonologic** [comment]
> I've just pushed `listmonk/listmonk:v3-rc-3`. Could you try that?

Thanks, I'll give that a go, but I see @zwolf has tried it already and reports all is well. I'm not using SES though, sending out another campaign tomorrow (I only send one out every 2 weeks, so couldn't test earlier). Will use the new docker image and report back!

**Comment by sonologic** [comment]
> > I've just pushed `listmonk/listmonk:v3-rc-3`. Could you try that?
> 
> Thanks, I'll give that a go, but I see @zwolf has tried it already and reports all is well. I'm not using SES though, sending out another campaign tomorrow (I only send one out every 2 weeks, so couldn't test earlier). Will use the new docker image and report back!

Ran another campaign on friday, the errors are indeed gone. I did not receive the message myself, even though I am subscribed to the list, so I need to investigate this further. Maybe this means messages are now silently dropped.

**Comment by knadh** [comment]
That’s concerning. What’s changed is better state handling and connection recycling in SMTP pooling. If there’s any error anywhere, it should definitely be logged. There’s no error suppression.

Please let me know what you find.

**Comment by sonologic** [comment]
> That’s concerning. What’s changed is better state handling and connection recycling in SMTP pooling. If there’s any error anywhere, it should definitely be logged. There’s no error suppression.
> 
> Please let me know what you find.

I will look into it, have to check the logfiles. Might be a while. It might also be something completely unrelated to listmonk of course, email is finicky :)

> @sonologic with Amazon SES we have the ability to see the actual count of emails sent out by Amazon in their dashboard and compare that with what listmonk says it sent. Does your SMTP have that? I used it earlier to verify that the number of errors listmonk reported was the exact amount.

I'm just a one-person outfit using a simple sendmail server, I don't have such an option unfortunately.

**Comment by sonologic** [comment]
> Please let me know what you find.

It looks like the mail was successfully sent out by listmonk, and was put in my imap mailbox. I was, at the time, also doing some heavy cleaning up of my inbox, so my guess is that I deleted it without noticing.

In any case, no cause for concern, seems this is a pebcak.

Again, thanks for fixing the issue!
