### ISSUE TITLE
Is it possible to send via Google Workspace?

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#1637]
Hi,
I have seen tutorials like this to use Google Workspace to send Emails:
https://www.inventiva.global/how-to-set-up-google-workspace-for-smtp-delivery/

This one is german:
https://kinsta.com/de/blog/gmail-smtp-server/

It looks to me that google has some "PostSmtp" API which is no "normal" smtp, but smtp via rest I guess?? I could not find if this is in general possible with listmonk or how much effort it takes.

I am also unsure how many mails/day you are allowed to send, I found multiple definitions, but this google document does not really state a limit.
https://support.google.com/a/answer/81126?hl=de#zippy=%2Canforderungen-an-alle-absender

It would be nice if someone could give me more information about that :-)

**Comment by knadh** [comment]
Directly, no. You can create a [Messenger web service](https://listmonk.app/docs/messengers/) that accepts postbacks from listmonk and posts them to the Workspace API.
