### ISSUE TITLE
Feature Request: allow defining a List-Id header per list

### ISSUE THREAD

**Issue by javierarce** [knadh/listmonk#1643]
I think it would be nice to add functionality for defining a specific [List-Id header](https://www.ietf.org/rfc/rfc2919.txt) for each list. 

At present, it's possible to set the List-Id as a custom SMTP header, but this is applied to all lists, so this approach is only effective for users who manage a single list. Adding this functionality would be especially useful for email services like Gmail or Fastmail, where the List-Id header enables easier filtering of messages from a particular list.

<img width="658" alt="Screenshot 2023-12-26 at 00 26 26" src="https://github.com/knadh/listmonk/assets/4933/2995b19e-5dca-4560-b3fb-60f698a8a926">

**Comment by knadh** [comment]
Hi @javierarce. How would this work? Add a `List-ID` header per public mailing list that is attached to a campaign? Private mailing lists shouldn't be exposed.

**Comment by javierarce** [comment]
Hi, @knadh! The functionality should be campaign-independent and just associated with the list because the goal is to enable the filtering of all messages from a given list.

Reading [the spec](https://www.ietf.org/rfc/rfc2919.txt), I believe this could be implemented as a text field in the list model. This way, users could manually define the identifier using any of the syntaxes outlined below:

```
   While it is perfectly acceptable for a list identifier to be
   completely independent of the domain name of the host machine
   servicing the mailing list, the owner of a mailing list MUST NOT
   generate list identifiers in any domain namespace for which they do
   not have authority.  For example, a mailing list hosting service may
   choose to assign list identifiers in their own domain based
   namespace, or they may allow their clients (the list owners) to
   provide list identifiers in a namespace for which the owner has
   authority.

   If the owner of the list does not have the authority to create a list
   identifier in a domain-based namespace, they may create unmanaged
   list identifiers in the special unmanaged domain "localhost".  This
   would apply to personal users, or users unable to afford domain name
   registration fees.

   The syntax for a list identifier in ABNF [RFC2234] follows:

   list-id = list-label "." list-id-namespace

   list-label = dot-atom-text

   list-id-namespace = domain-name / unmanaged-list-id-namespace

   unmanaged-list-id-namespace    = "localhost"

   domain-name = dot-atom-text

   Where:

       dot-atom-text is defined in [DRUMS]

       "localhost" is a reserved domain name is defined in [RFC2606]

   In addition, a list identifier (list-id) MUST NOT be longer than 255
   octets in length, for future compatibility.  It should be noted that
   "localhost" is not valid for the domain-name rule.
```

**Comment by knadh** [comment]
Missed responding to this. It's possible to set custom SMTP headers per campaign. I think this is the ideal approach here that gives fine grained control as campaigns can have a mix of private lists whose existence would have to be kept private.
