### ISSUE TITLE
Feature request: Be able to send hyperpersonalised campaigns based on user's attributes (and not based on lists as it is now)

### ISSUE THREAD

**Issue by roperi** [knadh/listmonk#1645]
**Is your feature request related to a problem? Please describe.**
It is rather laborious to send an email campaign per user email.   

**Describe the solution you'd like**
It would be great to be able to dynamically generate email content based on user's attributes, leveraging ChatGPT or your preferred LLM GPT. 

Say none of my 1000 subscribers have the same 10 attributes they all posses but a different combination of many of them.  I want to blast a campaign to all of them based on each of their unique attributes.

I'd like to know if this is even a thing among listmonk's core developers. Or if there's a branch working on a similar feature. Or if is feasible (to start working on this). Feels to me campaiging in bulk based on several common user's attributes is kind of antiquated. I think we should be able -especially from 2024- to be able to launch hyperpersonalised campaigns in bulk.

**Comment by knadh** [comment]
Hi @roperi. There are no plans to integrate any content generation tools to listmonk (AI or otherwise). It's goal is to remain a content-agnostic newsletter tool. You can always use the APIs to add any content you like.
