### ISSUE TITLE
Setting "Preconfirm subscription" is ignored

### ISSUE THREAD

**Issue by Wonko52** [knadh/listmonk#1646]
**Version:**
 - listmonk: 2.5.1
 - OS: Docker

Under Subscribers -> Managed List, all subscribers should be added to a new list. "Preconfirm Condition" is set. If some subscribers are selected, this also works. However, if "Select all x" is used before, the subscribers are added to the list but are not confirmed.

**Comment by shenderaj9021** [comment]
Hey I want to work on this bug. Can you assign this issue to me
