### ISSUE TITLE
Cannot Change Default Outgoing Email in Listmonk General Settings

### ISSUE THREAD

**Issue by PackMeister** [knadh/listmonk#1649]
**Version:**
 - listmonk: 2.5.1
 - OS: Debian 12.4

**Description of the bug and steps to reproduce:**
Cannot change and save default email address in general settings 
from: noreply@listmonk.14servers.net
    to: admin@riversidefolksongsociety.org

When I try to save with new address address box returns with red borders and a 'manage password' dropdown appears.

<img width="1147" alt="LIstmonk Screenshot-Default From Email" src="https://github.com/knadh/listmonk/assets/35346304/65289881-8200-42e2-b2fc-579a745145e3">

**Comment by MaximilianKohler** [comment]
If you mouse over it it tells you that you need to match the format. `name <email@domain.com>`

**Comment by knadh** [comment]
The upcoming version won't mandate the `name` bit in the e-mail either. Changed it recently here: https://github.com/knadh/listmonk/commit/2feb1b0fb8c72ba33ef693bc2ec41ee203557ee9
