### ISSUE TITLE
Internal Server Error on static-dir command

### ISSUE THREAD

**Issue by rameshdon1** [knadh/listmonk#1651]
![image](https://github.com/knadh/listmonk/assets/139542777/10e58a7e-2e28-4661-a904-60d98cc7cd85)
Here is my app service inside docker compose file, when I add support for static templating, I get this ___{ "message": "Internal Server Error"}___ on UI
Static templating files are copied exactly from this main repo.
![image](https://github.com/knadh/listmonk/assets/139542777/cefbbf95-2e49-4703-b5c1-f9068b3ffa50)

When i manually go to, "mydomain.com/admin/" then normal dashboard is opening
![image](https://github.com/knadh/listmonk/assets/139542777/2a7ba8da-9931-45f1-a563-e50775a276a1)

Am i doing anything wrong here?
Here is my full docker compose file,

`    
version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  ports:
    - "80:80"
  networks:
    - listmonk
  environment:
    - TZ=Etc/EST

x-db-defaults: &db-defaults
  image: postgres:13-alpine
  ports:
    - "9432:5432"
  networks:
    - listmonk
  environment:
    - POSTGRES_PASSWORD=samyogdb
    - POSTGRES_USER=listmonk
    - POSTGRES_DB=listmonk
  restart: unless-stopped
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U listmonk" ]
    interval: 10s
    timeout: 5s
    retries: 6

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data
      - ./db_backups:/db_backups

  app:
    <<: *app-defaults
    container_name: listmonk_app
    depends_on:
      - db
    command: "./listmonk --static-dir=/listmonk/static"
    volumes:
      - ./config.toml:/listmonk/config.toml
      - ./uploads:/listmonk/uploads
      - ./static:/listmonk/static

networks:
  listmonk:

volumes:
  listmonk-data:

`

**Comment by rameshdon1** [comment]
any update @MaximilianKohler ? I am waiting for your reply.

**Comment by knadh** [comment]
Please check the app's docker logs. You must've have a syntax error in your custom static templates.
