### ISSUE TITLE
Is there a DEBUG logging level? Dealing with lots of "AxiosError: Network Error"

### ISSUE THREAD

**Issue by TheDanHealy** [knadh/listmonk#1653]
As the title says, is there a DEBUG logging level I can enable? I'm often receiving "AxiosError: Network Error" on the web app after sitting on a page for too long (like +30 seconds) and then clicking "Save". For example, when adding a new list, if I click "Save" after having the pop-up modal open for too long, I receive this error. There's no errors in the DB or APP logs.

I'm using version 2.5.1, deployed with Docker. I also run an Nginx reverse proxy in front of the site.

I'm seeing random instances of "⇨ http server started on [::]:9000" in the APP logs, but no indication about why it would have restarted. The container didn't restart either during that time.

**Comment by knadh** [comment]
That sounds like a network error indeed, where the request never hits listmonk. Please inspect the request in your browser's network inspector. Could it a browser plugin that's blocking the request somehow?

**Comment by knadh** [comment]
> I'm seeing random instances of "⇨ http server started on [::]:9000" in the APP logs, but no indication about why it would have restarted. 

Changing any settings causes the app to reload.

**Comment by TheDanHealy** [comment]
> Could it a browser plugin that's blocking the request somehow?

Ah, that's probably what it is.
