### ISSUE TITLE
Notification Usage for a status page

### ISSUE THREAD

**Issue by jchomat** [knadh/listmonk#1654]
Hey @knadh ,
I am looking for a notification system that can be use to update users about status changes on a website availability by example. Basic needs are to send a mail to a dynamic list where interested users could subscribe.

We should be able to launch these mail campaign with a simple webhook call from our status page system to notify subscribed users.

I see two options :
- Updating the /api/tx to add a listid parameter for transactionnal email instead using list of subscriber_email.
- Be able to launch a preset campaign based on a list multiple time

Do you think these kind of usage can be integrated in listmonk as a feature ?

**Comment by knadh** [comment]
`/api/tx` isn't ideal for groups. It's meant for individual transactional e-mails.

When there is an incident that you want to publish, you can:
- Use the `POST /campaigns/` API to create a specific campaign for the incident with its details.
- The campaign_id comes in the response to this. Use it immediately to trigger the campaign with `PUT /api/campaigns/{campaign_id}/status` (JSON params  `status=running`)

Ref: https://listmonk.app/docs/apis/campaigns/#put-apicampaignscampaign_idstatus

**Comment by jchomat** [comment]
Thanks for you answer, 
we need to recreate the campaign each time because the list of subscribers used will not be updated ?

Templates and campaign configuration will not change, just our subscriber list who may been updated, if we preset our campaign based on a list and always trigger the same one it could match our use case too if the list is dynamically refresh at each campaign triggering.

**Comment by knadh** [comment]
Yes, you have to create a separate campaign and trigger it. It's also ideal to create a separate campaign so that the context/contents of the particular incident are preserved. You can always delete old campaigns after a while.

**Comment by jchomat** [comment]
👍 Thanks
