### ISSUE TITLE
What is Google's requirement for the `unsubscribe` button.

### ISSUE THREAD

**Issue by porterporter** [knadh/listmonk#1655]
When sending emails, only emails that use mailto: as an unsubscribe method show the big unsubscribe button. I don't want to use mailto: because that means complicated inbox stuff. What makes the unsubscribe button appear using the List-Unsubscribe-Post=One-Click and List-Unsubscribe=listmonk-url/unsubscribe show up

Email from random list I am subscribed to (uses mailto:)
![ishare-1704480571](https://github.com/knadh/listmonk/assets/57007161/c0971a8d-62df-4e69-b5da-fda4a4d3e9c7)

Email from me (uses listmonk)
![ishare-1704480599](https://github.com/knadh/listmonk/assets/57007161/b2757845-6cf6-45d0-8526-af82ebe6cb7f)

**Comment by MaximilianKohler** [comment]
In my experience, I saw it randomly show up. But it should be the `list-unsubscribe header ` which you can enable in listmonk's settings. https://www.paved.com/blog/everything-you-need-to-know-about-the-gmail-unsubscribe-button/

However, I just tried that and it didn't work for me either. There was a problem with it not showing with test messages https://github.com/knadh/listmonk/issues/360, but I did a normal campaign as well and it didn't show.

I had list-unsubscribe headers disabled. I sent two test messages and the unsubscribe didn't show (expected), then I enabled the option and sent another test and it still didn't show. Then I sent a normal campaign and it still didn't show.

I do see the two lines in the raw message that was delivered (and not in the previous two):
```
List-Unsubscribe: <https://website.com/subscription/22335xxx5328ffc7d8/edc4d2xxxx428f3>
To: xxx@gmail.com
Mime-Version: 1.0
X-Listmonk-Campaign: 2233xxx328ffc7d8
X-Listmonk-Subscriber: edc4d2xxxf71428f3
List-Unsubscribe-Post: List-Unsubscribe=One-Click
```

I looked at another email I received from the Effective Altruism Forum and it has the "unsubscribe" at the top of gmail yet it doesn't have the `list-unsubscribe` headers. Same for an email from nextdoor.com.

**Comment by knadh** [comment]
I just sent a test e-mail from a test listmonk instance and GMail renders the "Unsubscribe" link.

![image](https://github.com/knadh/listmonk/assets/547147/ee76287f-88d1-41b1-845b-ffecf0ed2f72)

**Comment by MaximilianKohler** [comment]
>I just sent a test e-mail from a test listmonk instance and GMail renders the "Unsubscribe" link.

That's lacking a lot of relevant context/info from my comment. IE: were you using listmonk's `list-unsubscribe header` option? Did the email land in Gmail’s Promotions, Social, or Forums inboxes? What is the reputation of the sender? Etc...

**Comment by knadh** [comment]
- Yes, list unsub header is on. Without that, G-mail wouldn't know how to unsub.
- E-mail landed in the inbox.
- I used my personal G-mail SMTP (app password) and sent the test campaign to another G-mail account.

**Comment by MaximilianKohler** [comment]
>Without that, G-mail wouldn't know how to unsub

Not true, see my first comment.

The other two points seem to confirm the randomness of it...

**Comment by porterporter** [comment]
interesting, i guess i'll just let it be for now and hope it shows up but that's super weird on google's end

**Comment by michaelPotter** [comment]
Just chiming in for other folks who might come across this ... It seems google requires a certain level of sender reputation to show the button. 

https://support.google.com/mail/thread/49653586?hl=en&msgid=49801705

Anecdotally, we couldn't get the button to render with our "testing" domain that rarely gets used, but it seems to show up regularly with our main domain.
