### ISSUE TITLE
echo http URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed | golang error

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1656]
**Version:**
 - listmonk: [v2.5.1 binary]
 - OS: [CentOS 7]

Per https://listmonk.app/docs/configuration/#binary, I am using this line in my service file to create a persistent log: 
`ExecStart=/bin/bash -ce "exec /usr/bin/listmonk --config /etc/listmonk/config.toml --static-dir /etc/listmonk/static >>/etc/listmonk/listmonk.log 2>&1"`

I see one bunch of around 50 lines of these errors that didn't show up in the listmonk UI/logs, only the log file.
```
2023/12/31 08:42:26 manager.go:686: campaign (Thanks 2023-12-31 3k) finished
echo: http: URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed; see golang.org/issue/25192
echo: http: URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed; see golang.org/issue/25192
echo: http: URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed; see golang.org/issue/25192
echo: http: URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed; see golang.org/issue/25192
2024/01/01 08:40:04 manager.go:507: start processing campaign (Thanks 2024-01-01 3k)
```

I looked at the golang issue but I don't understand it. My log file dates back to 2023/12/24, and I've been sending 3k emails per day.

Unlike most of the other log entries, these don't have a timestamp, but I included the before and after ones that do.

**Comment by knadh** [comment]
This is coming from the `echo` HTTP server lib that listmonk uses.

- Do you have any API calls that you're making internally that may have a semicolon?
- Otherwise, this seems like automated bots sending malformed requests to check for vulnerabilities. This can be ignored.

**Comment by MaximilianKohler** [comment]
>Do you have any API calls that you're making internally that may have a semicolon?

I have no idea what this is, so I'm not doing it intentionally.
