### ISSUE TITLE
Footer spacing -- an extra space is added after the links

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1660]
**Version:**
 - listmonk: [eg: v2.5.1]
 - OS: [CentOS 7]

**Description of the bug and steps to reproduce:**
I added text after the links in the footer and an extra space is added.
```
    <div class="footer" style="text-align: center;font-size: 16px;color: #888;">
        <p>
        <a href="{{ UnsubscribeURL }}" style="color: #888;">{{ L.T "email.unsub" }}</a>, test.
        </p>
        <div style="text-align: center;font-size: 12px;color: #888;">	
	<p>Powered by <a href="https://listmonk.app" target="_blank" style="color: #888;">listmonk</a>, a free and open source newsletter and mailing list manager.</p>
	</div>
    </div>
    <div class="gutter" style="padding: 10px;">&nbsp;{{ TrackView }}</div>
```

**Screenshots:**
![Screenshot 2024-01-09 145410](https://github.com/knadh/listmonk/assets/3606996/65f3ec28-ff21-4c24-9fc9-92d3355b41af)
![Screenshot 2024-01-09 145643](https://github.com/knadh/listmonk/assets/3606996/69b1d0ed-ec49-4c58-807c-3dc7c7550584)
![Screenshot 2024-01-09 145955](https://github.com/knadh/listmonk/assets/3606996/b1f825fb-70ff-4d83-b072-a638208d9729)

**Comment by knadh** [comment]
Not sure. You'll have to use the browser element inspector and figure out which tag/style is causing this, and adjust the CSS accordingly. It could just be the default spacing of <p> tags.

**Comment by MaximilianKohler** [comment]
I found it. It's this:
```
            }
                .footer a {
                    color: #888;
                    margin-right: 5px;
                }
```
I suggest that should be set to 0 in the default templates. Would you disagree?

**Comment by knadh** [comment]
That's there to separate multiple nav-like links that may be added to the footer. Example: `Unsubscribe   Homepage   Contact us` etc. That's fine for a default setting. Since you're adding a sentence and not using a nav-like layout, you can edit the style for your template accordingly.

**Comment by MaximilianKohler** [comment]
Couldn't they just insert some spaces?
```
<a href="{{ MessageURL }}" style="color: #888;">{{ L.T "email.viewInBrowser" }}</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://listmonk.app" target="_blank" style="color: #888;">Homepage</a>&nbsp;&nbsp;&nbsp;&nbsp;Contact Us
```
![andnbsp](https://github.com/knadh/listmonk/assets/3606996/d0833ca3-497a-4f06-a21f-6a2fea501e6e)

Maybe one of the default templates could use the code above?
