### ISSUE TITLE
Plug to existing pg db

### ISSUE THREAD

**Issue by flutter-painter** [knadh/listmonk#1661]
Such a cool project !
I would rather use it on top of my db to avoid manual sync across business db and listmonk db. 
Has this already been tried/requested ? 
Sorry if this was already answered, I did search for it.

**Comment by knadh** [comment]
Thanks @flutter-painter. Unfortunately, that's not possible. listmonk requires it's own database with it's own schema (you can create a new database on an existing Postgres server just fine). Any external business DB, you will have to sync it with listmonk using APIs are directly writing to the database.

**Comment by flutter-painter** [comment]
Thank you for lightning speed reply.
OK, 
Else What if I moved business db into a dedicated schema in listmonk db ? 
Would allow direct upsert of new subscribers for example. Could it go wrong ?

**Comment by knadh** [comment]
It's possible, but you have to be very careful mixing tables/schemas with other tables. I wouldn't recommend it though as listmonk's schema can change over versions.
