### ISSUE TITLE
Access Individual Tracking setting in template

### ISSUE THREAD

**Issue by sp1r1t** [knadh/listmonk#1663]
Is it possible to access the setting of individual tracking from the template?

I imagine this in the style as it is done for e.g. AllowPreferences.

`
{{ if .Data.AllowPreferences }}
`

I would like this to adapt the subscribe disclaimer in accordance to be compliant with GDPR.

**Comment by sp1r1t** [comment]
I am not proficient in Go. From the code it looked to me as if `{{ if .Data.IndividualTracking }}` should work. But I'm getting the following error:

> handlers.go:62: template: subscription.html:27:14: executing "optin" at <.Data.IndividualTracking>: can't evaluate field IndividualTracking in type interface {}

**Comment by knadh** [comment]
`IndividualTracking` is not exposed to the template currently. I'll add it in a patch shortly and make it available in the next release (which should be out next week).
