### ISSUE TITLE
Accessing file storage images on html templates

### ISSUE THREAD

**Issue by dhaneshmarch** [knadh/listmonk#1665]
Have been trying to shift whole mailing workflow from postmark mailing server scripts on flask to listmonk. 

As there is functionality for uploading images as media. Is there any way to access these images using some kind of literal in go.

I am aware of accessing it through direct server url/ s3 url. But not sure if there is some convention followed here.

**Comment by knadh** [comment]
Ah, there isn't a way to programmatically access images currently.
