### ISSUE TITLE
I built a WordPress plugin to connect to listmonk for people without programming skills 

### ISSUE THREAD

**Issue by post-duif** [knadh/listmonk#1667]
Hi all, I have built a WordPress plugin that makes it possible to add people to a mailing list through a form on your WordPress website or when they consent to being added on the WooCommerce checkout.

The plugin has a settings page where you can input your listmonk server URL, username, password and the list ID you want to subscribe new entries to. No programming knowledge is required, it should be plug and play.

I have been using it myself for over a year and it works flawlessly for my use case. Hopefully some of you can benefit from it too! Perhaps it can even be added to the docs?

Please note you currently need the (free) WPForms plugin to build a simple newsletter form that my plugin uses to send the data to listmonk through its API. How to do this is explained in the README and settings page of the plugin. WooCommerce is supported without the need of other plugins. 

I couldn't find a similar plugin or instructions online anywhere online, so I hope this is useful to people. Feature requests and bug reports can be submitted to the repository. It will be available in the official WordPress plugin directory but it's awaiting approval. 

Repository link: https://github.com/post-duif/integration-listmonk-wordpress-plugin

**Comment by post-duif** [comment]
I updated the plugin so that a custom _checkout field editor plugin_ isn't needed anymore! It's now included in the plugin itself, including the ability to edit the text displayed at checkout to inform users of what they can subscribe to. You can change this in the settings. See release 1.1.

**Comment by post-duif** [comment]
@knadh have you seen this and do you think we could add this to the docs or perhaps to https://listmonk.app/docs/apis/apis/? I think users that are less tech savvy could benefit from this easy integration into their WordPress/WooCommerce setups.

**Comment by knadh** [comment]
https://listmonk.app/docs/apis/apis/

Hi @post-duif . We can add a new section under APIs, perhaps "SDKs and libs" and list this there.

**Comment by post-duif** [comment]
> https://listmonk.app/docs/apis/apis/
> 
> Hi @post-duif . We can add a new section under APIs, perhaps "SDKs and libs" and list this there.

That sounds nice! The plugin is currently undergoing review for the WordPress plugin directory so then that can also be linked.

**Comment by post-duif** [comment]
Submitted a PR for this: https://github.com/knadh/listmonk/pull/1723.
