### ISSUE TITLE
AWS SES bounce processing docs incomplete

### ISSUE THREAD

**Issue by LukeLambert** [knadh/listmonk#1668]
While setting up bounce processing on a new instance, I noticed that the SES docs could be improved. Specifically, the link to the Mautic docs is no longer relevant as their docs have changed. I've rewritten the complete steps below. I could submit a PR, but I'm not sure where in the docs this would live. Alternatively, if the docs were reorganized into provider-specific instructions, I'd be happy to expand this to cover all aspects of using SES with listmonk, including SMTP and IAM.

### Bounce processing with AWS SES

1. In listmonk, click "Bounces" and use the following settings:
    - Enable bounce processing: `Enabled`
        - Complaint: `1` (with `Blocklist` or `Delete`)
    - Enable bounce webhooks: `Enabled`
    - Enable SES: `Enabled`
2. In the AWS console, go to [Simple Notification Service](https://console.aws.amazon.com/sns/) and create a new topic with the following settings:
    - Type: `Standard`
    - Name: `ses-bounces` (or any other name)
3. Once created, click "Create subscription" and use the following settings:
    - Protocol: `HTTPS`
    - Endpoint: `https://<your-listmonk-domain>/webhooks/service/ses`
    - Enable raw message delivery: `Disabled` (unchecked)
4. If successful, the subscription should say "Confirmed" after a page refresh. If not, your endpoint may be incorrect or not publicly accessible.
5. In the AWS console, go to [Simple Email Service](https://console.aws.amazon.com/ses/) and click "Verified identities" in the left sidebar.
6. Click your verified domain and go to the "Notifications" tab.
7. Next to "Feedback notifications", click "Edit".
8. For "Bounce feedback" and "Complaint feedback", select the SNS topic you created earlier.
9. Check "Include original email headers" for both and save changes.
10. You can test that bounce processing is working with [SES simulator addresses](https://docs.aws.amazon.com/ses/latest/dg/send-an-email-from-console.html#send-email-simulator). Add them as subscribers, send them campaign previews, and observe that the appropriate action was taken after the configured bounce threshold was reached.
    - Success: `success@simulator.amazonses.com`
    - Bounce: `bounce@simulator.amazonses.com`
    - Auto-reply: `ooto@simulator.amazonses.com`
    - Complaint: `complaint@simulator.amazonses.com`
    - Suppression list: `suppressionlist@simulator.amazonses.com`
11. Once bounce processing is working, you can safely disable "Email feedback forwarding" under the "Notifications" tab of your verified domain in SES.

**Comment by MaximilianKohler** [comment]
IMO, "delete" should not be used for complaints. If you delete them and they're added back again and you send them another email that will hurt your sender reputation. Since hard bounces may be due to emails that don't currently exist, but may exist in the future, it might make sense to use `delete` for those, but I use `blocklist` for all 3 options. Maybe purging hard bounces once a year may be reasonable and an option for that could be added to `/admin/settings/maintenance`.

Here's an archived version if needed https://web.archive.org/web/20230521055826/https://docs.mautic.org/en/channels/emails/bounce-management#amazon-webhook

Maybe SES can be taken out of that grid https://listmonk.app/docs/bounces/#external-webhooks and an `Amazon SES` subheading can be made under `external webhooks`, and you could copy-paste your text there. 

Otherwise, the `Mautic steps` link could be replaced with the archived version or the link to this issue. Not sure which knadh would prefer.

**Comment by LukeLambert** [comment]
I agree about complaints. The [current defaults](https://github.com/knadh/listmonk/blob/0935e9c136b24aa5a9b023a951d8b4b571b3d784/schema.sql#L255) are `{"count": 2, "action": "delete"}`, and I wasn't sure if there was a reason for that. Count should certainly be `1` for according to SES docs.

I worked from the old Mautic docs, which are also available in [their repo](https://github.com/mautic/user-documentation/blob/4d7700daff7e4ef4d4f754a6a612a8b06f5affa4/docs/channels/emails.rst#amazon-ses-webhook), but the AWS console has changed quite a bit, so the directions vary slightly and the screenshots are out of date.

**Comment by knadh** [comment]
> I could submit a PR, but I'm not sure where in the docs this would live.

We can add them as sub-sections here https://listmonk.app/docs/bounces/ or add sub-pages under /bounces.

**Comment by Jhchavezr** [comment]
Hey guys, so I set up the listmonk app using the following tutorial.
https://rameerez.com/free-mailchimp-alternative-email-marketing-service/#listmonk-tutorial

But I haven't been able to setup the bouncing with SES and SNS with the documentation.

I have added the webook to SNS, but can't get confirmation.
![image](https://github.com/knadh/listmonk/assets/69514727/353ba53e-5834-490a-8d6b-7a1d61e5f3e6)

Then I followed Lukes recomendation, but still won't work. 
https://github.com/knadh/listmonk/issues/1668#issue-2080438101

I get asked for a token, but I don't know where to get it or how to add it to the url.
![image](https://github.com/knadh/listmonk/assets/69514727/848da6fa-da08-4ff2-bb4e-f9d767155685)

Thanks for the patience and follow up.

**Comment by LukeLambert** [comment]
Have you configured feedback notifications in the SES admin? That would be steps 5-8 from [the docs](https://listmonk.app/docs/bounces/#amazon-simple-email-service-ses) and should look something like this:

![SES Admin](https://github.com/knadh/listmonk/assets/3031207/2e6bdcbc-a513-4157-9782-702fa6f29d69)

**Comment by Jhchavezr** [comment]
Got it working. Thanks a lot for the follow up.

![image](https://github.com/knadh/listmonk/assets/69514727/d6a25c20-82b8-4d87-bfc8-babaab852018)

Documentation should be updated with lukes comment process.

https://github.com/knadh/listmonk/issues/1668#issue-2080438101

Have a great  day!

**Comment by MaximilianKohler** [comment]
It's already there https://listmonk.app/docs/bounces/#amazon-simple-email-service-ses.

**Comment by jiimmyy1** [comment]
Hi! I'm trying to configure SNS for bounces. Which URLs need to be accesible?

**Comment by LukeLambert** [comment]
If you're using an auth proxy instead of the built-in authentication, you can find the [list of public endpoints](https://listmonk.app/docs/configuration/#http-routes) in the docs. Specifically, SES will POST to `https://<your-listmonk-domain>/webhooks/service/ses`.

**Comment by jiimmyy1** [comment]
/ses is already public. No change from SNS, still waiting for confirmation...
