### ISSUE TITLE
Removing tags when editing lists fails

### ISSUE THREAD

**Issue by atomtigerzoo** [knadh/listmonk#167]
When editing a list, like the two default lists on new installs, and trying to remove the tags inside the modal window, it will fail. The tag is still there afterwards.

Steps to reproduce:
- download latest release (v0.6.2-alpha)
- install and run
- edit one of the two lists and remove the tag
- save
- tag is still there

**Comment by knadh** [comment]
Thanks @atomtigerzoo. Will fix this in the upcoming version.

**Comment by knadh** [comment]
Done in [v0.7.0](https://github.com/knadh/listmonk/releases/tag/v0.7.0-alpha).
