### ISSUE TITLE
Feature Request: Bounce processing for Zoho Mail

### ISSUE THREAD

**Issue by tan-yong-sheng** [knadh/listmonk#1670]
**Is your feature request related to a problem? Please describe.**
I found that this listmonk is awesome to send bulk email easily. However, when I would like to configure bounce management for Zoho mail. It seems quite hard.

Thus, I would like to ask if there is any way to manage bounced emails in Zoho via listmonk easily. It possible, the same applies to gmail as well.

**Describe the solution you'd like**
When we send email via Zoho mail's or Gmail's SMTP, listmonk retrieve the bounced email list and take action against them (e.g., unsubscribe, blocklist).

**Comment by tan-yong-sheng** [comment]
still investigating, but suspect it's because Zoho mail stripped off my email header, as I don't see "X-Listmonk-Subscriber" in my email header.

Reference case:
1. https://github.com/knadh/listmonk/issues/1229
2. https://github.com/knadh/listmonk/issues/1162

Still checking if I got any ways to solve this issue.

**Comment by tan-yong-sheng** [comment]
Ok, I switched to the namecheap privatemail and the bounce processing works. If so, I will choose to use namecheap privatemail instead.

**Comment by MaximilianKohler** [comment]
I switched from namecheap privatemail to this free option:

Cloudflare + brevo (300/day) or mailjet (200/day, 6k/mo) https://www.youtube.com/watch?v=nNGcvz1Sc_8 

There's also gmail + forwardemail.net https://www.youtube.com/watch?v=0fbUMJYvteQ.

**Comment by tan-yong-sheng** [comment]
> I switched from namecheap privatemail to this free option:
> 
> Cloudflare + brevo (300/day) or mailjet (200/day, 6k/mo) https://www.youtube.com/watch?v=nNGcvz1Sc_8
> 
> There's also gmail + forwardemail.net https://www.youtube.com/watch?v=0fbUMJYvteQ.


Thanks so much for the suggestion. Sorry as it's not directly related to listmonk...

Just that I faced one problem when I tried to add an alternative email, as guided in https://www.youtube.com/watch?v=nNGcvz1Sc_8, I couldn't receive the verification email from no-reply@accounts.google.com to verify that alternative email.

The error code in Cloudflare:
![image](https://github.com/knadh/listmonk/assets/64836390/e14aa0d5-6de8-4323-8271-ba70f732a574)

![image](https://github.com/knadh/listmonk/assets/64836390/34dc132b-fb68-4fba-8b0b-dd29a507c575)

**Comment by MaximilianKohler** [comment]
Interesting. No, I didn't experience that, but gmail is implementing new guidelines. I would check that google support link.

**Comment by tan-yong-sheng** [comment]
I see, thanks

**Comment by MaximilianKohler** [comment]
https://www.ecosia.org/search?q=gmail%20UnsolicitedRateLimitError

**Comment by tan-yong-sheng** [comment]
Thanks for the update. 

After 1 hour, this problem seems solved aldy... I think this problem is mainly because I just switch ISP from Zoho to Gmail and in a very short time spam.

Thanks so much @MaximilianKohler

**Comment by tan-yong-sheng** [comment]
Just documenting my progress in using Brevo & Cloudflare to set up a free custom domain email.

It's working well for sending and receiving emails, but I've encountered a problem, and I'm not sure why.

Here's the story:
- I've set up two custom domain emails from two different domains.
- I attempted to use one of them to send an email to the other domain email.
- However, I didn't receive the email from that domain.
- Upon checking Cloudflare email routing, I was surprised to find that Cloudflare didn't capture the email sent from my other domain email (as attached below)
- I can confirm that Brevo SMTP is working properly when sending to other common email addresses (like name@gmail.com). I suspect there might be an issue with Cloudflare email routing when setting up two different domain emails in one account and allowing them to send and receive each other's emails. However, I haven't yet identified why this problem occurs.

![image](https://github.com/knadh/listmonk/assets/64836390/75e4fdd1-6f5b-461e-9459-9330986f1bda)

**Comment by tan-yong-sheng** [comment]
What I did is that I've deleted all previously created Zoho accounts.

And now, I can receive the email from the other domain. But, the emails are showing in all mail, and are not showing up in any tab like Primary inbox or Promotion inbox 🤣

Upon checking Cloudflare email routing, it seems like Cloudflare still didn't capture the email sent from my other domain email (as attached above)....
