### ISSUE TITLE
Where find the content in {{ template "content" . }}

### ISSUE THREAD

**Issue by ArabianCat** [knadh/listmonk#1672]
Hello.
I search to create a template in listmonk, but I don't find the content for modify it.
Can you help me to find it ?
Thanks you.
Cordially,

**Comment by knadh** [comment]
- You can create and manage templates in Admin -> Campaigns -> Templates.
- You write the content in Admin -> Campaigns by creating a new campaign and selecting a template that you created previously.

**Comment by ArabianCat** [comment]
Thanks you for your answer.
I know that, I just question where modify the `{{ template "content" . }}` because I dont would like the text below.
![image](https://github.com/knadh/listmonk/assets/102919110/cdeb371f-5940-4f5d-bf66-6de6cb5865a1)

**Comment by knadh** [comment]
That's just dummy content that shows in the preview. Your actual campaign will not have this.

**Comment by ArabianCat** [comment]
But I've to insert `{{ template "content" . }}` ?
And I cannot modify the content ?

Sorry I'm not a genius in html.

**Comment by knadh** [comment]
Yes, you have to insert. That's the placeholder where your actual campaign content is inserted.

**Comment by ArabianCat** [comment]
Ok I'm starting to understand.
How I modify this content in the template content ?

**Comment by ArabianCat** [comment]
Oh I understand it's ok !
Thanks you !
Have a good day !
