### ISSUE TITLE
Feature Request - Ability to view subscribers to each list

### ISSUE THREAD

**Issue by PaulMcF1987** [knadh/listmonk#1674]
I am using Listmonk more as a suppliers mailing list. If I have jobs to be quoted, it is easy to go onto listmonk, type up one email and send to multiple recipients.

The problem, though... I have hundreds of suppliers....
I can go through each of my suppliers and see which list I have assigned them to but that would take forever.

If there was an option when I view the lists, to also see who has been added to each list, this would make things far easier as I would then have an idea as to who has potentially been missed from the list.
If I need to look through all suppliers it will take an age.

Im hoping I have described this well enough, im hoping that it should be a pretty basic request.
If you have any questions, please ask

**Comment by tan-yong-sheng** [comment]
Upvote it. Another feature I wish is the ability to filter out those who doesn't opened my emails... Hope there is predefined option (or postgresjb query) to let us select those people in that list

**Comment by MaximilianKohler** [comment]
@PaulMcF1987 I don't really understand your post. Screenshots would help. But the next listmonk release will have the functionality to view and export subscribed/unsubscribed.

@tan-yong-sheng there are threads about that: 
* https://github.com/knadh/listmonk/issues/1107
* https://github.com/knadh/listmonk/issues/1337

It's not really advisable for multiple reasons:
1. https://github.com/knadh/listmonk/issues/1025
2. Opens aren't detected if the recipient has disabled loading of external images.

**Comment by mikeckennedy** [comment]
+1 for "All subscribers" filtered by list.

**Comment by MaximilianKohler** [comment]
@mikeckennedy ?? Why not https://demo.listmonk.app/admin/lists ?

**Comment by mikeckennedy** [comment]
Because I missed that the numbers of subscribers there clickable. Thanks! And thanks for working on listmonk.

**Comment by tan-yong-sheng** [comment]
I see, I missed it as well

**Comment by MaximilianKohler** [comment]
>Just a suggestion, perhaps it's better to change "list name"'s link to navigate the list of subscribers? To me, it will be more intuitive

I agree. There's already an `edit` button on the left.

**Comment by PaulMcF1987** [comment]
I think I have found what I was looking for, not sure if it has been released in an update or if it has been there the whole time.

**Comment by knadh** [comment]
> I think I have found what I was looking for, not sure if it has been released in an update or if it has been there the whole time.

The subscriber count leading to list -> subscribers has been there from the beginning. Will add a small `View` link underneath the subscriber count to make this obvious.
