### ISSUE TITLE
AB Testing

### ISSUE THREAD

**Issue by samyogdhital** [knadh/listmonk#1675]
I am trying to do AB testing to my email list subscribers. Is there any way to that other than making new list and adding users to that manually?

**Comment by knadh** [comment]
Don't think so, @samyogdhital. listmonk is designed to be a list/newsletter manager. It doesn't have any marketing-specific features.

**Comment by christophcemper** [comment]
I would like to add the need/requirement for at least trivial A/B testing.

If you have a list of over 2 million contacts it makes a huge difference how well your email performs.

And *everything* about ListMonk is (Email) Marketing, so I don't even follow the statement "designed to be a list/newsletter manager". What should even mean? It's a bulk emaililing software, and by it's very nature that's one of the oldest marketing functions :) 

How A/B testing should work minimally - for at least 2 subject lines:

1/ Enable A/B Test (and maybe add number of variations)
2/ Define % of receipients to receive the two variants
3/ Define time when the result is judged on and the rest of receipients receive the better performing variation

## Example UI for setup (screenshot of Simplero)

![image](https://github.com/user-attachments/assets/939b07eb-dd49-4222-b153-fa3f264d153f)


## Example UI for broadcast/send list (screenshot of Simplero)

![image](https://github.com/user-attachments/assets/0e743f90-c7ad-4058-a737-1e976f333a26)

As you can see it makes a *huge* difference if 6% or 12% of 1.2 million contacts open an email,
that's a whopping 72,000 more eye balls @knadh 

## Example UI for broadcast stats (screenshot of Simplero)

![image](https://github.com/user-attachments/assets/ede164ea-1763-40de-b0f9-bd2753ab4b83)

So as you can see, that's one of the most vital things a bulk mailing tool needs for the end user,
and not something you can "delegate to the marketing department". That marketing department is the key user/end user here imo.

We are able and motivated to add such features to ListMonk at least in a custom fork for us at the moment,
but of course want to make it as useful/reuseable as possible.
