### ISSUE TITLE
How do i setup development environment?

### ISSUE THREAD

**Issue by Satishglk** [knadh/listmonk#1678]
I sincerely appreciate any help. I spent hours trying to debug and still no where closer.

I am using a windows environment  to do the developer setup.  I have all the prereq's installed (Go, node, yarn, postgres etc.) After cloning the repository,  Here is what  i am seeing in my console.

C:\listmonk-master>go build -v -o listmonk.exe ./cmd

C:\listmonk-master>listmonk.exe -- new-config
2024/01/18 20:25:04 main.go:102:
2024/01/18 20:25:04 init.go:148: reading config: config.toml
2024/01/18 20:25:04 init.go:287: connecting to db: localhost:5432/listmonk
**[2024/01/18 20:25:04 init.go:204: unable to initialize embedded filesystem (no ID found in the file). Using local filesystem]**
2024/01/18 20:25:04 init.go:226: loading i18n files from: i18n
2024/01/18 20:25:04 init.go:246: loading static files from: [static](url)
**2024/01/18 20:25:04 init.go:258: failed reading static files from disk: 'static': CreateFile frontend\dist: The system cannot find the file specified.**

I am unsure what  i am missing.  Appreciate any help.

**Comment by knadh** [comment]
You're compiling the Go program successfully, but you are not running the frontend build that produces the JS/CSS etc. assets in the `frontend/dist` directory. Please refer to the Makefile to figure out the correct steps. Better yet, install `make` on Windows (I'm not familiar with the steps) and just run `make dist` so that all these steps are handled.

**Comment by Satishglk** [comment]
Adding some additional info as it might benefit others.
1. Doing the developer setup on windows was way more complicated. 
2. Installing WSL (windows subsystem for Linux) with Ubuntu (Both WSL and Ubuntu are available in Microsoft store for free) on windows is a better option.  
3. Once you complete above step, then you need to go through and install Prereq's with correct versions. Packages such as NPM, YARN, Nodejs, and few more need to be installed. Once done, then follow the Listmonk's developer setup instructions-execute those commands (to launch backend and front end) in the WSL window
