### ISSUE TITLE
Question on list imports with already opted-in subscribers

### ISSUE THREAD

**Issue by atomtigerzoo** [knadh/listmonk#168]
Hello!
I'm trying out listmonk and would eventually make the switch from mailchimp :) I therefor have to import a huge list of subscribers I already have. All of the have made the double opt-in in the give list.

Can I import all and have them assigned to double opt-in list *without* having them to opt-in again?
My understanding is right now that each subscriber will have to opt-in again when importing lists or adding them manually? How can I avoid this if I already have the double opt-in done before?

Thank you for your time that you invest in listmonk 💯

**Comment by knadh** [comment]
@atomtigerzoo you can run an SQL query and confirm subscriptions. Something like `UPDATE subscriber_lists SET status='confirmed';`

**Comment by russ** [comment]
I this issue should be revisited now that listmonk has reached 1.0 🎉

I'm dealing with the same issue right now. The SQL fix does "work" but it's not a great solution. Where exactly would I end putting that solution that makes sense? I'd really not access the database directly and treat my listmonk deployment more like a remote service.

My hunch is that this a pretty common problem that might turn people off when first looking into listmonk as a viable solution.

Without making it too complicated, I think a simple status toggle could be added to the import page as well as an option on the import api.

**Comment by knadh** [comment]
> Without making it too complicated, I think a simple status toggle could be added to the import page as well as an option on the import api.

+1. Makes sense. Re-opening the issue.

**Comment by russ** [comment]
@knadh I opened up a pull request with working code. Please feel free to rework any of that how you feel necessary.
