### ISSUE TITLE
Custom CSS in Admin Panel Not Overriding Main CSS

### ISSUE THREAD

**Issue by warebytes** [knadh/listmonk#1682]
## Description
I've encountered an issue where the custom CSS specified for the admin panel in Listmonk is not overriding the main CSS. This limits the ability to fully customize the admin panel's appearance.

## Steps to Reproduce
1. Navigate to the admin panel.
2. Specify custom CSS in the provided option.
3. Observe that the custom CSS changes do not take effect as expected.

## Expected Behavior
The custom CSS specified should override the main CSS, allowing for complete customization of the admin panel's appearance.

## Actual Behavior
The main CSS seems to have higher priority, and the custom CSS does not override it as intended.

## Possible Cause
Upon inspecting the page's source code, it appears that the link to the custom CSS (`<link href="/admin/custom.css" rel="stylesheet">`) is placed before the link to the main CSS (`<link href="/admin/static/css/main.e4446e42.css" rel="stylesheet">`). In standard CSS loading behavior, the last read stylesheet has the highest priority, which could be causing this issue.

## Suggested Solution
Reorder the HTML to ensure the custom CSS link is placed after the main CSS link. This change should allow the custom CSS to have higher priority and override the main CSS as intended.

## Additional Information
- Listmonk version: v2.5.1

**Comment by knadh** [comment]
This is because of CDN/browser cache. Has already been addressed for the next release in this: https://github.com/knadh/listmonk/commit/0c9dc074791d81c0003d59dc4db4593285fbe90f

**Comment by warebytes** [comment]
Hi Knadh,
Thank you for your prompt response and for supporting this awesome project.
Cheers.
Achraf
