### ISSUE TITLE
Need help integrating Listmonk with mailhog or mailpit

### ISSUE THREAD

**Issue by rameshdon1** [knadh/listmonk#1683]
I initiated a smtp server with mailhog through this command `docker run -p 8025:8025 -p 1025:1025 mailhog/mailhog`
Now on `/admin/settings` page's SMTP section,
The smtp server is running on port 1025, so below is the details that i filled up
 
![image](https://github.com/knadh/listmonk/assets/139542777/890db5f9-5d78-48ff-acf3-66f5e2ac77af)

I don't know why, but when i try to test connection, I get this error 
![image](https://github.com/knadh/listmonk/assets/139542777/1b80da37-cabf-4b17-8d2c-74d454f4b51a)

Is there any thing that i am missing?

**Comment by knadh** [comment]
Is listmonk also running in Docker? Seems like a localhost port binding issue. Try binding Mailhog to 0.0.0.0 and supplying the host IP in listmonk settings.

**Comment by rameshdon1** [comment]
@knadh thanks. indeed it was the issue with port binding, In the smtp host i provided my system's ipv4 address and it worked.!
