### ISSUE TITLE
Add external font like inter, roboto on rich text editor

### ISSUE THREAD

**Issue by rameshdon1** [knadh/listmonk#1684]
How to add custom fonts in this rich text editor? 

![image](https://github.com/knadh/listmonk/assets/139542777/4fdcb79c-b6af-4aa1-95a9-bdfea960d0d0)

**Comment by knadh** [comment]
You can't really. The significant majority of e-mail clients do not support loading external fonts. The ones listed are just widely installed system fonts.

**Comment by rameshdon1** [comment]
Thanks @knadh did not knew that
