### ISSUE TITLE
1-click unsubscribe

### ISSUE THREAD

**Issue by TychoWerner** [knadh/listmonk#1685]
**Is your feature request related to a problem? Please describe.**
As per feb 2024 it is required to have 1 click unsubscribe links for Gmail recipients 
As per https://www.google.com/amp/s/blog.google/products/gmail/gmail-security-authentication-spam-protection/amp/

**Describe the solution you'd like**
I would appreciate an option to send 1 click unsubscribe links for all users and keep the other options on the page as is.

**Comment by Justinomics** [comment]
Listmonk already has this. Go to Settings -> Privacy, and toggle the "Include `List-Unsubscribe` header" option.

**Comment by TychoWerner** [comment]
Hi @Justinomics 
Thanks for your reply; I have checked to see that function is indeed enabled.
I see the List-Unsubscribe headers in my emails:

![Scherm­afbeelding 2024-01-22 om 16 42 48](https://github.com/knadh/listmonk/assets/34608981/5a03f53f-1556-461e-9c49-79b9f1d5e3fc)


Only thing is the URL it gives me, when I visit that it still presents me with a screen to click again before being unsubscribed. Hereby not following the 1-click unsubscribe?

Thanks for your help so far!

![Scherm­afbeelding 2024-01-22 om 16 45 54](https://github.com/knadh/listmonk/assets/34608981/26a5904a-44f1-43e1-b535-94fa74d89f07)

**Comment by TychoCeltCast** [comment]
Listmonk might also need to support mailto unsubscribe to get rich unsubscribe features in clients
https://www.litmus.com/blog/the-ultimate-guide-to-list-unsubscribe

**Comment by MaximilianKohler** [comment]
>Only thing is the URL it gives me, when I visit that it still presents me with a screen to click again before being unsubscribed. Hereby not following the 1-click unsubscribe?

It's valid per the requirements from what I read. I would be worried about false unsubscribes resulting from converting the current method to an actual 1-click method: https://github.com/knadh/listmonk/issues/1078#issuecomment-1879499536

>Listmonk might also need to support mailto unsubscribe to get rich unsubscribe features in clients

* https://github.com/knadh/listmonk/issues/1161

More recent discussion & testing here:
* https://github.com/knadh/listmonk/issues/1655

**Comment by knadh** [comment]
> Only thing is the URL it gives me, when I visit that it still presents me with a screen to click again before being unsubscribed.

Visiting is a GET request. The endpoint accepts a POST request as per the spec, which clients like GMail post to, enabling one-click unsubscribe.

**Comment by alt-romes** [comment]
It seems like this is broken, or at least not properly configured by default (even when the option is toggled).

I'm using listmonk v4.1 and the emails sent by the campaign do not include the List-Unsubscribe header at all, and I have tried both with and without the option being toggled.

Any help would be greatly appreciated.

**Comment by knadh** [comment]
@alt-romes if the toggle is enabled, then listmonk definitely includes the header. What SMTP server are you using? It may be possible that the SMTP server is stripping it?

**Comment by alt-romes** [comment]
(I've opened #2224 to track my issue)
