### ISSUE TITLE
Change the performance setting in the middle of a running campaign.

### ISSUE THREAD

**Issue by rameshdon1** [knadh/listmonk#1687]
@knadh What will happen if I change the performance of email sending lets say add more workers thread during a running campaign (without pausing it)? Would this action interrupt the campaign, or its fine? 

I noticed that my campaign was immediately stopped. May be i provided less batch size than (concurrency * message_rate).

**Comment by knadh** [comment]
Changing settings causes listmonk to restart. That's why when there's a running campaign, the settings page warns of this. You should pause the campaign and then make any settings changes.
