### ISSUE TITLE
New Python API Client for Integrating with Python Apps

### ISSUE THREAD

**Issue by mikeckennedy** [knadh/listmonk#1688]
Hey folks. This is really a just an announcement for the creators/maintainers of Listmonk. I didn't see an alternative contact us, sorry for the noise. Please close this issue once you see it.

I just wanted to let you know I spent some time last week building out a polished Python package to allow Python devs to easily integrate with Listmonk.

https://github.com/mikeckennedy/listmonk

From the repo, here are the core features:

* ➕**Add a subscriber** to your subscribed users. 
* 🙎 Get **subscriber details** by email, ID, UUID, and more.
* 📝 **Modify subscriber details** (including custom attribute collection).
* 🔍 **Search** your users based on app and custom attributes.
* 🏥 Check the **health and connectivity** of your instance.
*  👥 Retrieve your **segmentation lists**,  list details, and subscribers.
* 🙅 Unsubscribe and block users who don't want  to be contacted further.
* 💥 Completely delete a subscriber from your instance.
* 📧 Send transactional email with template data (e.g. password reset emails).

Feel free to add it to your documentation or point people at it if they need a Python API. It's [available on PyPI](https://pypi.org/project/listmonk/) (Python's package manager)

I hope this helps some folks. It's working well in my apps so far.

**Comment by knadh** [comment]
This is quite cool @mikeckennedy.

We can add a new "API Clients" section to https://listmonk.app/docs/apis/apis/ and list this there.

**Comment by mikeckennedy** [comment]
100% that'd be a great place to add it. Thanks @knadh!

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0
