### ISSUE TITLE
Data loss after reboot

### ISSUE THREAD

**Issue by venethia** [knadh/listmonk#1689]
Hi,

I installed Listmonk with Docker and a persistence data folder, but every time I reboot the server I find the default created lists and subscribers that i previously deleted.

All lists created after install and subscribers uploaded are gone.

I use DietPi a debian-based distribution and the latest version of Listmonk.

This is my docker compose file:

version: "3.7"

services:
  db:
    image: postgres:13
    container_name: listmonk-db
    ports:
      - "5432:5432"
    networks:
      - listmonk
    environment:
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - /data/listmonk/postgresql/:/var/lib/postgresql/data

  app:
    image: listmonk/listmonk:latest
    container_name: listmonk-web
    restart: always
    ports:
      - "9800:9000"
    command: [sh, -c, "yes | ./listmonk --install --config config.toml && ./listmonk --config config.toml"]
    networks:
      - listmonk
    environment:
      - TZ=Europe/Rome
    depends_on:
      - db
    volumes:
      - /data/listmonk/config/config.toml:/listmonk/config.toml
      - /data/listmonk/static:/listmonk/static

networks:
  listmonk:

**Comment by knadh** [comment]
Please see:

- https://github.com/knadh/listmonk/issues/1618
- https://github.com/knadh/listmonk/issues/1089#issuecomment-1342492323
