### ISSUE TITLE
docker not building

### ISSUE THREAD

**Issue by chovy** [knadh/listmonk#169]
````
$ docker-compose up --build
Removing listmonk_demo-db_1
Recreating listmonk_db_1 ...
Recreating listmonk_db_1                   ... error
WARNING: Host is already in use by another container

ERROR: for listmonk_db_1  Cannot start service db: driver failed programming external connectivity on endpointlistmonk_db_1 (1da241985620cc8c0c1a3c82e7a619e863384662940d7f1656261d812cfe1d2f): Bind for 127.0.0.1:9774 faileRecreating 32e351cd71e9_listmonk_demo-db_1 ... done
Recreating listmonk_demo-app_1             ...
Recreating listmonk_demo-app_1             ... error

ERROR: for listmonk_demo-app_1  Cannot start service demo-app: driver failed programming external connectivityon endpoint listmonk_demo-app_1 (f7fcc6de0c7272083b501142acc0d6eb71b60e1607f7e0c1ee4e6436f3219d8a): Bind for 127.0.0.1:9421 failed: port is already allocated

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint listmonk_db_1 (1da241985620cc8c0c1a3c82e7a619e863384662940d7f1656261d812cfe1d2f): Bind for 127.0.0.1:9774 failed: port isalready allocated

ERROR: for demo-app  Cannot start service demo-app: driver failed programming external connectivity on endpoint listmonk_demo-app_1 (f7fcc6de0c7272083b501142acc0d6eb71b60e1607f7e0c1ee4e6436f3219d8a): Bind for 127.0.0.1:9421 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
````

**Comment by mr-karan** [comment]
Looks like there is a service listening on `9421` already. 

You can check with `sudo lsof -i:9421`

**Comment by chovy** [comment]
I guess this error no matter what port i use.

**Comment by mr-karan** [comment]
Can you try doing a docker-compose down?

Looks like the network isn't cleaned up properly. In any case, recreating the service after cleaning up should help.

**Comment by mr-karan** [comment]
@chovy I just realised you are trying to run all services present in the `docker-compose.yml`. The instructions [here](https://github.com/knadh/listmonk/blob/master/INSTALL.md#running-on-docker) mention the exact command you should run `docker-compose up app db` or `docker-compose up demo-app demo-db` based on your environment.

**Comment by chovy** [comment]
That worked. Is there a way to get an archive in html of emails sent? I am trying to build something like nodeweekly.com

**Comment by knadh** [comment]
@chovy the original template and body is saved in the `campaigns` table which you can query and extract, but a rendered copy of the template per subscriber is not stored currently.
