### ISSUE TITLE
Enabled transactional messages to campaign IDs

### ISSUE THREAD

**Issue by GregAke** [knadh/listmonk#1690]
I'm unsure if there is another way to accomplish this, but I would like to request to be able to target a campaign ID in transactional messages so I can send updates to a list of subscribers. I manage a blog and would like a single method to update them of a new post being published.

**Comment by knadh** [comment]
Hi @GregAke. You should use the /campaigns API to create and start a new campaign for your blog post.

Transactional mails are for individual transactions, not groups.
