### ISSUE TITLE
Fetch content directly from a https link (remote webpage)

### ISSUE THREAD

**Issue by CIMEOS** [knadh/listmonk#1691]
Hi,
First thanks for this tool that seems pretty cool. We are currently using phplist but lismonk seems quite appealing, especially with the quite complete API. We have a improvement suggestion.
It's not uncommon to prepare a whole newsletter in a CMS, generating content directly from the data available in the system. In several emailing tools (phplist for instance), it's possible to give a https link instead of using the RTE.
When sending a campaign, it's downloading the source of the page and use it as content. Of course, the remote page has to be specifically built for that but it's working very well and allow a lot more flexibility that creating everything in a RTE or trying to copy/paste a source code (also not very intuitive for a end user).
Is it something that has been planned for a future update ?

**Comment by knadh** [comment]
Thank you @CIMEOS. This is out of the scope of the project. You can always orchestrate this with scripting externally and insert content into listmonk using its APIs.

**Comment by CIMEOS** [comment]
Alright, thanks for the quick answer, we'll have a look at the api if it can work for us
