### ISSUE TITLE
Question on Views

### ISSUE THREAD

**Issue by Satishglk** [knadh/listmonk#1692]
Really quick questions. I don't have much experience in email terminology and making sure that my understanding is correct on the stats-Views. 

1) Are "Views" count an indication that email has been 'delivered'  AND  an user has 'opened' the email ?  

2) Based on what i read from the discussions/issues,  views count shown on campaign panel is not unique views and we should use the database table "campaign_views" and query it for unique views ?

Sincerely appreciate the help. This App is very powerful !

**Comment by MaximilianKohler** [comment]
>Are "Views" count an indication that email has been 'delivered' AND an user has 'opened' the email ?

It counts when they load the tracking pixel image. If you set your emails to never load external images you will never register as a view.
