### ISSUE TITLE
Preview error when adding `Safe` to template syntax

### ISSUE THREAD

**Issue by waza-ari** [knadh/listmonk#1693]
**Version:**
 - listmonk: v2.5.1
 - OS: Docker (on Ubuntu 22.04)

**Description of the bug and steps to reproduce:**
The preview of a transactional template fails when introducing template functions such as `| Safe`. Not tested with others.

Create a new template, transactional, any subject. Add the following minimal template:

```html
<!doctype html>
<html lang="de">
  <head><title>{{ .Tx.Data.subject }}</title></head>
  <body>{{ .Tx.Data.content }}</body>
</html>
```

Verify preview shows an empty white page. Replace it with

```html
<!doctype html>
<html lang="de">
  <head><title>{{ .Tx.Data.subject }}</title></head>
  <body>{{ .Tx.Data.content | Safe }}</body>
</html>
```

Now the error message is shown instead:

```
{"message":"globals.messages.errorFetching: Invalid arguments"}
```

Note that saving the template and sending mails using this template work fine.

**Comment by knadh** [comment]
Please see this: https://github.com/knadh/listmonk/issues/1686
