### ISSUE TITLE
Files added to static directory are not getting refreshed

### ISSUE THREAD

**Issue by jackraj97** [knadh/listmonk#1697]
I added a HTML file to the static directory `listmonk/static/public/static` while listmonk was already running. This file was not accessible at `http://localhost/public/static/hello.html`.

I had to restart the process and access it. If I make any changes to this file it is not reflected too. Looks like I need to refresh the server everytime.

Is there anyway I can serve custom files without the need to restart listmonk?
My usecase is to add a custom `feed.xml` file (for other purpose) to this directory which will be updated with a custom script.

**Comment by knadh** [comment]
Hi @jackraj97. listmonk requires a restart as it loads the static files into memory to avoid repeated disk reads. Also, `--static-dir` is not really meant to serve arbitrary static files that change frequently.

- listmonk archives (Campaign -> Archive) already publishes an XML feed.
- If you want to publish custom files, then it's best to configure that in your reverse proxy (like Nginx) behind which you'd be putting listmonk in production.
