### ISSUE TITLE
v3.0.0 release candidate

### ISSUE THREAD

**Issue by knadh** [knadh/listmonk#1699]
v3.0.0 release candidate (RC) is ready for public testing. It has already been tested internally on a very large installation in production. Please consider upgrading your installation to v3.0.0 RC 7 (and sharing any feedback before the final release).

**Upgrading to v3.0.0 RC 7**
- Download binary: [listmonk-v3.0.0-rc-7.tar.gz](https://github.com/knadh/listmonk/files/14075073/listmonk-v3.0.0-rc-7.tar.gz)
- Docker image: `listmonk/listmonk:v3.0.0-rc-7` (change the image name in docker-compose.yml and run the --upgrade step)

# What's new?
- The concurrent core or the "engine" is completely re-written. Campaign pausing and cancellations are now near-instant and lossless. Concurrent campaign sending performance has improved significantly. The `sent` count now accounts for every single message rather than an approximation.
- Major performance improvements for large databases with the new `Settings -> Performance -> Cache slow queries` option. On installations with millions of subscribers, enabling this speeds up database queries (retrieving lists, subscribers etc.) by several orders of magnitude. On our production database with ~14 million subscribers, the speed up on the lists page was 2000x, from ~20s to ~10ms.
- New frontend dependency and build system refactor, speeding the admin pages (and the development build process).
- Addressed the root cause of mysterious SMTP sending errors that triggered only in certain SMTP environments.
- New fields for filtering lists, campaigns, subscribers in query APIs.
- Major refactor and cleanup of documentation.
- `F9` shortcut key for campaign and template previews.
- Many quality-of-life improvements, fixes, and dependency upgrades.

See full changelist: https://github.com/knadh/listmonk/compare/v2.5.1...master

**Comment by MaximilianKohler** [comment]
Big update knadh! Thank you!

BTW, when I switched to binary I was looking at the "assets" https://github.com/knadh/listmonk/releases and I was a little unsure of which one to choose. Most seem self-explanatory, but I think `amd64` is what we choose even with an intel x86 CPU, so I was a little unsure on that part. Eg: when looking at the CPU list here https://www.hetzner.com/cloud/ they have `arm64` and `amd` and `intel` `x86`. Might it be suitable to give some short guidance either on the releases page or [in the docs](https://listmonk.app/docs/installation/#binary)?

**Comment by knadh** [comment]
Thanks @MaximilianKohler. The RC binary for testing is not on the releases page. It’s attached in the post above. It’s amd64 (Linux, 64 bit).

**Comment by MaximilianKohler** [comment]
Yeah, I was making a more general comment.

**Comment by samyogdhital** [comment]
Works great!

**Comment by knadh** [comment]
@eddywashere ah, next time!

https://github.com/knadh/listmonk/releases/tag/v3.0.0
