### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by vtolstov** [knadh/listmonk#17]
Can you split main package to cmd/listmonk
And other stuff provide like listmonk package for easy to integrate to other apps?
Also why you dont use something like xorm to abstract db access?
This can bring ability to use sqlite or mysql too

**Comment by knadh** [comment]
> Can you split main package to cmd/listmonk

Will consider this. The re-usable and extensible parts are already packages and it's just HTTP handlers in the main package.

>  Also why you dont use something like xorm to abstract db access?

I took this route initially. Tried gorm, xorm etc. but dealing with ORMs was limiting and painful. Most of listmonk's queries use CTEs extensively and they'd have to hand-written anyway. Also, listmonk relies heavily on Postgres features such as JSON blob and indexes. I don't think the complexity of supporting multiple DB backends is beneficial.

The table structures are really simple, so it's straight forward to integrate with external CRMs by directly manipulating table data or using APIs.

Thanks

**Comment by Xeoncross** [comment]
> Most of listmonk's queries use CTEs extensively and they'd have to hand-written anyway. 

I agree. I've worked on similar software and the queries really need to be written natively for the part of the software that interacts with an SQL store. (Any NoSQL storage also must be carefully designed.) The way you per-defined all your queries is very nice and manageable anyway.

**Comment by knadh** [comment]
Cheers @Xeoncross. ORMs may give a headstart, but in the long run, they almost always end up being inadequate. Easier to just write SQL than to learn an obtuse ORM language :)

**Comment by hsluoyz** [comment]
Another vote for MySQL. I can tolerate some performance downgrade to use MySQL.

**Comment by knadh** [comment]
@hsluoyz As I wrote earlier, listmonk uses a number of Postgres specific features. While it is possible to build an abstraction layer to add support for multiple storage backends (and this may happen in the future), there are definitely no plans of adding MySQL or any other storage backend right now. There are other features that take priority. Thanks.

**Comment by SalahSaqr** [comment]
I vote for MySQL as well!

**Comment by vladaman** [comment]
Listmonk looks great but the reason why we still stick to other paid products is that we don't want to maintain Postgres. Postgres requirement is a blocked for us. We run exclusively on MySQL. Adding support for MySQL would be great.

**Comment by knadh** [comment]
Thanks @vladaman, but adding support for two large DBs is not feasible for a product like listmonk, unfortunately. If anything, the support should be for SQLite enabling it listmonk to be able to run with zero dependencies.

On a slightly unrelated note, we find Postgres to be far more stable and far more easier to maintain. For non-massive DBs, it's pretty much install and forget!

**Comment by richardpickett** [comment]
Postgres is very stable, that's correct.  But there are several reasons mysql/mariadb may be preferred:

One main factor is multi-master is built in.  Multi-master-ish is achievable in postgres with third-party extensions, but this is one step away from the postgres maintainers themselves building multi-master into the product, which isn't as good as mysql/mariadb.

Multi-master is important for production-level systems because:

1. it allows you to have high availability across multiple database instances.  If one instance goes down, you get switched to the other.

2. it allows you to easily move your entire service to another region, or run web instances in multiple regions.  Each region has it's own master that is synced with the other regions.

**Comment by handkerchief333** [comment]
We vote also for mysql/mariadb. Our case is simple, we can't use listmonk with our prefered hosting providers because they only support mysql/mariadb.

**Comment by CicerBro** [comment]
Another vote for MariaDB
