### ISSUE TITLE
Subscribers sorting not working

### ISSUE THREAD

**Issue by sweetppro** [knadh/listmonk#170]
clicking the headers in the Subscribers list view does nothing. It would be great if this could be made functional. Also great if sort toggles could be added to the other columns: *Status, Lists, Created, Updated*

**Comment by knadh** [comment]
Sorting by name / email / date fields is on the to-do. But sorting by status does not make sense as there are only 3 statuses and you can filter them using the query box. Again, it's not possible to sort by lists. Filtering by lists can be done from the Lists page.

**Comment by knadh** [comment]
This is now merged to master: https://github.com/knadh/listmonk/commit/1aecd6f2e13d7a07c4938e280723430e1bc1e170
