### ISSUE TITLE
Handle feedback and bounces on Sendamatic (new smtp provider)

### ISSUE THREAD

**Issue by samyogdhital** [knadh/listmonk#1707]
I am using this new SMTP provider [Sendamatic](https://www.sendamatic.net/).
To handle feedback there are two methods:

1. Email:

![image](https://github.com/knadh/listmonk/assets/91406792/2f1ec86f-d672-4551-9e0e-0d780ec6e136)

2. Webhook:

![image](https://github.com/knadh/listmonk/assets/91406792/639766dc-3dc2-4ae1-bbf4-7ddc5aaaaa11)

What should I do to handle my bounces on listmonk. I did some search on issues section, @knadh You were referring to make your own messenger system for this. If creating a new messenger to handle bounces is the right approach how should i get started?

**Comment by knadh** [comment]
> If creating a new messenger to handle bounces is the right approach how should i get started?

Yep, this is the way to go.

- Setup a webserver/HTTP endpoint (you can write this in any language/framework) that accepts and POST payload coming from sendmatic. They'd have a developer API documentation that details the structure of this bounce payload they send.
- Once this payload is received and parsed, POST it to the listmonk bounce API endpoint: https://listmonk.app/docs/bounces/#webhook-api
