### ISSUE TITLE
How to use different mailed-by on each campaign

### ISSUE THREAD

**Issue by samyogdhital** [knadh/listmonk#1710]
![image](https://github.com/knadh/listmonk/assets/91406792/e39d05af-fd64-4cb4-a3f1-9bd3d53b349e)

I have multiple Custom MAIL FROM domain which will be used in that mailed-by section from above image, I have verified multiple subdomain to send email from.

On listmonk can I choose which one to use?
For eg: On marketing email  => marketing.domain.com
            On transactional email => order.domain.com
            
 Am I able to explain properly to you? 
 Or is it something that I have to consult it with the smtp provider?

**Comment by knadh** [comment]
- Every campaign can have its own `from` address. Check out the `Campaign` tab on a campaign.
- If you're referring to separate SMTP servers per campaign, that isn't possible currently. You can achieve it in a crude way by enabling/disabling the necessary SMTPs in settings before sending a campaign.

**Comment by MaximilianKohler** [comment]
>Or is it something that I have to consult it with the smtp provider?

Yes, with Amazon SES for example, you set it up in their admin area.
