### ISSUE TITLE
Unsubscribe and MessageURL for transactional templates?

### ISSUE THREAD

**Issue by poblabs** [knadh/listmonk#1711]
Hey there, I'm working on a way to send a transactional template to new subscribers which contain a coupon code as a thank you for signing up. I noticed I can't add the {{ MessageURL }} nor {{ UnsubscribeURL }} to these messages. I think it's appropriate for this to be displayed just in case the user needs them. 

Any suggestions on how to get around this? Is the answer to create a new campaign for each user and segment them? Or create a draft campaign and use the API to send just targeted email using `POST /api/campaigns/{campaign_id}/test`?

Thanks

**Comment by knadh** [comment]
`{{ MessageURL }}` is only meant for campaigns (newsletters) that can be clicked and viewed in the browser and are also archived. Transactional messages are ephemeral. They're not stored anywhere to be viewed later.

`{{ UnsubscribeURL }}` again is for campaigns (backed by mailing lists to which someone has subscribed). Transactional messages are ad-hoc/one-off/ephemeral and not connected to mailing lists of subscriptions, so there isn't a list to unsubscribe from.

Creating a new campaign per user is definitely not advisable! I think your particular usecase may work better with a system like Mautic and not a mailing list manager.

**Comment by ghostdevv** [comment]
@knadh I'm not sure if there is a roadmap I am missing but I think it's fully worth moving listmonk in the direction of something like Mautic. The work being done on Mautic is incredible but it's a significantly larger system that is hard for non-contributors to get running (I have first hand experience with this from the past two months). Even if you aren't up for implementing more of the features of Mautic making listmonk more flexible would be greatly appreciated. If listmonk itself is more flexible around specific areas then it allows external tools/scripts to implement other features, as I somewhat covered [here](https://github.com/knadh/listmonk/issues/1712#issuecomment-1925580712).

**Comment by MaximilianKohler** [comment]
> Transactional messages are ad-hoc/one-off/ephemeral and not connected to mailing lists of subscriptions, so there isn't a list to unsubscribe from.

I think an "unsubscribe" link leading to an option to add their email to the blocklist would be appropriate.

**Comment by KristianLentino99** [comment]
I had the same need

**Comment by joshvickerson** [comment]
I find it confusing that in order to send a transactional email, the address in question must be a subscriber to a list in Listmonk, but we can't get an unsubscribe URL for that user in a transactional email. If the address must be subscribed, why can't Listmonk also provide an unsubscribe URL?

**Comment by alanef** [comment]
Yes, this is an issue, I need to find a work around or will have to try a different solution, this must be feasible?

**Comment by alanef** [comment]
Just for other you can do this   using a link

Since the subscriber is fetched from the DB (in default mode), you already have access to {{ .Subscriber.UUID }}. You could hardcode the URL pattern in your template:

  <a href="https://yoursite.com/subscription/00000000-0000-0000-0000-000000000000/{{ .Subscriber.UUID }}">Unsubscribe</a>

  The 00000000-0000-0000-0000-000000000000 is the dummyUUID used elsewhere for non-campaign unsubscribes.
