### ISSUE TITLE
uuid & id combination struggles 

### ISSUE THREAD

**Issue by ghostdevv** [knadh/listmonk#1712]
It seems quite common in places to have both a `uuid` and a int `id` for an object, and I wonder what was the motivation here? It seems to add additional complexity both in the listmonk code and in integrations with it. I've just finished a major integration with a client's site including having to make some internal changes to listmonks code and having both ids has been a big pain point.

I have marked this as a question but ideally it's a feature request, specifically to drop the auto incrementing `id` and just use a uuid for all objects.

**Comment by knadh** [comment]
Publicly exposed objects (campaigns, lists, subscribers in SMTP headers, sub/unsub webpages) etc. use UUIDs so as to not expose internal auto-increment IDs that can give away sensitive information, like a subscriber count, list count etc.

Moreover, the entire concurrent message processing core depends on the subscribers being sortable fast. In a table with millions of subscribers, the sort performance matters of a SERIAL vs. UUID.

- All internal APIs exclusively use IDs.
- All public APIs (sub/unsub/manage form, webpage URLs, SMTP headers etc.) use UUID.
