### ISSUE TITLE
Unable to search campaigns if the campaign name has numbers.

### ISSUE THREAD

**Issue by adxy** [knadh/listmonk#1713]
**Version:**
 - listmonk:  v3.0.0
 - OS: Ubuntu 20

**Description**
Unable to search a campaign with numbers in the name. 

**Screenshots:**
![Screenshot 2024-02-05 111319](https://github.com/knadh/listmonk/assets/26243064/acc917a5-5258-4401-a914-caf7b3b52504)
![Screenshot 2024-02-05 111334](https://github.com/knadh/listmonk/assets/26243064/f02fafa4-2629-49e3-afa2-475d7beb6b38)

**Comment by MaximilianKohler** [comment]
I can confirm that `NL-02-24-#1` works for me on v2.5.1.

**Comment by adxy** [comment]
> I can confirm that `NL-02-24-#1` works for me on v2.5.1.

Can you check this for `v3.0.0`?

**Comment by MaximilianKohler** [comment]
>Can you check this for v3.0.0?

I don't want to upgrade if it's broken. There should be other people who can easily check this.
