### ISSUE TITLE
Impossible upgrade to 3.0.0

### ISSUE THREAD

**Issue by ArabianCat** [knadh/listmonk#1714]
**Version:**
 - listmonk: 2.5.1
 - OS: Debian 11

**Description of the bug and steps to reproduce:**
I try to upgrade listmonk in binary. So I stop the service, and start the upgrade, but it don't find an upgrade.

**Screenshots:**
![image](https://github.com/knadh/listmonk/assets/102919110/a19fe1f5-d08d-4751-8f5a-ff6e24f7c261)

**Comment by ArabianCat** [comment]
I precise the listmonk program is the new (3.0.0).

**Comment by cyrusx** [comment]
execute upgrade with listmonk v3.0, not the old one

**Comment by MaximilianKohler** [comment]
After stopping the service did you replace the old binary with the new one?

**Comment by ArabianCat** [comment]
> After stopping the service did you replace the old binary with the new one?

Only the "listmonk" program

**Comment by ArabianCat** [comment]
Ok when i use all the new one it's good. Sorry for the inconvenience !
