### ISSUE TITLE
Question about test campaign messages API

### ISSUE THREAD

**Issue by poblabs** [knadh/listmonk#1719]
Hey there, I had a question on the design decision behind the POST payload when testing a campaign. [Why do you include the full HTML content, and other values, as the the payload body in the POST request?](https://github.com/knadh/listmonk/blob/6689b716d9ff3f7036025b3a213b4de83a7f8513/cmd/campaigns.go#L448) The body is already saved to the campaign table, wouldn't it be sufficient to use what's saved in the database? 

My use case: 

I am using the `/api/campaigns/{campaign_id}/test` API method to send welcome emails to new subscribers. I have to include any content changes in both the POST payload AND the campaign content UI (in case they click the link to view on browser). It seems redundant. 

**For my specific use case**, I was able to comment out [these lines](https://github.com/knadh/listmonk/blob/6689b716d9ff3f7036025b3a213b4de83a7f8513/cmd/campaigns.go#L422-L427) and [these lines](https://github.com/knadh/listmonk/blob/6689b716d9ff3f7036025b3a213b4de83a7f8513/cmd/campaigns.go#L448-L462) to get it to work.

Since the test method isn't creating a new campaign, shouldn't the test method be a representation of what the database has stored?

Thought I'd ask about it as a general design decision on the project.

Thanks!

**Comment by knadh** [comment]
On the editor, the body often has to be modified and previewed first before saving it to the database. Previewing unsaved changes is more frequent than previewing saved changes.

**Comment by poblabs** [comment]
Makes sense, thanks! With that said, I think I'll make a custom handler and a copy of `handleTestCampaign` for my purposes, leaving the original in place.
