### ISSUE TITLE
Campaign progress issue

### ISSUE THREAD

**Issue by heinrichreimer** [knadh/listmonk#172]
In v0.6.2-alpha, the campaign progress seems to be broken.
It shows the number of Mails fetched from the DB and inserted to the message queue.
In my opinion it should show the number of messages that were successfully processed and sent from the queue.
That leads to situations where the progress is like 1234/1234 (100%), but the campaign is still running.
Also it is hard to monitor progress, as database connections are usually much faster than sending messages.

**Comment by knadh** [comment]
It's not broken, but is a trade-off. Each send cycle involves fetching records from the DB with an offset marker which is recorded in the campaigns table. The campaign stats uses this metric to show an approximation of progress. Up until v0.6x, this batch size was hardcoded in the core (5k I think), so the progress was based on blocks of incremental 5k fetches. In the upcoming release, this number is configurable. By setting a lower number, the progress accuracy can increase.

About keeping track of live e-mail counts, it's a little tricky. Where as the current progress simply uses existing campaign offsets from the DB with no additional state management, counting sends will require addition states. Hopefully this'll improve at some point, but until then, the batch size control should help.

**Comment by heinrichreimer** [comment]
Okay, I'll try out some different values for the batch size. Thanks for this great app!
