### ISSUE TITLE
How can I view detailed analytics for each subscriber in a campaign?

### ISSUE THREAD

**Issue by admc2023** [knadh/listmonk#1720]
How can I see which specific subscribers within the campaign followed links from the letter, opened the letter, deleted the letter without opening it, added it to spam, unsubscribed, etc. Is this functionality implemented now and where can I view it? If this functionality is not implemented, will it be in the future, since without this functionality full interaction with subscribers is impossible...

**Comment by knadh** [comment]
Hi @admc2023. This isn't currently possible. Please see https://github.com/knadh/listmonk/issues/1458

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0
