### ISSUE TITLE
HTTP 400 when sent headers listmonk doesn't seem to understand.

### ISSUE THREAD

**Issue by birlorg** [knadh/listmonk#1722]
**Version:**
 - listmonk: 2.5.1
 - OS: nixos-23.11
 - Nginx configured as proxy

**Description of the bug and steps to reproduce:**
When setting headers to send to listmonk via HTTP proxy, say nginx, you might get a 400 error.
I for sure had this happen with these headers set:

```nginx
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_pass_header Authorization;
  proxy_set_header Host                $host;
```

I don't mind the 400 error, but there is nothing logged to tell you hey we got extra headers we didn't like. This can cause debugging what's going on a touch annoying.

So I'd recommend at the very least a log entry saying, Invalid Headers, to at least point someone in the right direction. Bonus points would be, letting them know what headers are invalid.

Anyways, this is a brand new deployment, never used listmonk before, but so far so good! Thanks for writing this!

**Comment by knadh** [comment]
Hi @birlorg. listmonk simply ignores unknown headers like any other webapp. listmonk in fact only explicitly cares about the authentication header `Authorization` which is required for authenticating all admin pages.

> I don't mind the 400 error, but there is nothing logged to tell you hey we got extra headers we didn't like.

Web apps rarely do this because anyone can send an infinite number of arbitrary header and query param variations (and bots do this regularly).

**Comment by birlorg** [comment]
My point was, if you throw a HTTP 400 error, you should log *something* pointing out WHY you are sending the 400 error, otherwise how can anyone fix it? If it's only in a debug or verbose mode, that's fine, but otherwise people have to randomly guess what in the world is the problem. Which is what I ended up doing to make it work. This is not a good way to troubleshoot software.

Given your comment, I assume it's the `Authorization` header that it was mad about?

**Comment by knadh** [comment]
As I mentioned earlier, listmonk itself does not parse look for any headers. The webserver lib it uses (`labstack/echo`) has an auth middleware that uses the `Authorization` header.
