### ISSUE TITLE
Responsive issues on Stripo designed emails, exported as HTML

### ISSUE THREAD

**Issue by panomitrius** [knadh/listmonk#1724]
**Version:**
 - listmonk: v3.0.0
 - OS: docker on Ubuntu server

**Description of the bug and steps to reproduce:**
When designing a newsletter in Stripo, with a responsive design having a block with f.x. 3 containers in it, it should display one container after the other and on mobiles and the containers horizontally besides each other on desktop. On Stripo's preview windows, it displays accordingly on Desktop and Mobile. But when I export it as HTML, add it to Listmonk as a template, and send it out, it displays in horizontal view on both desktop and mobile (viewed on Samsung S10E in Protonmail app). I've contacted the Stripo support, and they claim it's working fine when used through gmail export. 

I'm not sure if this is a problem on Stripo's behalf, Protonmail or if it's potentially a problem with Listbug, but I'm curious if anyone has any suggestion for solution?

**Comment by panomitrius** [comment]
Update, this problem seems to be only in the Protonmail mobile app, it's not an issue on fx gmail mobile app.

**Comment by knadh** [comment]
Hi @panomitrius. listmonk doesn't re-format or transform HTML tags, so this must be a clientside (Proton) quirk.
