### ISSUE TITLE
v3.0.0 Clone works only once per campaign name

### ISSUE THREAD

**Issue by setiseta** [knadh/listmonk#1725]
**Version:**
 - listmonk: v3.0.0
 - OS: Ubuntu 22.04 (but docker deployment)

**Description of the bug and steps to reproduce:**
create a campaign and try to clone it two times.

* Create a campaign, with name "test1"
* clone campaign "test1" and rename it
* clone campaign "test1"

**Screenshots:**

**Log:**
2024/02/12 09:40:30 campaigns.go:197: error creating campaign: pq: duplicate key value violates unique constraint "campaigns_archive_slug_key"

**Comment by Orthdron** [comment]
Not maintainer but I looked into it and the new Version 3.0 adds slug by default and hence it can't be cloned. No issues if you clone old campaigns.

**Comment by root-io** [comment]
.

**Comment by elrumordelaluz** [comment]
Same here.

**Comment by elrumordelaluz** [comment]
thank you @knadh! will this be added in a new version?

**Comment by Codinator007** [comment]
sorry for asking maybe a dump question... All issues seems closed for this topic but it still exists.
Will this issue be fixed in the next version or is there a chance to solve it earlier?
thank you :)

**Comment by PackMeister** [comment]
I'm unable to clone an old campaign as well.
Tried bouncing listmonk server but when re-attempting to clone old campaign to edit for new campaign I get following:

error creating campaign: pq: duplicate key value violates unique constraint "campaigns_archive_slug_key"

**Comment by m3nu** [comment]
Getting this error too. My solution was to set the `campaigns.archive_slug` to `NULL` before cloning the old campaign. Most of my campaigns already had `NULL`. Hope this doesn't break something else.

**Comment by muammaramer** [comment]
same issue here! can we re-open this?

**Comment by momu** [comment]
> My solution was to set the `campaigns.archive_slug` to `NULL` before cloning the old campaign. Most of my campaigns already had `NULL`

@m3nu How did you do it?

**Comment by serge005** [comment]
@momu I'm assuming he modified the data in the database.
