### ISSUE TITLE
URL Query strings possible for user attributes?

### ISSUE THREAD

**Issue by poblabs** [knadh/listmonk#1726]
I'm looking into a way to generate referral metadata to subscribers. One way I'm thinking of automating this is with the subscribe form URL and using URL query strings. Is it possible to capture these and save them as the user's attributes? If not, can this be an optional feature added?

**Comment by knadh** [comment]
Sorry, missed responding to this. This is not possible out of the box, however, you can build your own form on your website, capture any arbitrary fields, then post it to listmonk using the API. This way, you can sanitize and do custom validations for the fields as well.
