### ISSUE TITLE
cant connect to api after upgrading to 0.70

### ISSUE THREAD

**Issue by sweetppro** [knadh/listmonk#173]
I get the error message:
{"message":"Unauthorized"}

what do I need to add to my Nginx settings to allow api access in v0.7.0

I was using the following Nginx settings for v0.6.2:
```
        AuthType Basic
	AuthName "Restricted Content"
	AuthUserFile /etc/apache2/.htpasswd
	Require valid-user

	Require expr %{REQUEST_URI} =~ m#^/subscription/.*#
	Require expr %{REQUEST_URI} =~ m#^/api/.*#
	Require expr %{REQUEST_URI} =~ m#^/link/.*#
	Require expr %{REQUEST_URI} =~ m#^/public/.*#
	Require expr %{REQUEST_URI} =~ m#^/campaign/.*.png#
```

**Comment by knadh** [comment]
External authentication is no longer required. You can remove it.

`admin_username` and `admin_password` can now be configured in config.toml or env variables. Please refer to [config.toml.sample'](https://github.com/knadh/listmonk/blob/master/config.toml.sample).

**Comment by sweetppro** [comment]
yup, I have that all configured,
but get an error when trying to add a subscriber via api

**Comment by knadh** [comment]
Are you passing the BasicAuth credentials you've configured to the API endpoints?

For example, with curl, it would be `curl -u username:password -X POST https://localhost:9000/api/subscribers`.

**Comment by sweetppro** [comment]
Ah ok, thx I’ll look into it.
I’m using Ajax

**Comment by knadh** [comment]
If you leave the `admin_username` and `admin_password` fields empty, auth is disabled and you can continue using your old setup.

**Comment by sweetppro** [comment]
Hmm,
That’s much easier.
Thx!

**Comment by sweetppro** [comment]
> If you leave the `admin_username` and `admin_password` fields empty, auth is disabled and you can continue using your old setup.

this doesn't seem to work...

```
admin_username = ""
admin_password = ""
```

**Comment by sweetppro** [comment]
just for completion,
I was using the API to generate users via a custom form,
which I just could not get working...

Ive changed to using the inbuilt form and submitting via Ajax and parsing the response.
