### ISSUE TITLE
Plain text email content

### ISSUE THREAD

**Issue by root-io** [knadh/listmonk#1730]
I want to set my campaign content as plain text but the issue is I am forced to use a HTML template wrapping it.

My feature request is either to be able to not associate my campaign content to any templates and/or be able to create a raw text template instead of raw HTML.

**Comment by ondrejvrabel** [comment]
I had the same issue and I was able to solve it by creating new template called "Plaintext" with content '{{ template "content" . }}'. This way there is no HTML wrapper around and you can easily select the plaintext template. Or you can add useful content to the template too, like unsubscribe link or signature.

**Comment by knadh** [comment]
Yep, this is the right way to do it @ondrejvrabel.

**Comment by root-io** [comment]
Thanks, it worked!
