### ISSUE TITLE
Unsuscribe stats from campaing

### ISSUE THREAD

**Issue by javipj** [knadh/listmonk#1731]
Hello,

How can i know the new unsuscribe users from certain campaing? Is It possible?

Thanks

**Comment by knadh** [comment]
listmonk doesn't have a UI for this currently.

**Comment by CReimer** [comment]
@knadh How can this be closed as completed? Did you add the missing UI for this?

**Comment by knadh** [comment]
Hi @CReimer. This isn't in the immediate roadmap. Please feel free to open another descriptive issue with a draft spec of how such a feature should look like, and we can continue the discussion there.
