### ISSUE TITLE
Load external fonts to my message

### ISSUE THREAD

**Issue by flashdens** [knadh/listmonk#1732]
Hello,

I've been trying to use google fonts in my letter in this manner

`<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bruno Ace:wght@400&display=swap" />`

but this does not seem to have any effect. Does listmonk support this type of feature or there's an other way of doing so?

**Comment by knadh** [comment]
Hi @flashdens. Pretty much all mail clients strip out external CSS and fonts. Custom fonts are unsupported in e-mails by most mail clients.
