### ISSUE TITLE
Please simplify the process for switching to plain-text system email

### ISSUE THREAD

**Issue by rt4mn** [knadh/listmonk#1734]
**Is your feature request related to a problem? Please describe.**

I am currently 45 minutes into the process of following the steps outlined [here](https://listmonk.app/docs/templating/#system-templates) to try and make system emails sent from us plain text rather then html. the Instructions at the end say:

> To turn system e-mail templates to plaintext, remove <!doctype html> from base.html and remove all HTML tags from the templates while retaining the Go templating code.

That means I have to go through all 10 template files and remove all the html tags, and figure out how to format them with the Go templating code (thats everything between the {{}} right?). I have not even gotten to the part where I will need to edit listmonk's systemd file to add the custom path to this directory by adding the  --static-dir=your/custom/path flag, and after that I'm going to need to figure out how to test all of the various ways the system can email folks. 

Its a lot of rigamaroll to send plaintext email.

**Describe the solution you'd like**

Best: A global "send plain text system email only" option.

Good: maybe provide a different link that folks can wget in the `You can fetch the static files with:` step of the docs, such that when they wget those static files, everything in the sent emails is plaintext rather then requiring folks to manually edit them. I'd be happy to do pull request with all my plain text templates (right now I'm just trying to strip out the html so they should be the same) once I have verified that they work. 

Intermediate / temp: update the documentation to better explain the process  (IE, dont assume people automagically understand how to "remove all HTML tags from the templates while retaining the Go templating code.")

**Comment by rt4mn** [comment]
I am now dealing with a bug where the public form to subscribe is broken. I think its this: https://github.com/knadh/listmonk/issues/1708

This is just one example of why requiring users to dig into the guts of their instillation via nano (and telling them to download files that have data that dont work bc wrong version?) is not the right way to change how emails are formatted.

**Comment by rt4mn** [comment]
> Copying and modifying static system templates is for the rare usecase when you also want to turn the automated system e-mails (opt-in, unsubscribe notifications etc.) also plaintext. Is that what you're trying to achieve?

Yup, this is what we want! We dont want the first "confirm your subscription" email that folks get to be an html formatted email, since the kinds of people who subscribe to our lists are the kinds of people who are inherently suspicious of html formatted email (we are an anti-mass surveillance org), and I think its more in line with our stated goals and values to send only plain text email, even when its system email.

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0

**Comment by LeoVS09** [comment]
Hello @knadh, we just integrated Listmonk and were surprised that it does not support plaintext emails out of the box. And as far as I get, the only way to send emails in plaintext is to write them in code? This defeats the purpose of integrating listmonk, it is simpler to use the SMTP library then.
