### ISSUE TITLE
TrackLink doesn't work within markdown

### ISSUE THREAD

**Issue by frostyfrog** [knadh/listmonk#1735]
**Version:**
 - listmonk: v3.0.0
 - OS: Docker (Linux)

**Description of the bug and steps to reproduce:**
When experimenting with a campaign and adding tracking links, I found out that the tracking links are not turning into links and are instead being displayed as plain text. I believe that this is due to the following code *first* rendering the markdown, followed by rendering the template. Since `{{ TrackLink "https://example.com" }}` is not a link according to markdown, it renders it out as text.

https://github.com/knadh/listmonk/blob/3e06b29b0ae0aa4158bb61f77eb967a0459420ec/models/models.go#L559-L596

Reproduction is simple. Try to create a link via either the `[Title](link)` or (`[Title][ref]` followed by `[ref]: link`) and use a the template TrackLink function to generate a link. The resulting HTML will show the failure to render as a link.

**Screenshots:**
![2024-02-16-193047_393x210_scrot](https://github.com/knadh/listmonk/assets/509363/3ef8135b-9a12-47d2-a03e-a66bc4de3725)
![2024-02-16-193134_611x278_scrot](https://github.com/knadh/listmonk/assets/509363/230e4f07-e50f-4080-b3ea-5c1353659f4f)

**Comment by knadh** [comment]
That's not correct Markdown. You're missing the parenthesis. It should be:

`[link1]({{ TrackLink "https://listmonk.app" }})`

**Comment by frostyfrog** [comment]
If it's not correct markdown, then why did the other link work?

**Comment by frostyfrog** [comment]
I was following "reference style links" which does not use parenthesis: https://daringfireball.net/projects/markdown/syntax#link

**Comment by knadh** [comment]
hm, I'll investigate this. Please try the alternate syntax:

`[Link](https://listmonk.app@TrackLink)`
