### ISSUE TITLE
"a non-empty Access Key (AKID) must be provided in the credential" using IAM role to upload media to s3 bucket

### ISSUE THREAD

**Issue by bombergio** [knadh/listmonk#1743]
I want to use the IAM role attached to the instance to upload media to the S3 bucket. Listmonk is set with the empty AWS access key and AWS access secret. The S3 backend URL is set to `https://s3.us-east-1.amazonaws.com`.
When I try to upload media, I'm getting:
```
error uploading file: status code: 400 Bad Request: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential.</Message><RequestId>28VC95QZRTVTE8VX</RequestId><HostId>fZDRsxXIkQzCGWnC2aOkfIUp8+Zret5kUCreAIRvSNUyPxJ046cPbEUgswtB/I6Jc/IFJwry1+w=</HostId></Error>"
```
The `aws s3 ls <bucket-name>` command from the same instance works perfectly fine, so this is not an IAM permissions issue. Same for the `aws sts get-caller-identity`.
Is IAM role-based access to S3 supported?

**Comment by knadh** [comment]
Hi @bombergio. IAM based access is not supported. It has to be an access key / secret.
