### ISSUE TITLE
Support for other Databases

### ISSUE THREAD

**Issue by wakaztahir** [knadh/listmonk#1747]
**Is your feature request related to a problem? Please describe.**
listmonk doesn't provide support for other dbms, I have a single VM in google cloud, I don't want to create more VM's because its costly

**Describe the solution you'd like**
I use MongoDb in production, I would love it if listmonk would allow you to configure it in a single mongo database, I think database code should be abstracted, support for configuring multiple databases should be provided

**Comment by MaximilianKohler** [comment]
Why would you need another VM? Why can't you just install and use postgres for listmonk and MongoDb for whatever else you have?
