### ISSUE TITLE
Adding an email to a list fails if the email address has already been added to a different list

### ISSUE THREAD

**Issue by corstian** [knadh/listmonk#175]
When adding an email address which already exists in any other list, adding the email fails. Although changing the already existing email address succeeds, I would expect that adding an email address to a list (for example through the form) would add the list to the potentially pre-existing entry.

**Comment by knadh** [comment]
hm, silently overwriting an existing entity is not good behavior though. The right way here would be to catch the error and then make an update call (if that's what's required in your scenario).
