### ISSUE TITLE
Authentication Error: Failed Email Send Attempt

### ISSUE THREAD

**Issue by simo25us** [knadh/listmonk#1750]
When attempting to send a test email, I encountered an authentication issue with the mail server. 

The error message **'535 5.7.8 Error: authentication failed: Invalid authentication mechanism'** indicated that the authentication mechanism used was invalid.

 The email client was configured to use the SMTP server at 'mail.xxxxx.com' on port 587 with the authentication protocol set to LOGIN and TLS enabled using STARTTLS. 
Despite these settings, the authentication process failed, preventing the email from being sent.

![errror](https://github.com/knadh/listmonk/assets/159400448/5f43cd31-cb59-4fe3-b95a-253531920abb)

**Comment by simo25us** [comment]
Problem solved, thanks

**Comment by MaximilianKohler** [comment]
>Problem solved, thanks

How?

**Comment by simo25us** [comment]
> > Problem solved, thanks
> 
> How?

change login to plain
