### ISSUE TITLE
Random Template Retrieval Issue with {{ template "content" . }} Expression

### ISSUE THREAD

**Issue by simo25us** [knadh/listmonk#1752]
It sounds like there's a problem with your template retrieval process. When you try to save or preview a template using the expression **{{ template "content" . }},** it's fetching a random template instead of the one you intended.

![camping](https://github.com/knadh/listmonk/assets/159400448/9f990613-6604-4ab6-80ef-1ff430e4f3a0)
![this not template](https://github.com/knadh/listmonk/assets/159400448/f86678f5-4cc8-42c8-ae8d-e5b275b6292e)

When I don't put an expression

![errror black](https://github.com/knadh/listmonk/assets/159400448/edb04b11-31ca-424e-9140-f3de70eb9655)

**Comment by knadh** [comment]
Hi @simo25us. That's dummy content being injected for the sake of preview. It won't be in the actual campaign.
