### ISSUE TITLE
No Images In Email

### ISSUE THREAD

**Issue by PGC-CBeyor** [knadh/listmonk#1753]
**Version:**
 - OS: Ubuntu 22 Docker

**Description of the bug and steps to reproduce:**
When I create a campaign and preview it I can see images showing properly but once the email is sent there arent any images in it. I have tried uploading images, linking local, and linking public images all with the same results.

**Comment by knadh** [comment]
- In the delivered e-mail, have you inspected the image URLs? Are they proper? Are they broken?
- If they are proper, opening those URLs, what do you get? A 404?
