### ISSUE TITLE
no paging in list management page. 

### ISSUE THREAD

**Issue by lovejieer** [knadh/listmonk#176]
1. no paging in lists page
2. after creating list then no notification response. (Uncaught (in promise) TypeError: Cannot read property 'data' of null)
3. when refresh other page but not list, the /api/lists loading again. like media page. 
you can check it in chrome F12

**Comment by lovejieer** [comment]
2 was solved.
lists.go
handleCreateList(c echo.Context) 

`return c.JSON(http.StatusOK, handleGetLists(c))`
change to -->
`return handleGetLists(c)`

**Comment by lovejieer** [comment]
1 solved.

https://github.com/knadh/listmonk/compare/master...lovejieer:patch-1

**Comment by lovejieer** [comment]
3 solved. i got your idea.

**Comment by knadh** [comment]
Can you send a PR for list pagination? I missed it in the last update.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/8fe601aa4a96ececd45c518991ed9d59907d0234 adds this.
