### ISSUE TITLE
Optimizing Message Delivery

### ISSUE THREAD

**Issue by simo25us** [knadh/listmonk#1760]
I want to send one message every 1 minute but unfortunately I see that the messages are being sent so quickly that most of the messages are bouncing

![Capt2ure](https://github.com/knadh/listmonk/assets/159400448/65bedb4c-c168-472f-9d28-ccb41169a939)

I made these adjustmentsin Concurrency, Message rate, Batch size, Enable sliding window limit. before sending a message, however I encountered this problem

![window](https://github.com/knadh/listmonk/assets/159400448/18eda7f1-4d7d-49a9-9243-eb229881b850)

![Captunnre](https://github.com/knadh/listmonk/assets/159400448/1cfb34a4-6bb7-4a39-afa4-1082e1672083)

**Comment by MaximilianKohler** [comment]
>the messages are being sent so quickly that most of the messages are bouncing

I have never heard of this. Can you elaborate?

Your log looks normal.
