### ISSUE TITLE
Template: Comparing .Subscriber.CreatedAt to now fails due to null date value

### ISSUE THREAD

**Issue by sjoerdvanderhoorn** [knadh/listmonk#1764]
I am trying to use `.Subscriber.CreatedAt` in a template so I can display a different message based on when a subscriber joined (recent vs long time subscriber). However, I am having a hard time comparing `.Subscriber.CreatedAt` against `now`, because in the listmonk editor, when trying to prevent, CreatedAt seems to have a value of `{0001-01-01 00:00:00 +0000 UTC false}`. The if statement does not seem to handle this well unless I cast it to a date using `date "2006-01-02"`, but in that case it will show as **today**. My below attempt seemed more promising by using `unixEpoch`, but this errors when providing a date.null value.

```js
{{ $now := now }}
{{ $createdAt := .Subscriber.CreatedAt }}
{{ if lt ($now | date_modify "-900h" | unixEpoch) ($createdAt | unixEpoch) }}
  <h1>Thank you for recently joining.</h1>
{{ else }}
  <h1>Thank you for being a subscriber for so long.</h1>
{{ end }}

<table>
  <tr><td>.Subscriber.CreatedAt</td><td>{{ .Subscriber.CreatedAt }}</td></tr>
  <tr><td>.Subscriber.CreatedAt (formatted)</td><td>{{ .Subscriber.CreatedAt | date "2006-01-02" }}</td></tr>
  <tr><td>~30 days before today (formatted)</td><td>{{ now | date_modify "-900h" | date "2006-01-02" }}</td></tr>
</table>
```

Does anybody have a hint on how to properly compare `.Subscriber.CreatedAt` against `now | date_modify "-900h"` so it can toggle a message based on how long someone has been a subscriber?

**Comment by knadh** [comment]
Ah, this is happening because in the campaign preview mode, there's no value for createdAt. When the campaign is sent, every subscriber will have a value for this field. I'll fix this so that even in preview, there's a valid dummy value for createdAt so that template previews don't break.

For the time being, you can use an `if` to check validity like this:
```go
{{ if .Subscriber.CreatedAt }}
Stuff here.
{{ end }}
```
