### ISSUE TITLE
SMTP setting error using Pikapod during initial configuration

### ISSUE THREAD

**Issue by Vania-02** [knadh/listmonk#1765]
Hello, I'm trying to create a newsletter using Listmonk for a gmail address. As I'm not familiar at all with all the terminology and coding surrounding Listmonk, I decided to try an option that seemed easy by hosting the server on PikaPods and followed this [video : ListMonk Open Source App: How to Create Email Campaigns?](https://www.youtube.com/watch?v=Myq8MqT9xfM&t=57s&ab_channel=PikaPodsOpenSourceAppHosting).

At the step of changing SMTP settings and testing the connection, I got the following error: 

> dial tcp: lookup _mygmailadress@gmail.com_: no such host

Can someone help with this? I can give you more informations if needed. Thanks in advance.

**Comment by knadh** [comment]
Looks like you've misconfigured the SMTP Host field. It should be `smtp.gmail.com`. In the SMTP settings, click on "Gmail" to auto-fill the necessary settings and simply enter the username and password.

![image](https://github.com/knadh/listmonk/assets/547147/b7123e7c-a81a-4715-8c60-ce6789e0ed0e)

**Comment by Vania-02** [comment]
Thank you @knadh, this first error message disappeared to be replaced by an other. As advised, I clicked on "Gmail", left the Host field as the default "smtp.gmail.com", and put my Gmail address in "Username" as well as the related password. This is the new error message :

> 535 5.7.8 Username and Password not accepted. For more information, go to
5.7.8  https://support.google.com/mail/?p=BadCredentials pf10-20020a056214498a00b0068f914ac80bsm6324273qvb.50 - gsmtp

After that, I tried using STARTTLS as in your print screen but I get an "EOF" message and no mail is received at my "To e-mail".

I also tried to use my Listmonk username and password just in case but it leads me to the error message quoted above.

**Comment by knadh** [comment]
The error message from Google clearly says that it's an issue with your username and password, not any other settings.

Please follow these instructions to generate "app passwords" for your Gmail that'll allow you to authenticate via SMTP: https://support.google.com/mail/answer/185833?hl=en

**Comment by Vania-02** [comment]
Generating an "app password" for the Google account and using it in the password field of the SMTP setting page solved the problem. Thanks for your help, it is really appreciated.
