### ISSUE TITLE
Can we add subscribers while updating status in campaign 

### ISSUE THREAD

**Issue by liza-nt** [knadh/listmonk#1766]
I am using twp apis of listmonk first one is create campaign then updating status of it
so i need to add subscribers in that not the list how we add subscriber inhere
 /api/campaigns/{campaign_id}/test
 (https://listmonk.app/docs/apis/campaigns/#post-apicampaignscampaign_idtest)
 Is that possible ??

**Comment by knadh** [comment]
You attach a list (ID) to a campaign when creating it. You don't directly attach subscribers to a campaign.

To test a campaign, you can pass the e-mails of existing subscribers. Campaign test mails will be sent to them but they won't be attached permanently to the campaign.
