### ISSUE TITLE
How to a list's subscriber

### ISSUE THREAD

**Issue by liza-nt** [knadh/listmonk#1768]
I need to check my list's subscriber and update it how to do that

**Comment by knadh** [comment]
Click on the number or "View" link next to the list on the lists page.

**Comment by liza-nt** [comment]
I meant in api is it possible to update subscriber of list in a api

**Comment by knadh** [comment]
Yes. In the `PUT /api/subscribers/:id` request, you can send the array `lists: [1,2,3]` (where the numbers are list IDs).

**Comment by liza-nt** [comment]
can we do it other way like update subscribers in list?Is it possible??
