### ISSUE TITLE
Campaign cron scheduling

### ISSUE THREAD

**Issue by hovanessb** [knadh/listmonk#1769]
**Is your feature request related to a problem? Please describe.**
I see there is an option to schedule when a campaign goes out in the future, but what is lacking is setting a campaign to go out weekly or monthly.

**Describe the solution you'd like**
If I were to program a cron scheduling option would this be accepted into the project or would developing a plugin be more of an acceptable solution?

**Comment by knadh** [comment]
Hi @hovanessb. Sending a campaign weekly/monthly will be tricky as listmonk doesn't keep track of individual subscribers who've received an e-mail for you to figure out whom the campaign should go to at a later period.

**Comment by knadh** [comment]
Doing this externally using APIs to create and start campaigns via an external script+cron should be straight forward. I'd suggest you try the latter solution you suggested, doing this externally.
