### ISSUE TITLE
Campaign planified => Attachment disappear

### ISSUE THREAD

**Issue by ArabianCat** [knadh/listmonk#1770]
**Version:**
 - listmonk: 3.0.0
 - OS: Ubuntu 22.04

**Description of the bug and steps to reproduce:**
When I planned an email with an attachment, the attachment disappear few minutes agos. So when the email has been send, the receiver don't have the attachment.
Can u fix it ?

**Comment by ArabianCat** [comment]
Hello,
I specify I try many times with many compaign, and the problem is same.
Cordially

**Comment by knadh** [comment]
I am unable to reproduce this. Tried the following:
- Create a campaign, add attachment and save. Switch content to plaintext and then send. Works fine.
- Create campaign, switch to plaintext, add attachments and send. Works fine.

**Comment by ArabianCat** [comment]
Hello.
The problem appears during campaign planning, not in creation and send of the campaign.

**Comment by MaximilianKohler** [comment]
@ArabianCat you should list your steps.

**Comment by ArabianCat** [comment]
Ok I'll list : 
- First, I create the campaign, i select a template, add a text and add a attachment
- Secondly, I plan my campaign (for exemple, tommorow at 9 AM

And few minute laters, the attachment dispair in the planned campaign.

**Comment by knadh** [comment]
I'm unable to reproduce this.
- Create campaign.
- Enter text.
- Add attachments.
- Set schedule.
- Save

Attachments don't disappear.

**Comment by ArabianCat** [comment]
Hello @knadh ,
I make a campaign planned yesterday with an attachment.
Today, the attachment dispair.
I think after 24h of schedule, the attachment dispair (Last time it was a campaign planned for a week later).

**Comment by knadh** [comment]
Couldn't reproduce this. Created a new campaign, added attachments, scheduled it to be sent after X minutes. Came back and the campaign was sent, attachments were delivered and were still visible on the campaign.

There is no logic in listmonk that removes attachments from a campaign automatically.

**Comment by ArabianCat** [comment]
The problem is not resolved.
Maybe it's not logical but it's a true problem.
All the attachment disparair after approximatly 24 hours on all campaign (send or not) and it's a true problem.

**Comment by ArabianCat** [comment]
I test yesterday, and i've the problem, so the problem is real.

**Comment by knadh** [comment]
Could you share screenshots of the steps you’re following? How the campaign looks when it is created and what happens after the schedule triggers it.

**Comment by ArabianCat** [comment]
Okay, I create a campaign planned at tomorow 6:00 PM UTC+1. It's today : 

![image](https://github.com/knadh/listmonk/assets/102919110/613bb5a9-ba79-40db-82b7-6a1296527afa)

![image](https://github.com/knadh/listmonk/assets/102919110/bc7e8aa9-1414-4065-abe7-7f998f7b596d)

I'll send the changement tomorrow

**Comment by ArabianCat** [comment]
![image](https://github.com/knadh/listmonk/assets/102919110/5cabf2d2-367f-46ec-9314-a00e54353f42)

**Comment by knadh** [comment]
This is really weird. As I said, there's no logic in listmonk that removes attachments automatically. It can only happen when: a) the file is deleted from media b) the attachment is removed from the campaign explicitly.

Nonetheless, I've scheduled a campaign in my test setup for 24 hours to try and reproduce this.

Are you 100% sure that you don't have an API integrations that may be updating the campaign or deleting media?

**Comment by ArabianCat** [comment]
Hello, sorry for the waiting.

I don't have API on listmonk. I just install it, add by CSV the recipients with list.
I know it's weird, but the problem is true :/

**Comment by knadh** [comment]
> Nonetheless, I've scheduled a campaign in my test setup for 24 hours to try and reproduce this.

Tested two scheduled campaigns on our production instance. The attachments didn't disappear. Unable to reproduce this ;(

**Comment by ArabianCat** [comment]
Ohh... Strange...
I don't understand this problem, and I try to solve & understand it, but it's complicated

**Comment by ArabianCat** [comment]
Hello Knadh,
Sometimes, the attachments of a campaign don't dispear (today, the attachements of a campaign dated a 04/29 don't dispear, but the attachements of a campaign dates a 04/25 dispear).
I try to understand the logic, but it's very weird.

**Comment by ArabianCat** [comment]
Hello Knadh,
The problem is always present.
Can you investigate ?
Thanks you.

**Comment by zevszym** [comment]
Hello All, 
I use v3.0.0 (f9120d9 2024-02-04T11:20:27Z, linux/amd64) from stock docker-compose from this repo. 
In my case can be reproduced by: 
1. Create Campaign named Campaign01, add content  + attached a.pdf, b.pdf, c.pdf from filesystem storage => attachments exist and work on Campaign01
2. Create Campaign named Campaign02, add content  + attached d.pdf,  e.pdf, f.pdf files from filesystem storage => attachments exist and work on Campaign02 but vanish from Campaign01
3. Create Campaign named Campaign03  , add content  + attached g.pdf,  h.pdf, i.pdf files from filesystem storage => attachments exist and working on Campaign03 but vanish from Campaign02, Campaign01 still without attachments 

table public.campaign_media on db represent actual state of webui (allways show 3 attachments)
When I populate data directly to database by
`
TRUNCATE TABLE public.campaign_media;
INSERT INTO public.campaign_media(
	campaign_id, media_id, filename)
	VALUES 
	(2, 20, 'a.pdf'),
	(2, 18, 'b.pdf'),
	(2, 13, 'c.pdf'),
	(5, 24, 'd.pdf'),
	(5, 22, 'e.pdf),
	(5, 14, 'f.pdf'),
	(3, 21, 'g.pdf'),
	(3, 19, 'h.pdf'),
	(3, 15, 'i.pdf')
	;

`
after inserts all three Campaigns have working attachments. Attachments in this Campaign exist until one of the campaigns is edited. After edit random Campaign,  two of not edited loose thearis attachments.
