### ISSUE TITLE
Segment list based on open views or clicks

### ISSUE THREAD

**Issue by graphicmist** [knadh/listmonk#1771]
I am using listmonk to send marketing campaigns and i want to segment my list further based on open and click actions on my email. My query is does listmonk stores views and clicks based on each subscriber, so that segmentation is possible. If not, what are my other options to achieve it?

PS: Thanks for building listmonk. Loving it!

**Comment by MaximilianKohler** [comment]
/admin/settings -> Individual subscriber tracking

**Comment by graphicmist** [comment]
Thanks for pointing this out
