### ISSUE TITLE
Nested Go templaate expressions

### ISSUE THREAD

**Issue by graphicmist** [knadh/listmonk#1772]
Hi,

I am trying to create a nested template expression given below:
 `<a href="https://example.com/?utm_source=newsletter&utm_medium=email&utm_campaign={{ .Campaign.Name }}@TrackLink">`

This is not working. Need advise?

**Comment by etranger7** [comment]
This is the updated expression. Other issues already have this solution but in case you find yourself in this issue and getting an error for 2 args instead of one:

```
{{ $link := print "https://www.example.com?uuid=" .Subscriber.UUID }}
<a href="{{ TrackLink $link . }}">Link Text</a>
```
