### ISSUE TITLE
[Question] Dynamic Variables in href along withTrackLink

### ISSUE THREAD

**Issue by sufyan297** [knadh/listmonk#1775]
Hello,

**Listmonk version**: v2.5.1

I want to use **{{ .Subscriber.Name }}** in an href along with TrackLink. I am aware that this will create multiple track links with the same URL but different parameters.

`<a href="https://google.com/?name={{ .Subscriber.Name }}@TrackLink">Click To Follow</a>` 
Above code generates the TrackLink but it does not replace variable with value.
![image](https://github.com/knadh/listmonk/assets/836773/67bfe858-32f0-4a39-9d71-73c0475206bd)

**Comment by knadh** [comment]
You can try this approach: https://github.com/knadh/listmonk/issues/1772
