### ISSUE TITLE
Customizing templates while using PikaPods as 3rd party host

### ISSUE THREAD

**Issue by Vania-02** [knadh/listmonk#1776]
**Listmonk v3.0.0
Hosting : PikaPods**

I'd like to **customize the opt-in form** and other confirmation mails my subscribers would receive in order to **change the language** it is using. I've seen past issues such as #1503 and #279 as well as the Templating section of the documentation : [https://listmonk.app/docs/templating/#system-templates](https://listmonk.app/docs/templating/#system-templates). 

As I understand it, I'm supposed to copy a directory locally, make changes to some code and indicate a path for Listmonk to fetch these. However, I don't see at all what this refers to, and my guess is that I don't have access to these files as I don't run anything locally but rather use PikaPods. In an other issue, someone mentioned that [there is no access to database using PikaPods](https://github.com/knadh/listmonk/issues/979#issuecomment-1276744865). 

**Questions:**
Is the problem the fact that I use PikaPods for hosting which doesn't grant me access to static files etc?
If not, how do I change templates for opt-in forms ? 
If PikaPods is the problem, what are the solutions available for less tech-savvy persons ? 

Thanks for your help

**Comment by knadh** [comment]
Hi @Vania-02. I'm not familiar with PikaPods but found this with a quick search: https://docs.pikapods.com/apps/listmonk

Looks like they allow filesystem access via SFTP.

**Comment by Vania-02** [comment]
Thanks, I missed this information. I now have access to the files using WinSCP.
