### ISSUE TITLE
Can we update subscribers in a list in api

### ISSUE THREAD

**Issue by liza-nt** [knadh/listmonk#1781]
listmonk has PUT /api/subscribers/:id request, where we can send the array of id of lists : [1,2,3] 
is there other way where we can update subscribers to list like we can send array of subscriber id to list

**Comment by knadh** [comment]
Yes.

```
PUT /api/subscribers/lists

{"action":"add", "target_list_ids":[1, 2], "ids":[1, 2, 3 .........]}
```

I don't think this is documented. You can inspect these APIs on the subscribers admin UI. The bulk list management options are revealed when you click on the select box in the table header.

**Comment by liza-nt** [comment]
Thanks a lot..
one more question can we sync sunscribers in list 
like i have subscriber id 1, 2, 3 in list 1
but when i am calling update api i have subscriber id 1, 3, 4 for list 1
so i need to remove list 1 from subscriber 2 
Is that possible??

**Comment by liza-nt** [comment]
Thanks a lot..
one more question can we sync sunscribers in list
like i have subscriber id 1, 2, 3 in list 1
but when i am calling update api i have subscriber id 1, 3, 4 for list 1
so i need to remove list 1 from subscriber 2
Is that possible??

**Comment by liza-nt** [comment]
Or we have call both api for put and delete

**Comment by knadh** [comment]
You've to issue two calls, one to remove and one to add.

**Comment by liza-nt** [comment]
how to get subscribers of particular list
if i am using this
curl -u 'username:password' 'http://localhost:9000/api/subscribers?list_id=1&page=1&per_page=100'
i am getting subscribers which are not list 1

**Comment by liza-nt** [comment]
can you tell me delete api its not working for me
PUT /api/subscribers/lists

{"action":"delete", "target_list_ids":[1, 2], "ids":[1, 2, 3 .........]}
