### ISSUE TITLE
Trigger to send emails x time before x attribute

### ISSUE THREAD

**Issue by rauldeheer** [knadh/listmonk#1783]
Hey! We're considering using Listmonk for our marketing/informative mails. 

The whole feature set looks amazing, but I'm just wondering if it is possible to create a automation which sends an email x time (10 days for example) after/before a certain date (from the subscribers attributes). So for example:

Our subscribers all have a visitDate attribute. Now I want every subscriber to receive an email with additional information about their visit 5 days before their visit (not marketing related) and another email 5 days after their visit to ask for a review (marketing related).

Would something like this be possible within Listmonk? I'm technical, so if I have to create something myself that would be possible.

**Comment by knadh** [comment]
Hi @rauldeheer. listmonk doesn't support this sort of automation out of the box as its focus is mailing lists/newsletters and not marketing automation. You might want to consider a tool like Mautic instead.
