### ISSUE TITLE
Successful media upload yields 404 on review and embedding of file

### ISSUE THREAD

**Issue by CYPH4R** [knadh/listmonk#1787]
**Version:**
 - listmonk: v3
 - OS: Gentoo

**Description of the bug and steps to reproduce:**
Upload picture through media site, upload is successful, no thumbnail and clicking on uploaded file you get redirected to 404.

I have verified that the files get uploaded to the correct directory with auto-generated thumbnail.

**Comment by CYPH4R** [comment]
Ive look a little bit closer and saw that the link seems to be badly formatted:
`
https://listmonk.customdomain.com/admin/campaigns/listmonk.customdomain.com/uploads/picture.jpg
`
if I remove the preceding `listmonk.customdomain.com/admin/campaingns` it works and I see the file and can embed it in campaigns

**Comment by knadh** [comment]
This happens when the `Root URL` config in settings is missing the `https://` prefix. Please make sure you've the fully formed URL there.
