### ISSUE TITLE
Resolve subscriber disabled status to respective label

### ISSUE THREAD

**Issue by CodeShakingSheep** [knadh/listmonk#1793]
**Version:**
 - listmonk: 3.0.0
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**
Hi,
and first of all thanks for listmonk. I'm still testing it to use it in production soon. Until now it seems really fast and stable. :)
I just encountered one minor UI issue. Instead of showing a disabled label like "Disabled" for disabled subscribers the UI shows, I suppose, a label id `subscribers.status.disabled`, see screenshot.

**Screenshots:**
![image](https://github.com/knadh/listmonk/assets/19874562/ba35eca6-e94d-4cbd-b884-eb4322b2efeb)

**Comment by MaximilianKohler** [comment]
That's odd. It doesn't even appear to be in the code? https://github.com/search?q=repo%3Aknadh%2Flistmonk+subscribers.status.disabled&type=code - 0 results.

**Comment by knadh** [comment]
Ah, this is from the obsolete `disabled` status from a very early version. It's not used anywhere anymore and subscribers are `blocklisted` instead of `disabled`.

Did you set this status via the API as it's not available on the UI.

**Comment by CodeShakingSheep** [comment]
Yes, I set the status via API as "disabled" is still listed in the API docs, e.g. see here https://listmonk.app/docs/apis/subscribers/#post-apisubscribers

So, I would propose to update API docs and also make the API reject this status. What do you think?
