### ISSUE TITLE
[Proposal] Google Customer Match (GCM) Integration.

### ISSUE THREAD

**Issue by rohanchavan1918** [knadh/listmonk#1794]
**User Story**:
As a Marketing Manager, I want to integrate our email newsletter subscriber list with Google Ads Customer Match. So that we can target our Google Ads campaigns to a highly relevant audience, leading to improved campaign performance and increased customer engagement.

**Acceptance Criteria**:
The system can securely upload / sync our newsletter subscriber list to Google Ads.

**Benefits of integrating newsletter with GCM**:

- Enhanced Targeting:  By using your newsletter subscriber list for Customer Match, you can target your Google Ads campaigns to a highly relevant audience who has already shown interest in your brand or products. This means your ads are more likely to resonate with viewers, leading to increased click-through rates and conversions.

- Improved Campaign Performance: Since Customer Match targets existing customers or warm leads, you can expect better campaign performance compared to reaching a broad audience. This translates to a higher return on investment (ROI) for your ad spend.

- Re-engagement with Inactive Subscribers:  Customer Match allows you to reach subscribers who haven't opened your emails in a while. By showcasing targeted ads, you can rekindle their interest and potentially win them back as active subscribers.

- Cross-Device Reach:  Customer Match enables you to deliver consistent messaging across different devices users might be on. This ensures a seamless brand experience and maximizes the reach of your campaigns.

**Solution**:
A Integrations section can be introduced in the Navigation pane like `Settings > Integrations > Google Customer Match`
There should be 3 sub-settings, 
- Tokens: Pane for tokens settings where users can enter their `access_id, secret` (which they can get from GCP console )
- Accounts: Pane where users can integrate their google account, if already integrated  the linked google account can be shown.
- History: Pane to show the history of syncs

**Lists**:
- A quick action can be added to the "lists" list which on click will create a list on GCM with the same name as the listmonk list and then upload the users (manual sync) similarly an auto sync feature can be introduced later on. 

Currently there's no official Google Ads SDK for golang but the package below is a good alternatives:
https://github.com/shenzhencenter/google-ads-pb

Thanks and regards !
Rohan

**Comment by knadh** [comment]
Thanks Rohan, but this is outside the scope of listmonk. Integration with external CRMs should be built as standalone utilities that utilise the listmonk API to keep lists/subscribers etc. in sync.
