### ISSUE TITLE
Multiple Users connecting on dashboard

### ISSUE THREAD

**Issue by Zathiel** [knadh/listmonk#1796]
**Is your feature request related to a problem? Please describe.**

as a tech lead for a french NPO i need to have multiple accounts on dashboard to permit my commercial team to send mailing list 

**Describe the solution you'd like**

I would like my team to have their own account on the app instead of using the admin account

Regards

**Comment by knadh** [comment]
Tracking here: https://github.com/knadh/listmonk/issues/543
