### ISSUE TITLE
Managing unconfirmed emails

### ISSUE THREAD

**Issue by radioboss** [knadh/listmonk#1799]
I use Listmonk and find it a great solution, thank you!

One small thing that could be improved is managing unconfirmed emails. I have a public (double opt-in) list, and a form on a web site to subscribe. For some reason, there are lots of spam requests that sign up and never confirm their address. Currently I have about 200 such subscribers a day! 

Said that, what could be improved:

1. Dashboard - show the number of active, confirmed emails. Currently it also includes unconfirmed emails, in my case it about triples the number of the real subscribers I have.
2. Add some way to clean-up such subscriptions, e.g. if an email is not confirmed within N days, remove it.

**Comment by knadh** [comment]
Please check out Admin -> Settings -> Maintenance. These don't run automatically, but will get the ability to be scheduled like a cron job in a future release.
