### ISSUE TITLE
Campaign still sends even if the scheduled time is long past

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#1801]
**Version:**
 - listmonk: [eg: v2.5.1]
 - OS: [CentOS 7]

I created a snapshot of my server while there was a campaign scheduled for 8am. It was sent at 8am. At 1pm I created a new server from the snapshot and the campaign was sent out again from the new server. 

The original server is still active and doesn't show any new campaign. The only record of it is on Amazon SES dashboard.

**Comment by knadh** [comment]
- Are there two instances of listmonk somehow running on one database?
- If not, the second snapshot that you created, are you certain it had the "finished" campaign?

If a scheduled campaign is finished in the database, then listmonk obviously can't resend it. The database state is the only source of truth.

**Comment by MaximilianKohler** [comment]
>Are there two instances of listmonk somehow running on one database?

Yes, but on different servers. When you make a backup/snapshot of your server and create a new server from that, it makes an identical copy that is now running "in the background".

>If not, the second snapshot that you created, are you certain it had the "finished" campaign?

It had a "scheduled" campaign, not "finished".

>If a scheduled campaign is finished in the database, then listmonk obviously can't resend it.

Yes, I agree.

I think the core issue is that listmonk will send a campaign out if it's scheduled, regardless of how long past the scheduled deadline it is.

Another way to imagine this is if you schedule a campaign for 8am and your server goes down for 4 hours. When the server comes back up that campaign will be sent off.

**Comment by knadh** [comment]
Ah yes, understood. I think this is the correct behaviour. Campaign is set at 8:00 AM. There's an issue on the server and it's restarted at 8:09 AM. It's right for the campaign to be sent out. Also, it's important to note that this is not a normal everyday scenario.

**Comment by MaximilianKohler** [comment]
Can't there be some limit? 

>There's an issue on the server and it's restarted at 8:09 AM. It's right for the campaign to be sent out.

This is reasonable, but 30+ minutes later not so much. Even if you set the limit to 1 hour after the scheduled time that would be better than nothing.

Because without such a limit there is no way to know about and stop a duplicate campaign from being sent out. I create new identical test servers from snapshots/backups all the time.

**Comment by knadh** [comment]
`30+`, that's subjective. Someone may want a missed campaign to be sent out even if it's days late. Someone may decide to cancel.

As I said, this is a rare scenario where a campaign is forgotten and the server is shutdown or crashes for prolonged periods enough to coincide with the schedule. Don't think there's anything to do in listmonk here.

**Comment by MaximilianKohler** [comment]
> Someone may want a missed campaign to be sent out even if it's days late. Someone may decide to cancel.

Would it be simple enough to give people that option? No one currently has the choice to cancel or not. If you restore a backup or make a snapshot of your server, all scheduled campaigns will get resent without your approval or knowledge. Maybe something in the options area for "_continue trying to send campaign if x time has passed_"?

>As I said, this is a rare scenario where a campaign is forgotten and the server is shutdown or crashes for prolonged periods enough to coincide with the schedule.

This part makes me think you're still not understanding the problem/behavior.

The current behavior caters to the rare scenario where someone will want a scheduled campaign to still be sent out if their server happens to go down around the time the campaign is scheduled.

A less rare scenario is making and using backups and snapshots of servers, particularly for testing purposes. And for these cases the current behavior is highly problematic since it will silently send out all scheduled campaigns again, and there's no way to prevent it.
