### ISSUE TITLE
Does "/upload" need to be publicly accesible?

### ISSUE THREAD

**Issue by Biepa** [knadh/listmonk#1803]
Hey,

I recently started using listmonk. Thank you for creating it. :heart: 
The proxy in use has been configured to only allow the endpoints listed here: https://listmonk.app/docs/configuration/#http-routes
While uploading pictures worked fine, the thumbnail wasn't rendered and the files were not publicly accessible.
I then added "/upload" to the endpoints to be publicly accessible which seem to have fixed this.
Have I missed anything or misconfigured something to have this not working or is the endpoint missing in the documentation?
Thank you

**Comment by jcm-shove-it** [comment]
Hi,
As media uploads are IMHO usually part of campaign html formatted messages, the html reference to the image must be visible when the client (email client) reads the mail.
So my understanding is: The uploads folder with images does not support directory lists, but the images can and should be retrieved via http(s) without additional authorization.
BR, Joerg

**Comment by Biepa** [comment]
@jcm-shove-it 
I see it the same way. Though the Mails sent also use the /uploads folder and the images weren't available with a direct link therefore before allowing the endpoint.
