### ISSUE TITLE
Disabling public subscription form disables the Public API?

### ISSUE THREAD

**Issue by errolt** [knadh/listmonk#1804]
**Is your feature request related to a problem? Please describe.**
I don't want a public subscription form. I only want subscriptions to come from embedded or API sources.
But if I disable the public subscription form, then the /api/public/subscription API endpoint is also disabled?

**Describe the solution you'd like**
I want to be able to disable the public subscription form, without disabling the public API.

https://github.com/knadh/listmonk/blob/d5cfaa9bb333a38668a79a6ea817df23488c1f0a/cmd/public.go#L494-L496

**Comment by knadh** [comment]
Hi @errolt. Having the public API enabled implies that with or without a form, anyone can submit a request to it directly. Enabling the public API while disabling the public form, thus, is only a UI tweak really.

Are you simply trying to hide the public subscription form then? If yes, you can try one of these approaches:
- If you are running a reverse proxy like Nginx, simply block the public URL.
- [Customize the system template](https://listmonk.app/docs/templating/#system-templates) for the form and remove it.

**Comment by errolt** [comment]
Hi @knadh. I will modify the template. It was just a surprise to get a reply of 
`{"message":"That feature is not available."}`
when I tried to call the API. I had to dig though the code to figure out why I was getting that message.
