### ISSUE TITLE
Sending rate limit

### ISSUE THREAD

**Issue by LeoYeAI** [knadh/listmonk#1805]
We currently have a Daily Newsletter with one million subscribers. Our goal is to deliver our newsletters simultaneously every morning, ideally within a 5-minute window, assuming SMTP service provider rates allow.

Previously, we have been utilizing Sendy, and despite AWS providing a send rate of 160 emails per second, we struggled to dispatch over 100,000 emails within an hour.

We are considering a transition to Listmonk and would like to know if it can support the delivery of 1-2 million newsletters in the timeframe we require.

Is Listmonk capable of scaling to meet our need for sending a volume of this magnitude? Any implementation advice or insights into the potential performance on a high-capacity workload like ours would be immensely appreciated.

Thank you for your assistance.

**Comment by knadh** [comment]
Hi @LeoYeAI. Our production instance at work has 15+ million subscribers. We use self-hosted instance of Haraka SMTP on EC2. A single instance does about ~50k/minute. More importantly, we don't send marketing e-mails, only a newsletter and rare announcements, hence, the IP reputation with mail providers has been built over many years which permits high throughput sending.

Technically, the rates can be easily horizontally scaled with more Haraka instances. listmonk has no problems scaling to very high throughputs even on small instance, but the bottleneck is going to be:
- The SMTP server(s).
- Mail providers flagging large/fast volumes of e-mails.

**Comment by LeoYeAI** [comment]
Thanks for the real quick response! Knadh.
