### ISSUE TITLE
Vue 2 is EOL and doesn't receive security updates

### ISSUE THREAD

**Issue by libreom** [knadh/listmonk#1808]
**Is your feature request related to a problem? Please describe.**
Vue 2 is [EOL ](https://endoflife.date/vue)and doesn't receive security updates https://v2.vuejs.org/eol/
**Describe the solution you'd like**
Upgrade to Vue 3 or any other security updates supported js library/framework or buy [commercial support](https://www.herodevs.com/support/nes-vue)

**Comment by knadh** [comment]
Since Vue is used listmonk in the private non-user facing admin UI only, threat vectors are minimal.

Upgrading to Vue 3 is not a trivial project, unfortunately. It's not on my to-do for now. Perhaps it's a PR someone may be willing to invest time in.
