### ISSUE TITLE
Campaign Remains Stalled Even After Pausing It And Restarting App

### ISSUE THREAD

**Issue by PackMeister** [knadh/listmonk#1811]
**Version:**
 - listmonk: v3.0.0
 - OS: 
<img width="1515" alt="Listmonk Campaign Stalled" src="https://github.com/knadh/listmonk/assets/35346304/70526a61-d884-40f1-8e56-ccc8819ad5b9">
Debian 12.5

**Description of the bug and steps to reproduce:**
Noticed the sending of a small campaign had stalled.
Sometimes this has required I changed the SMTP password at my email provider which I did just to be on the safe side.
Listmonk provides a message that settings have changed, to pause server, & restart app...which I did.

I re-tried campaign but it stalls and the settings message remains.

**Screenshots:**

**Comment by knadh** [comment]
>  Listmonk provides a message that settings have changed, to pause server, & restart app...which I did.

If listmonk is restarted, then the message shouldn't remain. If you've a running campaign and you want to change settings, you've to pause it and then change the settings, at which point, listmonk will automatically restart.

If the notice is visible, it means listmonk hasn't restarted.

**Comment by PackMeister** [comment]
Listmonk isn't restarting even after I've paused campaign.
Have tried this through several different browsers, but issue remains.
Is their a Listmonk CLI command I can use to restart the server?

**Comment by MaximilianKohler** [comment]
>Is their a Listmonk CLI command I can use to restart the server?

Yes, but what do your logs say? The fact that you're not sure how to restart listmonk makes me wonder how you were even able to get listmonk set up?

**Comment by PackMeister** [comment]
Logs as of 04-03-2024 showed email authentication failures like I suspected (and corrected).

I confirmed the email SMTP server is working by sending a test message successfully from Listmonk.

But Listmonk WILL NOT restart from the GUI.

So if I have to use kill -9 , I'm happy to do so.

Since ./listmonk --help show NO stop or restart options let me know what I'm overlooking.

**Comment by knadh** [comment]
listmonk not restarting automatically after changing the settings, I've never encountered this before (including the issues filed here). How are you running listmonk? Binary? Docker?

And yes, you can use a `pkill -9 listmonk` to kill it and start it again. If you're using a systemd service to run the binary, `sudo systemctl restart listmonk` like any other app.

**Comment by PackMeister** [comment]
I'm running a binary....

Upon restarting with ./listmonk I now get the following:

2024/04/07 12:20:57 main.go:102: v3.0.0 (f9120d9 2024-02-04T11:20:27Z, linux/amd64)
2024/04/07 12:20:57 init.go:150: reading config: config.toml
2024/04/07 12:20:57 init.go:289: connecting to db: localhost:5432/listmonk
2024/04/07 12:20:58 init.go:618: media upload provider: filesystem
2024/04/07 12:20:58 init.go:541: loaded email (SMTP) messenger: admin@riversidefolksongsociety.org@smtp.ionos.com
⇨ http server started on 127.0.0.1:9000
2024/04/07 12:20:58 bounce.go:133: error scanning bounce mailbox: authentication failed
2024/04/07 12:38:17 init.go:843: reloading on signal ...
2024/04/07 12:38:17 init.go:796: HTTP server shut down
2024/04/07 12:38:18 main.go:102: v3.0.0 (f9120d9 2024-02-04T11:20:27Z, linux/amd64)
2024/04/07 12:38:18 init.go:150: reading config: config.toml
2024/04/07 12:38:18 init.go:289: connecting to db: localhost:5432/listmonk
2024/04/07 12:38:18 init.go:618: media upload provider: filesystem
2024/04/07 12:38:18 init.go:541: loaded email (SMTP) messenger: admin@riversidefolksongsociety.org@smtp.ionos.com
⇨ http server started on 127.0.0.1:9000
2024/04/07 12:38:18 bounce.go:133: error scanning bounce mailbox: authentication failed

-------------------

So there's likely still some kind of interaction with Listmonk and the problem I'd thought I'd sorted out with my SMTP server provider.

The restart message goes away upon restart but when I send a test campaign to a test list I get:

2024/04/07 13:05:57v3.0.0 (f9120d9 2024-02-04T11:20:27Z, linux/amd64)2024/04/07 13:05:57reading config: config.toml2024/04/07 13:05:57connecting to db: localhost:5432/listmonk2024/04/07 13:05:57media upload provider: filesystem2024/04/07 13:05:57loaded email (SMTP) messenger: admin@riversidefolksongsociety.org@smtp.ionos.com2024/04/07 13:05:58error scanning bounce mailbox: authentication failed2024/04/07 13:35:58error scanning bounce mailbox: authentication failed2024/04/07 14:05:58error scanning bounce mailbox: authentication failed2024/04/07 14:09:57start processing campaign (Test List April 7th)2024/04/07 14:09:58error sending message in campaign Test List April 7th: subscriber 1: 535 Authentication credentials invalid2024/04/07 14:09:58error sending message in campaign Test List April 7th: subscriber 3: 535 Authentication credentials invalid2024/04/07 14:09:58campaign (Test List April 7th) finished2024/04/07 14:09:58error sending message 'Finished: Test List April 7th': 535 Authentication credentials invalid

So both upon restart and when actively sending a test campaign i'm getting email-related authentication failures.

**Comment by MaximilianKohler** [comment]
You must have filled out the SMTP settings page incorrectly. There are some tutorials in the docs that you can look through.

**Comment by PackMeister** [comment]
If Listmonk SMTP settings were set incorrectly then it shouldn't have been possible to have a successful email test from Listmonk.

That said, I've opened a ticket with my ISP to see if previous issues regarding SMTP email authentication have reared their head again.
