### ISSUE TITLE
Same user on miltiple lists

### ISSUE THREAD

**Issue by PaulMcF1987** [knadh/listmonk#1816]
My plan is to use this to keep I'm touch with suppliers
I have suppliers who offer various services

My question is
If I send a mail to different lists and some suppliers are on both lists
Will this software recognise this and only email them once or will it work through each list and potentially email the same person multiple times?

**Comment by knadh** [comment]
Yes, a subscriber will get only one e-mail even if they're in multiple lists on the same campaign.
