### ISSUE TITLE
Link Redirect issue

### ISSUE THREAD

**Issue by Edwinsiby** [knadh/listmonk#1823]
href='{{ TrackLink "https://www.something.com/{{.Subscriber.Attribs.Name}}-{{.Subscriber.Attribs.SerialNumber}}?country=us" }}'

this link won't work because it throws an error while templating so I'm using the below link,

"https://www.something.com/{{.Subscriber.Attribs.Name}}-{{.Subscriber.Attribs.SerialNumber}}?country=us@TrackLink" 

Like these links, the attributes are not getting attached. Is there any update?

URL

https://www.something.com/%7B%7B.Subscriber.Attribs.Name%7D%7D-%7B%7B.Subscriber.Attribs.SerialNumber%7D%7D?country=us

**Comment by knadh** [comment]
Please see https://github.com/knadh/listmonk/issues/1772
