### ISSUE TITLE
What Is The Difference Between LOGIN and PLAIN Authentication for Outgoing SMTP Server?

### ISSUE THREAD

**Issue by PackMeister** [knadh/listmonk#1824]
I'm having an intermittent authentication issue with the SMTP server I'm using with Listmonk that **_may_** be related to which of LOGIN and PLAIN is used.

As I can't find anything in the online documentation, can someone clarify the difference and any best practices for when to select LOGIN and when to select PLAIN.

**Comment by knadh** [comment]
LOGIN and PLAIN are login mechanisms that SMTP servers support. A server may support both or either. It’s not a choice you can make on the client side and listmonk has to be configured to use the mechanism the sever requires.

As long as there is TLS (or STARTTLS) support on the server, technically, there isn’t much of a security implication in either of the methods.

See also: https://stackoverflow.com/questions/59464979/what-is-the-difference-between-using-plain-vs-login-in-active-mailer-smtp
