### ISSUE TITLE
What Version(s) of TLS Does Listmonk 3.0 Support

### ISSUE THREAD

**Issue by PackMeister** [knadh/listmonk#1825]
In working through an authentication issue involving Listmonk and the SMTP server I'm using, I learned my SMTP server requires TLS 1.2 or higher.

Does Listmonk's STARTTLS configuration option meet this requirement?

**Comment by knadh** [comment]
listmonk uses Go’s built-in TLS library which has support for both TLS 1.2 and 1.3
