### ISSUE TITLE
Uploading 2 images in a row (among other actions) crashes editor interface

### ISSUE THREAD

**Issue by 3-w-c** [knadh/listmonk#1826]
**Version:**
 - listmonk: 3.0.0
 - OS: Debian 11 (server), various (client)

**Description of the bug and steps to reproduce:**

Campaign content editor interface crashes, especially after trying to insert 2 images consecutively.

1. Deploy a listmonk instance (docker swarm config here: https://git.coopcloud.tech/coop-cloud/listmonk/src/branch/main/compose.yml, manually set SMTP details and uploads path in admin)
2. Create a new campaign
3. Edit campaign content
4. Click insert » image, upload from local computer
5. Click the image upload toolbar button

Then, the interface crashes, preventing further edits, scrolling or saving. 

No errors are shown in the browser console or network tab of developer tools.

Uploading images is the most reliable way to reproduce this problem, but it also happens sometimes when inserting a link, sometimes when trying to bold some text, etc.

I looked for similar issues in the bugtracker here but couldn't find any.

**Screenshots:**

The interface post-crash:

![image](https://github.com/knadh/listmonk/assets/66082850/ae0a2449-c556-49f7-be5a-79e5dc704771)

Video demonstration:  https://nextcloud.autonomic.zone/s/n4DCa9CpTcr3J2n

**Comment by knadh** [comment]
Hi @3-w-c. The editor component is [TinyMCE](https://www.tiny.cloud/).

On Firefox 123, I am unable to reproduce this issue though. The below screenshot shows two images (2K resolution) which I inserted and resized. I am able to insert more images without any slowdown or freezing of the editor.
![image](https://github.com/knadh/listmonk/assets/547147/22bfddb0-addc-4ab9-9e95-e8f99d65b588)

- Which browser are you using?
- Are the images very large in size (MBs)? I don't know if there's a specific size after which TinyMCE grinds to a halt. This could be a bug in TinyMCE that's triggered by a certain condition.
- Are there any browser plugins that may be interfering?

**Comment by 3-w-c** [comment]
Thanks for reply @knadh!

> Which browser are you using?

Happens on both Firefox and Chromium.

> Are the images very large in size (MBs)? 

No, the image in the screenshot of the shells is 22 kb.

> Are there any browser plugins that may be interfering?

It happens with a chromium profile with no active plugins.

**Comment by knadh** [comment]
hm, I'm unable to reproduce this on Firefox 123 or Chromium 123.

![image](https://github.com/knadh/listmonk/assets/547147/7276233e-588d-4ef2-bf26-27163ccb8b5c)

It would be great if someone else could confirm.

- @3-w-c this happens the moment you upload any two images?
- Does this happen on a new campaign or only when a campaign has a specific body?

**Comment by 3-w-c** [comment]
Thanks for trying @knadh :pray: 

> @3-w-c this happens the moment you upload any two images?

Yes.

> Does this happen on a new campaign or only when a campaign has a specific body?

New campaign: no.

However, if I copy/paste [the HTML from a problematic campaign](https://bin.autonomic.zone/?0eca0079edf5b564#3r3X7uBdbtVpPqcyDKThZwJoeg6x77QPu6qragZ61yge) into the new campaign, then the problem starts happening again.

**Comment by MaximeMaW** [comment]
I would like to reopen the issue. 
I am encountering the problem.
Another user of the software on a different install is also encountering the issue.
The OP provided problematic HTML generated by the campaign.
The issue is still present in 6.1.0
What can I provide so that this gets investigated?
