### ISSUE TITLE
&quot; into TrackLink

### ISSUE THREAD

**Issue by Giordano1974** [knadh/listmonk#1827]
HI,
I'm sending the newsletter's html markup from a proprietary cms to Listmonk via the API. The html sent has the double quotes of the link traced encoded, because otherwise it would be misinterpreted as the closing of the href attribute, and it appears like this:

`<a href="{{ TrackLink &quot;https://www.raitalia.it&quot; }}"`

It returns this error:
{"message":"Errore durante la compilazione del modello: error compiling message: template: content:1: unexpected \"\u0026\" in operand"}

I tried @tracklink at the end of the url, 
I tried writing like this
`<a href="{{ TrackLink \"www.examplke.com\" }}"></a>....`

It returns this error:
{"message":"Errore durante la compilazione del modello: error compiling message: template: content:1: unexpected \"\\\\\" in operand"}

I tried like this 
`<a href="{{ TrackLink 'www.examplke.com' }}"></a>`..... 

It returns this error:
{"message":"Errore durante la compilazione del modello: error compiling message: template: content:1: malformed character constant: 'https://www.raitalia.it'"}

Nothing works.

Can you help me?

**Comment by knadh** [comment]
If you try `{{ TrackLink "https://listmonk.app" }}` from listmonk's UI, it works. You can inspect how it's escaped and passed via the API and ensure that the CMS does the same. It looks like the the encoding is going wrong before it's posted to the API.

That said, you can also just use the shorthand that doesn't need quotes.
```<a href="https://listmonk.app@TrackLink">Link</a>```
