### ISSUE TITLE
Metadata (e.g. Subject) in Mail Templates

### ISSUE THREAD

**Issue by m42e** [knadh/listmonk#183]
Hi,

I would like to have a meta part in the *static* email-templates to configure the subject. This way it would be easy to adapt the mails to specific needs.

E.g. a yaml block:

```
---
subject: What a nice subject for a Confirmation
---
<Content>
```

What du you think?

**Comment by knadh** [comment]
Campaign subject lines support the Go templating syntax. You can use `{{ Subscriber.Attribs.city }}, {{ Subscriber.Name }}` etc. along with logic, if you want.

**Comment by m42e** [comment]
I actually tourt about the OptIn email. For now I just forked it and adapted the texts to my need.

**Comment by knadh** [comment]
You need not fork listmonk to customize public templates. You can supply a custom theme with the [`--static-dir` flag](https://listmonk.app/docs/configuration/#customizing-public-templates).

**Comment by m42e** [comment]
Yes,  it the subject line will stay the same. And I wanted it to be German.

**Comment by knadh** [comment]
Ah yes, of course. i18n is on the roadmap and we'll have it soon hopefully.

**Comment by m42e** [comment]
I would have helped there but I have no experience with i18n in go. But feel free to can’t me to translate certain stuff.

**Comment by knadh** [comment]
No problem. Integrating an i18n lib in Go should be straight forward, but composing it in such a way that it works uniformly in the backend and on the Javascript frontend, is where some extra effort will be required. Once it's done, it should be as easy as translating strings in a `de` file. I'll update you here when that's ready.
