### ISSUE TITLE
POST /api/subscribers/query/delete - removing non-existent subscriber returns 200-OK response?

### ISSUE THREAD

**Issue by exeterobserver** [knadh/listmonk#1830]
Hi. First, very many thanks to Kailash and everyone else who has contributed to this fantastic project. We're using listmonk to help power a community-owned non-profit public interest journalism project: we wouldn't be able to do the things we can do with listmonk any other way even if we could afford to pay for a pro platform.

We're running listmonk v3.0.0 on AWS Lightsail in a Docker container, and are handling several website forms using AWS Lambda functions written in Node.js. (Hope that description is sufficient and/or makes sense: we're a million miles away from expertise in these matters.)

The scenario that is confusing us is this: using /api/subscribers/query/delete to remove a subscriber works fine, and a 200-OK response is returned as expected.

However when we use the same method to try to remove an email address that is not already subscribed, a 200-OK response is still returned. Is this also expected or are we doing something wrong in our removeSubscriber function (as follows)?

async function removeSubscriber(formData) {

    const apiURL = 'https://mail.example.com/api/subscribers/query/delete';

    const requestData = {
        query: `subscribers.email = '${formData.email}'`
    }

    const requestOptions = {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Basic ' + base64Credentials
        },
        body: JSON.stringify(requestData),
    }

    return new Promise((resolve, reject) => {
        /* etc */
    });
};

We imagined that attempting to unsubscribe an unknown subscriber would produce a 4** response instead.

We'd be very grateful for any insight into what's going on here :-)

**Comment by knadh** [comment]
Thank you @exeterobserver.

The specific handler in question executes bulk deletes based on an arbitrary expression, for instance, "delete all subscribers with the string 'blah' in the e-mail". It cannot thus meaningfully validate whether the given condition is a valid subscriber or not. The `true` basically implies "the arbitrary query was run and an arbitrary number of matches may have been deleted."

If you want to work on a single subscriber at a granular level, you will have to execute two steps:

1)
```shell
# Pass `email='a@a.com'` as the query string to the `query` param.
curl 'http://localhost:9000/api/subscribers' \
    --url-query "query=email='a@a.com'"
```

2)
The response will tell you whether the e-mail exists in the database or not. If it does, use the subscriber's ID from the response to delete the record: `DELETE /api/subscribers/$id`

This does remind me that fetching a subscriber by e-mail should have a direct query just like fetching by ID. I'll consider adding `GET /api/subscribers/$email`.

**Comment by exeterobserver** [comment]
Hi Kailash. Very many thanks for your very helpful reply. The example code you've included is especially helpful: I'm confident I'll be able to successfully implement the two-step approach you describe. And I'm glad to have prompted consideration of a means to query a subscriber by email address too, as I'm sure others will find that useful too.

I'm not sure of the protocol, but I'm guessing I should now close the issue, with many thanks again.

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0
