### ISSUE TITLE
Show List description on hover

### ISSUE THREAD

**Issue by sjoerdvanderhoorn** [knadh/listmonk#1831]
**Is your feature request related to a problem? Please describe.**
The Description property of lists is not used anywhere. However, it would be very useful if it shows when hovering over the "list tag" fields.

I am adding a PR.

**Comment by knadh** [comment]
Hi @sjoerdvanderhoorn. The list description is rendered on the public subscription pages for end users.

**Comment by sjoerdvanderhoorn** [comment]
> Hi @sjoerdvanderhoorn. The list description is rendered on the public subscription pages for end users.

Thank you for your reply, I did not realize! I believe that makes showing it as a popup when hovering over the "list tag" fields in the administrative environment an even better use case.

Preview of changes made by this PR:
![image](https://github.com/knadh/listmonk/assets/24693534/29bae8d2-ba8c-45dc-a04e-f271776e8ef7)
![image](https://github.com/knadh/listmonk/assets/24693534/bb67f5e7-c0b3-4f6c-9242-3730d416e5f1)
![image](https://github.com/knadh/listmonk/assets/24693534/cc5be274-0a7d-4033-9703-94021b663e27)
![image](https://github.com/knadh/listmonk/assets/24693534/353bab9c-07fb-4071-9bb0-39e891dd7fd3)

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0
