### ISSUE TITLE
OAUTH für GMAIL

### ISSUE THREAD

**Issue by Dolphin1220** [knadh/listmonk#1835]
GMAIL (smtp) does not work anymore, because you need to link the "App" to you GMAIL-Account, you can't use  less save App (only username and passwort) with gmail. I think the are using OAUTH for this, please implement OAUTH for gmail, because without this feature it does not work !

![grafik](https://github.com/knadh/listmonk/assets/123817278/b34fe433-bb34-444a-a4db-40e79235f459)

**Comment by knadh** [comment]
You have to generate a special "App Password" for your Gmail account and use that as the SMTP password. There's no oAuth required.

https://support.google.com/mail/answer/185833?hl=en

**Comment by Dolphin1220** [comment]
i know, but this featuere is not aviable any more, but not problem i use 
an paid SMTP Server, it is much better then gmail 😉

regards
Andy

------ Originalnachricht ------
Von "Kailash Nadh" ***@***.***>
An "knadh/listmonk" ***@***.***>
Cc "Dolphin1220" ***@***.***>; "Author" ***@***.***>
Datum 22.04.2024 10:31:57
Betreff Re: [knadh/listmonk] OAUTH für GMAIL (Issue #1835)

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0
