### ISSUE TITLE
Use golang embed package

### ISSUE THREAD

**Issue by yonas** [knadh/listmonk#1838]
**Is your feature request related to a problem? Please describe.**
You're currently using an external project [stuffbin](github.com/knadh/stuffbin) to accomplish what golang already can accomplish via the embed package.

**Describe the solution you'd like**
Use embed instead of stuffbin.

**Comment by knadh** [comment]
Hi @yonas. embed can't be used in this context as listmonk heavily relies on features that embed doesn't support. Please see this comparison: https://github.com/knadh/stuffbin?tab=readme-ov-file#stuffbin-vs-go-116-embed
