### ISSUE TITLE
Bounces - unexisting email

### ISSUE THREAD

**Issue by Giordano1974** [knadh/listmonk#1839]
I didn't understand if Listmonk reports the bounce if it encounters a non-existent email address while sending. I created a list with 5 recipients, 2 of which had non-existent email accounts. When sending, Listmonk reported 5 emails sent and 0 bounces. I have enabled "enable bounce processing" and I am sending the campaign from a company development server that is not accessible without a VPN. However, the campaigns correctly arrive at the existing boxes. Can you help me understand?
Thank you

**Comment by knadh** [comment]
listmonk will deliver the e-mail to the respective domain (say @gmail.com). The way SMTP works, rarely do you get a reply from the SMTP server (again, say @gmail.com) saying that the address is non-existent. That comes in the form of a failure e-mail at a later point to the original sender's address, which is the bounced e-mail.

To receive bounce e-mails from target mail servers, you should either:
a) setup a dedicated POP mailbox with an e-mail address that is used as the sending address, to which bounce mails come
b) or if you're using an integration like AWS SES, enable the respective configuration in settings to receive bounce "webhooks" from those providers.

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0
