### ISSUE TITLE
Possibility to edit views?

### ISSUE THREAD

**Issue by AshPowell** [knadh/listmonk#1840]
Hi,

Is it possible to edit frontend/src/views ? Perhaps similar to how editing static is possible?

I'd just like to be able to add some basic enhancements such as open rate percentages on listings etc or buttons for saved sql queries for generating temporary lists (for segmenting email sends)

Thanks

**Comment by knadh** [comment]
That’s not possible unfortunately, @AshPowell. That’s the frontend source code that’s compiled and bundled. To edit the frontend, you’ll have to fork listmonk, change the frontend and rebuild and run your own listmonk version.

That said, you should be able to manipulate the frontend to some extend after it’s rendered in the browser by using custom snippets of JavaScript (Admin -> Settings -> Appearance).
