### ISSUE TITLE
Selecting to blocklist a selection, blocklists the whole list

### ISSUE THREAD

**Issue by AshPowell** [knadh/listmonk#1841]
**Version:**
 - listmonk: 3.0
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**
I'm trying to blocklist subscribers who have unsubscribed from a list. So:

1) Select 'unsubscribed' number on a list to go into the unsubscribed users view.
2) Filter subscribers.status = 'enabled'
3) Select top box to select all in view, then click 'Select all 123' next to 20 subscribers selected.
4) Click blocklist and confirm to blocklist 123 subscribers
5) Whole list of subscribers get blocklisted, not the selected query.

The first time this happened I thought I must have selected the whole list by accident, second time I am 100% sure this is a bug, I 100% confirmed I clicked only 123 subscribers and confirmed on the blocklist popup to blocklist 123 subscribers.

Thanks!

**Comment by Bowrna** [comment]
can I take a look into this issue?

**Comment by knadh** [comment]
Yes please. Thank you!
