### ISSUE TITLE
SMTP timeout failure

### ISSUE THREAD

**Issue by krair** [knadh/listmonk#1842]
**Version:**
 - listmonk:  v3.0.0
 - OS: Podman via AlmaLinux 9

**Description of the bug and steps to reproduce:**
I suppose the is related to the other thread(s) on SMTP failure. I am also getting the I/O timeout error as described in https://github.com/knadh/listmonk/issues/1492

I am using Mailjet as my smtp relay.

The initial setup (and test) of SMTP works just fine, the test email works great. However, subsequent emails (like a double opt-in) don't make it to the SMTP server and I get an error in the log:

```
2024/04/24 20:45:11 manager.go:513: error sending message 'Confirm subscription': dial tcp 104.199.96.85:465: i/o timeout
```

If I switch the port to 587 for example, the test email will go through fine, and subsequent messages will go through, but not for long. Switching back to port 465 will also work again for some time, but eventually I hit the same error.

**Comment by knadh** [comment]
hm, this seems related to https://github.com/knadh/listmonk/issues/1837 and similar issues in the past. The app's attempt to establish an outgoing TCP connection fails. This has to be in Docker/network/environment/firewall ... At his point, I'm at a loss ;(

**Comment by knadh** [comment]
When you change any setting and save, listmonk does a full restart. So something's getting flushed/cleared which is why it works. Then whatever's blocking the connection kicks in and connections fail. I'm at a loss here as to what could be blocking the connections and how.

**Comment by krair** [comment]
I think you misread what I said. When I change a setting BUT DON'T SAVE, it also works.

**Comment by knadh** [comment]
That's just a coincidence. Changing the setting on the UI without hitting save has no effect on the backend. That's just a browser/UI thing.

**Comment by krair** [comment]
I tried to create a screen recording to show, and its true I can't get it to reliably reproduce the timeout error every time.

I will try running listmonk as a standalone binary and see if the error still exists. 

Thank you anyways for the great app!

**Comment by MaximilianKohler** [comment]
If you're using docker it may be a firewall issue. See https://github.com/knadh/listmonk/issues/1837#issuecomment-2070181984.

Docker may be opening some ports after you make a change, and then your firewall blocks them again.
