### ISSUE TITLE
Helm chart for installing on kubernetes

### ISSUE THREAD

**Issue by th0th** [knadh/listmonk#1844]
Hey folks,

I was trying to install listmonk on my kubernetes cluster. I saw there is a helm chart created by delivery hero, but the last commit was 3 years ago, I think it is not maintained. And also, it didn't include options to create an ingress, either.

So I created a helm chart, and I wanted to share in case someone else needs it. Here is the chart: https://github.com/th0th/helm-charts/tree/main/charts/listmonk Installation instructions are available on README. I am not sure if helm is a common installation method among listmonk users, if so, I can create a PR adding helm installation instructions to the README here?

**Comment by knadh** [comment]
Thanks @th0th. We can add a "Helm charts" section to the installation doc after the "Release candidate" section here and link it to your repository: https://listmonk.app/docs/installation/

Source: https://github.com/knadh/listmonk/blob/master/docs/docs/content/installation.md

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0
