### ISSUE TITLE
Lists getting corrupted by zwnbsp character

### ISSUE THREAD

**Issue by astick360** [knadh/listmonk#1845]
Version:
 - listmonk: v3.0.0
 - OS: Docker on https://www.pikapods.com/

Description of the bug and steps to reproduce:
Some of my lists, at unknown point get corrupted by zwnbsp ascii character. It doesn't happen on every list of subscribers, i can't find what is the cause of this issue. Every list was upladed same way and worked until some of them got corrupted and if I fix it and upload the subscribers again firstly deleting the wrong ones the list and sending works again. I found out because parts of the campaings weren't being sent. After i exported the corrupted lists i found that some of the records got the "zwnbsp" character added to start of the email address fields as shown on screenshots. I can't find any steps to reproduce this or answer why is this happening. Can someone help me figure this out or advice me where to look for solution so this stops happening?

Screenshots:
Example exported corruped list with censored emails:
![screen1](https://github.com/knadh/listmonk/assets/101253081/826f0784-02b4-4f5e-be00-c0213af6ebed)

One of the problematic campaigns:
![Screenshot_2](https://github.com/knadh/listmonk/assets/101253081/90ccadfc-cd8c-48c1-9516-cc9021832de7)

Logs of the campaign:
2024/04/16 08:29:18v3.0.0 (f9120d9 2024-02-04T11:20:27Z, linux/amd64)
2024/04/16 08:29:18reading config: config.toml
2024/04/16 08:29:18connecting to db: postgres.internal:5432/p20538
2024/04/16 08:29:18loading i18n files from: /listmonk/i18n
2024/04/16 08:29:18loading static files from: /listmonk/static
2024/04/16 08:29:19media upload provider: filesystem
2024/04/16 08:29:19loaded email (SMTP) messenger: xxxxxxx@email-smtp.eu-north-1.amazonaws.com
2024/04/22 06:38:44start processing campaign (Urządzenie wielofunkcyjne Develop)
2024/04/22 06:38:50error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 439330: 501 Invalid RCPT TO address provided
2024/04/22 06:38:50error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 439331: 501 Invalid RCPT TO address provided
2024/04/22 06:38:50error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 439332: 501 Invalid RCPT TO address provided
2024/04/22 06:38:50error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 439333: 501 Invalid RCPT TO address provided
2024/04/22 06:38:50error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 439334: 501 Invalid RCPT TO address provided
2024/04/22 06:38:50error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 439335: 501 Invalid RCPT TO address provided
2024/04/22 06:38:50error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 439336: 501 Invalid RCPT TO address provided

<about 700 of the same lines with different subscribers (i have automatic stop on 1000 not ddelivered mails, so it tried to send to the whole list)>

2024/04/22 06:38:50error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 439338: 501 Invalid RCPT TO address provided
2024/04/22 06:38:51error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 439337: 501 Invalid RCPT TO address provided
2024/04/22 06:38:51error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 439339: 501 Invalid RCPT TO address provided
2024/04/22 06:40:08error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 440370: 501 Invalid RCPT TO address provided
2024/04/22 06:40:08error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 440375: 501 Invalid RCPT TO address provided
2024/04/22 06:40:08error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 440377: 501 Invalid RCPT TO address provided
2024/04/22 06:40:09error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 440389: 501 Invalid RCPT TO address provided
2024/04/22 06:40:09error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 440390: 501 Invalid RCPT TO address provided
2024/04/22 06:40:19error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 440689: 501 Invalid RCPT TO address provided
2024/04/22 06:40:19error sending message in campaign Urządzenie wielofunkcyjne Develop: subscriber 440690: 501 Invalid RCPT TO address provided
2024/04/22 06:40:31campaign (Urządzenie wielofunkcyjne Develop) finished

**Comment by MaximilianKohler** [comment]
zwnbsp is Zero-width non-breaking space. [I noticed that gmail inserts these in their text editor](https://github.com/knadh/listmonk/issues/1102#issuecomment-1368708742). My guess is that it has to do with the way you're copying the emails. Somewhere in the process the ZW space is being created; possibly by a text editor you're using. Notepad++ allows you to view _(and find & replace)_ such characters.

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0

**Comment by astick360** [comment]
closed by mistake im not fluent with github

**Comment by MaximilianKohler** [comment]
The only other thing I can think of is that perhaps the language you're using is a clue. Maybe someone accidentally slipped in some ZW spaces into the code for that particular language. Maybe it's something unique with pikapods + your language?

Otherwise, you'd have to try to get more details on what triggers it to happen on some lists but not others.
