### ISSUE TITLE
Table Borders on Previews and sends

### ISSUE THREAD

**Issue by nachobazz** [knadh/listmonk#1846]
**Version:**
 - listmonk: v3.0.0 
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**
Create a raw HTML content campaign pasting a normal responsive HTML template such as: [https://github.com/leemunroe/responsive-html-email-template/blob/master/email-inlined.html](https://github.com/leemunroe/responsive-html-email-template/blob/master/email-inlined.html)

Both the preview and sent email show all major TABLE borders as grey 1px despite the HTML and CSS indicate they should be invisible. I tested this with several templates and always got the same result.

Any idea why it could be?

**Screenshots:**
Here's a screenshot of how the template looks in preview. Sent email looks identical when received in gmail. I'm under the impression a CSS stylesheet may be overriding some of the styles at send and preview time.

![SCR-20240426-pqp](https://github.com/knadh/listmonk/assets/3536050/ade7d855-17f7-453d-8656-8f890b544d32)

**Comment by knadh** [comment]
I am not sure. It could be G-mail stripping styles. Are styles inline? If you set the mode to Raw HTML in listmonk, it does not make any changes to HTML or CSS.

**Comment by nachobazz** [comment]
It doesn't modify but, it does seem to add a chunk of HTML before the raw HTML which looks like this:

`<!doctype html>
<html>
    <head>
        <title>IMPORTANTE: Playbook de incidentes de seguridad</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
        <base target="_blank">
        <style>
            body {
                background-color: #F0F1F3;
                font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, sans-serif;
                font-size: 15px;
                line-height: 26px;
                margin: 0;
                color: #444;
            }

            pre {
                background: #f4f4f4f4;
                padding: 2px;
            }

            table {
                width: 100%;
                border: 1px solid #ddd;
            }
            table td {
                border-color: #ddd;
                padding: 5px;
            }

            .wrap {
                background-color: #fff;
                padding: 30px;
                max-width: 525px;
                margin: 0 auto;
                border-radius: 5px;
            }

            .button {
                background: #0055d4;
                border-radius: 3px;
                text-decoration: none !important;
                color: #fff !important;
                font-weight: bold;
                padding: 10px 30px;
                display: inline-block;
            }
            .button:hover {
                background: #111;
            }

            .footer {
                text-align: center;
                font-size: 12px;
                color: #888;
            }
                .footer a {
                    color: #888;
                    margin-right: 5px;
                }

            .gutter {
                padding: 30px;
            }

            img {
                max-width: 100%;
                height: auto;
            }

            a {
                color: #0055d4;
            }
                a:hover {
                    color: #111;
                }
            @media screen and (max-width: 600px) {
                .wrap {
                    max-width: auto;
                }
                .gutter {
                    padding: 10px;
                }
            }
        </style>
    </head>
<body style="background-color: #F0F1F3;font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, sans-serif;font-size: 15px;line-height: 26px;margin: 0;color: #444;">
    <div class="gutter" style="padding: 30px;">&nbsp;</div>
    <div class="wrap" style="background-color: #fff;padding: 30px;max-width: 525px;margin: 0 auto;border-radius: 5px;">`


The style affecting the template is this:

`            table {
                width: 100%;
                border: 1px solid #ddd;
            }`

But a few others are undesirable as they set arbitrary width for the template and reduce flexibility.

This seems to be embedded to all emails and it does affect the styles of a raw HTML to be sent. Could I suggest a feature to disable this optionally for raw HTML emails? Most templates include their boilerplate and this affects compatibilty.

Please advise if this is a good suggestion to incorporate in the future.

**Comment by knadh** [comment]
This is your default template being applied to the campaign e-mail. Please go to Campaigns -> Template and edit the default campaign template to suite your needs. If your campaign is fully self-contained and doesn't need stored templates, remove all HTML from the default template and simply leave `{{ content . }}` there.

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0
