### ISSUE TITLE
Resend SMTP

### ISSUE THREAD

**Issue by anaclumos** [knadh/listmonk#1851]
**Version:**
 - listmonk: 3.0.0
 - OS: Railway Docker Image

**Description of the bug and steps to reproduce:**

Using Resend SMTP gives: 

https://github.com/knadh/listmonk/assets/31657298/0237ebb7-69e0-4b79-8424-a273c768a68d

I have confirmed that emails are in valid form.

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox 
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
       🍞Bank Scam Pages
       🍞Greece/USA/UK/French Scam Pages
       🍞Crypto Scam Pages
       🍞Office365 Cookies Grabber
       
✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted 
       🍞All kind of sender available 

✅SMTP To Sms Sender 
       🍞Smtp to sms php sender 
       🍞Sender Id 
       🍞Php Sms Sender USA 

✅ Encrypted Letter To Inbox
       🍞 Show sample and get inbox guaranteed letter. 

✅Email Leads Extractor Any Country
✅Email Leads Verifier 
✅Sms Sender php Version 
✅Sms Leads Extractor 

✅SMTP Servers
      
🔥24/7 Customer Support 
🔥Telegram, Channel 
🔥All Proof on Fire 🔥 
🔥Dont wait, work with me now and become a permanent Customer 

✅ Telegram : @AnonWG4
✅ Channel Link :  https://t.me/+Z4BjtNeklvNjYmI0
