### ISSUE TITLE
automatic --install

### ISSUE THREAD

**Issue by tcurdt** [knadh/listmonk#1852]
**Is your feature request related to a problem? Please describe.**

It seem this the only way to get listmonk up and running in a container deployment is to first run

    command: [sh, -c, "yes | ./listmonk --config='' --install"]

and then later replace that with

    command: ./listmonk --config=""

which is not particular automation friendly.

**Describe the solution you'd like**

It would be so much easier if `listmonk` could just check on startup if the db is still empty.
If it is, run the install procedure.

**Comment by tcurdt** [comment]
It seems like the code is almost here already.

`./listmonk --config="" --yes --idempotent --install --upgrade`

Why exit after the install/upgrade?

**Comment by knadh** [comment]
`--install` and `--upgrade` together don't make sense and are mutually exclusive actions.

A fresh `--install` always installs the latest DB schema. There is nothing to `--upgrade` after that.

> It would be so much easier if listmonk could just check on startup if the db is still empty.
> If it is, run the install procedure.

I think it's not ideal for listmonk (or any app) to perform an implicit destructive action (wiping all existing schema and installing new schema).  Even if the DB is empty, the behaviour should be explicit and reproducible. While in the context of docker, chaining two commands may seem a bit clunky, it's still better to be explicit and composable that way.

**Comment by tcurdt** [comment]
> I think it's not ideal for listmonk (or any app) to perform an implicit destructive action (wiping all existing schema and installing new schema). Even if the DB is empty, the behaviour should be explicit and reproducible.

How is setting up a database a destructive operation? It should just not wipe by default.

Idempotence (of a schema) also seems like a highly desirable goal that lends itself to reproducibility.
If you want to have this really composable this could be an option:

"--install" would be "ensure schema exists".
"--wipe" would "ensure the db is empty"
"--upgrade" would run migrations
"--start" would start the app.

So I would be after "--install --start"

> While in the context of docker, chaining two commands may seem a bit clunky, it's still better to be explicit and composable that way.

What's the solution for a full automatic install then?

With the current commands it seems to always require manual intervention.

**Comment by knadh** [comment]
> How is setting up a database a destructive operation? It should just not wipe by default.

Currently, `--install` deletes every type and table and re-creates them. This is the only way to ensure a clean install. There is no other straight forward way for a broken DB to re-done for instance.

That said, I missed the `--idempotent` flag in your previous example. Since it's possible to compose the commands and achieve this behaviour explicitly, isn't a `--start` flag superfluous?

Example:
`./listmonk --yes --idempotent --install --upgrade && ./listmonk`

Not sure of the Docker convention though. @mr-karan?

**Comment by mr-karan** [comment]
Yep, using `idempotent` ensures that the DB is not wiped at startup. 

> ./listmonk --yes --idempotent --install --upgrade && ./listmonk

Using this as the `CMD` makes sense to me. This will ensure that everytime the docker container is restarted, latest upgrades are automatically applied. First time run, will create the schema as well and start the app. Explicitly chaining commands seems a better flow (UNIX philosophy) than introducing additional flags
