### ISSUE TITLE
Account level access

### ISSUE THREAD

**Issue by maratgaliev** [knadh/listmonk#1853]
Hey, I want to use listmonk and create one account per one customer.
So basically I want to create accounts inside listmonk and use different api keys/credentials to work with API, is that possible?
Something like:
- Account 1: email list1, campaign1
- Account 2: email list2, campaign2
- ...
Thanks!

**Comment by AnonWG4** [comment]
🎫 SMTP, Scam Pages, Links, Hosting, Sender, Leads, Extractor, Verifier

🎟Email Spamming Tools 100% Inbox
🎟Sms Spamming Tools 100% Inbox
🎟Office365 Spammimg Tools 100% inbox
🎟Banks Spammimg Tools 100% inbox

✅Scam Pages, True Login & Anti Bot, uAdmin
🍞Bank Scam Pages
🍞Greece/USA/UK/French Scam Pages
🍞Crypto Scam Pages
🍞Office365 Cookies Grabber

✅Bullet proof Link+SSL+Hosting

✅Email Senders Crack/Encrypted
🍞All kind of sender available

✅SMTP To Sms Sender
🍞Smtp to sms php sender
🍞Sender Id
🍞Php Sms Sender USA

✅ Encrypted Letter To Inbox
🍞 Show sample and get inbox guaranteed letter.

✅Email Leads Extractor Any Country
✅Email Leads Verifier
✅Sms Sender php Version
✅Sms Leads Extractor

✅SMTP Servers

🔥24/7 Customer Support
🔥Telegram, Channel
🔥All Proof on Fire 🔥
🔥Dont wait, work with me now and become a permanent Customer

✅ Telegram : @AnonWG4
✅ Channel Link : https://t.me/+Z4BjtNeklvNjYmI0

**Comment by knadh** [comment]
Hi @maratgaliev. This isn't possible currently. Please see https://github.com/knadh/listmonk/issues/543
