### ISSUE TITLE
Struggling to work out concurrency & message rate

### ISSUE THREAD

**Issue by AshPowell** [knadh/listmonk#1854]
Hi, 

I'm trying to get to 70 messages per second but the configuration settings don't seem to add up or equate to the amount of messages being sent per second.

For example, just testing different numbers - 25 concurrency and 2 message rate - technically should give me 50 messages per second?

It's giving me 1000 per minute so around 16 per second.

I've changed the values, changed the batch but nothing seems to add up to the amount it's sending.

Is there something else I should be looking at?

Thanks

**Comment by knadh** [comment]
Ultimately, it depends on the speed of your network and speed at which your SMTP server accepts and processes e-mails. If despite high concurrency, you're getting 16/sec, that's the bottleneck your network+SMTP is imposing.

**Comment by AshPowell** [comment]
But that doesn't explain why when I lower these figures, the final number is lower... If it was a bottle neck say if I do 25 and 1 the number is lower still but not 25.

The network is DigitalOcean and the SMTP server is SES - I don't think it's a bottleneck ?

**Comment by subhash-ngowda** [comment]
@knadh We are also facing a similar problem. Out SMTP has a very good performance and we are on AWS EC2. I don't think we have bandwidth problem either. Our HTML creative size varies from 10KB to 3KB and the kind of bandwidth that AWS provides is  sufficient enough.   No matter what concurrency that I put, it is not pushing more than 2000 messages / min. When the campaign starts it will be 4000 / min, then reduces to 2000/min after 30 min. I monitor the docker stats and also the system resource utilisation using linux top command. System hardware is under utilised. Do you think running the application on the OS then the docker container help to solve this problem?

**Comment by knadh** [comment]
hmm, not sure what's happening here. We run a small Docker instance with a locally hosted (EC2) SMTP and get 50k/minute.

**Comment by AshPowell** [comment]
> @knadh We are also facing a similar problem. Out SMTP has a very good performance and we are on AWS EC2. I don't think we have bandwidth problem either. Our HTML creative size varies from 10KB to 3KB and the kind of bandwidth that AWS provides is sufficient enough. No matter what concurrency that I put, it is not pushing more than 2000 messages / min. When the campaign starts it will be 4000 / min, then reduces to 2000/min after 30 min. I monitor the docker stats and also the system resource utilisation using linux top command. System hardware is under utilised. Do you think running the application on the OS then the docker container help to solve this problem?

Do you see your figures scale correctly with concurrency & message rate before the limitations?
