### ISSUE TITLE
Allow tracking individual mail openings but not link clicks

### ISSUE THREAD

**Issue by andreagdipaolo** [knadh/listmonk#1856]
**Is your feature request related to a problem? Please describe.**
At the moment Listmonk lets you choose if you want to track individually for every user both mail openings and link clicks.
I believe it would be useful to let the admin decide if tracking both events or only one.
For example, I would benefit from tracking mail openings but I would disable link tracking because I want my subscribers to see the original URL without redirects and I don't care if they open my links.

**Describe the solution you'd like**
The solution would be to split the option in two toggles (and obviously all the code changes in the backend to let it work).
Thanks!

**Comment by MaximilianKohler** [comment]
It already allows this. I don't use link tracking either for the same reason you stated.

**Comment by andreagdipaolo** [comment]
> It already allows this. I don't use link tracking either for the same reason you stated.

Could you show me how? I only see one toggle and it says it will track links and openings. I'm a little bit confused.

**Comment by MaximilianKohler** [comment]
>I only see one toggle and it says it will track links and openings.

Where? Link tracking is done manually. 

Are you referring to `Settings -> privacy -> Individual subscriber tracking`?

**Comment by andreagdipaolo** [comment]
> Are you referring to Settings -> privacy -> Individual subscriber tracking?

Yes, I thought that if I enabled that Listmonk would automatically convert all the links to track them.
Thanks!
