### ISSUE TITLE
unexpected new.line - manager.go

### ISSUE THREAD

**Issue by Saddamus** [knadh/listmonk#1857]
**Version:**
 - listmonk: : v3.0.0
 - OS: Debian , Alpine

**Description of the bug and steps to reproduce:**
Make dist ends up with error:
`CGO_ENABLED=0 go build -o listmonk -ldflags="-s -w -X 'main.buildString=v3.0.0 (#f34d108 2024-05-06T14:03:13+0000)' -X 'main.versionString=v3.0.0'" cmd/*.go
# github.com/knadh/listmonk/internal/manager
internal/manager/manager.go:359:4: syntax error: unexpected newline in composite literal; possibly missing comma or }
make: *** [Makefile:42: listmonk] Error 1
`
Tried with node 16 and several go version on Alpine and Debian. 
What can be he reason ?

**Comment by knadh** [comment]
Hi @Saddamus. Looks like the last PR that was merged introduced a syntax error! :O I've fixed it. Please pull and rebuild.

Will add a GitHub action that runs the build steps as a test so that this doesn't happen in the future.
