### ISSUE TITLE
Error: dial tcp: lookup smtp.sendgrid.net: i/o timeout

### ISSUE THREAD

**Issue by andreamichelon** [knadh/listmonk#1859]
Getting this error when trying to send a test email: dial tcp: lookup smtp.sendgrid.net: i/o timeout

Everything seems to be working on SendGrid and it was working on ListMonk for 4 months. Now, it is throwing this error. What I'm doing worng?

**Comment by MaximilianKohler** [comment]
What did you do/change recently? How are you running listmonk?

**Comment by andreamichelon** [comment]
Nothing has changed. I'm running Listmonk on a Cloudron

**Comment by knadh** [comment]
Looks like a network/firewall issue.

**Comment by candidexmedia** [comment]
@AndreaMichelon Were you able to solve it? I'm also facing this issue https://github.com/knadh/listmonk/issues/2675
