### ISSUE TITLE
Listmonk not working with own server like plesk or aapanel

### ISSUE THREAD

**Issue by anmol7210** [knadh/listmonk#1863]
**Version:**
 - listmonk: [eg: v3.0.0]
 - OS: [e.g. ubuntu 20]

I am using listmonk on ubuntu server , installed using docker
Also using mail server based on postfix which is hosted on different vps, 

Issue: if i try to send email using smtp test tools (https://www.gmass.co/smtp-test), it sends without any issue.
but when i try to send with listmonk, my aapanel email server shows error
the error is about spf or dkim, but  ii have configured dkim and spf correctly, also test smtp is working

Error logs from aapanel email : (above logs are of smtp test, then listmonk)
May 12 09:06:59 ubuntu postfix/submission/smtpd[265006]: connect from ec2-54-212-131-181.us-west-2.compute.amazonaws.com[54.212.131.181]
May 12 09:07:00 ubuntu postfix/submission/smtpd[265006]: 95BB481E18: client=ec2-54-212-131-181.us-west-2.compute.amazonaws.com[54.212.131.181], sasl_method=PLAIN, sasl_username=info@startax.in
May 12 09:07:00 ubuntu postfix/cleanup[264995]: 95BB481E18: message-id=<OMUG9EJ91NU4.F80WNTONHWBG1@WIN-AUIR3RRGP88>
May 12 09:07:00 ubuntu postfix/qmgr[264792]: 95BB481E18: from=<info@startax.in>, size=820, nrcpt=1 (queue active)
May 12 09:07:01 ubuntu postfix/smtp[264964]: connect to gmail-smtp-in.l.google.com[2a00:1450:400c:c0c::1b]:25: Network is unreachable
May 12 09:07:01 ubuntu postfix/submission/smtpd[265006]: disconnect from ec2-54-212-131-181.us-west-2.compute.amazonaws.com[54.212.131.181] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 commands=7
May 12 09:07:01 ubuntu postfix/smtp[264964]: 95BB481E18: to=<anmolsuvidha@gmail.com>, relay=gmail-smtp-in.l.google.com[64.233.184.26]:25, delay=0.96, delays=0.38/0/0.08/0.5, dsn=2.0.0, status=sent (250 2.0.0 OK  1715504821 ffacd0b85a97d-3502bd16064si4323646f8f.646 - gsmtp)
May 12 09:07:01 ubuntu postfix/qmgr[264792]: 95BB481E18: removed
May 12 09:07:07 ubuntu postfix/submission/smtpd[265006]: warning: hostname 65.20.68.152.vultrusercontent.com does not resolve to address 65.20.68.152
May 12 09:07:07 ubuntu postfix/submission/smtpd[265006]: connect from unknown[65.20.68.152]
May 12 09:07:08 ubuntu postfix/submission/smtpd[265006]: 8D14581E18: client=unknown[65.20.68.152], sasl_method=PLAIN, sasl_username=info@startax.in
May 12 09:07:08 ubuntu postfix/cleanup[264995]: 8D14581E18: message-id=<1715504828776238042.1.8216812870832503300@03c120b8c6e8>
May 12 09:07:08 ubuntu postfix/qmgr[264792]: 8D14581E18: from=<noreply@listmonk.yoursite.com>, size=3166, nrcpt=1 (queue active)
May 12 09:07:08 ubuntu postfix/smtp[264964]: connect to gmail-smtp-in.l.google.com[2a00:1450:400c:c0c::1b]:25: Network is unreachable
May 12 09:07:09 ubuntu postfix/smtp[264964]: 8D14581E18: to=<anmolsuvidha@gmail.com>, relay=gmail-smtp-in.l.google.com[64.233.184.26]:25, delay=0.84, delays=0.51/0/0.06/0.26, dsn=5.7.26, status=bounced (host gmail-smtp-in.l.google.com[64.233.184.26] said: 550-5.7.26 Your email has been blocked because the sender is unauthenticated. 550-5.7.26 Gmail requires all senders to authenticate with either SPF or DKIM. 550-5.7.26  550-5.7.26  Authentication results: 550-5.7.26  DKIM = did not pass 550-5.7.26  SPF [listmonk.yoursite.com] with ip: [194.164.30.189] = did not pass 550-5.7.26  550-5.7.26  For instructions on setting up authentication, go to 550 5.7.26  https://support.google.com/mail/answer/81126#authentication ffacd0b85a97d-3502bbe1264si4277955f8f.674 - gsmtp (in reply to end of DATA command))
May 12 09:07:09 ubuntu postfix/cleanup[264995]: 4624A81E1D: message-id=<20240512090709.4624A81E1D@mail.startax.in>
May 12 09:07:09 ubuntu postfix/qmgr[264792]: 4624A81E1D: from=<>, size=6295, nrcpt=1 (queue active)
May 12 09:07:09 ubuntu postfix/bounce[265008]: 8D14581E18: sender non-delivery notification: 4624A81E1D
May 12 09:07:09 ubuntu postfix/qmgr[264792]: 8D14581E18: removed
May 12 09:07:09 ubuntu postfix/error[265009]: 4624A81E1D: to=<noreply@listmonk.yoursite.com>, relay=none, delay=0, delays=0/0/0/0, dsn=4.4.1, status=deferred (delivery temporarily suspended: connect to listmonk.yoursite.com[2606:4700:3035::6815:db2]:25: Network is unreachable)

while it says success in listmonk, i also tried with plesk and cyberpanel, i dont know where they store logs, but they dont send emails the same way

logs from https://www.gmass.co/smtp-test:
Connected to smtp://mail.startax.in:587/?starttls=when-available
<< 220 mail.startax.in ESMTP Postfix (Ubuntu)
>> EHLO [172.31.11.248]
<< 250-mail.startax.in
<< 250-PIPELINING
<< 250-SIZE 102400000
<< 250-VRFY
<< 250-ETRN
<< 250-STARTTLS
<< 250-ENHANCEDSTATUSCODES
<< 250-8BITMIME
<< 250-DSN
<< 250-SMTPUTF8
<< 250 CHUNKING
>> STARTTLS
<< 220 2.0.0 Ready to start TLS
>> EHLO [172.31.11.248]
<< 250-mail.startax.in
<< 250-PIPELINING
<< 250-SIZE 102400000
<< 250-VRFY
<< 250-ETRN
<< 250-AUTH PLAIN LOGIN
<< 250-ENHANCEDSTATUSCODES
<< 250-8BITMIME
<< 250-DSN
<< 250-SMTPUTF8
<< 250 CHUNKING
>> AUTH PLAIN AGluZm9Ac3RhcnRheC5pbgAxMjNNb251Iw==
<< 235 2.7.0 Authentication successful
>> MAIL FROM:<info@startax.in> SIZE=556
>> RCPT TO:<anmolsuvidha@gmail.com>
<< 250 2.1.0 Ok
<< 250 2.1.5 Ok
>> DATA
<< 354 End data with <CR><LF>.<CR><LF>
>> From: info@startax.in
>> Date: Sun, 12 May 2024 09:06:58 퍍
>> Subject: SMTP test from mail.startax.in
>> Message-Id: <OMUG9EJ91NU4.F80WNTONHWBG1@WIN-AUIR3RRGP88>
>> To: anmolsuvidha@gmail.com
>> MIME-Version: 1.0
>> Content-Type: multipart/alternative; boundary="=-qnQeqSYuyBInvuSW3glxcg=="
>>
>> --=-qnQeqSYuyBInvuSW3glxcg==
>> Content-Type: text/plain; charset=utf-8
>>
>> Test message
>> --=-qnQeqSYuyBInvuSW3glxcg==
>> Content-Type: text/html; charset=utf-8
>> Content-Id: <OMUG9EJ91NU4.ZXT40X2PAXQX2@WIN-AUIR3RRGP88>
>>
>> <b>Test message</b>
>> --=-qnQeqSYuyBInvuSW3glxcg==--
>> .
<< 250 2.0.0 Ok: queued as 95BB481E18

spam tester screenshot:
![image](https://github.com/knadh/listmonk/assets/134092976/1cf4eb58-80fc-42b0-93d7-a5e1b778c636)

**Comment by orbit-robertl** [comment]
Does your aapanel server ipv6 and is the mail server (postfix) configured for ipv6?
