### ISSUE TITLE
Wrong view count in the "Analytics" section

### ISSUE THREAD

**Issue by JustAnotherEmployee** [knadh/listmonk#1868]
**Version:**
 - listmonk: [eg: v3.0.0]
 - OS: [Windows 10, 22H2]
- Google Chrome / Mozilla Firefox

**Description of the bug and steps to reproduce:**
I was wondering why/how the "views" count in the analytics tool was going downwards. 
I realized Listmonk per default sets the period to be the last 7 days. 
Nothing simply happens when I try to update to the wanted period. 
The blue search button is non responsive.
See picture below for clarification:

**Screenshots:**
![Listmonk_Analytics_Bug](https://github.com/knadh/listmonk/assets/170608487/59f8e3a6-74c1-4dd9-ba08-5155648da7e5)

**Comment by knadh** [comment]
Hi. This is being tracked here https://github.com/knadh/listmonk/issues/1821
