### ISSUE TITLE
AWS SNS Bounce and complaints not processed

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1869]
**Version:**
 - listmonk: Repocloud
 - OS: [e.g. Fedora]

**Description of the bug and steps to reproduce:**

I tried to set up Bounce Processing following the documentation:
https://listmonk.app/docs/bounces/

The AWS SNS subscription is confirmed, but bounces and complaints are not counted by Listmonk

**Screenshots:**
![Screenshot_2024-05-23-23-54-31-493_com android chrome-edit](https://github.com/knadh/listmonk/assets/8183572/90bf76bf-7e2d-4081-8171-509d38bd7a85)

**Comment by MaximilianKohler** [comment]
Anything in your logs? It's working for me with these instructions: https://listmonk.app/docs/bounces/#amazon-simple-email-service-ses

**Comment by benstaf** [comment]
yes, when I configured SNS I got this log:

2024/05/22 15:39:10 error processing SES notification: notification type is not bounce
2024/05/22 15:39:10 error processing SES notification: notification type is not bounce

**Comment by MaximilianKohler** [comment]
Repocloud may have an old version of listmonk?

**Comment by benstaf** [comment]
It's v3.0.0

![Uploading Screenshot_2024-05-25-17-20-10-066_com.android.chrome.jpg…]()

**Comment by MaximilianKohler** [comment]
Well, I don't know if it matters for this issue, but that "public URL" is not supposed to be localhost:9000. It should be the first part of the one you put in your Endpoint.

**Comment by benstaf** [comment]
I did it and nothing changed. It's actually the same issue as #1807

**Comment by benstaf** [comment]
Problem solved here:

https://github.com/knadh/listmonk/issues/1668#issuecomment-1994726088
