### ISSUE TITLE
Amazon SES integration

### ISSUE THREAD

**Issue by MrGKanev** [knadh/listmonk#187]
Hi guys,
Firstly I wanted to congratulate you guys on this cool piece of software. My question Is connected with Amazon SES. If it is possible to integrate yourself with it and if not, is it in your future plans to implement it.

**Comment by knadh** [comment]
Thanks @MrGKanev. You can use listmonk with SES SMTP servers.

**Comment by manjeshpv** [comment]
@MrGKanev aws ses having smtp
