### ISSUE TITLE
Possibility to have a dual-lingual-instance

### ISSUE THREAD

**Issue by spammads** [knadh/listmonk#1871]
Hi! Thanks for this amazing project. Works like a charm.
My basic situation is, that I got a multilingual-hugo-site. 
So I am able to tell if the users subscribes via a polish page or via english one.
If its a polish user I would like to trigger a polish onboarding-process - meaning all subsequent listmonk-forms and confirmation sites should be displayed in polish.
If the users does the same but is visiting my english site i want to trigger the onboarding-process in english.
The only possibility I have found is to host 2 instances of listmonk and configure the language in the global settings page.
I’m courious if any of the listmonk-maintainers has another – more lean – solution.
As hosting two instances would mean to keep templates and stuff in sync.

Thanks again for your work on this project.
BR.

**Comment by knadh** [comment]
Hi @spammads. Please refer to this thread: https://github.com/knadh/listmonk/issues/838

It's possible to achieve this using templating hacks, but first-class support for this will take time. Thank you.

**Comment by spammads** [comment]
Thanks for the redirect. I searched issues but this one didnt show up. Will subscribe. Many Thanks again.
