### ISSUE TITLE
Sliding window resets upon app restart

### ISSUE THREAD

**Issue by AshPowell** [knadh/listmonk#1873]
The sliding window limitations reset upon app restart when changing a setting. It would be great if this could be stored and adhered to upon app restart

**Comment by knadh** [comment]
If your settings aren't being saved upon restart, it's most likely an incorrect installation that's resetting the database. Please see this: https://github.com/knadh/listmonk/issues/1089

**Comment by AshPowell** [comment]
They are... that's not what I've said mate
