### ISSUE TITLE
Multiple Logo Support

### ISSUE THREAD

**Issue by saint11** [knadh/listmonk#1875]
I use the same Listmonk docker for multiple mailing lists, I wonder if there is a way to have different logos for different lists. My main use case is for the Opt-In email and subscription confirmation page.

**Comment by mcgrue** [comment]
I'd like this too. Right now I'm running three dockers to do this - and probably expanding to more

**Comment by knadh** [comment]
- You can customize the system template and add logic to swap the logo: https://listmonk.app/docs/templating/#system-templates
- Easier option would be to use a bit of Javascript to read the mailing list UUID on the opt-in form and change the logo URL accordingly. This JS can be inserted in Settings -> Admin -> Appearance -> Public.

**Comment by mcgrue** [comment]
javascript solutions unfortunately don't work if you want to harden against info leak.  In the modern web it's advantageous to not share what software you're using or what other properties are hosted locally as secops tactics to remove attack vectors

There are always other angles that are unavoidable (looking up IPs etc) but the fewer avenues for discovery that you expose the safer you are

**Comment by knadh** [comment]
Sorry, confused by this. There's no security implication here.

The JS would look something like this. Pseudocode:

```javascript
// Define the map of listIDs => logos.
const logos = {
	"6fd717cb-e540-41a7-bd74-6bc6e4e675c8": "/path/to/logo1.png",
	"47236f6e-7dd0-48bb-bf9a-7738cd143b98": "/path/to/logo2.png",
	"fe7d9531-aca7-47b8-8cf8-b63cb9e12552": "/path/to/logo3.png"
};

// Get the ID of the list on the opt-in page.
const optInListID = document.querySelector(....).value;

// Replace the logo.
document.querySelector("logo").src = logos[optInListID];

```

**Comment by DiaryRegistr** [comment]
I imagine it might work in a very similar way, but I don't have enough knowledge to figure that out on my own:
Is it also possible to change the corresponding favicon?
What would be the JS for that?
Thanks for your help.
