### ISSUE TITLE
Immediately opt-in when user clicks on link in confirmation email

### ISSUE THREAD

**Issue by spammads** [knadh/listmonk#1876]
Sorry if I have overlooked a setting to configure this.
I really looked into the documentation an the app-setting but found nothing.

Currently if the list is a double-opt-in list the user gets an confirmation email after the initial registration.
In this confirmation email is a subscribe button.
This button takes the user to a confirmation-website where he again has to confirm via a form-submit.
I would expect that the click in the email gets the user signed-up immediately (like on _Mailapes_ and friends).
It would be nice if the email-link would bring up the final confirmation-site instead of another additional confirmation-step.

Sorry for writing up so many issues in such a short time. But I'm in kind of a hurry and need to move forward.
Thanks again for this great tool.
BR.

**Comment by knadh** [comment]
Something like the following snippet should work. Please try pasting this in the `Javascript` field in Admin -> Settings -> Appearance -> Public

```
if(document.querySelector(".optin-form")) {
	document.querySelector(".optin-form").submit();
}
```

**Comment by spammads** [comment]
This works but feels kind of hacky as the user can see the skipped opt-in page. Would be great if this could be a customizable option in future releases.
