### ISSUE TITLE
Cant clone campaign where lists no longer exist

### ISSUE THREAD

**Issue by AshPowell** [knadh/listmonk#1879]
Not sure if bug or feature enhancement - but if a list no longer exists, it stops you being able to clone a campaign they're linked to.

**Comment by Bowrna** [comment]
could i try my hands on this issue as part of FOSS Hack?

**Comment by knadh** [comment]
@Bowrna yes, sure.

**Comment by Bowrna** [comment]
This shows an error message saying "There are no subscribers in the selected list to create the campaign" when we try to clone the campaign associated with deleted lists.
But at the backend, a campaign is getting created and on refresh at front end, you can see a copy of the campaign without any associated list. 
Attaching screenshots for reference
Taking a clone of the campaign with deleted list, show following message
<img width="1150" alt="Screenshot 2024-07-29 at 2 30 36 PM" src="https://github.com/user-attachments/assets/e796f60d-fb34-42ac-8b8d-7870fbf57034">
On page reload, it shows the following clone 
<img width="1150" alt="Screenshot 2024-07-29 at 2 26 03 PM" src="https://github.com/user-attachments/assets/44caf38b-da39-488d-9915-56721d0c5fd1">
