### ISSUE TITLE
media links broken

### ISSUE THREAD

**Issue by coconutpool** [knadh/listmonk#188]
dashboard -> campaigns -> media 

drag image to box, click upload link. image uploads fine, gets stored in the filesystem in the uploads directory in the listmonk home. however, in the media browser in listmonk, the images thumbnails and links are broken: 

```
{
"message": "Not Found"
}
```

not sure if im doing something wrong or if this is a bug.

**Comment by knadh** [comment]
Assuming you're using the filesystem provider, have you configured `/uploads` correctly? There are no known issues with the media upload currently otherwise.

**Comment by coconutpool** [comment]
> Assuming you're using the filesystem provider, have you configured the `Upload URI` in the settings correctly? There are no known issues with the media upload currently otherwise.

no, i don't know about that. its not in the config. how do i set that?

**Comment by knadh** [comment]
What version are you using? `v0.7.0` has a "Settings" UI where you can configure this.

**Comment by coconutpool** [comment]
hi.

provider: filesystem
uploads path: uploads
uploads uri: /uploads

the path to the files works: https://test.doobiemailer.com/uploads/SPOCRA-WANTS-YOU.png so its being uploaded.

but from inside listmonk when i click on the link from the media tab: https://test.doobiemailer.com/campaigns/test.doobiemailer.com/uploads/SPOCRA-WANTS-YOU.png its an error.

**Comment by onlywicked** [comment]
@coconutpool Can you provide the screenshot or values for the General Tab in Settings?

**Comment by knadh** [comment]
Closing the issue since there's no update to debug further.
