### ISSUE TITLE
502 Bad Gateway for /api/health and /api/events?type=error on admin/settings

### ISSUE THREAD

**Issue by GeistFighter** [knadh/listmonk#1881]
**Version:**
 - listmonk: 3.0.0
 - OS: Debian 12
 - Nginx: 1.22.1
 - Psql: (PostgreSQL) 15.6 (Debian 15.6-0+deb12u1)
 - Install type: Binary 

**Description of the bug and steps to reproduce:**
Hi all,

I recently installed Listmonk on my server, in Binary mode, with the aim of putting the Listmonk server on a local server only and accessible via a Nginx reverse proxy.

But apparently I'm getting 502 Bad Gateway errors when I make changes in admin/settings, in the console I'm also getting errors, but in the GUI there aren't any, I'd like to know where this is coming from, have I made a mistake or not?

To explain my configurations better, I've put everything on a local infrastructure so that I can share them with you.

**Screenshots:**
![image](https://github.com/knadh/listmonk/assets/42804270/e413e9b5-0f70-4807-a0c8-a194722e7922)
![image](https://github.com/knadh/listmonk/assets/42804270/fa5080c0-7643-4220-9b39-3568f6a5d25a)

I'll also put the request logs in which you'll find the answers in 502.
[newsletter.testing.local_Archive [24-06-01 16-31-49].log](https://github.com/user-attachments/files/15522193/newsletter.testing.local_Archive.24-06-01.16-31-49.log)

Nginx error logs :
2024/06/01 16:26:22 [error] 86006#86006: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.8.1, server: newsletter.testing.local, request: "GET /api/health HTTP/2.0", upstream: "http://127.0.0.1:16670/api/health", host: "newsletter.testing.local", referrer: "https://newsletter.testing.local/admin/settings"
2024/06/01 16:26:23 [error] 86006#86006: *2 upstream prematurely closed connection while reading response header from upstream, client: 192.168.8.1, server: newsletter.testing.local, request: "GET /api/events?type=error HTTP/2.0", upstream: "http://127.0.0.1:16670/api/events?type=error", host: "newsletter.testing.local", referrer: "https://newsletter.testing.local/admin/settings"
2024/06/01 16:26:27 [error] 86006#86006: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.8.1, server: newsletter.testing.local, request: "GET /api/health HTTP/2.0", upstream: "http://127.0.0.1:16670/api/health", host: "newsletter.testing.local", referrer: "https://newsletter.testing.local/admin/settings"
2024/06/01 16:26:32 [error] 86006#86006: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.8.1, server: newsletter.testing.local, request: "GET /api/health HTTP/2.0", upstream: "http://127.0.0.1:16670/api/health", host: "newsletter.testing.local", referrer: "https://newsletter.testing.local/admin/settings"

No error on the service :
![image](https://github.com/knadh/listmonk/assets/42804270/a9d47693-32e9-48fb-bd9d-0f7de80d0bd1)

**My configuration**

My config.toml :
![image](https://github.com/knadh/listmonk/assets/42804270/af0bf1f0-134f-4904-ad37-7f027759e4e0)

The service :
![image](https://github.com/knadh/listmonk/assets/42804270/c331355b-3edc-4b58-81ab-a39b26588311)

My Nginx configuration :
![image](https://github.com/knadh/listmonk/assets/42804270/497b7f1e-6a94-48d3-9dd6-64b9939fbecc)

Thank you in advance for your answers!

**Comment by MaximilianKohler** [comment]
That's the error I got when I had a firewall issue.

**Comment by GeistFighter** [comment]
Hello [MaximilianKohler](https://github.com/MaximilianKohler), thank you for your reply !

I've disabled my firewall :
![image](https://github.com/knadh/listmonk/assets/42804270/9982f89f-9f16-4afd-91b7-681f4cfa722b)

but the problem is still there :
![image](https://github.com/knadh/listmonk/assets/42804270/7eb41d92-4b4a-473d-b163-5f37a261a785)

**Comment by GeistFighter** [comment]
What's strange is that even if there are errors in the console, the site looks functional.

I think the problem is with the reverse proxy, because if you go directly via the IP address and port in the configuration it works without any errors in the console. 

Do you have any ideas as to why the reverse proxy can causing these errors (I've tested the reverse proxy in 80 http and 443 https, and it makes no difference) ?

**Comment by GeistFighter** [comment]
Hi, do you think this could be due to my Nginx reverse proxy configuration not respecting certain routes?

https://listmonk.app/docs/configuration/#http-routes

**Comment by GeistFighter** [comment]
Where do you think the misconfiguration could have come from?
