### ISSUE TITLE
Individual tracking of openings and clicks

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1882]
I'm always frustrated when I can't know if a given subscriber opened or clicked on my email 
![Screenshot_2024-06-01-21-31-48-995_com android chrome-edit](https://github.com/knadh/listmonk/assets/8183572/a1b8b65d-002f-4c58-92ec-613f716650a9)

**Describe the solution you'd like**
I would like analytics with individual tracking of openings and clicks, like in Sendportal and Mailbluster 
![Screenshot_2024-06-02-10-56-51-869_com android chrome-edit](https://github.com/knadh/listmonk/assets/8183572/ceedde67-b9ef-482b-aa3a-9b8ae0cbb868)

Overall, the Listmonk Analytics and User Interface isn't as good as [Sendportal](https://github.com/mettle/sendportal) which is open-source, or [Mailbluster](https://mailbluster.com), I would appreciate to find those UX/UI features in Listmonk

**Comment by MaximilianKohler** [comment]
Currently, you have to do an SQL query to find the list of people who opened the email: https://listmonk.app/docs/querying-and-segmentation/#querying-subscribers-who-viewed-the-campaign-email
