### ISSUE TITLE
Skip importing a subscriber that already exists in the database 

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1883]
**Is your feature request related to a problem? Please describe.**
I don't want that to import a subscriber if it already belongs to the subscriber database.

**Describe the solution you'd like**
In the import process, I want to have the option to skip a subscriber that already exists, like here:
![Screenshot_2024-06-02-13-11-08-619_com android chrome-edit](https://github.com/knadh/listmonk/assets/8183572/b2a4e298-ce9d-4bcc-a7e7-8819515a154e)

This option currently doesn't exist:
![Screenshot_2024-06-02-13-12-21-372_com android chrome-edit](https://github.com/knadh/listmonk/assets/8183572/e847676d-e5a1-4fb1-9c72-829975aa3555)

**Comment by MaximilianKohler** [comment]
I think that's essentially what turning off "overwrite" does.

Relatedly, if you import a list of 10 people with 1 duplicate, it will say "finished 10/10" and no errors. I think it should notify us that there was a duplicate that was skipped or the first instance was overwritten by the second one.

**Comment by benstaf** [comment]
It's different. Turning off "overwrite" still adds the email to the lists.

I would like the option of not subscribing an email to the lists if it's already in the database

**Comment by nrathi** [comment]
Also, why is overwrite turned on by default 😭
