### ISSUE TITLE
Can listmonk support Template expressions in custom headers?

### ISSUE THREAD

**Issue by yagamikira88** [knadh/listmonk#1884]
Can listmonk support Template expressions in custom headers?

For example:

List-Unsubscribe: https://solarmora.com/unsubscribe/example?{{ .Subscriber.Email }}

**Comment by knadh** [comment]
Ah, not currently. This can be considered for a future version.

**Comment by ilkkao** [comment]
This is the most important missing feature in my use case as well. We do one way sync from the app user database to listmonk. It's much simpler than two way syncing. This means we have a custom unsubscribe page as part of the app. 

Big email providers are making List-Unsubscribe header mandatory and not being able to set it like @yagamikira88's example means we probably need to maintain a custom listmonk image. I can't think of any other workaround. It would be great to keep this issue open @knadh

**Comment by jordanamr** [comment]
> This is the most important missing feature in my use case as well. We do one way sync from the app user database to listmonk. It's much simpler than two way syncing. This means we have a custom unsubscribe page as part of the app.
> 
> Big email providers are making List-Unsubscribe header mandatory and not being able to set it like [@yagamikira88](https://github.com/yagamikira88)'s example means we probably need to maintain a custom listmonk image. I can't think of any other workaround. It would be great to keep this issue open [@knadh](https://github.com/knadh)

I'm having the exact same issue sadly, what was your solution?

**Comment by ilkkao** [comment]
I've a tiny patch that hardcodes the unsubscribe urls to point to our custom unsubscribe page (in `internal/manager/manager.go`). Including it when building docker images used in our production.

**Comment by jordanamr** [comment]
> I've a tiny patch that hardcodes the unsubscribe urls to point to our custom unsubscribe page (in `internal/manager/manager.go`). Including it when building docker images used in our production.

Thanks. I've tried adding the feature in https://github.com/knadh/listmonk/pull/2794, let's see what the author thinks about it
