### ISSUE TITLE
FEATURE: Stronger data validation + defaults on `PUT /api/settings`

### ISSUE THREAD

**Issue by Amphaal** [knadh/listmonk#1885]
Actually, there is only PUT verb enabled on this path, which will result in replacing the whole setting file: some settings in body are explicit requirements (as the API tells us if we do not set them), but some more that are not required by the API are actually required for the UI to keep functionning !
For example, if you call `PUT /api/settings` and missing some parameters configuring an SMTP server, the Settings's SMTP tab goes completely blank, same for bounces.

Can we have defaults values where required if expected properties are missing in the body ? If not, telling us with `HTTP 500` that some properties are missing and need to be set, with somehow documented possibles values in Swagger ?

**Comment by nayanthulkar28** [comment]
Hello,
Would like to work on this. 
Can you provide an request response example to understand it better?

**Comment by nayanthulkar28** [comment]
Does this happens with only SMPT and bounce use case? Or it can happen with any field

**Comment by Amphaal** [comment]
Any field, really. Like with my example above, if i run this script minus the `smtp.*` declaration, SMTP UI goes fully blank.

**Comment by nayanthulkar28** [comment]
Got it.

**Comment by nayanthulkar28** [comment]
I assume that while updating the setting, frontend is providing all the attributes(regardless its new updated values only). So this type of bug won't happen through UI. The problem arises when we try to update this manually and misses out some field which are required by UI. For ex. in bounce case if we miss out bounce.action the UI crashes. 
An easy fix would be making all attribute as required/mandatory and return error if not provided.

**Comment by Amphaal** [comment]
Seems legit for a PUT verb. What would be nice for most usescases regarding updating settings, is to enable POST verb, and allow atomic properties replacement through it. With this, we could just let actual settings as it and only update those that we wish to change.

**Comment by nayanthulkar28** [comment]
Yes, we could actually make this change to PUT method only, as this API will use to updating setting. Thought of this as my second approach but will require lots of code change. I'm fine with both the approaches.

**Comment by nayanthulkar28** [comment]
@Amphaal can you confirm this ? Will start with development

**Comment by Amphaal** [comment]
Just do what makes the more sense to you, as long at it makes the usage safer and documented :)
