### ISSUE TITLE
FEATURE: Swagger along Listmonk w/ better configuration and up-to-date definitions

### ISSUE THREAD

**Issue by Amphaal** [knadh/listmonk#1886]
- Swagger should be available along the app, reflecting the actual installed listmonk's API, with something like `http://<my-installed-listmonk>/docs/swagger`

- Swagger should tell us which version of the API it reflects (as of now listmonk latest version is 3.0.0, and official Swagger doc https://listmonk.app/docs/swagger/ tells us it is 1.0.0)
<img width="517" alt="Capture d’écran 2024-06-05 à 13 38 27" src="https://github.com/knadh/listmonk/assets/13903151/a3a5d66f-f062-401b-9902-c4d0d41c1841">

- Swagger has outdated definitions (namely for /api/settings, might also be the case with other paths)

**Comment by knadh** [comment]
Hi @Amphaal. I'm totally unfamiliar with Swagger, unfortunately. The collection was a community contribution. Please feel free to send a PR with fixes and improvements.
