### ISSUE TITLE
Base 64 image not coding correctly

### ISSUE THREAD

**Issue by PaulMcF1987** [knadh/listmonk#1888]
Version 3.0.0

I have used the same email template as I use in my email client - thunderbird

I have added my logo as a base-64 code which I have never had any problems with

However, when using listmonk, some of my recipients recieve an email which shows my logo and others receive the base-64 code and have actually called me to see if I had sent them a virus

Is there a recommended way to add a logo/image to an email template?

**Comment by knadh** [comment]
Hi @PaulMcF1987. Without seeing what the e-mail clients are rendering, it wouldn't be possible to guess what's going on. The recommended way is using the "Media" tab to upload images and reference them via https in the e-mail (load remotely without embedding base64).

**Comment by PaulMcF1987** [comment]
@knadh 
Where the image is supposed to be, they are receiving a long Base64 string... essentially my logo should be at the top but instead of my logo they get a massive string
```
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAckAAAFoCAYAAAA8fwA6A.........bWLiNfbK0YAAAAASUVORK5CYII=" style="-ms-interpolation-mode:bicubic;line-height:100%;outline:none;text-decoration:none; border: none; display:block max-height:120px!important; height:100%; max-width:150px!important; width:100%; vertical-align: top;" width="150" height="120" border="0" alt="Logo">

Hello x,
.......
```

I have tried using the media section and have looked at various posts to try and set this up but I cannot seem to get it working.
I am using a docker hosted instance of Listmonk and have looked at the relevant help sections that I can find but no joy
