### ISSUE TITLE
Error creating Campaign: pq: duplicate key value violates unique constraint "campaigns_archive_slug_key". Key (archive_slug)=(test-campaign-l-1-2) already exists.

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1889]
**Version:**
 - listmonk: [eg: v1.0.0]
 - OS: [e.g. Fedora]

**Description of the bug and steps to reproduce:**

**Screenshots:**

**Comment by MaximilianKohler** [comment]
Use search first. Duplicate of https://github.com/knadh/listmonk/issues/1725.
