### ISSUE TITLE
selcting different smtp when scheduling the campaigns

### ISSUE THREAD

**Issue by subhash-ngowda** [knadh/listmonk#1890]
Hi, Is there a way to select differnt smtp accounts when I am scheduling the campaigns? I mean lets say on Friday i want to schedule a campaign  to start on 10am Saturday using smtp #1. Then I want to schedule another campaign to start at 12noon on Saturday using smtp #2.  I am not able to find out how to do this.

**Comment by knadh** [comment]
Hi @subhash-ngowda. Selecting an SMTP per campaign isn't possible currently.
