### ISSUE TITLE
Cant connect to Gmail account to process bounces

### ISSUE THREAD

**Issue by agroideas** [knadh/listmonk#1893]
I have set up a gmail account for bounce processing, the emails are coming in but I can't process them from Listmonk. We have google accounts with our own domain.

Two errors in logs, depending on config:

If I disable TLS:
2024/06/11 15:24:50 error scanning bounce mailbox: EOF (the mailbox have more than 20 unread bounces)

<img width="1058" alt="Screenshot 2024-06-11 at 12 26 28" src="https://github.com/knadh/listmonk/assets/26013564/e781fa6e-4efa-4da3-aa82-4ac25f2e4913">

If I enable TLS: (with or without skip TLS verification)
2024/06/11 15:28:35 error scanning bounce mailbox: [AUTH] Username and password not accepted.

<img width="1058" alt="Screenshot 2024-06-11 at 12 30 04" src="https://github.com/knadh/listmonk/assets/26013564/3cec6ceb-27ae-4a7c-aa43-09ddd78b7dc2">

Of course user/pass are checked.
Any help is appreciated.

**Comment by zevszym** [comment]
Hello, 
If you change TLS button to off you need to change port to 110
Are you using googel app password as credencial ? 
https://support.google.com/accounts/answer/185833?hl=en

**Comment by agroideas** [comment]
Hello, thank you very much for your quick reply.
I'm using a normal account, not google app password.
I was able to solve it enabling less secure app for the account, but this will going to stop working soon.

Google app password is the correct way to connect the account?
