### ISSUE TITLE
CORS Error when wanting to add subscriber from my own website

### ISSUE THREAD

**Issue by YannikBleilinger** [knadh/listmonk#1896]

**Comment by thebrownbreadtoast** [comment]
@YannikBleilinger I am trying to do same, can you guide me how did you achieve this?

**Comment by thebrownbreadtoast** [comment]
for others' reference: https://github.com/knadh/listmonk/issues/1523

**Comment by knadh** [comment]
CORS 'allowed origins' can now be configured in Settings -> Security in [v6.0.0](https://github.com/knadh/listmonk/releases/tag/v6.0.0).
