### ISSUE TITLE
Campaigns - RSS / Digest feature?

### ISSUE THREAD

**Issue by tiredofit** [knadh/listmonk#19]
Just stumbled on this today, very nice work.

As a feature request, I was wondering the ability to implement functionality to send out a campaign containing contents of an RSS Feed.

Here are two use cases:
1) At a specific period, Listmonk checks for the existence of a new article in the RSS / XML feed and sends a messaeg to subscribers with a custom template and the capability of either displaying the Title of the Article (with link to Original Source), or the actual content.

2) Similar to 1 - However on a scheduled campaign, check the RSS/XML contents and send a digest of information (Ie, Send articles to subscribers of anything that has appeared within the past 3 days - either an excerpt, title, or full content). If no new articles, skip sending the campaign.

Mailchimp handles 2 quite well, and I've yet to see an open source mailing list manager that gets it right. Mailtrain handles Scenario #1, PHP List attempts to handle #1 and #2. So I thought I would see if this would make sense inside of your application.

**Comment by knadh** [comment]
Thanks @tiredofit. I'm of the opinion that this would be outside of the scope of listmonk, a pure mailing list manager.

However, listmonk exposes easy to use HTTP APIs that can be used to build enhancements like this. Parsing an RSS feed, constructing an HTML body, and pushing it to listmonk to start a campaign should be trivial to implement externally as a Bash or Python script.

**Comment by HLFH** [comment]
But MailChimp supports it: https://mailchimp.com/features/rss-to-email/
Mailtrain supports it: https://github.com/Mailtrain-org/mailtrain ; https://mailtrain.org/
Mautic supports it: https://github.com/ChrisRAoW/mautic-rss-to-email-bundle

**Comment by knadh** [comment]
@HLFH quoting from my previous reply.
> However, listmonk exposes easy to use HTTP APIs that can be used to build enhancements like this. Parsing an RSS feed, constructing an HTML body, and pushing it to listmonk to start a campaign should be trivial to implement externally as a Bash or Python script.

**Comment by HLFH** [comment]
Well. I really like the design of Listmonk. I have just migrated to Mautic for the features.

**Comment by candidexmedia** [comment]
Hi everyone! I wanted to revive this issue to ask if anyone figured out how to do this:

> However, listmonk exposes easy to use HTTP APIs that can be used to build enhancements like this. Parsing an RSS feed, constructing an HTML body, and pushing it to listmonk to start a campaign should be trivial to implement externally as a Bash or Python script.

I have very little experience with using APIs, Bash, and Python, but could follow a guide if one exists.

I'm namely interested in something similar to [sendinblue's rss-to-email](https://www.sendinblue.com/blog/rss-to-email-campaigns/) which uses dynamic content from the feed to populate the email body:

![image](https://user-images.githubusercontent.com/55474996/235472880-bb14f541-bed6-48fe-abe2-0050375c4014.png)

[Mailerlite](https://www.mailerlite.com/features/rss-to-email) also has a really nice implementation of this feature:

![image](https://user-images.githubusercontent.com/95003834/235475473-33f126c3-6f15-470b-88c5-478ba3b067dc.png)

**Comment by kirkpsmith** [comment]
> I've implemented a simple script as described by @knadh: https://github.com/ElliotKillick/elliotonsecurity.com/blob/main/serve/ping.elliotkillick.com/rss2newsletter/rss2newsletter.py
> 
> Feel free to use it for your own site if you wish.

Thanks for this @ElliotKillick , I was able to make this work for my needs, and thanks @knadh for listmonk! Mailchimp doesn't seem to be able to easily do RSS-to-email anymore, and this serves my need as wanting a simple newsletter for my personal blog.

**Comment by candidexmedia** [comment]
Thank you @ElliotKillick ! Do you have instructions anywhere on how to get started with this?

**Comment by ElliotKillick** [comment]
You're welcome @candidexmedia and @kirkpsmith! Development of rss2newsletter has continued and it's now in its own repo with instructions: https://github.com/ElliotKillick/rss2newsletter

**Comment by ElliotKillick** [comment]
Note that all copies of rss2newsletter are now AGPL. It's best for everyone due to the large amount of proprietary email marketing solutions.

**Comment by candidexmedia** [comment]
@ElliotKillick Beautiful! I use Railway for my Listmonk instance, and I'm not the most tech-savvy person... Do you think rss2newsletter could work with Railway? Or could I use it from my Windows desktop's Python, and still have it talk to my Listmonk instance?

Sorry if these are silly questions... Let me know if I should direct them to your repo. 😊

**Comment by ElliotKillick** [comment]
@candidexmedia Railway allows you to deploy from a GitHub repo so you should be able to host from there. Your Windows desktop would also work well though. Or, you can buy a VPS if you would rather have a more customizable server host the app for you (see README for a link to a good VPS).

**Comment by Robert-van-Barlingen** [comment]
@ElliotKillick Thank you for your tool. I forked it and added some additional features. I created a merge request. Would you mind looking at it?

**Comment by candidexmedia** [comment]
Coming back to this to share a new RSS-to-Listmonk tool which works with GitHub Actions: https://github.com/ping13/listmonk-rss
