### ISSUE TITLE
Spintax support 

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1901]
I would like a spintax feature to improve email deliverability at high volumes

Many other softwares have spintax support, such as:

https://www.mailstand.com/blog/spintax-cold-email-outreach

https://www.gmass.co/blog/spintax/

https://www.saleshandy.com/blog/introducing-spintax/

https://postaga.com/spintax-guide/

**Comment by knadh** [comment]
This looks like a writing technique for tweaking language in an e-mail specifically for sending "cold" e-mails. Either way, listmonk is a generic mailing list manager agnostic of any specific writing techniques. Hence, this is out of the scope of the project.

**Comment by benstaf** [comment]
You can watch how {spin} feature is baked in the software:
https://youtu.be/LjzjzK7tj3c?si=jd9a_x6zLuffWp9x

I can help implementing this feature in Listmonk, it's pretty straightforward using existing modules such as https://github.com/AceLewis/spintax

**Comment by knadh** [comment]
> Listmonk is only able to send identical emails for each campaign

This is incorrect. E-mail content in listmonk is fully programmable with the Go templating language. Please see https://listmonk.app/docs/templating/
