### ISSUE TITLE
How to import a Go Template library ?

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1902]
Listmonk supports [Go template](https://pkg.go.dev/text/template) expressions and integrates [Sprig template functions](https://masterminds.github.io/sprig/) from Sprig library

I would like to import another Go Template library from the [Awesome Go list](https://awesome-go.com/template-engines/). Is it possible? How to do it on an example?

The [documentation](https://listmonk.app/docs/templating) does not address this question

**Comment by knadh** [comment]
No, this is not possible.
