### ISSUE TITLE
Plain smtp mail send fails with tls error

### ISSUE THREAD

**Issue by titansmc** [knadh/listmonk#1905]
**Version:**
 - listmonk: [v3.0.0]
 - OS: [Rocky 8 kubernetes]

**Description of the bug and steps to reproduce:**
If I configure my email server on port 25 without any authentication neither TLS, sending a test email works fine, but when I submit a campaign it fails with:
```
2024/06/20 11:21:34 manager.go:513: error sending message 'Finished: campaingn': tls: server selected unsupported protocol version 301
```

**Comment by titansmc** [comment]
interesting...if I enable TLS, and then toggle on "Skip TLS verification" and disable TLS again, I have no issues. I would say this is a bug, so if TLS is disabled, it shouldn't try to perform any TLS verification.

**Comment by knadh** [comment]
If TLS is disabled, listmonk doesn't attempt to establish a TLS connection at all. The "skip host verification" setting is only applied when TLS is either STARTTLS or TLS.
