### ISSUE TITLE
Add subscribers to list based on attributes, via the API

### ISSUE THREAD

**Issue by Tchekda** [knadh/listmonk#1906]
**Is your feature request related to a problem? Please describe.**
We plan to use Listmonk only via the API since we need some custom access rules in our organization.

Our most frequent use case is to send emails to users from a given country, keeping in mind that this is dynamic and changes over time.
From what we understood on the documentation, we first need to query all users from that given country via `GET /api/subscribers` and then send that list of IDs to `PUT /api/subscribers/lists`. But this payload is expected to be huge (around 200000 users).

**Describe the solution you'd like**
We were wondering if there was a way to directly add the users from the SQL query to a list ?

**Comment by benstaf** [comment]
I would like to do the same via the Web interface.

I didn't find how to segment subscribers in a new list without downloading and then uploading them again

**Comment by knadh** [comment]
@Tchekda yes, this is possible. This queries subscribers with the given expression and adds them to the target list ID. You can also do `remove`.

```shell
curl -u "user:pass" 'http://localhost:9000/api/subscribers/query/lists' -X PUT \
   --data-raw '{"action":"add","query":"sql_exp_here","target_list_ids":[1]}'
```

@benstaf once you search for subscribers, click on the checkbox on the table header to select subscribers from the table and list management options will appear.

**Comment by Tchekda** [comment]
> @Tchekda yes, this is possible. This queries subscribers with the given expression and adds them to the target list ID. You can also do `remove`.

Thank you very much for this information, would it be possible to add it to the documentation because I believe it's a pretty nice thing to have ! 

Awesome tool by the way !
