### ISSUE TITLE
Can you change the subject line of system emails?

### ISSUE THREAD

**Issue by jettlorenzo** [knadh/listmonk#1908]
I have customised the system emails through the local static directory.

I am simply wondering if changing a system email subject is possible.

Eg. Confirm subscription > Confirm your email

**Comment by knadh** [comment]
Yes, this is possible. Please see https://github.com/knadh/listmonk/issues/1727#issuecomment-2017667781

**Comment by jettlorenzo** [comment]
I did indeed try using <title data-i18n>Hey {{ .Subscriber.FirstName }}!</title> for example, restarting Listmonk, even changing other elements of the templates to ensure the changes were taking effect.
And everything besides the Subject line changes, am I missing other configuration changes that need to occur to make it work.

Full email example:
```
{{ define "subscriber-optin" }}
{{ template "header" . }}
<title data-i18n>Hey {{ .Subscriber.FirstName }}!</title>

<h2>{{ L.Ts "email.optin.confirmSubTitle" }}</h2>
<p>{{ L.Ts "email.optin.confirmSubWelcome" }} {{ .Subscriber.FirstName }}</p>
<p>{{ L.Ts "email.optin.confirmSubInfo" }}</p>
<ul>
    {{ range $i, $l := .Lists }}
        {{ if eq .Type "public" }}
            <li>{{ .Name }}</li>
        {{ else }}
            <li>{{ L.Ts "email.optin.privateList" }}</li>
        {{ end }}
    {{ end }}
</ul>
<p>{{ L.Ts "email.optin.confirmSubHelp" }}</p>
<p>
    <a href="{{ .OptinURL }}" class="button">{{ L.Ts "email.optin.confirmSub" }}</a>
</p>
<a href="{{ .UnsubURL }}?manage=true">{{ L.T "email.unsub" }} weird</a>

{{ template "footer" }}
{{ end }}
```

**Comment by jettlorenzo** [comment]
@knadh I did indeed try using <title data-i18n>Hey {{ .Subscriber.FirstName }}!</title> for example.
But even after restarting my Listmonk docker container, and even changing other elements of the templates to ensure the changes were taking effect, everything besides the Subject line changes, am I missing other configuration changes that need to occur to make it work.

Full email example:
```
{{ define "subscriber-optin" }}
{{ template "header" . }}
<title data-i18n>Hey {{ .Subscriber.FirstName }}!</title>

<h2>{{ L.Ts "email.optin.confirmSubTitle" }}</h2>
<p>{{ L.Ts "email.optin.confirmSubWelcome" }} {{ .Subscriber.FirstName }}</p>
<p>{{ L.Ts "email.optin.confirmSubInfo" }}</p>
<ul>
    {{ range $i, $l := .Lists }}
        {{ if eq .Type "public" }}
            <li>{{ .Name }}</li>
        {{ else }}
            <li>{{ L.Ts "email.optin.privateList" }}</li>
        {{ end }}
    {{ end }}
</ul>
<p>{{ L.Ts "email.optin.confirmSubHelp" }}</p>
<p>
    <a href="{{ .OptinURL }}" class="button">{{ L.Ts "email.optin.confirmSub" }}</a>
</p>
<a href="{{ .UnsubURL }}?manage=true">{{ L.T "email.unsub" }}</a>

{{ template "footer" }}
{{ end }}
```
