### ISSUE TITLE
Can't send an email, no internet access from app container

### ISSUE THREAD

**Issue by BenoitEirik** [knadh/listmonk#1911]
**Version:**
 - listmonk: v3.0.0
 - OS: Debian 12

**Description of the bug and steps to reproduce:**
I have installed Listmonk using Docker, I can log into the app on my server can add lists, campaigns, subscribers, etc. but I can't send an email when I setup SMTP parameters (the parameters are correct). I got the error: `dial tcp 213.156.68.104:587: connect: network is unreachable`
I'm on an IPV6 only server with a DNS64.

I tried to ping on the `app` container by I can't to any domain/IP. So I conclude that the container does not have internet access.
Is this normal ?
Thank you for any help.

**Comment by knadh** [comment]
This is not normal. It must be a firewall configuration issue.

**Comment by BenoitEirik** [comment]
> This is not normal. It must be a firewall configuration issue.

Thank you for your response.
All my outgoing traffic is open so for SMTP this shouldn't be a problem.
What problem could be the cause of the error in the firewall?

**Comment by MaximilianKohler** [comment]
What firewall are you using? There's another issue covering docker & firewalls.
