### ISSUE TITLE
Query working yesterday and not today

### ISSUE THREAD

**Issue by bestbrian** [knadh/listmonk#1912]
**Version:**
 - listmonk: 3.0.0
 - OS: Linux

**Description of the bug and steps to reproduce:**
I want to query a list to get back a certain number of subscribers. This was working perfectly fine yesterday:
`subscribers.email LIKE '%gmail%' AND
(subscribers.uuid IN (
    SELECT subscribers.uuid
    FROM subscribers
    WHERE subscribers.email LIKE '%gmail%'
    ORDER BY subscribers.email
    LIMIT 200
))`
but not today. If I remove "FROM subscribers", it runs the query but without the LIMIT. I can use the same code in subscribers and it works with the LIMIT, but now it doesn't give me the users from the list I want to see. I tried many variations of this:
`subscribers.email LIKE '%gmail%' 
AND subscribers.id IN (
    SELECT subscriber_id 
    FROM subscriber_lists 
    WHERE list_id = 16
)
AND subscribers.id IN (
    SELECT id 
    FROM subscribers 
    WHERE email LIKE '%gmail%' 
    ORDER BY email 
    LIMIT 200
)` 
to no avail. I'm just not sure why it was working yesterday and not today. If anyone has any idea or how to reference the list I want to target (16), please let me know. Thank you

**Comment by knadh** [comment]
You can do this easily by doing this:
- Go Lists. Click on the "View" link under the Subscribers column where the subscriber count is shown. You'll land on the subscribers page for that particular list.
- Use the expression `email LIKE '%gmail.com'`

**Comment by knadh** [comment]
```sql
id IN (SELECT id FROM subscribers WHERE email LIKE '%gmail.com' LIMIT 200)
```

The UI will only render paginated results. To select all rows selected by your query, click on the select checkbox in the table header in the results and when the options show, click on `Select all $num` above the table.

**Comment by bestbrian** [comment]
This is exactly what I was looking for, thank you so so much!!!
