### ISSUE TITLE
New subscriber gets "That feature is not available."

### ISSUE THREAD

**Issue by popey** [knadh/listmonk#1913]
**Version:**
 - listmonk: v3.0.0 (f9120d9 2024-02-04T11:20:27Z, linux/amd64)
 - OS: Ubuntu 22.04

**Description of the bug and steps to reproduce:**

I created a brand new mailing list, then shared the [url](https://newsletter.popey.com/). 
Someone using Firefox attempted to subscribe but got a json response "That feature is not available".

I'm not a Go developer, but I looked through the listmonk source and it seems like that comes from [here](https://github.com/knadh/listmonk/blob/master/cmd/public.go#L280) which says `// Is preference management enabled?`

I have 'Allow preference changes' enabled. Full privacy settings screenshot below.

Nothing in the logs on the server from running `journalctl -fu listmonk.service`

**Screenshots:**

![image](https://github.com/knadh/listmonk/assets/1841272/d2e5a29b-1316-4dd9-b311-494cf5e200ea)

![image](https://github.com/knadh/listmonk/assets/1841272/5dfeacf3-824a-47d3-a605-9898d0e4ecda)

**Comment by bit101** [comment]
I'm the someone who was attempting to subscribe. On this initial form page, I get these errors in the console. 

<img width="547" alt="image" src="https://github.com/knadh/listmonk/assets/376980/ad6e6fe0-7984-46da-a6d8-5ed4d4003d32">

After pressing the subscribe button, I get these: 

<img width="547" alt="image" src="https://github.com/knadh/listmonk/assets/376980/725b3c77-8b47-4480-be77-7016967b4d9b">

Getting the same thing on Firefox and Chrome on MacOS and Firefox on Kubuntu

**Comment by popey** [comment]
Aha! I think I see what is going on there. I was loading the favicon and logo from another domain (popey.com rather than newsletter.popey.com) which I assumed was okay, and clearly isn't. I've uploaded the items to the site and changed the settings.

If you refresh the page, to reload the assets, and try again, does that fix it?

**Comment by bit101** [comment]
OK, weirdly, I keep getting the same error, but it works in incognito mode.
I went back and disable every extension I had installed and still get the error in normal mode.
But maybe it's down to caching.

**Comment by knadh** [comment]
This error is thrown when the:
- Settings -> General -> Enable public subscription page option is disabled.
- The hidden "nonce" field on the form is empty (happens when bots fill the form or if a browser extension interferes with the form).

PS: @popey I did a test signup on your page and it worked fine.
