### ISSUE TITLE
Custom form with custom success page?

### ISSUE THREAD

**Issue by jettlorenzo** [knadh/listmonk#1915]
I know you can create custom HTML forms and set HTML form action as Listmonk.
As shown in: https://listmonk.example.com/admin/lists/forms

The problem is the user is then directed to the default Listmonk success page after submitting the form, I was hoping to take users to another landing page after they subscribe, how can this be achieved?

**Comment by knadh** [comment]
Hi @jettlorenzo. If you'd like to fully customize the form + response experience, you should use the API and script your own form.

**Comment by jettlorenzo** [comment]
Hey @knadh I figured that might be the answer, I typically use html and php, is it possible to script the response experience using these?

**Comment by knadh** [comment]
Yes, of course. Your script can receive user input, register with listmonk using its API, and then show whatever response you want.
