### ISSUE TITLE
Sliding window limit does not work

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1917]
**Version:**
 - listmonk: v3.0.0
 - OS: Repocloud

**Description of the bug and steps to reproduce:**
I enabled sliding window limit, but it did not pause sending the campaign once the limit was crossed

**Screenshots:**
![image](https://github.com/knadh/listmonk/assets/8183572/22a5021b-ac2b-4736-a59d-96cb1caf17a9)

**Comment by knadh** [comment]
Hi @benstaf. It doesn't actually pause the campaign, but silently waits and refrains from sending messages. The campaign continues to be in the `running` status. Did you observe messages being sent continuously? Please try with a shorter interval to observe the behaviour.
