### ISSUE TITLE
GCP S3 Not supported

### ISSUE THREAD

**Issue by malayh** [knadh/listmonk#1918]
**Version:**
 - listmonk: [eg: v3.0.0]
 - OS: [Using the official docker image]

**Description of the bug and steps to reproduce:**
Uploading media to a Private S3 bucket in GCP generates incorrect signed URL for the objects

**Screenshots:**
Configuration

<img width="1920" alt="Screenshot (66)" src="https://github.com/knadh/listmonk/assets/18195461/1f478ed8-07c5-4d17-9e85-e52dfb75faaf">

Incorrect URL
![Screenshot (67)](https://github.com/knadh/listmonk/assets/18195461/d8c6e00a-de8d-47e2-900e-a8c7869603f4)

**Comment by knadh** [comment]
Can you try specifying the `Custom Public URL` field?
