### ISSUE TITLE
Forward previous campaigns

### ISSUE THREAD

**Issue by PaulMcF1987** [knadh/listmonk#1919]
I use Listmonk, self-hosted on Docker to send emails to suppliers, Obviously, this allows me to email multiple suppliers with just one message.

On occasions, the details may change from the email which was initially sent, and I then need to send a new email with no email trail linking back to the previous email that I sent
It would be great if there was an option to "Forward" the previous chain, which would allow me to details the changes in the new message but also have the previous email visible below as if it was being forwarded from Outlook

Is this something that could be implemented?

**Comment by knadh** [comment]
Hi @PaulMcF1987. This wouldn't be feasible. You'll have to clone the previous campaign into a new one and edit it manually to make it look a certain way. The tracking links in the content will automatically point to the new campaign.

**Comment by PaulMcF1987** [comment]
@knadh I wouldn't expect the way the tracking links worked to change, I would expect this to be the case.

I was more meaning the format.

I have set up an email template which i use in listmonk so for me to make it look like a forwarded email wouldn't be possible.

If, rather than cloning, there was also a forwarding option which had something like

```
<email>
    <template>
        "New message text"
    </template>
    -------- Forwarded Message --------
    Subject: | Email Subject
    Thu, 27 Jun 2024 15:11:16 +0100
   Sender <sender@email.co.uk>
    <Forwardedemail>
        "previous email text"
    <forwardedemail>
<email>
```

**Comment by knadh** [comment]
Hi @PaulMcF1987. As I said, this isn't feasible and it's a very niche requirement to be considered as a generic, reusable feature. You will have to copy the contents and manually edit it to give the appearance you'd like, like that of a forwarded message.
