### ISSUE TITLE
button to resend OptIn email

### ISSUE THREAD

**Issue by sweetppro** [knadh/listmonk#192]
It would be great if there was a button to resend the OptIn email for subscribers

**Comment by knadh** [comment]
![image](https://user-images.githubusercontent.com/547147/93978510-ba8f5280-fd99-11ea-948c-87c4407b50d6.png)

^ This?

**Comment by sweetppro** [comment]
That sends to everyone though, does it not?
I’m looking at a resend per user button. For those users who misplaced/ignored the initial optin.

**Comment by knadh** [comment]
It'll only e-mail subscribers who have not confirmed the opt-in.

Per use is a possibility, but will probably need additional controls to select the lists for which the confirmation has to be sent. Will explore this.

**Comment by knadh** [comment]
`v0.9.0-beta` which was just released, has some changes related to this. Simply updating a subscriber on the UI who hasn't confirmed opt-in lists will receive an opt-in subscription e-mail. I missed out on adding an explicit `resend opt-in confirmation` on the UI, but will add that in the next release.
