### ISSUE TITLE
Easy way to remove inactive Subscribers

### ISSUE THREAD

**Issue by tanmay-predisai** [knadh/listmonk#1920]
We have been using Listmonk for some months and is working well for us! Thank you for the product!

**Is your feature request related to a problem? Please describe.**
We are looking to remove inactive subscribers from our lists. The idea is to keep pruning lists by removing subscribers that have not opened emails for last x days (say 60 days). This helps in maintaining a reasonable open rate. 

I searched for a way to query subscribers using the SQL expressions but could not. 

**Describe the solution you'd like**
Would you be able to explain how to query for subscribers who have not opened any email for last x days? 

Or Please add this as an option under the maintenance section. It can have a simple option "Last opened since" and the option to mark as unsubscribe. This is a pretty standard feature of most of the newsletter tools. 

Thank you!

**Comment by MaximilianKohler** [comment]
>The idea is to keep pruning lists by removing subscribers that have not opened emails for last x days (say 60 days).

Open-rate tracking in listmonk is not accurate https://github.com/knadh/listmonk/issues/1025. Open-rate tracking in general is not reliable as it depends if people choose to "load external images".

**Comment by knadh** [comment]
@tanmay-predisai perhaps something like this? https://github.com/knadh/listmonk/issues/1337#issuecomment-2185477862

**Comment by tanmay-predisai** [comment]
@knadh Apologies for the delayed reply - yes the example in the given comment worked for us. Thank you for the help.
