### ISSUE TITLE
If I have bounce processing off, means I will never know if a mail bounces?

### ISSUE THREAD

**Issue by kamazeuci** [knadh/listmonk#1923]
As the title says.... I turned off mail bouncing but I'm afraid this is not letting me know of any failure/bounces.
Or it has nothing to do?

thanks!

**Comment by kamazeuci** [comment]
So, I turned bounce processing on, and put some non-existent email addresses on the list, to check if bouncing is working OK, but got no bounces...

**Comment by kamazeuci** [comment]
I have created a specific mail account (that does support POP3) and am using it as the "From" field in the listmonk campaign, but it is not getting any bounces...

**Comment by knadh** [comment]
Please Settings  -> Logs to see if non-existent e-mails are being rejected instantly by the mail server at the time of sending.
