### ISSUE TITLE
Error using integers in a template

### ISSUE THREAD

**Issue by daurpam** [knadh/listmonk#1924]
Hello,
I'm trying to apply a logic to the template for a campaign. With this attribute: **{ "years" : "15" }**
If I use this in a template: **{{ if eq .Suscriber.Attribs.years "15" }}** it works

But I would like to use the value as number not text, then attribute is: **{ "years" : 15 }** but template didn't work:
**{{ if eq .Suscriber.Attribs.years 15 }}**

What I'm doing wrong? Why doesn't work?

Thank you

**Comment by knadh** [comment]
This is because of how Go represents types in the JSON map internally. You can use the Sprig `int` function to treat the number as an int.

` {{ if eq (.Suscriber.Attribs.years | int) 15 }}`

Please refer to the Sprig docs: https://masterminds.github.io/sprig/conversion.html
