### ISSUE TITLE
'Subscribe' link on the archive page contains an extra space

### ISSUE THREAD

**Issue by halphalp** [knadh/listmonk#1925]
i'm running the latest version of listmonk via docker (also confirmed this exists on the public demo instance) and noticed the 'Subscribe' link in the 'Archive' page contains an extra space found before the word 'Subscribe'.

**Comment by arshkumarsingh** [comment]
Is this what you are talking about 
![listmonk](https://github.com/knadh/listmonk/assets/66940182/34048433-b8d5-4aa2-8568-960c8ba5b7f7)

**Comment by arshkumarsingh** [comment]
@knadh what file is this caused by I could quickly fix this, assign if suitable

**Comment by MaximilianKohler** [comment]
I couldn't find an extra space in `/static/public/templates/archive.html`.
