### ISSUE TITLE
listmonk delivers mails OK but non existent email addresses don't deliver bounces back.

### ISSUE THREAD

**Issue by kamazeuci** [knadh/listmonk#1928]
**Version:**
 - listmonk: 3.0.0~ynh1
 - OS: yunohost (debian)

**Description of the bug and steps to reproduce:**
I am getting no mail bounces. I have specifically added non existent email addresses to the test list (like daosdniasoindoasndonace8nc89@hotmail.com, and others from different domains and servers that I handle), but they don't bounce to the POP3 mail account that I have set up specifically for mailing with listmonk. Also, in stats, I get "0 bounces", but I know these email addresses are fake so something is not right. I have set up the correct mailing address both in the from field (in both default settings and in campaign) and also in SMTP header as a reply-to.

**Comment by knadh** [comment]
Please Settings -> Logs to see if non-existent e-mails are being rejected instantly by the mail server at the time of sending.

**Comment by nayanthulkar28** [comment]
Was looking at this issue. No, the mail server is not rejecting any non-existing e-mails. It is giving err as nil if we are making smtpPool call using wrong e-email. @knadh
