### ISSUE TITLE
Make tracking anonymous

### ISSUE THREAD

**Issue by knadh** [knadh/listmonk#193]
listmonk registers link and click tracking impressions against specific subscriber IDs. While this data isn't visible on the UI right now (except for aggregate graphs), internally, that's how it is. While a subscriber can get a copy of this data or wipe it remotely (if the admin permits), it is still personally identifiable tracking data. I hadn't given this much thought early on, but this is a feature with significant ethical implications. An admin can track clicks and views in many ways, but I don't think this is something listmonk should support out of the box.

**Proposal:** Views and link clicks (using the optional template tags) should no longer be linked to subscriber IDs internally. This changes nothing on the current listmonk UI and it will still be possible to visualize views and clicks, but they will no longer be personally identifiable.

Would be great to get feedback on this.

**Comment by knadh** [comment]
- Add switches on the Settings > Privacy UI to turn view tracking and click tracking on off. These switches will determine if an event is registered irrespective of the tracking template tags being present in an e-mail.

- Refactor the `campaign_views` and `link_clicks` tables, and the related functions and queries to lose the `subscriber_id`. Have to add a migration for this breaking change too.

**Comment by tttp** [comment]
Hi,

I would argue that tracking open and clicks and linking them to contact is acceptable **if** the contact has been informed and gave explicit consent **and** has an option to withdraw this authorisation (I'm not sure if it's ethical to put it in an endless privacy policy, but that's another issue).

On a practical level, we've used the tracking at the contact level for:
- being able to put "on ice" folks that didn't open/click in the emails sent in the past x months, and only send them the "most important" emails until they re-engage.
- being able to remove emails that haven't opened/clicked on an email for y>x months. No point to pay sending emails to contacts that aren't engaging with our campaigns
- being able to dedupe the open/clicks from a same contact. Some mail clients go crazy and "open" (load the external image) tons of time, of  if I forward an email I receive to a mailing list or publish it on my website, everyone clicking on that link will be counted as me clicking. Counting "distinct" open/clicks is less good for the ego, but way more reliable
- being able to do analytics at the domain name level (eg "@gmail.com" emails have an unreliable open measurement, as google's proxy downloads the image even if the recipient doesn't read the email)
- being able to recover from a website crashing (happened once): we sent a link to a site that was down, we were able to send a "website back online" only to those that clicked

For privacy reason, being able to disable the tracking on a per install or campaign would be great, but I'd argue it has its benefit to track at the contact level.

An option might be to aggregate and remove individual events for older emails.eg count and store the aggregate of unique clicks and open for mailing older than x months, update "last clicked/last opened" for each contact and then remove all the open/click events of these mailings

**Comment by knadh** [comment]
> being able to remove emails that haven't opened/clicked on an email for y>x months. No point to pay sending emails to contacts that aren't engaging with our campaigns.

This is a pertinent point. Removing subscribers who  are no longer interested in the e-mails. I'd forgotten about this, but at work, we're required by regulations to have "proof of receipt", and "proof of delivery" (usually as mailserver logs). There's that too.

> For privacy reason, being able to disable the tracking on a per install or campaign would be great, but I'd argue it has its benefit to track at the contact level.

Opt-in and consent collection falls outside the scope of listmonk as subscribers can be added in indefinite ways using the API or bulk import mechanisms. A compromise is to have an "enable personal tracking: on/off" switch in settings which is off by default, and its the responsibility of the admin to turn it on manually and comply with privacy laws and regulations.

**Comment by knadh** [comment]
This is now merged to master: https://github.com/knadh/listmonk/commit/1b279478fba51dae4dd8af585e8cc456028f71b3

![image](https://user-images.githubusercontent.com/547147/96367316-bd981b80-116a-11eb-8f62-7ebb83aa06ce.png)
