### ISSUE TITLE
A real mailing list manager?

### ISSUE THREAD

**Issue by theotherandre** [knadh/listmonk#1932]
Hi,

am I right, that Listmonk only knows the direction Listmonk -> subscribers? I. e. can, like in a real mailing list subscribers send in a mail 'to the list' that will be delivered to all other subscribers? I think no. At least I don't see any hints in the documentation how to set this up (or oversaw them).

If so, it would be fair enough to explicitly state this in the docs, e. g. 'Listmonk can only be used to send mails out  to subscribers by the admin of the list. It is not intended for mail delivery from a subscriber to all other subscribers!'
Sorry if I got anything wrong, but I went through the hassle of setting it up only to find out, what Listmonk probably really is made for...

**Comment by knadh** [comment]
listmonk is indeed a one-way mailing list. Will add this to the intro in docs to make it explicit. Thanks for pointing out.

**Comment by lispstudent** [comment]
I also went through the install requirements (including mail server) because I need a true Mailing List Manager, ie MailMan, Mlmmj, Sympa, etc. Perhaps it would help to say Listmonk is a Newsletter manager?

**Comment by knadh** [comment]
This is added to docs and the site in https://github.com/knadh/listmonk/commit/139267d57ef16dcf0ed26edc9564657a39b95823
