### ISSUE TITLE
Issue with Adding Unsubscribe Function in Listmonk Docker Installation

### ISSUE THREAD

**Issue by majdidraouil** [knadh/listmonk#1934]
I am encountering a problem while trying to add an unsubscribe function to my Listmonk installation, which is running in a Docker container on a VPS. Specifically, I am unable to correctly implement the unsubscribe link in the email templates and handle the removal of subscribers from the database upon clicking the link.

**Comment by MaximilianKohler** [comment]
What trouble are you having? The pre-made links in the default templates work fine for me. I've also added them to email bodies without issue.
