### ISSUE TITLE
Incorrect Example Request in Listmonk API Documentation

### ISSUE THREAD

**Issue by Prachi-Jamdade** [knadh/listmonk#1939]
I noticed an error in the example request provided for the Listmonk API documentation at various places.

The documentation currently shows the following example for Basic Auth examples of ```Lists``` , ```Import``` , ```Media``` , ```Templates``` .

**Issue:**

The documentation currently shows the following example for a endpoint request:

```
curl -u "username:username" -X GET 'http://localhost:9000/api/templates'
```

This example uses the same value for both the username and password, which is incorrect.

**Correction:**

The correct example should differentiate the username and password, as shown below:

```
curl -u "username:password" -X GET 'http://localhost:9000/api/templates'
```

**Screenshots:**

Screenshot showing the incorrect example (401 Unauthorized error):

![WhatsApp Image 2024-07-15 at 10 01 46 PM](https://github.com/user-attachments/assets/67e852a4-04de-42d0-b236-27efa223bce8)

Screenshot showing the correct example (200 OK response):

![WhatsApp Image 2024-07-15 at 10 03 19 PM](https://github.com/user-attachments/assets/892f150a-e21b-4c0e-af1e-ae8c637ea818)

**Steps to Reproduce:**

1. Follow the current example provided in the documentation
2. Observe that it returns a 401 Unauthorized error.
3. Use the corrected example
4. Observe that it returns a 200 OK response.

**Expected Behavior:**

The documentation should provide a correct example that successfully authenticates and returns a 200 OK response.

**Comment by Prachi-Jamdade** [comment]
Hello, @knadh 

I can work on this and will raise a PR to fix this in the documentation. Let me know what you think, will do it if it's a go-ahead from you

**Comment by knadh** [comment]
Please send a PR. Thnak you.
