### ISSUE TITLE
Listmonk on HTTPS 

### ISSUE THREAD

**Issue by daway46** [knadh/listmonk#1940]
I can access listmonk with IP address on HTTP but struggling to work for HTTPS. 

I cannot configure Gmail as an SMTP client because the password is sent via clear text with default HTTP on port 9000

I installed an SSL certificate for listmonk.mydomain.com and added DNS A record that point to my website server but when I cannot access https://listmonk.mydomain.com:9001 or via https://67.68.69.70:9001

I had to use 9001 for HTTPS because HTTP use 9000

The below my config.toml 

#address = "67.68.69.70:9001"
address = "listmonk.mydomain.com:9001"
#address = "67.68.69.70:9000"

# HTTPS server
[https]
enabled = true
address = "67.68.69.70:9001"
cert_file = "/etc/letsencrypt/live/mydomain.com/fullchain.pem"
key_file = "/etc/letsencrypt/live/mydomain.com/privkey.pem"

# HTTP server.
[http]
address = "67.68.69.70:9000"

I am using wordpress litespeed web server, hosted on vultr. Any inputs or suggestion will help.

**Comment by daway46** [comment]
I can access my DNS URL http://listmonk.mydomain.com:9001/ with new port but problem is it only works for HTTP, not HTTPS

below is my updated config.toml file where I commented HTTP related configuration
address = "67.219.107.173:9001"
#address = "listmonk.daveoncyber.com:9001"
#address = "67.219.107.173:9000"

# HTTPS server
[https]
enabled = true
address = "67.219.107.173:9001"
cert_file = "/etc/letsencrypt/live/daveoncyber.com/fullchain.pem"
key_file = "/etc/letsencrypt/live/daveoncyber.com/privkey.pem"


# HTTP server.
#[http]
#address = "67.219.107.173:9000"

**Comment by MaximilianKohler** [comment]
Have you looked through the tutorials in the docs?

**Comment by knadh** [comment]
@daway46 SMTP configuration for Google has no relation to whether listmonk is configured on http or https. That said, if you're running a public instance of listmonk, it should definitely be on https.

listmonk does not have built-in TLS/https support, so the config you've pasted above are not supported by listmonk. config.toml only takes the config parameters that you see in the [sample config](https://github.com/knadh/listmonk/blob/master/config.toml.sample).

You should use a reverse proxy like Nginx or Caddy and put listmonk behind it. Caddy is [simple to configure](https://caddyserver.com/docs/quick-starts/https).

I am closing this issue as it is unconnected to listmonk.

**Comment by fedmod** [comment]
> Have you looked through the tutorials in the docs?

of course yes  
noithing related to this issue. 

There are other users with a similar problem that should be fixed in latest versions. 
but I have the latest version, so no idea. 

THE TRACKED LINKS appear in html like this (before sending) 

<a href="https://www.facebook.com@TrackLink">facebook.com</a></p>  

and after 

Facebook:=C2=A0<a href=3D"ht=
tps://sitomonk.com/link/27fcf379-7c3d-4da7-8b94-4dc659567a67/7b0f75c7-=
0f6e-42e0-abfc-c3823237ef95/0739c84b-2470-4a72-ba0c-383789f7b0c0">facebook.=
com</a></p>
