### ISSUE TITLE
Safari has issues with HTTP 307 generated by TrackLink

### ISSUE THREAD

**Issue by usverger** [knadh/listmonk#1941]
**Version:**
 - OS: MacOS or iOS

**Description of the bug and steps to reproduce:**
{{ TrackLink }} macro generates a link like this:
https://hostname/link/1c11119e-82d3-469c-9253-5ca542c555ef/d11dc1c1-7943-48d9-8072-e0002ed3f446/e1198f57-6a46-4bf2-a7af-b097e41b647c. This link responds with HTTP 307 that is supposed to redirect to a real address.
Apparently, Safari has issues with HTTP 307, both desktop and mobile. Instead of following the redirect, it shows an error page with "server unexpectedly dropped the connection"
Any other browser works just fine.

Looking at url shortener services, they use HTTP 301 and safari seems to have no issues with it.

This feels like a major issue, makes link tracking unusable for all Apple recipients.

**Comment by knadh** [comment]
HTTP 307 being completely broken in Safari seems highly unlikely. I was unable to find any references to such an issue after searching for a few mins. Could you please share a few links that explain this?

**Comment by usverger** [comment]
I agree, I could not find much. My experiment of creating a simple app that responds with 307 did not confirm the issue as well. It worked in safari with no problems.
