### ISSUE TITLE
Import finished campaigns from other providers

### ISSUE THREAD

**Issue by Mokkapps** [knadh/listmonk#1945]
I want to import my campaigns from another provider via your API. But I cannot see an option to set the `created_at` or `started_at` property via a campaign endpoint? 

Otherwise all imported campaigns would have the same creation date.

Thanks for this amazing project and your support!

**Comment by knadh** [comment]
Hi @Mokkapps. `created_at` and `started_at` are internal record-keeping meta fields that are automatically set. They cannot be modified via the API. If you'd really like to change them, you'll have to do it directly in the database via SQL queries.

**Comment by Mokkapps** [comment]
> Hi @Mokkapps. `created_at` and `started_at` are internal record-keeping meta fields that are automatically set. They cannot be modified via the API. If you'd really like to change them, you'll have to do it directly in the database via SQL queries.

Ok, thanks for your advice!
