### ISSUE TITLE
How do we cache using CDN the webpages for listmonk

### ISSUE THREAD

**Issue by nascarsayan** [knadh/listmonk#1947]
Firstly, let me start with a lot of appreciation on the project and the each of the interesting utilities that are self-created and used here, like goyesql, stuffbin, koanf. The whole idea of embedding everything into a single go monolith is something I liked for some years now (being a DHH fan myself, now a knadh fan too). 

I have one small query. If we built a user-facing application where users are spread across the globe, and there are a lot more static webpages, we'd require a CDN-like cache. What would be a good CDN to use with the architecture used in this application? Can we use Cloudflare here?

**Comment by knadh** [comment]
Hi @nascarsayan. You can use any CDN including CloudFlare. CDNs (that proxy) generally pick files from the origin once and then cache them globally at their "edges", serving the cache to users based on their location from the closest edges.
