### ISSUE TITLE
[api] test email for campaign api requires all parameters

### ISSUE THREAD

**Issue by iloveitaly** [knadh/listmonk#1948]
**Version:**
 - listmonk: 3.0.0
 - OS: ubuntu

**Description of the bug and steps to reproduce:**
[The `/test` endpoint](https://listmonk.app/docs/apis/campaigns/#post-apicampaignscampaign_idtest) seems to require *all* params that the creation endpoint does. Just passing `subscribers` returns a validation error.

I ran into this when building https://github.com/iloveitaly/listmonk-newsletter

**Comment by knadh** [comment]
This is by design. This allows the campaign to be tested before it’s saved to the DB. Having to save every change to the DB only to test it is not ideal.

**Comment by iloveitaly** [comment]
Got it, that case makes sense.

Does this apply to *after* the campaign is created and persisted to the DB? Would be better for users if only `subscriptions` is required to send test emails if the campaign has already been fully created.

The docs state that only `subscriptions` is required, so I can submit a PR to better document this functionality.

**Comment by knadh** [comment]
Yep, it always takes the inputs from the form, saved or unsaved, to send the test. Please do send a PR to fix the docs. Thank you.
