### ISSUE TITLE
Limit on number of Lists

### ISSUE THREAD

**Issue by sbgmedia** [knadh/listmonk#195]
Hello,

Is there a limit on the number of lists that can be created. I am having trouble adding more than 30.
Please note I am playing around with the demo setup.
Thank you.

**Comment by knadh** [comment]
There are no limits. Are you getting any errors?

**Comment by jackdanielux** [comment]
No errors on UI, it shows green prompt "Sent".  Any way to check via root
login?

**Comment by sbgmedia** [comment]
Hi,
No errors..I looked further into it and it is actually a pagination issue and I believe it was fixed as per issue #176 
I setup listmonk locally via docker. How do I update it to the version with the fix?

**Comment by knadh** [comment]
Ah yes, that's not been released just yet (very soon). You can get it earlier by pulling the repo and compiling `master` manually.

**Comment by sbgmedia** [comment]
Do you have an idea when the docker update will be released?

Thanks

**Comment by knadh** [comment]
Hopefully in the next 10 days. The planned features are all ready and need to be tested.
