### ISSUE TITLE
Export of unsubscribed users exports all users

### ISSUE THREAD

**Issue by lorenzode** [knadh/listmonk#1950]
**How it is:**

The Export button on `/admin/subscribers/lists/3?subscription_status=unsubscribed` exports all users in the list irregarding of status.

**How it should be:**

Export only unsubscribed users.

**Steps to reproduce:**

- Click on `Unsubscribed: 51` (in my case there are 51 unsubscribed users for this list) in `/admin/lists`

![Screenshot from 2024-07-22 14-58-23](https://github.com/user-attachments/assets/ab07a4bc-9d45-40e9-b291-fbd3a610bf3e)

- On the subsequent page  `/admin/subscribers/lists/3?subscription_status=unsubscribed` click the Export button above the list

![Screenshot from 2024-07-22 14-59-46](https://github.com/user-attachments/assets/8f0fbf46-340c-44d6-9e81-726197c485fb)

- I get a confirmation pop up window:

![Screenshot from 2024-07-22 14-49-30](https://github.com/user-attachments/assets/8a1b9d4b-53ae-453f-b1c7-42ace83766a9)

- Open the resulting CSV. Instead of 51 users it contains the full list of confirmed, unconfirmed and unsubscribed users for this list.

**Version:**

Self hosted v3.0.0

Thank you for looking into this! Best

Edits: Clarification

**Comment by MK-0x41** [comment]
I have the same issu on elfhostet docker v3.0.0

**Comment by keshavg2** [comment]
Hi @knadh can I work on this issue?

**Comment by knadh** [comment]
Yes, sure @keshavg2.
