### ISSUE TITLE
No special characters (ä, ö, ü, ß, etc.) in attachments

### ISSUE THREAD

**Issue by KarlKeu00** [knadh/listmonk#1955]
**Version:**
 - listmonk: v3.0.0
 - OS: Docker

**Description of the bug and steps to reproduce:**
1. Create a file with (German) special characters in the name.
2. Create a new campaign.
3. Attach "special" file to campaign (no error message or warning).
4. Try sending campaign.

**Comment by knadh** [comment]
Hi @KarlKeu00. What happens when you try sending? It doesn't send? Throws an error? Please add those details also, with screenshots if possible.

**Comment by KarlKeu00** [comment]
When I upload a new file in a campaign, this campaign is sent without an error message but also without attachments.
However, as soon as I select an existing file in a new campaign, the following error message appears (the file name was "Test-ä-ß.txt"):
<img width="1343" alt="Example" src="https://github.com/user-attachments/assets/77ec67a3-8b95-4040-8d92-d57ce40f98bb">
Perhaps it would be helpful to automatically replace all special characters?

**Comment by knadh** [comment]
I think replacing all chars automatically is the solution here indeed.

**Comment by Bowrna** [comment]
can i take a look at this issue?

**Comment by knadh** [comment]
I just realised, figuring out how/what to replace with is tricky. What does `汉语.png` become for instance? Or `File-മലയാളം-name.pdf`. hmm. Or the backend has to completely reject non-ASCII characters in filenames with an error to make it explicitly known.

**Comment by thebootable** [comment]
> Alternatively, you could simply enter a hash or GUID as the file name for all attachments that only consist of special characters or are not unique after removing all special characters. This would not be as user-friendly, but would at least work.

That's not know not adding user friendlyness but probably making it worse. I'd hate if my attachments got named after a UUID without me knowing why.
It's probably better to just reject those cases during the upload and add a easy to understand error message ("no special characters").
