### ISSUE TITLE
Public/Private Lists ~ 2 seperate send opt-in confirmations?

### ISSUE THREAD

**Issue by jettlorenzo** [knadh/listmonk#1956]
In the _/admin/settings_ page there is a _"send opt-in confirmations"_ toggle, but then there is also the _"Double opt-in"_ toggle inside each the individual list, I'm curious of the purpose of the settings one, when it always seems to follow the one set in the list?

I am also struggling to understand what this sentence means regarding public vs private lists:
_"Public lists are open to the world to subscribe and their names may appear on public pages such as the subscription management page."_
What is the _"...public pages such as the subscription management page."_ more specifically, why would that be describing a management page as public?

Lastly, Enable public subscription page must be turned on in settings, even if you set it to public in the lists, is this supposed to be like a global on off switch by design?

**Comment by knadh** [comment]
- "Send opt-in confirmation" in settings enables automatically sending the opt-in confirmation e-mail to users who are added to/subscribe to double-opt in lists. If this is off, when users subscribe, they don't get the confirmation e-mail automatically, and hence can't confirm. This is for building alternate confirmation mechanisms via APIs.

- Private lists: These are never exposed to the public subscription pages. Their names are never revealed in e-mails (even in opt-in confirmation and on unsubscribe pages). Their list UUIDs cannot be used in the public subscription APIs that you can use to make custom forms, or the built-in public subscription form. These are fully private and have no interface to the outside world.

- Public lists: Their names are public on built-in subscription forms, optin-confirmation e-mails, unsubscribe page etc. 

- Enable public subscription form: Enable / disable the built-in subscription form that allows subscription on public lists. If this is disabled (many users don't want the auto-generated sub form and want to customize subscription form, embed on their website etc), there's no default subscription form that listmonk will expose. You can use APIs to build your on subscription form.
