### ISSUE TITLE
Disable sending summary email for campaigns

### ISSUE THREAD

**Issue by julienvienne** [knadh/listmonk#1958]
When sending a campaign, would it be possible to disable the send of "Finished" email ?

**Comment by thebootable** [comment]
you can remove your mailaddress from the "admin notifications" in the settings menu. For me those are the only admin-mails I get so that would be sufficient, is that also an option for you?

**Comment by julienvienne** [comment]
ooh. I completly forgot this setting!
It is perfect, many thanks.
