### ISSUE TITLE
Templates - add option for default archive template

### ISSUE THREAD

**Issue by thebootable** [knadh/listmonk#1960]
**Is your feature request related to a problem? Please describe.**
I use two different templates, one for e-mail and one for the archive. This allows me to e.g. add a top-bar to the archive and some buttons linking to my homepage etc.
But with that I have to actively set the archive-template in every message, which is easy to forget.

**Describe the solution you'd like**
Having the option to define a separate template as the default template for archived messages would make sure I can't forget that and help with consistency.

**Comment by MaximilianKohler** [comment]
>I have to actively set the archive-template in every message, which is easy to forget.

What if you clone a previous campaign rather than create a new one?
