### ISSUE TITLE
how to query and segment subscribers according to lists?

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1968]
The documentation does not say how to query and segment subscribers according to the lists they belong to:

https://listmonk.app/docs/querying-and-segmentation/

**Comment by colinn** [comment]
I am also wondering about this - filtering the list by attribute works great in the Subscribers page, but all that allows you to do is export a subset of the list. You can't do anything useful like have a new dynamic list or even run a campaign. Am I missing something?

**Comment by knadh** [comment]
You can blocklist/bulk add/bulk remove the results of a query into other lists.

There are no dynamic lists yet (one can be created manually, and results can be bulk added to it, for now). Please see: https://github.com/knadh/listmonk/issues/250
