### ISSUE TITLE
Use annotated Git tags instead of lightweight tags for releases

### ISSUE THREAD

**Issue by vividvilla** [knadh/listmonk#197]
When I was running Listonk recently I noticed that it shows current version incorrectly. 

```
❯ ./listmonk --install
2020/10/03 03:12:46 main.go:64: v0.2.1-alpha-189-g23d479e (23d479e 2020-10-02T21:37:36+0000)
2020/10/03 03:12:46 init.go:91: reading config: config.toml
```

```
❯ ./listmonk --version
2020/10/03 03:23:51 main.go:64: v0.2.1-alpha-189-g23d479e (23d479e 2020-10-02T21:37:36+0000)
v0.2.1-alpha-189-g23d479e (23d479e 2020-10-02T21:37:36+0000)
```

This is because in `Makefile` `git describe` is used to get the current Git tag version but according to [Git docs](https://git-scm.com/docs/git-describe) it only returns annotated tags. To fix this we can use `git describe --tags` instead which also considers lightweight tags but its generally recommended to use annotated tags instead of lightweight tags for any releases. This Stackoverflow answer explains it neatly - https://stackoverflow.com/a/4971817/973508

@knadh I can create an MR to update the Makefile if you wish. For future releases you can consider annotated tags.

**Comment by knadh** [comment]
Thanks for fixing.
