### ISSUE TITLE
subscribers.email NOT LIKE ANY (ARRAY['%@gmail.com', '%@yahoo.com'])   - List not filtered 

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1971]
**Version:**
 - listmonk: [eg: v3.0.0]
 - OS: repocloud

In Lists, Advanced partial SQL, when I enter the query:

1. ` subscribers.email NOT LIKE ANY (ARRAY['%@gmail.com', '%@yahoo.com'])`

then the list is not filtered as it should. Nothing is filtered

However, if I enter:

2.   `subscribers.email LIKE ANY (ARRAY['%@gmail.com', '%@yahoo.com'])`  

then the query works correctly 

and if I enter:

`subscribers.email NOT LIKE '%@gmail.com' AND subscribers.email NOT LIKE '%@yahoo.com'`

it works too

Queries 1 and 3 give the same result, but 1 is more concise, especially because I want to input a very big list (because of issues https://github.com/knadh/listmonk/issues/1968 and https://github.com/knadh/listmonk/issues/1961 )

**Comment by shornabho** [comment]
> 1. ` subscribers.email NOT LIKE ANY (ARRAY['%@gmail.com', '%@yahoo.com'])`

@benstaf That partial SQL seems to be incorrect in achieving your desired result. I think the query you're rather looking for is:
`NOT (subscribers.email LIKE ANY (ARRAY['%@gmail.com', '%@yahoo.com']))`

Hope that helps.
