### ISSUE TITLE
Correct parameters to pass API request to send campaign test email?

### ISSUE THREAD

**Issue by panomitrius** [knadh/listmonk#1972]
**Version:**
 - listmonk: v3.0.0 
 - OS: Docker

**Description of the bug and steps to reproduce:**
I can't find a way to use API request to send campaign test email. I keep getting this error message:

```
{"message":"Invalid length for name."}
```

When using this bash script

```
#!/bin/bash

BASE_URL="https://link.to.listmonk"
USERNAME="listmonk"
PASSWORD="password"

CAMPAIGN_ID=16 

SUBSCRIBER_EMAILS=('test@test.com')


SUBSCRIBER_JSON=$(printf '%s' "${SUBSCRIBER_EMAILS[@]}" | jq -R -s -c 'split("\n")[:-1]')


curl -s -u "$USERNAME:$PASSWORD" -X POST "$BASE_URL/api/campaigns/$CAMPAIGN_ID/test" \
-H 'Content-Type: application/json;charset=utf-8' \
-d '{"subscribers": '"$SUBSCRIBER_JSON"'}' --verbose
```

The campaign I want to send has ID=16. What else do I need to pass to send the list?

**Comment by knadh** [comment]
Please refer to the docs: https://listmonk.app/docs/apis/campaigns/#post-apicampaignscampaign_idtest

> Use the same parameters in [POST /api/campaigns](https://listmonk.app/docs/apis/campaigns/#post-apicampaigns) in addition to the below parameters.

You've to pass the same params you'd pass to campaign creation.
