### ISSUE TITLE
SMTP settings for local self-hosted email server 

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1977]
Hi, I want to use a local self-hosted email server as a mail delivery platform, hosted on the same server as Listmonk (for example, a VPS server with [Postal](https://docs.postalserver.io/)+Listmonk), instead of using an external SMTP relay such as Sendgrid or AWS SES.

How should I configure the SMTP settings in this case?

![Screenshot_2024-08-06-15-06-39-604_com android chrome-edit](https://github.com/user-attachments/assets/97415f94-4973-422b-a4f7-4428ce4db460)

**Comment by knadh** [comment]
- If it's on the same VPS, you don't need TLS.
- Host: `127.0.0.1`. `Port` should ideally be 25 (or whatever else Postal gives you).
- Credentials, again, should be whatever you create in Postal.

Rest of the fields can be left as-is.

**Comment by benstaf** [comment]
It doesn't work, I am getting the error:
`dial tcp 127.0.0.1:25: connect: connection refused`

![Screenshot_2024-08-17-22-15-18-816_com android chrome-edit](https://github.com/user-attachments/assets/c3b88b63-4208-4cab-9625-8209a3a1add2)

If I connect to Postal from an external Listmonk server, it works normally 

I am investigating this issue (maybe Docker Network)

**Comment by benstaf** [comment]
`172.17.0.1` works for me. I found that on [Stackoverflow](https://stackoverflow.com/a/48547074)
