### ISSUE TITLE
api to get specific bounce id returns an error response

### ISSUE THREAD

**Issue by Bowrna** [knadh/listmonk#1979]
**Version:**
 - listmonk: development
 - OS: MacOS

**Description of the bug and steps to reproduce:**

 curl -X 'GET' -u listmonk:listmonk \
  'http://localhost:9000/api/bounces/840167' \
  -H 'accept: application/json'

I am making the above API call and it returns an error response. {"message":"Error fetching Bounce: pq: syntax error at or near \"rder\""}

On further debugging, 
https://github.com/knadh/listmonk/blob/e4dcb066d9ec5991c5cc27a6f877c76fbad8a4b1/internal/core/bounces.go#L42-L58

Here in Line 44, the query bounces statement has not replaced the "order" column  like how we do below in Line 26

https://github.com/knadh/listmonk/blob/e4dcb066d9ec5991c5cc27a6f877c76fbad8a4b1/internal/core/bounces.go#L16-L39

**Comment by flow6979** [comment]
hey @Bowrna i would like to work on this issue, you can assign this to me.
Thanks!!

**Comment by knadh** [comment]
Please free to send a PR @Bowrna @flow6979. Thank you.

**Comment by flow6979** [comment]
Hello @knadh @Bowrna please review [this PR](https://github.com/knadh/listmonk/pull/2007)
Thanks!!

**Comment by knadh** [comment]
Merged in #2007.
