### ISSUE TITLE
Site Not Loading, Can't Import Users or Access Campaigns

### ISSUE THREAD

**Issue by isarsb** [knadh/listmonk#1984]
**Version:**
 - listmonk: v.3.0.0
 - OS: [e.g. Fedora]

Hi Team,

I've been unable to load any data for the past two days. I can't import new users, and now I'm also unable to access or view my campaigns. The issue seems to affect the entire site—no data is being downloaded or displayed.

Is this a known issue? Could it be that Listmonk is experiencing a major outage? Please advise on the status and any steps to resolve this.

Thanks!

**Comment by knadh** [comment]
Hi @isarsb. There seems to be some confusion here. listmonk is an app that you download and run on your server. It’s not a service that is provided by its authors.

Where are you running listmonk? How did you set it up?
