### ISSUE TITLE
Bulk actions not working in the List detail view

### ISSUE THREAD

**Issue by tanmay-predisai** [knadh/listmonk#1985]
**Version:**
 - listmonk: v3.0.0
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**
1. Click on Menu -> List option
2. Click on the unsubscribe number CTA in the list to open this URL https://<domain>/admin/subscribers/lists/1?subscription_status=unsubscribed
3. Click Export. The Confirmation popup will state the exact number of subscribers in the popup.
4. When the actual export is downloaded, it has the entire list instead of the stipulated number of subscribers.

5. Click on the Select All CTA. The blacklist CTA will be visible now.
6. Click on Blacklist - The Confirmation popup will state the exact number of subscribers in the popup. 
7. Once you confirm, it will actually Blacklist the entire list instead of only doing it to the selected contacts. 

Also, what is the difference between Blacklist and unsubscribed contacts?

**Screenshots:**

**Comment by MaximilianKohler** [comment]
>Also, what is the difference between Blacklist and unsubscribed contacts?

Unsubscribe is only from the one list. Blocklist is from all lists, including future ones.
