### ISSUE TITLE
Authentication fails for custom database credentials but works with default database credential

### ISSUE THREAD

**Issue by rhosigma123** [knadh/listmonk#1987]
**Version:**
 - listmonk: v3.0.0
 - OS: Ubuntu

When i use default database credentials listmonk runs perfectly
2024/08/11 00:38:05 main.go:102: v3.0.0 (f9120d9 2024-02-04T11:20:27Z, linux/amd64)
2024/08/11 00:38:05 init.go:150: reading config: config.toml
2024/08/11 00:38:05 init.go:289: connecting to db: db:5432/listmonk
2024/08/11 00:38:06 init.go:618: media upload provider: filesystem
2024/08/11 00:38:06 init.go:541: loaded email (SMTP) messenger: username@smtp.yoursite.com
⇨ http server started on [::]:9000

When i custom database credentials listmonk fails with the below auth error
reading config: config.toml
2024/08/11 00:44:23 init.go:289: connecting to db: db:5432/abdussalam
2024/08/11 00:44:23 init.go:293: error connecting to DB: pq: password authentication failed for user "abdussalam"

![image](https://github.com/user-attachments/assets/44ff3a39-bcfc-45c8-9ae1-e3d0120ab158)

**Comment by richeshgupta** [comment]
Hey @rhosigma123 I just connected with custom db credentials and I was able to connect. Could you elaborate more if you are trying to connect to some remote host or trying to set db up locally?
I might be able to help you here.
