### ISSUE TITLE
error sending message: mail: unclosed angle-addr When trying to send sample emails (also no emails are sending)

### ISSUE THREAD

**Issue by komali2** [knadh/listmonk#1988]
**Version:**
 - listmonk: v3.0.0
 - OS: Ubuntu 22.04 (but within docker)

**Description of the bug and steps to reproduce:**
When attempting to send example emails, get an error:

```
mail: unclosed angle-addr
```

1. Have previously-confirmed-valid SMTP settings (gmail)
2. Re-enter SMTP password
3. Click "send test mail"
4. View error

Or

1. From within a campaign, click "send test message"
2. View "message sent successfully"
3. View secondary `mail: unclosed angle-addr` error after

Logs:

```
2024/08/11 10:07:03v3.0.0 (f9120d9 2024-02-04T11:20:27Z, linux/amd64)
2024/08/11 10:07:03reading config: config.toml
2024/08/11 10:07:03connecting to db: listmonk_db:5432/listmonk
2024/08/11 10:07:03media upload provider: filesystem
2024/08/11 10:07:03loaded email (SMTP) messenger: caleb@thejispot.com@smtp.gmail.com
2024/08/12 05:47:24error sending message in campaign August Holiday: subscriber 3: mail: unclosed angle-addr
2024/08/12 06:04:10error sending message in campaign August Holiday: subscriber 3: mail: unclosed angle-addr
2024/08/12 06:04:42error sending message in campaign August Holiday: subscriber 3: mail: unclosed angle-addr
```

**Screenshots:**
![2024-08-12-140350_1251x385_scrot](https://github.com/user-attachments/assets/462c2473-3277-4154-a947-e64d6be1fa70)
![2024-08-12-134935_1487x861_scrot](https://github.com/user-attachments/assets/8c37192d-2c3c-40f3-a82c-0cbf591fe3b3)

**Comment by knadh** [comment]
Whoa, haven't seen this one before. The error's saying that the e-mail is malformatted where it starts with `<` but doesn't end with `>`. Could you please try this with a different e-mail?

I have a feeling it is because of `508` being the domain name, hm.

**Comment by komali2** [comment]
> Whoa, haven't seen this one before. The error's saying that the e-mail is malformatted where it starts with `<` but doesn't end with `>`. Could you please try this with a different e-mail?
> 
> I have a feeling it is because of `508` being the domain name, hm.

Well that's interesting that you say that since the `from` should actually be `@thejispot.com` so I may have misconfigured something. It's odd though since we've already had one or two successful campaigns last month. Lemme double check that and report back.

**Comment by komali2** [comment]
Probably user error. Malformed "default `from` email" was `caleb@jispot.com@thejispot.com`. Must have accidentally changed it at one point.

**Comment by lebouquetin** [comment]
Note: I also got an error because of a sender email address including a coma, like `name, company<name@company.com>` (which should be accepted, I think)
