### ISSUE TITLE
Use a Data Table library 

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#1990]
The table interface can be greatly improved by adding a table library:

Compare with Ag-Grid, the gold standard: https://www.ag-grid.com/

It Supports React / Angular / Vue / Plain JavaScript.

Datatables is also very good: https://datatables.net/

And many other options: https://webix-ui.medium.com/10-data-table-libraries-for-javascript-in-2024-36d30a1fe100

Implementation is pretty quick in all cases

**Comment by knadh** [comment]
Hi @benstaf. listmonk already uses the the Buefy (Vue) table library. There are no plans to integrate any other libraries for now.
