### ISSUE TITLE
Double Opt-In List Confirmation Emails Fail to Send

### ISSUE THREAD

**Issue by amaisonneuvedev** [knadh/listmonk#1995]
**Version:**
 - listmonk: v3.0.0
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**
Deployed a working Docker setup. Tested the Single Opt-In and Double Opt-In, all worked flawlessly once properly setup.

A few weeks after deployment, Double Opt-In Confirmation emails no longer send to new subscribers. I have confirmed this, with other emails i have and the confirmation email doesn't arrive.

Reviewed all logs, email queues and email server logs. No errors, No stuck email or anything.

I'm not sure what steps I can take to further debug this.

I have restarted both the Dockers, App and DB. I also restarted the Email servers, web server. 

There was no change in DNS or configurations.

**Screenshots:**

**Comment by amaisonneuvedev** [comment]
Ok, yeah this there is definitely a bug somewhere about this, but i would love to get some additional ideas i can debug so that i can assist in identifying the fix.

**Comment by knadh** [comment]
Settings -> General. Maybe this was accidentally turned off? 

![image](https://github.com/user-attachments/assets/4a96c567-f7c2-4f66-8cb0-ccf2e52c9bd9)

**Comment by amaisonneuvedev** [comment]
HAHA, OMG.. sorry sir.. that would be it.. :(
