### ISSUE TITLE
Select SMTP provider at the campaign level 

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#2001]
I would prefer to choose SMTP provider at the campaign level, not at the setting level.

Now it's only possible to select "email", not a particular SMTP provider

On the other hand, it's possible to select among different "Messengers" (which are non-email channels like SMS)

![IMG_20240817_000829_046](https://github.com/user-attachments/assets/d24d1f79-3711-4e6d-a17f-3def7c7c181a)

**Comment by knadh** [comment]
This is being tracked here: https://github.com/knadh/listmonk/issues/1703
