### ISSUE TITLE
Community extensions docs page?

### ISSUE THREAD

**Issue by iloveitaly** [knadh/listmonk#2002]
**Is your feature request related to a problem? Please describe.**
Finding extensions or additions to the listmonk core product.

**Describe the solution you'd like**
I built a tool to generate a email newsletter based on a blog feed https://github.com/iloveitaly/listmonk-newsletter

I'd love others to use it. Wdyt about a docs page listing out this and other community plugins/additions?

**Comment by knadh** [comment]
Hi @iloveitaly. We could add it here: https://listmonk.app/docs/apis/sdks/
