### ISSUE TITLE
Undo import?

### ISSUE THREAD

**Issue by nrathi** [knadh/listmonk#2008]
Hi,

I imported my subscriber list. I accidentally left "Overwrite" turned on:

<img width="270" alt="image" src="https://github.com/user-attachments/assets/3a36efb5-4962-4d41-8473-13be9211b85b">

As a result, I lost my information about who was unsubscribed. Is there any way to get this back?

Thanks.

**Comment by nrathi** [comment]
I really feel like "Overwrite" should not be turned on by default :(

**Comment by nrathi** [comment]
I sent a campaign last month. Is there any way to reset based on who I sent it to (i.e., certain people were already unsubscribed) and who clicked unsubscribe from that campaign itself?

**Comment by nrathi** [comment]
Okay. I've realized there's nothing I can do. Please consider making the default less aggressive.

**Comment by MaximilianKohler** [comment]
Do you have a backup of your database?

**Comment by nrathi** [comment]
No, I never thought to do that.

**Comment by MaximilianKohler** [comment]
It's essential. Here are the commands: https://gist.github.com/MaximilianKohler/e5158fcfe6de80a9069926a67afcae11#backup

You should backup daily, and before making major changes. You may also want to download your backups to your PC once a week.
