### ISSUE TITLE
bulk import subscribers with API

### ISSUE THREAD

**Issue by makarov-ittx** [knadh/listmonk#201]
Are there any examples of using the api for  "POST | api/import/subscribers"  bulk import subscribers ?

**Comment by knadh** [comment]
You do a multi-post POST to `/api/import/subscribers` with two form fields, `params` and `file`:

- `params = {"mode": "subscribe", "delim": ",", "lists": [1,2], "overwrite": true}` (stringified JSON)
- `file = CSV file`

**Comment by tttp** [comment]
sorry to pile on a closed issue:

what is the requirement on the csv file? does it need a header line? 

do the various columns (email, name...) need a specific name?

is this possible to have custom fields?

**Comment by knadh** [comment]
If you go to `Subscribers -> Import` on the dashboard, it explains the structure. Yes, custom fields can be imported as JSON strings.
