### ISSUE TITLE
Merging attributes instead of overwriting them, when importing subscribers 

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#2010]
When importing subscribers, It would be nice to have the option to merge attributes instead of overwriting vs. not-overwriting them 

![Screenshot_2024-08-23-10-00-16-204_com android chrome-edit](https://github.com/user-attachments/assets/8ce5a2b4-ddec-42d8-93ba-ff5a447864e0)

For example, if I have `alice@alice.com` with attributes `{ 'hobbies': ['swimming','cooking']}`and then import again `alice@alice.com` with attributes `{ 'hobbies': ['dancing','gardening']}` , it would be nice to get `alice@alice.com` with attributes  `{ 'hobbies': ['swimming','cooking','dancing','gardening']}`

This would be in addition to the option of re-importing vs. skipping existing subscribers, mentioned in issue https://github.com/knadh/listmonk/issues/1883 (still unsolved)

**Comment by knadh** [comment]
Recursively merging arbitrary attributes in the database, the `hobbies[]` array for example, is unfortunately not technically feasible.
