### ISSUE TITLE
Customize the confirmation mail

### ISSUE THREAD

**Issue by sepiropht** [knadh/listmonk#2012]
I loooking for a way to customize the confirmation mail. I hope this is possible.

How can i set up the login ? In the conf i have 
```
 admin_username = "listmonk"
admin_password = "listmonk"
```
But when i  go to server:9000, the login button give access to the dashboard without  ask login/password

**Comment by Mangeshrex** [comment]
>I loooking for a way to customize the confirmation mail. I hope this is possible.

Customize which confirmation email ? 

>How can i set up the login ? In the conf i have 

Listmonk uses the default nginx basic_auth feature to setup the login. `admin_username` and `admin_password` are set to "listmonk" by default. Editing the text between the " " will setup the updated admin username and password. 

Also, it'd be really helpful, if you explain your issue even better.

**Comment by sepiropht** [comment]
My problem is solved thanks !
