### ISSUE TITLE
Uploading Media To Listmonk Questions

### ISSUE THREAD

**Issue by PackMeister** [knadh/listmonk#2015]
Need to use a dedicated image in a forthcoming campaign but am unable to upload it from my Listmonk 3.0 admin console.

The Media Uploads screen doesn't appear to have an option or field for me to select a local file for upload and the SAVE button is always greyed out.

<img width="1202" alt="Listmonk Media Upload Screenshot" src="https://github.com/user-attachments/assets/266dfaaa-842a-44f0-a28f-7ef8f1ce6549">

**Comment by knadh** [comment]
Please share a screenshot of Campaigns -> Media
