### ISSUE TITLE
Go template code in the subject line remains in the email head

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#2018]
**Version:**
 - listmonk: v3.0.0
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**
when i use Go template language in the subject line, the Go code remains in the email head section (while it prints normally in the subject line)

for most recipients, it's fine (this section is hidden), but for some of them the code appears

To see this bug, dowmload the .eml version of the email from the mail server:

<!doctype html>
<html>
<head>
    <title>{{ $r :=3D randInt 0 3}}{{if eq $r 0}} Subject Variant 1 {{else =
if eq $r 1}}Subject Variant 2{{ else}}Subject Variant 3{{end}} </title>

**Comment by knadh** [comment]
`{{ $r := randInt 0 3 }}{{ if eq $r 0 }} Subject Variant 1 {{ else if eq $r 1 }}Subject Variant 2{{ else }}Subject Variant 3{{end}}`

I tried this and send a test campaign to 2k dummy emails (locally on Mailhog) and was unable to reproduce this behaviour.

![image](https://github.com/user-attachments/assets/8972bdb2-8881-4e8d-a5d0-c63527d81087)

**Comment by benstaf** [comment]
I found the issue, t's because `Campaign.Subject` is in the default template:

![Screenshot_2024-09-03-20-11-54-106_com android chrome-edit](https://github.com/user-attachments/assets/2504ade3-3276-43a9-ad35-7eb5f5449add)

`Campaign.Subject` is in Go template language, not compiled

I deleted this and the problem disappeared
