### ISSUE TITLE
Installing on shared hosting

### ISSUE THREAD

**Issue by tobidwest** [knadh/listmonk#202]
Is there a way of installing Listmonk on shared hosting? I cannot run commands or use Docker. However, I do have ftp access to the server and can manually create databases and edit config files.

**Comment by jackdanielux** [comment]
You'll have to run ./listmonk to start this (after all manual activities
that you've done) as per my understanding.  Does your shared hosting allow
running scripts from command line?

**Comment by knadh** [comment]
> I cannot run commands or use Docker.

It wouldn't be possible I am afraid. You can get simple (and economic) VPS from DigitalOcean, AWS Lightsail etc. though.

**Comment by tobidwest** [comment]
> Too bad. But thank you for the quick response.


Can you recommend another list management tool with a nice UI similar to
yours?

**Comment by jackdanielux** [comment]
Not that I know of and I've explored plenty.  And that too for shared
hosting, really difficult.

**Comment by Donatzsky** [comment]
There are shared hosting companies where it's possible. You need to have full (non-root) SSH access, usually.
Opalstack, which I use, is a good example.
