### ISSUE TITLE
[Feature Request] Add "From" and "Email Headers" fields to transaction email templates in admin panel

### ISSUE THREAD

**Issue by ttphi88** [knadh/listmonk#2021]
**Feature Request**: Extend Transactional Email Template Configuration in Admin Panel

## Current Situation
Currently, the admin panel allows for the creation and management of email templates. [The Transactional API](https://listmonk.app/docs/apis/transactional/) allows setting "From" addresses and custom headers when sending emails. However, this requires the API client to manage these details.

## Proposed Change
Extend the email template functionality in the admin panel to include:
1. A field to set the default "From" address for each template
2. The ability to set custom "Email Headers" for each template
These template-specific settings would be used when sending transactional emails, but could still be overridden by the API if needed.
3. These new fields only show when the template type is "transactional", similar with the current "Subject" field

## Benefits
- Simplifies API client implementation: Clients only need to provide template ID, subscriber ID, and payload data.
- Centralizes email configuration: Admins can manage "From" addresses and headers directly in templates.
- Reduces the need for client-side updates when changing email settings.

## Implementation Notes
- This change will not remove the ability to set "From" and "Email Headers" via the Transaction API.
- If set in both the template and API call, the API values will take precedence.
- Template headers will be merged with the global SMTP headers config in the settings. (I guess this is already in place?)

## Next Steps
I'm interested in implementing this feature myself and submitting a PR. I'd appreciate feedback on this approach and any guidance on implementation details or potential concerns.

**Questions**
- Are there any foreseeable conflicts with existing functionality?
- Should there be any restrictions on what headers can be set in templates?

Your feedback is greatly appreciated. Thank you for considering this feature request!

**Comment by knadh** [comment]
Hi @ttphi88. While I understand that this makes using the API slightly more convenient by not having to send two fields, tying e-mail addresses (or other specific metadata) to generic templates, has little upside (apart from this minor added convenience).

Bringing this change about in the generic templates schema (currently same table for all kinds of templates) and tying transactional data to the template itself in addition to new UI elements + behaviour, I don't think makes sense.
