### ISSUE TITLE
Issue with Delayed Message Sending Intervals

### ISSUE THREAD

**Issue by simo25us** [knadh/listmonk#2029]
I've encountered a problem with my message-sending process. Despite setting up my system to send one message every minute or hour, all messages are still being sent out in one batch instead of at the specified intervals. I've adjusted the settings, but the issue persists.

Has anyone experienced this before? Any suggestions or solutions would be greatly appreciated!
Thanks in advance for your help.

**Comment by knadh** [comment]
How have you set this up? listmonk does not support sending messages continuously at intervals. A campaign can be scheduled to be sent at a particular time, but that’s it.

**Comment by simo25us** [comment]
Thank you for clarifying that. I initially thought Listmonk supported sending messages at specific intervals, but it seems I was mistaken.
