### ISSUE TITLE
Error while importing csv

### ISSUE THREAD

**Issue by yuriizinets** [knadh/listmonk#203]
Our listmonk instance was upgraded to 0.7.0
And from that moment, we have an error even for sample data.

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/17050536/95589501-1cf87c00-0a45-11eb-9c37-f08593d6596d.png">

Possibly related to that line
https://github.com/knadh/listmonk/blob/be9fbcd5425250c91eb344bb743496be4f71f0b3/internal/subimporter/importer.go#L270

**Comment by knadh** [comment]
This issue has been fixed https://github.com/knadh/listmonk/commit/d219f6549edcae50061a5a9ff8fee5894d752702 and will be available in the next binary release.

In the meanwhile, running the following manually on your DB will fix the issue:

`ALTER TABLE subscribers ALTER COLUMN status SET DEFAULT 'enabled';`
