### ISSUE TITLE
Since upgrading from 2.2.0 to 3.0.0 the "Lists" page only shows the first page (and there is no page loading indicator)

### ISSUE THREAD

**Issue by nkosi23** [knadh/listmonk#2030]
**Version:**
 - listmonk: v3.0.0
 - OS: FreeBSD
 -  Web Browser: Firefox 127.0.2

**Description of the bug and steps to reproduce:**
Since upgrading to v.3.0.0 earlier today, when navigating to the "Lists" page (the page listing the mailing lists) first of all the page appears to be empty but the data is actually being loaded behind the scenes (there is no loading indicator on this page). Then after a few seconds the first page of results appears, but the paging buttons have no effect and do not update load the data for the corresponding page.

Navigating to the page describing the subscribers of a specific list also has issues, it takes a long time to load and then the list is empty. However the problem only occurs if I click on the link present on the "Lists" page : if I instead use the shortcut for displaying the subscribers of a list that is present on the "Campaigns" page, the page loads without issue.

Apparently the upgrade process completed without error. :

```
2024/09/01 10:36:52 upgrade.go:72: running migration v2.3.0
2024/09/01 10:36:53 upgrade.go:72: running migration v2.4.0
2024/09/01 10:36:53 upgrade.go:72: running migration v2.5.0
2024/09/01 10:36:53 upgrade.go:72: running migration v3.0.0
2024/09/01 10:36:53 v3.0.0.go:13: IMPORTANT: this upgrade might take a while if you have a large database. Please be patient ...
2024/09/01 10:39:12 upgrade.go:87: upgrade complete

```

Actually, as I tested again just before submitting this issue, I got the page working, it looks like loading the lists takes a very long time to complete when paging, so the issue I see could be related to race conditions. The "Lists" section used to be snappy before the upgrade. 

There is definitely some wrong with the loading animations on this page because the loader does not appear when the Lists page is loaded, but does appear for a brief moment when paginating however the spinner disappears before the HTTP request actually completes, which is misleading. 

**Screenshots:**
N/A

**Comment by knadh** [comment]
> first of all the page appears to be empty but the data is actually being loaded behind the scenes (there is no loading indicator on this page)

The missing loading indicator has already been fixed in the current master branch and will be available in the next release. The time taken to load is indeed because of very large lists, for which, the query-caching feature is the right solution.
