### ISSUE TITLE
Night Mode - User Interface 

### ISSUE THREAD

**Issue by benstaf** [knadh/listmonk#2031]
I would like to have a Dark Mode, because the screen is too white

The ideal would be to have a Night/Day Switch

**Comment by knadh** [comment]
PRs for this are welcome if anyone is interested in picking up this task. I wouldn't have time to work on this personally.

**Comment by MaximilianKohler** [comment]
Related: https://github.com/knadh/listmonk/issues/429

The screenshots here https://github.com/knadh/listmonk/pull/438 look pretty nice, but it wasn't working fully for me.

I played around with the CSS under `Settings -> Appearance`, but I found it easier to just use the Dark Reader addon. https://darkreader.org/

I still use some CSS there though:

Admin:
```
.tag.list {
  color: rgb(23, 23, 23) !important;
  background-color: rgb(235, 198, 240) !important;

}

.tag:not(body) {
  font-size: 0.9em !important;
  color: rgb(0, 0, 0) !important;
}
```

Public:
```
body {
  background: #ddd;
}

.header {
  border-bottom: 1px solid #aaa;
  padding-bottom: 15px;
  margin-bottom: 30px;
}

.wrap {
  background: #d5d5d5;
  padding: 40px;
  box-shadow: 2px 2px 0 #aaa;
  border: 1px solid #aaa;
}

.button {
  background: #023582;
}

footer a {
  color: #7c7c7c;
}
footer a:hover {
  color: #111;
}

```
