### ISSUE TITLE
Next release timeline? Fixed bugs but no new release yet

### ISSUE THREAD

**Issue by MK-0x41** [knadh/listmonk#2037]
Hi Listmonk team,

First of all, thank you for the great work on this project! I've noticed that there are some bugs that have been fixed in recent commits, but there hasn't been a new release for a while.

Is there a timeline for the next release? It would be great to get an update, especially since the current master branch contains important fixes.

Thanks for your time and effort!

**Comment by knadh** [comment]
Please see this: https://github.com/knadh/listmonk/issues/543

The upcoming release a major one and all my estimates so far has been wrong, unfortunately. That said, it is done and is in the testing phase with a public RC release expected in the coming days. Final release will follow shortly.
