### ISSUE TITLE
How to send CC or BCC

### ISSUE THREAD

**Issue by Satishglk** [knadh/listmonk#2039]
How do we use listmonk to send a bcc of emails sent (to some archived folder)?.  Going through the issue log it appears like there is a feature /setting/header directive that can be used. Went through the documentation but couldn't see any mention of this.

Please can  someone provide me a simple example of how to accomplish this ?  (or if there is a way to save a copy of sent emails within listmonk)

Sincerely appreciate your help.

**Comment by knadh** [comment]
BCC headers do not work in the current version, but it has been fixed (https://github.com/knadh/listmonk/pull/1865) and will be available in the next version.

You can attach them by adding custom headers on the campaign UI (`+ Set custom headers`) on the campaign form. There, you can set any extra headers.

```
[
   "X-Custom-Header": "value",
   "BCC": "email@site.com"
]
```
