### ISSUE TITLE
Fix empty line breaks and Shift+Enter issue in the Quill richtext editor

### ISSUE THREAD

**Issue by knadh** [knadh/listmonk#204]
listmonk uses [Quill](https://github.com/quilljs/quill) as the WYSIWYG richtext editor on campaigns. It has two known issues that make editing painful.

1. Line breaks become `<p><br></p>` instead of an empty `<p></p>` causing double spacing.
2. The universal `Shift+Enter` (that inserts a `<br>` instead of a paragraph break `<p>`) doesn't work.

There are some hacks available and this has been heavily discussed on the Quill issues page, like [this one](https://github.com/quilljs/quill/issues/252).

The editor setup is in `frontend/src/components/Editor.vue`

**Comment by roshanjonah** [comment]
Not sure if Quill supports pasting HTML templates - that would great to have - like a button to paste or edit HTML source code because then we could paste our existing HTML templates from other providers directly in Listmonk

**Comment by knadh** [comment]
Sorry, missed this comment. Yes, Quill supports pasting HTML directly. However, listmonk only uses Quill for message composition. Templates are pasted as raw HTML separately.

**Comment by hfactor** [comment]
@knadh: Issue 1 can be solved, I think. https://stackoverflow.com/questions/43748108/how-to-keep-quill-from-inserting-blank-paragraphs-pbr-p-before-heading

**Comment by knadh** [comment]
@hfactor sorry, missed this comment. I'd tried out the suggestions on that post. Doesn't work.

**Comment by henk23** [comment]
Another chance for me to promote TinyMCE. :D I've been using it for years (mostly inside wordpress) and it's a charm to work with. Also, it has a builtin sourcecode view, so there would be no need anymore for a separate raw html view.

Would you be interested in a PR in that direction or is there something about TinyMCE that makes this a no-go?

**Comment by knadh** [comment]
@henk23 I'd evaluated TinyMCE but had refrained from using it as it (JS/CSS bundle) turned out to be far greater than the whole of listmonk combined. There were a couple other reasons that I unfortunately no longer recollect.

But now that Quill has been in production for a while, there is better clarity. Quill is indeed quite rudimentary to compared to what something like TinyMCE offers, and to an app like listmonk, a good WYSIWYG editor is important. We should evaluate TinyMCE as a potential replacement for Quill (with the app size tradeoff in mind).

I've opened a new issue here (https://github.com/knadh/listmonk/issues/467). If you're interested in sparing some time on this, that would be great.

**Comment by knadh** [comment]
Closing this issue as Quill has been [replaced](https://github.com/knadh/listmonk/issues/467) by TinyMCE.
