### ISSUE TITLE
test message work, campaign sending not (& broken pipe error)

### ISSUE THREAD

**Issue by 1000i100** [knadh/listmonk#2045]
**Version:**
 - listmonk: v3.0.0
 - OS: dockerised  "listmonk/listmonk:latest" on a ubuntu-server host

**Description of the bug and steps to reproduce:**
1. configure the server to send email with protonmail token
2. set quota very low : in smtp setting only 1 simulaneous connection and in speed settings (2nd tab) put everything to 1)
3. create a campaign, use the test email function to verify it send. (it send well)
4. launch te campagn (it get stuck and don't send anything)
5. send a new test-email (it still work so it's not a quota full problem)

Here is an extract of my logs  with `docker compose logs app` command : 
```
istmonk_app  | 2024/09/18 23:41:53 pipe.go:122: messages exceeded (1) for the window (1m0s since 18 Sep 24 23:41 +0200). Sleeping for 1m0s.
listmonk_app  | 2024/09/18 23:42:53 pipe.go:122: messages exceeded (1) for the window (1m0s since 18 Sep 24 23:42 +0200). Sleeping for 1m0s.
listmonk_app  | 2024/09/18 23:43:53 pipe.go:197: set campaign (Erratum Formulaire présence 40ans Millicent) to paused
listmonk_app  | 2024/09/19 01:35:43 manager.go:409: start processing campaign (Erratum Formulaire présence 40ans Millicent)
listmonk_app  | 2024/09/19 01:35:43 pipe.go:122: messages exceeded (1) for the window (1m0s since 19 Sep 24 01:35 +0200). Sleeping for 1m0s.
listmonk_app  | 2024/09/19 01:35:44 manager.go:485: error sending message in campaign Erratum Formulaire présence 40ans Millicent: subscriber 13: write tcp 172.28.0.3:51664->185.205.70.135:587: write: broken pipe
listmonk_app  | 2024/09/19 01:35:44 pipe.go:149: error count exceeded 1. pausing campaign Erratum Formulaire présence 40ans Millicent
listmonk_app  | 2024/09/19 01:36:43 pipe.go:122: messages exceeded (1) for the window (1m0s since 19 Sep 24 01:36 +0200). Sleeping for 1m0s.

```

**Comment by knadh** [comment]
> listmonk_app  | 2024/09/18 23:41:53 pipe.go:122: messages exceeded (1) for the window (1m0s since 18 Sep 24 23:41 +0200). Sleeping for 1m0s.

The error says that listmonk has been set to only send 1 message every 1 minute, after which, it waits for the next minute. Enabling the sliding window feature, is that intentional? 1 message per minute max doesn't seem valid.

**Comment by 1000i100** [comment]
Yes, it's intentional, to be sure i don't exceed any external sending quota, so if it don't send, it's not because external limit but because something in listmonk.
It should send a message every minute until there is no message left to deliver... and it don't (but test message (in smtp config and in campaign) are well sent.

**Comment by MaximilianKohler** [comment]
Google translate can't translate this:

>Erratum Formulaire présence 40ans Millicent

The other error you got is "broken pipe". Have you searched other issues for "broken pipe"?

**Comment by 1000i100** [comment]
i still have broken pipe error :/
```
listmonk_app  | 2024/09/20 03:22:48 manager.go:485: error sending message in campaign myCampaign: subscriber 130: write tcp 172.28.0.3:50408->176.119.200.135:587: write: broken pipe
```

**Comment by knadh** [comment]
`Broken pipe` is a network error. listmonk's TCP connection to the SMTP server outside is breaking for reasons outside of listmonk controls.

**Comment by 1000i100** [comment]
ok, it should be stable : it's a fiber connection with not main issue in other services, but what depend of listmonk is : after broken pipe, it don't repair the pipe (or replace it). My actual workaround is : when it don't continue, i check the log, if broken pipe, i go to setting and i change anything and save to force restarting, then it continues for a few sending, then it usually fail again.
