### ISSUE TITLE
Campaign Stat Limit

### ISSUE THREAD

**Issue by daway46** [knadh/listmonk#2046]
**Version:**
 - listmonk: 3.0
 - OS: Ubuntu

I have 111 subscribers in my list. When I ran the campaign, it only sent email to 100 out of 111. I checked with my audience and few did not get mail. There was no errors

Is there a campaign limit to 100? Don’t think so. Please guide me to right direction if anyone has raised this or am I doing anything wrong. 

![IMG_5917](https://github.com/user-attachments/assets/f163cb52-37c5-459a-a84f-69a220dccc39)

**Comment by knadh** [comment]
Do you have any blocklisted or unconfirmed double-opt-in subscribers in your list? There's a bug that we're currently investigating here: https://github.com/knadh/listmonk/issues/1931

**Comment by daway46** [comment]
None. I use single opt-in of now.

**Comment by MaximilianKohler** [comment]
Look at the list of subscribers. The campaign emails them in reverse order, starting from the last page. So check if there's anything unique about the subscriber it stopped at.

**Comment by daway46** [comment]
Thanks Max

I am bit confused. Lot of my subscribes shows UNCONFIRMED status as shown below

<img width="134" alt="image" src="https://github.com/user-attachments/assets/bbc74f8d-c172-43a8-b811-d9e639cb2ebc">

But it shows ENABLED for single-optin

<img width="110" alt="image" src="https://github.com/user-attachments/assets/ee9cfe1c-ab51-4796-8c20-3fd332b8330c">

**Comment by daway46** [comment]
ok I got the answer - based on below, it doesn't matter whether subscriber status is "unconfirmed" - they should all get mail 

<img width="110" alt="image" src="https://github.com/user-attachments/assets/81e46ca7-8001-4822-a451-95a8eed7309f">
