### ISSUE TITLE
Views and Clicks showing up in Stats but not in Analytics

### ISSUE THREAD

**Issue by aus70** [knadh/listmonk#2049]
**Version:**
 - listmonk: v3.0.0
 - OS: MacOS Ventura 13.6.9

**Description of the bug and steps to reproduce:**
I created a few test campaigns, viewed the emails, clicked on the tracked links.
Views and clicks show up in the campaign Stats, but not in the Analytics, where i see `Views (0)` and `Clicks (0)`.

Am I missing anything?
Thanks

**Comment by MaximilianKohler** [comment]
Like #1728 and #1795?

**Comment by aus70** [comment]
not quite:

With reference to #1728, in my case not only the percentage was missing, but the whole chart and, most importantly, the view and Clicks count was zero.

#1795 seems to be somewhat related to my case. I see now, after about 24 hours, that the charts and counts look good, so it might be an issue with the query that is run to extract the data used in the Analytics chart. Please note that changing the Analytics time window did not solve the problem.

Thanks!
