### ISSUE TITLE
Installing into Docker Swarm

### ISSUE THREAD

**Issue by Stainless5166** [knadh/listmonk#2051]
**Is your feature request related to a problem? Please describe.**
When deploying list monk as part of a docker compose file as a stack to a docker swarm, passing --install flag is not viable.
Documentation solutions do not address this issue, and the current install mechanism a bad fit for the idempotent intention of the docker stack context. 

**Describe the solution you'd like**

Possibly a config option of autoinstall. I know that giving a program the ability to automatically clobber data can be problematic, but useful for systems that run through the installation alot, like CI/CD Piplines.

Or host a webpage if a valid database is not available, with an installation button. Possibly could include an "Upload Backup" option?

Or a flag or config option that disables the prompt for user input, as currently, that exits when not connected to an interactive terminal session. So the program just sits and waits if not installed, with a log message of "No Valid Database Found" or something. This solution will keep a service from constantly restarting and allow an administrator to "Docker Exec" into a running container.

As I work though the installation I will comment with any other ways I have found to work with the current available options.

**Comment by knadh** [comment]
You can use the `--idempotent` flag. Please see: https://github.com/knadh/listmonk/issues/1887
