### ISSUE TITLE
Can't deploy listmonk to Azure Container App

### ISSUE THREAD

**Issue by j54j6** [knadh/listmonk#2056]
Hey, 

I am trying all day to deploy listmonk to azure but it fails alwys and I don't get any errors shown except for 
`
{"TimeStamp":"2024-09-28 19:27:12 \u002B0000 UTC","Type":"Warning","ContainerAppName":"listmonk-01","RevisionName":"listmonk-01--rev6","ReplicaName":"listmonk-01--rev6-<<id>>","Msg":"Container \u0027listmonk-01\u0027 was terminated with exit code \u0027\u0027 and reason \u0027ContainerCreateFailure\u0027. Create container failed with unexpected exception.","Reason":"ContainerTerminated","EventSource":"ContainerAppController","Count":7}

`

Thank you for the help, if anyone already deployed on azure I would be grateful for a short hint what I do wrong ^^

**Comment by knadh** [comment]
Please see this recent issue on how to --install and initialize silently on boot in container environments: https://github.com/knadh/listmonk/issues/2051

**Comment by j54j6** [comment]
@knadh  - thank you ^^ - I already solved it yesterday morning. In out case the problem was the "--yes" option for the first deployment. After figuiring out in my personal env. it was pretty simple in azure too ^^

Thank you for this great project

**Comment by knadh** [comment]
@j54j6 please include `--idempotent` as well, otherwise, every restart will wipe and reinstall the DB.
