### ISSUE TITLE
[FEATURE REQUEST] Change default value for overwrite and warn users before overwrite old subscriber data

### ISSUE THREAD

**Issue by SnejPro** [knadh/listmonk#2057]
**Is your feature request related to a problem? Please describe.**
- I accidently have overwritten old subscriber data and informations about unsubscribed emails are lost

**Describe the solution you'd like**
- "Overwrite?"-Button in import subscriber page should be deactivated by default
- Show a warning to the user that unsubscribed emails could be overwritten as subscribed and this could lead to GDPR violations because mails will be sent to users who already unsubscribed

**Comment by MaximilianKohler** [comment]
Since the damage is already done, your best bet is probably to send out an email to everyone apologizing that you accidentally overwrote their unsubscribed status, and ask them to unsubscribe again.

**Comment by SnejPro** [comment]
> Since the damage is already done, your best bet is probably to send out an email to everyone apologizing that you accidentally overwrote their unsubscribed status, and ask them to unsubscribe again.

Luckily i have a backup of the database.
But to prevent this in the future the "overwrite"-switch should be disabled by default and enabling it should warn the user about possible consequences.

**Comment by knadh** [comment]
This, if I recall correctly, has come up twice in the recent past. Good to address on the UI with a warning.
