### ISSUE TITLE
Markdown editor lacks syntax highlighting

### ISSUE THREAD

**Issue by olib14** [knadh/listmonk#2058]
Simply, the the _Markdown_ editor does not have syntax highlighting. The _Raw HTML_ editor already has it, and _Rich text_/_Plain text_ do not require it.

![image](https://github.com/user-attachments/assets/5b6b87e6-88ed-4f73-aa86-2aa780eece41)

The right window, KWrite, supports syntax highlighting for a variety of markdown features, such as raw HTML.

**Comment by olib14** [comment]
Additionally, it would be good if the editor supported breaking things whilst retaining indentation - this helps to structure the text and make editing more pleasant:

![image](https://github.com/user-attachments/assets/a411a8c0-b1b1-43ce-8fc9-0a8c75ce4b49)

The "Product" section is all a single line with one level of indentation (two spaces, as four denotes code blocks). In the current markdown editor, the text spills with no consideration for indentation.

This is also quite useful for bullet-point lists.

**Comment by knadh** [comment]
@Bowrna would you like to explore this? listmonk uses [@kazzkiq/CodeFlask](https://github.com/kazzkiq/CodeFlask) for HTML syntax highlighting. It has support form Markdown as well I think.

**Comment by Bowrna** [comment]
yes I will pick this one after raising PR for this https://github.com/knadh/listmonk/issues/1728
