### ISSUE TITLE
/api/tx sending old template after template update via api

### ISSUE THREAD

**Issue by roozbehk** [knadh/listmonk#2061]
**Version:**
 - listmonk: [eg: v3.0.0]

**Description of the bug and steps to reproduce:**
Template update via api PUT /api/templates/{template_id} works but Sending TX mail via /api/tx sends mail using old tx template 

reproduce: 
1. Create a transactional template via admin, update the subject of the template via PUT /api/templates/{template_id} and send mail via  /api/tx ; the email is sent using the old template. If I go back to admin panel and update the template and try sending via /api/tx; it works. the issue seems to be when you update the template via api.

**Comment by roozbehk** [comment]
So you know when the fix will be available?

**Comment by Bowrna** [comment]
can i look into this issue @knadh ?

**Comment by knadh** [comment]
@Bowrna thanks. Was a trivial fix https://github.com/knadh/listmonk/commit/58b13afa294e191767e229b1805c0ff2beb54566
