### ISSUE TITLE
Transactional send to multiple subscriber

### ISSUE THREAD

**Issue by Intrudr-Sec** [knadh/listmonk#2067]
Hi,

I want to use the transactional template to send to multi subscriber. If I test with 1 sub, it's work fine with this :
`curl -u "listmonk:listmonk" "http://10.0.0.3:9000/api/tx" -X POST \
-H 'Content-Type: application/json; charset=utf-8' \
--data-binary @- << EOF
{
    "subscriber_email": "test@test.com",
    "template_id": 5,
    "data": {"date": "2024-10-15"}
}

EOF
{"data":true}`

I have a script to verified the password expiration of our users and send email to them. If I export the list in json format, can listmonk handle the array ?

i try this, but not working :
`curl -u "listmonk:listmonk" "http://10.0.0.3:9000/api/tx" -X POST \
-H 'Content-Type: application/json; charset=utf-8' \
--data-binary @- << EOF
[
    {
        "subscriber_email": "test@test.com",
        "data": {"date": "2024-10-15"},
        "template_id": 5
    },
    {
        "subscriber_email": "test2@test.com",
        "data": {"date": "2024-11-15"},
        "template_id": 5
    },
    {
        "subscriber_email": "test3@test.com",
        "data": {"date": "2024-10-09"},
        "template_id": 5
    }
]

EOF
{"message":"Unmarshal type error: expected=models.TxMessage, got=array, field=, offset=1"}`

Any idea ?

Thanks

David

**Comment by knadh** [comment]
This is incorrect. Please see the docs: https://listmonk.app/docs/apis/transactional/

You can pass a list of subscriber IDs or e-mails in a single variable, eg: `{"subscriber_emails": ["a@a", "b@b"], template_id: 2 ...}`
