### ISSUE TITLE
Swagger Docs Error: GET /api/lists requires request body

### ISSUE THREAD

**Issue by Strehk** [knadh/listmonk#2077]
**Version:**
 - listmonk: v3.0.0
 - OS: N/A – Listmonk docs

**Description of the bug and steps to reproduce:**
In the swagger docs of the official listmonk documentation, the /api/lists endpoint requires a request body to be present, which is not allowed in get requests.

**Screenshots:**
![CleanShot 2024-10-08 at 13 30 08@2x](https://github.com/user-attachments/assets/fe6e918a-a382-45fd-885e-a7403d5eb1c3)

**Comment by valterpatrick** [comment]
How do I activate the API?

When I try to access https://listmonk.meusite.com.br/api, it returns 404

**Comment by TadeSF** [comment]
The API should always be enabled by default, you can get a list of all endpoints in the swagger documentation at https://listmonk.app/docs/swagger/

**Comment by knadh** [comment]
Hi @Strehk, would you be able to send a PR to fix the Swagger doc issues? I am not familiar with it.

**Comment by Strehk** [comment]
Usually the swagger docs are the result of some kind of code-generation process during build-time, often as a part of an API framework that supports swagger out of the box – but apparently it is quite out of date anyways: I just noticed the 1.0.0 tag at the top 😅

When you say you are not familiar with it – I take it someone contributed this part of the documentation? I am happy to look into how the swagger docs are generated and how they can be updated to 4.0.0

**Comment by Strehk** [comment]
After doing some very shallow digging in the Repo, it seems like the [collections.yaml](https://github.com/knadh/listmonk/blob/master/docs/swagger/collections.yaml), which is the basis for the swagger UI is in fact manually maintained ([see this PR](https://github.com/knadh/listmonk/pull/1253))

The Swagger UI itself is then built by [this workflow](https://github.com/knadh/listmonk/blob/master/.github/workflows/github-pages.yml)

I could try to update the collections.yaml, but I am not very experienced in Go, so it would take some time probably :)

How do you keep an overview over existing endpoints yourself @knadh? Or how did you provide the list of endpoints to the security testing service you just did for the 4.0.0 release? If you have some kind of list, it would make it much easier to get the full picture ;)
