### ISSUE TITLE
Missing List-Unsubscribe

### ISSUE THREAD

**Issue by bugsel** [knadh/listmonk#208]
Hello, I am using the latest version, I see this setting in the UI (Include `List-Unsubscribe` header - Enabled), but the header is missing in the email source code. (I do not add the UnsubscribeURL tag to the campaign content when I create it)

**Comment by bugsel** [comment]
And one more bug, a email with a field "From" containing unicode is not sent (for example, Russian characters)

`mail postfix/qmgr[348]: D3E8D13FCDC: from=<>, size=10077, nrcpt=1 (queue active)`

**Comment by knadh** [comment]
@bugsel, sorry, I missed this issue.

![image](https://user-images.githubusercontent.com/547147/97100700-37289000-16bc-11eb-83d5-293ca1895a84.png)
`List-Unsubscribe` works. Unable to reproduce this behaviour locally our in our production. Please note that test e-mails that you send out don't include the header, only actual campaigns do.

The Unicode encoding bug was fixed just a few days ago and will be available in the next release: https://github.com/knadh/listmonk/issues/34

**Comment by bugsel** [comment]
Yes you are right. I have tested having a header when sending test emails. When sending the newsletter, everything is fine!
