### ISSUE TITLE
Sending email newsletters on certain days of the week and hours...?

### ISSUE THREAD

**Issue by mkulgin** [knadh/listmonk#2088]
Is there an option to send email newsletters only on certain days of the week and hours? The specifics of our business is that we should not send on weekends, but only on weekdays. I would be very grateful for advice on how to implement this!

**Comment by MaximilianKohler** [comment]
You can schedule them for whenever you want.

**Comment by mkulgin** [comment]
Thanks, but apparently I didn't phrase the question well - we're not allowed to send mailings at night, only during weekday business hours. That is, we create a campaign and the emails go out only during the day on weekdays, until the whole campaign is over. The campaign does not work at night and on weekends.
