### ISSUE TITLE
resend to list where a connection timeout occurred. 

### ISSUE THREAD

**Issue by cb3inco** [knadh/listmonk#209]
I sent a campaign to a list of 889 users and only 875 were sent. How can I determine who didn't get it and resend it to them? This is the error I got. 

 error sending message in campaign _CAMPAIGN NAME_: 421 4.4.1 Connection timed out

I had concurrency at 4 and rate at 6

**Comment by cb3inco** [comment]
I think this can be disregarded. The number of users that are missing are ones that are blocklisted. I think this is what happened. Is there a way to confirm that?

**Comment by knadh** [comment]
Hm, you're right. The log lines don't include the subscriber ID with the error messages to cross check failures. This is trivial to add. Will push it in the next version.

**Comment by knadh** [comment]
Done https://github.com/knadh/listmonk/commit/a0b36bb01bda696dceb71253c1d717015ab24504.
