### ISSUE TITLE
listmonk never asks me for a password to log in

### ISSUE THREAD

**Issue by zarevskaya** [knadh/listmonk#2092]
**Version:**
 - listmonk: v3.0.0
 - OS: Debian 12 + Docker

Hello,

Maybe I didn't understand the principle, but all I have to do is click **Connect** to connect to listmonk. Authentication does not ask me for my credentials.

I added these lines in the config.toml:

admin_user = "password"
admin_password = "password"

These are not the real identifiers, the real ones don't have special characters or capital letters yet.

Have a nice day!

**Comment by knadh** [comment]
The key is `admin_username`, not `user`.

**Comment by zarevskaya** [comment]
Thanks, I just tested it, it does the same. Should the database be updated?

**Comment by knadh** [comment]
Please restart your browser once and try just to be sure that basicAuth creds aren't cached. The username/password are picked up directly from the config file in v3.0.0 and have no connection to the database.

If it's still not working, then the particular config file may not be the one that's being read.

**Comment by zarevskaya** [comment]
I added these lines under [app]
Solved. Thanks :)
