### ISSUE TITLE
Does not display email views and clicks (AWS SES)

### ISSUE THREAD

**Issue by valterpatrick** [knadh/listmonk#2093]
**Inglês (Google Translate):**
I enabled the webhook bounce option for AWS SES and added the endpoint "https://listmonk.meusite.com.br/webhooks/service/ses" to AWS SNS to receive webhooks, but the problem is that it is only displaying bounces.
The emails that were opened and clicked are not being displayed. I have already checked on CloudWatch and it is being recorded, in addition to sending the messages correctly via the webhook.

When I look at the logs, the following message appears:

2024/10/21 21:27:51 error processing SES notification: notification type is not bounce

I am using version 3.0 and I wanted to know if there is any way for the views and clicks to appear correctly in the analysis report?
In addition to being able to list the emails that were opened and clicked, of course?

**Português:**
Não exibe visualizações e cliques de emails (AWS SES)

Eu ativei a opção de webhook bounce para o SES da AWS e adicionei o endpoint "https://listmonk.meusite.com.br/webhooks/service/ses" no SNS da AWS para receber os webhook, problema é que só está exibindo rejeições.
Os emails abertos e clicados não estão exibindo. Eu já conferi no CloudWatch e está registrando, além de enviar as mensagens corretamente pelo webhook.

Quando eu olho nos logs apresenta a seguinte mensagem:

2024/10/21 21:27:51error processing SES notification: notification type is not bounce

Estou utilizando a versão 3.0 e queria saber se há alguma forma de as visualizações e cliques aparecerem corretamente no relatório de análise?
Além é claro de eu poder listar os e-mails que abriram e clicaram?

**Comment by knadh** [comment]
listmonk only supports bounce notifications from SES. It uses in-built mechanisms for view/click tracking. Please see https://listmonk.app/docs/templating/#functions

**Comment by valterpatrick** [comment]
Inglês (Google Translate):
I searched and couldn't get it to display views, clicks and opens.

Português:
Eu pesquisei e não consegui fazer ele exibir as visualizações, cliques e aberturas.
