### ISSUE TITLE
Open and click based sending

### ISSUE THREAD

**Issue by roshanjonah** [knadh/listmonk#210]
It would be awesome to have this simple feature of sending campaigns to subscribers that have opened a particular campaign or clicked a particular campaign via SQL expressions that are already there. 

This simple feature will enable some very advanced filtering and automation in the future because someone could easily build on this by interacting with API and database to create flows and all sorts of stuff but the very basis of it would remain quite simple. Is this possible to include in v0.8.0 release :)

Ps. I did read issue #193 but feel like this would be beneficial to certain users. When we allow customers to delete their data, I am assuming all relational attributions will be deleted as well so should be okay?

**Comment by knadh** [comment]
> It would be awesome to have this simple feature of sending campaigns to subscribers that have opened a particular campaign or clicked a particular campaign via SQL expressions that are already there.

This is easy:

```sql
subscribers.id IN (SELECT subscriber_id FROM campaign_views WHERE campaign_id=2)
```

> When we allow customers to delete their data, I am assuming all relational attributions will be deleted as well so should be okay?

That is correct.
