### ISSUE TITLE
Does `curl -u "username:password"` still work in `v4.0.0` ?

### ISSUE THREAD

**Issue by spammads** [knadh/listmonk#2106]
I keep getting `{"message":"invalid API credentials"}` when using the sample request from the docs with the correct login-credentials for my instance (just sanitized the following credentials):

```zsh
curl -u "username:password" 'http://localhost:9000/api/campaigns' -X POST -H 'Content-Type: application/json;charset=utf-8' --data-raw '{"name":"Test campaign","subject":"Hello, world","lists":[1],"from_email":"test <test@example.com>","content_type":"richtext","messenger":"email","type":"regular","tags":["test"],"template_id":1}'
```

**Comment by knadh** [comment]
It does until you remove the legacy username and password params from the TOML file. After that, you have to generate a new API key/secret from Admin > Users by creating a new API user.

**Comment by spammads** [comment]
Ah. Thanks. I already deleted the params from the config but missed to create the Api-User. Just tested it with a new Api-User and it works. Many thanks for this massive improvement!
