### ISSUE TITLE
Docker Upgrade Error

### ISSUE THREAD

**Issue by mrhll** [knadh/listmonk#2107]
**Version:**
 - listmonk: Latest
 - OS: Docker/Debian 12

Just followed the documentation to upgrade docker :
docker compose down app
docker compose pull
docker compose up app -d

There was a 500 Server Error and docker service keeps restarting forever.

**Comment by knadh** [comment]
You've to run the `--upgrade` [step](https://github.com/knadh/listmonk/releases/tag/v4.0.1) if you're using the old Docker compose file.

```shell
docker-compose down
docker-compose pull && docker-compose run --rm app ./listmonk --upgrade
docker-compose up -d app db
```

**Comment by mrhll** [comment]
That worked. Thank you !
Please mind updating the upgrade instructions as it was not clear enough.
