### ISSUE TITLE
Opt-in list requires user to click twice

### ISSUE THREAD

**Issue by jackdanielux** [knadh/listmonk#211]
Hi 

I was wondering if there is a setting which allows to send opt-in mails which result in opt-in action just by clicking once on the button in email?  the below screen grab is from the user's email, now if he clicks on confirm another url opens up where he has to click confirm again.  Question is how can he straight away confirm by clicking only once i.e. the link in the email.

![image](https://user-images.githubusercontent.com/71901268/97088391-1295cf00-164e-11eb-8d94-29417870bf6e.png)

**Comment by knadh** [comment]
I think it's a bit of a dark pattern to do that, however, if you really want to, you can add something like this to `/static/public/templates/optin.html`, and load your custom templates with [`--static-dir`](https://listmonk.app/docs/configuration/#customizing-public-templates).

```html
<script>
    document.getElementsByName("form")[0].submit();
</script>
```
