### ISSUE TITLE
/lists/NUM returns all lists rather than one by ID

### ISSUE THREAD

**Issue by mikeckennedy** [knadh/listmonk#2117]
**Version:**
 - listmonk: 4.0.1
 - OS: macOS

**Description of the bug and steps to reproduce:**

Doing a GET request against the URL: `https://servername/api/lists/5` returns JSON of this style:

```json
{
    "data": {
        "results": [
            {
                "id": 9,
                "uuid": "7a998..."
            },
            {
                "id": 8,
                "uuid": "a12603..."
            },
            {
                "id": 7,
                "uuid": "a12603..."
            },

            {
                "id": 6,
                "uuid": "a12603..."
            },
```

That is, all of the lists are returned when calling the endpoint at /lists/**NUM** (in this case I passed 5). It seems like something is wrong with the URL route here and it's being handled in the `/lists` route, not `/lists/{int}` route.

**Comment by mikeckennedy** [comment]
Hey @knadh this is the bug I mentioned when closing #2111.

**Comment by knadh** [comment]
Ouch, this was indeed a (tiny, but problematic) bug that crept through while building the new per-list permission system. I think I'll have to make a v4.0.2 release after waiting for the next couple of days in case any more reports come.

**Comment by mikeckennedy** [comment]
Perfect, thanks a bunch. It's not a massive issue for my library ( https://github.com/mikeckennedy/listmonk ) because I added some logic to pull the details from the list if it returns a list instead. But it is an issue with a broken API. Happy to have it fixed in the next release.

Thanks for the great app.
