### ISSUE TITLE
API token auth

### ISSUE THREAD

**Issue by rwrx** [knadh/listmonk#2122]
I have successfully upgraded to version 4.0.1. Unfortunately API calls with Basic Auth now does not work. I have generated API key in Listmonk dashboard, but unfortunately I cannot find anywhere how to send this token to API so, API calls currently does not work. I would like to ask for advice how to send token to API? Thank you.

**Comment by maxnoe** [comment]
From the code here:

https://github.com/knadh/listmonk/blob/be9fe9c7a2a9936c980364e571cb412b3af59a8d/internal/auth/auth.go#L355-L387

It seems like listmonk expects an `Authorization` header of the form:

```
Authorization: token <token>
```

**Comment by knadh** [comment]
API authentication supports both BasicAuth for backwards compatibility and bearer-style tokens.

```shell
$ curl -u "test:gQ3VKCNWjlbXRiBgZT8wIoKBRgN48gB6" localhost:9000/api/lists | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   420  100   420    0     0   9581      0 --:--:-- --:--:-- --:--:--  9767
{
  "data": {
    "results": [
      {
        "id": 1,
        "created_at": "2024-10-29T04:42:50.571167Z",
        "updated_at": "2024-10-29T04:42:50.571167Z",
        "uuid": "af6cef51-9d2b-4400-abb4-7c87c843b69e",
        "name": "Default list",
        "type": "private",
        "optin": "single",
        "tags": [
          "test"
        ],
        "description": "",
        "subscriber_count": 1,
        "subscriber_statuses": {
          "unconfirmed": 1
        },
        "subscription_created_at": null,
        "subscription_updated_at": null
      }
    ],
    "query": "",
    "total": 1,
    "per_page": 20,
    "page": 1
  }
}
```

What is happening when you are trying BasicAuth?

**Comment by maxnoe** [comment]
Any reason why you use `token:` and not `Bearer`?

**Comment by rwrx** [comment]
@knadh and @maxnoe thanks for your answers. When I am trying BasicAuth I am getting this error: `invalid API credentials`. I use the same username and password for BasicAuth as before upgrading to 4.0.1 version. Before upgrade it worked properly. So this is why I tried to use token instead of BasicAuth.

**Comment by knadh** [comment]
Ah, as the red warning on the dashboard would’ve said, you should create a new API user in Admin -> Users and use those credentials instead of your superadmin username and password.

**Comment by rwrx** [comment]
@knadh thank you, it helped. Now I am able to do api requests. Another issue emerged. Using this request, I need to delete only one subscriber matching email, but it will delete all subscribers:
`curl -u 'api:xxx' -X POST 'http://localhost:9000/api/subscribers/query/delete' --data-raw '"query=subscribers.email='\''test@example.com'\''"'`

**Comment by knadh** [comment]
I think this is because you aren't passing the `-H 'Content-Type: application/json'` header (as the query is raw JSON), essentially giving the backend an empty query which selects all records.

Either way, the backend should reject empty queries or malformatted request can accidentally delete all subs! I'll add this check.

**Comment by rwrx** [comment]
@knadh Thank you a lot. I have just copied this code from documentation: https://listmonk.app/docs/apis/subscribers/#post-apisubscribersquerydelete and changed server and credentials. So maybe documenation needs updating. Unfortunately by passing content type parameter did not helped. Now I am getting this error: `{"message":"Unmarshal type error: expected=main.subQueryReq, got=string, field=, offset=44"}`.

**Comment by knadh** [comment]
Ah, the docs had incorrect examples! Thanks for pointing it out. I've fixed it.

```shell
curl -u curl -u 'api_username:access_token' -X POST 'http://localhost:9000/api/subscribers/query/delete' \
-H 'Content-Type: application/json' \
--data-raw '{"query":"subscribers.name LIKE \'John Doe\'"}'
```

**Comment by rwrx** [comment]
@knadh thank you. Unfortunately, I am not very familiar with curl, but when I call this command, it just hangs and do nothing on the server side. I have also removed the first `curl -u` as it is there twice.

**Comment by rwrx** [comment]
@knadh I am sorry, I did not understand it correctly. I have implemented it as you advised to be in json format and deleting works properly. Thank you a lot for your help and a great software!
