### ISSUE TITLE
Issue with non-latin symbols in from field 

### ISSUE THREAD

**Issue by alehano** [knadh/listmonk#213]
If I set from field like: ```ВсеОтзывы.ру <noreply@vseotzyvy.ru>```
I can't receive mail on gmail.com, and receive mail with a bad header on another mail service:
```ВсеОтзывы.р =?UTF-8?q?=D1=83_```

Source mail:

```From: =?UTF-8?q?=D0=92=D1=81=D0=B5=D0=9E=D1=82=D0=B7=D1=8B=D0=B2=D1=8B.=D1=80?= =?UTF-8?q?=D1=83_<noreply@vseotzyvy.ru>?=```

**Comment by knadh** [comment]
This was recently fixed (https://github.com/knadh/listmonk/issues/340) and will be available in the upcoming release.
