### ISSUE TITLE
Option to make "all future emails" checked by default

### ISSUE THREAD

**Issue by MaximilianKohler** [knadh/listmonk#2130]
I think many people are not paying close attention when unsubscribing, and thus not bothering to click "all future emails". So when they unexpectedly get another email when I create a new list, they're more likely to mark it as spam.

**Context**:
I'm not running a typical newsletter, I'm responding to people who applied for something. I email around 2k per day and make a new list and campaign for each day. Sometimes I'll email everyone, and due to how spam filters work, it's recommended to slowly increase the number each day instead of emailing a million people all at once. 

So I have hundreds of "one-time use" lists. And when people click "unsubscribe" from one of my emails, they really mean "all future emails".

**Comment by knadh** [comment]
You can paste this in Settings -> Appearance -> [Public -> Custom Javascript].

```javascript
const chk = document.querySelector("#privacy-blocklist");
if (chk) { checked = true; }
```
