### ISSUE TITLE
Can't upgrade from v3.0.0 to v4.0.1

### ISSUE THREAD

**Issue by jlar0che** [knadh/listmonk#2132]
I am running Listmonk v3.0.0 in Docker basically using the instructions from [mariushosting](https://mariushosting.com/how-to-install-listmonk-on-your-synology-nas/). Before I perform any upgrades on my containers I shut them down, then copy the directory of the container placing it in a backup location (and labeling it with the version it was).

I tried following the instructions about upgrading from the github page for 4.0.1 but I think I'm missing something.

1. After SSHing into the appropriate hardware I cd into the directory there listmonk's docker-compose.yml is located
2. docker-compose down (or in my case, I fire up Portainer and shut down the Listmonk containers)
3. docker-compose pull && docker-compose run --rm app ./listmonk --upgrade
Here are my results:
![Untitled-1](https://github.com/user-attachments/assets/60f3ef69-2892-4c71-b14b-c18acd513624)

And, here is my (redacted) docker-compose.yml. Any detailed instructions on how to actually accomplish the upgrade would be very appreciated.

version: "3.9"
services:
  db:
    image: postgres
    container_name: Listmonk-DB
    hostname: listmonk-db
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: _####:###_
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "listmonk", "-U", "listmonkuser"]
      timeout: 10s
      interval: 5s
      retries: 6
    volumes:
      - /volume1/docker/cdc/listmonk/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: listmonk
      POSTGRES_USER: _listmonkuser_
      POSTGRES_PASSWORD: _listmonkpass_
    restart: on-failure:5

  listmonk:
    image: listmonk/listmonk:latest
    #command: [sh, -c, "yes | ./listmonk --install"] # only first startup ! or the db wipe every time
    container_name: Listmonk
    hostname: listmonk
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: _####:###_
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9000/
    ports:
      - 9192:9000
    volumes:
      - /volume1/docker/cdc/listmonk/uploads:/listmonk/uploads:rw
    environment:
      TZ: Europe/Belgrade
      LISTMONK_app__address: 0.0.0.0:9000
      LISTMONK_app__admin_username: _username_
      LISTMONK_app__admin_password: _password_
      LISTMONK_db__host: listmonk-db
      LISTMONK_db__port: 5432
      LISTMONK_db__user: _listmonkuser_
      LISTMONK_db__password: _listmonkpass_
      LISTMONK_db__database: listmonk
      LISTMONK_db__ssl_mode: disable
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy

**Comment by jlar0che** [comment]
It says:

[+] Running 2/2
 listmonk Pulled
 db Pulled
no such service: app

**Comment by knadh** [comment]
>  no such service: app

Your Docker compose file looks different from the sample provided in the repository. There's no service named "app" or "db" in your file. It seems to be named `container_name: Listmonk` instead.

Please use the names you've set in the compose file in the commands.

eg:
```
docker-compose pull && docker-compose run --rm Listmonk ./listmonk --upgrade
docker-compose up Listmonk
```

**Comment by jlar0che** [comment]
Ahh. I didn't realize that was referencing the Docker Container Name. Anyway, this was borked beyond recognition so I just ended up installing v4.0.1 from scratch and importing our one list.

We can close out this ticket.

Thanks for your assistance.
