### ISSUE TITLE
Resend Opt-In in case the subscription is requested again.

### ISSUE THREAD

**Issue by m42e** [knadh/listmonk#214]
If one registers and accidentally deletes the opt-in mail, he could not join with this E-Mail again.

With a timeout (about a hour/day/configureable) a resend, if the address is added twice would be nice.

**Comment by knadh** [comment]
This behaviour is fixed in `v0.9.0-beta` which was just released. Every time a user re-subscribes, if they haven't confirmed the opt-in, they'll receive another confirmation e-mail.
