### ISSUE TITLE
Redirecting to Old IP Address after Migration from Local VM to AWS

### ISSUE THREAD

**Issue by renangustavou** [knadh/listmonk#2141]
After migrating my setup from a local VM to AWS, I'm being redirected to the old IP address instead of the new public IP from AWS.

I updated the config.toml file, setting both site_url and public_url to http://AWSnewPublicIP:9000.
I verified the docker-compose.yml to ensure that the LISTMONK_app.site_url environment variable is configured correctly.
I edited the /etc/hosts file to remove any references to the old IP address.
Lastly, I cleared the cache after making all these changes and restarting the docker, but with no success. 

Has anyone else encountered this issue or have any suggestions on what I might try next?

**Comment by MaximilianKohler** [comment]
You left out your listmonk version. Per another recent duplicate issue, you have to change the `Root URL` in the listmonk settings.

**Comment by knadh** [comment]
If you are unable to change the root URL from the UI, you can do it directly by running this query.

`UPDATE settings SET value='"http://listmonk.yoursite.com"' WHERE key = 'app.root_url';`

**Comment by knadh** [comment]
The fix is merged and set to be release in v4.1.0 shortly.
