### ISSUE TITLE
Is it possible to send the more than 2k email using gmail

### ISSUE THREAD

**Issue by venkatoriga** [knadh/listmonk#2142]
Dear Team,

I need to send email campaigns through my Gmail account, but Gmail enforces a limit of 2,000 emails per day, which doesn't meet my requirements as I need to send a higher volume daily. I’m considering using Listmonk to handle the campaigns. However, I understand that Listmonk uses SMTP for email delivery, which may still be subject to Gmail's daily sending limits. Could you confirm if Listmonk can bypass this restriction or if there are alternative options within Listmonk or other SMTP providers to support higher daily email volumes? Any guidance on configuring Listmonk to handle larger campaigns would be greatly appreciated.

**Comment by knadh** [comment]
You can look at the "Performance" settings, particularly "Sliding window limit", here to see if those will help you with your scenario: https://demo.listmonk.app/admin/settings

**Comment by MaximilianKohler** [comment]
Most people use Amazon SES for this reason. You can check the "tutorials" section in the docs for more info.

Oracle Cloud Infrastructure (OCI) Email Delivery is a bit cheaper, but less well-known & used. https://www.oracle.com/application-development/email-delivery/

Slightly cheaper than Amazon SES. $0.085 per 1000 vs $0.1.

Guide https://blogs.oracle.com/cloud-infrastructure/post/step-by-step-instructions-to-send-email-with-oci-email-delivery
