### ISSUE TITLE
Possiblity of add grapesjs as newsletter editor

### ISSUE THREAD

**Issue by rwrx** [knadh/listmonk#2144]
I have seen these issues: https://github.com/knadh/listmonk/issues/820 and https://github.com/knadh/listmonk/issues/521 . But I am curious if it would be possible of implementing GrapeJS https://grapesjs.com as newsletter email editor for a bounty?

**Comment by sweetppro** [comment]
This was the default editor in a different newsletter app I used before finding ListMonk. I prefer the editor ListMonk currently uses. I found GrapeJS generated spaghetti markup which was a nightmare when I needed to customise the layout of my campaigns.

**Comment by rwrx** [comment]
@sweetppro thank you a lot for sharing your experience with GrapeJS.
@vividvilla that are great news. I am looking forward for this update for ListMonk.

**Comment by sweetppro** [comment]
I have no problem with more options. Just hoping that the current editor stays as an option :)

**Comment by mohamedamjad** [comment]
this would be a life changing update.
looking forward to test this update too. How can we access beta builds ?

**Comment by vividvilla** [comment]
@mohamedamjad you can build and test the `feat-visual-editor` branch locally:

- Clone this branch: https://github.com/knadh/listmonk/tree/feat-visual-editor
- Follow the [developer setup](https://listmonk.app/docs/developer-setup/) instructions
- Run `make build-frontend` to compile the frontend changes and email builder

@knadh and I conducted an initial review and identified several items that need addressing before we can proceed to beta. While I haven't been able to dedicate time to this over the past few weeks, I plan to resume work on this either this week or next to prepare for the beta release.

**Comment by odhiambo** [comment]
I have tried to test this. When I attempt to login to 127.0.0.1:8080, I end up with an "Invalid session" error on the browser. I will follow this discussion and perhaps await the beta.

**Comment by odhiambo** [comment]
@mohamedamjad did you try the beta build?

**Comment by odhiambo** [comment]
> I am working on [Email builder JS](https://usewaypoint.github.io/email-builder-js/#sample/welcome) integration and its almost [done](https://github.com/knadh/listmonk/tree/feat-visual-editor). In a week or two we should have a beta release out.

Is the BETA release out yet?

**Comment by HadrienKerlero** [comment]
> [@mohamedamjad](https://github.com/mohamedamjad) you can build and test the `feat-visual-editor` branch locally:
> 
> * Clone this branch: https://github.com/knadh/listmonk/tree/feat-visual-editor
> * Follow the [developer setup](https://listmonk.app/docs/developer-setup/) instructions
> * Run `make build-frontend` to compile the frontend changes and email builder
> 
> [@knadh](https://github.com/knadh) and I conducted an initial review and identified several items that need addressing before we can proceed to beta. While I haven't been able to dedicate time to this over the past few weeks, I plan to resume work on this either this week or next to prepare for the beta release.
> 
> Update: you also need to run DB migration.
> 
> ALTER TYPE content_type ADD VALUE 'visual';
> ALTER TYPE template_type ADD VALUE 'campaign_visual';
> ALTER TABLE templates ADD COLUMN body_source TEXT NULL;
> ALTER TABLE campaigns ADD COLUMN body_source TEXT NULL;
> 
> ALTER TABLE campaigns DROP CONSTRAINT IF EXISTS campaigns_template_id_fkey;
> ALTER TABLE campaigns
> ALTER COLUMN template_id DROP DEFAULT,
> ALTER COLUMN template_id SET DATA TYPE INTEGER,
> ALTER COLUMN template_id SET DEFAULT NULL;
> ALTER TABLE campaigns
> ADD CONSTRAINT campaigns_template_id_fkey
>   FOREIGN KEY (template_id)
>   REFERENCES templates(id)
>   ON DELETE SET NULL;
> 
> ALTER TABLE campaigns DROP CONSTRAINT IF EXISTS campaigns_archive_template_id_fkey;
> ALTER TABLE campaigns
> ALTER COLUMN archive_template_id DROP DEFAULT,
> ALTER COLUMN archive_template_id SET DATA TYPE INTEGER,
> ALTER COLUMN archive_template_id SET DEFAULT NULL;
> ALTER TABLE campaigns
> ADD CONSTRAINT campaigns_archive_template_id_fkey
>   FOREIGN KEY (archive_template_id)
>   REFERENCES templates(id)
>   ON DELETE SET NULL;

Hello :)

Do you have a DockerHub TAG where we could test this implémentation ?
