### ISSUE TITLE
OIDC corrupts itself as soon as the settings are saved again

### ISSUE THREAD

**Issue by KarlKeu00** [knadh/listmonk#2147]
**Version:**
 - listmonk: v4.0.1
 - OS: Docker

**Description of the bug and steps to reproduce:**
As soon as OIDC is set up and the settings are saved a second time, the client_secret in the database is replaced by the characters ••••••••••.

**Comment by knadh** [comment]
This is already fixed and merged and will be available in the upcoming patch release in the next couple of days. https://github.com/knadh/listmonk/pull/2116
