### ISSUE TITLE
Docker not using uploaded images properly

### ISSUE THREAD

**Issue by always-testing** [knadh/listmonk#2149]
Hi,

I tried to upload images. In my docker compose I have mapped thusly:

 volumes:
      - "./uploads:/listmonk/uploads:rw"

One of my uploaded images shows up like this when I click the Image icon in campaign editor. This image shows up in the emails.
blob:http://localhost:9000/7d567a27-57c2-47db-8a8e-548097806910

However another image shows like this
http://localhost:9000/uploads/logo_rfX4fO.png

This image is broken in the emails.

I am not sure how the first one shows as BLOB to be honest. I have no idea.

Please help.

The preview shows both images properly. Only when I received emails have this problem.

Apperciate your help. Thanks in advance.

**Comment by knadh** [comment]
> Only when I received emails have this problem.

You haven't configured the the root URL (Settings -> General). It's still referring to `localhost`, which obviously will only work locally when you're testing. The URL should point to a publicly accessible endpoint which you setup, like `listmonk.yoursite.com`
