### ISSUE TITLE
How to know which link got how many clicks?

### ISSUE THREAD

**Issue by jackdanielux** [knadh/listmonk#215]
I could not find any relevant documentation to know as to which link got how many clicks?  If the email contained only 1 link that we can know by link clicks of that campaign but for multiple clicks could not find any way around ?  Any suggestions pls?

**Comment by marcinkunert** [comment]
@jackdanielux I don't think there is such a feature build in currently into the UI ([it is planned!](https://github.com/knadh/listmonk/issues/319#issuecomment-820243576)), but the data are available in the database. Remember to enable `Individual subscriber tracking` in settings.

Queries:

```
select url, count(*) from link_clicks lc
join links l on l.id  = lc.link_id
where campaign_id = 5 -- enter yout campaing id
group by url;
```

If you want to avoid counting multiple clicks on the same link by the same user you could use:

```
select url, count(*)
from (
	select distinct url, campaign_id, subscriber_id from link_clicks lc
	join links l on l.id  = lc.link_id
	where campaign_id = 5 -- enter yout campaign id
) as subquery 
group by url;
```

**Comment by knadh** [comment]
This is feature is now merged: https://github.com/knadh/listmonk/issues/391
