### ISSUE TITLE
Docker images not working #2149 contd

### ISSUE THREAD

**Issue by always-testing** [knadh/listmonk#2152]
I'm not hosting it on a domain. I would like to run from localhost.

Is it possible to include the images in the content of the email rather than referring to them via a URL? This will be simple and solve my problem.

Or

Can I point an image on our website.. for eg: mysite.com/image1.png

Thanks in advance for the help

**Comment by knadh** [comment]
This isn't possible currently but the support will be added in a future version. Discussion here: https://github.com/knadh/listmonk/issues/2065
