### ISSUE TITLE
Can't update from 4.0.1 to 4.1.0 on Railway

### ISSUE THREAD

**Issue by JoshTristram** [knadh/listmonk#2156]
**Version:**
 - listmonk: 4.1.0
 - OS: Docker via Railway

**Description of the bug and steps to reproduce:**
Can't update to 4.1.0 on Railway due to the required "Y" input to "have you backed up your db" input. Can an extra flag "--y" be added to allow this input to be bypassed?

**Comment by knadh** [comment]
listmonk already has `--yes` for both `--install` and `--upgrade`
