### ISSUE TITLE
Can't authenticate Outlook SMTP Host

### ISSUE THREAD

**Issue by jun-netizen** [knadh/listmonk#2158]
Host: smtp-mail.outlook.com
Port: 587
Auth protocol: LOGIN
Username, Password: Outlook account username and password
TLS: STARTTLS

I sent test mail and the result is 
`535 5.7.139 Authentication unsuccessful, basic authentication is disabled. [BYAPR21CA0026.namprd21.prod.outlook.com 2024-11-14T16:41:11.391Z 08DD045B7D96603E]`

The authentication for outlook is OAuth2 and I found **Enable OIDC SSO** in **Security** tab.
I tried to make github OAuth provider Client ID and Secret but no change.
I'm confused about thing in **Security**.
BTW, what is **Messengers** and how can I use that?

**Comment by knadh** [comment]
OIDC SSO isn't for SMTP but user logins for the listmonk admin dashboard.

**Comment by jun-netizen** [comment]
Thanks for the answer.
But I'm still confused about using **Messengers**.
