### ISSUE TITLE
Listmonk unsubscribe URL issues 

### ISSUE THREAD

**Issue by RajuHarry** [knadh/listmonk#216]
I had done Setup with nginx 
reverse proxy http://xyz.com
Without reverse proxy I.e. xyz.com:9000
And with reverse proxy , SSL https://xyz.com
Above 3 scenarios tried with docker also .

Every time I have seen 'not found' json output.
Software UI is damn good and performance is good as well in terms data Post methods .

But it has lots of bugs .

In 7 alpha version if you click on lists and then click on Rocket button(start campaign shortcut) screen turns blank, and after refreshing GET based URL! it says not found .

Does anyone know what is the exact issue 
Especially when I had used 7 alpha 
Unsubscribe URL asks for Authentication 

I need to restart server, and listmonk to make unsubscribe URL to work properly as per expectation!

Everytime You need to restart server and listmonk to work with Unsubscribe URLS and with links.
@knadh 
Kindly Guide !

**Comment by knadh** [comment]
Looks like this issue is the same as https://github.com/knadh/listmonk/issues/216. Closing this to track on #216.

**Comment by RajuHarry** [comment]
How can You close it ? 
It's not resolved yet @knadh 
Where is the same issue it's my question thread

**Comment by RajuHarry** [comment]
> Looks like this issue is the same as #216. Closing this to track on #216.

Share me the reference 216 is created by me !

**Comment by RajuHarry** [comment]
![Uploading PSX_20201103_184111.jpg…]()

**Comment by knadh** [comment]
Sorry, I meant https://github.com/knadh/listmonk/issues/207.
