### ISSUE TITLE
AWS SES 535 Authentication Credentials Invalid

### ISSUE THREAD

**Issue by mnismi** [knadh/listmonk#2160]
**Version:**
 - listmonk: v4.1.0
 - OS: Linux/Docker

**Description of the bug and steps to reproduce:**
I tested the Keys in node js with nodemailer it works.

But in Listmonk the same credentials throws "**535 Authentication Credentials Invalid**" error.

And i tried other TLS and other matching ports.
Not sure where the problem is.

**Screenshots:**

![{C5F388FD-8813-4D0B-9EDD-EA8F1EE8C72D}](https://github.com/user-attachments/assets/7cde8425-39c8-4b61-99af-c525c8ef91fc)
![{A18406AE-83AD-450B-B8DA-C15F2937393E}](https://github.com/user-attachments/assets/bed91bdc-c914-43d9-8622-4d223818ecf4)

**Comment by mnismi** [comment]
Found the solution
A Normal user with necessary permissions does not work
You have to create a SMTP user

**Go to SES -> SMTP -> create credentials (creates new user).**
Here: https://github.com/knadh/listmonk/issues/1053

**Comment by kevinstylesx** [comment]
Thanks for this!
