### ISSUE TITLE
How to add the name to the email message

### ISSUE THREAD

**Issue by always-testing** [knadh/listmonk#2162]
I would like to personall address the user like:

Hello <Username>,

....

I tried Hello {{ .Name }},
I notice in the subscribers the column name is "Name" (case sensitivity noted).

Yet, when I preview, I get this error...

{"message":"Error rendering message: template: content:3:15: executing \"content\" at \u003c.Name\u003e: can't evaluate field Name in type *manager.CampaignMessage"}

**Comment by knadh** [comment]
It's .Subscriber.Name

Please refer to the template documentation.

**Comment by always-testing** [comment]
Sorry, I missed it in the doc. Thank you.
