### ISSUE TITLE
OpenApi Body Content Missmatch on Sub-Import

### ISSUE THREAD

**Issue by dylancetin** [knadh/listmonk#2163]
**Version:**
 - listmonk: [ v4.0.0]
 - OS: [-]

**Description of the bug and steps to reproduce:**
Miss match OpenApi specs on /import/subscribers POST 

Current OpenApi spec is:
```yaml
  /import/subscribers:
    ...
    post:
      description: handles the uploading and bulk importing of a ZIP file of one or more CSV files.
      operationId: importSubscribers
      tags:
        - Import
      requestBody:
        description: uploads and bulk imports of compressed CSV files
        content:
          application/json:
            schema:
              type: object
              properties:
                params:
                  type: string
                file:
                  type: string
      ...
```

But as far as I am aware, body should be "multipart/form-data" or "application/x-www-form-urlencoded" to be able to transmit files. I have a copy of the yaml that I modified like below. And I am using this modified yaml to generate typescript clients. 

I would love to dive in the Go code, but I am not familiar. I will be guessing this is a bug.

```yaml
  /import/subscribers:
    ...
    post:
      description: handles the uploading and bulk importing of a ZIP file of one or more CSV files.
      operationId: importSubscribers
      tags:
        - Import
      requestBody:
        description: uploads and bulk imports of compressed CSV files
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                params:
                  type: string
                  description: JSON string containing import parameters
                file:
                  type: string
                  format: binary
      ...
```

**Comment by dylancetin** [comment]
Something similar exists in "/lists" GET. OpenApi says search query string should be in the body json. But it only works when I add it on to URL params.

**Comment by dylancetin** [comment]
Similar things mentioned in #2077

**Comment by knadh** [comment]
Hi @dylancetin. Would you be able to send a PR fixing the YML spec?

**Comment by dylancetin** [comment]
@knadh opened one
