### ISSUE TITLE
Confirmation Email

### ISSUE THREAD

**Issue by amaisonneuvedev** [knadh/listmonk#2166]
**Version:**
 - listmonk: v4.1.0
 - OS: Upgraded Docker on Ubuntu

**Description of the bug and steps to reproduce:**
I have just updated to the latest listmonk, thank you for the many updates, so excited.

Subscribing using the exciting form from prior to upgrade, works great and the email is captured in the 3 mailing lists as expected. 
User receives the Confirm your subscription email, as excepted

The links in the confirmation email navigates to the website on the listmonk open ports but times out. 

https://XXX.com:9000/subscription/optin/b71d271d-655b-40da-a1a7-7dc97f6f32fb?l=d994e5da-495b-4f62-9822-801d678b03fc&l=2e50442a-00f9-42a4-a6d8-c66f5b4ef2e9&l=2c6d7c06-8e0b-46fa-8364-85be610353c0

in the listmonk settings, the domain is set to my https://XXX.com:9000 domain, and the port it open. Just a browser timeout. this worked fine prior to the upgrade.  

No errors in the log, 
**Screenshots:**

**Comment by amaisonneuvedev** [comment]
just to add to this, the all subscription form is now working either?

https://xxx.com:9000/subscription/form

**Comment by knadh** [comment]
You're supposed to setup a reverse proxy like Caddy or Nginx in front of listmonk and not expose port :9000 to the internet directly. In the same manner as hosting any serverside web app.
