### ISSUE TITLE
Cannot delete all subscribers and cannot edit blocked email

### ISSUE THREAD

**Issue by EdisAganovic** [knadh/listmonk#2167]
**Version:**
- v4.1.0 (0a27de1 2024-11-12T18:42:26Z, linux/amd64)
- Dockerized version from original docker-compose.yml

**Description of the bug and steps to reproduce:**
1. Editing blocked contact to correct wrong email, throws error: Error updating Subscriber: pq: duplicate key value violates unique constraint "subscribers_email_key". Key (email)=(xxx@hotmail.com) already exists.
2. Deleting all subscribers, throws error: Invalid fields: query

**Video:**
https://youtu.be/kAS3rx5Y89M

**Comment by aman400** [comment]
Facing a similar issue

**Comment by EdisAganovic** [comment]
@knadh Yes you are right about duplicate. That's my mistake.

Now 2nd problems we need to solve.

**Comment by knadh** [comment]
Fixed in https://github.com/knadh/listmonk/commit/7bfbd6a856123ebd2bb067f9195c3e29660dc764

**Comment by swarnk** [comment]
Hi! Can you tell me in which stable version this commit is planned to be included https://github.com/knadh/listmonk/commit/7bfbd6a856123ebd2bb067f9195c3e29660dc764

Also Is it possible to correctly delete all subscribers bypassing the web interface? How to do it correctly in the psql console?

Thank you!
