### ISSUE TITLE
error loading SQL queries

### ISSUE THREAD

**Issue by mzch** [knadh/listmonk#217]
I tried `./listmonk --install`, then got an error as below:

```
2020/11/03 23:01:46 install.go:51: error loading SQL queries: Error preparing query 'next-campaign-subscribers': pq: SELECT DISTINCT ONの式はORDER BY式の先頭に一致しなければなりません
```

How to fix this isse?

- PostgreSQL: 13.0

**Comment by mzch** [comment]
It seems to fix the following patch...Is this OK?

```diff
--- queries.sql.orig	2020-11-03 23:18:22.232822949 -0800
+++ queries.sql	2020-11-03 23:16:28.301465010 -0800
@@ -537,7 +537,7 @@
     WHERE subscriber_lists.status != 'unsubscribed' AND
     id > (SELECT last_subscriber_id FROM camps) AND
     id <= (SELECT max_subscriber_id FROM camps)
-    ORDER BY id LIMIT $2
+    ORDER BY uniq_id LIMIT $2
 ),
 u AS (
     UPDATE campaigns
```

**Comment by knadh** [comment]
The query works on Postgres 12. Have to test if this is an issue with Postgres 13 before considering a patch.

Could you translate what the Kanji characters in the error says? I'm guessing that's because your Postgres locale is different?

**Comment by mzch** [comment]
It means `SELECT DISTINCT ON expression must match the beginning of the ORDER BY expression`.

**Comment by jackdanielux** [comment]
Postgres 13 has this error, I switched to 12 and this error does not occur
there.

**Comment by knadh** [comment]
Ah, thanks @jackdanielux. @mzch I'll test whether the patch works on 12 and 13 and them commit.

**Comment by knadh** [comment]
@mzch the patch works on Postgres 13 but fails on 12 with the same error. Investigating this.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/684c64ced14742455b6f9da186d2fd07f5af6ce4 fixes this for Postgres 13.
