### ISSUE TITLE
function gen_salt does not exist when upgrade

### ISSUE THREAD

**Issue by Etheonor** [knadh/listmonk#2171]
**Version:**
 - listmonk: upgrade from 3.0 to 4.1
 - OS: Docker install

**Description of the bug and steps to reproduce:**

When trying to upgrade my local installation from 3.0 to 4.1, I have this error : 

2024/11/19 09:06:59.631694 upgrade.go:76: error running migration v4.0.0: pq: function gen_salt(unknown) does not exist

The thing is, I definitely have the pg_crypto installed on my DB... I tried to install it again with _CREATE EXTENSION pgcrypto;_ but have this log: _ERROR:  extension "pgcrypto" already exists_ 

I installed listmonk in a specific schema, so I think it could be the issue and the function gen_salt should be in fact public.gen_salt. Is there a workaround?

Thank you

**Comment by knadh** [comment]
Can yo try `ALTER EXTENSION pgcrypto SET SCHEMA your schema`?

**Comment by Etheonor** [comment]
Well, it was that easy. Thank you very much, it works now :)
