### ISSUE TITLE
smtp "from" not respecting the from field configured 

### ISSUE THREAD

**Issue by vmichel-ephe** [knadh/listmonk#2172]
**Version:**
 - listmonk: v4.0.1 & v4.1.0
 - OS: debian 12

**Description of the bug and steps to reproduce:**
We are running listmonk with a opensmtpd sender.

with those settings : 
from : noreply@$DOMAIN
return-path : bounces.listmonk@$COMPANY.onmicrosoft.com

When we tried version 3.0.0, mail were sent to the mail server with a sender as configured : 
```
smtp envelope evpid=484a94911c5b0330 from=<noreply@$DOMAIN> to=<vmichel@$DOMAIN>
```

after update to 4.0.1 and 4.1.0, this field is set to the address set in the return path : 
```
smtp envelope evpid=ae1933c1e35e6ba2 from=<bounces.listmonk@$COMPANY.onmicrosoft.com> to=<vmichel@$DOMAIN>
```
those logs are extracted directly from the sending mail server.

The from header stay correct, as is the displayed sender.
This switch put us out of the DKIM signing, the SPF check and put us right in the spam.

I cant find any other issue referencing this behavior, and no point in the changelog.
Is this the expected behavior ?
why is the return path used as the sender address ?

**Comment by knadh** [comment]
Is this related? https://github.com/knadh/listmonk/issues/908
