### ISSUE TITLE
ListMonk allows me to disable the default smtp and throws an error while saving. Why not throw the error at disable event itself?

### ISSUE THREAD

**Issue by mrajasekar-dev** [knadh/listmonk#2173]
**Version:**
 - listmonk: v4.1.0 (0a27de1 2024-11-12T18:42:26Z, linux/amd64)
 - OS: MacOS Sequoia (Version 15.1)

**Description of the bug and steps to reproduce:**

- ListMonk allows me to disable the default smtp connection which is the only connection while setting up and then throws an error while saving.
- Instead why not throw the error during the disabling event only?

**Screenshots:**
![image](https://github.com/user-attachments/assets/9ccfeb56-704a-462e-9645-8ad325656bc8)

**Comment by knadh** [comment]
It's possible to add multiple SMTP servers and enable/disable/add/remove them in any order before one finalises the decision and hits Save. Throwing an error when clicking around wouldn't be ideal.
