### ISSUE TITLE
Allow Users to Unsubscribe from Newsletter via Website

### ISSUE THREAD

**Issue by xelayz** [knadh/listmonk#2180]
I am using Listmonk and I would like users to be able to unsubscribe from our newsletter directly through our website. Currently, if users delete the newsletter emails containing the unsubscribe link from their email inbox, they can no longer easily unsubscribe. Therefore, I want to implement a feature where users can enter their email address on our website and receive an email with a link to unsubscribe.

Upon reviewing the Listmonk documentation, I suspect this functionality might not be possible. Using the API, I can only work with the subscriber ID, which I do not have when the user only provides their email address on the website. It's possible to retrieve all subscribers and then match the entered email address to find the ID, but this would be inefficient and cumbersome as the number of subscribers grows.

My question is: Am I overlooking something, or is there truly no way for users to unsubscribe if they delete all newsletter emails and lose access to the embedded links? Any guidance or solutions would be greatly appreciated. Thank you!

**Comment by knadh** [comment]
There isn't an out-of-the-box UI for this now.

> Using the API, I can only work with the subscriber ID ...

Please refer to: https://listmonk.app/docs/apis/subscribers/#example-request

You can retrieve subscribers by e-mail:

```shell
curl -u 'api_username:access_token' -X GET 'http://localhost:9000/api/subscribers' \
    --url-query "query=subscribers.email = 'user@email.com'"
```
