### ISSUE TITLE
Feature request: Addition to the API schema to Create/Delete/List API keys

### ISSUE THREAD

**Issue by wildernessfamily** [knadh/listmonk#2195]
**Is your feature request related to a problem? Please describe.**
I use CloudFlare secrets and AWS secret manager for almost all my secrets. I was setting up CloudFlare KV and Workers to rotate my ListMonk API keys. However, in the API schema I didn't see any way to generate, list, create, API keys through ListMonk's API.  I thought I would just put it out there to see if anyone else would be interested in this and possibly request a future update to the API schema.

For now, I have the API locked down through CloudFlare Zero Trust Application's auth keys. For now, I'm just having CloudFlare KV/Workers rotate the Zero Trust Application auth keys. As someone that is very security conscience, I would like to take it one level deeper.

Thank you to all the developers/contributors for your hard work and time on developing ListMonk. Very much appreciated!

**Comment by knadh** [comment]
These already exist. Just realised that they haven't been added to the docs.

Although less than idea, for now, you can inspect the requests using the browser network inspector on the user add/edit/delete pages and copy that schema in your API requests. If you're able to perhaps send a PR documenting that in the API section, that would be very helpful! Thank you.

**Comment by wildernessfamily** [comment]
Hi, I didn't even check the network inspector. I should have thought of that first prior to opening this issue. I have a little time today. I will see if I can add those to the docs and do a PR.  Thanks again for the info.
