### ISSUE TITLE
can  we use same database for 2 docker 

### ISSUE THREAD

**Issue by shelu16** [knadh/listmonk#2197]
can  we use the same database for 2 docker  like i have already list monk in docker but I want to create another docker with different mail and port

**Comment by knadh** [comment]
You can create a second database inside the Postgres Docker container manually (CREATE DATABASE ...) and then connect to it.

**Comment by shelu16** [comment]
no  i means i have 1 docker is running site1.com and I want to use site1.com database in site2.com docker

**Comment by knadh** [comment]
Ah no. Only one listmonk instance should be connected to a database.

**Comment by shelu16** [comment]
ok
