### ISSUE TITLE
Feature Request: Support for Automated Email Sequences (Campaign Workflows)

### ISSUE THREAD

**Issue by Tanjohnson99** [knadh/listmonk#2198]
# **Feature Request: Support for Automated Email Sequences (Campaign Workflows)**

## **Description**
We would like to request the implementation of a feature to support **automated email sequences** (also known as campaign workflows) in **Listmonk**. This feature would allow users to configure and manage multi-step campaigns, where subsequent emails are sent based on predefined delays or recipient actions, such as email opens or link clicks.

---

## **Why This Feature is Important**
Automated email sequences are essential for many businesses aiming to engage their audience effectively. Currently, Listmonk excels as a high-performance platform for sending campaigns, but lacks this advanced automation feature. Adding this functionality would:

- Make Listmonk competitive with other platforms like Emelia or Mailchimp.
- Help businesses nurture leads and improve customer engagement without relying on external automation tools.
- Streamline workflows for users, saving time and reducing manual effort.

---

## **Example Use Case**
1. **Day 0:** Send a welcome email to new subscribers.
2. **Day 3:** Follow up with a reminder email if no action is taken.
3. **Day 7:** Send a final email offering a special incentive.

---

### **Core Features**
- Users can define a sequence of emails to be sent in order.
- Timing can be set based on:
  - Fixed delays (e.g., "Send 3 days after the previous email").
  - Recipient actions (e.g., "Send if the user opens the first email").
- A visual interface for managing workflows, allowing users to:
  - Add or remove steps.
  - Adjust timing or trigger conditions.

### **Technical Suggestions**
- **Database Changes:**
  - Introduce a `workflows` table to store sequence data (e.g., email templates, delays, triggers).
- **Backend Logic:**
  - A scheduler or worker process to manage email sends at the right times.
- **Frontend:**
  - Add a "Workflow" tab or section in the campaign creation interface.
- **API Extensions:**
  - Support retrieving, creating, updating, and deleting workflows.

---

## **Possible Implementation Ideas**
If development time is limited, a phased approach could work:

1. **Phase 1:** Allow users to define sequences with fixed delays (e.g., 3 days, 7 days).
2. **Phase 2:** Add support for recipient-triggered actions (e.g., opens or clicks).
3. **Phase 3:** Enhance the UI for a more visual, drag-and-drop workflow builder.

---

## **Conclusion**
This feature would significantly enhance Listmonk's usability and appeal, especially for businesses looking for a comprehensive solution for their email marketing needs.

We understand that implementing such a feature may require significant effort and resources, but we believe it would provide substantial value to the community. 

Thank you for considering this request! We are happy to provide more details or assist with testing if needed.

**Comment by knadh** [comment]
Hi @Tanjohnson99. This level of automation is not planned for listmonk. A tool like Mautic may be better suited for your requirements.
