### ISSUE TITLE
Campaign URL issue | Asks for Login after clicking on Unsubscribe URL

### ISSUE THREAD

**Issue by RajuHarry** [knadh/listmonk#220]
![screenshot-scuberestaurants com-2020 11 06-21_55_11](https://user-images.githubusercontent.com/19948885/98390467-673c3f80-207b-11eb-8e5d-9268e709a37f.png)
![screenshot-scuberestaurants com-2020 11 06-21_54_51](https://user-images.githubusercontent.com/19948885/98390474-6acfc680-207b-11eb-8208-22f6ccb8939d.png)

1) Issue with URL : https://xyz.com/campaign/new?list_id=6

Screen turn blank after clicking on Rocket Icon

Does Anyone know what is the issue or how to resolve it with 7 alpha binary version ?

Server is Nginx

@knadh Kindly guide.

2) Also How to Continuously keep running Listmonk
or Restart The app .
3) After generating unsubscribe URL
After starting campaign URL prints Json : not Found. and before that asks for login!
 
What is Wrong with this ?

<!doctype html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
        <base target="_blank">

        <style>
            body {
                background-color: #F0F1F3;
                font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, sans-serif;
                font-size: 15px;
                line-height: 26px;
                margin: 0;
                color: #444;
            }
            .wrap {
                background-color: #fff;
                padding: 30px;
                max-width: 525px;
                margin: 0 auto;
                border-radius: 5px;
            }
            .button {
                background: #7f2aff;
                border-radius: 3px;
                text-decoration: none !important;
                color: #fff !important;
                font-weight: bold;
                padding: 10px 30px;
                display: inline-block;
            }
            .button:hover {
                background: #111;
            }
            .footer {
                text-align: center;
                font-size: 12px;
                color: #888;
            }
                .footer a {
                    color: #888;
                }
            .gutter {
                padding: 30px;
            }
            img {
                max-width: 100%;
            }
            a {
                color: #7f2aff;
            }
                a:hover {
                    color: #111;
                }
            @media screen and (max-width: 600px) {
                .wrap {
                    max-width: auto;
                }
                .gutter {
                    padding: 10px;
                }
            }
        </style>
    </head>
<body style="background-color: #F0F1F3;font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, sans-serif;font-size: 15px;line-height: 26px;margin: 0;color: #444;">
    <div class="gutter" style="padding: 30px;">&nbsp;</div>
    <div class="wrap" style="background-color: #fff;padding: 30px;max-width: 525px;margin: 0 auto;border-radius: 5px;">
        {{ template "content" . }}
    </div>
    
    <div class="footer" style="text-align: center;font-size: 12px;color: #888;">
        <p>Don't want to receive these e-mails? <a href="{{UnsubscribeURL}}" style="color: #888;">Unsubscribe</a></p>
        <p>Powered by <a href="https://listmonk.app" target="_blank" style="color: #888;">The Amazing Listmonk</a></p>
    </div>
    <div class="gutter" style="padding: 30px;">&nbsp;{{TrackView}}</div>
</body>
</html>

**Comment by knadh** [comment]
> Screen turn blank after clicking on Rocket Icon

This is not a known issue that I've encountered or anyone else reported. If you're seeing a blank screen, it means the frontend Javascript app's breaking somehow. Can you see if there are any errors logged on the browser's developer console?

> Also How to Continuously keep running Listmonk

listmonk is a server service. You can run it as a daemon using Docker, or run it as a system service with something like systemd. What operating system are you using?

**Comment by RajuHarry** [comment]
@knadh 
Thank you For Your reply.

There is no errror in Browser Developer Console.
But When I refreshed the page it shows below mentioned json
{"message":"Not Found"}

After Clicking on Rocket Button from "Lists section" below mentioned URL pattern replaces in browser URL.
URL Structure  : https://domainxyz.com/campaign/new?list_id=1

Its quite strange . This issue is not there in Old Versions of Listmonks.
it is in Binary version of 7 Alpha.

and also
After generating unsubscribe URL
After starting campaign URL prints Json : not Found. 
{"message":"Not Found"}
and before that asks for login!
URLS starts working Magically after 5-6 minutes.

**Undeniably This Software is good but latest version (7 Alpha) has issues.**

I have used below mentioned Method for installation

1) Downloaded the latest release and extract the listmonk binary.
2) ./listmonk --new-config to generate config.toml. Then, edited the file.
3) ./listmonk --install 
4) Run ./listmonk 

**For Reverse Proxy used Nginx Server**

**Comment by knadh** [comment]
Co-incidentally, I was just able to reproduce this issue on a DigitalOcean instance (but surprisingly, nowhere else including our production setup). I'm investigating the issue. Closing this to instead track it on the original report here: https://github.com/knadh/listmonk/issues/207#issuecomment-723560155

**Comment by RajuHarry** [comment]
@knadh 

First of all Thanks A lot For Amazing New Release (Beta Release).
Tried Full Fresh Install Everything works As per Expectation only The Part that I had Highlighted earlier is Not working For Sure.

**mdi mdi-rocket-launch-outline**

URLS Structure : http://xyz.com:9000/campaign/new?list_id=2

![screenshot-15 206 211 123_9000-2020 11 11-20_48_25](https://user-images.githubusercontent.com/19948885/98829846-b0b3d280-245f-11eb-83bf-2eff2b52da77.png)


![screenshot-15 206 211 123_9000-2020 11 11-20_50_45](https://user-images.githubusercontent.com/19948885/98829832-ab568800-245f-11eb-866f-f001206d04bc.png)

![screenshot-15 206 211 123_9000-2020 11 11-20_51_45](https://user-images.githubusercontent.com/19948885/98829880-bc9f9480-245f-11eb-8d82-adefaf8fbd7e.png)

**Lists Sections**

**After Refreshing Page it shows {"message":"Not Found"}**

Tried With Digital ocean 18x Ubuntu and AWS 18x Ubuntu as well

PostgreSQL 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu,
There is no Nginx
Kindly guide.

**Comment by knadh** [comment]
Will investigate this. In the meanwhile, you don't need to use that button to start a campaign. You can just go to `Campaigns -> Create New`.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/ce108c8487369a4af22654027ea0e6b48e804a96 fixes this.

**Comment by RajuHarry** [comment]
@knadh 

It's great contribution to the system !!
It really , has a great performance !
Thank you means a lot !
