### ISSUE TITLE
Messengers list has blank values

### ISSUE THREAD

**Issue by hank** [knadh/listmonk#2207]
**Version:**
 - listmonk: v4.1.0
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**
I have 2 messengers configured but both appear as blank in the dropdown for the campaign.

**Screenshots:**
![image](https://github.com/user-attachments/assets/6986a089-5efb-42e4-a50b-1720281eae1a)
![image](https://github.com/user-attachments/assets/094d73b2-8359-4b02-a245-43d768ba0bd7)

**Comment by hank** [comment]
I hacked the HTML in the browser to add the right option attribute and it worked, but that's pretty ghetto.

**Comment by knadh** [comment]
Hi @hank. This was fixed last week and will be available in the next release: https://github.com/knadh/listmonk/pull/2187

**Comment by hank** [comment]
Thanks!
