### ISSUE TITLE
EOF error in smtp connection

### ISSUE THREAD

**Issue by mehdichitforoosh** [knadh/listmonk#221]
Hi.
The connection to zoho smtp server takes a long time for sending test message and eventually gives an EOF error message.
It gives the same error on the [Mailu.io](https://mailu.io) smtp server.
[Zoho smtp configuration](https://www.zoho.com/mail/help/zoho-smtp.html)
Environment: Docker
Docker image: listmonk/listmonk:latest
Thank you.

![Screenshot from 2020-11-09 21-00-29](https://user-images.githubusercontent.com/9556642/98577053-9d263180-22d0-11eb-9bf6-87cdd74a18e9.png)

![Screenshot from 2020-11-09 21-07-03](https://user-images.githubusercontent.com/9556642/98577079-ac0ce400-22d0-11eb-852f-ec943a486d83.png)

**Comment by mehdichitforoosh** [comment]
Log:
2020/11/09 17:33:56 init.go:454: reloading on signal ...
2020/11/09 17:33:56 init.go:429: HTTP server shut down
2020/11/09 17:33:56 main.go:64: v0.7.0-alpha (0f055ea 2020-08-09T14:44:45Z)
2020/11/09 17:33:56 init.go:91: reading config: config.toml
2020/11/09 17:33:56 init.go:167: connecting to db: pgsql-db-site-01:5432/listmonk
2020/11/09 17:33:57 init.go:360: media upload provider: filesystem
2020/11/09 17:33:58 init.go:318: loaded SMTP: info@rondoit.com@smtppro.zoho.com
⇨ http server started on [::]:9000

**Comment by mehdichitforoosh** [comment]
Please tell me,
How to set the log level?
Thanks.

**Comment by knadh** [comment]
EOF indicates a broken connection. Have you tried connecting to the SMTP server directly from the server?

`telnet smtp.zoho 587`?

**Comment by mehdichitforoosh** [comment]
$ telnet smtppro.zoho.com 465
Trying 176.9.122.179...
Connected to smtppro.zoho.com.
Escape character is '^]'.

**Comment by mehdichitforoosh** [comment]
$ telnet smtppro.zoho.com 587
Trying 176.9.122.179...
telnet: connect to address 176.9.122.179: Connection refused
Trying 176.31.102.224...
telnet: connect to address 176.31.102.224: Connection refused
Trying 176.9.122.183...
telnet: connect to address 176.9.122.183: Connection refused

**Comment by knadh** [comment]
Looks like 587 is not reachable. Can you check your firewall settings? The [Zoho docs](https://www.zoho.com/mail/help/zoho-smtp.html) say that 587 works with the TLS setting on. You can see if 465 works with TLS on/off in setings.

**Comment by mehdichitforoosh** [comment]
I tried on 465 , TLS Off, gives an EOF error message.
Ok I check with TLS On and comment the result.

**Comment by mehdichitforoosh** [comment]
On 465 with TLS On gives an EOF error.too.
![Screenshot from 2020-11-10 20-46-11](https://user-images.githubusercontent.com/9556642/98707986-e5f3ee00-2395-11eb-8fec-c6b20356d082.png)
![Screenshot from 2020-11-10 20-49-24](https://user-images.githubusercontent.com/9556642/98708272-3b2fff80-2396-11eb-8c0f-bbd331edf2d4.png)

**Comment by mehdichitforoosh** [comment]
@knadh 
I set Auth protocol to plain.is this correct?

**Comment by knadh** [comment]
Not sure what auth protocol Zoho uses. You should unblock 587 in your firewall and try it with TLS on.

**Comment by mehdichitforoosh** [comment]
Ok. I'll check.

**Comment by mehdichitforoosh** [comment]
Do I need to install a service like [Postfix](http://www.postfix.org/) mail server?

**Comment by mehdichitforoosh** [comment]
I think the documentation needs to be completed.
It is confusing in some cases.

**Comment by knadh** [comment]
You needn't run your own local Postfix. listmonk works with any SMTP server. The Zoho one, there seems to be some sort of a network issue that's preventing listmonk from connecting, not an issue with listmonk's SMTP lib. Can you try other SMTP servers (eg: Gmail, Sendgrid, SES etc.)

If you want to run your own locally, I recommend [Postal](https://postal.atech.media/). Far easier to install and use than Postfix.

**Comment by mehdichitforoosh** [comment]
Ok.I 'll check other SMTP servers and will comment the result.

**Comment by mehdichitforoosh** [comment]
@knadh 
I connected to gmail SMTP server!

$ telnet smtp.gmail.com 587
Trying 173.194.76.109...
Connected to smtp.gmail.com.
Escape character is '^]'.
220 smtp.gmail.com ESMTP n15sm1402170wrq.48 - gsmtp

What do you suggest to solve the problem of connecting to the Zoho server??
My business domain is on Zoho mail.
Thank you.

**Comment by knadh** [comment]
I'm not sure what's happening with Zoho. Seems like a network/firewall issue. You should try and debug it outside of listmonk. Something [like this](https://blog.mailtrap.io/how-to-test-smtp-server/) may help.
