### ISSUE TITLE
Correct way to send message to part of the users

### ISSUE THREAD

**Issue by Gijsen** [knadh/listmonk#2210]
Hi team,

I want to deploy this for the following situation:
have one list for all users that paid the membership. To everyone I want to send out the information about events etc.

We do about 10 events / year and I want to send out the information a couple days prior to that event.

Should I create a list for every event? How to avoid the opt in options? As the preconfirm option is greyed out with me if I try to add a user to a list.

Since we do a lot of these events, in summer about every 2 weeks one , i do not want to keep on sending mails that people are opted in. these lists also only are valid for one campaign. 
However I cannot re-use them because multiple inscriptions are open at the same time.

**Comment by zxsa89675** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the code to add a new list type 'event' and disable opt-in requirements for event lists. This will allow easier management of event-based communications without requiring opt-in for each event.

You can review changes in this commit: https://github.com/zxsa89675/knadh-listmonk-2210/commit/78eff7764aeae0b00b8f359b1dbfda3ee979d85d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Gijsen** [comment]
Hi,

Does this send a notification to the user every time?
Which is wat i want to avoid. The user already receives a order
confirmation from is.

Op ma 16 dec 2024, 17:23 schreef Kailash Nadh ***@***.***>:

**Comment by knadh** [comment]
No notifications are sent in single-optin lists.
