### ISSUE TITLE
GET /api/lists returns only one list after update

### ISSUE THREAD

**Issue by PLangowski** [knadh/listmonk#2222]
**Version:**
 - listmonk: 4.1.0
 - OS: Fedora 40

**Description of the bug and steps to reproduce:**
When calling the `GET /api/lists ` endpoint, it only returns one list.
```
 curl -u "<username>:<token>" -X GET "https://.../api/lists"
```

When I call `GET /api/public/lists`, all public lists are returned correctly.

**Comment by knadh** [comment]
The API user that you created should either have `lists:get_all`, `lists:manage_all` permissions, or have per-list permission assigned to all the lists you want to access.

**Comment by PLangowski** [comment]
Thanks, this fixed the issue.
