### ISSUE TITLE
Why POST /api/subscribers needs to be authenticated?

### ISSUE THREAD

**Issue by mehdichitforoosh** [knadh/listmonk#223]
Hi.
I think the /api/subscribers on POST method should be allowed to access without authentication.
I want to call the POST api directly from subscription form!!

**Comment by knadh** [comment]
All `/api/*` endpoints are for internal use. There is a public end point with limited fields for registering subscriptions, which also works with HTML forms. Check out the `Subscribers -> Forms` menu.

**Comment by mehdichitforoosh** [comment]
Thank you.
Good luck.
