### ISSUE TITLE
Managing SMTP errors

### ISSUE THREAD

**Issue by phylor** [knadh/listmonk#224]
First of all, thank you for the effort on this project. It looks awesome!

I tried to use listmonk to send a company internal newsletter. Obviously, I did not change the performance settings and my SMTP server quickly rate-limited the sending. A lot of emails then failed to send (I see their subscriber IDs in the logs).

Am I correct that listmonk does not store which emails failed to send? And there is currently no way to resend them? If not, are there any plans for such features?

Thanks in advance!

**Comment by knadh** [comment]
Thanks @phylor.

> Am I correct that listmonk does not store which emails failed to send? And there is currently no way to resend them? If not, are there any plans for such features?

That's correct. For now, they're just app logs. Reconciliation and resumption are planned features.
