### ISSUE TITLE
Feature/Question: Run campains based on a query

### ISSUE THREAD

**Issue by jcalfee** [knadh/listmonk#229]
We have a number of lists based on two variables: Country and Cause

Is there a way to use `attribs` to query for the target subscribers automatically for each campaign run?  I want to set this up in a way that other users will not need to re-enter the query and update members again.  I'm adding users from an external API, so simply setting the variables Country and Cause in `attribs` when I post/add a new subscriber would be ideal.

Alternatively I could use lists.  However there are some complications using lists:

1. We have 2 variables which would lead to a compounding number of lists
2. I could auto-create the lists in the API.  However, the list API mostly works on list_id, so my concern is that the external sever calling your API will have to query all the lists each time to get IDs and discover and add missing lists.
3. POST /api/subscribers requires list ids (no option to list names)
4. There is no unique constraint on the list name so I would not be able to simply try and add a list just in-case it does not already exists.  If there were a unique constraint and the API failed and returned the list ID this would be a more reasonable option.

![image](https://user-images.githubusercontent.com/204121/100250446-4bea8480-2f03-11eb-9f63-810acbc00b54.png)

**Comment by jcalfee** [comment]
Lists are really not idea .. New lists can show up anytime (someone from a new Country signs up to an existing Cause for example) and then the lists in the campaign may then go out of date.  The query is ideal, it would pick up the case where they want to campaign everyone on a given Cause and other case where they want to campaign only English speaking countries for a given Cause.

**Comment by knadh** [comment]
Any number of lists can be added to a campaign. Overlapping subscribers will only get a single copy of the campaign message, so that isn't an issue.

There is a plan to create ephemeral query-based lists that are created and automatically thrown away after a campaign is finished, but that isn't supported right now.

**Comment by jcalfee** [comment]
Ephemeral query-based lists sound great.  Any plans to let the campaign define multiple lists using either the AND or OR conditions (instead of just a default OR)?  That might be easier in the mean time.  That would help keep the number of lists minimal.

**Comment by knadh** [comment]
Adding `AND` to list selections to campaigns wouldn't be natural and will require significant changes to the list management logic. Segmentation logic is already external to list selection, so it makes sense to extend that to ephemeral lists. Can't give an ETA, but it's definitely on the list!

**Comment by jcalfee** [comment]
Interesting .. Thank you!
