### ISSUE TITLE
Unable to add users to multiple lists with form.

### ISSUE THREAD

**Issue by LukasSchulz** [knadh/listmonk#232]
When a users adds himself to a list via the form, it all works as expected. Even if using a form with multiple lists to subscribe to.
But when the same user, using the same email address then tries to add himself to the other list using the form, the error "The e-mail already exists." appears.

It isn't surprising, because, yes, the email exists - but on a different list.

A fix would maybe be to check whether the user is already subscribed to all the lists and if he isn't to then automatically subscribe him to all the "missing" lists - and only if he is already subscribed to all the lists, to throw the error.

**Comment by knadh** [comment]
I remember this being raised in another issue. I agree. For public forms, it doesn't make sense to reject the input. Will push a patch for this.

**Comment by knadh** [comment]
Done https://github.com/knadh/listmonk/commit/dd0c124b0e0cad7f032606e4605bdefa6a70279d. Will be available in the upcoming release.
