### ISSUE TITLE
Unable to get listmonk up and running

### ISSUE THREAD

**Issue by Kolskidman** [knadh/listmonk#233]
I've been trying to get listmonk to work for the past two weeks now but it keeps failing to run or open on my web browser once I'm done with the installation running the first command take forever to load and once it completed it just won't work. I need someone to help me out as I'm a complete nood at this

**Comment by knadh** [comment]
Can you share a screenshot of what you see when you run `./listmonk` after installation?

**Comment by Kolskidman** [comment]
Like you asked I've attached the screenshot of the screen when I'm done running the installation script and also when I accessed my website but to cut the story short would you pls either maybe give me a more beginner-friendly guide to follow beginner-friendly to someone that only knows about the existence of dockers only when I encountered it in your tutorial or I would greatly appreciate it if I can just give you either my Facebook username or WhatsApp number and we connect over that. Then you helped me install it over a TeamViewer session. Either way, I would really appreciate your help see me through this installation. Looking forward to hearing from you.
![WhatsApp Image 2020-12-06 at 1 01 14 PM (1)](https://user-images.githubusercontent.com/50783314/101272033-7b32a880-37c3-11eb-89c4-5e28a4a790d7.jpeg)
![WhatsApp Image 2020-12-06 at 1 01 14 PM](https://user-images.githubusercontent.com/50783314/101272035-7cfc6c00-37c3-11eb-8b1c-e46df23a3e9a.jpeg)

**Comment by knadh** [comment]
Looks like listmonk is starting correctly on port `9000` but your server's firewall may not be configured to expose port 9000. From the screenshot, it looks like you are using Google Cloud. You'll have to read up on how to open ports on Google Cloud docs.

Alternatively, you can try port 80 which might be open by default. Edit config.toml and change the address to `0.0.0.0:80` and visit your IP without any port component in the browser.

**Comment by jackdanielux** [comment]
As @knadh pointed out - your firewall is blocking port 9000 access.  Just disable firewall and see if the same issue persists.  If you're just testing since the screengrab just shows an IP, you might as well use port 80 since that's open by default.

**Comment by Kolskidman** [comment]
I'm very grateful for the great assistance provided to me. And thanks for helping me getting somewhere. I've been able to install it on digitalocean and I think that doesn't put in place some stupid firewall rules as I'm able to access the application. But I don't seem to be getting the login credentials correctly as I've tried both the admin:test combinations in your docs all to no avail. So I would need you to help me with the default login credentials and attached to this email is a screenshot of my screen after I'm done installing it on digitalocean
![Uploading WhatsApp Image 2020-12-06 at 8.54.28 PM.jpeg…]()

**Comment by knadh** [comment]
The username and password are generated in the `config.toml` file. You can just edit the values there.

**Comment by Kolskidman** [comment]
Thanks for that info. As i mentioned I'm completely new to this. So would you mind giving me the path to the config.toml file and how best I can edit it so as for me not to break anything. I'm very grateful for your timely response

**Comment by jackdanielux** [comment]
It's in the root directory.

In case you're on DO, cd directory of listmonk
Sudo nano config.toml and then copy the credentials.

**Comment by Kolskidman** [comment]
Thanks for helping me out. I'm happy to tell you that I've now been able to get listmonk up and running. Thanks for helping me out as I won't be able to do it without you
