### ISSUE TITLE
The Logo URL / Alt Text in Email Body are Problematic

### ISSUE THREAD

**Issue by jackdanielux** [knadh/listmonk#234]
Hi

Sorry for the long pause, was occupied with some other setup :)

I'm running listmonk in prod now, below 2 are hygiene issues, that are affecting deliverability/open rates:

1. The root url (path of the software) is getting tagged as the hyperlink of the logo (so my actual blog is on domain.com whereas I am running a separate instance on domain.in for listmonk >> domain.in is the link which gets opened when someone clicks on the logo of the email body (logo has been inserted using the logo option in UI of listmonk dashboard)

2. The alt-text of the logo is listmonk :), while I'm absolutely fine with the footer being powered by listmonk for this amazing piece of software, the alt-text is something of a bummer.  The problem is specifically when email clients don't display images by default so that only thing they are able to see instead of the logo is hyperlinked version of text "listmonk" with the link pointing to my listmonk installation URL

Any chance to put these two in the UI as well?

**Comment by knadh** [comment]
Hi @jackdanielux 
1) The `Logo URL` option in Settings can be any URL. It does not have to be listmonk's domain.
2) You don't even have to use the `{{ LogoURL }}` tag in the template. You can just add any custom HTML by editing the template in `Campaigns -> Templates`

**Comment by jackdanielux** [comment]
Hi Knadh/Listmonk

The opt in template is the one that's giving problems.  Rest of them we can
edit as we need.

In the Opt in template the logo is fetched auto using the path that we
specify and the alt-text to that logo is "listmonk"

Plus the hyperlink to that logo is by default of listmonk root URL so no
option to edit that as well.

**Comment by knadh** [comment]
Ah yes, got it. I'll fix that in the next release. In the meanwhile, you can tweak the [optin/unsub templates too](https://listmonk.app/docs/configuration/#customizing-public-templates).
