### ISSUE TITLE
API for sending a campaign to subscribers

### ISSUE THREAD

**Issue by mahmoudmy** [knadh/listmonk#235]
I need to send a campaign to one or many subscribers by calling API. Is it possible?

**Comment by mehdichitforoosh** [comment]
I need this API,too.

**Comment by knadh** [comment]
You can create a list and add subscribers to it using the [subscriber APIs](https://listmonk.app/docs/apis/subscribers/), and then create a campaign, attach the list to it, and send it using the [campaign APIs](https://listmonk.app/docs/apis/campaigns/).

**Comment by mahmoudmy** [comment]
Thasnk for your quick response.
Which endpoint in campaign APIs is for sending?

GET | /api/campaigns | Gets all campaigns.
-- | -- | --
GET | /api/campaigns/:campaign_id | Gets a single campaign.
GET | /api/campaigns/:campaign_id/preview | Gets the HTML preview of a campaign body.
GET | /api/campaigns/running/stats | Gets the stats of a given set of campaigns.
POST | /api/campaigns/:campaign_id/test | Posts campaign message to arbitrary subscribers for testing.
POST | /api/campaigns | Creates a new campaign.
PUT | /api/campaigns/:campaign_id | Modifies a campaign.
PUT | /api/campaigns/:campaign_id/status | Modifies a campaign status.

**Comment by knadh** [comment]
`PUT /api/campaigns/:campaign_id/status` with `status=running` will start a campaign.

**Comment by mahmoudmy** [comment]
Is there any way to send emails without using campaigns?

**Comment by knadh** [comment]
Not currently. There is a plan to explore transactional messaging, but nothing definitive yet.
