### ISSUE TITLE
Plain text message part

### ISSUE THREAD

**Issue by eglimi** [knadh/listmonk#236]
I saw that #80 added a plain text body by automatically converting the HTML message to plain text. However, in my case, this doesn't look great, see the screenshot below. The E-Mail is created using MJML and the screenshot shows the preview line from the Fastmail Web-Interface.

![image](https://user-images.githubusercontent.com/169826/101400668-88d65400-38d1-11eb-9d56-2fa3716f487c.png)

It would be great to have a way to specify the plain text part of the message separately. One reason is the rendering issue mentioned before, the other reason is that the plain text message is not necessarily always the same as the HTML version, at least in my E-Mails.

Thanks for working on listmonk :)

**Comment by knadh** [comment]
The lib usually does a good job at converting HTML to plain text and I've tested it to render fine on Gmail and Thunderbird with complex HTML e-mails including MJML ones. It makes sense to have explicit control over this though. I'm adding this to the next release milestone.

**Comment by knadh** [comment]
This is done https://github.com/knadh/listmonk/commit/68afd61024f13cce800fe076df500347b1291752 and will be available in the upcoming release (~next week).

![image](https://user-images.githubusercontent.com/547147/106357487-5888c000-632c-11eb-9f09-f0ec321f6cdd.png)

**Comment by MaximilianKohler** [comment]
@knadh what do you think about adding the ability to preview the plain text version?
