### ISSUE TITLE
SQL queries in API calls don't work

### ISSUE THREAD

**Issue by kamilryszkowski** [knadh/listmonk#238]
I am trying to use the API call described [here](https://listmonk.app/docs/apis/subscribers/#get-apisubscribers_1).

Unfortunately, adding `-d "query=...` to my calls does nothing. The same data gets returned as if the `query=...` param was not even there, in both cases the output is the first 30 results (page 1) out of my entire subscriber list.

Here is my curl call without `query=...`:
```
curl -u [USER]:[PASSWORD] -X GET 'http://[API_URL]:9000/api/subscribers'
```

And with:
```
curl -u [USER]:[PASSWORD] -X GET 'http://[API_URL]:9000/api/subscribers' -d "query=subscribers.email = 'kamil+2@bearable.app'"
```

Using the exact same SQL query to filter in listmonk's UI works correctly, so the issue is either me making the wrong API calls or the API not working properly. Help & clarification would be greatly appreciated :)

**Comment by knadh** [comment]
I'm guessing the second `=` in the `query=` param isn't getting URL encoded.

**Comment by ramsrib** [comment]
Even using urlencode still returns unexpected results:

```
curl -u username:passsword -X GET 'http://localhost:9000/api/subscribers' --data-urlencode  "query=subscribers.email = 'test@gmail.com'"
```

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/issues/451

^ This issue delves into details.
