### ISSUE TITLE
Unable to get listmonk to send out campaign 

### ISSUE THREAD

**Issue by Kolskidman** [knadh/listmonk#239]
Thanks for helping me out with the installation, but after the installation, I got into a new error and it was that. I couldn't send out campaigns with listmonk as it keeps logging waiting for free conn in pool. I've tried several SMTP servers and still, it won't work and the error message is still the same. I attached a screenshot of my screen to this  message
![issue](https://user-images.githubusercontent.com/50783314/101681812-b4a63500-3a9d-11eb-955b-3f079e4d4733.png)

**Comment by knadh** [comment]
The logs clearly indicate that the auth mechanism is incorrect (none/plain/cram). You've to pick the right one. There are no usable connections in the pool because of this, and hence, the failures.

**Comment by Kolskidman** [comment]
Ok thanks for the info provided
