### ISSUE TITLE
Configuring links and views tracking to work

### ISSUE THREAD

**Issue by Kolskidman** [knadh/listmonk#240]
I don't know if it's proper to open an issue for this but this is the only way I've been taken to get help in using this software so I don't know of a better way to contact the developer other than this. My questiosn is that is there any special configuration I need to set to get listmonk clicks and views tracking to work. I've finally been able to send emails with it but I couldn't get the links and views tracking to work.

**Comment by knadh** [comment]
There is no special configuration. It's documented here with examples: https://listmonk.app/docs/templating/

**Comment by Kolskidman** [comment]
Hi knadh, thanks for your response as I would really feel bad if I never got any response from anybody but I've go through the links you sent me where I'm to read about templating and I'm confident I've understood how it works but my issue still the same. I've made sure to add the trackview templating code and the track link but the view and link stats withing my dashboard is still nothing here. I know there's nothing wrong with this package and I'm the one not setting up everything correctly. So I'm curious maybe there's a setting I forgot to set when I initially installed this software as I only go through docker documention to install docker and docker compose as I realized that's what I need to install your software and the instant I got done with that I head over to your sample docker-compose.yml file copy everything as it and I created a docker-compose.yml file on my server pasted everything as it is. Even I didn't even change the login credentials and simply leave it like that cuss I'm afraid of breaking something and I don't want that to happen cuss I just need to get the software up. Then I login setup the first smtp server up though I had a little issues there as well which you helped me with. So this are all the steps I've taken on the server. So I'm now curious as to that is there any configuration I'm yet to setup. Pls help with it and point me over to where I can learn more about it.

**Comment by knadh** [comment]
hm, can you share one of the tracking links you're getting in the e-mail here?

**Comment by jackdanielux** [comment]
Copy paste the HTML of your email with tracklink / trackview code.

**Comment by Kolskidman** [comment]
like you asked, this is the link I was trying to track (   <a href='{{ TrackLink "https://wpbeginner.pro" }}'> Here is my link being tracked</a> ) 


and like @jackdanielux  asked. this is my sample email I was using to see if link and view tracking had started working properly

`<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>

        <p>
            This is just to test whether my link and views clicks had start to works
        </p>
        <a href='{{ TrackLink "https://wpbeginner.pro" }}'> Here is my link being tracked</a>

        <footer>
            Copyright 2019. All rights Reserved.
        </footer>
        <p>And below is my trackview pixel</p>

        
        {{ TrackView }}
    </body>
</html>`

**Comment by Kolskidman** [comment]
Edit I forgot to insert the tracked link properly


`<a href='{{ TrackLink "https://wpbeginner.pro" }}'> Here is my link being tracked</a>`

> like you asked, this is the link I was trying to track ( Here is my link being tracked )
> 
> and like @jackdanielux asked. this is my sample email I was using to see if link and view tracking had started working properly
> 
> `
> 
> ```
> </head>
> <body>
> 
>     <p>
>         This is just to test whether my link and views clicks had start to works
>     </p>
>     <a href='{{ TrackLink "https://wpbeginner.pro" }}'> Here is my link being tracked</a>
> 
>     <footer>
>         Copyright 2019. All rights Reserved.
>     </footer>
>     <p>And below is my trackview pixel</p>
> 
>     
>     {{ TrackView }}
> </body>
> ```
> 
> `

**Comment by setiseta** [comment]
In the setting there is a Switch for tracking, under privacy, defaults to off. I think you need to Switch this one to on.
Then under settings -> general i think you need a correct root URL so the the tracking can contact the listmonk Server.
Are those settings done and correct?

Then in the Mail there should be an img Tag in the source like:
```
<img src=3D"https://[my listmonk url]/campaign/d6c146c4-de58-4130-=
9483-a0b331235a9a/1f708f12-586d-1234-b732-f151cd123b3f/px.png" alt=3D"" />
```
Be Sure that you Mail Client shows pictures and is not blocking this Pixel. 

After this I See an entry on the Campain Views panel.
