### ISSUE TITLE
Block subscribers through their email address or expose API to get their ID using email 

### ISSUE THREAD

**Issue by Haris3243** [knadh/listmonk#243]
@knadh sir i have problem while blocking a subscriber as it takes the subscribers ID to block. but AWS SNS send us only email address.
1. is there a way to block subscriber through their email?
2. if not, can you expose an API to get ID from email address? so that we can use that ID in the block API. but that would make our task a much time consuming as AWS SNS may sends multiple emails to Block and we have to get subscriber's IDs for each email first.
in AWS SNS their is only UUID is provided which can be used to block subscribers

**Comment by knadh** [comment]
You're right. All endpoints right now take an ID, but there needs to be APIs that take e-mails as primary IDs. Will implement these at some point.

You can pass the `query` (SQL exp param) to `GET /api/subscribers` to get a subscriber by e-mail. `email = 'email@id.com'` should do.
