### ISSUE TITLE
Install listmonk manually

### ISSUE THREAD

**Issue by tobidwest** [knadh/listmonk#244]
Great tool! I can't run commands, as I am on shared hosting. Is there a way to get listmonk running by just using ftp to manually edit files?

**Comment by knadh** [comment]
Unfortunately no. You need to be able to run commands to run programs like listmonk.

DigitalOcean, AWS Lightsail etc. provide inexpensive hosting with shell access. You might want to check them out.

**Comment by tobidwest** [comment]
Thank you for the recommendations, @knadh. I got a hosting plan with SSH access and successfully created and added the config file. However, when trying to connect, I'm seeing a timeout for the database correction, all though the information is the same as provided on my hosting dashboard. I even checked the information through phpmyadmin and it appears to be correct. Any suggestions?
`2021/01/10 20:33:03 init.go:173: error connecting to DB: dial tcp 178.254.10.134:306: connect: connection timed out`

**Comment by mr-karan** [comment]
`178.254.10.134:306`

Are you sure you're giving the correct port? `306` seems to be a typo for `3306` which is MySQL's default port. But Listmonk uses Postgres, default port for that is `5432`.

**Comment by tobidwest** [comment]
In phpmadmin I saw `3,306` so I thought there are two possibilites. It seems 3306 is the correct port. Thank you.

Now I am seeing:
`init.go:173: error connecting to DB: pq: unknown response for startup: '['`

Isn't there a way to use MySQL instead of Postgres? I don't think my hosting provider has Postgres.

**Comment by knadh** [comment]
@tobidwest listmonk only works with Postgres unfortunately.
