### ISSUE TITLE
docker keeps restarting due to unknown provider error 

### ISSUE THREAD

**Issue by song85129** [knadh/listmonk#251]
Hi, 
The docker container keeps restarting after installation.
The log says init.go:276: unknown provider. please select one of either filesystem or s3

Do you know how to solve that please?
Thank you.

**Comment by knadh** [comment]
Can you confirm which version of listmonk you are using? This scenario should not happen in the latest version.

**Comment by song85129** [comment]
> Can you confirm which version of listmonk you are using? This scenario should not happen in the latest version.

Hi， thanks for the reply. It is the latest version.

**Comment by song85129** [comment]
Hi Thank you for the hint! The problem was solved by specifying the version number in the docker-compose.yml instead of using latest. I think somehow the latest on my case downloaded some version dated back in may last year. It is now all setup and running. Thank you again.
