### ISSUE TITLE
List Subscrpton Confirmation Emails Not Being Sent

### ISSUE THREAD

**Issue by bonedaddy** [knadh/listmonk#254]
For some reason Listmonk doesn't appear to be sending the confirmation emails when people subscribe to the newsletter i am running, The first few subscribers the confirmation email was being sent, but now it is not.

The signup page is located here to test: https://ndx-newsletter.bonedaddy.io

**Comment by knadh** [comment]
If the opt-in mails fail, the logs will record that. Can you check `Settings -> Logs`?

Are non opt-in mails going out? You can create a sample campaign and use the `Send test message` box on the right to test it.

**Comment by bonedaddy** [comment]
Yea I checked `Settings -> Logs` and there was nothing indicating an error. I also checked the docker compose container logs and couldn't find anything. Non opt in mails are indeed going out.

**Comment by knadh** [comment]
`v0.9.0-beta` is released and there are some changes to how opt-in mails are sent. Could you try upgrading?
