### ISSUE TITLE
Error and success messages are not shown for long enough, and are not logged either

### ISSUE THREAD

**Issue by looeee** [knadh/listmonk#257]
I've just successfully set up listmonk on my server and sent my first test email using Amazon SES within about 15 minutes, thank you for creating such an easy to use program. 

Along the way, I encountered a small error when trying to send the test email - I had set the Auth Protocol incorrectly (I left it at the default of `cram` when SES needs `plain`). 

As a result, I got an error message saying "_503 incorrect authorization something something..._". I never got to read the rest of the message though, because it only displays for about 1.5 seconds (in a red banner at the top of the Campaigns page). 

Would it be possible to make the error messages persist for long enough to read/copy them? 

It doesn't seem like the details of this error are available on the settings/logs page either. It would be useful if sending success/error messages were stored in the logs so that I can check them later.

**Comment by knadh** [comment]
Thanks @looeee. All mailing errors are logged but the test message one was missed out. Just added it (https://github.com/knadh/listmonk/commit/b420c31d3369bf452f926b19934e75ad4d9ec7f6) and it will be available in the next release.

**Comment by looeee** [comment]
Great, thanks for the speedy response 👍
