### ISSUE TITLE
Question: Does Listmonk send using all SMTP configured or just one?

### ISSUE THREAD

**Issue by enniosousa** [knadh/listmonk#259]
**Situation**
My organization has G Suite for Education. Each email account can send only 2000 messages/day, becouse of that, when I need send 8000 messages I have 2 options: send the campaing in many days respecting the quota, or send from multiples email accounts.

So, does Listmonk send campaings using all SMTP configured or just one?

**Comment by knadh** [comment]
Emails are pushed to all SMTP servers that are enabled. The number of messages that go to each active server should be roughly equally distributed.

**Comment by DKV006** [comment]
@knadh is it possible to configure a Campaign to use specific SMTP server settings ??

**Comment by knadh** [comment]
It's not possible to pick an SMTP server per campaign, but if you really want to use different servers, you can globally enable/disable the required SMTP servers before sending certain campaigns.

**Comment by charlesmudy** [comment]
This will be a great addon if its possible considering the system already has multiple SMTP option. This is especially useful when sending using the API, you don't want to go to the dashboard to enable/disable before sending campaigns all the time.

Kindly consider or share how this can be added

**Comment by anantanandgupta** [comment]
i have tried to visualize the implementation https://github.com/knadh/listmonk/issues/1703#issuecomment-2007171972

> This will be a great addon if its possible considering the system already has multiple SMTP option. This is especially useful when sending using the API, you don't want to go to the dashboard to enable/disable before sending campaigns all the time.
> 
> Kindly consider or share how this can be added @knadh

**Comment by RealEstateSaga** [comment]
If you have multiple smtp servers configured with different domain names, what should you set as the default sending address for each campaign?
