### ISSUE TITLE
Campaign Sending Speed varies [Question]

### ISSUE THREAD

**Issue by cb3inco** [knadh/listmonk#263]
We've run about 14 Campaigns through Listmonk now and have noticed something peculiar. 

This campaign is set with a custom template. It's using the default 'from' address and went out in about 9 minutes to 904 users.

![image](https://user-images.githubusercontent.com/14948644/107313402-029edf80-6ac5-11eb-9beb-f6675c22d195.png)

This campaign is sent with a simple template. It's using a different email address than the default 'from' address and being sent to 895 people. It took 1 hour. 

![image](https://user-images.githubusercontent.com/14948644/107313338-e26f2080-6ac4-11eb-8ddd-11fbeb13758b.png)

The SMTP and Performance tabs stayed the same and neither were modified between campaigns. I'm not sure if the logs give any details. Curious if anyone else see this. Is it because I'm not using the default address for the one campaign?

**Comment by knadh** [comment]
Whoa, 9 mins to 1 hour for such a tiny number is crazy. The `from` address has no bearing on any of the app's routines. It's just a string that's added to the `from` header in the outgoing e-mail.

9 mins for 904 e-mails = ~1.4 messages / second. Have you set the rate this low in settings? On an average system, you should be able to send dozens or even hundreds of e-mails per second.

What is the `wait timeout` value in your SMTP settings? That is the max duration after which, if the SMTP server hasn't finished accepting a single message, listmonk considers it a timeout and logs. Do the logs show timeout errors?

**Comment by cb3inco** [comment]
Just yesterday I bumped from 4 to 5 on the performance tab for concurrency and message rate. This was the 'default' from when I initially installed Listmonk. I'm relaying the email over a IPsec tunnel from Asia to North America. It doesn't explain why one campaign with a specific template takes slower than another regardless of time of day. I've kept them low because of the VPN. I'm also relaying off and on-prem Exchange server. I have seen the timeout in the logs before, but I don't see that visually in the logs at the moment. The campaigns that are super quick have a template that is more 'graphic' heavy then the other that takes an hour. 

Performance:
![image](https://user-images.githubusercontent.com/14948644/107333017-78b43e00-6ae7-11eb-8eb7-d73a75ae5bfe.png)

SMTP:
![image](https://user-images.githubusercontent.com/14948644/107333073-8e296800-6ae7-11eb-9e8f-5788c29ce2f7.png)

**Comment by knadh** [comment]
hm, maybe it is related to this https://github.com/knadh/listmonk/issues/227 ([fixed here last week](https://github.com/knadh/listmonk/commit/68afd61024f13cce800fe076df500347b1291752)). This will be available in the upcoming release this weekend.

**Comment by cb3inco** [comment]
Hmm maybe this is the problem. The campaign taking forever is using tables too - https://github.com/knadh/listmonk/issues/227#issuecomment-766703878 - Will look out for the new update.

**Comment by knadh** [comment]
`v0.9.0-beta` is released!
