### ISSUE TITLE
Users subscribing to double opt-in list are given no indication that they will be receiving a confirmation e-mail

### ISSUE THREAD

**Issue by gryphonmyers** [knadh/listmonk#264]
Reproduction Steps:
1) Create a new public, double opt-in list
2) Create a subscription form for the list (copying and pasting the content from the 'forms' view for this list)
3) Use the form to perform a test signup with any e-mail address
4) Observe that you are taken to a view displaying a "Done. Subscribed successfully" message. 

Expected Results:
If a mailing list is public and set to double opt-in, upon submission of an email address, the user should be taken to a view explaining that they will need to confirm their e-mail address. A "Done. Subscribed successfully" message does not adequately explain that their information has been accepted in a tentative state and that further action from them will be required in order to receive further e-mails.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/2f6bd05ca0fc1d5070114df03544b184aa870017 fixes this.
