### ISSUE TITLE
Signups fail if user exists in any mailing list (including ones unrelated to the one they are signing up for)

### ISSUE THREAD

**Issue by gryphonmyers** [knadh/listmonk#265]
Reproduction Steps:
1) Create two lists. Add any test subscriber email address to one of them.
2) Perform a signup using a signup form for the other list (the one that does not contain the test e-mail address).
3) Observe that an "Error. The e-mail already exists" message is rendered.

Expected Results:
When an existing user signs up for a list that they are not currently on, they should be added to the list rather than rendering an error.

**Comment by knadh** [comment]
This was fixed last week https://github.com/knadh/listmonk/commit/dd0c124b0e0cad7f032606e4605bdefa6a70279d. Will be available in the upcoming release.
