### ISSUE TITLE
Repeat signup submissions to double opt-in lists are given no way of re-sending the confirmation e-mail

### ISSUE THREAD

**Issue by gryphonmyers** [knadh/listmonk#266]
Reproduction Steps:
1) Create a double opt-in public list
2) Signup to this list with a test e-mail address using a client signup form.
3) Ignore the confirmation e-mail 
4) Attempt to signup with the same e-mail address again.
5) Observe that you are given an "Error. The e-mail already exists" message. 

Expected Results:
If the user is attempting to sign up to a double opt-in list they have already signed up for but they are in an unconfirmed state, a duplicate submission should provide the option of having another confirmation e-mail sent to them. Otherwise, in a case where they never received or lost/deleted the confirmation e-mail, the user has no path to getting confirmed,

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/2f6bd05ca0fc1d5070114df03544b184aa870017 fixes this.
