### ISSUE TITLE
Page "Error fetching e-mail message"

### ISSUE THREAD

**Issue by TomBoss** [knadh/listmonk#269]
Hi,
With listmonk v0.9.0-beta, I have this error message: `error fetching campaign subscriber: sql: expected 3 arguments, got 2`, after clicking on link https://domain.com/campaign/c30dfabe-68c8-4a37-aefc-2fa084e4c939/9fefc0ef-7e5f-4d89-8a13-f76ebad9a544 generated by `{{ MessageURL }}`.
Thanks for the help

**Comment by knadh** [comment]
Ouch, this is a bug, a regression. Will fix shortly.

PS: A test suite is on the cards before v1.0 to avoid stuff like this.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/97b78aa69582af5df6c3f5a66ebf6884eb10cfbf fixes this.
