### ISSUE TITLE
Raw HTML mode removes HTML comments

### ISSUE THREAD

**Issue by TomBoss** [knadh/listmonk#270]
Hi,
Listmonk's raw HTML mode removes HTML comments `<!-- Comment -->` which are useful for adding conditional code depending on the mail client.
Would it be possible to keep the html comments `<!-- Comment -->` in raw HTML mode? Many thanks.

**Comment by knadh** [comment]
Looks like Go's templating library automatically removes comments in rendered HTML. There is no built-in way to toggle this behaviour unfortunately.

**Comment by knadh** [comment]
Maybe using a `data-comment="...."` attribute on certain elements can be used as a workaround?

**Comment by TomBoss** [comment]
Mmmh, I use [mjml.io](https://mjml.io) to generate the templates, and the HTML comments are added automatically to create responsive mails. This is what allows the mails to display correctly in Oultook...

**Comment by TomBoss** [comment]
Maybe with this solution should meet my need:
https://stackoverflow.com/questions/34348072/go-html-comments-are-not-rendered
