### ISSUE TITLE
Running listmonk on Plesk server

### ISSUE THREAD

**Issue by herzkerl** [knadh/listmonk#275]
Listmonk run's perfectly fine on our Plesk server—but I can't use Plesk's port mapping feature. I think I've found the problem—emphasis mine:

> To change the port on the host system, clear the option Automatic port mapping and specify another external port in Manual mapping. **If no Manual mapping appears when you clear the check box, it means that the container does not expose ports.**
Source: https://docs.plesk.com/en-US/obsidian/administrator-guide/plesk-administration/using-docker.75823/

Is there any way you could change the build process of the docker image—or is there anything I could do within Plesk? (besides starting the container manually with the port parameter)

Thank you!

PS: https://support.plesk.com/hc/en-us/articles/115003142213/comments/360000605359
PPS: https://github.com/knadh/listmonk/compare/master...herzkerl:patch-1

**Comment by herzkerl** [comment]
PS: https://support.plesk.com/hc/en-us/articles/115003142213/comments/360000605359

**Comment by herzkerl** [comment]
https://github.com/knadh/listmonk/compare/master...herzkerl:patch-1

**Comment by knadh** [comment]
Merged. Thanks for figuring this out.
