### ISSUE TITLE
Sync with external DB?

### ISSUE THREAD

**Issue by iammattmartin** [knadh/listmonk#277]
Are there any plans to have a list of users be added/removed from an external DB.

i.e we could insert MySQL data and the query to run to output the data. New addresses seen are added and those no longer returned are removed.

This would make list keeping automatic and always up to date (to the hour or day for example).

**Comment by knadh** [comment]
A note on this is available here: https://listmonk.app/docs/external-integration/

It's trivial to build external DB integrations. No specific features around this are planned.
