### ISSUE TITLE
Opt-in (and other notifications?) template customization 

### ISSUE THREAD

**Issue by nandanrao** [knadh/listmonk#279]
If I understand the code correctly, email templates for the 4 notification-type emails are loaded from stuffbin from the binary itself and used by `sendNotification`? 

This, and the fact that I see no other way to do it, makes me assume that it's not possible to customize the opt-in email (the first email subscribers see!) without recompiling. If there is an easy way, then it would be great for this to be documented somewhere!

If there is not, it seems like it would be helpful to at least have those templates loaded from the database where they can be modified without recompiling. 

I'm just getting started trying to integrate listmonk, but I'm very excited about it, it seems great! Happy to help with this if there is anything to be done.

**Comment by knadh** [comment]
You can customize the templates with the `--static-dir` flag.

https://listmonk.app/docs/configuration/#customizing-public-templates

**Comment by nandanrao** [comment]
Hi @knadh - thanks for the quick reply and sorry I missed that in the docs. 

I still think it would be useful to change the notification email in some way without having to mount static assets, as there is already a way to create templates in the UI and store them in the DB I'm not sure what the downside is?

**Comment by knadh** [comment]
> I still think it would be useful to change the notification email in some way without having to mount static assets.

The problem with this is, even if you make the HTML templates editable on the UI, how do you manage static assets like images, CSS, JS for the templates? Either you've to provide an interface to upload and manage these files, which is out of the scope of the product, or you've to allow them to be mounted locally on the disk (or you have to host them remotely behind a webserver and link them).

Either way, there's no avoiding disk, so mounting everything locally in one place + exposing them seamlessly via the built in HTTP server is the simplest approach.

**Comment by nandanrao** [comment]
Fair enough, I see your point!
