### ISSUE TITLE
APIs need documentation

### ISSUE THREAD

**Issue by knadh** [knadh/listmonk#28]
Currently, only the subscribers API is documented, while there are [many more handlers](https://github.com/knadh/listmonk/blob/2c18d6356bb8c1f9a2466455e3d4c1791a947461/handlers.go#L42) to document.

The docs are published at https://listmonk.app/docs/apis/apis/ and the source is at https://github.com/knadh/listmonk-site

**Comment by Quadrisheriff** [comment]
Knadh are you still in need of the services of a tech writer?

**Comment by brntbeer** [comment]
@knadh wanted to bump this thread. i noticed @Quadrisheriff and myself both being interested in helping and i was curious on the interest from Listmonk's side.

**Comment by knadh** [comment]
@Quadrisheriff @brntbeer the documentation right now is highly incomplete and it would be great if we could expand it. Documenting more API handlers would be a great start. I've done a [couple here](https://listmonk.app/docs/apis/subscribers/) to serve as a template.

**Comment by knadh** [comment]
Update: @Quadrisheriff has contributed significantly to the documentation and has documented pretty much all API endpoints here: https://listmonk.app/docs/

Thank you!
