### ISSUE TITLE
How to send a series of emails?

### ISSUE THREAD

**Issue by nest-don** [knadh/listmonk#280]
Hello Kailash,

From what I understand the developer must use their own scheduler to send the email.

What would be the best method to send a series of emails over a few days?

Thank you

**Comment by knadh** [comment]
You can schedule a campaign to go live at a certain date, but sending at cycles, isn't supported. If you're looking for that level of automation, I think something like Mautic may be better suited.

**Comment by nest-don** [comment]
Thank you, I had a look at Mautic but it does not support Postgres that I need.

Besides, all I require is a simple messaging.  I can probably use Laravel to fill the gaps.

I started testing and this pops up.  

**2021/03/02 15:23:43 campaigns.go:590: error sending test message: SMTP AUTH extension not found**

Do you want me to open a new issue or is this a simple fix?
