### ISSUE TITLE
How many emails can I send through campaign ?

### ISSUE THREAD

**Issue by PrashantRuth** [knadh/listmonk#282]
I need to send out bulk emails to a heavy group of customers and wasn't sure if listmonk would be able to handle that..
We have approx 1550k users we have to send an email to... 
Just wanted to know if this is possible or not.

**Comment by knadh** [comment]
Our production instance has ~5mn subscribers. listmonk runs fine and uses very little CPU and RAM. Bottleneck may be the DB setup, and most definitely, the SMTP servers. We provision multiple big SMTP instances when we've to send a campaign.

**Comment by PrashantRuth** [comment]
Okay cool!
Thanks for letting me know. Helped me out quite a bit
Have a great day :D

**Comment by readthecodes** [comment]
Hello, I'm confused with "We provision multiple big SMTP instances when we've to send a campaign", what is big SMTP instances meaning? and is it automatically load balance between multiple SMTP instances?

**Comment by knadh** [comment]
I was referring to our SMTP servers to which listmonk connects, nothing in listmonk itself. Yes, external SMTP servers can be used behing a load balancer.

**Comment by readthecodes** [comment]
OK, thanks for your response ^_^ 
what do i need to do if i want to use listmonk & AWS SES to send millions marketing emails? you build your own SMTP server or use third-party service just like AWS SES?

**Comment by knadh** [comment]
SES gives you an SMTP interface. You just have to put that config in listmonk Settings -> SMTP.
