### ISSUE TITLE
Error in the day of the week

### ISSUE THREAD

**Issue by TomBoss** [knadh/listmonk#285]
For example, today March 6, 2021, it's Saturday and not Sunday.

![2021-03-06](https://user-images.githubusercontent.com/423523/110220861-ed9d4c80-7ec8-11eb-94b3-b34b59a3ae6e.png)

Thanks

**Comment by knadh** [comment]
Thanks. Fixed here: https://github.com/knadh/listmonk/commit/8a6ed2ac2edbc42ce8b755fe77ff7ca4d98481d1
