### ISSUE TITLE
An option to disable basic auth

### ISSUE THREAD

**Issue by NicolaiSchmid** [knadh/listmonk#286]
I would like to completely disable Basic auth. I'm running Listmonk behind a proxy with a more comprehensive auth strategy and for this reason I would like to disable basic auth completely.
With the username and password empty
```
admin_username = ""
admin_password = ""
``` 
it seems like Basic auth is still enabled but just doesn't require a password.
Maybe we can detect the empty variables and then disable the auth mechanism? The new setup doesn't seem to cover all usecases

**Comment by knadh** [comment]
@NicolaiSchmid leaving both variables empty does infact disable auth checking, but there was a bug in the implementation that would still prompt for auth (but not do any validation in the input credentials).

I fixed this recently and it's in the new `testing` branch, which will get merged into master soon.

https://github.com/knadh/listmonk/blob/testing/cmd/handlers.go#L44

**Comment by NicolaiSchmid** [comment]
Perfect, thank you. I'll stay patient until this will be merged!

**Comment by alerque** [comment]
This bug just tripped me up for a while too.

**Comment by knadh** [comment]
Woops. This is already merged into master and will be available in the next release.

**Comment by alerque** [comment]
Yes. I'm not running a Git HEAD build to get around this, but I was initially following along with documentation that said this was working but the stable tag I was building didn't have this.

I know 2 months isn't *that* long for big projects development cycle, but when obvious bugs like this are fixed there should probably be tagged as patch versions.

**Comment by knadh** [comment]
> but when obvious bugs like this are fixed there should probably be tagged as patch versions.

I agree. Never got around to doing this. Will start doing.
