### ISSUE TITLE
Listmonk not reading from database

### ISSUE THREAD

**Issue by mattmalec** [knadh/listmonk#287]
I've got Listmonk installed with EKS & Fargate on AWS. I've setup my config.toml according to the sample and it successfully connects to the RDS Postgres database. Listmonk seems to save changes to the database, but doesn't want to read them. 

If I were to set the Root URL, it's saved in the database. But when the app reloads, those changes don't appear on the UI and it's reset to the default back in the database. Or when I create a list, the lists are successfully created and are visible in the database, but don't appear on the UI.

Any ideas? Thanks in advance.

Edit: I should mention there are no errors in the logs. I'm running version `v0.9.0-beta (e90fb1d 2021-02-13T12:41:40Z)`

**Comment by knadh** [comment]
This seems like an issue with the RDS setup. listmonk merely uses standard Postgres drivers to execute read/write queries. If the updates are returning a success, that means RDS accepted them and returned a success. If subsequent queries are somehow returning old data, that means RDS is returning old data.

PS: Have you checked that this is not some sort of aggressive HTTP caching?

**Comment by mattmalec** [comment]
No aggressive caching that I'm aware of. I tried using both CloudFront and the ALB directly to no avail. What does RDS do differently that would cause an issue here? I'm not using Aurora in this case, so shouldn't it be running standard Postgres?

**Comment by knadh** [comment]
Yeah, it's puzzling that writes come back with a success but the changes don't persist.

Can you try connecting to the DB directly (psql?) and doing an insert/update query to see if it persists?

**Comment by mattmalec** [comment]
It does. I connected via Datagrip. Making changes directly in the database don't appear on the UI. And when I save from the UI, the changes I made in the database are overwritten.

**Comment by knadh** [comment]
Whoa. Maybe RDS is incorrectly serving stale data from a replica internally? Try deleting and re-creating the RDS DB instance?

**Comment by mattmalec** [comment]
Is there a specific version of Postgres you'd recommend I use? This current one is running 11.10.

**Comment by knadh** [comment]
I've tried the latest version on 11, 12, and 13. Pretty sure this is unrelated to the Postgres version. Did you try re-creating RDS?

**Comment by mattmalec** [comment]
Sorry for not getting back to you sooner - i'll try this in the morning. Just wanted to bump this so you wouldn't close it thinking I figured it out. Cheers!

**Comment by mattmalec** [comment]
Tried recreating the Postgres DB on RDS, but it still doesn't work as expected. Even using a local instance doesn't seem to work.

**Comment by mr-karan** [comment]
@mattmalec Can you post reproduction steps and a bit more detail about how you're running Listmonk? Are you sure you're not using the `docker-compose` with `demo-app` and `demo-db` containers?

**Comment by knadh** [comment]
> Even using a local instance doesn't seem to work.

You installed Postgres DB locally and the writes still do not reflect in the DB? I'm stumped.

**Comment by mattmalec** [comment]
We are using Mailchimp for the time being. I'll open this issue again once I find time to sit down and debug this again. Thank you for the swift responses!
