### ISSUE TITLE
Add support for styling with markdown

### ISSUE THREAD

**Issue by mdehollander** [knadh/listmonk#292]
It would be nice if it is possible to paste/write content in markdown format. I think that could be added to the editor with this plugin for Quill: https://github.com/cloverhearts/quilljs-markdown

**Comment by knadh** [comment]
Missed this issue. Will test out the lib.

**Comment by knadh** [comment]
Markdown support is added: https://github.com/knadh/listmonk/commit/1e59d53135f1708e08e91e535b8555b5b45343ce

Couldn't figure out what the quill plugin was doing, but Markdown rendering support had to be added in the backend anyway. So, the UI is just a plaintext box and the rendering is handled by the backend.

![image](https://user-images.githubusercontent.com/547147/114679202-955c3480-9d29-11eb-8f8e-b2eb7c05cdb0.png)

**Comment by mdehollander** [comment]
Nice! Thanks. More reasons to update to 1.0 when it is out.

I think the guill plugin allows for direct rending of the markdown, so if you type/paste something like a header (`## Header`), then it it shows automatically as a formatted header. See https://cloverhearts.github.io/quilljs-markdown/ Not sure if this is the case now with the goldmark parser. Anyway, looking forward to try it out :)
