### ISSUE TITLE
List does not refresh for draft campaigns

### ISSUE THREAD

**Issue by BenBao93** [knadh/listmonk#293]
It looks like the list is frozen at the moment of campaign creation and new subscribers are not added. When a campaign is cloned it pulls the current total of subscribers in the selected lists.

Not sure if this is a display issue or if the list is really 'frozen' when the campaign is first created. Depending on how long a campaign is in draft there may be a lot of new subscribers in the list that should also get the mails at the time of sending.

![Screenshot 2021-03-13 at 11 48 30 AM](https://user-images.githubusercontent.com/29012632/111036780-fad3b180-845b-11eb-89d3-84489b25f3f5.png)

**Comment by knadh** [comment]
When a campaign is created, the stats are recorded (just to show on the UI). When the campaign starts, the numbers are updated again, so at the point of starting, all new subscribers are considered.

**Comment by BenBao93** [comment]
Ok, was hoping it is that but afraid to try sending and then not having it push to the whole list. Thanks for the clarification!
