### ISSUE TITLE
Bounces handling

### ISSUE THREAD

**Issue by athoune** [knadh/listmonk#3]
Will you use Postfix for handling bounces (tailing and parsing its log, just like [cuttlefish](https://cuttlefish.io/) does, or implementing a full golang smtp server with [go-smtp](https://github.com/emersion/go-smtp) ?

**Comment by knadh** [comment]
The plan is to try and implement these:
- API to pipe e-mails data in from arbitrary places (eg: pipe from Postfix or Dovecot).
- Interface for reading bounces from POP / IMAP endpoints.

Bundling a mail server into listmonk's core broadens the scope quite a bit and may not be desirable. It's probably easier to build a minimal standalone POP/IMAP daemon that pipes e-mails into one of the aforementioned interfaces.

**Comment by athoune** [comment]
Ohh, `IMAP IDLE` is handled by golang : https://github.com/emersion/go-imap-idle

**Comment by abhas** [comment]
How about using VERP: https://en.wikipedia.org/wiki/Variable_envelope_return_path

So when the mails go out, the RETURN-PATH is encodes the recipient's email address with VERP. When the mail bounces back, the SMTP server can tokenize the email address causing the bounce and it can then be flagged or deleted etc. One way of doing is to pipe all bounce messages to maildrop via an alias (or the equivalent of a .qmail file) and maildrop can then extract this email address and run a script to submit it to the newsletter management system for further processing.

**Comment by knadh** [comment]
VERP can certaintly be added as an option (that can be toggled on/off) in the SMTP settings. With a bounce processing interface in listmonk, it's then possible to bring in the data from anywhere in any number of ways.

But, I think it's important to have a dead simple bounce tracking system that anybody can setup. It doesn't have to be 100% accurate and should be as simple as pointing listmonk to an IMAP or POP inbox where bounces land without having to setup up and script middleware.

I've seen the `X-Failed-Recipients` header, but I'm not sure if it's prevalent enough. Also, I remember that phpList parses the e-mail body and uses a bunch of rules and heuristics to determine the bounce source, and it works quite well.

**Comment by sweetppro** [comment]
perhaps initially adding support for Amazon SNS notifications would be a good start.
It seems like it would be pretty easy to setup,
as the notification is sent as a JSON object:
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html

**Comment by tanmaymohan** [comment]
A little +1 to @sweetppro answer. I have been using SES Bounce notifications where all the bounce notifications from SES are sent to a SNS endpoint and then it's POSTed to a specific URL on my backend where I can unsubscribe the user. Somewhat like this might help in cases where the SMTP service used is SES

**Comment by knadh** [comment]
Yep, a postback for bounces make sense. We still need to have a more universal mechanism that works for all SMTPs. For locally managed SMTPs, it's possible to have a util that reads a bounces inbox and pipes the e-mails to the listmonk postbac endpoint. But I'm curious to know if there's an "industry standard" for this right now.

**Comment by knadh** [comment]
Closing this thread in favour of https://github.com/knadh/listmonk/issues/166.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/issues/166#issuecomment-850092419

I've finally started working on this :)

**Comment by Slach** [comment]
@knadh WOW! great news ;)
