### ISSUE TITLE
Querying part of subscribers - LIMIT not working

### ISSUE THREAD

**Issue by roshanjonah** [knadh/listmonk#301]
If a list has 1000 subscribers and I want to target only 500 - how exactly would my query look like? 

I tried the following:
```
subscribers.id BETWEEN 1 AND 500
subscribers.status = 'enabled'
```

But if I combine both, it is not working in list monk (Advanced querying box). Unfortunately `LIMIT 500` is not working. Any ideas anyone? =)

**Comment by knadh** [comment]
```SQL
subscribers.id in (SELECT id FROM subscribers WHERE status='enabled' ORDER BY RANDOM() LIMIT 500)
```

^ 500 random subscribers. You cannot rely on `id` being a continuous sequence.
