### ISSUE TITLE
Support for replies to mailing list

### ISSUE THREAD

**Issue by d3vv3** [knadh/listmonk#302]
The case: When someone answers an email from the list, the response gets sent to all the list subscribers.

Isn't this case contampleted? Thanks!

**Comment by roshanjonah** [comment]
You could look into Mailparser.io and utilise Listmonk API to send reply back to everybody else but I doubt listmonk would cover custom use case like this =)

**Comment by knadh** [comment]
@d3vv3 this isn't in the scope of listmonk, which is a list/newsletter system where lists can have millions of subscribers. You're referring to behaviour that is more suited for mailing list groups, where subscribers interact with each other.
