### ISSUE TITLE
how to use messengers service?

### ISSUE THREAD

**Issue by karimul** [knadh/listmonk#304]
Hi,
I'm trying listmonk and I was confused when configure messengers setting. 

1. how to configure messengers setting and which messengers provider that supported by listmonk?
![image](https://user-images.githubusercontent.com/5180710/112757295-60569f00-9013-11eb-9998-ee3c599475b4.png)

1. is there a way to send individual campaigns using messengers?

**Comment by knadh** [comment]
Please refer to [Messenger docs](https://listmonk.app/docs/messengers/). You'll have to write your own HTTP messenger service that takes a POST from listmonk and dispatches to whatever upstream backend (SMS, Telegram etc.)
