### ISSUE TITLE
Cypress end-to-end integration tests

### ISSUE THREAD

**Issue by knadh** [knadh/listmonk#305]
I've managed to add integration tests for a large number of interactions using [Cypress](https://www.cypress.io/). Cypress was really easy to understand get started with. This is available in the [testing](https://github.com/knadh/listmonk/tree/testing) branch. (`frontend/cypress.json`, `frontend/cypress`).

To run tests locally:
- `make dist` to prepare the listmonk binary. `docker-compose up db` to run the Postgres demo DB.
- `cd frontend` and then `yarn install` to install Cypress.
- `yarn run cypress open` to open the Cypress UI where tests are listed. Clicking on a test runs it.
 **IMPORTANT:**  Every test resets the state by pkilling listmonk, resetting the Postgres DB, and starting listmonk again. [See this](https://github.com/knadh/listmonk/blob/8ef9fc2558910d812ae5d8a4452528c775716cf7/frontend/cypress.json#L4).

**To-do**:
- Make tests work in the Cypress docker enivornment.
- Integrate [GitHub Actions](https://github.com/cypress-io/github-action) for running tests automatically on merge (CI)

@mr-karan would you have time to look into this?

**Comment by mr-karan** [comment]
> Make tests work in the Cypress docker enivornment.

Ah, a bit confused. Why's this required? If it's only for running tests in CI, this step isn't required. We could run Cypress in Github Actions without bundling it in our `docker-compose` file.

The reason I'm asking is, the local development of `listmonk` doesn't depend on Docker (building frontend, building binary etc) so why should tests depend on it?

**Comment by knadh** [comment]
I didn't mean our local `docker-compose`, but a generic Docker environment (headless browser etc.). Yep, so just GitHub actions.

**Comment by knadh** [comment]
The `testing` branch is now merged to master.

**Comment by knadh** [comment]
@mr-karan got a chance to look at this? :cold_face:

**Comment by mr-karan** [comment]
Yeah, I did take a look at it last week. Postgres service and Listmonk binary both run, but Cypress isn't able to connect to the app:

![image](https://user-images.githubusercontent.com/5689132/114896326-df2e4300-9e2d-11eb-8567-05b2df2d0b14.png)

I used https://github.com/cypress-io/github-action to integrate but looks like I'm missing some config here. I'll check this again.
