### ISSUE TITLE
null value in column "campaign_id" of relation "campaign_views"

### ISSUE THREAD

**Issue by tamalsaha** [knadh/listmonk#314]
I tried to send a test campaign and I am getting the following error. I have used `v0.9.0-beta`.

```
error registering campaign view: pq: null value in column "campaign_id" of relation "campaign_views"
violates not-null constraint
```

Any idea what might be wrong and how to fix this?

**Comment by knadh** [comment]
Hm, this is new. `campaign_id` of a campaign that exists can't be null when a view is being inserted. You're seeing this error in the logs and not on the UI when you do an action, right?

`{{ TrackView }}` is what generates this the tracking image that does this insert. Can you inspect the HTML source of the message to see if the campaign UUID is present in the generated image link?

**Comment by tamalsaha** [comment]
> Hm, this is new. campaign_id of a campaign that exists can't be null when a view is being inserted. You're seeing this error in the logs and not on the UI when you do an action, right?

Yes. I used the `Start Campaign` before using `Save Changes`. That caused it. The emails were sent but I see the error in the logs.

![Campaign-listmonk](https://user-images.githubusercontent.com/94814/114373005-07205c80-9b37-11eb-93c9-3b6c280059a6.png)

**Comment by knadh** [comment]
I was unable to reproduce this. `Start campaign` internally does a save first, so that shouldn't make a difference. Either way, the campaign is already created and the UUID is generated before ever getting to the content tab. This error can only happen if the campaign UUID in the view URL couldn't be resolved to an existing campaign (deleted?). Unable to figure out how that could've happened in this case.

**Comment by sol2070** [comment]
I'm seeing this every day in my logs:
```
listmonk[1279]: 2023/07/19 16:51:09 campaigns.go:384: error registering campaign view: pq: null value in column "campaign_id" violates not-null constraint                                                           │
listmonk[1279]: 2023/07/19 16:51:09 public.go:526: error registering campaign view: code=500, message=Erro ao atualizar Campanha: pq: null value in column "campaign_id" violates not-null constraint. Failing row contains (570, null, null, 2023-07-19 16:51:09.844371-03).
```
I think it started when I copied a campaign. I deleted the copy and the messages persist.
