### ISSUE TITLE
Automatically collect User Agent and IP info for subcribers

### ISSUE THREAD

**Issue by tamalsaha** [knadh/listmonk#315]
I would like to add this functionality as user attribute. What do you think?

**Comment by knadh** [comment]
hm, collecting IP address of subscribers is very invasive and I don't think it should be baked into listmonk. It falls outside the scope of basic statistics tracking (views and clicks), doesn't it?

**Comment by tamalsaha** [comment]
Usually we want to know what is the timezone of a user. That can be useful when sending email campaigns. OS, device (mobile, desktop) those are also useful things to know when sending campaigns.

**Comment by mr-karan** [comment]
>  This can be found from IP address.

Not really full proof way. 

> OS, device (mobile, desktop) those are also useful things to know when sending campaigns

I'd suggest you take the timezone info from the user and create lists "Afternoon", "Midnight", "Evening" and add your subscribers accordingly to these lists. 

Just my $0.02 :)

**Comment by knadh** [comment]
@tamalsaha I don't think IP recording should be baked into listmonk's core. If you want to reocrd a subscriber's geographic location and timezone, you could figure that out at the time of subscription (a custom form or however you're inserting subscribers) and insert them as arbitrary fields in the subscriber's attributes. These can be queried using SQL expressions for segmentation later.
