### ISSUE TITLE
Can't subscribe to new lists from public subscription page

### ISSUE THREAD

**Issue by tamalsaha** [knadh/listmonk#316]
It seems that an email can't subscribe to new lists if already subscribed to one or more list using the public subscription page. Is this intended or a bug? Thanks.

**Comment by knadh** [comment]
![image](https://user-images.githubusercontent.com/547147/114681142-79599280-9d2b-11eb-9434-d80cb684ec50.png)

Unable to reproduce this (http://localhost:9000/subscription/form). Tried with single and double opt-in lists. Also, this behaviour was specifically fixed a while ago: https://github.com/knadh/listmonk/commit/dd0c124b0e0cad7f032606e4605bdefa6a70279d

**Comment by knadh** [comment]
Fixed: https://github.com/knadh/listmonk/commit/708d0e0b00acb3b59817b0164cadf587eb712143

**Comment by tamalsaha** [comment]
Thank you! The issue seems fixed in my testing.
