### ISSUE TITLE
Confused about dockerhub images and versioning

### ISSUE THREAD

**Issue by marcinkunert** [knadh/listmonk#318]
I've just started a fresh installation, it shows a message, that there is a newer version available.

![image](https://user-images.githubusercontent.com/2963232/114832506-d9eddb80-9dce-11eb-85d2-757e9c054102.png)

I've checked on docker hub and listmonk/listmonk:v0.9.0-beta seems to be older than listmonk/listmonk:latest

![image](https://user-images.githubusercontent.com/2963232/114832658-043f9900-9dcf-11eb-80ae-be2b3dda8cfa.png)

![image](https://user-images.githubusercontent.com/2963232/114832694-102b5b00-9dcf-11eb-99aa-e3335a065126.png)

I've checked the logs and I seem to be running `vtest0.1.2 (a0aefd3 2021-03-19T06:39:30Z)`. It's probably newer than `v0.9.0-beta`. If it's the case than the "A new update is available" message is redundant.

**Comment by mr-karan** [comment]
Ah crap. Sorry for the confusion @marcinkunert . I was testing Github Actions with https://github.com/knadh/listmonk/pull/296 and it looks like I'd pushed to `latest` from an unreleased version on 19th March.

The latest is still `0.9.0-beta` and you should use that. `:latest` will be updated automatically whenever a new release happens.

**Comment by mr-karan** [comment]
@marcinkunert I've retagged 0.9.0-beta to `:latest`.

Thanks for reporting this.

**Comment by marcinkunert** [comment]
@mr-karan thanks, it works now as intended!
