### ISSUE TITLE
Clicks should also increase the view count

### ISSUE THREAD

**Issue by marcinkunert** [knadh/listmonk#319]
I've sent a test campaign to myself. Thunderbird blocks sending tracking information so the `view` count is 0. I've clicked on a tracked link and it was counted. So the current state of the campaign is 0 views and 1 click. 

![image](https://user-images.githubusercontent.com/2963232/114833443-df97f100-9dcf-11eb-8637-01b77e66674a.png)

In my opinion the link click should increase the view count, only if the view wasn't already tracked for this user.

**Comment by knadh** [comment]
> In my opinion the link click should increase the view count, only if the view wasn't already tracked for this user.

I don't think views and clicks should be mixed. Entirely different contexts. A link can be shared without the e-mail, which wouldn't constitute a view.

Morever, multiple views and clicks can be recorded per user, which means it's not possible to figure out if a view wasn't already tracked just once.

**Comment by marcinkunert** [comment]
I've looked a bit into recorded data in the database and you are right. In this view "raw" data are being shown. Not really too useful for campaign statistics (like open rate, % of user that clicked a link, etc.), but I guess it gives a rough understanding how successful the campaign was.

Are there plans for better campaign statistics? For example adding a third tab for with details like open rate links clicked? Or is it out of scope for this project?

**Comment by knadh** [comment]
> Are there plans for better campaign statistics?

Yes indeed. A proper report viewer / analytics feature has been pending for a while. After the planned 1.0 release in the next couple weeks (finally out of beta after 2.5+ years), analytics will be the next big release.

**Comment by marcinkunert** [comment]
Great news! Thanks a lot!

**Comment by knadh** [comment]
This is available in the latest version, v2.0. Analytics looks like [this](https://github.com/knadh/listmonk/issues/391#issuecomment-917637156).
