### ISSUE TITLE
Error sending test: 550 I cannot deliver mail for some email

### ISSUE THREAD

**Issue by Archer-Thane** [knadh/listmonk#32]
Hey there! Great work on this project!
I installed the app based on the description you have been provided.
I run email service using [poste](https://poste.io/). I almost not touched the config they provided. (smtp was run on port 25)
so on the config.toml, on the smtp part there are two fields which needed to complete. This is my config:
`
[smtp]
    [smtp.my0]
        enabled = true
        host = "aalimoshaver.com"
        port = "25"

        # cram or plain.
        auth_protocol = "plain"
        username = "aalibash"
        password = "somepassword 😉"

        # Maximum time (milliseconds) to wait per e-mail push.
        send_timeout = 5000

        # Maximum concurrent connections to the SMTP server.
        max_conns = 10

    [smtp.postal]
        enabled = true
        host = "aalimoshaver.com"
        port = "25"

        # cram or plain.
        auth_protocol = "plain"
        username = "aalibash"
        password = "somepassword 😉"

        # Maximum time (milliseconds) to wait per e-mail push.
        send_timeout = 5000

        # Maximum concurrent connections to the SMTP server.
        max_conns = 10
`
when I try to test with `Send test messages` in campaign part, I see this error:
`Error sending test: 550 I cannot deliver mail for someRealEmail.`
I also used thunder bird to check remote connection of my mail server, poste. But that was fine. from there for the Outgoing part, It shows me these: 
SMTP (protocol) - smtp.aalimoshaver.com (Server hostname) - 25 (port) - STARTTLS (SSL) - Normal Password (Authentication)
Can you help me fix this out?
Many thanks!
I also thought to contribute to this project as a developer. I can help you out, specially on the templating part. 
Thanks again!

**Comment by knadh** [comment]
Looks like your SMTP server is explicitly blocking e-mails (error 550). Possibly some whitelist / blacklist / spam configuration that you'll need to look at.

**Comment by Archer-Thane** [comment]
Thanks for your response 
After some time and ip of server to whitelist, I encounter with a new error:
Error sending test: EOF
What does this mean?

**Comment by knadh** [comment]
`EOF` would mean that listmonk's connection to the SMTP server is closed or reset. Have you tried restarting?

**Comment by Archer-Thane** [comment]
Thanks for your help knadh.
So if anyone wants to use poste as mailserver, here is how to integrate listmonk to poste:
1- login to admin dashboard of poste
2- go to 'system settings'
3- in the 'Relay networks' part, add this as the ip: 172.17.0.1
done.
Many Thanks to knadh for his help. without his kindness I never could solve the issue.
