### ISSUE TITLE
[API] Adding a user to Double opt-in list without additional email confirmation

### ISSUE THREAD

**Issue by marcinkunert** [knadh/listmonk#320]
I've got the following scenarios:

1. User fills a newsletter form on my website to 
2. User registers to my website and gives consent p

The 1 scenario is pretty straightforward: `POST /api/subscribers` can be used to add the user to a desired list, the user gets an opt-in email, confirms it and done. (one thing to consider if he was already subscribed, and updating it, but I guess it can be done with a few more requests)

The 2nd one on the other hand is a bit tricky. I don't want to send a confirmation email, the user already confirmed that he wants to get the newsletter. I could theoretically connect directly to the database and change data in `subscriber_lists` table (as the author of [this article](https://yasoob.me/posts/setting-up-listmonk-opensource-newsletter-mailing/) has done). 

Other option would be to use the single opt-in list, but what about scenario 1, where I want to get a confirmation?

So my question is what are my options here? Maybe there is an undocumented API I could use?

If not, is there an option to add additional parameters for `POST /api/subscribers` in order to mark the subscription as confirmed?

**Comment by knadh** [comment]
This sounds like a scenario that can be commonplace.

> If not, is there an option to add additional parameters for POST /api/subscribers in order to mark the subscription as confirmed?

Doesn't exist, but seems trivial enough to implement. Looking into this.

**Comment by knadh** [comment]
This is added: https://github.com/knadh/listmonk/commit/ad0a0e0841c33d04cc295fb0b9569e5db7a8a225

Sending `preconfirm_subscriptions: true` in the JSON request body to `POST /api/subscribers` marks all subscriptions in the request as `confirmed` and skips the opt-in e-mail for double opt-in lists.

**Comment by marcinkunert** [comment]
@knadh thanks a lot!
