### ISSUE TITLE
Support merging attributes during import

### ISSUE THREAD

**Issue by tamalsaha** [knadh/listmonk#325]
It will be great if the attributes could be merged by default instead of ignoring or overwriting. https://pkg.go.dev/github.com/imdario/mergo could be handy library to implement such feature. But I see that this is done at the [sql level](https://github.com/knadh/listmonk/blob/33450f86bbdae88dc255793d0c89abb3f1c14f08/queries.sql#L90). So, I am not sure what is the best way to do this.

**Comment by knadh** [comment]
It's possible to do it in SQL with the `||` notation: `attribs || $1`. However, this'll need changes on the UI to give an option to merge.

**Comment by Libermentix** [comment]
Is this still on the roadmap? Or otherwise said, is there anything that can be done to support?

**Comment by knadh** [comment]
Hi @Libermentix. I haven't had a chance to look at this yet, but I'll try to look at this soon. If you are able to propose a PR in the meanwhile, that's welcome.

**Comment by devinellis** [comment]
Just to confirm, this is the reason a `POST /api/subscribers/` to an existing email address seems to update name, email, lists, but will not update attribs? I wasn't expecting that, but I can simply query for the email address first and do a `PUT` instead.
