### ISSUE TITLE
Does not delete user

### ISSUE THREAD

**Issue by firefiesta** [knadh/listmonk#328]
I'm trying to delete a user using the 2 versions of DELETE subscriber, but neither delete the user. I launch the request from my own server. The create user (subscriber) works correctly.

The answer is {data: true} but it doesn't remove it. From within the panel, launch the same request to DELETE api / subscriber /: id and everything is correct.

The http requests are DELETE with subscribers /: id and subscribers? Id =: id but neither actually delete the user.

I have the latest version of listmonk.
I do not know if any extra data is needed.

**Comment by knadh** [comment]
```shell
curl -X DELETE "http://localhost:9000/api/subscribers/1"
```

This works as expected. This is the same request that the UI sends. Can you share the full request you're trying?

**Comment by firefiesta** [comment]
I using Guzzle for Laravel.

$delete = $this->client->request('DELETE', config('app.listmonk_api_url') . 'subscribers/' . $user->id );

**Comment by knadh** [comment]
This looks fine, hm. The only thing I can think of is `$user->id` somehow not being the correct subscriber ID. Can you verify that?

**Comment by firefiesta** [comment]
The `$user->id` in panel is 171 and the `$user->id` in request is the same.

I don't know if a specific header is needed or something else in particular.
But as I say, the response is `{data: true}`

The request is made from my own API server to my Listmonk server as in the following example (differents servers):
`DELETE https://username:username@myserverlistmonk.com/api/subscribers/171`

**Comment by knadh** [comment]
There are no additional headers or params involved apart from basic auth if its enabled.

```shell
curl -X DELETE "http://listmonk:listmonk@localhost:9000/api/subscribers/1"
```
^ This exact request works on my local setup. Just to be sure:

- Can you make the request from within the server where listmonk is installed?
- Are the responses being cached somehow? Have you checked in the DB if the record is actually getting deleted.

Unless there is an SQL error, the response will always be `true`, even if you try an ID that doesn't exist.

**Comment by firefiesta** [comment]
I have launched the command from the listmonk server and everything has gone well, it has deleted the user.

I have tried to launch by curl command from another machine and it has also worked.

Now, I have launched from code, the curl command, both using the Guzzle library and basic curl with DELETE request and the response is {data: true} but it does not eliminate it.

I do not know if it must be due to some type of header, or extra data, I am sorry to repeat myself, but seeing the data of the curl request by command is the following:

`* TCP_NODELAY set
* Connected to xxxxxxx (xxx.xx.xx.xxx) port 443 (# 0)
* ALPN, offering h2
* ALPN, offering http / 1.1
* successfully set certificate verify locations:
* CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: / etc / ssl / certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http / 1.1
* Server certificate:
* subject: CN = myserver.com
* start date: Feb 21 07:04:00 2021 GMT
* expire date: May 22 07:04:00 2021 GMT
* subjectAltName: host "myserver.com" matched cert's "myserver.com"
* issuer: C = US; O = Let's Encrypt; CN = R3
* SSL certificate verify ok.
* Server auth using Basic with user 'listmonk'
> DELETE / api / subscribers / 2 HTTP / 1.1
> Host: myserver.com
> Authorization: Basic bGlzdG1vbms6SHpqOVlBcjRnNUhRSUl3Vw ==
> User-Agent: curl / 7.68.0
> Accept: * / *
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
<HTTP / 1.1 200 OK
<Date: Wed, 21 Apr 2021 12:25:10 GMT
<Server: Apache / 2.4.41 (Ubuntu)
<Content-Type: application / json; charset = UTF-8
<Content-Length: 14
<Access-Control-Allow-Origin: *`

You check User-Agent or any field ?

**Comment by firefiesta** [comment]
I have already found the error. It is from headers, but from my API server.

Thank you very much for everything and for your time.
