### ISSUE TITLE
Port 465 is not supported

### ISSUE THREAD

**Issue by HLFH** [knadh/listmonk#33]
Hi,

[RFC 8314](http://www.rfc-editor.org/rfc/rfc8314.html#section-3.3) recommends to use port 465 for SMTP Submission. And if I set port 465 in `config.toml`, I will get:

> ⇨ http server started on [::]:9000
2019/11/08 10:55:21 manager.go:166: start processing campaign (Test campaign)
2019/11/08 10:55:21 manager.go:349: campaign (Test campaign) finished
2019/11/08 10:55:26 manager.go:243: error sending message in campaign Test campaign: timed out
2019/11/08 10:55:26 notifications.go:28: error sending admin notification (Finished: Test campaign): timed out

Many thanks,
HLFH

**Comment by knadh** [comment]
>  2019/11/08 10:55:26 manager.go:243: error sending message in campaign Test campaign: **timed out**

Can you check your firewall rules? Looks like the connection to your SMTP host is timing out.

**Comment by HLFH** [comment]
My SMTP host is not timing out.

> openssl s_client -showcerts -connect arch-server.dhautefeuille.eu:465
