### ISSUE TITLE
Problem editing campaign content (plain text)

### ISSUE THREAD

**Issue by dronir** [knadh/listmonk#335]
I find my campaign body text "freezes" in the editor, so that it can never be changed again.

This is in the current Docker `latest` version, set up according to the "production" instructions with Docker-compose. I did not test this in other modes except plain text.

## Steps to replicate

I find these steps replicate the problem at least on my setup:

1. Create a new campaign.
2. Enter some campaign text in the plain text mode and click **Save changes**.
3. Navigate away from the Campaign view and back.
4. Edit the campaign text and click **Save changes** again. 
5. Navigate away and back again.
6. See that the campaign text has reverted to the version from step 2. 

Nothing I have tried makes edits persist in the campaign text body after this.

Also, immediately after step 4:

- The **Preview** button shows the message with the new text, but:
- The **Send test message** button sends out a message with the old text from step 2.

**Comment by knadh** [comment]
I was able to reproduce this issue following the steps you described in `v0.9.0`. In the current `master` that's slated for release, this bug is fixed.

**Comment by dronir** [comment]
Good to know, thanks. I'll wait for the next release.

**Comment by knadh** [comment]
Closing this. This issue was resolved in https://github.com/knadh/listmonk/commit/1e59d53135f1708e08e91e535b8555b5b45343ce.
