### ISSUE TITLE
Blacklist disposable email domains

### ISSUE THREAD

**Issue by Donatzsky** [knadh/listmonk#336]
An option to prevent email addresses on certain domains from signing up would be useful. There are a lot of disposable email providers out there, and being able to blacklist them could help with cutting down bounce rates.

An option to automatically fetch the list from somewhere would be great, but to begin with a simple form to paste the list into would do the job.

https://github.com/disposable-email-domains/disposable-email-domains
https://www.block-disposable-email.com/cms/

**Comment by knadh** [comment]
> but to begin with a simple form to paste the list into would do the job.

+1
