### ISSUE TITLE
Error: nested MAIL command

### ISSUE THREAD

**Issue by Donatzsky** [knadh/listmonk#337]
I tried to send a test campaign, and got the following error:

```
2021/04/26 17:53:06 start processing campaign (Test campaign)
2021/04/26 17:53:06 campaign (Test campaign) finished
2021/04/26 17:53:07 error sending message in campaign Test campaign: subscriber 1eac130c-7007-42b3-b721-e84dd9d1d3c0: 503 5.5.1 Error: nested MAIL command
2021/04/26 17:53:07 error sending message in campaign Test campaign: subscriber 398e30c1-a2bb-4e42-bf02-d9b18c56feb6: 503 5.5.1 Error: nested MAIL command
2021/04/26 17:53:07 error sending message in campaign Test campaign: subscriber eec6c72c-f765-49e7-a299-9619ca23fa0c: 503 5.5.1 Error: nested MAIL command
2021/04/26 17:53:07 error sending message in campaign Test campaign: subscriber 80c83735-c1f0-44e8-ac5e-ea0461058a9f: 503 5.5.1 Error: nested MAIL command
2021/04/26 17:53:08 error sending message in campaign Test campaign: subscriber 4009e6b7-aeac-41b8-abe3-9b82920a50ef: 503 5.5.1 Error: nested MAIL command
```

Curiously, `1eac130c-7007-42b3-b721-e84dd9d1d3c0` did receive the message, but the others didn't.

**Comment by knadh** [comment]
`nested MAIL command`, never seen this. What SMTP server are you using? Could you also share the settings used?

**Comment by Donatzsky** [comment]
I forgot to mention that under the campaign, it says `Sent: 5/5`. Clearly there needs to be some better error handling.

I believe the server is Postfix. Currently trying to see if my host can tell me more.

Is there a more verbose logging option? That could help in resolving issues such as this.

**Comment by knadh** [comment]
`Sent` indicates the number of messages that were pushed into the sending queue. Errors are tracked separately. Unfortunately, there's no verbose logging that's easily possible. The message you're seeing is returned by the SMTP lib which is reponsible for pushing the e-mail to the upstream SMTP server.

Surprisingly, there are only [~900 results](https://www.google.com/search?q=%22nested+MAIL+command%22) on Google for this error message!

**Comment by Donatzsky** [comment]
> `Sent` indicates the number of messages that were pushed into the sending queue. Errors are tracked separately.

There should probably be an error count then. It's easy to forget to look at the log.

The host didn't have anything in their logs that could help. I've since run the exact same test campaign twice, and didn't have any issues with either. So I guess for now this should be filed under ¯\_(ツ)_/¯

**Comment by Sohib** [comment]
Anyone got a solution for this? i am getting this error with postfix. 

`2021/06/30 16:51:26error sending message in campaign Test Campign: subscriber 1bf0a106-0849-498c-af39-012cbd70fe6d: 503 5.5.1 Error: nested MAIL command`

**Comment by SuaYoo** [comment]
I'm getting `Error: nested MAIL command.` only from automated opt-in list confirmation emails. Manually sending emails to test a campaign works.

I see `loaded email (SMTP) messenger` in the logs. TLS enabled on port 587.

**Comment by janwni** [comment]
I can confirm. I have the same issue when I try to send confirmation mails to opt-in lists.

I use the mail server of my provider. SMTP seems to be Postfix.

**Comment by janwni** [comment]
I think I've found the mistake. I set the wrong default "from" address in the settings. This wasn't a problem for normal campaigns, because there I always entered the correct address.

**Comment by IAkumaI** [comment]
Have same problem.
Listmong says "nested MAIL command" for much subscribers. But I event can't find this emails in postfix logs. It's just like listmonk even didn't sent this emails to postfix.
Any solution?

**Comment by jeff-h** [comment]
Since v2.3.0 I'm also getting this. My Listmonk logs are full of entries such as `2022/12/10 01:03:57 error sending message 'Confirm subscription': 503 5.5.1 Error: nested MAIL command`. Nobody has been able to confirm their subscription as a result. I also am unable to send test emails, through "Settings > SMTP" nor through "Campaign > Send test message", each of which throw a similar `nested MAIL` error.

I have to get a newsletter out, so fortunately I was able to roll my docker compose back to `v2.2.0` and it works perfectly again.

I'd be very keen to help debug this in any way I can. Is it possible to view the raw message that `smtppool` is emitting? I am using the SMTP provided by my Mail-in-a-box server, and it's been working beautifully till now. @knadh I'd be more than happy to set up a test account for you on my MIAB if that would be useful.

**Comment by knadh** [comment]
@jeff-h

**Comment by knadh** [comment]
@jeff-h that is strange. There is no change in the SMTP lib internals between v2.2.0 and v2.3.0 which could cause something like this. If you could share test credentials with me at kailash [at] nadh.in, I'll try and debug this locally.

Just to be sure, when you encountered this issue with v2.3.0, restarting listmonk didn't help?

**Comment by jeff-h** [comment]
Whilst I can guarantee it didn't work after the 2.3.0 upgrade, and that it does now work after reverting to 2.2.0, I would like to send out my newsletter (hopefully tomorrow) and then re-upgrade to 2.3.0 and confirm it is again broken as expected. 

When trying to fix things originally, I did restart 2.3.0 several times without any apparent success.

I also have a second Listmonk instance which I haven't been using so I will check that too.

@knadh thanks as always for your incredible work on Listmonk and willingness to try to sort out the edge-case problems!

**Comment by knadh** [comment]
Figured out (finally!) and fixed the issue in the underlying smtp-pool lib. https://github.com/knadh/listmonk/commit/274d86422c5d44fe393d80b5bad6f19fb442fb66.

**Comment by IAkumaI** [comment]
Great! Is release coming?

**Comment by jorge-vitrubio** [comment]
Hello
any idea how to solve this? where to look at?

I came out with 67 errors from subscribers having this issue on a list of more than 5000 email addresses.

I did try to look for a pattern in my side, but I wasn't able. All of them are confirmed in the list from where mail is being sent.

This error didn't happen two weeks ago with the same version, currently using listmonk v 2.5.1

**Comment by krzysztofgal** [comment]
I got this `nested MAIL command` error when SMTP `HELO hosname` wasn't set.

**Comment by jorge-vitrubio** [comment]
> I got this `nested MAIL command` error when SMTP `HELO hostname` wasn't set.

thanks, I'll try it and let you know

**Comment by SKJoy** [comment]
Has anyone been able to figure the issue out? I have From defined in the SMTP custom header, and my mail server needs that. The From in SMTP server configuration will always overwrite the From in the Campaign settings, right?
