### ISSUE TITLE
Can't build under nodejs 16

### ISSUE THREAD

**Issue by alerque** [knadh/listmonk#339]
Given my issues with the prebuilt binary (#338) I decided to try setting up the resources for a `--static-dir`. That requires building the frontend, so down the rabbit hole I went.

I tried first with my system's `node`, which is 16.1.0. That blew up in my face, node_gyp couldn't compile something or other. I switched to building in a clean chroot with 14.16.0 instead and that went fine.

It looks like something in the node-sass dependency is holding this back from compiling on current versions.

**Comment by mr-karan** [comment]
>It looks like something in the node-sass dependency is holding this back from compiling on current versions.

https://github.com/sass/node-sass/issues/3077

**Comment by knadh** [comment]
Looks like node-sass now supports Node 16: https://github.com/sass/node-sass/pull/3090

**Comment by alerque** [comment]
Hmm, thanks for the news and you seem to be correct...

However this isn't *quite* fixed for Listmonk because the package currently calls for a v4.x dependency  and the fixes you link to are only in v6.0.0 upstream. Listmonk will not build properly until this is updated:

```json
{
  "dependencies": {
    "node-sass": "^4.14.1"
  }
}
```

I tried bumping just this dependency, but it's not quite that simple. The `sass-loader` dependency is also several major versions behind, and bumping that causes build errors.

**Comment by knadh** [comment]
Ouch. I just spent a couple hours investigating this which turned out to be a rabbit hole. Tracking this here: https://github.com/knadh/listmonk/issues/369

**Comment by knadh** [comment]
Merged: https://github.com/knadh/listmonk/pull/371/files

@alerque could you check if it compiles on Node 16 now? I don't have 16.

**Comment by mr-karan** [comment]
I'm running `v16.2.0`. It builds fine :) 

```
$ make deps
$ make build-frontend

...
 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
   
Done in 36.33s.
```

**Comment by alerque** [comment]
I can confirm too, I just successfully built from Git HEAD in a clean chroot system with Node 16.2.0 an Arch Linux.

**Comment by thebarefootdev** [comment]
On mac Catalina with Node 16, there are still issues with node-sass via npm install. Is there any progress on this as a stable update?

**Comment by alerque** [comment]
@thebarefootdev You realize that these fixes are not in any released version yet, they only work for building the Git HEAD from the `master` branch, right?

**Comment by thebarefootdev** [comment]
@alerque Is that a question or sarcasm?

Assuming it's a question, then no, I didn't realize, I'm not involved on npm modules to that level. Apologies for not being in the know 😉

**Comment by alerque** [comment]
Just a question, not sarcasm. The issue here is closed because the change has been made in the master branch. You can checkout and build from a clone, but not from the last released version yet which was released before this fix.

**Comment by knadh** [comment]
> On mac Catalina with Node 16, there are still issues with node-sass via npm install.

Are you pulling `master` and then trying to install? Like @alerque said, this has been fixed and merged into master.
