### ISSUE TITLE
Please add a flag / config option to not "phone home"

### ISSUE THREAD

**Issue by alerque** [knadh/listmonk#344]
The current builds have a system that is phoning home at run time by calling out to a remote API to check for updates. This should be disclosed (at least in documentation) and a config file option should be added to completely disable the checks.

Besides being a privacy concern and potentially a network security concern, the data can also be wrong. If people are using distro packages, whether they are up to date with their distro is more relevant than whether there has been an upstream release. As noted in #343 it's even possible for the running version to be *newer* than the upstream release.

**Comment by knadh** [comment]
Already planned here https://github.com/knadh/listmonk/issues/326.

**Comment by alerque** [comment]
Sorry, missed the duplicate issue.
