### ISSUE TITLE
Document public vs. private paths

### ISSUE THREAD

**Issue by alerque** [knadh/listmonk#345]
I'm running Listmonk behind an Apache proxy server that handles authentication against a central system (in my case Keycloak via OIDC, but the details are not relevant here). Hence I've disabled the internal HTTP auth mechanism guarding admin endpoints. I see from #286 that others such as @NicolaiSchmid, @xplosionmind, and undoubtedly others are doing something similar. What I didn't find is any documentation about doing this securely.

There should be some documentation identifying what endpoints are admin and should be secured vs. which are user facing and should be public.

By trial and error I came up with the arrangement of authenticating everything, then allowing access to three directories:

```apache
	<Location />
		AuthName "Listmonk"
		AuthType openid-connect
		Require valid-user
		ProxyPass http://127.0.0.1:9000/
		ProxyPassReverse http://127.0.0.1:9000/
		ProxyPassReverseCookieDomain 127.0.0.1 listmonk.example.com
	</Location>

	<Location /subscription/>
		Require all granted
	</Location>

	<Location /public/>
		Require all granted
	</Location>

	<Location /uploads/>
		Require all granted
	</Location>
```

Are there other endpoints besides `/subscription/`, `/public/`, and `/uploads/` that should be public? Is there anything under those endpoints that should actually be secured?

**Comment by knadh** [comment]
Yep, this should be in the docs.

The public handlers defined [here](https://github.com/knadh/listmonk/blob/68b80d0eb603d6e747284a29540cb0792911cad9/cmd/handlers.go#L135) are public. Nothing under these paths need to be secured.

- `/subscription/*`
- `/link/*`
- `/campaign/*`
- `/public/*`

And whatever media directory if you are using it.

**Comment by alerque** [comment]
Thanks for the list. Given that info (and for the sake of anybody else finding this issue in search) a more secure list that above might look like this for Apache:

```apache
<Location />
	AuthName "Listmonk"
	AuthType basic
	Require valid-user
	ProxyPass http://127.0.0.1:9000/
	ProxyPassReverse http://127.0.0.1:9000/
	ProxyPassReverseCookieDomain 127.0.0.1 listmonk.alerque.com
</Location>

<LocationMatch "^/(subscription|link|campaign|public|upload)/">
	Require all granted
</Location>
```

Note: this assumes the media folder is configured as `/upload`.

Note: When using matches like this instead of plain Location directives it is important to match `^`, otherwise a malicious link or upload may be able to break the security and get through to unintended endpoints.

----

Also for consideration in a future version, it would be a lot easier to secure if the default domain landing page and `/` namespace was public and all the admin-only end points were lumped under `/admin` or similar! Having public endpoints nested under private secured ones is backwards, confusing, and an easy way to accidentally expose things that shouldn't be exposed.

**Comment by alerque** [comment]
Would a sample Apache virtual host config file be accepted if I put one together? I will probably inject one into the Arch Linux packages (it's pretty traditional to do for services that are frequently put behind a proxy)? Along the same lines, how about SystemD service configs? I already provide those in the packages as well.

**Comment by knadh** [comment]
> Would a sample Apache virtual host config file be accepted if I put one together? I will probably inject one into the Arch Linux packages (it's pretty traditional to do for services that are frequently put behind a proxy)? Along the same lines, how about SystemD service configs? I already provide those in the packages as well.

Sure. This can be added to the [docs](https://listmonk.app/docs) as examples under the `Configuration` section. You can send a PR on the [docs repo](https://github.com/knadh/listmonk-site).

**Comment by alerque** [comment]
Documentation is fine and good too, but actually for the purposes of distro packages actual code in the form of example config files (often with `.example` or `.sample`) are what would get packages and put in the distro specific location where such things are expected.

**Comment by knadh** [comment]
Documented public paths in docs: https://github.com/knadh/listmonk-site/commit/37900bcfa420724081ed2cf622372194701feeb9
