### ISSUE TITLE
Convert existing content when switching input formats

### ISSUE THREAD

**Issue by alerque** [knadh/listmonk#348]
The current selection of Richtext/RAW/Markdown/Plain is cool and it is good that it warns about data loss, but I think it should be relatively "easy" to do better. After all Listmonk is already rendering all of these formats to a common target for actual use in sending emails (and previews). It should be possible to use the same mechanisms to convert between some formats.

1. A "revert" vs "continue" action being available right after switching formats (after you can see the difference but before you can continue editing) might be a better UX than the current warning that something might go wrong but no way to get back if it does.

1. There should be no warning between Richtext⋄RAW — if that switch is loosing data then something is *wrong* and it should be treated as a bug.

1. Conversion from anything→Plain text should keep the warning, but use the existing plain text message generated to "downsample" the message into something intelligent.

1. Conversion from Markdown→Richtext or RAW should be lossless. If it is not then that is a bug because that conversion is happening on send anyway. The Markdown message should be fed through the same `goldmark.Convert()` used in the final output, replacing the content with the resulting HTML.

1. Conversion from Richtext or RAW → Markdown may continue to be lossy and warn, but it should use an HTML→Markdown renderer. This will inevitably loose some info, but special care could be taken to pass through the templating language tokens and use RAW inline HTML links instead of markdown links so that attributes like classes are not lost. This would obviously be the most involved feature upgrade, but worth at least mentioning.

   - As a "poor man’s" temporary solution to mitigate not actually having a full featured HTML→Markdown conversion library, at the very least raw HTML should be allowed in the Markdown format. There are other uses for this as well, see #347. With inline HTML allowed it should be possible to convert HTML→Markdown without much loss.

**Comment by knadh** [comment]
> A "revert" vs "continue" action being available right after switching formats (after you can see the difference but before you can continue editing) might be a better UX than the current warning that something might go wrong but no way to get back if it does.

+1. This can be built on the frontend.

> There should be no warning between Richtext⋄RAW — if that switch is loosing data then something is wrong and it should be treated as a bug.

WYSIWYG editors in browsers are erratic and inconsistent across browsers. The conversion from richtext to raw HTML may be different between browsers and what you saw in the visual editor might not be exactly what you get when it's automatically converted to HTML. This warning should stay.

> Conversion from anything→Plain text should keep the warning, but use the existing plain text message generated to "downsample" the message into something intelligent.

+1. This can be built on the frontend.

> Conversion from Markdown→Richtext or RAW should be lossless. 

+1

> Co version from Richtext or RAW → Markdown may continue to be lossy and warn, but it should use an HTML→Markdown renderer.

Yep, will explore if there is a straight forward way of converting HTML to markdown.

**Comment by alerque** [comment]
> > Conversion from Richtext or RAW → Markdown may continue to be lossy and warn, but it should use an HTML→Markdown renderer.
> 
> Yep, will explore if there is a straight forward way of converting HTML to markdown.

Nothing is straight forward about converting a complex and infinitely tweakable markup language into Markdown. Inevitably this will be problematic and it may or may not be worth somebody's time to develop it. If you do start down the road (having been down it many times), I suggest first finding anything custom that you want to keep such as the allowed templating tags and converting them to plain text tokens, then doing the conversion, then replacing the tokens. This will keep the edge cases where the conversion breaks something to a minimum. This would also be useful for other conversions as well (Markdown → Richtext for example). You don't want anything trying to escape characters or re-encode URLs or do other monkey business inside your template tags.

That plus a converter that understands trickier conversions like link attributes *OR* knew to pass through inline HTML for anything it didn't understand should make for a 95%+ solution.

Pandoc would be ideal for this as by far the most mature and advanced conversion system out there, but I don't think interfacing to it from Golang would be much fun — unless there is some wrapper library I don't know about.

**Comment by alerque** [comment]
Thanks! I just reviewed the commit and will go test drive it in a bit, but it looks like that will be a big improvement.
