### ISSUE TITLE
Delete campaign

### ISSUE THREAD

**Issue by HLFH** [knadh/listmonk#35]
Hello,

In `All campaigns` tab, I have listed 18 test campaigns. I would like to delete them.
How to do that?
Can you please support it in the WebUI?

Thanks,
HLFH

**Comment by knadh** [comment]
Only draft campaigns can be deleted (there's a delete icon on the right side). Finished campaigns remain (audit trail). If you really need to delete them, you can delete them from the PostgresDB, eg: ```DELETE from campaigns where status='finished' CASCADE';```
