### ISSUE TITLE
AGPL is a shame

### ISSUE THREAD

**Issue by mysticaltech** [knadh/listmonk#358]
Such an amazing-looking piece of software, and you chose such a restrictive license. It just makes it unusable. If I want to use listmonk in my stack, I have to open-source my whole work? No way. What a shame really!

**Comment by knadh** [comment]
_"AGPL is a shame"_ is a strange sentiment, and looks like you've misunderstood the license as well. Nowhere does it say that your entire stack should be open sourced.

In simple terms, if you use listmonk unmodified (which would be 99% of the usecases), you needn't do anything. If you modify listmonk, you've to open source those modifications and whatever scaffolding is necessary for those modifications to work.

**Comment by alerque** [comment]
The aGPL license is a great choice for open-sourcing software that runs as network-accessed service like this. Nobody says anything about "your whole stack", but it does prohibit you making changes to listmonk itself, reselling a service based on those modifications, and not sharing the modifications. You can still sell a service, but you have to share any improvements you make to listmonk itself (not your whole stack).

Some large corporations are "alergic" to the aGPL license. I'm looking at you Google (that has a blanket ban on their employees touching anything aGPL based even in cases where they are not modifying it at all) and Amazon (which has a long standing habit of hosting modified OSS projects and charging for them as SAAS without contributing their fixes upstream). I say that's their problem and they should get their own acts cleaned up. The aGPL is doing its job.

**Comment by mysticaltech** [comment]
Ok, great explanations folks, now I see the subtle nuances. So in my case, I sure do not need to modify it, and even if I did, I would gladly share the code of my variant. So in that new light, it's definitely safe to use. 

You have just opened the whole AGPL universe to me (it was my ignorance that was a shame), thank you! 🙏
