### ISSUE TITLE
Subscription form

### ISSUE THREAD

**Issue by HLFH** [knadh/listmonk#36]
We need a subscription form

**Comment by knadh** [comment]
This is on the to-do.

For now, it should be easy to create a form that inserts a subscriber using the listmonk /api/subscribers API.

**Comment by mdehollander** [comment]
+1

The api is not a public endpoint, so how would this work in combination with a subscription form?

**Comment by knadh** [comment]
Re-opening the issue. Working on this.

**Comment by mdehollander** [comment]
Good to hear this is on the roadmap. What is the current status?

**Comment by knadh** [comment]
I've just started working on this. Hopefully sometime next week.

**Comment by knadh** [comment]
[v0.5.0-alpha](https://github.com/knadh/listmonk/releases/tag/v0.5.0-alpha) supports forms.

**Comment by mdehollander** [comment]
Thanks! I will give it a try later this week.
