### ISSUE TITLE
No unsubscribe headers

### ISSUE THREAD

**Issue by alerque** [knadh/listmonk#360]
Settings → Settings → Privacy → Include \`List-Unsubscribe\` header

...does nothing. No headers are added to outgoing messages.

I can add headers manually through the SMTP settings, but the above feature seems to do nothing.

**Comment by alerque** [comment]
Semi duplicate of #208, but the behavior is either wrong or at least should be prominently documented next to the setting.

Headers do go out but not on optin campaigns and not on test messages. What's the point in test messages if they don't actually test what things will look like when the campaign runs for real?

**Comment by knadh** [comment]
hm yeah, this was missed. Test messages are handled by an entirely different routine which doesn't do the header attachment. This needs some work.

**Comment by alerque** [comment]
The test messages should go through as much of the regular plumbing as possible. After a week or two fiddling with things I ran a big campaign last night and ran into several glitches that should have been caught by the dozens of tests I ran but weren't.

**Comment by knadh** [comment]
> should have been caught by the dozens of tests I ran but weren't

What were those? The only thing that's different between the test message and an actual campaign message is the list unsub header. There is no difference in the way messages are rendered in test and in an actual campaign.

**Comment by alerque** [comment]
> There is no difference in the way messages are rendered in test and in an actual campaign.

I thought from my use that there is a difference in the way templates are escaped. I have some notes to test and file issues on if I can isolate what happened.

The other one is that sending test messages (even several at once) does not seem to batch them in the same thread talking to the SMTP daemon. It turns out any batching at all can be subject to different outgoing rules that one-off messages.
