### ISSUE TITLE
Toggle option to send (or not send) optin messages on signup

### ISSUE THREAD

**Issue by alerque** [knadh/listmonk#363]
Through trial and error I finally deduced that the expected behavior is:

- Users that sign themselves up plus those added via the "add" popup display in the app are immediately send an opt-in confirmation message.

- Users that are added via CSV import are not. These must be sent manually via an optin campaign.

- There is no difference in the database between an unconfirmed user that has been sent an optin message already and one that has not. Those added individually and sent messages right away are mixed in with imports that have not been sent messages.

This isn't a bad default behavior, but it is unclear, undocumented, and inflexible.

I suggest three changes:

1. Document for both use cases in the admin interface when additions / imports are going to send optin messages.

1. Split the "unconfirmed" flags into two groups, those that haven't responded to the confirmation notices and those that haven't been sent them.

1. Allow a toggle on both methods to send or not send confirmations immediately. I may want to import several CSV users and go ahead and send them optin confirmations after import, or I may want to add some one by one via the form and not send them notices yet (to group them with the next optin campaign message).

**Comment by henk23** [comment]
+1 for the third suggestion: When doing administration, like manually adding contacts to lists or manually moving contacts around between lists, I would like to do that without triggering the opt-in mail every time.

I have zero knowledge in Go, but can offer my help in Vue.js :)
