### ISSUE TITLE
API Lists documentation

### ISSUE THREAD

**Issue by jcparant** [knadh/listmonk#367]
Hi,

I'm work with API on one script for one Google Sheet and in the endpoint POST /api/lists, there is missed the required parameter "optin".

Can you add it for the other users.

Documentation : https://listmonk.app/docs/apis/lists/

TY!

[Screenshot_7](https://user-images.githubusercontent.com/1880969/119156679-c16b8380-ba54-11eb-8e91-1854a1fcf0b7.jpg)

**Comment by knadh** [comment]
Thanks for pointing this out. It's done: https://github.com/knadh/listmonk-site/commit/2eb318dc1c88b75febf7ff754dd02a5ed64dd8dd
