### ISSUE TITLE
SQLite Support

### ISSUE THREAD

**Issue by maxhawkins** [knadh/listmonk#368]
Any plans to support SQLite?

I don't currently run Postgres on my tiny VPS and would prefer to use a lightweight database like SQLite.

I saw in a previous issue you don't plan to support alternative databases while the app is in beta. Now that you've hit 1.0 are there any plans to change that?

SQLite might be a good choice because it will be easier for people to get up and running with the standalone binary even if they don't have a database server handy.

**Comment by knadh** [comment]
No plans right now, @maxhawkins. 90% of the [SQL queries](https://github.com/knadh/listmonk/blob/master/queries.sql) would be easy to port, but the rest would be extremely hard. And, listmonk relies heavily on these queries for executing app logic.

That said, I've a personal 2 vCPU VPS instance on which I run Postgres that handles hundreds of queries per second on tables with a few million rows, serving user traffic alongside a bunch of other applications. It runs fine. In addition, listmonk is very light on resources including DB usage, so you should be able to get away with it. Of course, cannot compare to SQLite!

**Comment by maxhawkins** [comment]
Yeah, Postgres / using the API probably makes the most sense. It's nice having your database as a single file but running another server isn't too bad. My other applications run on SQLite so I was hoping I could do joins across the mailing list and another application's data store but I understand wanting to only support a single dialect.

I did take a look at the queries earlier today to see if it would be easy to implement a SQLite driver myself. At first glance, with the exception of the list types, it looked like everything would translate easily. It may be possible to emulate the missing list types with SQLite's json support.

Where I ran into trouble was with the Postgres-specific pq.*Array types passed as parameters elsewhere in the code. It seemed like fixing that would add a lot of extra abstraction so I stopped. I can post the SQLite-compatible translation of the schema I made if that would be helpful at all.

**Comment by knadh** [comment]
> I can post the SQLite-compatible translation of the schema I made if that would be helpful at all.

That would indeed be useful.

> At first glance, with the exception of the list types, it looked like everything would translate easily.

List and JSON types are used heavily, and there are other things like the `UNNEST()`, `COUNT(*) OVER()` which SQLite doesn't seem to support.

To support multiple DB backends, all query execution will have to be abstracted into functions on an interface. Some logic might end up moving into app code too. This is not necessarily bad, but some important considerations off the top of my head:

- The added effort of maintaining and testing multiple DB backends for all DB related features and changes may be significant. This will be non-trivial upfront and ongoing work.
- List segmentation with SQL-expressions is a documented user facing feature that uses the Postgres JSON syntax. With multiple DB backends, the nature of this feature changes.
- These arbitrary SQL expressions are executed in a readonly Postgres transaction. Not sure how this can be achieved in SQLite.
- Slightly tantential, referring to the old issue https://github.com/knadh/listmonk/issues/60, MariaDB 8 has the JSON data type.

All that said, if feasible at all, I would personally vote for the addition of SQLite as an additional backend which makes listmonk truly self-contained and standalone, over another networked database server such as MariaDB.

**Comment by maxhawkins** [comment]
> That would indeed be useful.

https://gist.github.com/maxhawkins/6093f597a510b679d59b7f7b6bbb22e4

The main thing I had to do was convert the custom datatypes into `CHECK()` constraints and use SQLite-compatible timestamp functions.

> List and JSON types are used heavily, and there are other things like the `UNNEST()`, `COUNT(*) OVER()` which SQLite doesn't seem to support.

SQLite supports [window functions](https://sqlite.org/windowfunctions.html) (`COUNT(*) OVER ()`). It doesn't support `UNNEST()` because there is no array type but the latest version does support the [json_each()](https://sqlite.org/json1.html#jeach) table-valued function which can serve a similar role. Also because the database runs inside of the process there is no overhead for using [application-defined functions](https://sqlite.org/appfunc.html) in Go and any missing behavior can be added as an extension.

> * The added effort of maintaining and testing multiple DB backends for all DB related features and changes may be significant. This will be non-trivial upfront and ongoing work.

Yes it's not insignificant. It might be easier if there was a common test suite for the database query interface.

> * These arbitrary SQL expressions are executed in a readonly Postgres transaction. Not sure how this can be achieved in SQLite.

One way I could imagine is opening a second database connection with [SQLITE_OPEN_READONLY](http://www.sqlite.org/c3ref/open.html) and doing all the readonly stuff with that separate connection. Opening a second connection doesn't add much overhead other than a little extra memory use.

**Comment by knadh** [comment]
That helps! I have several pending things on my to-do, so wouldn't be able to look at this right now. But, if you are interested in working on this, I'd be glad to help.

**Comment by maxhawkins** [comment]
OK I am going to take a stab at this. I've started adding some changes to [my fork](https://github.com/maxhawkins/listmonk/commit/acd94d899478640a75550ec4a722d75cc853453a) and will send a PR once I have some more progress.

My strategy is to do this in three parts:

1. Make Queries into an interface rather than a struct by putting the sqlx.Stmt objects behind function calls
```go
type Queries interface {
  GetSubscriber(s *models.Subscribers, id int, uuid, email string) error
  GetSubscribersByEmails(s *models.Subscribers, emails []string) error
  // and so on
}
```
2. Replace `pq.*Array`, `sqlx/types`, and `sql.Result` types in the interface with database-agnostic equivalents
3. Add and test a sqlite implementation behind that new interface

I'll ask you for help after abstracting `Queries` into an interface. It should be a fairly mechanical refactor but I want to make sure it doesn't introduce any regressions before implementing the new SQLite implementation alongside Postgres.

**Comment by knadh** [comment]
Makes sense.

1. The interface can be named "store", which is a more common label / idiom (`internal/store`) denoting arbitrary backend data stores. The functions can return the appropriate types rather than taking a reference and scanning into them. eg:
```go
type Store interface {
  GetSubscribers(id int, uuid, email string) ([]models.Subscribers, error)
  GetSubscribersByEmails(emails []string) ([]models.Subscribers, error)
  // and so on
}
```
2. +1
3. +1

**Comment by maxhawkins** [comment]
I just made a WIP pull request so you can track my progress. Let me know if you spot any regressions as I begin to move the existing database statements behind an interface.

**Comment by mr-karan** [comment]
@maxhawkins  While working on something else, I just realised that if we use https://github.com/mattn/go-sqlite3 (which is the most popular choice for Golang projects), we'll have to enable `CGO_ENABLED=1` as this library requires it to be enabled.

However there's a CGO-free port available as a different library: https://gitlab.com/cznic/sqlite which can be considered.

**Comment by knadh** [comment]
Whoa, completely forgot about this. Thanks for the spot @mr-karan

Adding `cgo` will complicate the build process, but more importantly, will break platform compatibility of the official binary releases. We should seriously consider `cznic/sqlite` (fingers crossed!).

**Comment by maxhawkins** [comment]
I think I got a little in over my head on this PR. It's going to take a lot of refactoring and I no longer have the time.

If someone else wants to take it over I'd be happy to help with code review.

**Comment by knadh** [comment]
No problem @maxhawkins, and thanks for kick starting this. I'll look at this once I run through the big to-do items on my list.

**Comment by joicemjoseph** [comment]
I will give a try

**Comment by ThomasSchoenbeck** [comment]
Hi there, came across this post being interested in compatibility to other databases, but the discussion about CGO caught my eye. I've been using a glibc package for alpine which usually let's me use all sorts of software on alpine. Maybe that package would solve your gcc dependency as well? https://github.com/sgerrand/alpine-pkg-glibc

on the other hand go-sqlite3 proposes to install this in Alpine
https://github.com/mattn/go-sqlite3#alpine
```
apk add --update gcc musl-dev
```

**Comment by knadh** [comment]
@maxhawkins I've started working on the CRUD package abstraction here https://github.com/knadh/listmonk/tree/core

**Comment by knadh** [comment]
The `core` package is merged. However, it is not going to be easy mapping and maintaining Postgres queries to SQLite. Maybe we could re-look at this in the future. Closing for now.

**Comment by altosaar** [comment]
Agreed it would be amazing to try this in sqlite!

**Comment by igitur** [comment]
This is an old issue and I understand the limitations of SQLite, but would you possibly consider implementing this on top of DuckDB, which is an embedded database that [draws inspiration](https://news.ycombinator.com/item?id=24531894) heavily from SQLite as well as Postgres. For example, it [supports](https://duckdb.org/docs/extensions/json.html) JSON data types. [UNNEST](https://duckdb.org/docs/sql/query_syntax/unnest) is also supported.

**Comment by knadh** [comment]
Hi @igitur. Adding support for another DB backend is a mammoth task. No plans for alternative DB backends currently.

Aside: DuckDB isn't a general purpose DB like SQLite though.
