### ISSUE TITLE
🚨 Potential Security Vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [knadh/listmonk#370]
Hello, @knadh - a potential high severity security vulnerability in your repository has been disclosed to huntr.

Visit report url and validate them 
[https://huntr.dev/bounties/3-other-knadh/listmonk/](https://huntr.dev/bounties/3-other-knadh/listmonk/)

**Comment by knadh** [comment]
Since file uploads can be done only by authenticated super admins, this shouldn't really be a problem, but I've added a file extension check anyway: https://github.com/knadh/listmonk/commit/dba47bca2840363c593ffc7c3ef2e3e10fd8808a

**Comment by ranjit-git** [comment]
Great.
Can you plz validate or invalidate  the report there https://huntr.dev/bounties/3-other-knadh/listmonk/

Thanks
