### ISSUE TITLE
Scheduling Campaigns - schedule time relative to subscription time

### ISSUE THREAD

**Issue by maciekmm** [knadh/listmonk#375]
**Is your feature request related to a problem? Please describe.**

It is a common practice to automatically send emails a set time after someone's subscription. 

An example use-case would be an on-boarding campaign:
1. send an email immediately after subscription with a guide on how to use a software
2. a a few days later do a follow up asking for opinions/problems encountered.

Another use case is to perform a product for email barter:
- send an email immediately after subscription with a course/report/pdf.

This will also solve #206 

**Describe the solution you'd like**

We already have "Send later" option in a campaign.
We could add a checkbox "relative to subscription time" or probably better - a separate section "Send after subscription".
I didn't get a deep dive into the source code, thus I don't have any insight on how hard it would be to implement, but it's something I could and wish to explore.

**Comment by knadh** [comment]
> send an email immediately after subscription with a guide on how to use a software

An auto-reply on subscription makes sense as described in #206. It will act like templates, where a message can be attached to a list as the default auto-reply.

> a a few days later do a follow up asking for opinions/problems encountered.

This isn't currently feasible with the way listmonk is built, or its primary function, which is to be a newsletter manager. This is more of "marketing automation" and tools like Mautic may be better suited. listmonk campaigns are transactional. You create them and once they start, they run and and then end.

**Comment by maciekmm** [comment]
Fair enough, closing :).
