### ISSUE TITLE
502 bad gateway error

### ISSUE THREAD

**Issue by smaranr** [knadh/listmonk#377]
![image](https://user-images.githubusercontent.com/16491433/120227804-84c73580-c267-11eb-8254-327f0d1a67f2.png)

![image](https://user-images.githubusercontent.com/16491433/120227581-0cf90b00-c267-11eb-909c-f931e656db13.png)

my config.toml

![image](https://user-images.githubusercontent.com/16491433/120227714-534e6a00-c267-11eb-8032-8a6dfd7a98e3.png)

please help struggling since a week for proper settings.

Also do i need to restart after making changes to config.toml to reflect?

note: i followed https://github.com/yasoob/listmonk-setup steps.

**Comment by mr-karan** [comment]
From the logs, the uptime of listmonk container seems to be less than a minute, my guess is that it's crashing and restarting? Is it a first time setup?

**Comment by smaranr** [comment]
@mr-karan  hey! thank you for the reply. Yes, this is a first time setup. successfully installed after using install command. But couldn't find logout option. 

![image](https://user-images.githubusercontent.com/16491433/120269564-aeaf4500-c2c5-11eb-88fb-01b744d4f595.png)


do i need to run -- install command whenever the instance restarts ?

**Comment by knadh** [comment]
There isn't a "logout" for now. Simply closing the browser will clear the httpauth session.

> do i need to run -- install command whenever the instance restarts ?

No! `--install` resets and wipes the DB and is meant to be only run once, ever.

**Comment by smaranr** [comment]
Awesome. Thank you so much for the info.
