### ISSUE TITLE
I can only see the first 20 lists on the campaign page

### ISSUE THREAD

**Issue by sfstpala** [knadh/listmonk#379]
**Version:**
 - listmonk: v1.0.0
 - OS: Ubuntu

On the Campaign page (`/campaigns/xxx`), I can only see the first 20 lists in the dropdown. The call to `/api/lists` returns 20 results even though I have a lot more lists.

**Comment by knadh** [comment]
Ah! The API is paginated for table views, but it shouldn't be paginated for drop downs (obviously). This has to be fixed.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/3d263666209db8755711236b2546ebe8b7bdf1ea fixes this.
