### ISSUE TITLE
Error preparing query 'get-dashboard-stats': pq: relation "lists" does not exist

### ISSUE THREAD

**Issue by matthewfurr** [knadh/listmonk#38]
I get the following error after starting up a docker image.

```
2019/11/15 12:01:15 main.go:112: reading config: config.toml
2019/11/15 12:01:15 main.go:284: no SQL queries loaded: Error preparing query 'get-dashboard-stats': pq: relation "lists" does not exist
```

**Comment by matthewfurr** [comment]
I fixed it by reading the rest of the documentation.

`docker-compose run --rm app ./listmonk --install `

Sorry for the hassle! I'll close this. I look forward to digging into this now!

**Comment by Vinutha-Garimella** [comment]
Hi I am facing the same problem too, I have a postgress db container already where I created a database called `listmonk` and created a listmonk container by volume mounting the config.toml 
```
[db]
host = "db"
port = 5432
user = "listmonk"
password = "listmonk"
database = "listmonk"
ssl_mode = "disable"
```
db container 
```docker run -itd --name db --hostname db --network my-net -v db-test:/var/lib/postgresql/data -e POSTGRES_PASSWORD=listmonk -e POSTGRES_USER=listmonk -e POSTGRES_DB=listmonk --restart unless-stopped -p 5432:5432 postgres:11
```
listmonk container
```
docker run -itd --name listmonk --hostname listmonk --network my-net -p 9000:9000  -v Desktop/config.toml:/listmonk/config.toml listmonk```
the listmonk container is not coming up and I see this error in listmonk container logs
```
2020/06/03 02:14:02 main.go:90: reading config: config.toml
2020/06/03 02:14:02 init.go:121: error preparing SQL queries: Error preparing query 'get-dashboard-stats': pq: relation "lists" does not exist
```
