### ISSUE TITLE
Query more than 20 elements per API

### ISSUE THREAD

**Issue by NiTRoeSE** [knadh/listmonk#383]
Hello, we need to script a lot for automating things.
We have more than 20 subscriber lists with a user count between 20 - 800 users.

The Problem:

If i query the API to show all lists, i only get the first 20 lists back.
In the documentation is shown the way to use parameters like `&page=X`.
Unfortunately i can't use the `&page=1&page=2` parameters because i simply doesn't know how many pages are present. ( I also doesn't know how many lists are present and how many users are in this lists)

Is there any way to make a API call to get all lists detached from how many pages or lists are present?

Something like `https://my.domain.com/api/lists&page=all` ?

The same problem exists for user queries, there i only get the first 30 users back.
So i also need this solution for that case to.

Thanks in advanced & kind regards

**Comment by knadh** [comment]
You can pass the `?per_page=all` param to pull all the results in one go. Will document this.

You can also pass a specific number to this param, but I just remembered that that has upper limits hardcoded in the code. This, I'll fix.

**Comment by NiTRoeSE** [comment]
Thanks for your quick answer. :)

I´ve tested it and came to following conclusion:

**For lists** the maxium possible is 50 lists, all numbers above are ignored, also param "all".
`https://my.domain.com/api/lists/api/lists?per_page=50` 

**For subscribers** it didn't work at all for me:

`https://my.domain.com/api/subscribers?list_id=58?per_page=40`

Param `?per_page=40` is ignored.

I tested all this in Browser.

Thanks

**Comment by knadh** [comment]
`per_page=all` and the UI not loading all lists in the dropdown are fixed here: https://github.com/knadh/listmonk/commit/3d263666209db8755711236b2546ebe8b7bdf1ea

If you are building listmonk from source, you can pull `master`. Otherwise, you can wait for a day for the next release that'll include this along with another critical bug fix. Thanks.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/8859911c738edcb3718ce08ccf7902363eccd0e1 this removes the hardcoded limit and allows any number in the `per_page` param.

**Comment by swarajyamagdev** [comment]
Hello @knadh 
`/api/subscribers?list_id=4&per_page=all&page=1`

We are trying this with subscription list with thousands of subscribers still it is returning only 50.
![Screenshot 2022-12-20 at 5 56 07 PM](https://user-images.githubusercontent.com/106065625/208667069-99a9c249-4375-47c1-937d-a427848d311a.png)

And we are on 2.3.0 . Please help out

**Comment by knadh** [comment]
@swarajyamagdev I just confirmed that this is a bug. I will push a fix tomorrow to `master`. Would you be able to compile `master` and use it?

Otherwise, as a temporary hack until next version, you can pass `per_page=9999999` (a large number).
