### ISSUE TITLE
Post campaign with api

### ISSUE THREAD

**Issue by NiTRoeSE** [knadh/listmonk#386]
Hi there, yes ist me again ;),

First of all thanks for you fast support in last days!

I try to post a campaign through api with following code and fail at "lists" in this step.
I always get errors like:

`{"message":"Unmarshal type error: expected=int64, got=object, field=lists, offset=207"}`

I tried various ways to post the campaign, but found no solution.

Unfortunately this step is not documented.

Maybe someone can help to find out how to write the "lists" part of request.

```python

import json, requests


authorisation = ('admin', 'password!')
apiurl_campaign = 'http://my.domain.de/api/campaigns'

BODY = "<p> test <p>"


def create_campaign(authorisation, apiurl_campaign, body):

    authorisation = authorisation


    def create_params(BODY):



        data={

            "type": "regular",
            "name": "Test API",
            "subject": "API ROCKS",
            "from_email": "No Reply <noreply@my.domain.de>",
            "body": BODY,
            "status": "draft",
            "content_type": "html",
            "template_id": 1,
            "lists": [
                        {
                        "id": 1,
                        "name": "Default list"
                        }

                    ]
            }
        return data


    campaign_data = create_params(BODY)


    campaign = requests.post(apiurl_campaign, auth=authorisation, json=campaign_data)
    print('  [IMPORT] - {}'.format(campaign.text.split('\n')[0])) # drop second empty line


# Run
create_campaign(authorisation, apiurl_campaign, BODY)



```

Thanks & regards

**Comment by knadh** [comment]
The `lists` param should not be an object but an array of list IDs. `lists: [1,2,3]`.

You can inspect the API requests on the network console of your browser. The UI uses the same API.
