### ISSUE TITLE
Update master branch

### ISSUE THREAD

**Issue by alerque** [knadh/listmonk#389]
The tag for v1.1.0 has commits that haven't been pushed to master. This breaks `git describe` because it thinks the most recent past tag related to the branch is v1.0.0. It looks like you pushed the tag without pushing the branch.

Also the GitHub Release page in messed up because of HTML in commit messages.

**Comment by knadh** [comment]
hmm.
```
$ git push origin master                                                                                                                                                                  
Are you sure you want to push to "master" ? (y/n): y
Everything up-to-date
```
The latest commit in the release note (automatically generated by `goreleaser`) also references the right commit in master.


> Also the GitHub Release page in messed up because of HTML in commit messages.

Ah yes, there was a `<pre>`. Escaped it. Thanks.

**Comment by alerque** [comment]
You pushed *something*. At the time of opening this issue a3b285f was the latest commit on master, b361292 existed on GitHub only as a tag on a detached HEAD. Master is now at b361292 as well.
