### ISSUE TITLE
List subscription status, double opt-in

### ISSUE THREAD

**Issue by Jjagg** [knadh/listmonk#39]
First off, thank you so much for open sourcing this tool :) 

Is the list subscription status currently used for anything? It seems to be for double opt-in, but it looks like it isn't used yet. I've set up my mailing list with double opt-in by only adding a list to a subscriber after they confirm, but that's a bit annoying because there's no subscription management page before I added users to the list (so I can't use the built-in UI to let users wipe their data before they confirm).

**Comment by knadh** [comment]
Thanks @Jjagg. That's right. It's meant for double opt-in (work in progress), so right now, they're mere indicators. I should be able to push this reasonably soon.

**Comment by knadh** [comment]
Work in progress:

![image](https://user-images.githubusercontent.com/547147/70335891-330a3e80-186e-11ea-82d3-d953a16cafb4.png)

![image](https://user-images.githubusercontent.com/547147/70336670-9648a080-186f-11ea-8278-f37d2d20ab50.png)

**Comment by Jjagg** [comment]
Neat! Would be nice to use a template for the confirmation mail.

**Comment by knadh** [comment]
@Jjagg this was more complex than I anticipated, but it's finally out. Check out [https://github.com/knadh/listmonk/releases/tag/v0.4.0-alpha](v0.4.0-alpha]).

You'll have to run a few SQL alterations to upgrade as described in the release notes.

**Comment by Jjagg** [comment]
Awesome, thanks :)
