### ISSUE TITLE
Issues with SMTP

### ISSUE THREAD

**Issue by rizwan95** [knadh/listmonk#393]
**Version:**
 - listmonk: [eg: v0.9.0-beta]
 - OS: [e.g. Centos]

**Description of the bug and steps to reproduce:**
When I try to send an email, I get the following error message Error sending test: dial tcp SERVER_IP:587: i/o timeout

I have tried telnet commands and they work fine. 

P.S - Please change the label to question instead of bug.

**Comment by knadh** [comment]
`test: dial tcp SERVER_IP:587: i/o timeout`

hm, the connection attempt itself is timing out. Is this running inside Docker? If yes, it could be related to the Docker network config. @mr-karan ?

Also, do you have access to the SMTP server? If yes, are you able to see a log of the incoming connection?

**Comment by mr-karan** [comment]
@rizwan95 If you're running Listmonk using Docker, can you show the output of this command (exec into the app container and run this):

```sh
nc -vz -w 3 SMTP_HOST_IP 587
```

**Comment by rizwan95** [comment]
@mr-karan  Here is the output of the command which you gave,

<img width="850" alt="image" src="https://user-images.githubusercontent.com/10910174/121813674-bd650700-cc8a-11eb-8aeb-282a52c99156.png">

**Comment by mr-karan** [comment]
`SMTP_HOST_IP` is to be replaced by your actual SMTP server IP

**Comment by rizwan95** [comment]
> `SMTP_HOST_IP` is to be replaced by your actual SMTP server IP

Sorry! here is the output 

![log](https://user-images.githubusercontent.com/10910174/121813882-bbe80e80-cc8b-11eb-8cbf-a004f65dab13.jpg)

P.S - I have obfuscated the IP address for privacy reasons

**Comment by mr-karan** [comment]
Can you try the same command outside docker container?

If it times out -> SMTP server probably is firewalled and you need to whitelist it.
If it works -> Try doing a `ping` / `traceroute` inside the container and compare the network hops. You'll probably find the different hops. 

It's difficult to debug without more information.

**Comment by rizwan95** [comment]
@mr-karan 

It connects well from external sources. 

Here is the output of the command from outside the docker
```
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to MY_SERVER_IP:587.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
```

**Comment by rizwan95** [comment]
@mr-karan  When I do a ping, it does nothing, 

Command - ping MY_SERVER_IP
`PING MY_SERVER_IP (MY_SERVER_IP): 56 data bytes`

Traceroute also does nothing, 

```
traceroute to MY_SERVER_IP (MY_SERVER_IP), 30 hops max, 46 byte packets
 1  *  *  *
 2

```

Something is clearly wrong with the docker container.. I am not sure what am I missing

**Comment by rizwan95** [comment]
Update, I restarted the docker service using `service docker restart` and ping works, the traceroute works, and the nc command also gives me this output

`MY_SERVER_IP (MY_SERVER_IP) open`

@mr-karan

**Comment by mr-karan** [comment]
Ah. Strange, it looks like the network interface wasn't bridged with your local LAN interface. I wonder how `apk add` commands worked though, since that means the container did have outside network connectivity, atleast for public IPs. 

Is `MY_SERVER_IP` a private IP, that can explain a few things. If not maybe you can check `journalctl -u docker` and check for any errors. 

Closing this anyhow! :smile:

**Comment by rizwan95** [comment]
Thank you, I will test it out and update here

**Comment by rizwan95** [comment]
Still the issue persists. @mr-karan  Please help!
I tried journalctl -u docker and it throws up this error, can you help in decoding what's going on in here? 

`Jun 13 05:36:34 vps.server.com dockerd[28771]: time="2021-06-13T05:36:34.617949549Z" level=error msg="stream copy error: reading from a closed fifo"
Jun 13 05:36:34 vps.server.com dockerd[28771]: time="2021-06-13T05:36:34.650159484Z" level=error msg="Error running exec 1bd13e674addb2b5d713aa9fbb592bfef43c826340e7204de4b
Jun 13 05:40:04 vps.server.com dockerd[28771]: time="2021-06-13T05:40:04.053962040Z" level=error msg="stream copy error: reading from a closed fifo"
Jun 13 05:40:04 vps.server.com dockerd[28771]: time="2021-06-13T05:40:04.200388029Z" level=error msg="3fc024662d330c50c93a9d999b2bb57a4584bf319a1a30eb58b2360b2b1659fd clean
Jun 13 05:40:25 vps.server.com dockerd[28771]: time="2021-06-13T05:40:25.739246550Z" level=info msg="ignoring event" container=55bceeeffa6224d1c023bf9d26a376cbeaea1e8905d46
Jun 13 05:40:32 vps.server.com dockerd[28771]: time="2021-06-13T05:40:32.409212335Z" level=info msg="ignoring event" container=1e8f28af4c9d428b6c2a6ef81f7d88e884b4440e999fb
Jun 13 05:40:32 vps.server.com dockerd[28771]: time="2021-06-13T05:40:32.786640872Z" level=info msg="ignoring event" container=c556485e70a89146243063764f90e7c5413de5390ca3b
Jun 13 06:10:10 vps.server.com dockerd[28771]: time="2021-06-13T06:10:10.498754663Z" level=warning msg="Failed to allocate and map port 9432-9432: Bind for 0.0.0.0:9432 fai
Jun 13 06:10:10 vps.server.com dockerd[28771]: time="2021-06-13T06:10:10.590734647Z" level=error msg="443f5f569b151e3cae78079f30c2952b2a013dd0c2688bc496f2d81ae4ec19ba clean
Jun 13 06:10:10 vps.server.com dockerd[28771]: time="2021-06-13T06:10:10.590855779Z" level=error msg="Handler for POST /v1.41/containers/443f5f569b151e3cae78079f30c2952b2a0
Jun 13 06:10:25 vps.server.com dockerd[28771]: time="2021-06-13T06:10:25.052096681Z" level=info msg="ignoring event" container=c5f76e2099e7bc1b43aaacdbd39f7aa814d93feca20f9
Jun 13 06:10:30 vps.server.com dockerd[28771]: time="2021-06-13T06:10:30.175537895Z" level=info msg="ignoring event" container=66fe2ebd8c67dc7a549bb2f5dd7c7e6d0796fad0de511
Jun 13 06:11:27 vps.server.com dockerd[28771]: time="2021-06-13T06:11:27.398908457Z" level=error msg="Error getting services: This node is not a swarm manager. Use \"docker
Jun 13 06:11:27 vps.server.com dockerd[28771]: time="2021-06-13T06:11:27.399936616Z" level=error msg="Handler for GET /v1.40/services returned error: This node is not a swa
Jun 13 06:16:25 vps.server.com dockerd[28771]: time="2021-06-13T06:16:25.900220614Z" level=error msg="stream copy error: reading from a closed fifo"
Jun 13 06:16:25 vps.server.com dockerd[28771]: time="2021-06-13T06:16:25.900285110Z" level=error msg="stream copy error: reading from a closed fifo"
Jun 13 06:16:25 vps.server.com dockerd[28771]: time="2021-06-13T06:16:25.905874428Z" level=error msg="Error running exec da6af8afb2984b74620e52ed09bd27155f8ceceaa9472bd25a8
Jun 13 06:17:00 vps.server.com dockerd[28771]: time="2021-06-13T06:17:00.118872658Z" level=error msg="stream copy error: reading from a closed fifo"
Jun 13 06:17:00 vps.server.com dockerd[28771]: time="2021-06-13T06:17:00.120130083Z" level=error msg="stream copy error: reading from a closed fifo"
Jun 13 06:17:00 vps.server.com dockerd[28771]: time="2021-06-13T06:17:00.122584825Z" level=error msg="Error running exec d5460fd658ac0945a24e63a9f879066979c4abec53f63e09eaa
Jun 13 06:18:33 vps.server.com dockerd[28771]: time="2021-06-13T06:18:33.909925570Z" level=error msg="stream copy error: reading from a closed fifo"
Jun 13 06:18:33 vps.server.com dockerd[28771]: time="2021-06-13T06:18:33.913560642Z" level=error msg="Error running exec 76a25b839580f96f63ab209cadf18aa4b605f4456e596b069df`

**Comment by rizwan95** [comment]
The problem was with the docker! Thank you @mr-karan

**Comment by mr-karan** [comment]
Looks like you're using Docker Swarm. Sorry I'm unfamiliar with its networking.

**Comment by rizwan95** [comment]
It got solved, @mr-karan  :D 
Thank you!

**Comment by imRezaAlie** [comment]
Dear @mr-karan  / @knadh  ,
when i run below command in container in i retrieve this error :



`[root@tevla526 lastlistmonk]# docker exec -it 0ed2d232524d sh
/listmonk # apk add netcat-openbsd
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: No such file or directory
ERROR: unable to select packages:
  netcat-openbsd (no such package):
    required by: world[netcat-openbsd]
/listmonk # nc -vz -w 3 20.131.61.43 587
nc: 20.131.61.43 (20.131.61.43:587): Operation timed out
/listmonk # nc -vz -w 3 20.131.61.43 25
nc: 20.131.61.43 (20.131.61.43:25): Operation timed out
`
note : i using internal smtp server
note 2: firewall off
note 3: There is no restriction between these nodes.

would you please support 

thanks in advance

**Comment by mr-karan** [comment]
> connectivity between docker and smtp server is ok (ping)

Doesn't seem like from the above logs

```
# nc -vz -w 3 20.131.61.43 587 nc: 20.131.61.43 (20.131.61.43:587): Operation timed out /listmonk # nc -vz -w 3 20.131.61.43 25 nc: 20.131.61.43 (20.131.61.43:25): Operation timed out 
```

**Comment by imRezaAlie** [comment]
please share related command for check form docker inside
