### ISSUE TITLE
Embed graphics in mail body

### ISSUE THREAD

**Issue by ChrisTG742** [knadh/listmonk#395]
Are there any plans to support embedding of image data directly in the email body? I'm talking about stuff like "<img src="data:image/jpg;base64,..." (see here: https://stackoverflow.com/a/4528706)

There are many e-mail clients out there that block external images by default. Also one needs to have the linkmonk-server be accessible from the WAN to get the images displayed correctly at the recipients side.
Having the images embedded right into the email's body-code would solve these issues.
TIA!

**Comment by Donatzsky** [comment]
The problem with this is that there are some (Gmail notably) that don't support data URIs.

**Comment by ChrisTG742** [comment]
Okay, another option that works in all major e-mail clients is using inline-attachments with content-IDs.
AFAIC this is the way Outlook nativly embeds pictures into the mail body.
https://stackoverflow.com/a/42014708

**Comment by knadh** [comment]
We're tracking this issue here: https://github.com/knadh/listmonk/issues/56

There are plans to explore this but haven't had a chance to make headway.
