### ISSUE TITLE
Will Listmonk ever offer brand management / multitenancy?

### ISSUE THREAD

**Issue by scottccoates** [knadh/listmonk#396]
I would love to be able to manage multiple brands (multiple tenants) in listmonk a la Sendy / BigMailer (the only 2 that I know of who offer such capability).

Will Listmonk ever offer something like this? I was surprised to find very little discussion about this topic, so that makes me think this feature is not in high demand :/

Hoping that's that the case!

**Comment by knadh** [comment]
Multi-tenancy is out of the scope of the project, hence not on the roadmap @scottccoates 

If you do want multi-tenancy in an environment where tenants are large, it may make sense to orchestrate a DB per client and run multiple instances of listmonk (single binary or Docker) for each tenant. listmonk is light weight to run and easy to install, so this should be straight forward too.
