### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by oomb** [knadh/listmonk#397]
Hi @knadh,

A potential security issue was found in this project, and it has been reported at https://huntr.dev/bounties/4-knadh/listmonk/. 

Could you please spare some time to look into the issue and validate it? The link is private, and will be only accessible to the maintainers of this project. 

Thanks!

**Comment by knadh** [comment]
Confirmed. Will patch this and confirm on the bounty page shortly. Thanks for reporting.

**Comment by oomb** [comment]
Can you please update this as a valid report on huntr.dev?
