### ISSUE TITLE
error fetching campaigns !!

### ISSUE THREAD

**Issue by Suleman-Elahi** [knadh/listmonk#4]
**Platform**: Windows 10, 1903
**Postgre Server**: Free plan of ElephantSQL

Everything is working fine, the UI shows up in the browser but after creating a campaign when I hit the "Continue" button it throws an error.

![image](https://user-images.githubusercontent.com/24384996/61213221-00767280-a722-11e9-990a-16e9b3238b01.png)

**Comment by knadh** [comment]
The error shows `"pq: too many connections ..."`. Looks like you've exceeded the Postgres connection limits. Please check your Postgres configuration.
