### ISSUE TITLE
UID/GID or PUID/GUID support

### ISSUE THREAD

**Issue by DOFfactory** [knadh/listmonk#400]
**Version:**
 - listmonk: 1.1.0
 - OS: CentOS7

**Description of the bug and steps to reproduce:**
I am not a root user on my VM and I need to set up a UID/GID or PUID/GUID as an environment for accessing the volumes with docker. Currently I am receiving the errors in the logs:

```sh
sh: /listmonk: Permission denied
sh: /listmonk: Permission denied
sh: /listmonk: Permission denied
sh: /listmonk: Permission denied
sh: /listmonk: Permission denied
```

Could you please add these environments?

**Comment by mr-karan** [comment]
You can pass a user/group ID with: `docker run --rm --user $(id -u):$(id -g) listmonk/listmonk:latest` or the equivalent in `docker-compose`. Does that not work?

**Comment by DOFfactory** [comment]
Hm, there is a weird issue. I defined a specific IP (due to network topology circumstances) in the `docker-compose.yaml`. In the `config.toml` the IPs are correctly created, however, when I run your command, I get the following error:

```
[user@host listmonk]$ sudo docker run --rm --user $(id -u):$(id -g) listmonk/listmonk:latest
2021/06/18 11:41:42 main.go:84: v1.1.0 (b361292 2021-06-09T14:49:25Z)
2021/06/18 11:41:42 init.go:99: reading config: config.toml
2021/06/18 11:41:42 init.go:190: connecting to db: localhost:5432/listmonk
2021/06/18 11:41:42 init.go:193: error connecting to DB: dial tcp 127.0.0.1:5432: connect: connection refused
[user@host listmonk]$ 
```

It seems as if the command does not read the correct `config.toml` file. The IP to the DB should be something completely different.

**Comment by mr-karan** [comment]
The command I gave was just an example command to show how to pass a custom user ID to a Docker container. That command doesn't include mounting of config file, which is why it's not picking up your custom config.

**Comment by DOFfactory** [comment]
Is there anything why this (together with the app hostname) cannot be set via environment fields? I would prefer that option.

**Comment by mr-karan** [comment]
This is not an app specific thing, that's why it's completely out of scope of the app. 

App hostname (and other variables) can be set by environment variables, as described here: https://listmonk.app/docs/configuration/#environment-variables

Docker allows you to set user with -u and even docker-compose does, which is a fairly standard practice that I've seen.

**Comment by DOFfactory** [comment]
Thanks, even with the variables set, I am running into the following problem:

```
[user@host listmonk]$ sudo docker-compose up
Starting listmonk_db ... done
Starting listmonk_app ... done
Attaching to listmonk_db, listmonk_app
listmonk_app   | sh: /listmonk: Permission denied
listmonk_db    | 
listmonk_db    | PostgreSQL Database directory appears to contain a database; Skipping initialization
listmonk_db    | 
listmonk_db    | 2021-06-18 18:09:31.524 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
listmonk_db    | 2021-06-18 18:09:31.524 UTC [1] LOG:  listening on IPv6 address "::", port 5432
listmonk_db    | 2021-06-18 18:09:31.531 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
listmonk_db    | 2021-06-18 18:09:31.552 UTC [26] LOG:  database system was shut down at 2021-06-18 18:07:47 UTC
listmonk_db    | 2021-06-18 18:09:31.557 UTC [1] LOG:  database system is ready to accept connections
listmonk_app exited with code 126
listmonk_app   | sh: /listmonk: Permission denied
listmonk_app   | sh: /listmonk: Permission denied
listmonk_app   | sh: /listmonk: Permission denied
listmonk_app   | sh: /listmonk: Permission denied
listmonk_app   | sh: /listmonk: Permission denied
listmonk_app   | sh: /listmonk: Permission denied
listmonk_app   | sh: /listmonk: Permission denied
listmonk_app   | sh: /listmonk: Permission denied
listmonk_app   | sh: /listmonk: Permission denied
listmonk_app   | sh: /listmonk: Permission denied
listmonk_app   | sh: /listmonk: Permission denied
listmonk_app   | sh: /listmonk: Permission denied
listmonk_app exited with code 126
```

Any help would be great.

**Comment by mr-karan** [comment]
Can you show the changes you've done to `docker-compose`?

Also, don't run `docker` or `docker-compose` with sudo.
