### ISSUE TITLE
template_id is not correct in update-campaign 

### ISSUE THREAD

**Issue by sparklive** [knadh/listmonk#401]
**Version:**
 - listmonk: v1.1.0

**Description:**

```
-- name: update-campaign
WITH camp AS (
    UPDATE campaigns SET
        name=$2,
        subject=$3,
        from_email=$4,
        body=$5,
        altbody=(CASE WHEN $6 = '' THEN NULL ELSE $6 END),
        content_type=$7::content_type,
        send_at=$8::TIMESTAMP WITH TIME ZONE,
        status=(CASE WHEN NOT $9 THEN 'draft' ELSE status END),
        tags=$10::VARCHAR(100)[],
        messenger=$11,
        template_id=$13,
        updated_at=NOW()
```

Please confirm that  template_id should be =$12 not =$13

**Comment by knadh** [comment]
Hi @sparklive, 
Where are you seeing `$13`? `$12` is correct as it is in the codebase:

https://github.com/knadh/listmonk/blob/5988ea36cbdcaebafab913e17e2691b6f65e31ce/queries.sql#L602

**Comment by sparklive** [comment]
sorry, my mistake.
BTW, whats the ETA for 2.0 release?
Thanks
