### ISSUE TITLE
Security issue (port separate)

### ISSUE THREAD

**Issue by myjjuliet0209** [knadh/listmonk#402]
Hello, 

Thank you for sharing it in open source.

There is a security issue.
Can't you separate the admin port and the api port?

Administration page cannot be opened outside. (firewall)
However, for subscriver api, firewall opening is required so that the user can call api.

I think the port that the administrator connects to and the port that users call api should be separated.

**Comment by knadh** [comment]
A separate port for certain endpoints is not a very common pattern. It complicates deployment and setup.

The admin endpoints are behind auth, and in production environments, listmonk is expected to be deployed behind a proxy like Nginx or Caddy (for things like TLS), where it's trivial to add custom rules to add extra protection to admin endpoints.

**Comment by bamboowonder** [comment]
On this note, I've been using Cloudflare Access for my business.   Used with the Argo Tunnel it makes securing apps and specifying ports for certain roles easy.
