### ISSUE TITLE
Add continuous campaigns based on triggers

### ISSUE THREAD

**Issue by cortopy** [knadh/listmonk#404]
**Is your feature request related to a problem? Please describe.**
AFAIK, all campaigns in listmonk are time-based, where they start/stop based on a time span. It would be nice to also have the possibility of defining campaigns that run based on triggers rather than on a timely basis.

This would allow things like:
- Send emails A, B, C, and D to each new subscriber with one week apart. For example, new users could learn about an organisation with a series of introductory emails with a weekly email during the first four weeks. During this time the user should not be getting any other emails to avoid user being overwhelmed
- Send email X when a user gets added to segment Y

**Describe the solution you'd like**
[Mailtrain](https://mailtrain.org/) has a feature called `triggers` which allow doing all the things above. It's quite neat and really helpful

**Comment by knadh** [comment]
> Send emails A, B, C, and D to each new subscriber with one week apart. For example, new users could learn about an organisation with a series of introductory emails with a weekly email during the first four weeks. During this time the user should not be getting any other emails to avoid user being overwhelmed

This level of automation is not in the project's scope right now.

> Send email X when a user gets added to segment Y.

Auto-responses on subscription based on lists is on the to-do.

**Comment by cortopy** [comment]
thanks @knadh for clarifying this, much appreciated. I'll close this one then
