### ISSUE TITLE
Subscribers SQL query placeholder

### ISSUE THREAD

**Issue by andreafa** [knadh/listmonk#408]
Within: Subscribers > All Subscribers > Advanced
the current placeholder is:
subscribers.name LIKE '%user%' or subscribers.status='blocklisted'

Clicking the [Query] button then the [Export] link, I get the error:
{"message":"Error preparing subscriber query: pq: invalid reference to FROM-clause entry for table \"subscribers\""}

Everything works fine using this syntax (without the subscribers. prefix):
name LIKE '%user%' OR email LIKE '%email%'

I could not find how to extract the status information.

**Comment by knadh** [comment]
Ah, this is a bug. In the export query, the `subscribers` table is internally aliased as `s`. Will fix this.

For now, you can hit the export API directly by replacing the `subscribers.` with `s.`

```
s.name LIKE '%user%' OR s.status != 'blocklisted'

(Query is urlencoded below)
/api/subscribers/export?query=+s.name+LIKE+%27%25user%25%27+or+s.status!%3D%27blocklisted%27
```
