### ISSUE TITLE
Integrate with GoTrue?

### ISSUE THREAD

**Issue by robhenley** [knadh/listmonk#41]
This is more of a feature thought but perhaps you could punt on actually doing authentication and use GoTrue (https://github.com/netlify/gotrue).  It might be better to keep third party dependencies out but I've used GoTrue and been happy with it.

**Comment by knadh** [comment]
Hi @robhenley,
I've looked at gotrue and https://github.com/volatiletech/authboss and have found them both to be a bit much. Didn't feel right to bring gotrue's naming conventions into listmonk's config. That said, I have been working on a much smaller (glue) package that provides necessary abstractions for auth. Have to think of user roles and permissions (and per user per list permissions) too. Hope to release this very soon.
