### ISSUE TITLE
Options for customising user-facing pages

### ISSUE THREAD

**Issue by jeff-h** [knadh/listmonk#415]
When a user successfully submits the subscription form (as generated at `lists/forms`) they are presented with this:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/841871/124348351-8c4e7580-dc3d-11eb-9b7d-13f094bccec6.png">

The logo is customisable (which is awesome), but it looks like the "Subscribe / Subscribed successfully." wording is coming from an i18n file and is generic to all lists.

I'm wondering if there's any way to customise this wording per-list, or even better a way to configure a return URL for listmonk to return the user to (again, per-list).

**Comment by jeff-h** [comment]
It looks like it might be possible to pass the `ListUUIDs` through to the templates? The templates could then apply per-list customisation logic based on the UUIDs received.

**Comment by knadh** [comment]
Passing arbitrary values to that page would be odd, as there would be other values to pass as well in other scenarios. Rather than adding these params to hack customization, the right way to do it is to just use subscription APIs to build your own custom form and views.

**Comment by jeff-h** [comment]
You're right of course, that's a prime use-case for the API :) In my specific scenario I'm trying to achieve something really quick & temporary (a beta sign-up form) so was hoping to get away without any other backend system, and just integrate listmonk directly with a Cloudflare Pages site. (Since the API requires BasicAuth even for adding subscribers I can't call it from Javascript.)

ps I also just wanted to thank you for the fantastic project & your ongoing work on it.

**Comment by jeff-h** [comment]
Ha, I just thought it through and realised there should be nothing stopping me just submitting the listmonk-generated form via JS. Will give that a go :)

**Comment by jeff-h** [comment]
Nothing that is, except... CORS 🙈

**Comment by jeff-h** [comment]
So I was able to work around the CORS issue by adding an `Access-Control-Allow-Origin` header in my nginx reverse proxy definition (fortunately I was already reverse-proxying listmonk anyway). The following is too loose as it allows posting the form from *any* site, but it's useful for testing:

```
add_header Access-Control-Allow-Origin *;
```

Then on my site I was able to programmatically submit the listmonk-generated form (from `lists/forms`) via Javascript. To make the JS simple I added a CSS ID to the form: `list-signup-form`.

```js
window.onload = function() {
  const form = document.getElementById('list-signup-form');

  form.onsubmit = function() {
    fetch(form.action, {
      method: 'POST',
      body: new URLSearchParams(new FormData(form)),
    })
    .then(function(response) {
      if (response.status !== 200) {
          showFailure('Response: ' + response.status)
        return;
      }

      // Examine the text in the response
      response.text().then(function(data) {
        if (data.includes("Subscribed successfully")) {
          showSuccess()
        }
        else {
          showFailure('Subscription failed')
        }
      });
    })
    .catch(function(err) {
      showFailure(err)
    });

    // Prevent the default form behavior.
    return false;
  }

  function showSuccess() {
    // Alert the user
  }
  
  function showFailure(e) {
    // Alert the user
  }

}
```

Hope this helps someone :)
