### ISSUE TITLE
Insert button via toolbar

### ISSUE THREAD

**Issue by mdehollander** [knadh/listmonk#416]
**Is your feature request related to a problem? Please describe.**
I would like to be able to insert elements via the toolbar in a newsletter, for example a button. Currently I can edit the html and insert a `<button>` field, but when you continue the editing in Rich Text mode the formatting is lost.

**Describe the solution you'd like**
Adding a "insert button" option in the Quil toolbar. According to the Quil documentation this should be possible: https://quilljs.com/docs/modules/toolbar/#container

For example adding a custom button to the toolbar can be done with:

```
<div id="toolbar">
  <!-- Add buttons as you would before -->
  <button class="ql-bold"></button>
  <button class="ql-italic"></button>

  <!-- But you can also add your own -->
  <button id="custom-button"></button>
</div>
<div id="editor"></div>

<script>
var quill = new Quill('#editor', {
  modules: {
    toolbar: '#toolbar'
  }
});

var customButton = document.querySelector('#custom-button');
customButton.addEventListener('click', function() {
  console.log('Clicked!');
});
</script>
```

Is it possible to add more options to the toolbar in listmonk? Besides button I can think of certain pre-formatted elements, like a divider with `<hr />` or even images with caption etc.

**Comment by mdehollander** [comment]
I have also tried to format a button with markdown by adding an extra class to a link, but that does not render a button unfortunately.

```
[Link button](http://example.com/){: .button }
```

**Comment by knadh** [comment]
An `insert HTML` button that prompts for raw HTML should cover this and other usecases.

**Comment by mdehollander** [comment]
Thanks, that would work. I was also thinking of end-user who do not write code/html (and therefore use listmonk ;) Then a set of extra buttons would help, but I don't know how much work that would be.

In Mailpoet (wordpress-plugin) it looks like this:
![image](https://user-images.githubusercontent.com/262872/124503263-79ff4380-ddc5-11eb-8703-2fbd2cf907d8.png)

I had something more in mind like that when I opened the issue. At least some icons for a button, spacer and divider would help people already a lot I think.

**Comment by henk23** [comment]
I also had the need to customize the quill editor. Something easy to implement could be a flag for the binary, something like:
`./listmonk --quill-config=my-quill-config.json` or similar

Have you ever considered using TinyMCE instead of Quill? My current solution is that I have a TinyMCE editor on an external page where my client can edit their newsletter. With that content I create a new campaign via the listmonk api and send my client to listmonk where they can preview and send.

**Comment by henk23** [comment]
@NicoHood, yes that was the plan. But that is not working at this moment. The feature has not been developed (yet).

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/df314265664ced63c4f3cb810c2f7f3a0ff87192 adds a new button to the toolbar that pops a dialog to quickly insert arbitrary HTML snippets where the cursor is on the editor.

![image](https://user-images.githubusercontent.com/547147/178789662-c6d146ad-a382-496b-89da-543459d5a293.png)

![image](https://user-images.githubusercontent.com/547147/178789237-ed0a87ef-f9f8-4b8e-af85-1f78980aecb7.png)
