### ISSUE TITLE
UX issue on Signup.zerodha.com

### ISSUE THREAD

**Issue by yashraj2312** [knadh/listmonk#420]
Hey Team,

I'm not sure whether this is the right repository or the right medium to post this issue here but signup.zerodha document upload page has some UX flaws in it.
If signup is paused because of invalid/wrong documents and the user wants to reupload some documents then after uploading there isn't any Next / Submit button available which leaves the user clueless about the next step.

Attaching the screenshot for your reference.
[IMAGE REDACTED]

As you can see that I have reuploaded the correct document but I can't see any next or submit button over here. I have no clue how to proceed next.

Looks like you have to add a Next/Submit button Component in VueJS.

P.S. - Your tech blog is awesome. Kudos to you guys for disrupting the brokerage industry.

HMU if you want me to reproduce this or get more clarity on this issue.

**Comment by knadh** [comment]
This is not the appropriate forum. I've removed the image as it contains your personal information. Please raise a ticket with Zerodha.
