### ISSUE TITLE
One binary to serve multiple URLs

### ISSUE THREAD

**Issue by roshanjonah** [knadh/listmonk#421]
Just a quick question on whether one single binary generated by go build can support multiple list monks - the same binary but when running, it will run pointing to separate config.toml file.

**Example:**
```
/usr/bin/listmonk --config /path/to/database1/config.toml
/usr/bin/listmonk --config /path/to/database2/config.toml
```

Is that possible or would there be some sort of conflict?

**Comment by mr-karan** [comment]
This is possible, no conflicts will happen if you use different DBs.
