### ISSUE TITLE
Missing NO_COLOR

### ISSUE THREAD

**Issue by spravil** [knadh/listmonk#422]
If you run the script the terminal is colored green because the NO_COLOR command is missing.

https://github.com/knadh/listmonk/blob/9e61bfc5dfb43dc61b5d6de44cf2c3cb727131c1/install-prod.sh#L23

**Comment by mr-karan** [comment]
Can you give more details of your environment. Particularly which OS, shell etc.

**Comment by spravil** [comment]
Debian 10 + PuTTY. But this is not required to replicate this issue. The other logging functions use NO_COLOR correctly.
For example:
```shell
error() {
  printf '%s\n' "${RED}x $*${NO_COLOR}" >&2
}
```
So 
```shell
completed() {
  printf '%s\n' "${GREEN}✓${GREEN} $*"
}
```
should be 
```shell
completed() {
  printf '%s\n' "${GREEN}✓ $*${NO_COLOR}"
}
```.
