### ISSUE TITLE
Won't run on windows 10

### ISSUE THREAD

**Issue by jcvw75** [knadh/listmonk#424]
**Version:**
 - listmonk: [v1.1.0]
 - OS: [Windows 10
![listmonk](https://user-images.githubusercontent.com/15347314/127318817-e8100b76-2427-4ec9-8109-ab828b5085d3.png)
]

**Description of the bug and steps to reproduce:**
After the screenshot shown/attached, 'Access is denied' in command prompt. I've tried running the command prompt as administrator and also running the app listmonk.exe as administrator. Neither works, just keep getting that same screenshot.
Windows version is as per screenshot, Microsoft Windows [Version 10.0.19042.1110]
Postgresql was also running without problems on windows. Windows 10 is 64-bit

**Screenshots:**

**Comment by Mattifyed** [comment]
I just tried this on my Windows system version: 10.0.22000 Build 22000 and it worked. Hadn't set up Listmonk, so it didn't start, but the binary did run.

![image](https://user-images.githubusercontent.com/56337463/127327022-bc66da42-71fd-48fb-9efc-14828a699fb0.png)

I'm on an early build of Win11, technically, but there's no real difference for running Win10 apps.

**Comment by knadh** [comment]
Thanks @Mattifyed. @jcvw75 the binary runs fine on Windows. It looks like something to do with permissions on your system and not listmonk itself. Googling "This app can't run on your PC" shows useful [links](https://windowsreport.com/app-cant-run-windows-10/) that might help debug this.

**Comment by jcvw75** [comment]
I am already using administrator account and I have run out of options where to tweak permissions. Disabled smartscreen, enabled developer mode. Still the same thing.

**Comment by jcvw75** [comment]
Not sure if it's related..
https://github.com/golang/go/issues/43529

**Comment by jcvw75** [comment]
I tried to use UPX to pack/check the exe and I get this.

                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96w       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: listmonk.exe: EOFException: premature end of file

**Comment by knadh** [comment]
I'm not sure what's happening here. The release does run on Windows 10/11 as @Mattifyed reported.

> Not sure if it's related..
> golang/go#43529

listmonk does not use cgo or have any DLL dependencies. 

> I tried to use UPX to pack/check the exe and I get this.

The EXE does not come packed with UPX.

**Comment by jcvw75** [comment]
Ok so any idea if I can build the binary myself in windows 10? I've installed golang 1.16 and nodejs. Just not sure what to use for the Makefile

**Comment by jcvw75** [comment]
Ok guys, never mind. I found the issue. Winrar 5.* can't handle the archive and was corrupting the exe file upon extraction. I switched to 7-zip and all problems went away.

**Comment by knadh** [comment]
Thanks for the update, and glad it worked!
