### ISSUE TITLE
Is there a short list of best practices for backing up?

### ISSUE THREAD

**Issue by weisisheng** [knadh/listmonk#425]
I am taking snapshots of AWS EC2 instance and I am guessing there is a postgres backup workflow using docker.  Would appreciate any tips, tricks...Otherwise outstanding software!

**Comment by mr-karan** [comment]
@weisisheng Disk snapshots are fine in most cases. If you want to store the backups in a different location apart from a VM snapshot, you can run a simple cronjob on the EC2 Instances which fires up `pg_dump`, backup entire DB, compress and push the archive to somewhere like S3. It can be a simple shell script.
