### ISSUE TITLE
`preconfirm_subscriptions` only implemented for `POST`, not `PUT`

### ISSUE THREAD

**Issue by totycro** [knadh/listmonk#426]
**Version:**
 - listmonk: 1.1.0
 - OS: Docker

**Description of the bug and steps to reproduce:**
When adding a list to a subscriber via the PUT endpoint with `preconfirm_subscriptions`, the list subscriptions won't be confirmed and also a confirmation email is sent.

Checking for preconfirmation is currently only implemented for the `POST` endpoint, i.e. here:
https://github.com/knadh/listmonk/blob/master/cmd/subscribers.go#L682

Probably, there should be something like `if !req.PreconfirmSubs {` before this line, as well as setting the confirmation status for these subscriptions:
https://github.com/knadh/listmonk/blob/master/cmd/subscribers.go#L348

***Steps to reproduce***
For a user having e.g. no list subscriptions, this call will create unconfirmed subscriptions and send out emails:
```
curl -v https://mylistmonk/api/subscribers/82 -X PUT -H "Content-Type: application/json" -d '{"email": "foo@example.com", "name": "foo", "status": "enabled", "lists": [2], "preconfirm_subscriptions": true}'
```

This call however will  create confirmed subscriptions and not send emails:
```
curl -v https://mylistmonk/api/subscribers -X POST -H "Content-Type: application/json" -d '{"email": "foo@example.com", "name": "foo "status": "enabled", "lists": [2], "preconfirm_subscriptions": true}'
```

**Comment by knadh** [comment]
Thanks for reporting this. Fixed on the develop branch: https://github.com/knadh/listmonk/commit/e6566189ed7669bbfa5b70f223003b73d733ab5f
