### ISSUE TITLE
Sending confirmation mail fails

### ISSUE THREAD

**Issue by Citrullin** [knadh/listmonk#435]
**Version:**
 - listmonk: v1.1.0 (b361292 2021-06-09T14:49:25Z)
 - OS: Debian GNU/Linux 10 (buster)

**Description of the bug and steps to reproduce:**
I have a running listmonk instance to a connected SMTP server. Sending mails isn't an issue. I tried to subscribe via the subscription form under `/subscription/form`. The confirmation mail isn't sent. Instead I get the error message 
```
2021/08/14 16:00:30 manager.go:332: error sending message 'Confirm subscription': mail: expected comma
```

**Comment by knadh** [comment]
Unable to reproduce this and no reports either. What SMTP server are you using?

**Comment by Citrullin** [comment]
> Unable to reproduce this and no reports either. What SMTP server are you using?

Postfix as mail server and Dovecot for the SMTP/IMAP.

**Comment by Citrullin** [comment]
@knadh If you need a setup for investigations, I can create a temporary setup. Should I send you an email, so we can discuss the details?

**Comment by knadh** [comment]
@Citrullin sorry, got caught up. Yes, if you can drop me an [e-mail](mailto:kailash@nadh.in), we can try and debug this.
