### ISSUE TITLE
campaign automatically stopped at 12000 messages sent,

### ISSUE THREAD

**Issue by craftpip** [knadh/listmonk#436]
hello, 

recently i've started using listmonk, and had run a few campaigns with around 20k subscribers each. 
After starting the campaign all have them automatically paused at 12000 messages. 

is there a condition for 12k messages per day per campaign ?

the tool is wonderful, keep up the work !

**Comment by knadh** [comment]
Campaign automatically pauses on crossing an error threshold. You can check `Settings -> Logs` to see what it says. The error threshold can be configured in `Settings -> Performance`.

**Comment by Aman-design** [comment]
please deploy new version on heroku so that new version can be used easily.
version name :- (v1.1.0)
