### ISSUE TITLE
new version 

### ISSUE THREAD

**Issue by Aman-design** [knadh/listmonk#437]
please deploy new version on heroku so that new version can be used easily.
version name :- (v1.1.0)

**Comment by Citrullin** [comment]
This isn't the correct repository. You can find the Heroku repository [here](https://github.com/bumi/listmonk-heroku). 
Shouldn't be too hard to fork it, bump the version and create a PR for it. 
Actually there is already a [fork](https://github.com/jammed-org/listmonk-heroku) with the bump version.
You should be able to deploy it with the following [link](https://heroku.com/deploy?template=https://github.com/jammed-org/listmonk-heroku).

**Comment by Aman-design** [comment]
i want new version name :- (v1.1.0) all the version which are deployed is v0.8.0-beta
