### ISSUE TITLE
new version 2.0.0

### ISSUE THREAD

**Issue by Aman-design** [knadh/listmonk#439]
how can we get listmonk version 2.0.0 please give button to deploy this to heraku

**Comment by knadh** [comment]
Working on a new deployment script for Heroku that will install the latest version automatically. Give me a day or two to close this.

**Comment by knadh** [comment]
The Heroku button on the README now automatically pulls and installs the latest listmonk release.

The source for the install buildpack is available here: https://github.com/knadh/listmonk-heroku
