### ISSUE TITLE
internal server error when using unsubscribe link?

### ISSUE THREAD

**Issue by sweetppro** [knadh/listmonk#442]
list monk 1.1.0
Ubuntu 18.0.4

I just sent out a campaign,
a users are get the internal server error when trying to unsubscribe through the link included in the newsletter?
also no log message is generated

**Comment by knadh** [comment]
Haven't encountered this or seen this reported anywhere. If there was an internal error, there should have been a log in the error, unless the app is somehow crashing and restarting? Are you recording stdout on the server somewhere to check this? Are you able to reproduce this yourself with an unsub link?

**Comment by sweetppro** [comment]
I can reproduce it through a test user I send to myself, its crashing every time I hit the unsubscribe link,
here's the apache log:
500 GET /subscription/240debd8-0f14-4797-a558-c4860ce09dcd/c308ab72-f955-4cc8-bed1-9d5318456966 HTTP/1.0

**Comment by knadh** [comment]
Unable to reproduce this on v1.1.0 and no other reports so far. If it's crashing, there will be a stack trace. Can you check the stdout logs/stack trace on the server? If you're running the Docker container, Docker would have have recorded the stdout.

**Comment by sweetppro** [comment]
no error message are posted anywhere...

**Comment by sweetppro** [comment]
what's the sql cmd which the unsubscribe button runs?
maybe there's something up with my db again...

**Comment by knadh** [comment]
[This](https://github.com/knadh/listmonk/blob/185d5111d7e118eb2f846d1ce64bcf7f4a3a8d09/queries.sql#L14) is the only query that's executed for rendering the page.

**Comment by sweetppro** [comment]
I have this nginx error:
`20937#0: *1452332 open() "/var/www/vhosts/…/listmonk/subscription/240debd8-0f14-4797-a558-c4860ce09dcd/c308ab72-f955-4cc8-bed1-9d5318456966" failed (2: No such file or directory) `

**Comment by sweetppro** [comment]
interesting,
when I start it with the flag:
`--static-dir=static`

I get the crash,
when started without the static directory, no crashing

**Comment by sweetppro** [comment]
my static directory was out of sync with the current release.
Its now working
:)
