### ISSUE TITLE
Database connection lost after some time

### ISSUE THREAD

**Issue by ChrisTG742** [knadh/listmonk#447]
**Version:**
 - listmonk: v1.1.0
 - OS: Debian Buster
 - Docker: 20.10.8

When running as docker installation, the connection between app and db is lost after some time (~10 minutes). It seems to be connected to inactivity, so maybe the database/database connector closes the channel itself?

![grafik](https://user-images.githubusercontent.com/25579378/131501619-364b7db4-6984-4901-ba58-97b4bdcc3c5b.png)

It does not seem to be a docker network problem, because the iptables-rule and the mapped port are still there:

-A DOCKER -d 172.26.0.2/32 ! -i br-2056be1f26a9 -o br-2056be1f26a9 -p tcp -m tcp --dport 5432 -j ACCEPT

nc -z -v 0.0.0.0 9432
0.0.0.0: inverse host lookup failed: Unknown host
(UNKNOWN) [0.0.0.0] 9432 (?) open

Any ideas?

**Comment by knadh** [comment]
listmonk uses a connection pool where many connections are created, re-used, and thrown away. If there is no connection at a given moment after a lot of idling, the pool should transparently just create one and use it.

`connection timed out` indicates that a new connection attempt was made from the app to the Postgres server, but it never completed.

**Comment by ChrisTG742** [comment]
Thanks for your reply. It brought me to the right direction.
I'm a step further now, it rather seems an issue with my hoster's cron-based updater script which handles the iptable-rules. It seems to be confused by the additional rules Docker inserts for the bridge iterfaces.
So TL;DR: It's obviously no listmonk bug, so this issue can be closed here.
BTW: It is possible to activate logging to /var/log or something inside the containers? It would make debugging a lot easier.

**Comment by mr-karan** [comment]
> BTW: It is possible to activate logging to /var/log or something inside the containers? It would make debugging a lot easier.

Any specific reason? You can just configure Docker logging driver and use one of the many drivers to store container logs (from STDOUT) to somewhere durable on your machine to inspect it later.

For eg, take a look at https://docs.docker.com/config/containers/logging/configure/. `journald` is quite nice to use (IMHO) :)
