### ISSUE TITLE
Root URL Settings, SSL, HELO hostname

### ISSUE THREAD

**Issue by candideu** [knadh/listmonk#448]
Hello! I've deployed the app in Heroku and I'm filling out the Settings. I'm still pretty new to this.

Under the "General" tab, I'm not sure what to put for "Root URL - Public URL of the installation".

I have a domain name for my site already -- should I create a subdomain with my registrar? If so, are there any resources on doing so, and what I should be pointing things to?

Is the root URL the same thing that I would enter in the "HELO hostname" field of the "SMTP" tab in the settings?

Lastly, I have SSL set up through my registrar. If I set up this root URL to a subdomain, will it apply to Listmonk?

**Comment by knadh** [comment]
> Under the "General" tab, I'm not sure what to put for "Root URL - Public URL of the installation".

It's the URL of your Heroku app, the default Heroku domain or whatever custom domain you may have assigned to it. So either your-site.herokuapp.com or yourcustomsite.com (or a subdomain if that's what you're assigning)

> Is the root URL the same thing that I would enter in the "HELO hostname" field of the "SMTP" tab in the settings?

`HELO` is SMTP specific. If your SMTP server does not ask for it, it should be left blank.

> Lastly, I have SSL set up through my registrar. If I set up this root URL to a subdomain, will it apply to Listmonk?

hm, I'm not sure what this means. You should refer to Heroku docs on SSL for custom domains.

**Comment by candideu** [comment]
Thanks for your help @knadh! Using the Heroku domain worked. 😄 

For Heroku: since I'm on the free plan, the SSL only works if I use the Heroku-provided domain.

**Comment by MaximilianKohler** [comment]
>HELO is SMTP specific. If your SMTP server does not ask for it, it should be left blank.

I was searching for "HELO hostname amazon ses", and [Amazon seems to reference EHLO instead](https://docs.aws.amazon.com/ses/latest/dg/smtp-connect.html). 

[This says they're the same](https://www.ibm.com/docs/en/ias?topic=usm-ehlo-procedure-perform-initial-handshaking-smtp-server-return-extended-information):

>The EHLO procedure allows the client to identify itself to the SMTP server. The [HELO](https://www.ibm.com/docs/en/SSHRBY/com.ibm.swg.im.dashdb.apdv.sqlpl.doc/doc/r0055186.html) procedure performs the equivalent functionality, but returns less information about the server.

I had mine on listmonk.mydomain.com, the same as the "root URL", but I guess I'll remove it.
