### ISSUE TITLE
Ability to change template email titles

### ISSUE THREAD

**Issue by atbe** [knadh/listmonk#449]
**Is your feature request related to a problem? Please describe.**

I'm not able to change the title of the email confirmation because it's hardcoded in the `en.json` file

https://github.com/knadh/listmonk/blob/edac5a1910c5a8eadd21cb97107e71e4229e3bf8/i18n/en.json#L85

**Describe the solution you'd like**

The ability to change the email template title would be very helpful. I'm not sure where you would store this or how you would make it configurable, but ideally modifying the `static` template assets would be nice.

**Comment by knadh** [comment]
You can copy the en.json file, customize it, put it in a custom directory somewhere, and pass that path to listmonk with the `--i18n-dir` flag.

**Comment by atbe** [comment]
Oh that's awesome, thanks @knadh can I add this to the documentation?

**Comment by knadh** [comment]
Yes sure. Can go here: https://listmonk.app/docs/i18n/ I guess.

Source: https://github.com/knadh/listmonk-site/tree/master/docs/docs
