### ISSUE TITLE
Add a -y flag to install command 

### ISSUE THREAD

**Issue by NicolaiSchmid** [knadh/listmonk#45]
I'm running the installation automatically via a Kubernetes job, and currently I need to pass y into the binary:
```
yes | ./listmonk --install
```
This is a little hacky and I would prefer and `-y` flag for the install to run it automatically

**Comment by mr-karan** [comment]
You should actually be writing a one time [Job](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) which is the standard way to do one off things.

> This is a little hacky
Yep, it's only there in `docker-compose` for a quick demo setup.

> install to run it automatically
The `--install` flag wipes the DB, it's better if you run this job manually once while setting up K8s env.

**Comment by NicolaiSchmid** [comment]
No. There are no extra benefits. It's just nice to have a simple 'helm install' and have it running

**Comment by knadh** [comment]
@mr-karan Would `-y` be added to the Docker routines or to listmonk's flags?

**Comment by NicolaiSchmid** [comment]
To listmonk itself, since it asks for confirmation during install

**Comment by knadh** [comment]
Added to the upcoming release. Cheers.

**Comment by knadh** [comment]
Added in https://github.com/knadh/listmonk/commit/427dd93d3bf99541d5fa82f0fcb208426300fa6f. Next release will happen after closing a few pending commits.

**Comment by patrickleet** [comment]
@NicolaiSchmid did you ever make that helm chart?

**Comment by NicolaiSchmid** [comment]
Yes, I have. However I haven't updated it in months, it's still running an old version and it's not perfect, it regenerates the password on each `helm upgrade`. 
If you can help me with that issue, I can see if I find some time over the weekend to publish it

**Comment by patrickleet** [comment]
I can help finish it up

**Comment by NicolaiSchmid** [comment]
https://github.com/NicolaiSchmid/helm-charts/pull/1
