### ISSUE TITLE
Gets subscribers with an SQL expression in Postman

### ISSUE THREAD

**Issue by marcofucito** [knadh/listmonk#451]
Hello,
I am not able to use Sql Expression in Postman.
The API call returns me all subscribers ignoring the query.
Follows screen.
Can you help me?

P.S. The ["querying and segmentation"](https://listmonk.app/querying-and-segmentation#querying-and-segmenting-subscribers) guide indicated on the [docs](https://listmonk.app/docs/apis/subscribers/#get-apisubscribers_1) returns 404 error

Thanks

![SQL expression in Postman](https://user-images.githubusercontent.com/23509784/131650706-d58d6035-9630-44b3-adf0-66443f507270.jpg)

**Comment by knadh** [comment]
Not familiar with Postman. Maybe the `=` is not being encoded properly in the query? @mr-karan ?

**Comment by mr-karan** [comment]
@marcofucito It'll be helpful if you can copy paste the raw `curl` command here. (Code -> Generate Code Snippets -> cURL)

**Comment by marcofucito** [comment]
Sure and thank you very much for your attention

```
curl --location --request GET 'http://localhost:9000/api/subscribers' \
--header 'Authorization: Basic hidden==' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'query=subscribers.name = '\''Test'\'''
```

**Comment by knadh** [comment]
`--data-urlencode 'query=subscribers.name = '\''Test'\'''`

The `=` sign in the SQL query after `.name` is not being URLencoded. Not sure how Postman handles the `=` character in param values, but that's a good place to start looking.

**Comment by marcofucito** [comment]
I tried to call the API directly from the terminal using the command shown in the[ official doc](https://listmonk.app/docs/apis/subscribers/#get-apisubscribers_1)

I ran the following command in the terminal

```
curl -X GET 'http://localhost:9000/api/subscribers' \
--header 'Authorization: Basic hidden==' \
-d 'page=1' \
-d 'per_page=1' \
-d "query=subscribers.name = 'null'”
```

here too it shows me all subscribers who do not agree with the query

![query](https://user-images.githubusercontent.com/23509784/131664939-076854cb-bd78-472a-b807-f9d941b7f426.jpg)

**Comment by knadh** [comment]
You can run the query from the UI, inspect the request in the browser console and `Copy as cURL` from there and compare.

**Comment by marcofucito** [comment]
Thanks @knadh for your advice.
Doing as you told me I discovered that the UI via browser puts the query in the "Params" and not in the Body as indicated in the [doc](https://listmonk.app/docs/apis/subscribers/#get-apisubscribers_1).

I paste below the curl request made from the dashboard, copied with the safari inspector

```
curl 'http://localhost:9000/api/subscribers?list_id=&query=subscribers.name%20%3D%20%27marco%27&page=1&order_by=updated_at&order=desc' \
-X 'GET' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Referer: http://localhost:9000/subscribers' \
-H 'Accept-Language: it-it' \
-H 'Host: localhost:9000' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15' \
-H 'Authorization: Basic hidden==' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'Connection: keep-alive'
```

By putting the query in the parameters, it now works as both curl in the terminal and Postman
(I removed unnecessary headers)

```
curl --location --request GET 'http://localhost:9000/api/subscribers?query=subscribers.name='\''marco'\''' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Authorization: Basic hidden ==' \
--header 'Accept-Encoding: gzip, deflate' \
--header 'Connection: keep-alive'
```

![query_ok](https://user-images.githubusercontent.com/23509784/131672443-290ef881-7459-42b9-9085-566131ad9ea1.jpg)
