### ISSUE TITLE
 ERROR: [Errno 2] No such file or directory: 'install'

### ISSUE THREAD

**Issue by Waelsabry36** [knadh/listmonk#453]
root@bee-HP-Z820-Workstation:/home/jo/projects/listmonk# make dist
go get -u github.com/knadh/stuffbin/...
go: downloading github.com/knadh/stuffbin v1.1.0
cd frontend && yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
make: * [Makefile:36: frontend/node_modules] Error 1
root@bee-HP-Z820-Workstation:/home/jo/projects/listmonk#

**Comment by knadh** [comment]
Don't think you have the right `yarn` installed. https://yarnpkg.com/

I recommend you use a pre-built binary from the releases page or use the Docker instance.

**Comment by lcuis** [comment]
On Ubuntu, to solve this issue, I had to:
```
sudo apt-get install yarnpkg
```
Edit the listmonk `Makefile` to set:
```
YARN ?= yarnpkg
```
