### ISSUE TITLE
Sending through multiple domains/smtp servers

### ISSUE THREAD

**Issue by khinlatt** [knadh/listmonk#454]
This may be related to https://github.com/knadh/listmonk/issues/178 but I couldn't find the answer.

I'm wondering if this is possible. Here is the scenario:

I have two smtp servers: noreply@domain1.com and noreply@domain2.com configured. When sending a campaign, I want the load to be spread out over those two smtp servers as intended. However, since we need to provide from email address on the campaign and if I provide noreply@domain1.com as the FROM address, then half of the load that goes through the other smtp server would not work properly as the FROM email is not valid. Could you please advise?

I've also read about toggling smtp servers on and off. But does that mean I must send one campaign via one server only and it's not possible to share the load?

Thank you very much in advance! By the way, this is such a great project; it's been a treat to use without any issues, until recently when we had to add another smtp server.

**Comment by knadh** [comment]
If you use multiple SMTP servers, they should all be configured to work with whatever from address you choose. That said, you can try if setting a custom "From" header in the SMTP settings (`Set custom headers` option below the SMTP config) works.

```json
[
    {
        "From": "custom@domain.com"
    }
]
```

**Comment by khinlatt** [comment]
Thank you very much, @knadh! I can confirm that it works successfully and overrides what was provided on the Campaign page.

I do have one more question to follow up with. Is there a place to set up a FROM name separately? For e.g., instead of specifying `No Reply <custom@domain.com>` on the Campaign page, is there a way to set up a different FROM name (without the email address) on each campaign? Thanks for you help.

**Comment by knadh** [comment]
hm, I don't understand. You can just do `Whatever Name <custom@domain.com>` on the campaign, right?
