### ISSUE TITLE
Updating Subscriber Info for Duplicate Entries, "Manage/Update Your Preferences" Link

### ISSUE THREAD

**Issue by candideu** [knadh/listmonk#455]
Hello!

I've been running a few tests with subscriptions and lists. I like that existing subscribers can opt in to more public lists via the form, in case new lists were created after they subscribed.

**Is your feature request related to a problem? Please describe.**

That said, when you submit the same email under a different name, it doesn't update to the new name. Subscribers also aren't alerted that they've already signed up.

**Describe the solution you'd like**

- If the email is already in database and a person subscribes again, ask subscriber if they would like to update their info (or send them an email to update their info to protect privacy?)
- Have an "update your preferences" link at the bottom of each email campaign (beside the unsubscribe link, or have it be the same link?) so that people can opt in and out of different public lists, update their name, etc.

**Comment by knadh** [comment]
> Have an "update your preferences" link at the bottom of each email campaign (beside the unsubscribe link, or have it be the same link?) so that people can opt in and out of different public lists, update their name, etc.

This makes sense.

**Comment by Sebastix** [comment]
> Have an "update your preferences" link at the bottom of each email campaign (beside the unsubscribe link, or have it be the same link?) so that people can opt in and out of different public lists, update their name, etc.

+1

Was looking in de docs if there was a template variable for this, but such a page isn't provided (yet) by Listmonk. Would be a nice feature!

**Comment by knadh** [comment]
Admin setting to toggle preference management on/off.
![image](https://user-images.githubusercontent.com/547147/198825073-4cd61d0c-20b8-4085-a187-c997966de5c9.png)

`Manage` link on the existing unsub UI.
![image](https://user-images.githubusercontent.com/547147/198825103-a7342759-1af2-4817-8d12-7abecad0a97e.png)

New `Manage` page.

![image](https://user-images.githubusercontent.com/547147/198825125-c38fb207-d644-4fd8-a828-e85ed5669f24.png)

**Comment by candideu** [comment]
Nice! 😍

**Comment by Sebastix** [comment]
@knadh Very nice!
When will it be available in a new release? I'm running the application with Docker and the latest release (image) is 2.2.0 if I'm correct?

**Comment by knadh** [comment]
v2.3.0 should be in out in a week or two.

**Comment by candideu** [comment]
Sidenote for anyone who ran into the same issue as me with activating the "Manage subscription" link:

Make sure you have "Allow preference changes" toggled on in the backend:

![image](https://user-images.githubusercontent.com/55474996/217415941-1e230497-c10a-4179-a126-759370cae357.png)


Then, people can manage their preferences like this:

https://user-images.githubusercontent.com/55474996/217415196-11bc10b7-1692-4f52-99ed-30c064076bc5.mp4
