### ISSUE TITLE
Change in Username and password

### ISSUE THREAD

**Issue by Aman-design** [knadh/listmonk#456]
Respected Knadh, this message is to enquire you about that is we can change username and password of the app once deployed.
and second how to change logo displayed on dashboard.
eagerly waiting foe your response
thank you

**Comment by knadh** [comment]
You can change the username and password by editing `config.toml`.

The logo is bundled with the dashboard. To change it, you'll have to customize and [compile the app yourself](https://listmonk.app/docs/developer-setup/).
