### ISSUE TITLE
Subscriber List: Bulk Mass Edit and Delete

### ISSUE THREAD

**Issue by candideu** [knadh/listmonk#457]
**Is your feature request related to a problem? Please describe.**
Hello! When I'm on the Subscriber page, I'm able to "select all" and select multiple subscribers. However, I don't see an option to delete multiple and/or edit them all at once.

**Describe the solution you'd like**

- ability to select and mass delete subscribers within the app
- ability to select and bulk edit subscriber attributes, tags, lists, etc.

**Comment by knadh** [comment]
![image](https://user-images.githubusercontent.com/547147/132284313-6b747cd4-b4ef-44e8-bf5b-98a29d0362f4.png)

**Comment by candideu** [comment]
@knadh Not sure how I missed that, my bad! Is there any way to bulk edit attributes? Thank you.

**Comment by knadh** [comment]
It wouldn't be possible to meaningfully bulk-edit attributes as they are meant to be custom per user. You could easily do this with an SQL query though. `subscriber.attribs` is a single JSON field.
