### ISSUE TITLE
Relaunch campaign with api?

### ISSUE THREAD

**Issue by yonimoses** [knadh/listmonk#458]
Hi

Is there anyway to re-launch campaign via api (or some other method of doing that?)
For example, I’d like to create a generic campaign of a service having issues or downtime and I don’t want (I think so) to create a campaign every time and I though about just relaunching an existing campaign. 
also, besides the relaunch, it there anyway to launch a campaign with api ?

thank!

**Comment by knadh** [comment]
On the UI, there's a clone icon (hover on a campaign) with which you can clone an old campaign and create a new one out of it.

With the API, you could GET the campaign you want to clone, and POST the data from it creating a new campaign.

Yes, there are APIs for everything. You can inspect the browser requests as-is or refer to the [docs](https://listmonk.app/docs/apis/campaigns/).

**Comment by yonimoses** [comment]
thanks!
