### ISSUE TITLE
Cannot delete more than 30 subscribers at once

### ISSUE THREAD

**Issue by qvolant** [knadh/listmonk#459]
Version:

listmonk: v1.1.0 (b361292 2021-06-09T14:49:25Z)
OS: Ubuntu 21.04

Description of the bug and steps to reproduce:
Select more than 30 subscribers (by using the `Select all n` link), from the all subscribers list or a query result.
Click delete link, confirm deletion of n subscribers, get confirm message, yet all subscribers selected are still there, even after page reload.

I've imported a 10k subscribers test list with custom attributes to test things, and I don't really wanna delete them 30 at a time.

Looking at the browser inspector tools, it seems `list_ids` sent to the api is null
https://github.com/knadh/listmonk/blob/68369a8f136b0ac071fdd44d6b8558544b3546d2/frontend/src/views/Subscribers.vue#L419

EDIT : Works when deleting 30+ subscribers when coming from a list, doesn't work when deleting 30+ subscribers on the `All subscribers` page.

**Comment by knadh** [comment]
Ah, this is a bug, a regression. Needs a Cypress test case. Fixed here: https://github.com/knadh/listmonk/commit/1f4f4263a38a65c445a988f6e66f31a13aa1ed1c 

Making the API call with `list_ids: null` will work. For now, you can also run `TRUNCATE TABLE subscribers CASCADE;` on the DB.

Apologies for the hassle.
