### ISSUE TITLE
I/O timeout while send test message

### ISSUE THREAD

**Issue by freakyowner** [knadh/listmonk#461]
**Version:**
 - listmonk: v1.1.0
 - OS: [PhotonOS 4 - docker]

**Description of the bug and steps to reproduce:**
Can't send any email from any smtp server, only what I see in the logs is i/o timeout while connection to smtp server
My liistmonk works before adding new smtp server with wrong credentials, after that I have removed the new one and left only old

`2021/09/08 20:00:37v1.1.0 (b361292 2021-06-09T14:49:25Z)
2021/09/08 20:00:37reading config: config.toml
2021/09/08 20:00:37connecting to db: db:5432/listmonk
2021/09/08 20:00:38media upload provider: filesystem
2021/09/08 20:00:38loaded email (SMTP) messenger: user@domain.com@smtp.server.com
2021/09/08 20:01:20error sending message in campaign test: subscriber 
63cc7012-3bb6-4dad-b04a-7b653cdf1a75: dial tcp 213.77.69.19:587: i/o timeout`

**Comment by mr-karan** [comment]
Can you run this inside your container to see if it's a network connectivity issue?

https://github.com/knadh/listmonk/issues/393#issuecomment-860213887

**Comment by freakyowner** [comment]
![image](https://user-images.githubusercontent.com/73135609/132635472-e173f236-7b06-499e-b104-a392d95e5151.png)

**Comment by mr-karan** [comment]
Yeah so this indicates the SMTP server is unreachable from your host/container.

**Comment by freakyowner** [comment]
Okay, thanks for that info, that was problem with config of my firewall. 
Now listmonk connects correctly but does not send any message even though it shows "message has been sent" 
Nothing in logs, how can I check this ?

**Comment by mr-karan** [comment]
>  Nothing in logs, how can I check this ?

Possible to check SMTP server logs, if indeed you're getting the messages?

**Comment by freakyowner** [comment]
Thanks Karan, now works, that was additional problem with our SMTP server.
