### ISSUE TITLE
Unable to setup dev environment

### ISSUE THREAD

**Issue by mohit1795** [knadh/listmonk#462]
Tried setting up dev environment for contribution, but, facing with error every time I run `make dist`.
From the error I suspect it is unable to download 'stuffbin' package (since go get is deprecated) in the Makefile. Tried downloading the package manually but no luck.

Attaching error message.
`go get -u github.com/knadh/stuffbin/...
go get: installing executables with 'go get' in module mode is deprecated.
	To adjust and download dependencies of the current module, use 'go get -d'.
	To install using requirements of the current module, use 'go install'.
	To install ignoring the current module, use 'go install' with a version,
	like 'go install example.com/cmd@latest'.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
/home/user/go/bin/stuffbin -a stuff -in listmonk -out listmonk config.toml.sample schema.sql queries.sql static/public:/public static/email-templates frontend/dist/frontend:/frontend i18n:/i18n
make: /home/user/go/bin/stuffbin: Command not found
make: *** [Makefile:71: dist] Error 127
`

**Comment by knadh** [comment]
What version of Go are you running?

**Comment by mohit1795** [comment]
go1.17

**Comment by knadh** [comment]
Ah, this changed in `1.17`.  Can you manually run this for now? `go install github.com/knadh/stuffbin/...`

**Comment by mohit1795** [comment]
Tried this already it runs without any errors, but, for some reason again the Makefile throws error saying `stuffbin` not found while running other commands. 
Also checked for it at the `go/bin` path but did not find `stuffbin`.
Guess I'm doing some trivial thing wrong.

**Comment by mohit1795** [comment]
`go install github.com/knadh/stuffbin/...` cannot download dependency from web i guess. This is for local project building. However cloned the `stuffbin` manually and generated binaries, and the application started working. 
Thanks for the help.
I guess some changes are required in the Makefile. I can go ahead and do them if required for smooth installation process.

**Comment by knadh** [comment]
`go install github.com/knadh/stuffbin/...` This is not project specific. This installs Go binaries in the $GOPATH/bin directory globally. 

> I guess some changes are required in the Makefile.

Feel free to send your first PR changing `go get` to `go install` in the Makefile.
