### ISSUE TITLE
Drop & Drag Email Template and send to filtered selected lists

### ISSUE THREAD

**Issue by m0hamedessam** [knadh/listmonk#465]
Thanks you for awesome project and i would like to suggest some feature which i see is very important to be consider.

* Drop & Drag and rich text composer for adding new template.
* Add filter while you send campaign to filter from chosen lists based on many options like (sendinblue)
Example you choose list 1 and list 2 you want filter from both lists subscribers who open previous emails or only click on previous emails or who signup after or before a date like a month or a year.
its very important because to keep campaign more clean.

finally we will be nice to option on search on subscribers page to find subscriber based on views or clicks i cant find any option to filter that only on profile data json file you can see such info.

Thanks in advance.

**Comment by knadh** [comment]
Thank you. Closing this issue as the two matters are being tracked here:

Richtext editor: https://github.com/knadh/listmonk/issues/204

List segmentation: https://github.com/knadh/listmonk/issues/250

**Comment by knadh** [comment]
> finally we will be nice to option on search on subscribers page to find subscriber based on views or clicks i cant find any option to filter that only on profile data json file you can see such info.

Views and counts can be registered anonymously against campaigns with no subscriber data. I think searching subscribers where `count > x` is a very niche usecase. This can be easily achieved with an SQL query directly on the DB though.
