### ISSUE TITLE
Multi SMTP Server

### ISSUE THREAD

**Issue by m0hamedessam** [knadh/listmonk#466]
I see you can put more than 1 smtp server and i was wondering you have more than 1 smtp server.
app will choose which one to send ? 
and theres any option for priority to let app choose one over other or balance between them ?

**Comment by knadh** [comment]
The app will automatically split load between all active SMTP servers. Over the course of a campaign, this will work out to be an almost equal distribution.

>  and theres any option for priority to let app choose one over other or balance between them ?

There is no way to select an SMTP per campaign, but you could always enable/disable certain ones before sending campaigns.
