### ISSUE TITLE
Confirmation mails not getting send.

### ISSUE THREAD

**Issue by samrat2825** [knadh/listmonk#468]
I am new to this. So please bear with me.

Steps I followed:
1. Installed the listmonk binary on windows. Here is my config file

`[app]
address = "localhost:9000"
admin_username = ""
admin_password = ""

# Database.
[db]
host = "localhost"
port = 5432
user = "postgres"
password = "1234"
database = "samrat"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"
`
Here is the log:
![image](https://user-images.githubusercontent.com/44095348/133104814-ea2185ff-c35d-4fab-a75a-918380e5df0a.png)

My SMTP settings:
![image](https://user-images.githubusercontent.com/44095348/133104960-c886bfdf-700c-48b8-a13a-7922679f1def.png)

On adding a subscriber using the GUI (lets say in the default list) no confirmation mail is sent to that email.

**Comment by knadh** [comment]
Opt-in confirmation e-mails are only sent to subscribers added to opt-in lists.

**Comment by samrat2825** [comment]
Thanks it got sorted
