### ISSUE TITLE
emails sent status

### ISSUE THREAD

**Issue by marcofucito** [knadh/listmonk#469]
is it possible to monitor the status of the emails sent?

If I enter a non-existent email in a test list, the campaign does not seem to return any errors, and I have not found a dashboard page that shows the status and history of the emails sent.

If it doesn't exist yet, could it be a new feature?

To send emails I use amazon ses.

Thank you so much

**Comment by knadh** [comment]
> If I enter a non-existent email in a test list

If you are referring to the `Send test e-mail` feature on the campaign page, if you enter a non existent e-mail to test, it immediately throws an error.

Any SMTP errors while sending e-mails are logged in `Settings -> Logs`

**Comment by marcofucito** [comment]
@knadh thanks a lot for the answer

Using amazon ses as sending smtp server,
there is no trace of the failure in the logs.

However, even using a desktop mail client configured with the smtp server of Aamzon SES, if I send an email to a non-existent address, I do not receive any error message.
So I think maybe it depends on the Amazon SES smtp server.

**Comment by knadh** [comment]
The error is thrown by listmonk when it cannot find the e-mail in the subscriber list. Nothing to do with the upstream SMTP server. This is how it looks. 

![image](https://user-images.githubusercontent.com/547147/133655477-fd788a06-8c15-4171-8dca-214fe5ff7f0e.png)
