### ISSUE TITLE
Postgres: too many clients already

### ISSUE THREAD

**Issue by Jjagg** [knadh/listmonk#47]
After running listmonk on my cloud-hosted VM for a couple days, I can't connect anymore with postgres giving `sorry, too many clients already`. This is the second time this happened.

What's going on here? Shouldn't connections only be open for the duration of a request?

It seems weird to me that no one else ran into this issue yet (or at least opened a ticket for it), so I'm wondering if it could have anything to do with my set up. Feel free to ask for any information about the environment that might be relevant.

**Comment by knadh** [comment]
That's strange. Connections are pooled and reused. Been running in production for almost a year running a large list, but have never run into this. Are there other services connecting to the same Postgres instance? Also, can you check the `max_connections` settings on Postgres?

That said, I just realised, listmonk isn't setting maxActive and maxIdle connections values on the driver. Will add this in the upcoming release.

**Comment by Jjagg** [comment]
No other services, in fact other than listmonk only a very simple web API shim for the listmonk service is hosted on the VM. 
`max_connections` is set to 100. I did not touch this setting.

**Comment by knadh** [comment]
Added max open/idle config here https://github.com/knadh/listmonk/commit/6b6dc59067d7285ac033d261e0d6303268b24580. Will make a new release soon with a few other pending features.

When you run into this error again, could you please run `SELECT * FROM pg_stat_activity` and see what queries are occupying the available connections?

**Comment by Jjagg** [comment]
I'll do that. Thanks :)

**Comment by Jjagg** [comment]
I just forced some of the requests I handle on my server to test this and a few connections stay open on the same query:

- `wait_event_type`: Client
- `wait_event`: ClientRead
- `state`: idle in transaction
- Query:
```sql
SELECT COUNT(*) OVER () AS total, subscribers.*
FROM subscribers LEFT JOIN subscriber_lists 
  ON ( (CASE WHEN CARDINALITY($1::INT[]) > 0 THEN true ELSE false END) AND subscriber_lists.subscriber_id = subscribers.id )
WHERE subscriber_lists.list_id = ALL($1::INT[])  ORDER BY $2 DESC OFFSET $3 LIMIT $4;
```

**Comment by mr-karan** [comment]
Ah, spot on @Jjagg :+1: 

Looks like this query is executed [here](https://github.com/knadh/listmonk/blob/7ee71166fbc315a7fafdb91158a0995826f80cf5/subscribers.go#L112). Since a Transaction object is created, the connection will only be released if a `Rollback` or `Commit` happens. There's a rollback in case of error [here](https://github.com/knadh/listmonk/blob/7ee71166fbc315a7fafdb91158a0995826f80cf5/subscribers.go#L120) but no `Commit` in case of success, hence the connection is never released in this case.

**Comment by knadh** [comment]
Good spot @Jjagg @mr-karan. Fixed https://github.com/knadh/listmonk/commit/6747a95b3d8bb28e2ff8a4d8c55837fdb5d3c3be.
