### ISSUE TITLE
Add Reply-To field in UI

### ISSUE THREAD

**Issue by kevinlang** [knadh/listmonk#470]
First of all, thank you for creating Listmonk. After the new bounce handling feature comes out, it looks like something that can replace the proprietary Sendy application I use now. The UI is great and a big update from what I currently use.

Poking around, it seems that there is no way to set a Reply-To in the UI. This is useful in the scenario where I am sending from one domain that I am using SES for, e.g., `kevin@email.example.com`, but want all users to reply to a different email that I actually use and monitor, e.g., `kevin@example.com`.

It would be useful for this to be editable both in the New Campaign page and to be able to configure the default in the Settings page.

Thanks!

**Comment by knadh** [comment]
Thanks! You can add this as a header in the SMTP settings.

`{"Reply-To": "your@reply.com"}`

**Comment by knadh** [comment]
Ah sorry, I misread the last bit. Will think about per-campaign headers.

**Comment by kevinlang** [comment]
For my use case, I don't need the per-campaign reply-to. Just being able to set the header field, via that header settings you told me about, for all campaigns is enough for me. Thanks! :+1:

**Comment by charleshan** [comment]
I was searching for a way to add Reply-To field per campaign. Can we keep this issue open?
