### ISSUE TITLE
we need to add detailed Analytics report 

### ISSUE THREAD

**Issue by Waelsabry36** [knadh/listmonk#473]
Dears we need to add a detailed report for each campaign listing all subscribers with view count or (yes/no) and clicked links for each one also

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/issues/391

Analytics was merged today and will be available in the next release.

**Comment by mrhydejc** [comment]
The standalone analytics page show anonymous usage. It do not list suscribers as needed.
