### ISSUE TITLE
Listmonk at scale on deployed instances

### ISSUE THREAD

**Issue by hariria** [knadh/listmonk#475]
Really amazing job @knadh on Listmonk. For those who are using Listmonk in production, I'd love to know the specs of the instances you're using and how much they support. For example, for a simple newsletter, how much RAM and how many vcpus would I need to support 10,000 subscribers and 100,000 emails per month?

**Comment by jackdanielux** [comment]
I'm currently running on 5$ DO Droplet.  Far more subscribers and number of
emails.

**Comment by knadh** [comment]
@hariria here's a snapshot from our production instance in the middle of sending 7+ million e-mails. A fraction of a single VCPU and 57 MB of peak RAM usage. The upcoming 2.0 release (~in a week) has significant performance improvements specifically for large installations.

![image](https://user-images.githubusercontent.com/547147/133957588-11c88623-110a-4928-8c41-9b4dc69b5320.png)

**Comment by hariria** [comment]
Awesome thanks
