### ISSUE TITLE
Which email id is used to sent the mails is there some setup we need to for that

### ISSUE THREAD

**Issue by abhinav-TB** [knadh/listmonk#478]

**Comment by abhinav-TB** [comment]
during the test setup, i just tried to send a mail to one of my Gmail acc but I didn't receive any mail even though it showed mail sent

**Comment by mr-karan** [comment]
Check the logs from your SMTP instance.

**Comment by knadh** [comment]
Seems like you may not have configured an SMTP server in Settings -> SMTP. listmonk needs an external SMTP server to send out e-mails.
