### ISSUE TITLE
Multiple domains and the root URL

### ISSUE THREAD

**Issue by PaulVipond** [knadh/listmonk#479]
First, congratulations on a great piece of software, It's fitted nicely into my containerized environment, so thanks :-)

I noticed some questions previously about running with multiple domains. I'm using Amazon SES, so all of this is really easy, having a single SMTP server, separate lists per domain and changing the noreply email address per campaign.

I'd like to suggest a change to make the root URL also editable per campaign. In this way, the unsubscribe / user management URL would align with the noreply address (perhaps populated with the default). E.g. you would have noreply@mydomain.com and the root url possibly as lists.mydomain.com and you could change 'mydomain' for each campaign. Alternatively, if I've misunderstood how this could be achieved, it would be good to know.

Thanks again.

(As an aside, managing a separate subdomain for each root url would easily work for me as I use Traefik and could so something like this in the config for the service:

`       - "traefik.listmonk.frontend.rule=Host:lists.domain1.com,lists.domain2.com,lists.domain3.com;PathPrefix:/"
`

And have them all automatically managed with Lets Encrypt.)

**Comment by knadh** [comment]
Thanks @PaulVipond. Unfortunately, changing the app installation's root URL per campaign is infeasible technically. This is pattern only really exists in apps that are specifically built for multi-tenancy.
