### ISSUE TITLE
Is listmonk compatible with HTML5 emails?

### ISSUE THREAD

**Issue by bstarynk** [knadh/listmonk#48]
The motivation is explained in https://softwarerecs.stackexchange.com/q/71336/1877
If listmonk is indeed compatible with HTML emails, that should be stated in its README.

Thanks and Merry Christmas!

--

Basile Starynkevitch  - http://starynkevitch.net/Basile/
<basile@starynkevitch.net> Bourg-La-Reine, near Paris, France

**Comment by knadh** [comment]
Hi. listmonk supports HTML emails. The readme says `Rich Go templates and WYSIWYG editor` which implies HTML, but I'll add HTML anyway.
