### ISSUE TITLE
‘View this email in your browser’ feature

### ISSUE THREAD

**Issue by ibrahimcesar** [knadh/listmonk#486]
**Is your feature request related to a problem? Please describe.**
A "view this email in your browser" or "view in web" option to display the sent HTML.

**Describe the solution you'd like**

_What is the ‘view this email in your browser’ feature?_
This feature is a small piece of hyperlinked text usually found in the header of an email.

Also known as a ‘mirror link’, it allows you to offer an online version of your email to readers who may have trouble viewing HTML messages or have image loading turned off.

Including this feature ensures that the full version your email is viewable to all readers, regardless of their email client, settings, or any other rendering issues.

_Why include ‘view this email in your browser’?_
One of the most frustrating things in terms of user-experience is receiving an email with formatting or rendering issues.

While most email clients will now render images without a problem, some still automatically preset emails to not display images or hyperlinked images for security reasons.

A bad rendering experience is a sure-fire way to lose your email subscribers. It’s important to remember that many of your contacts may not have the knowledge (or the time) to review or change their email settings.

_Reasons to have a ‘View this email in your browser’ option_
Mirror links are not mandatory but you should still use them.

While many argue that rendering issues are now a minority case and the need for the feature is obsolete, there are still many valid reasons to point your readers towards a web version of your email:

- If you have a particularly image-heavy or interactive email (p.s. follow these best practices for newsletter images)
- To eliminate any concerns about display features in certain email applications
- To make your email code accessible to your users
- To encourage social sharing
- To allow people to bookmark your email if you’re sharing helpful information
- For accessibility reasons—some readers may need a web version to activate assistive technology
- If you simply like the idea of your readers having an option to view a web version of your email for an enhanced experience

_Customizable text_
- ‘View online’
- ‘View full email’
- ‘Read email here’
- ‘See more’
- ‘View in browser’
- ‘Trouble viewing this email?’

_Nice to have_
Display this online versions on another domain, to not expose the listmonk, but almost all tools expose anyway.

_Duplicate issue or already implemented?_
I did not found in any issue or in my test Docker application.

**Comment by knadh** [comment]
This already exists. You can use the [`{{ MessageURL }}`](https://listmonk.app/docs/templating/#functions) template function to generate a public message URL.

**Comment by ibrahimcesar** [comment]
Thanks @knadh ! I did not found it!

BTW, thanks a lot for the great work! Amazing tool!
