### ISSUE TITLE
SNS subscription not confirming

### ISSUE THREAD

**Issue by panbanda** [knadh/listmonk#487]
**Version:**
 - listmonk: 2.0.0
 - OS: Docker

**Description of the bug and steps to reproduce:**

I followed the mautic steps for setting up the subscription and everything works fine except the endpoint doesn't actually confirm the subscription and my SNS subscription in AWS still says "Pending confirmation"

Great job on the v2 release BTW.

**Comment by knadh** [comment]
Could be this? https://github.com/knadh/listmonk/issues/483. 

> Great job on the v2 release BTW.

Thanks!

**Comment by panbanda** [comment]
Yep. Missed that one 😄
