### ISSUE TITLE
Basic automation feature

### ISSUE THREAD

**Issue by alaahariri** [knadh/listmonk#488]
Such a great efforts, thank you! 

I have a question. Does this app have any automation features? For example, if a contact is listed in a specific segment, he would get a welcome email automatically.

**Comment by knadh** [comment]
Thank you. Auto-response on subscription is planned, but beyond that, no other automation for now.

**Comment by bamboowonder** [comment]
n8n is a great platform for automation of everything, including listmonk.   We use it to fill in the gaps we need.

**Comment by jackdanielux** [comment]
@bamboowonder how do you automate things for listmonk using n8n?  can you pls elaborate?

**Comment by bamboowonder** [comment]
n8n is able to do everything from bounce processing, to automating internal processes that trigger email etc etc.  Most of the way we manipulate it is directly in the postgres database, but then use the api for triggering an actual send. It is very specific to our business, but that is the whole point.  We could use Mautic, but then we are shoehorned into their elaborate idea of what marketing automation is.     n8n is a lot like zapier but way better.

**Comment by chrisgereina** [comment]
> n8n is able to do everything from bounce processing, to automating internal processes that trigger email etc etc. Most of the way we manipulate it is directly in the postgres database, but then use the api for triggering an actual send. It is very specific to our business, but that is the whole point. We could use Mautic, but then we are shoehorned into their elaborate idea of what marketing automation is. n8n is a lot like zapier but way better.

I was just thinking about creating an ListMonk node for n8n - any way I could see how you set up the functions you described? Or maybe just pick your brain on it
