### ISSUE TITLE
Complaint process with amazon ses/sns

### ISSUE THREAD

**Issue by bamboowonder** [knadh/listmonk#489]
Hey, Thanks for the bounce processing.   I'm on ver 2.0
I've setup the amazon ses/sns for bounce processing.
Should I use the same listmonk endpoint for the "complaints" and "delivery notification" SNS topics?
(https://listmonk.yoursite.com/webhooks/service/ses)

Or how does Listmonk handle complaints/spam notifications?   

Does it handle the delivery notifications from SNS?

Thanks a bunch

**Comment by knadh** [comment]
Right now, listmonk only processes complaints (bounces) and delivery notifications are ignored.

**Comment by bamboowonder** [comment]
By "complaints (bounces)" can you be specific about how they are handled?    (being they are very different animals).  Complaints need to be blocklisted immediately, whereas bounces may have variable attempts.
If someone marks an email as spam, they should be blocked immediately.  
Can you confirm that happens?   (sorry I don't want to test that as it affects my sending reputation)

**Comment by knadh** [comment]
Currently, all kinds of "bounces" (over-quota, arbitrary delivery issues, spam report, other complaints) are treated equally, and based on the threshold set in settings, irrespective of the type, the subscriber is either blocklisted or deleted.

Internally, listmonk does have "soft" and "hard" bounce types which leaves provision for treating bounces differently in future versions.

**Comment by bamboowonder** [comment]
Ok thank you.  I'll make a feature request for this.   In the meantime, I'll use the setting threshold of 1 for all bounces.
Ideally though, spam complaints would always be treated as an immediate and permanent blocklist.
And bounces or other delivery errors could be a user configurable threshold.
Email senders who don't honour spam complaints from users will see their inbox delivery rates plummet.
Cheers

**Comment by knadh** [comment]
This is now tracked here: https://github.com/knadh/listmonk/issues/497

**Comment by MaximilianKohler** [comment]
> Internally, listmonk does have "soft" and "hard" bounce types which leaves provision for treating bounces differently in future versions.

When trying to set up bounces, I noticed that Amazon SES's suppression list misses many bounces that otherwise get emailed to me via `SES -> Verified identities -> notifications -> Email feedback forwarding`. 

Amazon's docs aren't very good and don't mention soft bounces https://docs.aws.amazon.com/ses/latest/dg/lists-and-subscriptions.html#3-suppression-overview, so I'm wondering if soft bounces are excluded from the suppression list. If so, I'm wondering if soft bounce reports are even sent to Listmonk. 

I haven't been able to get Listmonk to read SES's bounce reports at all. But if Listmonk simply gets the data from SES's suppression list, then it would be incomplete.

**Comment by Chars4785** [comment]
@knadh 
i send email complaint@simulator.amazonses.com but listmonk notice message like that 'listmonk error processing SES notification: notification type is not bounc' how can i use Complaint handler ??

**Comment by MaximilianKohler** [comment]
What's your listmonk version? I don't have any issues on v2.5.1.

**Comment by Chars4785** [comment]
my version is v4.1.0. i want to handle complaint by aws SNS. i registed topic and subscribe. my site URL + /webhooks/service/ses. But it dosen't work help me... 

i wander bounce and complaint, that can handle by listmonk bounces??

<img width="1032" alt="Image" src="https://github.com/user-attachments/assets/3f5d7bed-c18c-4506-8d10-a3a3b688bc41" />

**Comment by MaximilianKohler** [comment]
Did you follow the directions in the docs? My guess is that you misconfigured something.

**Comment by Chars4785** [comment]
@MaximilianKohler hmmm..... but I received an email ( bounce@simulator.amazonses.com ). same setting...I want to know if complaint@simulator.amazonses.com can receive a webhook URL.

**Comment by MaximilianKohler** [comment]
It can. I've tested it numerous times. I use SES too.
