### ISSUE TITLE
Send later does not send at scheduled time

### ISSUE THREAD

**Issue by lbayerlein** [knadh/listmonk#49]
Hi,

first of all thanks for your work and time, to create a simple application for managing mails and newsletter.

I have got a question on campaigns and sending mails on a scheduled time. If I create a new campaign and configure date and time, it is not saved when clicking on the "continue" button. After klicking "continue" again, the campaign is save as "draft".

If I edit this campaign, the schedule is not set. If I do configure it again, I can tell "schedule", and it is set to status "schedule". But it will never be executed. There is some note under "schedule", that is always the same: "Scheduled — Tue 14 Jan 2020, 08:01 AM" - is that okay? I scheduled it on another time today, but this note would not tell, that its schedule correct.

Do I am something wrong, or does the application need more planning time in the future? I am only waiting minutes for executing tasks in the future.

If I can assist you in any way, please tell me.

Thanks!

**Comment by knadh** [comment]
@lbayerlein thanks. This was an issue in one of the older versions which I remember fixing. Can you confirm the version you're using?

**Comment by lbayerlein** [comment]
Hi @knadh, thanks for your quick reply.

I am using version 0.3.0-alpha. Downloaded from the release page yesterday evening.

**Comment by knadh** [comment]
Ah, this is indeed a bug. I'll investigate this over the weekend and push a patch. Thanks for reporting.

**Comment by knadh** [comment]
This is fixed in [v0.3.1-alpha](https://github.com/knadh/listmonk/releases/tag/v0.3.1-alpha).
