### ISSUE TITLE
Bounce processing with Return-Path address

### ISSUE THREAD

**Issue by andreafa** [knadh/listmonk#493]
The [Bounce processing documentation](https://listmonk.app/docs/bounces/) page
describes how to set the Reply-To address.

Using standard SMTP servers (not Amazon SES), 
the bounced emails go to the Return-Path address, also called “envelope sender”.
If not defined, it is set as the sending From address.

A solution could be to add a new Return-Path field in Settings -> SMTP.

**Comment by knadh** [comment]
Thank you for pointing this out. Updated [bounce docs](https://listmonk.app/docs/bounces/).

**Comment by andreafa** [comment]
Thanks for your answer.
I've tried adding the custom "Return-Path" header with the bounce inbox,
but the Return-Path address is always the same as the From address.

**Comment by knadh** [comment]
Your mail server is enforcing a certain `Return-Path` then. You could just set the "from" address as your return path.
