### ISSUE TITLE
Treat spam reports / complaints separately from other types of bounces.

### ISSUE THREAD

**Issue by bamboowonder** [knadh/listmonk#497]
With an end goal of optimum deliverability and reaching people's inboxes.   Email sender reputation is critical.   This is measured by email service providers in a number of ways.

Two of the benchmarks commonly used is how bounces and spam/complaints are handled.

In this context, a bounce is any failed/delayed delivery that is not "successfully delivered" or "spam/complaint".

There are degrees of severity with bounces.

Spam/complaints are extremely sensitive, and resending to anyone who has marked you as spam will immediately affect your **entire** domain's deliverability.

Bounces are less sensitive, and open to interpretation as to how many bounces per email are acceptable.   Email providers look at both the per-email bounces, and overall account bounce percentage when determining whether to put your email in spam or the inbox.

----------------
The current functionality for bounce threshold is great for letting the user determine what is acceptable.

However spam complaints should always be treated as an immediate hard block, since a Listmonk user may not even realize how badly it will affect their deliverability to resend.   And understandably they want to treat generic bounces separately.

Thank you for your consideration.

**Comment by jackdanielux** [comment]
But is spam/complaint treated as bounce for major SMTP providers?

If yes, only then this threshold of 1 will help, otherwise it would
continue to deliver it to their inboxes.
