### ISSUE TITLE
Error in bounce process

### ISSUE THREAD

**Issue by Aman-design** [knadh/listmonk#498]
**Version:**
 - listmonk: [eg: v1.0.0]
 - OS: [e.g. Fedora]

**Description of the bug and steps to reproduce:**

**Screenshots:**

Respected Knadh
i am getting this error while processing for bounce 
error processing SES notification: error getting SNS cert: invalid SNS certificate URL:

how can i solve this please help

**Comment by knadh** [comment]
Did you confirm the subscription on the AWS SES dashboard before receiving bounces?

**Comment by marcofucito** [comment]
@Aman-design  do you have a valid certificate verified by a certification authority (like let's encrypt) on the domain where listmonk resides?

**Comment by Aman-design** [comment]
> Did you confirm the subscription on the AWS SES dashboard before receiving bounces?

yes i did

**Comment by Aman-design** [comment]
> @Aman-design do you have a valid certificate verified by a certification authority (like let's encrypt) on the domain where listmonk resides?

yes it is hosted on heroku so it has verifies SSL

**Comment by aliblui** [comment]
Same error in my aws deployed instance. My host has a verified certificate chain provided by let's encrypt. Any suggestion? Thanks.

**Comment by nclarey** [comment]
I just ran into this issue - make sure you have followed the instructions correctly when setting up the SNS subscription! Raw message delivery has to be *disabled*.

![Image](https://github.com/user-attachments/assets/304a882b-f71e-402c-857f-257ac663a12d)
