### ISSUE TITLE
Error updating Subscriber: pq: duplicate key value violates unique constraint "subscribers_email_key". Key (email)=(email@email.cz) already exists.

### ISSUE THREAD

**Issue by charlesmudy** [knadh/listmonk#499]
**Is your feature request related to a problem? Please describe.**
When a subscriber exist already in another list, I am able to add the same user by email to another list which is fine. So a unique user [by email] can be in multiple list. But the problem is that a user email that belongs to multiple list can't be updated, I get this following error:

`Error updating Subscriber: pq: duplicate key value violates unique constraint "subscribers_email_key". Key (email)=(email@email.cz) already exists.`

**Describe the solution you'd like**
Perhaps if there is a way to make emails unique by the list they belong to rather than across the whole system. or remove it all together. In my case, we have multiple admin managing a list, each list is independent and emails can be repeated.

Appreciate a solution around this.

**Comment by knadh** [comment]
Can you show the API calls you are making? Updating a subscriber to one or more lists does not throw an error. List subscriptions are recreated on every updation, so there is no unique constraint violations that'll be thrown.

**Comment by charlesmudy** [comment]
I am updating this `/api/subscribers/22` using 'PUT'

So I think the issue is that Email can be added to multiple lists, which also means I can't edit an email in a list to another email that exists in another list.

Even by adding a new subscriber with an existing emails but to a different list doesn't get added simply because that email already exist.

I simply wish to be able to have emails independent on their list.

**Comment by knadh** [comment]
> So I think the issue is that Email can be added to multiple lists, which also means I can't edit an email in a list to another email that exists in another list.

Not sure whether I understand this. If you want to change the lists to which a subscriber belongs, simply past the list IDs to the `PUT /api/subscribers/22` call.  If a user belongs to lists `1,2,3` and you want to change them to `1,3`, just pass `1,3` in the call. If you wan them to add to a 4th list, pass `1,2,3,4`.

> Even by adding a new subscriber with an existing email but to a different list doesn't get added simply because that email already exist.

A subscriber is a first class global citizen in listmonk. Lists are simply properties added to that subscriber and you can add/remove lists as you want as illustrated above.

**Comment by charlesmudy** [comment]
@knadh Not sure why you close this ticket.

See the screenshot from the app.

![kk](https://user-images.githubusercontent.com/1445007/135715886-cdb47cc9-aa9b-40c8-a4a0-afffd1873d02.jpg)

One can't edit an email to another email that exist in another list.

**Comment by knadh** [comment]
This is not a bug and is working as intended. As I said, subscribers (e-mails) are global first class objects. You cannot edit an existing subscriber's e-mail to another subscriber's e-mail because that is a wholly different unique subscriber. If you want to, you should delete the other subscriber and then edit.
