### ISSUE TITLE
Integrate custom https api like amazon ses or sendgrid

### ISSUE THREAD

**Issue by lu-zen** [knadh/listmonk#500]
Hello.

Actually it's possible to add another send method alongside smtp? I really want to send campaigns via ses https api for example.

**Comment by knadh** [comment]
Yes, this is easily doable with Messengers. You setup an HTTP endpoint that receives messages from listmonk in a certain JSON format and relays them to whatever service (Settings -> Messengers). 

https://listmonk.app/docs/messengers/
