### ISSUE TITLE
How to configure the title of the mail received in campaign.

### ISSUE THREAD

**Issue by samrat2825** [knadh/listmonk#501]
I am new to listmonk and I want to change this name(title of the mail).

![image](https://user-images.githubusercontent.com/44095348/136008659-c0e09047-52e0-4f4d-8119-e8f078dcdb5b.png)

But, I found out that listmonk picks this name from the email address itself. 

![image](https://user-images.githubusercontent.com/44095348/136008837-f2404c75-615e-4946-b28c-d2c84e660608.png)

how can I change that name/title of the mail while keeping the address same.

**Comment by knadh** [comment]
You can configure this just once in Settings -> General. The standard format for displaying a name is:
`Your Name <your@email.com>`
