### ISSUE TITLE
Support Actual SSL/TLS

### ISSUE THREAD

**Issue by Apreche** [knadh/listmonk#504]
**Is your feature request related to a problem? Please describe.**
I noticed when configuring listmonk for the first time that it only offers STARTTLS for SMTP, and not plain old TLS. At least, that's what the footnote in the user interface seems to indicate. STARTTLS is a slight security issue in that it is at least theoretically possible for it to silently fall back to plain text transmission based on the server's response. 

**Describe the solution you'd like**
I would like the option to configure the SMTP server with TLS (not STARTTLS)

Thank you.

**Comment by knadh** [comment]
![image](https://user-images.githubusercontent.com/547147/148096395-26fb934e-e8ed-4f07-a87f-c1fbad0b4ccf.png)
