### ISSUE TITLE
Support for CloudFront or other CDN

### ISSUE THREAD

**Issue by Apreche** [knadh/listmonk#505]
**Is your feature request related to a problem? Please describe.**
listmonk already has support for uploading media into an S3 bucket. That's terrific. However, it is not always desirable to deliver content directly from the bucket itself. It is extremely common to put a CDN, usually AWS CloudFront, in front of the S3 bucket to handle the actual content delivery. Uploads still go to the S3 bucket, but the URLs in the emails would point at the CloudFront URL.

**Describe the solution you'd like**
Allow configuration of a CloudFront/CDN URL from which media uploaded to S3 will be delivered. When rendering emails, construct URLs pointing at the CDN host instead of at the S3 bucket directly.

**Comment by ciceroverneck** [comment]
I was needing this

Now I need to use the custom url in the admin (`/admin/campaigns/media`)

![image](https://user-images.githubusercontent.com/755111/152839038-9ed27a28-efc0-465d-bd78-8fcd456345c2.png)

**Comment by knadh** [comment]
This feature is already merged and will be available in the upcoming release this week.

**Comment by ciceroverneck** [comment]
Yep, but in `/admin/campaings/media` still using the  s3 link

**Comment by knadh** [comment]
Sorry, I am a bit confused. Are you running `master` or v2.0.0? Once a custom public URL is configured, it will be used everywhere, in the admin and in e-mails.

**Comment by ciceroverneck** [comment]
I'm using docker image: `listmonk/listmonk:rc5`

**Comment by ciceroverneck** [comment]
I just updated to v2.1.0, and from `/admin/campaigns/media` the images keep loading from the aws link.

/reopen

**Comment by knadh** [comment]
Please share a screenshot of your S3 settings UI.

**Comment by knadh** [comment]
The public URL seems to be incorrect. It should be something like `https://cc-newslatter.storage.googleapis.com`, right?

**Comment by ciceroverneck** [comment]
No, I use my own CDN that uses the same domain for multiple buckets.
