### ISSUE TITLE
Campaigns Are Being Sent But Not Received

### ISSUE THREAD

**Issue by Pythorus** [knadh/listmonk#513]
Hey, I was using Listmonk hosted locally and ran into issues so I decided to switch to a hosted one. I went for Heroku, and followed the process and set it up to the best of my knowledge. However, I'm not able to get it to work. I'm attaching a snippet of the log files. Please take a look.

P. S. I don't know much about computer languages and all. I'm a science student.

Thanks in advance.
![Listmonk Error](https://user-images.githubusercontent.com/67878659/137283150-ad1a75ee-2e38-485f-89a2-c673ddd78a14.PNG)

**Comment by Pythorus** [comment]
@knadh waiting for your reply.

**Comment by knadh** [comment]
Unable to help here, @Pythorus. Clearly, as the error shows, the instance that listmonk is running on is unable to connect to the SMTP server. As I said earlier, `telnet 13.127.20.218 25` didn't work from my system, so clearly, that IP isn't really open.

Pretty sure that this has nothing to do with listmonk and is a firewall / network thing.

**Comment by Pythorus** [comment]
Got it, @knadh. Anything I can do about the network/firewall or anything else I can explore to get my Listmonk working?

**Comment by Pythorus** [comment]
Hey, @knadh I generated new credentials for SMTP and re-deployed Listmonk on Heroku using a different account. It worked this time. No issues.
