### ISSUE TITLE
Support campaign specific headers sent with each mail

### ISSUE THREAD

**Issue by Libermentix** [knadh/listmonk#514]
**Is your feature request related to a problem? Please describe.**
We want to track all of our customer communication including emails from Listmonk in our central CRM System. This system allows us to add e-mails sent from different sources by BCC'ing to a specific e-mail adress along with certain additional meta headers (X-SOME-HEADER: ....). The headers need to be campaign specific in order to record that the customer was part of that campaign. 

**Describe the solution you'd like**
On campaign level allow additional parameters (compared to the SMTP setup X-Header  Misc header config) to be embedded into the campaign's mail's mail-header.

**Comment by knadh** [comment]
![image](https://user-images.githubusercontent.com/547147/148096323-56f3fd44-a8a1-41a7-a8de-a776518c834d.png)

**Comment by winterleitner** [comment]
> > Have you tried adding a custom BCC header in SMTP settings -> Custom headers?
> > ```json
> > [
> >    {"BCC": "your@email.com"}
> > ]
> > ```
> 
> Does anyone knows if this actually works? At least for our mail provider it doesn't.

No success for me either.

**Comment by jvies** [comment]
Hi,
No success here with the BCC header.
Using CC, we can see the copied address, but the copied email is never delivered.
