### ISSUE TITLE
Any template for EnvironmentFile

### ISSUE THREAD

**Issue by securewebsite** [knadh/listmonk#515]
Hello,

I am not able to find anything related to 

EnvironmentFile=-/etc/default/listmonk
EnvironmentFile=-/etc/default/listmonk-%i

Please help me how to configure listmonk as service in ubuntu. 

Thanks & Regards,
Gaurav Maniar

**Comment by knadh** [comment]
listmonk does not require any env vars to run. You just need the default config.toml file. If you really want to use env vars, the config.toml variables [can be supplied as env vars](https://listmonk.app/docs/configuration/#environment-variables).
