### ISSUE TITLE
Adding Support For Amazon Ses along with SMTP 

### ISSUE THREAD

**Issue by sagarchoudhary96** [knadh/listmonk#52]
It would be great to have support for Amazon SES or third-party services to send emails. It is already supported or in features list down the line?

I Would like to work on it if possible :)

@knadh

**Comment by mr-karan** [comment]
You can use any SMTP provider with listmonk. You can read the AWS [docs](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-smtp.html) for more information on SMTP Interface with SES. 

For listmonk, you just need to configure `smtp` section in the [config](https://github.com/knadh/listmonk/blob/master/config.toml.sample#L75)

**Comment by sagarchoudhary96** [comment]
Thanks :)

**Comment by miickel** [comment]
Did you get it to work @sagarchoudhary96? How did you configure it? When I try on Ubuntu, the result is always time outs when trying to send an email.
