### ISSUE TITLE
Link Tracking counts multiple clicks from the same user multiple times

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#522]
**Version:**
 - listmonk: 2.0.0
 - OS: Uberspace webhosting (I dont know the OS)

**Description of the bug and steps to reproduce:**
* Insert a tracking link
* Click on that link from the same user twice

**Screenshots:**
In the screenshot you can see, that my newsletter with 3 people shows that 2 clicked on the button. But actually one guy clicked twice.
![image](https://user-images.githubusercontent.com/6888294/137854670-51610c96-f715-499d-a852-df310faf5a3d.png)

I am not sure if just the displaying UI is wrong or only one tracking link for all is generated. The link should be individual to correctly track the clicks.

**Comment by knadh** [comment]
Closing this in favour of #676.
