### ISSUE TITLE
Get back to original form after submitting

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#527]
**Is your feature request related to a problem? Please describe.**
When I subscribe to a newsletter and hit "send" I get redirected to the listmonk server which says the subscription was sucessfull. There is no button to go back to the original site.

**Describe the solution you'd like**
It would be nice to have a "go back" like button. Maybe passed via form, maybe set in the listmonk settings. I am not sure what would fit best.

**Comment by knadh** [comment]
You can [customize the public pages](https://listmonk.app/docs/templating/#system-templates) to add any links you would want.
