### ISSUE TITLE
Consider license change to Apache?

### ISSUE THREAD

**Issue by karambir** [knadh/listmonk#53]
Hi Kailash,

Wonderful software. This is more of a question/request than an issue. Will it be possible for you consider licensing this software under Apache or other more lenient license? Here is my reasoning:

For low-level/core software GPL and AGPL make perfect sense as it forces everyone to at least open-source their changes and everyone can benefit from that. A good example for this can be Email server(like Postal).

But for a software like Listmonk, which manages email list/segmentation and sending logic, there will be cases where organizations have to make some changes. Also due to nature of AGPL, there is not enough clarity if software used over network(even excluding API) is considered distribution and hence needs open-sourcing all parts.

**Comment by knadh** [comment]
Thanks @karambir. I believe AGPL is a good choice for programs like listmonk (along the lines of Mastodon, Trillium).

> But for a software like Listmonk, which manages email list/segmentation and sending logic, there will be cases where organizations have to make some changes.

If there are changes / improvements that are exposed publicly to users, say, over the internet, then the modifications have to be released to those users, which really is the intention. If the changes are private, then it's different. The modifications are then confined to the users within the organisation.

> there is not enough clarity if software used over network(even excluding API) is considered distribution and hence needs open-sourcing all parts.

This is [well defined](https://www.gnu.org/licenses/gpl-faq.html#AGPLv3InteractingRemotely).
> If a program is not expressly designed to interact with a user through a network, but is being run in an environment where it happens to do so, then it does not fall into this category. For example, an application is not required to provide source merely because the user is running it over SSH, or a remote X session.

**Comment by karambir** [comment]
Thanks for the reply. Reading your linked FAQ, I think the users will interact with the software if we are looking at "Unsubscribe" link functionality or even email images(though user is not "expressly" using them).

**Comment by knadh** [comment]
Ah yes indeed, the unsubscribe link will trigger the provision. listmonk's a web app, so all it's endpoints are all expressly designed to send responses over the network.

I understand this might be a bit painful, but AGPL was chosen specifically for the protections it offers, where improvements are made available to the upstream.

**Comment by karambir** [comment]
I understand your decision and thank you for the great software. I will try to use it where it is appropriate in future. Closing the issue for now.
