### ISSUE TITLE
Some Ui Modifications

### ISSUE THREAD

**Issue by sentinm** [knadh/listmonk#537]
In mobile view side bar is not friendly, so can make them toggle from three slides icon in the left upper corner. Also bettet move logout to that side menu, this will improve responsive of this site... 🙃

**Comment by knadh** [comment]
@sweetppro had already done a nice mobile menu in an earlier PR. [This commit](https://github.com/knadh/listmonk/commit/2f56057fc3179af4eb4e9e9c6f1d3ffaf3a581c8) adds a minor fix to it.

![image](https://user-images.githubusercontent.com/547147/148237719-1c8ead3f-5632-4b6b-96a5-3fdd55ddf7b9.png)
