### ISSUE TITLE
Weird UX autosave campaign

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#551]
**Is your feature request related to a problem? Please describe.**
1. Create a new campaign
2. fill out everything
3. Go to "All campaigns"
4. The last campaign was safed, but not the content

**Describe the solution you'd like**
* A popup that asks 'save unsaved changes/draft' etc.
* Also save the content, not only the metadata like subject, name etc.

**Comment by NicoHood** [comment]
@knadh I think this bug could be a good candidate for the next bugfix release?

**Comment by knadh** [comment]
Yep, this is also on my to-do to look at for the next release.
