### ISSUE TITLE
Add a global option to track all links

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#554]
**Is your feature request related to a problem? Please describe.**
I found it hard to always check/add the track link option. Why not have a default/global setting for the whole campaign?

Maybe related to https://github.com/knadh/listmonk/issues/522 Tracking links should be more precise, so you also know which exact links have been clicked, aka which topic (if there are multiple) in the newsletter was the most interesting?

**Comment by shemtovo** [comment]
+1 this would be super helpful. Takes a lot of attention to make sure all links are turned on
