### ISSUE TITLE
Confirm subscription on opt-in email link click

### ISSUE THREAD

**Issue by flergbarn** [knadh/listmonk#556]
Currently, clicking on the confirmation link for a double opt-in list leads to a page where a confirmation button has to be clicked again. This then loads a subscription confirmation page with a back button that, because it's using the history API, just takes us back to the confirmation button page.

I think it would be simpler if clicking the confirmation link/button in the opt-in email automatically confirmed the subscription without requiring yet another button click, registering the email to the list and showing the subscription confirmation page without a "Back" button (since it would be accessed via email link).

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/1054c019ce6f1918c2b285eb78ea35019b26f09f addresses this. The `Back` button now only shows if there's meaningful history to navigate beyond the dead end pages.

**Comment by flergbarn** [comment]
[1054c01](https://github.com/knadh/listmonk/commit/1054c019ce6f1918c2b285eb78ea35019b26f09f) fixes the superfluous `Back` button, but doesn't address the unnecessary extra step of having to click `Confirm subscription` twice to subscribe to a double opt-in list -- once in the email, and then once again at the `subscription/optin/` link.

It would be great if clicking the `Confirm subscription` button in the email linked to a URL endpoint that registers the subscriber without any further input (and then shows the "subscribed successfully" message).

**Comment by knadh** [comment]
Sorry, missed responding to that bit. It's important to have the confirmation button there to give control to subscribers. Someone could enter my e-mail ID on your site, which will then send me an opt-in mail. As a confused recipient, I could click on the link/button to figure out what's going on and then inadvertently confirm a subscription I didn't ask for.

That said, if you really don't want the button, you could [customize the confirmation template](https://listmonk.app/docs/templating/#system-templates) and add this bit of Javascript to automatically submit the form on page load.

```html
<!-- Paste just above </body> //-->
<script>document.querySelector("form").submit();</script>
```

**Comment by flergbarn** [comment]
That's a fair point about accidental signups, but it might be worth considering making this a setting as it seems to be a common UX pattern for newsletter subscription services.

**Comment by NessDan** [comment]
Sorry to re-open but just chiming in to say +1 to having this be the default.

> As a confused recipient, I could click on the link/button to figure out what's going on and then inadvertently confirm a subscription I didn't ask for.

I think having a clear "Don't recognize us? *Unsubscribe*" in this case would be the move (default opt-out vs. opt-in)

**Comment by NessDan** [comment]
Also, I'm trying to do this with some difficulties. I'm on a Docker installation. So far I've

1. Downloaded the `static` folder you linked to
2. Copied it and brought it into the volume
3. Made edits to `static/public/templates/index.html` and other files to test and see if they'd reflect on the site
4. They don't, the HTML changes never show up.

![2023-02-03 07_48_18-listmonk_static at master · knadh_listmonk](https://user-images.githubusercontent.com/304269/216607761-9105522d-55c2-4f7a-baf5-03ed9c7d3076.png)

**Comment by tricoos** [comment]
It actually works, but you have to restart the service/Docker container which I regard as really bad because it causes downtime, even if just for a few seconds. Instead, the file should either always be read from the disk or - to achieve 100.0000% performance - a button added to the admin backend to reload the templates from disk into memory.

**Comment by knadh** [comment]
@tricoos saving any setting on the admin UI causes the app to restart and reload all templates. This happens in a span of milliseconds.

**Comment by tricoos** [comment]
@knadh Thanks, that's good to know and prevents downtime.

**Comment by tricoos** [comment]
@knadh Can you please add a button "reload admin UI"? I always have to change something, then the save button will be enabled, then I have to revert the setting and click the button again because I can only save when something has been changed

**Comment by arran-nz** [comment]
Can we reopen this ticket?

Would it be acceptable to have a feature flag, so that clicking "Confirm" on the email confirms the subscriptions. Because as it currently stands "Double Opt-In" is more like "Triple Opt-In" and it's very confusing for new subscribers.

**Comment by knadh** [comment]
@arran-nz you can easily achieve this by having the form auto-submit on page load. Paste the following piece of JS in Settings -> Appearance -> Public -> Custom Javascript

```javascript
document.querySelector(".optin-form").submit();
```

**Comment by arran-nz** [comment]
@knadh Thank you for the quick response and actionable solution, much appreciated!

**Comment by bentuna** [comment]
Sorry to reopen the toppic but we really should have a setting for that. The Workaround of @knadh is nice, but 
- not really user friendly for admins that have find this here first
- not suitable for end users that have no JS enabled in their browser.

**Comment by knadh** [comment]
This is now a feature (https://github.com/knadh/listmonk/commit/45e85e3fb682ba9930c5f357ee740c29c3f73e04). Will be available in the next release.

<img width="442" height="158" alt="Image" src="https://github.com/user-attachments/assets/7f75117f-ed52-42c8-bf61-fd58df1d00f4" />
