### ISSUE TITLE
Add custom image dimensions

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#557]
**Is your feature request related to a problem? Please describe.**
When uploading images to listmonk they are usually too large. The template width is quite small, so we should shrink the images to save bandwidth. Also I personally like to have all images in an aspect ratio of 1200x628 which is a common feature image size. So cropping might be also a consideration.

**Describe the solution you'd like**
It would be nice to have a setting of custom media types. Similar to how it is implemented on wordpress, if you are familiar with it. You basically have a list of: max width, max height, crop yes/no. When inserting images we would then either need a selection menu or (for now) there is only one dimension that is **always** applied to all images uploaded. E.g. saying the default width is 525px, so it makes sense to add a media size of 525 wide pictures.

**Comment by knadh** [comment]
Closing this for now. Tricky to achieve with TinyMCE (WYSIWYG editor) v5. The latest version v6 has removed image uploading altogether, which means that listmonk might have to switch to a whole new editor in the near future.
