### ISSUE TITLE
Is it possible to embed jpg to html?

### ISSUE THREAD

**Issue by marcin-github** [knadh/listmonk#56]
Hello,
Is it possible to embed images into html?  Mail clients doesn't like images from external www servers and usually blocks it. Embedding makes email larger but it allow display mail without accepting "show remote content".

**Comment by knadh** [comment]
This isn't supported right now, but I'll explore adding support. Thank you.

**Comment by cb3inco** [comment]
I found a image encoder (base64) and was able to insert that into my template (https://www.base64-image.de/). Or are you looking for Listmonk to do it automatically? The site provides the img src html and css (url)

**Comment by knadh** [comment]
@cb3inco it'll be a feature on listmonk  that works out of the box.

**Comment by AnaghHegde** [comment]
@knadh Is this part of hactoberfest? Are you still interested in this feature ?

**Comment by knadh** [comment]
Sure. If you're interested in working on this, please post a proposal on how it'll be implemented before sending a PR.

**Comment by wweverma1** [comment]
@knadh is anyone currently working on this ?
If not can I start working on this feature?

**Comment by fsainovich** [comment]
I can't find this in 2.2 version. Is this working ?

**Comment by knadh** [comment]
This feature doesn't exist (yet) in listmonk @fsainovich.

**Comment by ChrisTG742** [comment]
Is there a planned release version for this feature yet?

**Comment by knadh** [comment]
This is being tracked here: https://github.com/knadh/listmonk/issues/241
