### ISSUE TITLE
Campaign view statistics counts multiple times per user

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#561]
**Version:**
 - listmonk: 2.0.0

**Description of the bug and steps to reproduce:**
Similar to https://github.com/knadh/listmonk/issues/522 the statistics for campaign views count multiple times per user, making it absolutely useless for me. If i just click the email on my inbox, click on another item and then back, it counts as opened 3 times. It does not count how many people actually read the email.

![grafik](https://user-images.githubusercontent.com/6888294/139430617-69bdd39b-6a3c-41c3-b6d4-c2da77a13f77.png)

**Comment by knadh** [comment]
Closing this in favour of #676.
