### ISSUE TITLE
Docker-Compose-dev.yml

### ISSUE THREAD

**Issue by Zusel** [knadh/listmonk#562]
Good day,

could you add a docker-compose-dev.yml?
I wanted to try my luck with IMAP and bounce.
Unfortunately, some things in your project are not clear to me and that's why I can't manage to start it (file paths are not correct in your Dockerfile). So that I can develop myself I would ask you to write a Docker-Compose which builds the Dockerfile.

**Comment by knadh** [comment]
> Unfortunately, some things in your project are not clear to me and that's why I can't manage to start it (file paths are not correct in your Dockerfile)

Could you please elaborate? The current Dockerfile is for use with Goreleaser for releasing Docker images. And, the docker-compose file is for running demo and production instances by pulling the latest release from DockerHub.

Have you followed the [developer setup](https://listmonk.app/docs/developer-setup/) guide?

@mr-karan would it make sense to have dev definitions in the docker-compose file that offers Node, Go, yarn etc. in a dev image that mounts the local file system? Not sure how this would work. Keep `docker-compose up dev-frontend` running (which runs auto-updating `yarn serve`) and run and re-run `docker-compose up dev-backend` every time the Go code changes during development?

**Comment by mr-karan** [comment]
We can explore using [`profiles`](https://docs.docker.com/compose/profiles/) which are meant for this purpose. 

Caveat: This is relatively a newer feature launched in 1.28.0 (https://docs.docker.com/compose/release-notes/#1280) and people would need to have updated `docker-compose` version to run this. Since `profiles` is not backported to older versions, existing users won't be able to use the existing `docker-compose.yml` in it's current form should they decide to update.

So yeah, given that limitation, ^ either we can take a call on not supporting older version or have a separate `docker-compose-dev.yml`.

**Comment by Zusel** [comment]
unfortunately i don't have much experience with go development. That there are profiles was not known to me because in my company always different files are used for it. I find that also clearer. Developing this with a Docker file would have the advantage that you do not have to "install" it on your system. I have not seen the DEV setup yet. Maybe I'll manage to write a Docker Compose Dev and show them what I wanted to achieve with it.

**Comment by knadh** [comment]
Thanks. Please do read the [contribution guidelines](https://github.com/knadh/listmonk/blob/master/CONTRIBUTING.md) @Zusel.

> So yeah, given that limitation, ^ either we can take a call on not supporting older version or have a separate docker-compose-dev.yml.

@mr-karan sounds like it's simpler to do this. Also, why create a new .yml file when the two dev blocks could just be a part of the existing file?

**Comment by mr-karan** [comment]
> why create a new .yml file when the two dev blocks could just be a part of the existing file?

For a very simple reason (and we have the issues history to back the data) that a lot of users simply run `docker-compose up -d` which seems very natural thing to do :). That would end up running dev services. If we have a separate dev file, which will only be used by contributors, I guess we can avoid a lot of confusion. But yeah, either of the approach should be okay, you can take a call. I can work on the dev docker setup.

**Comment by knadh** [comment]
> For a very simple reason (and we have the issues history to back this claim) that a lot of users simply run docker-compose up -d which seems very natural thing to do :).

Yep, fair point.

**Comment by knadh** [comment]
@mr-karan would you be able to look into this?

**Comment by mr-karan** [comment]
Ah, got busy and lost track of this. I'll try pushing this in next couple of days.
