### ISSUE TITLE
 Segmentation fault while installing binary file

### ISSUE THREAD

**Issue by mad2aroad** [knadh/listmonk#565]
**Version:**
 - listmonk: [eg: v2.0.0]
 - OS: [ FreeBSD]

**Description of the bug and steps to reproduce:**

When I try to install binary file on the server (tried with FreeBSD and Debian), after typing

`$ ./listmonk --new-config
`

I have an error related to the memory

`Segmentation fault 
`

Is it something wrong with the server? 

I'm new into this, please forgive me if it's a rookie mistake. 

**Screenshots:**

**Comment by knadh** [comment]
> When I try to install binary file on the server (tried with FreeBSD and Debian), after typing

These are two different OS architectures and they have different binary releases available. A Go binary shouldn't throw "Segmentation fault". I think you may be running the wrong binary for the wrong platform.

The FreeBSD binary won't work on Debian and vice versa. Could you share which binary release you tried for which platform?

**Comment by mad2aroad** [comment]
### **1st server**

```
NAME=FreeBSD
VERSION=12.2-RELEASE
VERSION_ID=12.2
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 12.2-RELEASE"
CPE_NAME=cpe:/o:freebsd:freebsd:12.2
HOME_URL=https://FreeBSD.org/
```

**With Listmonk - listmonk_2.0.0_freebsd_amd64**

```
$ ./listmonk --new-config
Segmentation fault 
$ file listmonk
listmonk: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), statically linked, stripped
```

I also tried other versions to check the response

**With Listmonk - listmonk_2.0.0_linux_amd64**

```
$ ./listmonk --new-config
ELF binary type "0" not known.
```

**With Listmonk - listmonk_2.0.0_netbsd_amd64**

```
$ ./listmonk --new-config
ELF binary type "2" not known.
```

### **2nd server**

```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Wist Listmonk - listmonk_2.0.0_linux_amd64**

```
$ ./listmonk --new-config
Segmentation fault 
$ file listmonk
listmonk: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

Maybe there are some restrictions regarding access to the memory. I will try to investigate it.

**Comment by knadh** [comment]
Did you manage to find the issue @mad2aroad ?
