### ISSUE TITLE
[UI] Too much gap between "Download" and "Mailing list section"

### ISSUE THREAD

**Issue by ghulamyazdani** [knadh/listmonk#566]
**Version:**
 - listmonk: [eg: v1.0.0]
 - OS: [e.g. Fedora]

**Description of the bug and steps to reproduce:**
As in the pic, there is so much gap between "Download" and "Mailing list section" it needs to be fixed.
You can specify the padding of the download section in a better way.

**Screenshots:**
If applicable, add screenshots to help explain your problem.'
![image](https://user-images.githubusercontent.com/55938346/139799210-6e1b64f0-7295-4aab-b7f5-b2835f8957c8.png)

**Comment by knadh** [comment]
Tweaked it a bit: https://github.com/knadh/listmonk-site/commit/a64ec49cb5cc684343bbbc8535c05422b32b9fc4
