### ISSUE TITLE
Plain text preview strips line breaks

### ISSUE THREAD

**Issue by flergbarn** [knadh/listmonk#568]
When clicking preview for a plain text campaign, the preview window shows the text stripped of line breaks.

In addition to fixing this, it might be nice for the plain text preview to use a fixed width font trather than the browser default.

**Comment by ChrisTG742** [comment]
I think both issues could be easily solved by adding "<pre>" and "</pre> tags to the plain-text preview output.

**Comment by flergbarn** [comment]
I think that's the best solution. The `<pre>` tag just needs a `white-space: pre-wrap;` attribute so the lines get wrapped.

**Comment by knadh** [comment]
This was fixed by adding the correct plaintext content type to the HTTP preview response.

![image](https://user-images.githubusercontent.com/547147/140455539-c8206af9-c5fd-4a84-987a-3d0f0d973484.png)
