### ISSUE TITLE
Something Wrong With my Analytics?

### ISSUE THREAD

**Issue by Pythorus** [knadh/listmonk#571]
I sent out a campaign today and the moment the campaign status changed from 'Sending' to 'Finished' I saw 79 views already.
Something feels wrong to me. 
![Analyanomaly](https://user-images.githubusercontent.com/67878659/140494266-c55d8c93-3a04-4306-86f3-772a72f52c20.PNG)
Please let me know if I have done something incorrectly.

**Comment by knadh** [comment]
Nothing in listmonk will generate view counts. They can only come from client side e-mail views. Maybe there are bots hitting the view pixel somehow? You can check the `campaign_views` table to see if all hits have come from a single subscriber.

**Comment by Pythorus** [comment]
@knadh Where is the campaign views table?

**Comment by knadh** [comment]
Postgres database table. `SELECT * FROM campaign_views;`

**Comment by Pythorus** [comment]
@knadh Really sorry but where can I find that? I'm using LM on Heroku. Is it on LM itself or do I go back to Heroku?

**Comment by knadh** [comment]
Ah, sorry. I assumed you would have hands on access to the database. There is no easy way to find out without that.

PS: A granular view/click report on the admin UI will be available in a future release.

**Comment by Pythorus** [comment]
@knadh Okay, man. Thanks

**Comment by NicoHood** [comment]
This might be the reason for your issue:
https://github.com/knadh/listmonk/issues/561
