### ISSUE TITLE
Cannot setup SMTP in Version 2

### ISSUE THREAD

**Issue by AndrewHUK1974** [knadh/listmonk#575]
**Version:**
 - listmonk: [2.0.0]
 - OS: [Ubuntu]

I am trying to add my SMTP details in the admin and when I got to send a test newsletter I am getting this in the error log.

2021/11/08 20:55:37v2.0.0 (05585b7 2021-09-27T17:59:39Z)
2021/11/08 20:55:37reading config: config.toml
2021/11/08 20:55:37connecting to db: listmonk_db:5432/listmonk
2021/11/08 20:55:37will load static files from: /listmonk/static
2021/11/08 20:55:37media upload provider: filesystem
2021/11/08 20:55:37loaded email (SMTP) messenger: newsletter@mail.mydomainname.com
2021/11/08 20:56:19error sending message in campaign Test campaign: subscriber 56662a42-b0d7-4bc9-830d-b784ef7fca03: SMTP AUTH extension not found

It seems to be taking the mail server address in the HOST textbox on the SMTP tab. if I take off the mail. from the host address I get this error.

2021/11/08 21:02:46v2.0.0 (05585b7 2021-09-27T17:59:39Z)
2021/11/08 21:02:46reading config: config.toml
2021/11/08 21:02:46connecting to db: listmonk_db:5432/listmonk
2021/11/08 21:02:47will load static files from: /listmonk/static
2021/11/08 21:02:47media upload provider: filesystem
2021/11/08 21:02:47loaded email (SMTP) messenger: newsletter@mydomainname.com
2021/11/08 21:03:01error sending message in campaign Test campaign: subscriber 56662a42-b0d7-4bc9-830d-b784ef7fca03: x509: certificate is valid for mail.mydomainname.com, not mydomainname.com

Any Ideas?

Thanks,
Andrew

**Comment by knadh** [comment]
Looks like TLS isn't setup correctly on your server. You can try the `Skip TLS verification` option (but this is not recommended and you should fix your certificates).
