### ISSUE TITLE
Listmonk 2.0.0, Jsonb data type and PostgreSQL < 9.4 ?

### ISSUE THREAD

**Issue by oleole39** [knadh/listmonk#578]
Hello,

I've been trying to install Listmonk 2.0.0 on a shared hosting plan under Red Hat Linux and coming with PostgreSQL 9.2.24 (which the provider told me they would not bump to a newer version).
I get the following error (after which the installation process stops):

> ** first time installation **
** IMPORTANT: This will wipe existing listmonk tables and types in the DB 'mydb_listmonk' **
continue (y/N)?  y
2021/11/09 12:29:53 install.go:60: error migrating DB schema: pq: type "jsonb" does not exist

It seems that [jsonb support](https://dzone.com/articles/using-jsonb-in-postgresql-how-to-effectively-store) was indeed introduced with PostgreSQL 9.4. 
Would anyone think of a workaround for this? 
If not maybe can I add in the install docs that minimum requirement is PostgreSQL ⩾ 9.4 ?

**Comment by oleole39** [comment]
Thank you for the feedback and docs' update. 
Quite unfortunate indeed. I investigated the issue a bit more:
1. that webhost's policy is to leave PostgreSQL version shipped with Cpanel for its shared plans (i.e. not performing the [manual update option](https://docs.cpanel.net/knowledge-base/sql/install-or-update-postgresql-on-your-cpanel-server/)).
2. So far, [cPanel policy](https://features.cpanel.net/topic/improved-postgresql-support) is to support only the default PostgreSQL version shipped with the OS on which it is installed. The issue is repeatedly commented in cPanel forum for the past 8 years, up to this year.
3. The [default PostgreSQL package](https://www.postgresql.org/download/linux/redhat/) available for RHEL/CentOS 7.x is [version 9.2.24](http://mirror.centos.org/centos/7/os/x86_64/Packages/).
4. I assume that webhost is running RHEL/CentOS/SL/OL 7 on its shared servers...

**Comment by bamboowonder** [comment]
a Linode Nanode will cost you $5/mth, be way faster, , secure, private etc   and you can install any stack you want, even include Cpanel if you need.
https://linode.com
