### ISSUE TITLE
Scheduled time in Emails getting ignored

### ISSUE THREAD

**Issue by LukasSchulz** [knadh/listmonk#58]
When I start a scheduled Campaign it gets sent instantly instead of waiting for the set time to send the emails.

I am using the latest version (0.4.0-alpha)

Am I doing something wrong?

**Comment by knadh** [comment]
Investigating this.

**Comment by LukasSchulz** [comment]
How are you getting the time in listmonk?
Because I am running listmonk in a lxc container with apparmor enabled and some other software has also problems (not with time, but with things like accessing the kernel), when running in a container.

**Comment by knadh** [comment]
Ah, that could be it. The schedule check happens in an SQL query, so Postgres. https://github.com/knadh/listmonk/blob/62aa31b14cf651084a76aba0021106fd78911081/queries.sql#L448

**Comment by LukasSchulz** [comment]
I just checked and properly set up the time in Postgres, but the emails still get sent instantly.

**Comment by knadh** [comment]
@LukasSchulz figured this out. It's fixed in [v0.5.0-alpha](https://github.com/knadh/listmonk/releases/tag/v0.5.0-alpha).

**Comment by LukasSchulz** [comment]
I just installed v0.5.2 and replaced listmonk - it still sends instantly instead of waiting - du i have to reset the database (eg. ./listmonk --instal) or should it work? - sorry for coming at this so late, but I had many many other things to do

**Comment by knadh** [comment]
There aren't any changes to the DB. The binary should've just worked. Tested `v0.5.2` locally again to confirm and works as expected.

**Comment by LukasSchulz** [comment]
Sorry, seems like i did something wrong when copying the new binary, now it works as expexted. Thank you for your spare time!

**Comment by LukasSchulz** [comment]
Sorry, seems like i did something wrong when copying the new binary, now it works as expexted. Thank you for your spare time!
