### ISSUE TITLE
Feature request: Line-spacing & typeface options

### ISSUE THREAD

**Issue by marishathakur** [knadh/listmonk#582]
Hi, might it be possible to have more typeface options as well as a way to adjust the line-spacing. 
For example, right now the line-space is uniform between an image and the caption, or between paragraphs of text and also between entire sections. So if we could adjust the line-space (or is it line-height?), it would aid legibility and navigation. And different fonts because these options tend to serve as separators & also for fun.  :) 
Thank you.

**Comment by knadh** [comment]
> Hi, might it be possible to have more typeface options

This isn't feasible, unfortunately. It's not possible to embed fonts in HTML e-mails like it's possible on webpages, so the list of fonts in the editor are qausi-standard ones that are expected to be installed on most systems.

> adjust the line-spacing.

> For example, right now the line-space is uniform between an image and the caption, or between paragraphs of text and also between entire sections. So if we could adjust the line-space (or is it line-height?)

This can be easily adjusted in the template CSS and doesn't have to be tweaked manually while editing the e-mail. @aksanoble

**Comment by marishathakur** [comment]
Got it, thank you.

**Comment by candideu** [comment]
> > Hi, might it be possible to have more typeface options as well as a way to adjust the line-spacing.
> 
> This isn't feasible, unfortunately. It's not possible to embed fonts in HTML e-mails like it's possible on webpages, so the list of fonts in the editor are qausi-standard ones that are expected to be installed on most systems.
> 

@marishathakur I'm not sure if this works on all email clients, but I've added custom fonts by editing the raw HTML. For Google Fonts, I edited the head tag like this:

```html
<head>
...
<link href="https://fonts.googleapis.com/css?family=Work+Sans" rel="stylesheet" type="text/css">
....
</head>
```

And then added the fonts using inline CSS like this:

```html
<div style="font-size: 12px; font-family: 'Work Sans', 'Georgia', serif; color: #ffffff; line-height: 1.2;">
```

OR like this for a more global style

```html
<body style="background-color: #e8d5b1;font-family: 'Work Sans', sans-serif;font-size: 15px;line-height: 1.7;margin: 0;color: #232324;">
 ```

`<style>` `</style>` tags may also work

You can also use online visual email template builders (WYSIWYG) ([list 1](https://www.sendinblue.com/blog/free-responsive-email-templates/), [list 2](https://www.ilovefreesoftware.com/14/webware/free-email-template-builder-websites-to-create-responsive-templates.html)), export the HTML code, and paste them into Listmonk. I really like Beefree, Topol, Unlayer, and Mosaico.
