### ISSUE TITLE
Images overflow on email forward

### ISSUE THREAD

**Issue by aksanoble** [knadh/listmonk#583]
**Version:**
 - listmonk: 2.0

**Description of the bug and steps to reproduce:**
Images overflow when the email get's forwarded. I believe this is due to the headers getting stripped on forward. I'm currently using this tool to convert styles to inline as a way around. https://templates.mailchimp.com/resources/inline-css/ 

**Screenshots:**
<img width="955" alt="Screenshot 2021-11-12 at 3 37 07 PM" src="https://user-images.githubusercontent.com/7472506/141453032-419fb45c-3833-48ec-a80d-a89bfbe993d2.png">

**Comment by Mattifyed** [comment]
You are right. This is because the headers are stripped off. However, this behaviour isn't consistent across email clients. All of them behave differently, and the difference is significant. The approach of inlining the HTML before sending, as you do now, seems to be the only solution to this and nothing else really works.

**Comment by aksanoble** [comment]
I'm wondering if the css can be made inline during the process where the template is being processed with the email content?

**Comment by NicoHood** [comment]
That has already been reported and fixed. https://github.com/knadh/listmonk/issues/548

**Comment by aksanoble** [comment]
@NicoHood The issue that I am reporting here is different from the #548 . It's related to the headers getting stripped by certain email clients. Wondering if styles can be applied inline while processing email templates. This will save tons of time. https://templates.mailchimp.com/resources/inline-css/

**Comment by NicoHood** [comment]
And which email client does that??

**Comment by aksanoble** [comment]
For example: gmail-web

**Comment by knadh** [comment]
@aksanoble Can you share screenshots describing the issue? Gmail does not strip of layer/table/image styles.

**Comment by aksanoble** [comment]
@knadh Here's how the image looks as we try to forward the email. 
![Uploading Screenshot 2021-11-22 at 6.05.52 PM.png…]()

**Comment by aksanoble** [comment]
@knadh Here's how the image looks as we try to forward the email.
<img width="1031" alt="Screenshot 2021-11-22 at 6 05 52 PM" src="https://user-images.githubusercontent.com/7472506/142863053-276ce71a-9e4f-44e0-9d67-7535a38d00de.png">

**Comment by knadh** [comment]
hm, I'm not sure how listmonk can fix this. You could click the HTML `<>` icon on TinyMCE toolbar to get the HTML view and add an inline style to the image.

To make it simpler, maybe adding a `width %` option to the image popup would help? But then again, to get fine grained control (`max-width`, `max-height`) on inline styles, it's just simpler to edit the HTML.

![image](https://user-images.githubusercontent.com/547147/142895516-e53700c8-68c8-4203-adc5-359716e406ea.png)

**Comment by aksanoble** [comment]
Can it be done in the step where the content for a particular campaign gets added to the template to generate the final html?

**Comment by knadh** [comment]
I don't think it can be. Different e-mails will treat images differently, right? width, height, max-width, max-height, percentages, pixels ... It has to be designed manually.

**Comment by NicoHood** [comment]
Don't we need to parse the final html and replace the css with inline styles? Like using a converter lib that removes all those styles and inlines them? I am not sure if that is a common usecase, but at least a solution. I am a bit shocked, that such limited mailclients exist.
