### ISSUE TITLE
Minimum hardware requirements for production?

### ISSUE THREAD

**Issue by m52go** [knadh/listmonk#584]
I would like to deploy an instance of listmonk for production use. Installation looks fairly straightforward, but I'm not sure what kind of resources it needs (processor, memory, etc).

Would you mind sharing minimum resource requirements for reliable performance?

**Comment by m52go** [comment]
Nevermind I found the information in a picture caption on the main page (https://listmonk.app/).

> A production listmonk instance sending a campaign of 7+ million e-mails. CPU usage is a fraction of a single core with peak RAM usage of 57 MB.

**Comment by shailendra-agarwal** [comment]
Segmentation option is not available in Listmonk so I was suggesting sendy. Can you check if they have recently added segmentation feature.
