### ISSUE TITLE
API get subscribers by list_id

### ISSUE THREAD

**Issue by charlesmudy** [knadh/listmonk#585]
The API from here https://listmonk.app/docs/apis/subscribers/#get-apisubscriberslist_id says you can use multiple params to get subscribers by list_id but the problem is it seems to fetch only the first list_id and not the ones after ... so if the first list_id has empty subscribers, the whole result is empty.

Am I missing an upgrade?

Example with this https://email.domain.com/api/subscribers?per_page=all&list_id=12&list_id=21 

I was expecting it to merge the array as results, if list_id(1) has 20 subscribers and list_id(2) has 20 subscribers, the total result is 20 subscribers

**Comment by knadh** [comment]
Apologies @charlesmudy. I missed this issue. It was indeed a bug and I've just fixed it.
