### ISSUE TITLE
give error

### ISSUE THREAD

**Issue by MaralDeveloper** [knadh/listmonk#586]
Dear team

would you please help me ,when I upload image I give error " **Error uploading file: open uploads/media.png: no such file or directory**"
How can fixed it?
I red the **API / Media** document but I didn't understand where should increase this ( curl -u "username:username" -X GET 'http://localhost:9000/api/media' \
--header 'Content-Type: multipart/form-data; boundary=--------------------------093715978792575906250298')
and I increase curl -u "username:maral" -X POST 'http://localhost:9000/api/media' \
--header 'Content-Type: multipart/form-data; boundary=--------------------------183679989870526937212428' \
--form 'file=@/Users/username/Desktop/Media file' in ( Partial SQL expression to query subscriber attributes.) and I give error again

**Comment by knadh** [comment]
>  Error uploading file: open uploads/media.png: no such file or directory

Do you have a directory named "uploads" in the binaries path? If not, create one called "uploads" anywhere in your system and in Settings -> Media uploads -> Upload path, enter the full path to the directory. eg: `/home/yourname/listmonk/uploads`

**Comment by MaralDeveloper** [comment]
thank you 
your right , I can fixed it
