### ISSUE TITLE
User who unsubscribes from a list cannot resubscribe to that list

### ISSUE THREAD

**Issue by joerosenthal** [knadh/listmonk#588]
**Version:**
 - listmonk: 2.0
 - OS: Debian 9

I currently have one list, if a user unsubscribes from that list, they are no longer able to to resubscribe to that list. Users that are deleted from the database can subscribe again without issue.

**Comment by joerosenthal** [comment]
Not sure if it impacts anything, but I'm subscribing users by doing an axios/post to subscription/form as application/x-www-form-urlencoded, and this works well with the exception of previously unsubscribed users. 

As a bandaid, I changed public.go's handleSubscriptionPage function to run query app.queries.DeleteSubscribers, so users are deleted instead of unsubscribed—I wanted users to be auto-deleted upon unsubscribing from my one list, anyway, so this is fine in the mean time.

**Comment by knadh** [comment]
Posting using axios is fine.

The unsubscribe/re-subscribe behaviour is a bit ambiguous because it was a conscious decision to not re-subscribe an e-mail that's been unsubscribed as this would allow anyone to enter any e-mail ID on the public form and forcibly re-subscribe someone. But as you've described, this also prevents users from legitimately trying to re-subscribe. This behaviour needs some rethinking. Maybe re-subscriptions can happen for users who haven't been blocklisted (`don't e-mail me ever again` checkbox).

**Comment by joerosenthal** [comment]
Ah, that makes sense. It does seem like giving the option for blocklisting would solve this issue to some extent.

**Comment by atomtigerzoo** [comment]
The re-subscribe after delete and add emails without consent to only happen when there is no double-opt-in, right?
It should be possible to re-subscribe. Some users might click the link without real purpose or just 'try out'. Blocklists should prevent a resubscribe, thats correct. But a normal unsubscribe should a allow a re-subscribe instantly without support/deletion.

**Comment by MaximilianKohler** [comment]
I unsubscribed my own emails to test, and now there's no way to restore them besides deleting and re-adding? Ugh...

If a person changed their mind, the only way for them to "undo" the unsubscribe would be for them to email me/our company and ask to be restored, then we have to delete and re-add them... very tedious.

**Comment by knadh** [comment]
> The unsubscribe/re-subscribe behaviour is a bit ambiguous because it was a conscious decision to not re-subscribe an e-mail that's been unsubscribed as this would allow anyone to enter any e-mail ID on the public form and forcibly re-subscribe someone. But as you've described, this also prevents users from legitimately trying to re-subscribe. 

Quoting an earlier reply. It's a trade-off. Don't have a clear solution for this yet.

**Comment by MaximilianKohler** [comment]
> Quoting an earlier reply. It's a trade-off. Don't have a clear solution for this yet.

I did read that earlier, but I think that's referring to something a little different. I'm not using any public form where people can enter email IDs to subscribe. 

Oh, maybe I understand, and the fix may be to treat "private" lists differently from "public" ones? To add a "resubscribe" option after they choose "unsubscribe", but it only works from their personal "unsubscribe" link, and not any public form?
