### ISSUE TITLE
POP3 bounce 

### ISSUE THREAD

**Issue by bohemtucsok** [knadh/listmonk#589]
**Version:**
 - listmonk: [eg: v2.0.0]
 - OS: [Docker]

Hello

I wanted to set up a pop3 account to handle bounces. The account is running on a mail server, but unfortunately listmonk indicates an error in the log :  bounce.go:139: error scanning bounce mailbox: unknown response. Neither -ERR, nor +OK

Any idea what the solution might be?   thx for help !

**Comment by knadh** [comment]
There was an issue with parsing the responses from certain kinds of POP servers. This has already been fixed: https://github.com/knadh/listmonk/commit/a7fa97a214b749952d5a5c7270cd0c5be7e6433d. This will be available in the next official release. If you're able to [compile the app](https://listmonk.app/docs/installation/#compiling-from-source) yourself, you can avail the fix right now.

**Comment by bohemtucsok** [comment]
Ohhh super I understand thank you. Unfortunately, I am not waiting for the next docker update.

**Comment by bohemtucsok** [comment]
Hello

Unfortunately I tried to rotate the docker container locally but unfortunately failed. I would like to know when an update is expected. Or I started the Hungarian translation and finished to send the file to you ???   :)

**Comment by knadh** [comment]
This is now available as a release candidate. You can use the [`listmonk/listmonk:rc`](https://listmonk.app/docs/installation/#release-candidate-rc) image. It also includes the Hungarian translation.

**Comment by bohemtucsok** [comment]
Thank you very much :)

**Comment by bohemtucsok** [comment]
Hello

So it already queries the pop3 mail perfectly, but unfortunately something is still not completely okay. It bounces the bounced mail out of the mail box but unfortunately does not process it, it seems to retrieve the mail but does nothing with it leaving the bouncing tab empty. am i setting up with me wrong?

**Comment by knadh** [comment]
Does `Settings -> Logs` show any error messages related to bounce processing?

**Comment by bohemtucsok** [comment]
unfortunately empty shows nothing

**Comment by bohemtucsok** [comment]
I also tested it with a new installation yesterday and although it produces this error unfortunately, do you have any idea what the error might be?

**Comment by knadh** [comment]
> although it produces this error unfortunately

Is there an error you missed include in the message?

**Comment by bohemtucsok** [comment]
unfortunately it doesn't put any messages in the log

**Comment by knadh** [comment]
hm, works in my dev environment. Maybe something to do with your e-mail/POP environment. What e-mail provider or system are you using?

**Comment by bohemtucsok** [comment]
the mail server is a Kerio Connect platform

**Comment by bohemtucsok** [comment]
Hello

I tried to put it in binary yesterday, but I got back the error message: bounce.go: 139: error scanning bounce mailbox: unknown response. Neither -ERR, nor + OK

I really don't want to put things together. We have already tried to handle bouncers with another mail server, but the bug retrieves the email and does not process it. I accept any idea if you can help because I really want to use the program but so there is a problem with handling bounced emails so unfortunately this is useless.

We will listen to any solution just to make it come to life somehow :)

**Comment by knadh** [comment]
The version in the master branch works with my test setup. Unsure what's happening in your environment. The bounce e-mail that's landing in your POP inbox, is it possible for you to download the whole e-mail (as a .eml file) and share it here? That'll help debug.

In the meanwhile, I'll see if I can signup on Kerio and try and debug it within its environment.

**Comment by bohemtucsok** [comment]
if you think I can give you access to our Kerio server if that helps you

**Comment by knadh** [comment]
That would definitely help. Could you please e-mail me at kailash@nadh.in?

**Comment by gusarg81** [comment]
Hi,

I have a problem configuring Bounces, not sure if related to this Bug:

"error scanning bounce mailbox: unknown response. Neither -ERR, nor +OK."

POP settings are Ok in Settings -> Bounces and tested the Mail server with telnet just in case (by the way, I use same server SMTP settings and works just fine; Mail server ours located in a Datacenter).

![listmonk](https://user-images.githubusercontent.com/6312430/147094415-09564896-3741-46a2-8127-9833fb2d5bec.png)

Btw, there is a bad help message under Host and Port, it says SMTP Host and SMTP Port. Should be POP Host and POP Port?

**Comment by knadh** [comment]
This sounds like [this](https://github.com/knadh/listmonk/issues/492) issue which has been fixed. It will be available in the next official release. In the meanwhile, if you're using the Docker setup, the fix is already available in the [release candidate](https://listmonk.app/docs/installation/#release-candidate-rc) version. Otherwise, if it is feasible, you can pull the `master` branch and build yourself too.

The incorrect help message was also [fixed](https://github.com/knadh/listmonk/blob/c1c2b6750351609018fe82f8d761c02a1091a8ea/i18n/en.json#L350) recently.

**Comment by gusarg81** [comment]
Yes, I am using the docker-compose setup. Well, I will wait to next release.

Thanks!
