### ISSUE TITLE
Tracking features only loading after restarting listmonk

### ISSUE THREAD

**Issue by LukasSchulz** [knadh/listmonk#59]
At First: Thank you very much for this incredibly nice software.

The Issue: When sending Emails with tracking features (Tracking Pixel and/or Tracking link) the content is only accesible after restarting listmonk in the commandline - otherwise i get a json response message:"not found"

Is there any way to solve this?

Thank you

**Comment by knadh** [comment]
Could you elaborate the issue a bit?

- "content is only accessible" <- Do you mean the e-mail body? The pixel body? Or the stats on the dashboard?

- Could you please share the JSON request log from the browser console (URI, params, response)?

**Comment by LukasSchulz** [comment]
"content is only accessible" -> I mean, that the tracking pixel isn't able to to be loaded, because the server replys an error json message with the contents message: "not found"

The same goes for the tracking link.

I don't know what happened, but somehow this issue resolved itself - now everything works perfectly as I tested it again.

I am so sorry to have stolen your time doing some better thungs than following up things that resolved itself...

**Comment by knadh** [comment]
No problem @LukasSchulz. "Not found" should only happen if the tracking pixel's URL is incorrect. Please report if you spot this again.
