### ISSUE TITLE
German (formal) language file

### ISSUE THREAD

**Issue by SvenPe** [knadh/listmonk#590]
**Is your feature request related to a problem? Please describe.**
The german language has two pronouns to address people. The informal (Du) and the formal (Sie). The de.json currently implemented uses the informal version which, in some cases, is not acceptable for a newsletter. 

**Describe the solution you'd like**
We made a translation file for the formal version de-formal.json that we think would be useful to be implemented. Furthermore it would probably make sense to adjust the current de.json file to represent the use of the informal pronoun in the following way:
    "_.code": "de-informal",
    "_.name": "Deutsch (de | Du)"

The attached zip contains both json files with the mentioned changes.

[Listmonk_Languagefiles_de.zip](https://github.com/knadh/listmonk/files/7544273/Listmonk_Languagefiles_de.zip)
"

**Comment by NicoHood** [comment]
Makes sense to me to add both! If you create a PR I can review the translations. I recommend first commiting a copy of the current translation and then replacing it with the new one. This diff commit is easier to review then.

**Comment by knadh** [comment]
Thanks for the submission @SvenPe. I don't thin it is ideal to have a formal and informal version of the same language in an application. This is applicable to many languages and following this logic, every multi-lingual app can end up with many different styles for the same language.

I just checked a few apps (including my OS) and formal/informal isn't a pattern that's followed anywhere. We could just edit the existing German language pack to make the language a bit formal, right? The difference between the packs already seem small.

**Comment by NicoHood** [comment]
There is no such thing "a bit formal". It is a common option  to have both variants. But not all software has the effort to support both.

**Comment by knadh** [comment]
> There is no such thing "a bit formal".

Sure there is, depending on the language. There can be a whole spectrum of styles: extremely casual, semi casual, casual, semi formal, very formal, extremely formal ... Multi-lingual apps generally just stick to something close to formal.

> It is a common option to have both variants.

Never came across this pattern. Could you point to some popular multi-lingual apps that have this?

**Comment by SvenPe** [comment]
I do see your point of increased complexity with all the variants @knadh , but see your argument coming a bit short. 
For most apps it will be true, that this is not needed, as the company distributing/offering the app will choose to either go with formal pronoun (like we do), if the target group is more conservative, or with the informal pronoun, if the target group is more modern. Either way the company will adjust this according to their target group. 
With a newsletter management software like listmonk this is different though, as you're not directly targeting YOUR audience (in which case you would choose), but rather offer a platform for other companies to base their services on, and they will have chosen to either go the formal or informal route. 

For an example there is the forum software phpbb (https://github.com/phpbb/phpbb) that offers several language packs, among them the mentioned formal and informal variants of the german language. https://www.phpbb.com/languages/index.php#package_list

**Comment by knadh** [comment]
Yep, I agree.

> For an example there is the forum software phpbb (https://github.com/phpbb/phpbb) that offers several language packs, among them the mentioned formal and informal variants of the german language. https://www.phpbb.com/languages/index.php#package_list

This is already possible with listmonk. It's possible to load custom language packs with the `--i18n-dir` flag. I was specifically referring to **bundling** multiple variants of the same language in the app. The common pattern is bundle something close to formal that should ideally work for most scenarios and those who need specific changes can always load custom language packs like in the phpBB example.

**Comment by SvenPe** [comment]
Fair enough. I didn't stumble upon the `--i18n-dir` flag in the documentation, so didn't know that language packs were an option. 
I'll create a PR for the de.json file later with our formal translations, as these should be much closer to the "close to formal" you mentioned as the default than the current informal translations. I'm not entirely sure what the difference between "formal" and "close to formal" is, but our language file should reflect the necessary courtesy of the formal pronoun without being pretentious. If whoever reviews it doesn't like it as the default, feel free to offer it as a language pack if you want. 
We merely wanted to contribute the work we had done anyway, as we like the software.

**Comment by knadh** [comment]
> I'll create a PR for the de.json file later with our formal translations

:+1: Thanks!

> but our language file should reflect the necessary courtesy of the formal pronoun without being pretentious.

This is exactly what I meant by "close to formal" :) 

> If whoever reviews it doesn't like it as the default, feel free to offer it as a language pack if you want.

The project doesn't have any formal language reviewers right now. All language packs are volunteer contributions just like yours. Since you've clearly defined the distinction / subtleties in pronouns in your changes, I would think that that would be more appropriate to be in the default language pack. Maybe @NicoHood would be interested in reviewing?

My German is limited to just one sentence: `ich bin ein schlanker mann`. I don't remember where and why I learnt it though.

**Comment by knadh** [comment]
Closing this issue as #593 has been left open for any further comments.
