### ISSUE TITLE
Allow email without name

### ISSUE THREAD

**Issue by vprelovac** [knadh/listmonk#594]
**Is your feature request related to a problem? Please describe.**
List can not be imported without names. 

**Describe the solution you'd like**
Allow emails only. We collect emails from people who want a notification when a product feature is out. We do not need to know their name. Currently listmonk does not let record have a blank name.

**Comment by knadh** [comment]
If you're using the CSV importer, you could just have the name part of the e-mail in the "name" field. eg: For `xyz@gmail.com`, you can use `xyz` as the name, or even the whole e-mail itself `xyz@gmail.com` as the name.

The name field is mandatory to ensure that template functions such as `{{ .Subscriber.Name }}` render some value so as to not be confusing when previewing, testing, and sending e-mails. Also, it makes the subscriber dashboard looks uniform.

**Comment by vprelovac** [comment]
Thanks for the reply.

Is name used in message headers (if I use email as name will it sent to email <email>)?

I am not using template functions. I just want to send an informational email to thousands of users how wanted a notification. Not trying to sell them stuff or personalize. Just sending a notification.

**Comment by knadh** [comment]
> Is name used in message headers (if I use email as name will it sent to email )?

No.

It is only used a) in the automatic double opt-in confirmation e-mail b) when you use `{{ Subscriber.Name }}` in e-mail templates and campaigns.

**Comment by vprelovac** [comment]
OK then this may work. Perhaps add this alternative to error message or something.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/0d74619caca232983b428c9ac986b50b7cc19454 makes having to submit name via API and in the CSV file optional. If no name is provided, the name part of the e-mail is automatically extracted and assigned.
