### ISSUE TITLE
Campaign creation fails when no default template is present

### ISSUE THREAD

**Issue by nkmnz** [knadh/listmonk#599]
**Version:**
 - listmonk: v2.0.0
 - Ubuntu 20.04
 - PostgreSQL 13.3 
 
**Description of the bug and steps to reproduce:**
1. remove all templates from db
2. create new templates through the UI. By default, none of them has `is_default` set to true
3. go to `/admin/campaigns/new` and fill out the form. Chose one of the valid templates
4. on clicking "continue", the request fails with the following error:
`Error fetching Campaign: sql: Scan error on column index 16, name \"template_id\": converting NULL to int is unsupported`
5. Setting the column `tempalte_id` to NOT NULL is no help, it seems that postgres - other than mysql - does not treat an explicit NULL value on a NOT NULL column by replacing it with the DEFAULT value.

**Workaround**
The error disappears when a random template is set as default, either through DB or UI

**Expected behavior:**
Campaign setup should not fail if a valid template is chosen in the form - it's not possible to continue without choosing one anyways. Is there a need for a default template other than pre-filling the campaign form?

**Comment by knadh** [comment]
> remove all templates from db

Was this done outside of listmonk API/UI? The template deletion API [specifically checks](https://github.com/knadh/listmonk/blob/575d00757588aa50fb5bb5a8b48dff36ebc075f2/queries.sql#L752) that there is at least one default template and disallows a state where the templates table is empty to prevent these scenarios.

> Is there a need for a default template other than pre-filling the campaign form?

Yes. It's used extensively across queries. If there is no default template and the templates selected on campaigns get deleted, everything related to campaigns break (preview, send, test). A default template ensures that even if an actively used template is deleted, all template compilation logic can revert to a default template and not break.

**Comment by knadh** [comment]
HI @nkmnz, any updates on this?
