### ISSUE TITLE
Rules and webhooks

### ISSUE THREAD

**Issue by toto1384** [knadh/listmonk#600]
The only reason for me to not use Listmonk full time is the lack of webhooks. For example, when the subscriber is assigned to a new attribute or list I would like an email to be sent. Or, for every week of a subscriber being in the newsletter, an email to be sent on Monday (Creating a funnel, on week 1 you get value, week 2 value, week 3 you get an offer)

You could implement a system similar to what Markethero had before turning into Hyros. Or any system that makes sense if it works

**Comment by knadh** [comment]
Are you referring to HTTP POST webhooks for various actions (add, sub, unsub etc.)? Generic webhooks would indeed be good to have to integration with external systems easier.

Funnels, timers and rules etc. are marketing automation features that aren't in the project's scope right now. I think something like Mautic may be more suited for that usecase.

**Comment by toto1384** [comment]
Oh, I will try Mautic. Thanks
