### ISSUE TITLE
`preconfirm_subscriptions` not working for `/api/subscribers` POST call (?)

### ISSUE THREAD

**Issue by hunicus** [knadh/listmonk#602]
### Versions
 - listmonk v2.0.0
 - Ubuntu 20.04.2 LTS

### Description of the bug 

I'm trying to add a user to a list through the API using the `/api/subscribers` endpoint and `preconfirm_subscriptions=true` parameter, and while user is added to the specified list, they are not marked as confirmed. As a result, they are sent an opt-in email and must manually confirm themselves.

### Steps to reproduce

Assume 'Test' (id=1) is a private list requiring double opt-in.

Send the following POST request:

```
curl --location --request POST 'https://my.url.tld/api/subscribers' \
--header 'Authorization: Basic <token>' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'email=test@mailinator.com' \
--data-urlencode 'name=sir/madam' \
--data-urlencode 'status=enabled' \
--data-urlencode 'lists=1' \
--data-urlencode 'preconfirm_subscriptions=true'
```

The following response is received:

```
{
    "data": {
        "id": 8,
        "created_at": "2021-11-29T00:57:36.373676Z",
        "updated_at": "2021-11-29T00:57:36.373676Z",
        "uuid": "181cadd5-fe6b-411e-b8cd-8d1c6fb7acd2",
        "email": "test@mailinator.com",
        "name": "sir/madam",
        "attribs": {},
        "status": "enabled",
        "lists": [
            {
                "subscription_status": "unconfirmed",
                "id": 1,
                "uuid": "e2e12965-56aa-491f-9c19-dea7e7b0feb7",
                "name": "Test",
                "type": "private",
                "optin": "double",
                "tags": [
                    "test"
                ],
                "created_at": "2021-11-26T06:03:55.561197+00:00",
                "updated_at": "2021-11-28T14:55:33.439764+00:00"
            }
        ]
    }
}
```

Notice the property `"subscription_status": "unconfirmed"`.

It also shows this way in the UI:

![Screenshot from 2021-11-28 20-05-23](https://user-images.githubusercontent.com/93150691/143794191-e741d7ec-5273-407d-8643-0c115888ef0e.png)

And a confirmation opt-in email is sent to the email address.

If I understand the `preconfirm_subscriptions` parameter correctly, the user should have a `confirmed` status for the specified lists and not be sent a confirmation email.

**Comment by knadh** [comment]
You are making an `application/x-www-form-urlencoded` API request where as all APIs take `application/json` payloads. Please refer to the curl examples in the API docs: https://listmonk.app/docs/apis/subscribers/#post-apisubscribers

Sending non-JSON payloads should ideally be rejected, but it looks like [echo](https://github.com/labstack/echo) is parsing it nonetheless, which is incorrect behaviour. Will look into that.

**Comment by hunicus** [comment]
Shoot, my bad. Works like a charm! Thank you for the quick response and amazing software!!

**Comment by sscarduzio** [comment]
Fell for this myself as well on Listmonk version 2.1.0. It would be **much better** if the API would fail with `400 Bad Request` if the payload is not JSON. ☠️ ☠️ ☠️
