### ISSUE TITLE
503 Only one sender per message, please

### ISSUE THREAD

**Issue by charlesmudy** [knadh/listmonk#606]
Hello,

I'm testing/experimenting with SendGrid and I keep getting this message `503 Only one sender per message, please` and emails fail to deliver, not sure why.

Any ideas?

**Comment by knadh** [comment]
There was a similar issue reported earlier. Could you please take a look at [this](https://github.com/knadh/listmonk/issues/300#issuecomment-926594953)?

**Comment by Uzay-G** [comment]
I'm getting something like this too:

```
2022/09/10 07:39:30error sending message in campaign Espial Update v2.1: subscriber 1eb1b3ac-d6a1-4d76-96b0-bf6583d5ac74: 503 Only one sender per message, please2022/09/10 07:39:31error sending message in campaign Espial Update v2.1: subscriber 1ede1e73-1b73-4ab4-b239-22064350749e: 503 Only one sender per message, please
```

This hapens for each message, and although some of them succeed I think most of them don't send because of this. 
I have set the admin notification email. Let me know if you have any ideas on what I can do to debug this more.

**Comment by charlesmudy** [comment]
This is actually still happening once in a large, I am not sure how to fix it. I know it's an old request but I just try to ignore it and focus on other things.

I think the message is different from the one you referenced @knadh

**Comment by michaeljakob** [comment]
Emails don't get sent out. How to fix this?

**Comment by Jay991** [comment]
Same issue here @knadh
