### ISSUE TITLE
Allow the subscriber to update his/her name

### ISSUE THREAD

**Issue by marcinkunert** [knadh/listmonk#607]
**Is your feature request related to a problem? Please describe.**
When signing up to a newsletter the user gives a fake name or types it wrong, he/she is then unable to fix it. The name is often used when sending messages using templating (e.g. `Hi {{ .Subscriber.Name }}!`)

**Describe the solution you'd like**
A possibility to add a link (next to 'unsubscribe') in the mail content pointing to a dedicated form for updating user settings. It could be possibly merged with current public subscription form (`/subscription/form`). If this is the case, the form should not display an error when there are no public lists to subscribe to.

**Comment by knadh** [comment]
Yep, makes sense.

**Comment by candideu** [comment]
Similar issue as this: https://github.com/knadh/listmonk/issues/455

**Comment by knadh** [comment]
Closing this in favour of #455.
