### ISSUE TITLE
Support for mixed HTML and plain txt emails

### ISSUE THREAD

**Issue by joerosenthal** [knadh/listmonk#610]
**Is your feature request related to a problem? Please describe.**
Currently, emails can only be sent as plain txt or HTML, and by choosing HTML without also sending plain txt, it's a minor hit in terms of being viewed as spam.

**Describe the solution you'd like**
Allow HTML emails to also be sent with plain text with a multipart/MIME message

**Comment by knadh** [comment]
This is already possible. You can find the option below the richtext/raw HTML editor boxes.

![image](https://user-images.githubusercontent.com/547147/144552237-cc460e9f-3248-41dd-93d6-d9132463b35e.png)
