### ISSUE TITLE
Single Opt-In List shows validation tag for subscribers

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#611]
**Is your feature request related to a problem? Please describe.**
If you have a single opt-in list and manually enter a subscriber, it is tagged as "validation missing" (sorry, the english translation might be a bit different). 
![image](https://user-images.githubusercontent.com/6888294/144582336-6bb31977-6de4-4009-b478-42dd86be05bf.png)

**Describe the solution you'd like**
This tag should only be displayed for double opt-in lists. Single Opt in should have no tag at all.

**Comment by knadh** [comment]
This was fixed in https://github.com/knadh/listmonk/commit/f9854bc54ba08e5765e993f81fc7916020c9ee1d.
