### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by MaralDeveloper** [knadh/listmonk#613]
**Version:**
 - listmonk: [eg: v2.0.0]
 - OS: [centos

**Description of the bug and steps to reproduce:**
I want connect to my database for do somethings my code is ( **<?php
$conn_string = "host=127.0.0.1 port=9432 dbname=listmonk user=listmonk password=listmonk";
$conn = pg_connect($conn_string);

if($conn){
echo"Connected to database";
}**

)
I then I get this error ( **pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user**)
would you please tell me whats the password and what should I do

**Comment by knadh** [comment]
Assuming that you're using the Docker setup, do you have a config.toml with a custom password?

@mr-karan ?

**Comment by mr-karan** [comment]
@MaralDeveloper A bit diffcult to tell with this much information. Can you tell, if you followed the Docker installation methods mentioned here? https://listmonk.app/docs/installation/#production

If yes, the `docker-compose` file has the default password as `listmonk` and it should have been set like that by default. `config.toml` is for app config to connect to DB, so if listmonk is running fine with the same password, so should your app. Please check the values inside `config.toml`.
