### ISSUE TITLE
Campaign progress incorrect

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#615]
**Version:**
 - listmonk: 2.0.0

**Description of the bug and steps to reproduce:**
I've set a rate limit to 20mails/hour. If I start an opt-in campaign, the progress shows as follows:
![image](https://user-images.githubusercontent.com/6888294/144847714-e982c5e0-fa39-402d-b714-06d0b75ea357.png)

This is not correct, as it will send ~200 mails only after 10hours. But it shows that all mails are already sent.

I am not sure if that was already corrected in the latest master, but I think no.

**Comment by knadh** [comment]
In every iteration, the system pulls `$batch_size` ("Batch size" option in Settings -> Performance) number of subscribers to process, which moves the progress bar. You should set it to 20 (or whatever upper limit you're using) so that the system only pulls so many e-mails in one shot, moving the progress indicators accurately.

**Comment by NicoHood** [comment]
Why doesnt listmonk do that automatically? That batch size should not be higher than the rate I guess.

**Comment by knadh** [comment]
> Why doesnt listmonk do that automatically?

hm yeah. The admin UI can warn if batch_size < rate. Will add this.

**Comment by knadh** [comment]
Actually, the settings UI says this, which is correct. It should be higher to achieve maximum throughput, but it shouldn't be disproportionately high, which doesn't affect sending, but skews stats like in this case.

![image](https://user-images.githubusercontent.com/547147/145411132-e43dfe4d-c54f-4902-aab2-7d4802ede132.png)

**Comment by NicoHood** [comment]
I still think, that the software should make a good default guess, based on the other settings.

**Comment by knadh** [comment]
This was fixed in the last release https://github.com/knadh/listmonk/commit/0f6a0376dafd4a2fb89d05c4058258915f375de0 with realtime rate counting that doesn't depend on these settings.
