### ISSUE TITLE
Any tips on getting Backblaze B2 (S3 compatible API) to work?

### ISSUE THREAD

**Issue by devinellis** [knadh/listmonk#617]
I've been able to use the [B2 S3 API](https://www.backblaze.com/b2/docs/s3_compatible_api.html) in other applications, but in ListMonk I am getting this response when attempting to upload an asset:
```
Error uploading file: status code: 501
```
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
    <Code>NotImplemented</Code>
    <Message>Backblaze B2 does not support this API call.</Message>
</Error>
```
I see Listmonk uses [simples3](https://github.com/rhnvrm/simples3/issues?q=b2) but I don't see any existing issues there about this either. Looking at [s3.go](https://github.com/knadh/listmonk/blob/master/internal/media/providers/s3/s3.go) it looks pretty straight forward, but without some debug logs I am not sure what API call they are complaining about.

**Comment by knadh** [comment]
Thanks for reporting this @devinellis.

@rhnvrm would you want to explore B2 compatibility in simples3?

**Comment by rhnvrm** [comment]
@devinellis simples3 supports custom endpoints which should work with s3 compatible instances. The library is tested against minio and s3 buckets (locally). I also use the library personally with Wasabi which seems to work. 

Since I currently don't have access to a B2 account, would it be possible for you to clone simples3 and run `go test ./...` with the [required environment vars](https://github.com/rhnvrm/simples3/blob/master/.github/workflows/go-test.yml#L37-L40) set with your B2 access keys locally and share the results on an issue on the simples3 repo?

**Comment by knadh** [comment]
> The library is tested against minio and s3 buckets (locally).

The listmonk integration has also been tested to work with S3 and minio.

**Comment by devinellis** [comment]
@rhnvrm Sure thing: 
```
--- FAIL: TestS3_FileUpload (1.11s)
    --- FAIL: TestS3_FileUpload/Upload_test.txt (0.33s)
        simples3_test.go:136: S3.FileUpload() error = status code: 501 : "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n    <Code>NotImplemented</Code>\n    <Message>Backblaze B2 does not support this API call.</Message>\n</Error>\n", wantErr false
        simples3_test.go:144: S3.FileUpload() returned empty response, {   }
    --- FAIL: TestS3_FileUpload/Upload_test.txt_with_custom_metadata (0.39s)
        simples3_test.go:136: S3.FileUpload() error = status code: 501 : "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n    <Code>NotImplemented</Code>\n    <Message>Backblaze B2 does not support this API call.</Message>\n</Error>\n", wantErr false
        simples3_test.go:144: S3.FileUpload() returned empty response, {   }
        simples3_test.go:154: S3.FileUpload() error = status code: 400 , wantErr false
        simples3_test.go:158: S3.FileDetails() returned incorrect metadata, got: map[]
    --- FAIL: TestS3_FileUpload/Upload_avatar.png (0.19s)
        simples3_test.go:136: S3.FileUpload() error = status code: 501 : "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n    <Code>NotImplemented</Code>\n    <Message>Backblaze B2 does not support this API call.</Message>\n</Error>\n", wantErr false
        simples3_test.go:144: S3.FileUpload() returned empty response, {   }
    --- FAIL: TestS3_FileUpload/Upload_special_filename_txt (0.19s)
        simples3_test.go:136: S3.FileUpload() error = status code: 501 : "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n    <Code>NotImplemented</Code>\n    <Message>Backblaze B2 does not support this API call.</Message>\n</Error>\n", wantErr false
        simples3_test.go:144: S3.FileUpload() returned empty response, {   }
--- FAIL: TestS3_FileDownload (0.56s)
    --- FAIL: TestS3_FileDownload/txt (0.21s)
        simples3_test.go:256: S3.FileDownload() error = status code: 400 , wantErr false
    --- FAIL: TestS3_FileDownload/png (0.18s)
        simples3_test.go:256: S3.FileDownload() error = status code: 400 , wantErr false
    --- FAIL: TestS3_FileDownload/txt-special-filename (0.17s)
        simples3_test.go:256: S3.FileDownload() error = status code: 400 , wantErr false
--- FAIL: TestS3_FileDelete (0.58s)
    --- FAIL: TestS3_FileDelete/Delete_test.txt (0.21s)
        simples3_test.go:338: S3.FileDelete() error = status code: 400 , wantErr false
    --- FAIL: TestS3_FileDelete/Delete_avatar.png (0.19s)
        simples3_test.go:338: S3.FileDelete() error = status code: 400 , wantErr false
    --- FAIL: TestS3_FileDelete/Delete_special_filename_txt (0.17s)
        simples3_test.go:338: S3.FileDelete() error = status code: 400 , wantErr false
```

This is using the same credentials I have configured in my production environment, including a CMS that accepts S3 config, like Listmonk. So I know it _can_ work.

I tested these scenarios:
- same variables set like in your example you linked
- added `AWS_S3_BUCKET`
- removed `https://` from `AWS_S3_ENDPOINT`
All gave me the same result

If you like, I can email you a temporary key with access to an empty bucket you can use to test

**Comment by rhnvrm** [comment]
Hi

I guess this might not be supported by b2, since simples3 by default uploads using signed POST calls instead of PUT calls. I couldn't find a resource on the backblaze website but this reddit comment seems to indicate the same based on a response from their support https://www.reddit.com/r/backblaze/comments/kzszym/comment/gjspw8s 

I'm not exactly sure what the appropriate resolution to introducing support for b2 would be at the moment. Forked a discussion on the simples3 repo; will try to figure out what would be feasible.

**Comment by knadh** [comment]
Closing this issue. @devinellis maybe an S3 proxy [like this](https://github.com/gaul/s3proxy) can help.
