### ISSUE TITLE
Allow searching of lists

### ISSUE THREAD

**Issue by anarchist912** [knadh/listmonk#618]
**Is your feature request related to a problem? Please describe.**
I used the API to create 299 lists, which will be filled with subscribers through the API, too.
To create a campaign for a particular list, I can either
`a)` go to lists -> all lists and click through the 16 pages, until I find the list I want to send to. Or I can
`b)` go to campaigns -> add new, and add the list in the lists field.

**_Problems:_**
`a)` takes a while to find the right list, but works.
`b)` only works if the right page was queried in `a` before taking steps in `b`. It seems like the pagination that is applied in `a`, is also active in the query behind the suggestions in the lists field in `b`

**Describe the solution you'd like**
 `a1)` add a page size to the pagination in the UI. If we can select 1000 per page, we can use the `ctrl + f` to find the right list (quick dirty fix)
`a2)` add a search similar to the one in the subscribers section (the right way IMHO)

`b1)` dirty fix `a1` might also dirty fix this one
`b2)` change the query behind the lists field's suggestions to search all lists

I would not recommend `a1`/`b1`.
**`b2` could be a quick and clean solution for the problem, until `a2` could be realized.**

THANK YOU!
Guys, I love the performance and simplicity of this software.

**Comment by knadh** [comment]
+1. Lists need first class search support like campaigns and subscribers. Will add this. Missed this in my early to-dos and then forgot about it altogether.
