### ISSUE TITLE
Choose different language for admin and public 

### ISSUE THREAD

**Issue by tadinski** [knadh/listmonk#619]
I am curious if there is a way to set two different languages. A language for the dashboard and a different language for public facing pages/files.

**Comment by knadh** [comment]
This isn't possible, but if you really want to change the frontend language,

- You could clone the `static` directory, replace language strings, and pass them to listmonk via the `--static-dir` option (easier). [Docs](https://listmonk.app/docs/templating/#system-templates).
- You could create a [custom language pack](https://listmonk.app/docs/i18n/) with different strings for the frontend.

**Comment by tadinski** [comment]
Thanks for the suggestion. I had already implemented the first point but thought maybe there was a way to toggle the setting through config file to use different language files
