### ISSUE TITLE
starting docker container fails

### ISSUE THREAD

**Issue by tadinski** [knadh/listmonk#621]
I was tinkering with media file upload path in the settings. I emptied the field with Upload URI after which my docker container crashed and I am not able to start it up.

`panic: echo: path cannot be empty`

Is this related to the media upload path being empty?
I tried setting the path through config.toml and composing-up the container, without luck

Here is the docker logs for the app container
<img width="757" alt="scrn_0223" src="https://user-images.githubusercontent.com/6358371/145166223-69131fe1-eb68-4c5b-93bd-64c847435c67.png">

**Comment by knadh** [comment]
Ah, this is a bug. Booting shouldn't fail just because the setting is empty.

For now, you can run this query to reset the value.

```sql
UPDATE settings SET value='"uploads"'  WHERE key='upload.filesystem.upload_path';
```

**Comment by tadinski** [comment]
Thanks

'upload.filesystem.upload_uri' cannot be empty either apparently

**Comment by knadh** [comment]
Thanks @tadinski. Leaving this issue open until the behaviour is fixed.
