### ISSUE TITLE
Provide a non-public way to document lists

### ISSUE THREAD

**Issue by devinellis** [knadh/listmonk#622]
List names are public because they will appear in unsubscribe pages and other forms. This wasn't obvious to me in the beginning, and I had some lists like "March 2021 Import" which is really more of an internal name.

I understand now how the Title is being used, but would still like a way to document some information about the list (for admins to be able to reference), basically make the list self-documenting. It doesn't need to be structured, could just be a description field. 

Example info that could be useful to document:
- List source
- Date it was sourced (in our case, we have old lists that pre-date listmonk so the created_at field is not very useful)
- Was it originally opt in? double opt-in? 
- Original intent / CTA. 
I am going use tags for now, but I'm not sure that will scale very well.

BTW, we love how lean and fast listmonk is!

**Comment by knadh** [comment]
Thanks @devinellis. Private vs. Public lists are clearly documented on the UI.

![image](https://user-images.githubusercontent.com/547147/145703037-56b1cfdd-6aed-4cb0-8e9e-2ef7b9a8324c.png)
![image](https://user-images.githubusercontent.com/547147/145703040-4076317a-911e-4308-ac58-2c2d875af85e.png)

Tags can be used to add metadata for internal use, but I agree that a new `description` field could be useful, even for public lists to show a helpful description on public subscription pages. Will add this.

**Comment by devinellis** [comment]
Correct me if I'm wrong, but in my testing it seemed like the List Title would still appear when a user unsubscribes, making it not really a "private" (admin-only) piece of information.

**Comment by knadh** [comment]
hm, can you share a screenshot?

This is how the unsubscribe page looks. No list names are revealed.

![image](https://user-images.githubusercontent.com/547147/145709955-e5e889a3-e067-45b1-a0c0-42d375889a54.png)

**Comment by devinellis** [comment]
My mistake, it was the double opt-in email that is sent to the subscriber:

---
![image](https://user-images.githubusercontent.com/3112022/145730046-91f82c21-b144-49ae-b41a-7e4c4b68d919.png)
---
This is an edge-case, since I doubt there are very many reasons to create a private double opt-in list, but I think I ran into it because we were working on importing folks who _should_ have been sent a confirmation, but weren't on our old system.

**Comment by knadh** [comment]
In the confirmation e-mail also, no details are revealed. All private lists just show the generic placeholder `Private list`.

**Comment by devinellis** [comment]
Oh I see. My test list had a similar name so I didn't notice that "Private list" in my screenshot was generic. 

I'll just use tags for now, feel free to close this if you like!
