### ISSUE TITLE
 i/o timeout error

### ISSUE THREAD

**Issue by noussssh** [knadh/listmonk#623]
I installed listmonk on a CentOS 8 using Docker  easy install (production)  and added gmail smtp details.   Tried to send a test email.  Got this error in log. 

2021/12/13 04:04:49error sending message in campaign Test campaign: subscriber 7bd23833-e655-4688-a0df-c1cedfe8b2a3: dial tcp 74.125.24.108:587: i/o timeout

What could be wrong?

**Comment by knadh** [comment]
Network configuration / firewall disallowing connections to the SMTP server. Related: #393, #461

**Comment by noussssh** [comment]
No experience in setting up firewall.  😔
However I installed it again on a different VPS provider, test mail is working now.  

Now I need to design the email and import contacts.  Back to docs. 

Thank you !
