### ISSUE TITLE
Install script does not works

### ISSUE THREAD

**Issue by alexisvisco** [knadh/listmonk#624]
**Version:**
 - listmonk: v2
 - OS: Mac os Monterey (m1 version)

**Description of the bug and steps to reproduce:**
➜  listmonk sh -c "$(curl -fsSL https://raw.githubusercontent.com/knadh/listmonk/master/install-prod.sh)"

>  checking for an existing docker db volume
>  fetching config.toml from listmonk repo
>  fetching docker-compose.yml from listmonk repo
>  generating a random password
tr: Illegal byte sequence
>  modifying config.toml
sed: 1: "config.toml": command c expects \ followed by text

**Comment by mr-karan** [comment]
@alexisvisco Thanks for opening. Looks like this is the offending line. Will see if we can generate a password that works across `macOS` and Linux systems. 

```
echo $(tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '')
```

**Comment by mr-karan** [comment]
@alexisvisco I don't have access to a macOS machine. Can you run this on your terminal and tell if it runs without errors:

```
echo $(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '')
```

**Comment by alexisvisco** [comment]
> echo $(tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '')

➜  listmonk echo $(tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '')
tr: Illegal byte sequence

**Comment by alexisvisco** [comment]
> @alexisvisco I don't have access to a macOS machine. Can you run this on your terminal and tell if it runs without errors:
> 
> ```
> echo $(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '')
> ```

➜  listmonk echo $(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '')
JhlBPPiyWzyMc
