### ISSUE TITLE
From: header sender name unnecessarily surrounded with double quotes

### ISSUE THREAD

**Issue by tcitworld** [knadh/listmonk#626]
**Version:**
 - listmonk: [eg: v1.0.0] v2.0.0
 - OS: [e.g. Fedora] Debian 10

**Description of the bug and steps to reproduce:**
When specifying a `From:` address as the following in the settings:
```
Sender <do-not-reply@domain.org>
```
When emails are sent, the `From:` header sender name value is unnecessarily surrounded with double quotes, like this:
```
[...]
From: "Sender" <do-not-reply@domain.org>
[...]
```
This causes trouble as sometimes these emails end up in our Sympa mailing-list system, which transforms it in:
```
From: "\"Sender\"" (via XXX Mailing List) <mailing-list@mailing-list.org>
```

We noticed the value is correctly saved into Listmonk database configuration as `"Sender <do-not-reply@domain.org>"`, so it looks like it's transformed afterwards.

Is there a way to identify where this is transformed? In Listmonk itself, a dependency, or our Exim mail server ?

**Comment by knadh** [comment]
Tested this with [Mailhog](https://github.com/mailhog/MailHog) and looks like it is happening in listmonk in the e-mail formatting lib. Will investigate this. I think quotes are a valid part of the e-mail address spec too (have to investigate this too).

![image](https://user-images.githubusercontent.com/547147/146342995-da48f9ea-16b0-451a-bae1-9eea6290548a.png)

**Comment by tcitworld** [comment]
Thanks. The specs seem to give an example of when to uses double quotes here: https://www.rfc-editor.org/rfc/rfc5322#appendix-A.1.2

**Comment by knadh** [comment]
Go's built in stdlib e-mail formatter is [adding the quotes](https://pkg.go.dev/net/mail#Address.String). In the linked spec, `From: "Joe Q. Public" <john.q.public@example.com>` conforms to the same valid syntax. Thunderbird, Gmail, and Proton display it correctly too.

**Comment by tcitworld** [comment]
Thanks, I've confirmed this. I'll go check on Sympa's side then.
