### ISSUE TITLE
Use escape in HTML template

### ISSUE THREAD

**Issue by SonalikaG** [knadh/listmonk#628]
How do you escape an HTML so that HTML code is visible to the user. We are sending users HTML to embed into their own website through email and we want to escape the HTML example as shown below.

![image](https://user-images.githubusercontent.com/72000677/146550225-912899fe-0a06-4f54-8b1c-97237d384a30.png)

We have tried adding  'pre'  and 'CDATA' but it did not seem to work.

**Comment by knadh** [comment]
You can escape HTML by encoding tags into [HTML entities](https://www.webatic.com/html-entities-convertor).

**Comment by SonalikaG** [comment]
Thanks @knadh, it worked.
