### ISSUE TITLE
Extensions not found

### ISSUE THREAD

**Issue by AlexVialaBellander** [knadh/listmonk#629]
Hey,

We've successfully gotten the app to run in it's container. However, regardless of how often we try to configure SMTP, we get the following messages from the log from different configurations.

`SMTP STARTTLS extension not found`
`SMTP AUTH extension not found`

I apologise if this is a nobb Issue. Any help or clues as to why this is?

//Alex

**Comment by knadh** [comment]
Looks like your SMTP server doesn't have STARTTLS or AUTH. Have you tried turning TLS off and turning CRAM on?

**Comment by AlexVialaBellander** [comment]
Hi @knadh 👋🏽 
I am trying to configure it with G Suite. 
With TLS off and CRAM on I get the following:
`SMTP AUTH extension not found`.

Is this a local issue or misconfiguration on our end at GMAIL? What do you think?

**Comment by knadh** [comment]
You should [use](https://support.google.com/mail/answer/7126229?hl=en#zippy=%2Cstep-change-smtp-other-settings-in-your-email-client) port=587, auth=CRAM, TLS=on.

**Comment by AlexVialaBellander** [comment]
Hi @knadh
Thanks for the expeditious reply, again :D

host: smtp.gmail.com port=587, auth=cram, tls=on --> `Unrecognized Authentication Type `
host: smtp-relay.gmail.com port=587, auth=cram, tls=on --> `Unrecognized Authentication Type `

host: smtp-relay.gmail.com port=587, auth=login, tls=on -->  `Username and Password not accepted`
host: smtp-relay.gmail.com port=587, auth=plain, tls=on -->  `Username and Password not accepted`

No clue why this isn't working :/

**Comment by AlexVialaBellander** [comment]
I got it working. Looks like I had a wrong configuration.

**Comment by wgroeneveld** [comment]
> I got it working. Looks like I had a wrong configuration.

Can you perhaps elaborate? I'm facing the same problem, with gmail CRAM on: 'unrecognized authentication type'. With something filled in in HELO, 'SMTP SMARTTLS extension not found'...

**Comment by knadh** [comment]
```
host: smtp.gmail.com
port: 587
auth_protocol: login
```

**Comment by medcelerate** [comment]
I Am now having this issue as well using the google smtp-relay. I get the `SMTP STARTTLS extension not found` error

**Comment by knadh** [comment]
The SMTP server you are using does not have STARTTLS support it looks like. Please try disabling that in the listmonk SMTP config.

**Comment by medcelerate** [comment]
The issue ended up being needing to put the domain in the help field
