### ISSUE TITLE
Feature Request: Formal German translation

### ISSUE THREAD

**Issue by SnejPro** [knadh/listmonk#630]
**Is your feature request related to a problem? Please describe.**
The German language knows two different forms of address: The formal "Sie" and the informal "Du". Unfortunately, Listmonk has so far only been translated with the informal form of address.

**Describe the solution you'd like**
Therefore I suggest to rename the language "Deutsch" to "Deutsch (Du)" and add a new language "Deutsch (Sie)". I would like to support the translation.

**Comment by knadh** [comment]
Hi @SnejPro. Please see the discussion here https://github.com/knadh/listmonk/pull/593
