### ISSUE TITLE
CSV file import - 'name' column not found

### ISSUE THREAD

**Issue by andreafa** [knadh/listmonk#631]
It would be nice if listmonk could import a simple list of email addresses, one per line.

If not specified, the "name" could be taken from the first part of the email address, up to @.

**Comment by knadh** [comment]
Hi @andreafa. Please see this https://github.com/knadh/listmonk/issues/594.

**Comment by andreafa** [comment]
Hello Kailash, thanks for your answer. I have read the issue [#594](https://github.com/knadh/listmonk/issues/528).

I'm suggesting that the application fills in the name by itself. So that the user is not obliged to do so. 
The goal is to make it easier for low-end users.

**Comment by knadh** [comment]
Hi @andreafa. If the app auto-fills usernames implicitly using e-mails, it'll show up after the first import where the user most likely will end up with undesirable names (eg: `me@listmonk.app` => `Me`), after which they'll have to edit these names, or delete and re-import subscribers.

Manually adding a name column in a CSV/spreadsheet gives the user control and avoids such gotchas. I think this trivial enough for it to be fair trade-off.
