### ISSUE TITLE
Rest API upload/post a new campaign example

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#632]
Would you be so kind to provide an example or at least a description which fields are required for posting a new campaign? Currently there is none:
https://listmonk.app/docs/apis/campaigns/

Also I'd like to know if there is a way to list campaigns only for a specific list id. More specific I'd like to count them. E.g.: How many newsletters did I already send out for list xyz (excluding planned campaigns)?

**Comment by knadh** [comment]
[Added missing docs](https://listmonk.app/docs/apis/campaigns/#post-apicampaigns).

> Also I'd like to know if there is a way to list campaigns only for a specific list id.

This isn't possible right now, but is a good feature to have. Added to the to-do. Thanks.

**Comment by NicoHood** [comment]
Thanks!
I try to schedule a newsletter, but I get the error:
```
CRITICAL:root:Error uploading post: 400 {"message":"parsing time \"\\\"2022-01-05T10:00:00\\\"\" as \"\\\"2006-01-02T15:04:05Z07:00\\\"\": cannot parse \"\\\"\" as \"Z07:00\""}
```

Checking the python object shows, that the format is also set correct:
```
, 'send_at': '2022-01-05T10:00:00'}
``

`2022-01-05T10:00:00` should be a valid format, do you have any idea what the issue might be?

**Comment by NicoHood** [comment]
I think there is a quote `"` somewhere added in the code. It does not look like this happens on my side, so it might be in the listmonk rest API

**Comment by knadh** [comment]
Not sure what's going wrong here, but there is nothing in listmonk that adds quotes to the date string. It's exactly the same API that's used by the UI as well.

Here's a cURL example that works fine on the current `master` and also v2.0.0.0

```
curl 'http://localhost:9000/api/campaigns' -X POST \
	-H 'Content-Type: application/json;charset=utf-8' \
	--data-raw '{"name":"test4","subject":"test4","lists":[1],"from_email":"listmonk <noreply@listmonk.yoursite.com>","content_type":"richtext","messenger":"email","type":"regular","tags":[],"send_later":true,"send_at":"2022-01-21T18:30:00.000Z","template_id":1}'
```

**Comment by NicoHood** [comment]
I think the issue is, that I am missing the timezone information. `.000Z`

I think the error should be either more precise or the timezone should be added automatically to the timezone the system is running on/configured with? Not sure what makes more sense, you are the expert.

**Comment by NicoHood** [comment]
What about the timezone information? Did you fix that it also accepts datetimes without timezone?

**Comment by NicoHood** [comment]
As I said: It does not work without timezone information. Just try it. `2022-01-05T10:00:00` does not work. `2022-01-05T10:00:00.000Z` does.

**Comment by approached** [comment]
For php i use the library carbon. 
```php
echo $dt->toISOString();            // 2019-02-01T03:45:27.612584Z
```

Can anybody update the documentation?
