### ISSUE TITLE
Planning campaign info lost when not saving first

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#633]
**Version:**
 - listmonk: 2.0.0

**Description of the bug and steps to reproduce:**
1. Create a new campaign
2. Add a schedule time at the end
3. Do NOT save
4. click the content tab
5. Go back to the first tab -> you will see there is not date set anymore

100% reproducible

**Comment by knadh** [comment]
Unable to reproduce this. The date is retained after campaign creation and tab switch, after a refresh and tab switch etc. Can you post a video?

**Comment by NicoHood** [comment]
Sure.

https://user-images.githubusercontent.com/6888294/147578742-0e0f8f86-6ca2-40ff-bac2-d5ad34800484.mp4

**Comment by knadh** [comment]
Ah, I was unable to reproduce this as it's already fixed in the [master branch](https://github.com/knadh/listmonk/commit/19e0ea5f6ced84e353880bfad61bc6997dfaebeb).

**Comment by NicoHood** [comment]
Oh yeah, I am running the production version. Maybe it is time for another bugfix release? I know you have fixed so many bugs in the meantime, I think it'd be worth it.

**Comment by knadh** [comment]
Yep, planning a release sometime this month. There are a few things that are yet to be fixed.
