### ISSUE TITLE
Configure time

### ISSUE THREAD

**Issue by priffo-karrott** [knadh/listmonk#637]
Where can I configure hour?

**Comment by NicoHood** [comment]
which hour?

**Comment by priffo-karrott** [comment]
of system for send later email. In my screen i see that hour of send must before actual hour, but my hour is true.

**Comment by knadh** [comment]
If you are running the listmonk Docker setup, the timezone in the container may be UTC and you'll have to adjust your schedule according to UTC instead of your system time.

**Comment by mr-karan** [comment]
@priffo-karrott The current way to fix this would be to mount `/etc/timezone` from your host in the container, so something like this can be done:

```
  app:
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

Future versions of `listmonk` will have a support for `TZ` environment variable that you can set to any Timezone mentioned [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

**Comment by MaximilianKohler** [comment]
So after I run `dpkg-reconfigure tzdata` I edit `docker-compose.yml` to add those two lines under `app -> volumes`?

You mentioned a year ago that future versions will have a new feature. Is that ready yet?

**Comment by bentuna** [comment]
It would be very helpful if there was 

- a mention of the active time zone inside the "send later" time picker in Campaign settings
- a Setting in the Admin UI to set the time zone for the the whole listmonk installation
