### ISSUE TITLE
Adding recipients while the vlas is running 

### ISSUE THREAD

**Issue by tttp** [knadh/listmonk#64]
Hi,

Not sure if it's the right venue to ask questions, but:

What happens if one adds recipients (via the api) while a sending is running?

My aim being to add new recipients to an existing mailing (and change its status if closed to running )

This would allow me to have transactional emails/drip campaign and reuse the existing templating.

(I have read #63, but the need is slightly different, as the template of the email is going to be the same for each new "transactional" email

**Comment by knadh** [comment]
When a campaign starts, it sorts subscriber IDs and sets markers (start ID and end ID), and processes them in batches. New insertions (serial, auto-increment IDs) won't fall in this range, so they won't be picked up in an already running campaign.

listmonk isn't really wired to be a transactional platform, but I'm evaluating the feasibility of adding transactional features to it without severely disrupting its innards.

**Comment by tttp** [comment]
Ok, thanks.

If it helps: my need is to be able to do drip campaigns/welcome emails, eg. if you sign a petition, I want to be able to send you a "thank you, to multiply your impact, share with your friends...", and if your friend Maria signs in 3 days, I want to send her the same email. So we would have several email templates, one per petition/action (and where I wanted to re-use/abuse the mailing list editor ;)

Not that different than the double opt-in (as in: sending an email after an action), but containing links and call to actions that go elsewhere than on mailchimp

Contrary to the double opt-in, these aren't very time sensitive, so if you receive this email several hours after you sign, not a big issue (ie. it'd be fine to batch them and send them every x hours). 

as for the reporting, everything that exists would be super useful, eg. being able to see how many of these emails bounce, neatly grouped by mailing (template)

**Comment by knadh** [comment]
Thanks for the added context. I wasn't familiar with the term "drip campaign". Looks like it's timed / funneled marketing e-mails where a lead passes through multiple stages triggering e-mails. I think something like [Mautic](https://www.mautic.org/) works best for that.

Transactional e-mails (named templates, arbitrary variables in the templates) seems doable with listmonk though. I'll explore that route.

**Comment by tttp** [comment]
Yeah, 

for now, I was thinking of using listmonk api to generate the mails to be sent (add recipients), but using external tools (eg. AI, to define who should be receiving what and when)

**Comment by eddiewang** [comment]
👋 would be willing to offer some time with helping implement DRIP / transactional emails if a direction is decided upon

**Comment by knadh** [comment]
Closing this as there are is no plan to support drip campaigns right now.
