### ISSUE TITLE
Entering invalid emails possible

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#643]
I've seen someone entering an email like this: `name@web` without `.de` or `.com`. I am not sure if there are other invalid emails in the list. I think this can be filtered via backend and output an error message?

**Comment by knadh** [comment]
While "dotless" e-mail addresses are rare, [they're still valid syntactically](https://www.netmeister.org/blog/email.html#dotless). Internal mailing lists in a closed loop could also have addresses like `user@private-domain`.

**Comment by NicoHood** [comment]
Alright.
