### ISSUE TITLE
SMTP message throttling

### ISSUE THREAD

**Issue by oncletom** [knadh/listmonk#645]
Hello,

I'm glad to discover this software, and move my charity out of MailChimp.
My webhost tells me it's fine to use their SMTP connection but asks the delivery to be below 30 sent emails per minute.

I have looked around and have not found anything explicit about capping the delivery.
Is it already done by default, or is there a hidden configuration to do so?

Thank for your help, and for your answer 🙂

**Comment by knadh** [comment]
Thanks @oncletom. Under Settings->Performance, you can try these settings:

```
Concurrency: 1
Message rate: 1
Batch size: 30
Enable sliding window limit: Max message: 30, Duration: 30s
```

That said, 30/minute is painfully slow!

**Comment by philiprenich** [comment]
@thom4parisot Did this work for you? My provider is 100/hr 😅 Fortunately I only need to send <400.

**Comment by thom4parisot** [comment]
I have not followed with listmonk. As we used Brevo for newsletters, I hooked in their SMTP service to ensure good delivery of transactional emails (mainly monthly invoices :-P)
