### ISSUE TITLE
Configure SMS

### ISSUE THREAD

**Issue by priffo-karrott** [knadh/listmonk#647]
I want configure listmonk with AWS Pinpoint, sms service. Any example?

**Comment by knadh** [comment]
Connecting external messengers requires a middleware web server that accept a [JSON message from listmonk](https://listmonk.app/docs/messengers/) and relays it to the upstream (AWS Pinpoint for example). I'm not aware of any middleware that's been written to connect listmonk and Pinpoint. Let me see if I can write one.

**Comment by joeirimpan** [comment]
@priffo-karrott I have added a generic listmonk messenger [here](https://github.com/joeirimpan/listmonk-messenger). Tweak config.toml as needed and give it a go?

**Comment by knadh** [comment]
Thanks @joeirimpan. Listed the project here: https://listmonk.app/docs/messengers/
