### ISSUE TITLE
Import subscribers error

### ISSUE THREAD

**Issue by pomazanbohdan** [knadh/listmonk#65]
Version v0.5.0-alpha
```
2020/03/09 10:53:13 processing 'Export_Lead.csv'
2020/03/09 10:53:13 ignoring unknown header '﻿email'
2020/03/09 10:53:13 'email' column not found in '/tmp/listmonk639519852'
```
CSV:
email,name
xmeliv-s.rada@ukr.net,xmeliv-s.rada@ukr.net

**Comment by knadh** [comment]
I copy pasted the the values and it imported successfully.
```
2020/03/09 18:16:08 processing 'test.csv'
2020/03/09 18:16:08 imported finished
```
I think someone had reported a similar issue in the past but the issue was never found. Can you please e-mail the exact file to `kailash@nadh.in`?

**Comment by pomazanbohdan** [comment]
> I think someone had reported a similar issue in the past but the issue was never found. Can you please e-mail the exact file to `kailash@nadh.in`?

+

**Comment by knadh** [comment]
Yep, I was able to reproduce the error with the file you sent. I suspect it has to do with character encoding. Investigating this.

**Comment by pomazanbohdan** [comment]
Yes, i change from UTF8 BOM to UTF8 (notepad++), and import work

Original cvs - MS Excel - "Save as" cvs

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/faf8a7ae63cd486db7dbec922d9ef4bee25a3741 fixes this. Will get bundled in the next release.

**Comment by Jay991** [comment]
> I copy pasted the the values and it imported successfully.
> 
> ```
> 2020/03/09 18:16:08 processing 'test.csv'
> 2020/03/09 18:16:08 imported finished
> ```
> 
> I think someone had reported a similar issue in the past but the issue was never found. Can you please e-mail the exact file to `kailash@nadh.in`?

I'm having the same issue. What values did you copy past? in the csv  sheet?

**Comment by Maximator98** [comment]
Same issue
