### ISSUE TITLE
View and click details by subscribers

### ISSUE THREAD

**Issue by mrhydejc** [knadh/listmonk#650]
**Is your feature request related to a problem? Please describe.**
I need to know which subscribers open/click a campaign. (linked to https://github.com/knadh/listmonk/issues/473)

**Describe the solution you'd like**
A CSV export could do the job.
When Individual subscriber tracking is enable, add an export button in analytic view, just below the view's graph and the click's graph.
![export-details](https://user-images.githubusercontent.com/11319259/148187144-c9a8f7d3-e502-4e08-b861-3f3a91c90e18.png)
View export :
![view-export](https://user-images.githubusercontent.com/11319259/148187203-1ead49b5-ba5f-4729-b2e6-c2dd4ad208c7.png)
Click export :
![view-click](https://user-images.githubusercontent.com/11319259/148187241-9f0fcde8-e2b7-4b36-ba35-f85331cef50f.png)

**Comment by charlesmudy** [comment]
+1 for this, the overall views and clicks is great but no context to it, knowing the individual subscribers that clicked, viewed a campaign will be great

**Comment by charlesmudy** [comment]
@knadh @mrhydejc this is what I managed to do and looks quite ok. 

`
WITH camps AS (
SELECT
			subscriber_id,
			COUNT(CASE WHEN subscriber_id = null THEN 0 ELSE 1 END) AS views 
FROM campaign_views
WHERE campaign_id = 586
GROUP BY subscriber_id ),

links AS (
SELECT
			subscriber_id,
			COUNT(CASE WHEN subscriber_id = null THEN 0 ELSE 1 END) AS clicks 
FROM link_clicks
WHERE campaign_id = 586
GROUP BY subscriber_id )

SELECT subscribers.id, subscribers.email, camps.views, links.clicks FROM camps, links, subscribers
WHERE camps.subscriber_id = links.subscriber_id
AND camps.subscriber_id = subscribers.id
AND links.subscriber_id = subscribers.id
`


<img width="761" alt="Screenshot 2022-04-07 at 13 14 25" src="https://user-images.githubusercontent.com/1445007/162196482-b153f47f-1c06-460a-b7f0-994fc8f89a4c.png">

**Comment by mrhydejc** [comment]
@charlesmudy take a look at this PR : https://github.com/knadh/listmonk/pull/689

**Comment by niraj-ranjan-comprinno** [comment]
Hi, Above query is failing in scenario like
Suppose no one clicked the link but view the compaign

**Comment by c-seeger** [comment]
Upvote. In Settings there is an option for individual subscriber tracking but I can't find a visualisation for this
