### ISSUE TITLE
Add more useful filter params to GET /campaigns API.

### ISSUE THREAD

**Issue by knadh** [knadh/listmonk#651]
Ref: https://github.com/knadh/listmonk/issues/632

**Comment by NicoHood** [comment]
I'd like to note, that I am also filtering only regular campaigns and campaigns before date X. So the filter should be somewhat dynamic, maybe we could add just multiple parameters?

**Comment by knadh** [comment]
Makes sense.

- `list_id[]`
- `from_date, to_date`

**Comment by NicoHood** [comment]
Or maybe `before` and `after`?
By regular campaigns I mean `type` = `regular` (not optin)

**Comment by knadh** [comment]
Closing this for now. Campaigns now support querying by `tags`.
