### ISSUE TITLE
Uploaded media isn't rendered properly by some clients when URL has spaces

### ISSUE THREAD

**Issue by nikochiko** [knadh/listmonk#652]
**Version:**
 - listmonk: [eg: v1.0.0] v2.0.0
 - OS: [e.g. Fedora] Ubuntu 20.04

**Description of the bug and steps to reproduce:**
Some clients (specifically GMail) do some procedure on media links inside emails, which substitute spaces in the URL for "+" instead of "%20". This would result in 404 from Listmonk.

To reproduce:
1. Upload an image that has spaces in its name via Media uploads
2. Use the image in an email and send it to an address that can be viewed from GMail.
3. The image won't load because it won't find it on the Listmonk server.

e.g. https://listmonk.fossunited.org/uploads/December%20foss%20Twitter.jpg won't render on GMail, and Google will instead try to grab it from https://listmonk.fossunited.org/uploads/December+foss+Twitter.jpg

**Screenshots:**
![image](https://user-images.githubusercontent.com/37668193/148355687-b4a67d36-df7a-4bf9-87c8-412e37d2b362.png)

**Fix:**
I see two possible ways we can fix this from listmonk:
* Change the filename while receiving the upload, substituting space character for '+' or '-'
* ~~Modify the file server to consider + as %20~~ may get complicated with permutations arising from multiple white spaces and actual + characters in the file name

I would like to submit a fix for this, if this is indeed something that should be fixed from listmonk.

**Comment by knadh** [comment]
@nikochiko I thought you'd send a PR for this :smile: We can replace the spaces with `-` here: https://github.com/knadh/listmonk/blob/a2458cf66817221566e8396d2c2bfa41200c2d1e/cmd/utils.go#L30

**Comment by nikochiko** [comment]
> I thought you'd send a PR for this

Yeah and I didn't want to spam PRs :smile: 

Thanks for the pointer

**Comment by nikochiko** [comment]
Probably the same also extends to tab and newline characters in filenames. I'm not sure if those characters will also be replaced with something by mail clients, but it seems like a good idea to normalize for those characters too.
I'll include that in the PR as well.
