### ISSUE TITLE
hey! Well Am trying to setup Listmonk.

### ISSUE THREAD

**Issue by code123841** [knadh/listmonk#653]
Hi, I'm trying to setup docker with listmonk and next.js
here's my docker compose file 

```
# NOTE: This docker-compose.yml is meant to be just an example guideline
# on how you can achieve the same. It is not intented to run out of the box
# and you must edit the below configurations to suit your needs.

version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  ports:
    - "9000:9000"
  networks:
    - listmonk
  environment:
    - TZ=Etc/UTC

x-db-defaults: &db-defaults
  image: postgres:13
  ports:
    - "9432:5432"
  networks:
    - listmonk
  environment:
    - POSTGRES_PASSWORD=listmonk
    - POSTGRES_USER=listmonk
    - POSTGRES_DB=listmonk
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 
services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    <<: *app-defaults
    container_name: listmonk_app
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml

  demo-db:
    container_name: listmonk_demo_db
    <<: *db-defaults

  demo-app:
    <<: *app-defaults
    container_name: listmonk_demo_app
    command: [sh, -c, "yes | ./listmonk --install --config config-demo.toml && ./listmonk --config config-demo.toml"]
    depends_on:
      - demo-db

networks:
  listmonk:

volumes:
  listmonk-data:
```

My nextjs code for connecting ot the Listmonk docker continer
```
  async function Postdata(){
    
const response = await fetch('http://localhost:9000/api/subscribers');
const data = await response.json();

console.log(data);
  }

```

# and here's my error
![image](https://user-images.githubusercontent.com/57910021/148527156-cd43b2cd-ab2f-4135-a3b7-12cd171baf53.png)

But when i try using postman it works! 

Context: 
Using node fetch with Yarn.

and my docker desktop 
![image](https://user-images.githubusercontent.com/57910021/148527294-0582698c-13f4-40c9-bfb2-fbc8453a252a.png)

**Comment by knadh** [comment]
`Failed to fetch` doesn't explain much. `catch` that error and check the stack trace? Also, I don't see the request carrying BasicAuth credentials. Maybe that's why the request is failing?

**Comment by code123841** [comment]
@knadh  Basic Auth Cred? I don't think so i follow you here Care to explain?

**Comment by knadh** [comment]
The username and password you've set for the instance should be used with the API as well. With curl, this would be `curl -u yourusername:yourpassword http://localhost:9000/api/subscribers`. With `fetch()`, you'll have to set the `Authorization` header. Something like https://observablehq.com/@mbostock/fetch-with-basic-auth

**Comment by code123841** [comment]
Hm Okay,

```
  async function Postdata(){    
    try {
      var test = await fetch('http://localhost:9000/api/subscribers');
      const data = await test.json();

      console.log(data)

      
    } catch (error) {
      console.log(error);
}
}

Postdata();
```

tried this but did not work... I see nothing in the console..

**Comment by knadh** [comment]
Sorry, I'm unable to help with this because this isn't a listmonk issue, but an external Node-HTTP-request issue. That said, you need to add the authorization headers with your username and password for the APIs to work.

**Comment by code123841** [comment]
@knadh  The thing is I don't remember Setting up a password for the api I just got the docker compose file up in running and then went into localhost:9000..

**Comment by code123841** [comment]
hey! @knadh  The connection to the API went well, yet another problem right now.. Hope, am not disturbing you.. 
I've posted this q on to stack over flow.. Please Do Let me know if y9ou have any solutions

https://stackoverflow.com/questions/70638408/problem-with-the-unmarshal-error-in-the-api-listmonk

**Comment by ganeshsundaram39** [comment]
Using Axios worked for me

    let apiResponse = await axios.post(listMonkUrl + "/api/subscribers", json, {
      headers: {
        "Content-Type": "application/json",

      },
      auth: {
        username: listMonkAdminUsername,
        password: listMonkUrlAdminPassword
      }
    });
