### ISSUE TITLE
Confirming List Subscription via the API

### ISSUE THREAD

**Issue by ay8s** [knadh/listmonk#654]
Thanks for all of your work on Listmonk. It looks like it's going to be a great solution for migrating from Mailchimp. 

I'm working on a couple of pages hosted on our site to handle unsubscribing without sending subscribers to Listmonk itself. 

My plan is to adjust the confirmation template to point to an URL on our site with the UUID. Then trigger an API call to confirm the list subscription however I've not quite found a way to confirm the subscription. It looks like the /api/subscribers/:id endpoint PUT request supports preconfirm_subscriptions but I don't think that will work for existing subscriptions and doesn't seem to in my testing.

Apologies if this is something I've overlooked or if its one of the API aspects that isn't documented yet.

Thanks again 🙌

**Comment by knadh** [comment]
Thanks @ay8s. This is a bit of a miss and is being [tracked here](https://github.com/knadh/listmonk/issues/604#issuecomment-981631799). A dedicated confirmation API will be available in the next release.

For now, you could POST to the same endpoint that the HTML form posts to. You can pass multiple `l` list UUID params.

```shell
curl 'http://localhost:9000/subscription/optin/$subscriber_uuid' -X POST \
	--data-raw 'l=$list_uuid&confirm=true'
```

**Comment by knadh** [comment]
Closing this to track it on #604.
