### ISSUE TITLE
Additional space character added to URLs when converted to raw html

### ISSUE THREAD

**Issue by aksanoble** [knadh/listmonk#655]
**Description of the bug and steps to reproduce:**
Edit the content in Rich text, add URL and then covert to Raw HTML. Additional space character gets added to all URLs. I believe this happens because the generated html is formatted with new line and character such as `,`, `.` moved to the next line. 

```html
  </em>
  . It captures the roles and emotions of the nest protectors and the excitement of the annual hornbill breeding season. Watch it
  <a href="https://example.com" target="_blank" rel="noopener">
    here
  </a>
  .
  <br />
```
 
**Screenshots:**
Additional space character added at the end of each of the URL. 
<img width="549" alt="Screenshot 2022-01-10 at 4 45 24 PM" src="https://user-images.githubusercontent.com/7472506/148757518-290e59e9-29c5-41b2-9ed6-863af3e034da.png">

**Comment by knadh** [comment]
Ah yes. This needs to be fixed. Has been a painful experience dealing with HTML formatting unsurprisingly.
