### ISSUE TITLE
[API] Updating a subscriber also sends opt-in

### ISSUE THREAD

**Issue by marcinkunert** [knadh/listmonk#656]
I've noticed that the API method:  `PUT  /api/subscribers/:id ` described as `Updates a subscriber by ID` (https://listmonk.app/docs/apis/subscribers/) also causes an opt-in campaign sendoff.

In my opinion, this method should only change the subscriber data.

**Comment by knadh** [comment]
Thanks for pointing this out @marcinkunert. Fixed this behaviour and also added an explicit option on the update UI.

![image](https://user-images.githubusercontent.com/547147/149618322-1c2d29f3-423b-4880-914d-c5a77ea7ae69.png)
