### ISSUE TITLE
Question: Custom Attribs for dummySubscriber?

### ISSUE THREAD

**Issue by jhrdt** [knadh/listmonk#657]
Hi,

is it possible to add additional Attribs to the dummySubscriber ([subscribers.go#L71](https://github.com/knadh/listmonk/blob/e9709e54eefd46f1d37df5c484df7c6fdacaea7c/cmd/subscribers.go#L71)) that is used for template previews?

Best-Case: 
+ The Attribs should be changeable through the UI.

Best,
Jhrdt

**Comment by knadh** [comment]
Not possible now, unfortunately. Two possibilities:
- Make the attribs changeable on the UI.
- Take an existing subscriber's e-mail ID and use their attributes to preview, like how the "Send test" feature works.
