### ISSUE TITLE
One-click install with Caprover

### ISSUE THREAD

**Issue by sandoche** [knadh/listmonk#659]
Hi,

It would be nice to have it in the one-click installable apps of Caprover:
https://github.com/caprover/one-click-apps/issues/599

More details here:
https://caprover.com/docs/one-click-apps.html

**Comment by knadh** [comment]
Hi @sandoche. CapRover looks interesting, but I'm not familiar with it. The setup also [looks simple](https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/wordpress.yml). If you're familiar with the system, would you be able to write an app schema and test it out on your installation?

**Comment by sandoche** [comment]
I've never done it but I can give a try when I have a bit of free time!

**Comment by sandoche** [comment]
I started it and someone had completed it, it is now released on caprover one click install:
https://github.com/caprover/one-click-apps/issues/599

**Comment by knadh** [comment]
Thanks great to know. Thanks @sandoche !
