### ISSUE TITLE
Heroku Issue -  Item could not be created

### ISSUE THREAD

**Issue by sandoche** [knadh/listmonk#661]
**Version:**
 - listmonk: 2.0.0

**Description of the bug and steps to reproduce:**
When I try to install it with the deploy to heroku button I get the following error:

    We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Screenshots:**
![image](https://user-images.githubusercontent.com/3635348/149209477-266d5119-8281-430e-af70-cc0b1590dc3a.png)

**Comment by knadh** [comment]
Whoa, I've no idea what this means! Could you please speak to Heroku and figure out what exactly this means? Plenty of listmonk Heroku instances exist.

**Comment by erayaydogdu** [comment]
I'm also having the same issue. Any suggestions?

**Comment by gadiarohit** [comment]
@knadh seems like source code violation error - https://youtu.be/QsisV_z8lNQ

**Comment by candidexmedia** [comment]
I tested it and received the same issue. Strange because my existing Listmonk deployment from last year works...

The video @gadiarohit shared solves the issue. Essentially:

- Fork the Listmonk Heroku: https://github.com/knadh/listmonk-heroku
- In your browser's address bar, type the following: https://heroku.com/deploy?template=https://github.com/KNADH/listmonk-heroku -> Change the "knadh" to your GitHub username, and go to the URL

**Comment by knadh** [comment]
hm, seems like some sort of an automated false positive block. I have renamed the repo for now and changed the button URLs everywhere: https://github.com/knadh/listmonk-heroku-deploy

If this happens again, will try and raise a ticket with Heroku and figure out what's going on. Thanks everyone for helping with this!

**Comment by karthik666manjunath** [comment]
Tried to deploy again today. But failed with the same issue. 

@knadh : I think we should raise a ticket with Heroku ?

**Comment by knadh** [comment]
Yes, please raise a ticket with Heroku. I think they've blanket banned mailing list apps.

**Comment by candidexmedia** [comment]
> Tried to deploy again today. But failed with the same issue.
> 
> @knadh : I think we should raise a ticket with Heroku ?

I'd give Railway a try as well. It's pretty similar to Heroku, and they have a new Listmonk starter. 

As soon as I'm able to figure out how to migrate the databases, I'm switching to Railway from Heroku, especially in light of Heroku's new announcement.
