### ISSUE TITLE
Kafka integration / webhooks

### ISSUE THREAD

**Issue by mrhydejc** [knadh/listmonk#662]
I would like to integrate listmonk with kafka, my specifics needs are : 
- Create suscribers from a kafka topic
- Create draft campaigns from a kafka topic
- When a subscriber click a link, feed a kafka topic

I plan to code this connector and would like to discuss about the right way to do it.
It could be a new GitHub project acting as a sidecar as kafka is not a concern to lismonk.
I know listmonk is not an automation-marketing tool but I want to try.

I can create suscribers/campaigns easily with listmonk API.
The most complicated part is to feed the kafka topic when a link is clicked.
I could use DB polling as links_click are not available in the API. But i would like to avoid polling.

What do you think about implementing webhooks in listmonk ?
**Could there be a webhooks administration page a bit like mautic do ?**
With this kind of feature, listmonk integration could be improved and it could be better connected with other apps by coding connectors.

![image](https://user-images.githubusercontent.com/11319259/149317981-861c9694-13a7-4284-96da-50d8f6b99ae3.png)

**Comment by knadh** [comment]
A "sidecar" system works well. At work, we have a simple Kafka consumer that consumes user creation messages from our CRM and UPSERTs into the listmonk `subscribers` table.

Yep, planning to add webhooks: https://github.com/knadh/listmonk/issues/658

**Comment by Grisgruis** [comment]
You could try to add https://debezium.io/ into the project, so you can directly load changes from db into kafka
