### ISSUE TITLE
Listmonk subscriptions management support requested

### ISSUE THREAD

**Issue by SonalikaG** [knadh/listmonk#666]
@knadh  As per our discussion on email, I am creating this ticket for the Listmonk 'Unsubscribe' feature related issue

When a user clicks on the 'Unsubscribe' button in a newsletter, he is asked to fill in Listmonk credentials. Please see the snapshot below. Instead, the recipient should redirect to the Subscription management screen directly without any sign-in step which gets recorded /updated in the Listmonk list of subscribers.

![image](https://user-images.githubusercontent.com/72000677/150093740-c2ac6b35-54f9-44c1-bcb8-8a78be14fe15.png)

The HTML code used for 'Unsubscribe' in the template is shown in the image below.
![image](https://user-images.githubusercontent.com/72000677/150131704-88591f5a-3389-47b2-8c08-e193654a028d.png)

Please let me know the reasons this issue may be occurring and how can we resolve it. Thank you.

**Comment by jackdanielux** [comment]
You have an issue with your proxy.  There were many issues regarding this,
but all were related to host proxy settings.

**Comment by SonalikaG** [comment]
As mentioned by @knadh, it was a misconfiguration issue and now the issue is fixed. Thanks.
