### ISSUE TITLE
Link tracking not working on template variables

### ISSUE THREAD

**Issue by charl4e** [knadh/listmonk#667]
- listmonk: 2.0.0
 - OS: Ubuntu

When you try to apply link tracking to a template variable, it either fails the validation or it simply doesn't convert the link to a tracked link. 

I've tried to apply the following:

```
<a href="{{ .Subscriber.Attribs.jobs.link }}@TrackLink">View</a>

<a href="{{ TrackLink ".Subscriber.Attribs.jobs.link" }}">View</a>

<a href="{{ TrackLink {{ .Subscriber.Attribs.jobs.link }} }}">View</a>

<a href="{{ .Subscriber.Attribs.jobs.link@TrackLink }}">View</a>
```
Is there perhaps a way to track links generated from the attributes on a subscriber? Feels like I'm missing something simple here.

**Comment by knadh** [comment]
Ouch, this is a miss. Failed to foresee variables being passed to `TrackLink`. Will fix this shortly.

**Comment by knadh** [comment]
`<a href="{{ TrackLink .Subscriber.Attribs.jobs.link }}">View</a>` works in https://github.com/knadh/listmonk/commit/d2cf6e0f14fd118ea1a060ed5e8d25467f9218a2. This will be available in the upcoming release.

**Comment by HiteshPaliya** [comment]
Hi, I'm trying to get count of people who has clicked the `{{ UnsubscribeURL }}` in the campagin analytics!

I tried adding **TrackLink** at multiple places with the UnsubscribeURL template variable, but wasn't successful.
```
<a href="{{ UnsubscribeURL@TrackLink }}" style="color:black;">Unsubscribe</a>
<a href="{{ TrackLink {{ UnsubscribeURL }} }}" style="color:black;">Unsubscribe</a>
<a href="{{ TrackLink UnsubscribeURL }}" style="color:black;">Unsubscribe</a>
<a href="TrackLink {{ UnsubscribeURL }}" style="color:black;">Unsubscribe</a>
<a href="{{ UnsubscribeURL }}@TrackLink" style="color:black;">Unsubscribe</a>
```
The last one did showed the URL but *@TrackLink* text was appended to the end so it threw **Invalid UUID(s)** error when navigating to Unsubscribe page.

I just want to know how many users clicked on the Unsubscribe link in the footer.
So is there a better way to achieve this or am I doing something wrong?

Thanks

**Comment by knadh** [comment]
`{{ TrackLink (UnsubscribeURL .) }}` <-- This will work. This isn't recommended because the unsubscribe link is unique for each user, so the UI will not show a total count, but one click per unique unsubscribe link per user.
