### ISSUE TITLE
Upload to S3 Minio preview is broken

### ISSUE THREAD

**Issue by drgroot** [knadh/listmonk#669]
**Version:**
 - listmonk: v2
 - OS: docker

**Description of the bug and steps to reproduce:**
Media upload does not work
1. Configure media uploads to use minio s3. set bucket type to private
2. Upload media under the Campaigns Menu. (this step works, and the file successfully uploads)
3. Click preview of image
 url of image is:  `https://<bucket>.s3.amazonaws.com/` instead of configured minio url

**Comment by knadh** [comment]
Hi @drgroot,
I am unable to replicate this on v2.0.0 running locally with a local Minio instance.

The settings look like this:
![image](https://user-images.githubusercontent.com/547147/150669981-545fbcaf-b801-4daf-8920-28ed0bd73350.png)


And thumbnails and the original image both render fine with the Minio URL.

![image](https://user-images.githubusercontent.com/547147/150669964-56b78efc-7b12-400a-8701-a3490a74d50b.png)
