### ISSUE TITLE
Details of Environment Variables missing

### ISSUE THREAD

**Issue by shankardevy** [knadh/listmonk#670]
**Is your feature request related to a problem? Please describe.**

I see the discussion [here](https://github.com/knadh/listmonk/pull/66) on adding environment variables information in the Github Wiki, however, it looks like the Wiki for this project has been disabled so there is no information about environment variable names.

**Describe the solution you'd like**

Make this information on environment variables as part of README file.

**Comment by knadh** [comment]
This is available in the docs: https://listmonk.app/docs/configuration/
