### ISSUE TITLE
How to edit content in the default 'Unsubscribe' form

### ISSUE THREAD

**Issue by SonalikaG** [knadh/listmonk#672]
@knadh Can you please specify the steps for updating/editing the default content in the 'Unsubscribe' form.

![image](https://user-images.githubusercontent.com/72000677/150564861-e6a26688-03ae-43ac-8711-2effc9e600c9.png)

**Comment by knadh** [comment]
Hi @SonalikaG. This requires editing the templates externally and re-configuring listmonk a bit to load the external templates from a directory. It's documented here https://listmonk.app/docs/templating/#system-templates
