### ISSUE TITLE
Add "no opt-out" list type

### ISSUE THREAD

**Issue by TheAssassin** [knadh/listmonk#673]
In an organization I occasionally help with IT stuff, all communication is performed via e-mail. Legally, this organization is required to make sure important messages (e.g., invitations to general assemblies) are sent out to the e-mail address members have submitted on sign-up. Currently, all such messages are sent out by hand or using add-ons like MailMerge. Using a newsletter system such as listmonk, which includes important features like bounce handling, would greatly simplify sending out such messages.

At the moment, there is currently no list type which does not allow opting out of subscriptions. Please add a "No opt-out" list type to listmonk, whose subscriptions are managed exclusively by the listmonk admins. In a use case like this one, this is completely fine legally: subscribers are added when they become members of the organization, and will be unsubscribed once they leave it.

**Comment by knadh** [comment]
Hi @TheAssassin. Will give this some thought.

In the meanwhile, to disable unsubscribes in your environment, you can:
- Disable the `Include Unsubscribe header` in Settings -> Privacy
- Remove the "Unsubscribe" link from your templates
- And optionally, block `"/subscription/*` in your HTTP server/proxy.

**Comment by TheAssassin** [comment]
Thanks for the tip. I considered those workarounds already, but I need both types of lists, and don't really want to maintain two instances.

**Comment by TheAssassin** [comment]
Have you had a chance to think about this yet?

**Comment by knadh** [comment]
Forgot to update here, but a `no-optout` list makes sense. I've added it to my to-do to try (or until there is a proposal and a PR welcome). Adding the new type involves quite a bit of changes.

**Comment by amitsrourabi** [comment]
Is there any update on this?

**Comment by MentalNomad** [comment]
Another +1 for some manner of a no-optout function.

Our organization has several informational email types which we're happy to let people opt out of, but we also have certain email types which are regulatory requirements and which we must send. We don't want to have to run two instances of mailing list software to give people options and still meet our obligations.

**Comment by brookgagnon** [comment]
+1 also :). (For similar reasons as above - we want a non-optional internal/organization news for staff.)

**Comment by herzkerl** [comment]
Any news regarding this feature? :)

**Comment by TheAssassin** [comment]
Just noticed that this issue has been closed a year ago without being resolved. Since I am still interested in this, I would like to have the issue reopened.

(Side note: stale bots are annoying...)

**Comment by groundsada** [comment]
I am interested in this well

**Comment by violoncelloCH** [comment]
@knadh, could you reopen it? :)

**Comment by migs35323** [comment]
+1
