### ISSUE TITLE
In template every html tag attribute's is getting wrongly modified in the sent message

### ISSUE THREAD

**Issue by RKVodde** [knadh/listmonk#674]
**Version:**
 - listmonk: [eg: v2.0.0]
 - OS: [e.g. Docker]

When the email sent, in the generated content every html tag's attributes are getting modified incorrectly due to which the content in the mail is not showing in a proper way.

For example:
`<div class="footer"> some content  </div>`

is being changed to

`<div class=ooter"> some content </div>`

![image](https://user-images.githubusercontent.com/7332974/150774954-08202c35-24a6-45f3-a9bf-da83bb9d1f2c.png)

**Comment by knadh** [comment]
This is a strange issue. Haven't seen this in production anywhere.

Would you be able to share the full raw source of the template so that I can try and reproduce it locally?

**Comment by RKVodde** [comment]
it seems this is done by "postalserver" which is my SMTP server and still not sure why it is happening.
