### ISSUE TITLE
Automating the release process

### ISSUE THREAD

**Issue by avanier** [knadh/listmonk#675]
Hiya!

This is more of general concern than an actual ask. It's been a while we've seen a release and quite a few _(yummy)_ features have been added since last October. You know the usual woes: the more we wait for a release, the more jarring the upgrade will be.

My goal here is not to put it on @knadh 's shoulders to produce more releases, but it might be worthwhile to think about guidelines for cutting releases and automating what we can of the process.

For example, if we were to stick to semantic versioning and we created a release for every new feature merged, we'd probably be at `2.12.x` by now, so that's not necessarily the best approach. :D Perhaps a gateway step would be to automate cutting release candidates for every new feature _(or whatever we can figure makes sense programmatically)_ and we could try to vet a _"stable"_ release out of the lot on a quarterly basis.

For example, in my actual use-case I have interest in consuming the recently added S3 URL features, but I'm not quite comfortable cutting myself a build from `master` and releasing it to production without knowing there's been other pairs of eyes on it.

Food for thought.

**Comment by mr-karan** [comment]
>  There is a release candidate (RC) system for bleeding edge releases. This can be automated. @mr-karan, would you have some time to give this a shot?

We can have a `rc` branch on GitHub and setup GH-Actions to build a new release with the format: `rc-{{commit-hash}}`. Whenever you're ready to create a new RC, you can rebase the `rc` branch from `master` and trigger the build.

If this approach sounds fine, I'll try it on my local fork

**Comment by knadh** [comment]
Yep, that sounds good. I don't think we should be pushing `rc` bundles to the releases page though. We can publish a Docker image and figure out a way to publish the RC zip somewhere. Maybe there can just be one `rc` tag (release) on GitHub that's updated with every release?

**Comment by avanier** [comment]
Ah! I feel pretty sheepish not having seen the documentation about RCs! :sheep: 

The only flag I'll raise if we publish a single image with the `rc` tag, that makes it a bit harder for people to communicate which release candidate they've been using, to my point about confidence. To this I like @mr-karan 's idea of `rc-{commit-hash}` better, but have appreciation for how non-trivial it would be to implement a cleanup routine so we don't spam ourselves with old RC images.

I think just knowing the strategy is improvement enough from my perspective.

**Comment by mr-karan** [comment]
> The only flag I'll raise if we publish a single image with the rc tag, that makes it a bit harder for people to communicate which release candidate they've been using, to my point about confidence

+1 these are my concerns too. Releases should preferably be immutable. It's going to be a maintenance headache if people report a certain feature doesn't work in their `rc` version but the maintainer won't have an idea which `rc` version is the person using.

On the other hand, frequent rc tags can also become messy on GitHub and Dockerhub. I think it's possible to prune older releases via GitHub Actions, but doing the same for Dockerhub will be challenging.

**Comment by knadh** [comment]
Sorry, I wasn't referring to the actual version of the release. Binaries will have the correct build date, commit hash etc. I was suggesting that we could create a single `rc` release tag on the GitHub releases page and use that as a placeholder for re-uploading RC assets after each release. Basically, a single `/releases/rc` page as a hack to avoid crowding the releases page.

**Comment by avanier** [comment]
I get you on the avoiding to crowd the release page. Even as a developer it's not great trying to filter through pre-releases and what not to find a stable release on bigger project.

On the other hand, I was raised to believe that [tags should be immutable](https://i.imgur.com/FsguyU2.gif). _(Watch-out, Firefly reference.)_ My first reflex would be to treat releases likewise, even semi-fictitious ones.

Just dropping thoughts. Let's say we don't do tags or GH releases, but do publish Docker images, but clean them up on a regular basis. I can easily foresee someone complaining they were using it. It's a bit of a :rabbit: :hole: / pandora's box. Also, opening the door to people running RCs in production without a modicum of effort is a bit icky. :thinking: _(Yeeeeah ... I just realized I'm describing myself.)_

At this point I'm starting to think sticking to the current `rc` mechanism might be the saner option. I mean, people aren't lining up asking for _"named"_ releases short of me. It seems like the safer thing to do for now. :sweat_smile:
