### ISSUE TITLE
Display unique campaign views instead of overall views

### ISSUE THREAD

**Issue by marcinkunert** [knadh/listmonk#676]
![image](https://user-images.githubusercontent.com/2963232/150948207-8722d12c-7fa3-444d-94b0-1c35441f0834.png)

![image](https://user-images.githubusercontent.com/2963232/150948570-4ffece13-2b8c-4e9b-ba0d-0f7dfdfc9f03.png)

Currently, the UI displays the total sum of views per campaign. If we have 10 users and only one user opens the email 10x times, the views' percentage will show 100%. 

This is misleading (#522, #561, #571) and in my opinion rather useless. The number displayed should be 1 view and 10% open rate. 

I could even try to create a PR for this, but first need your approval @knadh. I've seen there is a work in progress on adding another field #572, but imo this should be replaced.

**Comment by rudresh051** [comment]
Hi @knadh there seems to be an issue with the unique view count. The count is increasing when the same email is opened multiple times.

**Comment by dashrandom** [comment]
Can confirm the above. In the "campaigns" page the value seems to be wrong. But when viewing the details of an individual campaign, it seems correct. Some screenshots for comparison.

![2023-12-27 07_09_57-Campaigns _ listmonk and 22 more pages - Personal - Microsoft​ Edge](https://github.com/knadh/listmonk/assets/9287237/cf1f26cc-66ce-429e-ac29-c68948774256)
![2023-12-27 07_09_45-Analytics _ listmonk and 22 more pages - Personal - Microsoft​ Edge](https://github.com/knadh/listmonk/assets/9287237/6018afb8-6866-4c9c-94f1-990665e0fa02)

**Comment by MaximilianKohler** [comment]
Mine has also always been like @dashrandom's screenshot, and I've always had `Individual subscriber tracking` enabled.
