### ISSUE TITLE
Link click should automatically add a view if none exists

### ISSUE THREAD

**Issue by marcinkunert** [knadh/listmonk#677]
Some email clients like Thunderbird block images in order to not send back information about opening an email. There is nothing we could do about it, but if the user clicks any link in the email, it could register a view to make the analytics more accurate.

**Comment by knadh** [comment]
This should be doable by tweaking [`register-link-click`](https://github.com/knadh/listmonk/blob/6a5ed432758b77c748adfc14dd3897a61d9c0944/queries.sql#L780).

**Comment by knadh** [comment]
Revisiting this just now. Thinking about it, it may not be appropriate to register views every time there's a click. Since clicks themselves are recorded separately, that already serves as a good-enough indicator of activity.
