### ISSUE TITLE
Looping through subscriber attributes?

### ISSUE THREAD

**Issue by charl4e** [knadh/listmonk#678]
Is it possitble to loop through the subscribers custom attributes? I have a dynamic amount of repeating attributes on each subscriber, and would like to apply a template section to those repeating attributes, since the number of items in the object are never consistant. An example below:

`{
  "Attribs" : {
    "jobs" : [
      {
        "title" : "job title",
        "city": "location",
        "company": "company posting the job",
        "link"  : "link to job"
      },
      {
        "title" : "job title",
        "city": "location",
        "company": "company posting the job",
        "link"  : "link to job"
      },
      {
        "title" : "job title",
        "city": "location",
        "company": "company posting the job",
        "link"  : "link to job"
      }
    ]
  }
}`

The amount of repeating items differs per subscriber, so would like to repeat that part of the template, regardless of the amount of items in the array. I've looked at sprig functions, but it seems the documentation of how to implement it does not take effect on listmonk. It's also completely possible that I'm using the incorrect syntax:

`{{- range .Subscriber.Attribs.jobs }}`

and then to use them inside the range `{{ .title }}`

All what happens is that section gets hidden from the template. There a correct way to do this?

**Comment by knadh** [comment]
`Attribs` is the system identifier for referring to the JSON payload. Your actual data shouldn't have it. It should look like this:

```json
{ "jobs" : [ { "title" : "job title", "city": "location", "company": "company posting the job", "link" : "link to job" }, { "title" : "job title", "city": "location", "company": "company posting the job", "link" : "link to job" }, { "title" : "job title", "city": "location", "company": "company posting the job", "link" : "link to job" } ] }
```

Then, `{{ range .Subscriber.Attribs.jobs }}` should work.

**Comment by charl4e** [comment]
Ah my bad! The `Attribs` was added in the example just to indicate where the data I'm trying to use is coming from. 

Seems the included `-` I had in my opening and closing tags was the issue.  `{{ range .Subscriber.Attribs.jobs }}` is working perfectly now. 

Thank you for the help!
