### ISSUE TITLE
Translate or edit stock templates

### ISSUE THREAD

**Issue by gerricom** [knadh/listmonk#68]
First things first: This is an awesome software and I'm really looking forward in using this for our little newsletter. Thank you very much for sharing this with us!

As we are based in Germany, we'd like to translate all the stock templates (e.g. opt-in mails etc.) and do some minor optical tweaks. Am I right that I need to clone this repo, make my changes and then compile my own build of listmonk? Or is there a kind of easier solution in changing the templates?

**Comment by knadh** [comment]
Thanks @gerricom. In the last release, all static files got grouped into a better directory structure. If you wait for a couple days, I can push a `--static-dir=your/custom/dir` flag that'll let you load your own custom templates without the need to recompile.

**Comment by gerricom** [comment]
That would be a great solution great! Thank you!

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/71803ab1af6294a9d5b6381487654cfc8417aa94 adds a new `--static-dir` flag to listmonk. This will get bundled into a release shortly after a couple of other patches are ready. If you want to try it out before that, you can [compile master](https://github.com/knadh/listmonk/wiki/Developer-setup). Cheers.

PS: Adding support for full fledged internalization using language files is on my to-do.
