### ISSUE TITLE
ListMonk with Caddy Sends Campaign Emails But Doesn't Detect or Count Opened Emails

### ISSUE THREAD

**Issue by PackMeister** [knadh/listmonk#682]
**Version:**
 - listmonk: v2.0.0
 - OS: Debian 11.2

**Description of the bug and steps to reproduce:**
My test campaigns get sent, received and the emails opened, but I never see individual or collective VIEW stats.
In SETTINGS --> PRIVACY I've activated INDIVIDUAL SUBSCRIBER TRACKING.
My test campaigns all use the DEFAULT TEMPLATE which includes {{ TrackView }}.

**Screenshots:**
<img width="1090" alt="ListMonkImage1" src="https://user-images.githubusercontent.com/35346304/151683026-2e39f62f-42d9-4c35-87ac-6c5b88d8c9a4.png">
<img width="1010" alt="ListMonkCampaignSetup" src="https://user-images.githubusercontent.com/35346304/151683030-49c3606f-cfc8-46fe-9aea-57d1f18f9e99.png">
<img width="1385" alt="ListMonkCampaignContent" src="https://user-images.githubusercontent.com/35346304/151683032-f359d9af-3c5c-4342-a031-d14f7e38af86.png">

**Comment by knadh** [comment]
This happens because of two reasons:
1) The pixel <img> tag isn't in the e-mail or has not been loaded.
2) There is a web server proxy in front of listmonk that isn't letting the requests through.

Can you check the source/HTML of the e-mail received in your mailbox to ensure the <img> is in tact? If yes, can you copy the image URL from it and open it in your browser manually? It should render a 1x1px image.

**Comment by PackMeister** [comment]
Yup, this must be related to the configuration of my reverse proxy.

I recently migrated all my from nginx to Caddy.

I'm unfamiliar with using/exposing REST endpoints via proxies.

Has anyone an example (or links to) of setting up ListMonk's required routes with ANY reverse proxy like Nginx or Caddy?

Pretty sure this is why post-delivery functions like 1-pixel images for subscriber tracking, subscription pages, bounces, etc. are not working.

<img width="951" alt="ListMonkEndPointConfiguration" src="https://user-images.githubusercontent.com/35346304/151711013-21137c79-fff7-48aa-986f-38127e0cb029.png">

**Comment by knadh** [comment]
Can you share your Caddy config for listmonk?

**Comment by PackMeister** [comment]
listmonk.14servers.net {
	# Set this path to your site's directory.
	#root /opt

	# Enable the static file server.
	#file_server

	# Another common task is to set up a reverse proxy:
	reverse_proxy * localhost:9000

	# Add compression
	encode zstd gzip
}

**Comment by PackMeister** [comment]
Are the subscriber-specific 1x1 pixel image files created on-the-fly by the Caddy executable and embedded in outgoing emails?

I'm able to see now that the tracking pixel IS being received...when I do source on the opened email.

DIV class=3D"gutter" style=3D"padding: 30px;">&nbsp;<img src=3D"https:=
//listmonk.14servers.net:9000/campaign/0ee90265-099f-4363-a9e7-84a6bb80c8c0=
/c2b40353-dd60-48c4-bdac-a671141a53ac/px.png" alt=3D"" />/DIV

So it appears the issue is how to successfully invoke ListMonk's REST API when using a proxy.

**Comment by knadh** [comment]
Closing this issue for https://github.com/knadh/listmonk/issues/684 which indicates that this is a misconfiguration. You can follow any standard Caddy tutorial to setup a reverse proxy for your domain name with automatic TLS/SSL (otherwise, your `https` link will be broken).
