### ISSUE TITLE
How Do I Use ListMonk with a Reverse Proxy?

### ISSUE THREAD

**Issue by PackMeister** [knadh/listmonk#684]
Are there any examples or documentation on how to use ListMonk with Apache, Nginx or Caddy serving as a reverse proxy?

I'm able to successfully access my ListMonk console with Caddy and can send email campaigns that include the 1px subscriber tracking image.  See below....

DIV class=3D"gutter" style=3D"padding: 30px;">&nbsp;<img src=3D"https:=
//listmonk.14servers.net:9000/campaign/e965bffa-6252-4183-be53-3d8b5681e911=
/c2b40353-dd60-48c4-bdac-a671141a53ac/px.png" alt=3D"" />/DIV

However, whenever I open and view the test emails, the opens/views are never detected and registered by ListMonk.

My suspicion is the rest API at listmonk.14servers.net:9000/campaign/............   above is not being accessed properly because of the reverse proxy configuration.

If I can obtain examples from any other successful/working implementation of ListMonk with a reverse proxy, I'm pretty sure I can figure out how to translate it to an equivalent Caddyfile configuration.

**Comment by knadh** [comment]
Sample Nginx config. There's nothing specific to listmonk, just a standard one-line proxy config.

```nginx
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name demo.listmonk.app;

        location / {
                proxy_pass http://127.0.0.1:9000;
        }
}
```

You should not be exposing port `9000` to the outside world. The reverse proxy should put listmonk behind port 80 (ideally 443 for SSL) and in settings, your URL would be `https://listmonk.14servers.net`. Your example shows `https://` on port `9000`, which likely is a misconfiguration.

**Comment by PackMeister** [comment]
Kailash,

The caddy config for reverse proxy is correct and does not expose port 9000 publicly but only on localhost.  And Caddy automatically does redirects from port 80 to 443 which is one of its many benefits.

I've confirmed this by successfully ping-ing listmonk.14servers.net which fails when listmonk.14servers.net:9000 is similarly ping-ed.  Nor can port 9000 be accessed publicly via the server's IP address.

Does the example nginx config below imply the listmonk executable has been installed in the root directory?
If not, does that imply the nginx example would work regardless of where the listmonk executable was installed and that listmonk's location needn't be explicitly called out in the nginx file?

**Comment by knadh** [comment]
```
DIV class=3D"gutter" style=3D"padding: 30px;"> <img src=3D"https:=
//listmonk.14servers.net:9000/campaign/e965bffa-6252-4183-be53-3d8b5681e911=
/c2b40353-dd60-48c4-bdac-a671141a53ac/px.png" alt=3D"" />/DIV
```
The URL in your HTML shows `:9000`, which means the URL is configured incorrectly in `Settings -> General`. It should just be `https://listmonk.14servers.net` (without :9000), as that's what's exposed to the public.

Navigating to https://listmonk.14servers.net, I can see that the logo is also broken because of the incorrect URL.

Where the listmonk binary is running doesn't matter. It looks like the culprit here is the wrong URL in `Settings -> General`

**Comment by MaximilianKohler** [comment]
There's https://yasoob.me/posts/setting-up-listmonk-opensource-newsletter-mailing/#setting-up-ssl, but I'm trying to figure out why [mine didn't auto-renew](https://github.com/wmnnd/nginx-certbot/issues/9#issuecomment-1435820032). 

Maybe I'll have to figure out how to switch to Caddy.

**Comment by skolari93** [comment]
I have CORS errors usint this nginx .conf file templates. Don't know how to solve this.
