### ISSUE TITLE
Multi-language campaigns

### ISSUE THREAD

**Issue by mkrajewski90** [knadh/listmonk#685]
Hey,

I use a commercial solution but I'd like to switch to listmonk due to growing mailing list and more control, plus I like this solution. The only problem is that we have users on different languages and they should receive emails with their local content (especially footers)

The solution might be pretty easy - just add a language parameter on the campaign and render related content in the language (ex. footer).

PS: Sorry, I'd like to help but I don't code in Go and can't help :(

**Comment by knadh** [comment]
If you have the a subscriber's language set in their attributes, eg: `{"lang": "english"}`, then in your template, you can have something like this.

```go
{{ if .Subscriber.Attribs.lang eq "english" }}
	English string!
{{ else if .Subscriber.Attribs.lang eq "spanish" }}
	Espanol string!
{{ else }}
	Default string!
{{ end }}
```

**Comment by mkrajewski90** [comment]
Thanks @knadh for the answer.

The problem is that I as a technical person can do this in your way, but the tool will be moved to nontechnical people, who shouldn't write the code inside template (or do as less as possible), that's why I feel the language select is a better way here.

Anyway, I consider temporary your solution 👍

**Comment by knadh** [comment]
@mkrajewski90 is it feasible to create different templates for different languages in `Campaign -> Templates`? You can then choose the appropriate template when creating a campaign, assuming that a campaign is targeted at one language.

**Comment by mkrajewski90** [comment]
> `lates`? You can then choose the appropriate template when creating a campaign, assuming that a campaign is targeted at one language.

Yeah, That's sound good 👍 I focused for non-technical users, who prefer to select a campaign language so that's why I've written here. So if this way is not how you feel, that's ok, the template solution looks really good and we can close the ticket 👍
