### ISSUE TITLE
Can Analytics Show Which Subscribers Have Viewed or Unsubscribed a Specific Campaign

### ISSUE THREAD

**Issue by PackMeister** [knadh/listmonk#686]
Finally sent out my first campaign using a responsive email created with [MJML](https://mjml.io/try-it-live) to small list of 100 subscribers.

Within 30 minutes I saw approximately 25 subscribers had opened their emails, but I wasn't able to see which ones.

Is it possible from within the Analytics dashboard to see individual subscriber responses rather than just aggregate responses to a particular campaign?

**Comment by knadh** [comment]
This information is recorded in the DB (`campaign_views` template) but isn't available on the UI right now as there isn't an easy way to present this. A campaign could be viewed by millions of users.

**Comment by yash-git-dev** [comment]
I tried to access the campaign_views table but found blank data under subscriber_id column, on looking up the schema.sql found out that it was getting set by the register-campaign-view, but again unable to see the view under public profile. @knadh sir, any way to check out the subscriber id in both campaign_views and link_clicks table?

**Comment by knadh** [comment]
Settings -> Privacy -> Track individual users. It's turned off by default. If you enable it, the subscriber ID is recorded.
