### ISSUE TITLE
FeedBack Loop (FBL)

### ISSUE THREAD

**Issue by bytestore** [knadh/listmonk#687]
How can I put a FeedBack Loop (FBL) in the header of an email?

The header is automatically generated
Format of the header

Feedback-ID: a:b:c:SenderId

Feedback-ID: is the name of the header to be added.

a, b, c: - optional fields with which sender can set up to 3 identifiers (for example with a campaign or client name).

SenderId - mandatory unique identifier chosen by the sender (5-15 characters). It must be the same in all emails.

This is used by Google to track newsletters
https://support.google.com/mail/answer/6254652

**Comment by knadh** [comment]
For now, you can add any custom headers in the SMTP settings.

The ability to add custom headers per campaign was merged recently (https://github.com/knadh/listmonk/commit/583dab4bc6ed94b718461c54f65ce59e76bb0c76) and will be available in the upcoming release.
