### ISSUE TITLE
The difference in quantity between recipients in the company, and sent mail

### ISSUE THREAD

**Issue by pomazanbohdan** [knadh/listmonk#69]
Hi.
I create Campain and add list 2076 subscrubes
![image](https://user-images.githubusercontent.com/696713/76511073-43c4e480-645b-11ea-8fc5-d8d221e64737.png)
But server send only  973
![image](https://user-images.githubusercontent.com/696713/76518348-9b694d00-6467-11ea-984a-ed7299b5811a.png)

![image](https://user-images.githubusercontent.com/696713/76518431-c2c01a00-6467-11ea-94fa-1c141884b05e.png)

**Comment by knadh** [comment]
`Invalid connections 413 ` in your screenshot. Can you dig into that? Are these listmonk SMTP connection attempts that failed?

Also, did the listmonk's error log show failed mails?

**Comment by pomazanbohdan** [comment]
> `Invalid connections 413 ` in your screenshot. Can you dig into that? Are these listmonk SMTP connection attempts that failed?

I think this is the number of “letters” that the mail server could not deliver.
But still a significant part was lost.



> Also, did the listmonk's error log show failed mails?
I run the service in docker, only this is available in the logs

```
2020/03/12 10:01:33 manager.go:268: error sending message in campaign Форматори: timed out,
2020/03/12 10:01:36 manager.go:268: error sending message in campaign Форматори: timed out
```

**Comment by pomazanbohdan** [comment]
During distribution, the server was not critically loaded.

![image](https://user-images.githubusercontent.com/696713/76626626-2dde1f00-6542-11ea-8255-278d7f39f2c8.png)

**Comment by pomazanbohdan** [comment]
I think that listmonk goes very aggressively into an error when it is impossible to reach the mail server.
It is necessary to increase the default timeout and possibly make a progressive increase in the time between letters in the presence of a long response from the server.

**Comment by knadh** [comment]
@pomazanbohdan so many timeouts is an an anomaly still. We push out millions of e-mails in a single campaign with zero timeouts (listmonk instance and SMTP instance on the same AWS VPC).

The [SMTP pooling library](github.com/jordan-wright/email) listmonk uses is fast, but basic. It doesn't have retry/reconnect mechanisms. It is on my to-do to try and fix that lib or write a new one. I'll try and work on it this weekend.

**Comment by pomazanbohdan** [comment]
The SMTP server stack I use has many components (https://poste.io/), and it turned out that in my case, it utilized all available resources.
Perhaps if you use a lighter, then there will be no such problem.
But I think that this should be taken into account, because I used a rather powerful VPS.

**Comment by knadh** [comment]
Yeah. listmonk by design will try and push out as many messages as possible. You can reduce this throughput by tweaking the `concurrency` in the config file for now to slow down the push.

**Comment by pomazanbohdan** [comment]
I change concurrency = 10 and my server sent all mail )

**Comment by pomazanbohdan** [comment]
Only 7 error.

**Comment by knadh** [comment]
Nice. It seems like there may be a need to build more fine grained controls to the control the throughput. I've added this to my to-do.

**Comment by bumi** [comment]
just a quick note: same here; we have limited throughput capability and would like to spread sending a campaign over a certain period. 
So far I try to configure that with the concurrency option, but having more control there would be amazing.

**Comment by knadh** [comment]
@bumi Working on this. Will have a solution soon.

**Comment by bumi** [comment]
you're amazing! listmonk is amazing! :) 
let me know if I can be of any help. and I am happy to test.

**Comment by knadh** [comment]
That was simple enough to implement. [v0.5.2-alpha](https://github.com/knadh/listmonk/releases/tag/v0.5.2-alpha) implements a new `message_rate` parameter to control the max message pushed out per second per concurrent worker.

**Comment by pomazanbohdan** [comment]
> That was simple enough to implement. [v0.5.2-alpha](https://github.com/knadh/listmonk/releases/tag/v0.5.2-alpha) implements a new `message_rate` parameter to control the max message pushed out per second per concurrent worker.

What is the default value?

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/blob/master/config.toml.sample#L33
