### ISSUE TITLE
Upcoming release this week: v2.1.0

### ISSUE THREAD

**Issue by knadh** [knadh/listmonk#691]
This release has been delayed by a month as I tried to squeeze in a couple of things, mainly a transactional mailing API. listmonk has the core + scaffolding and all the right pieces to have a simple transactional mailing feature. However, handling templates optimally turned out to be trickier than I thought. Will try to work it out in the next release. I shouldn't have delayed a release for just one big experimental feature. Some more discussion on the release process here: https://github.com/knadh/listmonk/issues/675

The current `master` now has over a hundred commits with a number of small improvements. An RC is live in our production environment at work (which sends out millions of e-mails weekly) and it's under observation. I always do this before every release as a stress test. This big fix https://github.com/knadh/listmonk/commit/1b163d18957f527d4a468ccfd403fd16f26e9ec0 came out of this.

There's a nice PR from @mrhydejc https://github.com/knadh/listmonk/pull/689 which is pending, but that'll only be available in the next release. It's big and needs to be tested thoroughly (and tweaked a little bit).

All that said, v2.1.0 looks good to be released in the coming week, after a few more rounds of testing. So, February 12th.

**Comment by knadh** [comment]
Commits since v2.0.0

1. knadh@93366f4 Remember last chosen tab on the settings UI.
1. knadh@0f6a037 Add accurate realtime message rate counter.
1. knadh@1b163d1 Fix next-subscribers batch query for a ~210x speedup.
1. knadh@02eaa66 Fix lists test to accommodate new UI yes/no campaign prompts.
1. knadh@8fb459d Fix custom DB type scan failing when nil.
1. knadh@48ef3dc Support `status` in bulk subscriber list update API. Closes #604.
1. knadh@251c1ea Fix campaign start throwing error when disabling schedule on the UI.
1. knadh@da30d46 Add subscriber status counts to the lists UI.
1. knadh@182795e Refactor table stats field set styles.
1. knadh@1b017c0 Merge branch 'master' of github.com:1. knadh/listmonk
1. knadh@2614b07 Refactor campaign analytics to show unique / non-unique data.
1. knadh@1c37732 Merge pull request #683 from sanketsaurav/master
1. knadh@0d88bd8 Fix spelling for "compatible"
1. knadh@d0b32b9 Allow unsubscribed users to re-subscribe. Closes #588
1. knadh@d2cf6e0 Fix `TrackLink` template code to accept Go template variables. Closes #667.
1. knadh@9551f54 Merge branch 'master' of github.com:1. knadh/listmonk
1. knadh@636db20 Fix editor HTML beautification in incorrectly adding breaks to links.
1. knadh@f46ab23 Merge pull request #679 from marcinkunert/patch-3
1. knadh@3b1614b Added end of line config for git
1. knadh@6a5ed43 Change Heroku button repo.
1. knadh@5c2005d Merge pull request #668 from avanier/upkeep/spiffy-up-docker-dev-stack
1. knadh@c7c04c5 Provide a default configuration file for containerized development
1. knadh@5a6b338 Use --idempotent and --yes flags when bootstrapping the dev db
1. knadh@4ecd044 Spiffy up the continerized dev README
1. knadh@64d2c5a Add support for custom public S3 URLs. Closes #505.
1. knadh@7955a4f Fix media upload S3 IAM init blocking outside non-AWS environments.
1. knadh@4ddd3e8 Add 'View in browser' link to the default email template. Closes #540.
1. knadh@c6d5d86 Warn of unsaved changes on the campaign editor on navigation. Closes #551.
1. knadh@4c09cc1 Auto-focus TinyMCE editor area on load.
1. knadh@3f02609 Add unsubscribe link to opt-in confirmation e-mail. Closes #573.
1. knadh@28efe27 Merge branch 'master' of github.com:1. knadh/listmonk
1. knadh@04ea18c Refactor opt-in confirmation behaviour in subscriber update API.
1. knadh@740373d Merge pull request #664 from nikochiko/spaces-in-filenames
1. knadh@be1d048 Replace whitespace with dash in names of uploaded files
1. knadh@c95427e Merge branch 'master' of github.com:1. knadh/listmonk
1. knadh@a2458cf Merge pull request #663 from 1. knadh/dependabot/npm_and_yarn/frontend/follow-redirects-1.14.7
1. knadh@a314eb5 Bump follow-redirects from 1.13.1 to 1.14.7 in /frontend
1. knadh@e62dc24 Re-order SMTP auth protocols in the settings UI by popularity.
1. knadh@2f56057 Close burger 'menu' when clicking items in mobile view.
1. knadh@b0787f7 Merge pull request #649 from joeirimpan/fix/msgr-persist
1. knadh@4c48c32 fix(frontend): Persist messenger selection
1. knadh@e200ab0 Add support for additional POP3 mail charsets. Closes #644.
1. knadh@f266f55 Tidy go.mod
1. knadh@e1d3dd4 Merge branch 'master' of github.com:1. knadh/listmonk
1. knadh@d8ed404 Make `tls_enabled` key migratin idempotent.
1. knadh@583dab4 Add support for per-campaign custom headers.
1. knadh@9e9ea0e Refactor automatic camel casing of API response fields.
1. knadh@d42c676 Merge pull request #646 from ldidry/add-autoheadingid-option-to-markdown-parser
1. knadh@73e6668 Add AutoHeadingID option to Markdown parser
1. knadh@dd061f5 Add support for direct SSL/TLS (non-STARTTLS) SMTP connections.
1. knadh@e46a5cd Merge pull request #640 from rhnvrm/feat-s3-put
1. knadh@c003aec feat: switch from s3 POST to s3 put
1. knadh@d523d0a Merge pull request #639 from mr-karan/tz
1. knadh@e4d8286 feat: Add timezone config in app container
1. knadh@b48a15c Fix incorrect 'nice date' formatting. Closes #635.
1. knadh@e982e6b Don't warn on format change when campaign content is empty. Closes #634.
1. knadh@c1c2b67 Add a link to more language packs to the language settings UI.
1. knadh@fabe06e Add support for custom CSS/JS in settings for admin and public pages.
1. knadh@920645f Fix typo in Makefile.
1. knadh@13edf42 Merge pull request #625 from mr-karan/master
1. knadh@c9189a1 fix(install-prod.sh): Make `tr` work with macOS
1. knadh@ca128df Add support for searching lists + search UI. Closes #618.
1. knadh@e9709e5 Upgrade `labstack/echo` webserver to major version v4.
1. knadh@02c1408 Fix broken Cypress UI tests.
1. knadh@4cb5eb7 Fix settings form input validation.
1. knadh@e9dded7 Merge pull request #608 from mr-karan/dev_docker
1. knadh@e977b90 feat: Add dev docker setup
1. knadh@e6c1f1e Merge pull request #605 from Jjagg/i18n-nl
1. knadh@1c8ab5c Add dutch (nl) translation
1. knadh@3386de4 Fix GET `/subscribers` calls not accepting multiple `list_id`s.
1. knadh@d32c11a Merge pull request #603 from NicoHood/patch-2
1. knadh@8a70595 Fix #601 german translation
1. knadh@575d007 Fix alert email urls (#595)
1. knadh@903330b Create hu.json (#591)
1. knadh@a7fa97a Add scanning of full bounce email body for bounce headers. Closes #492.
1. knadh@c8c135e Fix broken test mail due to missing tpl param.
1. knadh@35ac1cc Embed Inter font files and remove Google font links. Closes #547.
1. knadh@46f13bf Fix broken logout link in desktop nav view (#580)
1. knadh@2388a05 Update fr.json (#581)
1. knadh@7b9ba2e improved mobile navbar/sidebar (#574)
1. knadh@125d51f Merge pull request #576 from MickGe/patch-1
1. knadh@a2c885b Add a note on Postgres min version.
1. knadh@ebf6af2 Clear placeholder on focus
1. knadh@19e0ea5 Fix scheduling params being ignored on the create campaign UI. Fixes #516.
1. knadh@0bd13fe Fix response content type in plaintext campaign previews. Closes #568
1. knadh@d00a1a1 Merge branch 'master' of github.com:1. knadh/listmonk
1. knadh@738c8e9 Merge pull request #569 from ChrisTG742/patch-2
1. knadh@34915f1 Merge pull request #570 from jorge-vitrubio/patch-1
1. knadh@58bd242 Updated es.json
1. knadh@bfefb0f German translation needed for #526
1. knadh@88d0c77 Merge pull request #567 from 1. knadh/dependabot/npm_and_yarn/frontend/tinymce-5.10.0
1. knadh@2819ca8 Bump tinymce from 5.9.2 to 5.10.0 in /frontend
1. knadh@1ece738 Fix incorrect container width on public page responsive view.
1. knadh@5bfbe15 Fix campaign template preview not working without saving. Closes #553.
1. knadh@644f98f Fix typo
1. knadh@ef4de09 Add contribution and participation guidelines and code of conduct.
1. knadh@1054c01 Hide 'Back' button when it is superfluous on public pages.
1. knadh@1101039 Add "passive" mode with `--passive` flag.
1. knadh@9dd8592 Prevent images from being squished in the default e-mail template. Closes #548.
1. knadh@f39ee4e Fix TinyMce campaign editor toolbar to the top on scroll. Closes #549.
1. knadh@b290d27 Add support for plaintext system e-mail templates.
1. knadh@1c8ac0f Add 'preconfirm subscription' option to subscriber UI. Closes #526.
1. knadh@76cd4d3 Merge branch 'master' of github.com:1. knadh/listmonk
1. knadh@ed8d68b Add anti-bot nonce field to generated forms. Closes #541.
1. knadh@151b86a Merge pull request #538 from NicoHood/patch-1
1. knadh@fb3da6b Add german back button translation
1. knadh@b163b13 Add a "Back" button the public subscription/message page.
1. knadh@bc9252f Autogenerate subscriber name from e-mail on the UI if it's empty. Closes #525.
1. knadh@0f896c1 Fix email field in generated form HTML. Closes #529.
1. knadh@ca51c48 Fix duplicate class attr in optin e-mail. Closes #524.
1. knadh@f91b27d Merge pull request #518 from mr-karan/script_fix
1. knadh@6cd7d66 fix: Add a check for existing docker db volume
1. knadh@3064844 Merge branch 'master' of github.com:1. knadh/listmonk
1. knadh@a017597 Fix strings on the UI missed in i18n translation. Closes #506.
1. knadh@469f392 Merge pull request #507 from marcinkunert/patch-2
1. knadh@d6703f2 Updated polish translations
1. knadh@823f11e Remove redundant GitHub issue template.
1. knadh@b46ab6d Fallback to default S3 URL on empty media upload URL in settings.
1. knadh@d91d6e5 Merge branch 'go-deps'
1. knadh@6053b09 Merge branch 'master' of github.com:1. knadh/listmonk
1. knadh@7aa8508 Add explicit `public-read` ACL to public S3 uploads. Closes #496.
1. knadh@4ec4a1b Merge pull request #494 from marcofucito/master
1. knadh@7015c04 Italian translation
1. knadh@443ba18 Merge pull request #491 from citrus-it/makedep
1. knadh@ecc3516 pack-bin is missing dependency on build-frontend
1. knadh@0d8c036 Merge pull request #490 from citrus-it/touch
1. knadh@ac69f6c Use POSIX standard -c flag for "touch"
1. knadh@d0f1a27 Update Go deps.
1. knadh@b45baaa Merge pull request #485 from tachyons/patch-1
1. knadh@30dbe88 Fix typo

**Comment by danilobuerger** [comment]
Hi @knadh thanks for all your hard work. Just to clarify: Is transactional emails coming in 2.1.0?

**Comment by knadh** [comment]
Thanks @danilobuerger. Unfortunately, not in 2.1.0, but the version after.

**Comment by danilobuerger** [comment]
@knadh Awesome, thanks! I am so excited for transactional emails in listmonk 😅

**Comment by knadh** [comment]
v2.1.0 is released: https://github.com/knadh/listmonk/releases/tag/v2.1.0
