### ISSUE TITLE
Login form page ?

### ISSUE THREAD

**Issue by vocuzi** [knadh/listmonk#695]
Any plans on adding a login form page instead of the browser HTTP auth ?

If that's not possible in near future, I would love to have any pointers on how I can start with a login page myself. Any help is appreciated.

**Comment by knadh** [comment]
Yep, a proper non-BasicAuth multi-user system is on the roadmap. This is being tracked here: https://github.com/knadh/listmonk/issues/543

**Comment by vocuzi** [comment]
Can you help me with any pointers on a custom makeshift login page till the non-basicauth system is rolled out ?

**Comment by knadh** [comment]
Without context on how and where you want to achieve this, as a part of listmonk or an external page, it's difficult to answer. If it's to setup an external page, listmonk uses HTTP BasicAuth so Googling something along the lines of `html form for basicauth` should come up with useful answers.

A standalone static HTML page that does this should work.

HTML form -> `onSubmit()`, make a `fetch()` call to `/admin/dashboard` with the `Authorization` headers constructed with the username and password from the form, browser caches the auth from that point on, redirect to `/admin/dashboard`.
