### ISSUE TITLE
Api handlers not working 

### ISSUE THREAD

**Issue by Quadrisheriff** [knadh/listmonk#70]
Hi, i need you to check out the following handlers :

- **PUT("/api/subscribers/:id", handleUpdateSubscriber)** :- This handler only returns the api not update/modify it 

- **PUT("/api/subscribers/blacklist", handleBlacklistSubscribers)** - I keep getting the 404 not found error whenever i try to blacklist more than 1 subscribers with this endpoint. 
![Screen Shot 2020-03-22 at 2 33 31 PM](https://user-images.githubusercontent.com/59125401/77250743-358c7a80-6c4a-11ea-9d8f-bdde1c95aaba.png)

- 	e.**PUT("/api/subscribers/lists/:id", handleManageSubscriberLists)**
	e.**PUT("/api/subscribers/lists", handleManageSubscriberLists)**
:- i don't get how to use this two endpoints

**Comment by knadh** [comment]
Unsure how you're sending the requests, but to see these in action, try managing the lists on the dashboard and inspect the requests in your browser's network console.

`handleBlacklistSubscribers` is used when you search for subscribers and select multiple subscribers to bulk-blaklist.

`handleManageSubscriberLists` is used similarly, for bulk-assigning lists on the subscriber query view.
