### ISSUE TITLE
Invitations sent on Import with Custom Message

### ISSUE THREAD

**Issue by sumdog** [knadh/listmonk#702]
In my testing, it seems like when you use the import feature to add users to a mailing list and add them unconfirmed, Listmonk doesn't give you the option to send out a confirmation e-mail.

One use case for Listmonk is for sending out invites to potential contacts, with a custom message, allowing them to confirm the invite and be opted into a mailing list. Is this possible with the current (2.1.0) version of Listmonk and I'm just not looking in the correct sections? or would this be an entirely new feature? Also, what is the point of importing "unconfirmed" e-mail addresses if confirmation e-mails are not sent out?

**Comment by knadh** [comment]
Once the subscribers are imported to a list, you can create an opt-in campaign from the lists page.

![image](https://user-images.githubusercontent.com/547147/154284797-e152a23c-f09c-4aa1-a955-aabcd40be9c7.png)
