### ISSUE TITLE
Set app.root_url from TOML or env var

### ISSUE THREAD

**Issue by m3nu** [knadh/listmonk#705]
**Is your feature request related to a problem? Please describe.**
Just set up Listmonk for use with [PikaPods.com](https://www.pikapods.com). Works all well thus far. I just noticed that it's not possible to set `app.root_url` and `app.logo_url` (defined [here](https://github.com/knadh/listmonk/blob/master/cmd/settings.go) during initial setup. It just defaults to `localhost:9000`. As a result the logo won't load and the user needs to visit the *Settings* page to update the URL.

**Describe the solution you'd like**
It would be helpful to set at least `app.root_url` in the TOML file during initial setup or use a value from there during initial setup. Editing the URL in *Settings* is helpful too, so I see why it's not in the TOML.

Alternative I've considered is to run a DB query to update this setting after running `--install`.

**Comment by knadh** [comment]
Setting `LISTMONK_APP__ROOT_URL` should work. However, this will always override the value set in the UI creating an ambiguous UX.

**Comment by knadh** [comment]
Ah yes, sorry, my bad. DB settings override environment variables for precisely the same reason. If env vars took precedence, then whatever is configured on the settings UI would be moot, rendering settings unreliable wholly.

**Comment by m3nu** [comment]
Thanks for checking. I'll manage `app.root_url` from the database then and remove `app.logo_url` initially, so it falls back to the default (and doesn't cause a broken image) and users can set their own if they like. I think the latter point could be a good general improvement. In detail:

Set the optional setting `app.logo_url` to an empty value initially so it doesn't cause a broken image on the login page when the URL isn't correct. This would be in line with `app.favicon_url`, which is already set to `""` after installation.

Happy to do a PR if this is a desired change.

**Comment by knadh** [comment]
+1. Makes sense.
