### ISSUE TITLE
Use of S3 storage not possible

### ISSUE THREAD

**Issue by cyrano007** [knadh/listmonk#706]
**Version:**
 - listmonk: v2.0.0 (05585b7 2021-09-27T17:59:39Z)
 - OS: Ubuntu 

**Description of the bug and steps to reproduce:**
When the S3 is configured as storage and I try to upload images, I always get the following error.

`2022/02/15 15:54:07error uploading file: status code: 501 Not Implemented: "<Error><Code>NotImplemented</Code><Message>The requested functionality is not implemented.</Message><RequestId>0af901a7:17de36995cc:7dd61:4e2f</RequestId></Error>"`

S3 works and with an S3 browser data can be uploaded and downloaded 

**Screenshots:**

**Comment by m3nu** [comment]
v2.0.0 isn't the latest released version. Usually better to confirm your bugs affect the current version before filing an issue.

That being said, I couldn't reproduce this bug report in the current version using the `eu-central-1` region.

**Comment by knadh** [comment]
Unable to reproduce this. Maybe something to do with bucket permissions/policy? @rhnvrm have you encountered this error before?

**Comment by rhnvrm** [comment]
This could be related to #640 #617; @cyrano007 are you using S3 or some other API compatible service? Also as m3nu suggested, maybe you can try v2.1.0.

**Comment by cyrano007** [comment]
version 2.1 is running. sorry my mistake
