### ISSUE TITLE
Error sending test - broken pipe

### ISSUE THREAD

**Issue by matthewfurr** [knadh/listmonk#71]
I get the following error when trying to send a test email. I haven't been able to find anything in the documentation.

Error sending test: write tcp 172.19.0.5:57172->xx.xxx.xxx.xx:587: write: broken pipe

**Comment by knadh** [comment]
Looks like an issue with SMTP/network connectivity. Does telnet to your SMTP server from where your listmonk instance is, work?

**Comment by matthewfurr** [comment]
Yes, the lists consist of 35 people, but 4 addresses are were not sent. I tried sending test emails to the individuals who did not receive the actual campaign. Listmonk did say that all emails on the list were sent, but those 4 did not show up in mailgun. Thoughts?

**Comment by knadh** [comment]
> I tried sending test emails to the individuals who did not receive the actual campaign

Using the test on the campaign pages? Did these go through?

**Comment by matthewfurr** [comment]
Hi @knadh! Thanks for following up.

That is correct! Using docker logs, I can see the emails that didn't go through:

```
2020/03/23 02:25:59 manager.go:243: error sending message in campaign NAME: write tcp 172.19.0.5:48048->xx.xxx.xxx.xx:587: write: broken pipe
2020/03/23 02:25:59 manager.go:243: error sending message in campaign NAME: write tcp 172.19.0.5:48060->xx.xxx.xxx.xx:587: write: broken pipe
2020/03/23 02:25:59 manager.go:243: error sending message in campaign NAME: write tcp 172.19.0.5:48050->xx.xxx.xxx.xx:587: write: broken pipe
```

Then using Mailgun's logs I determined who did not get an email. So I tried using the test email tool in the campaign to send it individually. However, I get the same error when trying to send it via the test tool. See screenshot below:

<img width="456" alt="Screen Shot 2020-03-23 at 9 40 04 AM" src="https://user-images.githubusercontent.com/5639047/77322605-5ad0c580-6cea-11ea-8b7e-5c28c23dd46d.png">

**Comment by knadh** [comment]
This is interesting. It looks like for these specific e-mail IDs, the SMTP server is dropping the connection. Is some sort of spam/blacklist protection being triggered? Would you be able to check your SMTP logs?

**Comment by Arsur** [comment]
Hi
i have also this broken pipe error. But it effects all subscribers. Not even one mail is send out. In previous tests it worked but when running the campain a bit later it doesnt.

**Comment by knadh** [comment]
@Arsur `broken pipe` happens when the TCP connection between listmonk (Go's SMTP lib) and the SMTP host is dropped. Would you be able to check SMTP logs?

**Comment by Arsur** [comment]
I checked the logs. I had a little error in my test. The emails where mostly send out.

Only one mail had a problem, maybe this is cousing the pipeline error ("message": "4.7.650 The mail server [209.61.151.224] has been temporarily rate limited due to IP reputation.")

Iam using mailgun at the moment, is it recommended to setup my own smtp server?

**Comment by knadh** [comment]
> Iam using mailgun at the moment, is it recommended to setup my own smtp server?

That depends on your usecase and volumes. Setting up your own mail server is straight forward, but building and maintaining IP reputation may not be easy. At work, we run our own mail servers to send out updates to our customers (no marketing mails) and it has worked well. We send out tens of millions of e-mails without any hiccups.

If you're hosting on your own, I'd recommend https://postal.atech.media

**Comment by henricazottes** [comment]
Similar to this issue, I had the error:
```
manager.go:292: error sending message 'Confirm subscription': write tcp <MY_IP>:35720-><MAILGUN_IP>:587: write: broken pipe
```
But the email got delivered like 10min after. Using mailgun too.

**Comment by knadh** [comment]
[v0.6.0-alpha](https://github.com/knadh/listmonk/releases/tag/v0.6.0-alpha) solves these issues.
