### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#711]
As we all know, today more than ever before, it is crucial to be able to trust our computing environments. One of the main difficulties that package maintainers of GNU/Linux distributions face, is the difficulty to verify the authenticity and the integrity of the source code. With GPG signatures it is possible for packagers to verify source code releases quickly and easily.

In order to securely package your software I am kindly requesting GPG signatures for the source tarballs. If you are not yet familiar with secure source code signing I suggest using [GPGit](https://github.com/NicoHood/gpgit) which automates the process of secure source code signing and also has a quick start guide on GPG for learning how to use it manually.

Thanks in advance.

**Comment by knadh** [comment]
Thanks. I'll explore this. Is signing every commit necessary? What about PRs? What about older commits? Wouldn't signing only the version tag be sufficient to establish the authenticity of a release?

**Comment by NicoHood** [comment]
The more, the better. Signing the tag and the release tarball ist most important, as this is what packagers use to build a release. Enabling gpg signing is easy, so you can simply sign all the commits anyways, as I do.

[It is as easy as](https://github.com/NicoHood/gpgit#32-enable-commit-signing):
```bash
# For commits
git config --global commit.gpgsign true

# For tags
git tag -s 1.0.0
```

**Comment by knadh** [comment]
Cool. I'm familiar with signing commits, but the question was about commits from contributors that'll be unsigned. Maintainers can sign their commits and merge commits, but when there are a number of unsigned contributor commits, it may not be as useful.

Signing tags + releases is definitely valuable.

**Comment by NicoHood** [comment]
Yes, we cannot enforce it from contributor. I think you can sign the merge commit itself, if you merge via shell. Otherwise it will be signed with the GitHub gpg key. It can't be perfect, but release are most important.

**Comment by knadh** [comment]
Argh! I forgot about this for v2.2.0!

**Comment by NicoHood** [comment]
You can always sign a .tar.gz release asset

**Comment by 1000i100** [comment]
> Argh! I forgot about this for v2.2.0!

How about v3.0.0 ?
