### ISSUE TITLE
Campaign view count seems to display invalid values

### ISSUE THREAD

**Issue by marcinkunert** [knadh/listmonk#712]
**Version:**
 - listmonk: v2.1.0
 - OS: Docker

I've noticed a weird behaviour in displaying campaign view count.

```
select count(*) from campaign_views where campaign_id = 9; -- result: 4955
select count(distinct subscriber_id) from campaign_views where campaign_id = 9; -- result: 2830
```

# With individual subscriber tracking enabled.

I've made sure the option is enabled. I've even disabled and enabled it to be sure.

![image](https://user-images.githubusercontent.com/2963232/154234078-cde458a0-e4ec-49ef-a095-51b086f458f7.png)
Expected 2830, got 4955 (looks like is not counting the distinct value)

![image](https://user-images.githubusercontent.com/2963232/154234164-1e8bad2f-4328-492b-ae78-c67fe996628b.png)

Expected 2830, got 3564. This seems to be the sum of the day values:

```
select EXTRACT(day FROM created_at) as day, count(distinct subscriber_id) from campaign_views
where campaign_id = 9
group by EXTRACT(day FROM created_at);
``` 

returns

day;count
2;2066
3;792
4;242
5;89
6;71
7;78
8;45
9;51
10;28
11;32
12;16
13;22
14;15
15;16
16;1

after summing up the count: 3564

# Without individual subscriber tracking enabled.

![image](https://user-images.githubusercontent.com/2963232/154235213-9feb86c4-98f4-4b53-82ff-fc819ec1c857.png)
![image](https://user-images.githubusercontent.com/2963232/154235175-46ca3b3f-a8cc-4151-babb-f2e42c50f46c.png)

Looks in both list view and detail view.

**Comment by NicoHood** [comment]
@knadh Any comment from your side? This issue is currently keeping me from upgrading to the lastest version.

**Comment by marcinkunert** [comment]
@NicoHood these values are being calculated in runtime and are not persisted, so there is not much risk involved in upgrading

**Comment by knadh** [comment]
I am yet to debug this, but like @marcinkunert said, it's just a read query. Has no effect on how data is stored internally.

**Comment by knadh** [comment]
Ah! https://github.com/knadh/listmonk/blob/3b0c8b3b15f3b0a7b265b6f7b3704a7c37e35d11/queries.sql#L577

The distinct (subscriber_id) applies to each day (`GROUP BY timestamp`), not the entire group of all days. Glaring miss. Have to change the query so that the it only considers the first occurrence of a subscriber_id across all days.

**Comment by NicoHood** [comment]
Will we see a bugfix release for those fixes, or do we have to wait for a new minor release?

**Comment by knadh** [comment]
These will be fixed and merged to `master`. You'll be able to run an `RC` version without waiting for a versioned release.

**Comment by NicoHood** [comment]
I personally would always go for a tagged release. Especially if it is gpg signed ;-) #711

**Comment by knadh** [comment]
RCs can be RC-versioned and GPG signed :)
