### ISSUE TITLE
S3 upload to digitalocean 403  Forbidden

### ISSUE THREAD

**Issue by nickwynja** [knadh/listmonk#715]
**Version:**
 - listmonk: 2.1.0
 - OS: macOS 10.15.7

**Description of the bug and steps to reproduce:**
Uploading S3 assets to digitalocean fails with 403 error:

```
error uploading file: status code: 403 Forbidden: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>AccessDenied</Code><RequestId>tx000000000000028330f0d-00620d9368-2738c28d-nyc3c</RequestId><HostId>2738c28d-nyc3c-nyc3-zg03</HostId></Error>"
```

This happens since https://github.com/knadh/listmonk/pull/640. Reverting to `c.s3.FileUpload(p)` instead of `c.s3.FilePut(p)` fixes this issue.

Happy to open a PR with a change but I'm not very familiar with go convention and syntax. I understand the change to `FilePut` was to support B2  as mentioned in #617. Seems like `FileUpload()` is simples3's suggested function so what about something like this where listmonk tries `FileUpload` but tries to fall back to `FilePut` and then ultimately errors:

```go
// Upload.
if _, err := c.s3.FileUpload(p); err != nil {
    if _, err := c.s3.FilePut(p); err != nil {
        return "", err
    }
}
return name, nil
```

**Screenshots:**

Configuration:

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/1012017/154379317-9772a5f2-e0f4-4147-9e50-943f0f807dbb.png">

**Comment by rhnvrm** [comment]
@nickwynja thanks for reporting. I am not sure about the compatibility for digital ocean spaces and how much it supports S3 API, will have to dig deeper for that. Although, after reading their docs, maybe some ACL needs to be specified?

https://docs.digitalocean.com/products/spaces/resources/s3-sdk-examples/#upload-a-file-to-a-space

Would it be possible to check if supplying a private ACL / Meta (x-amz-meta-my-key) resolves this? [code](https://github.com/knadh/listmonk/blob/64d2c5aeb9a4e96b8b5030d7ff0d2efa9498d1ae/internal/media/providers/s3/s3.go#L71)

![image](https://user-images.githubusercontent.com/952036/154416001-3b7dd8e1-eb9c-4dd3-b01c-fffd39a19ecf.png)

**Comment by nickwynja** [comment]
Thanks, @rhnvrm. Neither adding a Private ALC nor custom metadata change the 403.  I'm continuing to investigate. These are the docs I'm referencing: https://docs.digitalocean.com/reference/api/spaces-api/#upload-an-object-put

`PUT` does seem to be supported while `POST` is a multi-part upload.

I've cloned the simples3 repo and running tests with my digitalocean vars exported. So far I'm getting 403 errors _even though_ the files are uploading. I'll keep digging.

**Comment by nickwynja** [comment]
I'm stuck. This is the output of `go test ./...`:

```
--- FAIL: TestS3_FileUploadPostAndPut (1.05s)
    --- FAIL: TestS3_FileUploadPostAndPut/Upload_test.txt_put (0.02s)
        simples3_test.go:172: S3.FileUpload() error = status code: 403 Forbidden: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>AccessDenied</Code><RequestId>tx00000000000002906edb1-00620e673f-2738c28d-nyc3c</RequestId><HostId>2738c28d-nyc3c-nyc3-zg03</HostId></Error>", wantErr false
        simples3_test.go:180: S3.FileUpload() returned empty response, { map[]}
    --- FAIL: TestS3_FileUploadPostAndPut/Upload_test.txt_with_custom_metadata_post (0.09s)
        simples3_test.go:158: S3.FileUpload() error = status code: 403 Forbidden, wantErr false
        simples3_test.go:162: S3.FileDetails() returned incorrect metadata, got: simples3.DetailsResponse{ContentType:"", ContentLength:"", AcceptRanges:"", Date:"", Etag:"", LastModified:"", Server:"", AmzID2:"", AmzRequestID:"", AmzMeta:map[string]string(nil), ExtraHeaders:map[string]string(nil)}
    --- FAIL: TestS3_FileUploadPostAndPut/Upload_test.txt_with_custom_metadata_put (0.16s)
        simples3_test.go:172: S3.FileUpload() error = status code: 403 Forbidden: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>AccessDenied</Code><RequestId>tx00000000000002909674c-00620e673f-2741fd34-nyc3c</RequestId><HostId>2741fd34-nyc3c-nyc3-zg03</HostId></Error>", wantErr false
        simples3_test.go:180: S3.FileUpload() returned empty response, { map[]}
        simples3_test.go:190: S3.FileUpload() error = status code: 403 Forbidden, wantErr false
        simples3_test.go:194: S3.FileDetails() returned incorrect metadata, got: simples3.DetailsResponse{ContentType:"", ContentLength:"", AcceptRanges:"", Date:"", Etag:"", LastModified:"", Server:"", AmzID2:"", AmzRequestID:"", AmzMeta:map[string]string(nil), ExtraHeaders:map[string]string(nil)}
    --- FAIL: TestS3_FileUploadPostAndPut/Upload_avatar.png_put (0.14s)
        simples3_test.go:172: S3.FileUpload() error = status code: 403 Forbidden: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>AccessDenied</Code><RequestId>tx00000000000002906ee0d-00620e673f-2738c28d-nyc3c</RequestId><HostId>2738c28d-nyc3c-nyc3-zg03</HostId></Error>", wantErr false
        simples3_test.go:180: S3.FileUpload() returned empty response, { map[]}
    --- FAIL: TestS3_FileUploadPostAndPut/Upload_special_filename_txt_put (0.02s)
        simples3_test.go:172: S3.FileUpload() error = status code: 403 Forbidden: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>AccessDenied</Code><RequestId>tx0000000000000290967e6-00620e6740-2741fd34-nyc3c</RequestId><HostId>2741fd34-nyc3c-nyc3-zg03</HostId></Error>", wantErr false
        simples3_test.go:180: S3.FileUpload() returned empty response, { map[]}
--- FAIL: TestS3_FileDownload (0.55s)
    --- FAIL: TestS3_FileDownload/txt (0.02s)
        simples3_test.go:292: S3.FileDownload() error = status code: 403 Forbidden, wantErr false
    --- FAIL: TestS3_FileDownload/png (0.32s)
        simples3_test.go:292: S3.FileDownload() error = status code: 403 Forbidden, wantErr false
    --- FAIL: TestS3_FileDownload/txt-special-filename (0.21s)
        simples3_test.go:292: S3.FileDownload() error = status code: 403 Forbidden, wantErr false
--- FAIL: TestS3_FileDelete (1.03s)
    --- FAIL: TestS3_FileDelete/Delete_test.txt (0.19s)
        simples3_test.go:390: S3.FileDelete() error = status code: 403 Forbidden, wantErr false
    --- FAIL: TestS3_FileDelete/Delete_test_metadata.txt (0.32s)
        simples3_test.go:390: S3.FileDelete() error = status code: 403 Forbidden, wantErr false
    --- FAIL: TestS3_FileDelete/Delete_avatar.png (0.19s)
        simples3_test.go:390: S3.FileDelete() error = status code: 403 Forbidden, wantErr false
    --- FAIL: TestS3_FileDelete/Delete_special_filename_txt (0.34s)
        simples3_test.go:390: S3.FileDelete() error = status code: 403 Forbidden, wantErr false
FAIL
FAIL	github.com/rhnvrm/simples3	5.352s
FAIL
```

**Comment by nickwynja** [comment]
After extensive debugging and chatting a bit with DigitalOcean support, I found the issue. Without `x-amz-date` header, DO seems to reject the PUT request. Just adding `x-amz-date` along with _or_ instead of `Date` makes everything 200. I've filed this with support as nowhere mentions requiring this header but it might also be easy to just add it to all requests.

**Comment by rhnvrm** [comment]
@nickwynja I have opened a PR at https://github.com/rhnvrm/simples3/pull/21

I ran the tests against DigitalOcean spaces, but would it be possible to re-check it with your setup as well. If this works, we can make a new release and bump the version in listmonk :+1:

**Comment by nickwynja** [comment]
@rhnvrm All tests pass with my DO env vars against https://github.com/rhnvrm/simples3/pull/21 👍
