### ISSUE TITLE
List homepages?

### ISSUE THREAD

**Issue by tfillmor924** [knadh/listmonk#716]
Hi -
I want to move off of the Sympa list server, listmonk looks great.  One thing - each list on Sympa has its own homepage, I'm lost trying to find a way to do that using listmonk. Is this even possible?
Thanks
TFillmore

**Comment by marcinkunert** [comment]
What do you mean by homepage? It's a kind of landing site? What functionality does it offer?

**Comment by knadh** [comment]
Maybe the `/subscription/form` page? https://demo.listmonk.app/subscription/form

**Comment by knadh** [comment]
Thanks for explaining this in detail @tfillmor924. Every feature in listmonk has an API, so pretty much any behaviour can be scripted. I suggest you take a look at https://listmonk.app/docs/

listmonk doesn't have any CMS/publishing capabilities that enable you to publish custom webpages though. It is a one-way newsletter system and not really a multi-user mailing list manager like Sympa or Mailman with moderation features. There is no way for an external user to mail something in or for that to go into a moderation queue.

However, if you really wanted to, you could maybe use the campaign API to create a draft campaign via a form that the admin can either delete or publish. Seems like a bit of stretch though.

**Comment by tfillmor924** [comment]
Ah - OK, wow - I missed the one way thing.  That changes everything.  :)

If you ever decide to do a two-way mechanism I'd be happy to act as a soundboard.

Thanks again for the quick response!

Tom Fillmore
southern California

February 17, 2022 6:54:57 PM CET Kailash Nadh ***@***.***> wrote:

Thanks for explaining this in detail @tfillmor924. Every feature in listmonk has an API, so pretty much any behaviour can be scripted. I suggest you take a look at https://listmonk.app/docs/
listmonk doesn't have any CMS/publishing capabilities that enable you to publish custom webpages though. It is a one-way newsletter system and not really a multi-user mailing list manager like Sympa or Mailman with moderation features. There is no way for an external user to mail something in or for that to go into a moderation queue.
However, if you really wanted to, you could maybe use the campaign API to create a draft campaign via a form that the admin can either delete or publish. Seems like a bit of stretch though.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
