### ISSUE TITLE
Deployment does not use environment variables

### ISSUE THREAD

**Issue by cyrano007** [knadh/listmonk#719]
**Version:**
 - listmonk: [2.1]
 - OS: ubuntu

**Description of the bug and steps to reproduce:**
When I specify them in the format LISTMONK_db__password, there is always a message in the log config.toml not found.
I can only get the deployment to run with config.toml. 
I do my deployment on Cloudfoundry with the binary_buildpack

**Screenshots:**

**Comment by tcurdt** [comment]
Glad this is an option. This should really be included in the docker compose example.
