### ISSUE TITLE
Subscriber marked as bounced via SES webhook not reflecting in Campaign Analytics

### ISSUE THREAD

**Issue by HiteshPaliya** [knadh/listmonk#720]
Hello,

I am using Listmonk via AWS SES smtp server and have bounce processing and webhooks enabled. 
I do get postbacks for subscribers for whom the emails have been bounced but the same number is not reflecting in the campaign analytics. I suppose I could query the database and extract the data, but would be better if that task could be achieved without needing to do that.

So am I missing out on something here? Or is it something that is a WIP thing?
(I've been using v2.0.0 and updated to v2.1.0 recently.)

**Comment by knadh** [comment]
hm, nothing to do with bounce stats has changed between v2 and v2.1. Are you saying that this was working fine in v2 but has stopped working in v2.1?

**Comment by HiteshPaliya** [comment]
No, actually it didn't even showed the campaign analytics stats in v2.0 either.

The postbacks were received in the Subscribers -> Bounces section, but count of the same bounces did not reflect in the Campaigns -> Analytics section for the same campaing where the actual email bounce happened.  

I just shared the version info for reference.

**Comment by HiteshPaliya** [comment]
I went through the response from SES postback, and found this (redacted some stuff):
```
{
  "mail": {
    "source": "foo@bar.com",
    "sourceIp": "12.3.4.56",
    "messageId": "redacted-message-id-here",
    "sourceArn": "arn:aws:ses:ap-south-1:123456789012:identity/foo@bar.com",
    "timestamp": "2022-02-11T11:26:54.203Z",
    "destination": [
      "bouncetest01@company.com"
    ],
    "sendingAccountId": "123456789012"
  },
  "bounce": {
    "timestamp": "2022-02-11T11:26:56.000Z",
    "bounceType": "Permanent",
    "feedbackId": "redacted-feedback-id-here",
    "remoteMtaIp": "123.456.78.90",
    "reportingMTA": "dns; a123-45.smtp-out.ap-south-1.amazonses.com",
    "bounceSubType": "General",
    "bouncedRecipients": [
      {
        "action": "failed",
        "status": "5.1.1",
        "emailAddress": "bouncetest01@company.com",
        "diagnosticCode": "smtp; 550-5.1.1 The email account that you tried to reach does not exist. Please try\n550-5.1.1 double-checking the recipient's email address for typos or\n550-5.1.1 unnecessary spaces. Learn more at\n550 5.1.1  https://support.google.com/mail/?p=NoSuchUser h69si3856467pge.445 - gsmtp"
      }
    ]
  },
  "notificationType": "Bounce"
}
```

![Listmonk_bounces](https://user-images.githubusercontent.com/38072083/154919849-f08d0031-37e7-400e-b652-4d186d11d214.jpg)

> Are subscriber and campaign names in the bounce list proper?

I did saw the email of the subscriber but did not see any List there. I assume that is why the analytics for the same is not getting updated under https://demo.listmonk.app/admin/campaigns/analytics

**Comment by knadh** [comment]
Ah yes. `mail.headers` and `mail.headersTruncated` is missing in the SES payload. These headers are supposed to contain subscriber and campaign UUIDs. Maybe the mail server that is bouncing the e-mail is stripping the headers from the original e-mail.

Are all your bounces on the same target domain / server?

**Comment by HiteshPaliya** [comment]
> Are all your bounces on the same target domain / server?

Yes. I am using our company's domain (G-Suite Workspace Account Emails) for testing out bounces/campaigns.

And thank you. I was able to figure out why I was not able to view the Per Campaign Bounce statistics in Listmonk console.
Apparently, there is an option in **Amazon SES** where I had to update the *Feedback notifications* settings to **Yes** in the *Verified Identities* section to **Include Original Headers**.

![Listmonk_Include_headers](https://user-images.githubusercontent.com/38072083/154963023-2bae31f9-ce5e-441e-b30a-f9444cfcebc9.png)

Also I think we can close the issue now!

**Comment by knadh** [comment]
Great!
