### ISSUE TITLE
Alternative to Heroku

### ISSUE THREAD

**Issue by shreyas-satish** [knadh/listmonk#723]
Heroku is [no longer accepting](https://devcenter.heroku.com/changelog-items/2305) Indian credit cards. Our listmonk installation is unusable due to this.

Is it possible to add a starter pack for an alternative service please? ([Railway perhaps?](https://railway.app/))

**Comment by knadh** [comment]
I'm not sure if I'll have the time to explore these services and write buildpacks. If you're up for it, please feel free to contribute and we can publish them in the README and docs.
