### ISSUE TITLE
Sending a test message fails

### ISSUE THREAD

**Issue by samuelT2** [knadh/listmonk#724]
**Version:**
 - listmonk: v2.1.0 (0ecfb89 2022-02-12T15:27:45Z)
 - OS: Ubuntu (Docker image)

**Description of the bug and steps to reproduce:**
- Create new campaign
- Add all necessary fields and content
- Try to send a test message. Error message appears: "No known subscribers to test."
- I upgraded to 2.1.0 because I've seen that this should have been fixed with 2.1.0 - no luck with me. It worked for me earlier.

**Screenshots:**
![error1](https://user-images.githubusercontent.com/10983143/155329155-cdc1f822-0d56-4ce3-a0fd-876c63eef666.png)
![error2](https://user-images.githubusercontent.com/10983143/155329157-b25cad69-41a8-442c-a9d7-5cc8abd39463.png)

**Comment by knadh** [comment]
The e-mail ID you're trying to send test mails to should be of an existing subscriber. You can create a subscriber with the test e-mail ID.

**Comment by samuelT2** [comment]
Holy - it's that simple :) Should have guessed that, thank you very much for your prompt reply.
