### ISSUE TITLE
bounce.go:216: error processing sendgrid notification:

### ISSUE THREAD

**Issue by charlesmudy** [knadh/listmonk#725]
**Version:**
 - listmonk: [eg: v2.1.0]
 - OS: [e.g. Ubuntu]

**Description of the bug and steps to reproduce:**
Bounce isn't working at all using SendGrid, keep getting this error message `bounce.go:216: error processing sendgrid notification: error asn1 unmarshal of signature: asn1: syntax error: sequence truncated`

**Screenshots:**
<img width="641" alt="Screenshot 2022-02-24 at 01 48 48" src="https://user-images.githubusercontent.com/1445007/155435787-4514c0bf-4938-4f58-8d02-45855c8c28b7.png">

**Comment by knadh** [comment]
You have setup [**Signed** webhooks](https://docs.sendgrid.com/for-developers/tracking-events/getting-started-event-webhook-security-features), right? The error looks like there's no signature in the incoming post from Sendgrid.
