### ISSUE TITLE
Install a systemd service file

### ISSUE THREAD

**Issue by heyakyra** [knadh/listmonk#73]
It would be nice to install a `systemd` service file, and the binary as well. This could be done by the interactive install, with the same values needed for the config file.

The executable can be installed, and for systems with proper security under SELinux, the following will allow `systemd` to execute it:
`sudo chcon system_u:object_r:shell_exec_t:s0 /usr/bin/listmonk`

The `/etc/systemd/system/listmonk-[SITE NAME].service` file can contain:

```
[Unit]
Description=Listmonk systemd service for [SITE NAME]
Documentation=https://listmonk.app/docs/

[Service]
Type=simple
WorkingDirectory=[SITE ROOT DIR]
ExecStart=/usr/bin/listmonk
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by knadh** [comment]
I think once listmonk enters beta, it can be packaged for popular package repositories (and can be registered as a service during installation). It wouldn't be appropriate to bundle the service wile within the listmonk bin as not every distro has systemd.

Thanks for documenting this though.

**Comment by heyakyra** [comment]
Sure thing, figured that may be the case but wanted to share the file I used
