### ISSUE TITLE
Is it possible for subscribers to email all other subscribers?

### ISSUE THREAD

**Issue by gitmuir** [knadh/listmonk#732]
I manage a small community, is it possible for all subscribers to email each other? Essentially like a WhatsApp group…but via email.

I would like this to be via a dedicated email address rather than via the UI as not everyone would have a login; for example **everyone@mysubscribers.com** which could ideally get processed server side with an ‘unsubscribe’ link inserted to the bottom of each message?

Grateful for your consideration, or recommendation for similar services which may offer this functionality. Thank you.

**Comment by NicoHood** [comment]
I guess a mailing list is then the better solution for this.

**Comment by knadh** [comment]
Hi @gitmuir, listmonk is a one-way mailing list. What you are asking isn't feasible. More context here https://github.com/knadh/listmonk/issues/716#issuecomment-1043243476.

**Comment by gitmuir** [comment]
Thank you very much @NicoHood / @knadh. Understood 👍
Do you know of any services that may offer that sort of functionality by any chance?

**Comment by knadh** [comment]
Mailman, Dada Mail, Sympa.

**Comment by ManUtopiK** [comment]
> What you are asking isn't feasible. 
What is missing to do it? SMTP listener?

**Comment by knadh** [comment]
> What is missing to do it? SMTP listener?

Many-to-many mailing list functionality like mailman. listmonk is a one-to-many system.
