### ISSUE TITLE
[Feature Request] When Campaign is sent, send Webhook (to Slack or MS Teams)

### ISSUE THREAD

**Issue by cb3inco** [knadh/listmonk#736]
**Is your feature request related to a problem? Please describe.**
This probably isn't a highly requested feature, but we use Listmonk as a 'internal' tool for our staff. We also use MS Teams for communication in our organization. It would be great that when we send certain campaigns that a webhook posts to a MS Teams channel with a web link to the article. 

**Describe the solution you'd like**
On certain campaigns, and option to send a webhook to MS Teams, Slack, Rocket.Chat, etc. and the campaign posted and a link to the web version on the campaign is available to view.

**Comment by knadh** [comment]
Closing this issue as we're tracking it here: https://github.com/knadh/listmonk/issues/658

**Comment by cb3inco** [comment]
@knadh  That isn't exactly what I'm looking for. I want a campaign posted to a MS Team channel as if it was more of a 'blog' update or sharing a website on social media, rather than having updates about user changes. Am I misunderstanding the other issue you referenced?

**Comment by knadh** [comment]
Ah, I misread the request. What you're looking for is already possible with [webhook Messengers](https://listmonk.app/docs/messengers/). You can write a web service that receives a push from listmonk and transmits it to wherever (Slack, MS Teams etc.)

[Here's a Go service](https://github.com/joeirimpan/listmonk-messenger) for reference that receives listmonk campaign messages and pushes to AWS Pinpoint (SMS).
