### ISSUE TITLE
Support for LOGIN authentication

### ISSUE THREAD

**Issue by mdehollander** [knadh/listmonk#74]
Could you add support for LOGIN authentication to send emails?

There is a github gist to add support for LOGIN authentication for the `net/smtp` go library: https://gist.github.com/andelf/5118732

I am not a Go developer, but I guess this code would be added to `emailer.go` as a different authentication protocol: https://github.com/knadh/listmonk/blob/master/internal/messenger/emailer.go#L45

Thanks!

**Comment by mdehollander** [comment]
Login based authentication seems to be a common thing according to the [list of smtp providers at gitlab](https://docs.gitlab.com/omnibus/settings/smtp.html). At least for 41 the default is `login`, but I am not sure if this is the only supported method. In my case it is.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/9dcd716f91262b3709fcbddf25458fe49a442a0a adds support for LOGIN (thanks to the Gist you linked).

Will push a new release shortly.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/releases/tag/v0.5.1-alpha

**Comment by mdehollander** [comment]
Thanks a lot for the quick implementation. I can confirm that with my email server the LOGIN authentication works.
