### ISSUE TITLE
Back button doesn't navigate back to public subscription form

### ISSUE THREAD

**Issue by toontoet** [knadh/listmonk#744]
**Version:**
 - listmonk: 2.1
 - OS: Docker

**Description of the bug and steps to reproduce:**
1) Add a public subscription form on your website
2) Open the Listmonk admin or just open the main listmonk URL
3) Fill in the form on your website & click Subscribe. The page /subscription/form will be shown
4) Click 'Back'. 

You won't be redirected to the page containing the subscription form. In my case I'm redirected to a empty browser tab (Firefox).  

In my case history.length == 3, which causes the back button fire a history.go(-2). history.go(-1) does the job. 

As a work around I added some custom javascript, checing the document.referrer and changing the button event handler.

**Comment by NicoHood** [comment]
For me I remember this worked. So I guess this might be a special case, we have to investigate?

**Comment by knadh** [comment]
Hi @toontoet. I followed the exact steps and am unable to reproduce this.

**Comment by Uzay-G** [comment]
I also have this problem.

**Comment by NicoHood** [comment]
I also noticed, that the back button brought me 2 pages before, the page before the form.

Its like this:
1. Any web page that links to the form
2. Form, embedded on the webpage
3. Listmonk Success message with back button
4. Now jumps back to 1, not to 2

**Comment by NicoHood** [comment]
@knadh can you reopen this?

**Comment by buttle** [comment]
We have noticed that when the subscription is not completed (ie: the subscriber has *not* checked the checkbox), the back button does not return to the subscription form, but instead goes two pages back. It would be more user friendly if it went back to the form.
Thanks!

**Comment by apfatzgo** [comment]
I have the same problem on macOS 16.5, Safari and Firefox.

**Comment by msklywenn** [comment]
I'm having the same issue. 
Listmonk v2.5.1
Firefox on macOS or Windows, Safari on iOS, etc.

**Comment by boredland** [comment]
I guess a nicer solution would be to be able to pass a redirect url to `/subscription/form` where it should lead after successful form submission and that should be used on the "Back" button. This way, developers could decide where they'd want to go when POST'ing from their websites.

**Comment by knadh** [comment]
Without the URL being added to a safe list in the backend, this would lead to an open-direction vulnerability though.

**Comment by boredland** [comment]
> Without the URL being added to a safe list in the backend, this would lead to an open-direction vulnerability though.

While I agree that a configuration option in the backend would be preferable, I don't think this opens a new attack vector. If an attacker already manipulates the target of a form, he could easily replace that target with an address of his liking (with a redirect, data collection etc.). What am I missing?

**Comment by knadh** [comment]
> /subscription/form?redirect=[TARGET_URL]

An attacker doesn't have to compromise the form. They can send unsuspecting users to `https://listmonk.legitsite.com/subscription/form?redirect=$malicious_url`. Legit domain, legit form, legit signup, but malicious redirect after.

**Comment by boredland** [comment]
> > /subscription/form?redirect=[TARGET_URL]
> 
> An attacker doesn't have to compromise the form. They can send unsuspecting users to `https://listmonk.legitsite.com/subscription/form?redirect=$malicious_url`. Legit domain, legit form, legit signup, but malicious redirect after.

Well, sure, no form needed for that. But also: I'd need to first have a user-trusted website to have this link on. In both cases, I don't see why I'd need listmonk at that point.

**Comment by fullpwemium** [comment]
this back button doesn't work for me either, redirects to blank page

**Comment by handkerchief333** [comment]
### Our setup
- `newsletter.example.com` = listmonk URL  
- `example.com` = company website URL  
- embedded subscription form (double-opt-in) on `example.com ` 

### Steps  
1. User is on `example.com` and fills in the email address and clicks on subscribe.  
2. User gets redirected to `newsletter.example.com/subscription/form` with the message "An e-mail has been sent to you to confirm your subscription(s)." and a back button.  
3. The user clicks on the back button and gets redirected to `https://listmonk.app/`  
4. This happens all in the same tab, the user is now far away from the company website AND for god's sake, the browser back button is not working! No back option here, so the user is stranded!  

**Couldn't think of anything worse than maneuvering customers into a dead end away from the website.**  

### Strange side effects  
- The steps above are tested with: Firefox 138.0.1  
- If I test this with Chromium 136.0.7103.59, the back button redirects to the configured start page of the Chromium browser.  
- Same effect as Chromium with the Edge Browser 136.0.3240.64.  

### Question
- Why not simply add the option of specifying a URL for the back button to the relevant list? I've seen this a lot on other newsletter portals. There's no need for complicated queries.
