### ISSUE TITLE
Rate limiting / sliding window not applied to opt-in campaign

### ISSUE THREAD

**Issue by mdehollander** [knadh/listmonk#746]
**Version:**
 - listmonk: 2.1.0
 - OS: Ubuntu 20.04 LTS

**Description of the bug and steps to reproduce:**
For a opt-in campaign not all recipients receive the mail. The number of sent emails in the UI is larger (28) as the number of actual send email in the outbox (13). This is using Outlook365 SMTP with rate limiting setup:

![image](https://user-images.githubusercontent.com/262872/158384767-94312498-e60d-41ea-86ce-f64b22bebc6b.png)

Sending normal campaigns works ok, even with more recipients than in the opt-in campaign.

**Screenshots:**
Error message from the logs:
```
Mar 15 13:56:41 **** listmonk[973287]: 2022/03/15 13:56:41 manager.go:355: error sending message in campaign Opt-in to *****: subscriber *****: 432 4.3.21 Mailbox server busy; mail intentionally delayed  [Hostname=***.***.prod.outlook.com]

**Comment by knadh** [comment]
`Optin campaign` is just a flag in the DB that's used in the frontend to display it in a certain way, and to pick the opt-in template when creating the campaign. Internally, it is a regular campaign and uses the exact same logic as regular campaigns.

Not sure what's happening here. Maybe the content in the e-mail is somehow triggering the rate limit?
