### ISSUE TITLE
listmonk Android/iOS App

### ISSUE THREAD

**Issue by JustLuucy** [knadh/listmonk#748]
**Is your feature request related to a problem? Please describe.**
No. My feature request is not related to a problem or bug.. I wish there would be a mobile app that lets you connect to your listmonk server and then do everything you can do in the admin panel in one app.

**Comment by knadh** [comment]
Hi @JustLuucy. There are no plans to build an alternative frontend for listmonk. Building a full fledged mobile client is going to be a mammoth of a project and is highly unlikely that anyone else will attempt it either. listmonk has a decent responsive UI which is usable on mobile screens. Thanks.
