### ISSUE TITLE
Time-to-time mails not sent

### ISSUE THREAD

**Issue by epluginsprivate** [knadh/listmonk#75]
Hello!

For now we are testing Listmonk app and seems that it is very good solution for us.
But I already noticed important issue:
- Some emails are not being sent, when trying with test send it gives "timeout" or "broken pipeline" and after wew attempts it is sending some. (Hosted in k8s, tested with AWS and SendGrid SMTP servers).
According to same problem, when you launch campaign it says every time that it is finished, but no mails sent and see errors in logs.

Can you help me with that? I think that issue come from `send_timeout` parameter in config.toml file, but changes in this does not give result and nothing changes.

Thank you!

**Comment by knadh** [comment]
Please see this discussion https://github.com/knadh/listmonk/issues/71

This usually happens when a) there's a network issue between listmonk and your SMTP server b) the SMTP server is dropping connections (rate limits? spam checks?)

**Comment by epluginsprivate** [comment]
Thank you for response!

a) I don't think so, because when I tried with AWS SES, deployment and SMTP server were in one env, now it using Sendgrid but same.
b) This is only Sendgrid support visible, but for AWS I wrote to support and they said that it is api issue.

What exactly do `send_timeout` parameter? Because I did changes between 2 seconds and 10 and there was not difference.

**Comment by knadh** [comment]
`send_timeout` depends on your environment. If 2-10 seconds haven't worked with you, the issue is elsewhere.

Are you sure there's proper network connectivity from your instance to the SMTP server? Can you try `telnet smtp-host smtp-post` and see if you get a greeting?

**Comment by epluginsprivate** [comment]
Not possible, because I given with security groups only 587 port for mail sendeng

**Comment by knadh** [comment]
I'm not sure what's happening here. Could be the rate limits. You can try reducing the `concurrency` param to send fewer e-mails.

As far as SMTP sending goes, listmonk uses the `smtp` package from Go's stdlib.

**Comment by pomazanbohdan** [comment]
@epluginsprivate 
https://github.com/knadh/listmonk/issues/69

**Comment by knadh** [comment]
[v0.5.2-alpha](https://github.com/knadh/listmonk/releases/tag/v0.5.2-alpha) implements a new `message_rate` parameter to control the max message pushed out per second per concurrent worker. This should fix the ratelimit issue.

**Comment by knadh** [comment]
[v0.6.0-alpha](https://github.com/knadh/listmonk/releases/tag/v0.6.0-alpha) solves these issues.
