### ISSUE TITLE
Uploading Templates via API

### ISSUE THREAD

**Issue by pentaquarks** [knadh/listmonk#750]
Dear all,

I have some trouble using the API to upload email template files. As far as I know, this isn't described in the doc yet. I already tried similarly to how one uploads media files, i.e.
```console
curl -u "listmonk:listmonk" -X POST 'http://localhost:9000/api/templates' --form 'file=@/home/co/template.html'
```
which yields a server error. On the other hand, if I interpret `templates.go` correctly, it expects "name" and "body", so I tried passing the raw content of the template file, e.g. 
```console
--data '{"name":"asdf", "body":"{{ template "content" . }}"}'
```
which also didn't work (and I have no idea how to escape the quotes and the curly brackets). 

Do you have any idea how I can fix it?

listmonk: 2.1.0
OS: Ubuntu 20.04 LTS

**Comment by knadh** [comment]
You have not escaped the quotes in the the template string. This works:

```shell
curl 'https://localhost:9000/api/templates' -X POST -u "username:password" \
       -H 'Content-Type: application/json;charset=utf-8' \
       --data-raw '{"name":"test","body":"<div>{{ template \\\"content\\\" . }}</div>"}'
```

**Comment by pentaquarks** [comment]
Thanks for the quick answer! I still get 
```console
{"message":"The placeholder {{ template \"content\" . }} should appear exactly once in the template."}
```

**Comment by knadh** [comment]
Yes, you've to pass the raw template string, not a file. The string should have the `{{ template "content" . }}` placeholder.
