### ISSUE TITLE
Campaign stats report with delivered

### ISSUE THREAD

**Issue by charlesmudy** [knadh/listmonk#752]
Hello,

We are using SendGrid SMTP for sending out emails. Listmonk is providing the clicks, views, and sent report but we need to be able to get the `delivered` messages and possibly to each recipients.
<img width="888" alt="Screenshot 2022-03-19 at 11 55 35" src="https://user-images.githubusercontent.com/1445007/159118221-76b20e4e-1e94-421c-991c-77f5ec4549d2.png">

So let's say we send out to 500 subscribers, ideally maybe 450 was delivered (which SendGrid provides) ... then the view and clicks can be more realistic on the sent messages. How can I get the delivered from SendGrid?

Also, what does this mean in the report? `sent: 500/500` ... they are always the same number for me.

Thanks in advance.

**Comment by knadh** [comment]
listmonk doesn't have the ability to reconcile delivery reports from SMTP servers currently. I'll see if it can be added via webhooks for services that support it, like SendGrid.

`500 / 500` indicates that of the 500 e-mails that were to be pushed to an SMTP server, all 500 were. Whether the SMTP delivers them to the target or they bounce, is not captured here.

**Comment by charlesmudy** [comment]
1. That would be great, since there is a webhook for bounce anyways ... just not good would go Lang but I’ll see if I can try as well.
2. Thanks for the clarification
