### ISSUE TITLE
https://listmonk.app/docs/installation/ not working

### ISSUE THREAD

**Issue by pepa65** [knadh/listmonk#754]
**Version:**
 - listmonk: 2.1.0
 - OS: Ubuntu 20.04.4 LTS
 - Postgresql: 12.9-0ubuntu0.20.04.1

**Description of the bug and steps to reproduce:**
Following https://listmonk.app/docs/installation:
```
./listmonk --new-config
./listmonk --install
```
Output:
```
2022/03/21 11:06:01 main.go:92: v2.1.0 (0ecfb89 2022-02-12T15:27:45Z)
2022/03/21 11:06:01 init.go:127: reading config: config.toml
2022/03/21 11:06:01 init.go:244: connecting to db: localhost:5432/listmonk
2022/03/21 11:06:01 init.go:247: error connecting to DB: pq: password authentication failed for user "listmonk"
```
It seems there is a step missing. The same happens for the root user.

**Comment by knadh** [comment]
> ./listmonk --new-config to generate config.toml. **Then, edit the file.**

Did you edit the config file and populate your DB host, username, password?

**Comment by pepa65** [comment]
I edited `config.toml` and it all looked good. So the missing step is to manually populate the DB? Could you give some pointers??

**Comment by knadh** [comment]
Once you've filled the config, running `./listmonk --install` will populate the DB.

**Comment by pepa65** [comment]
After `./listmonk --new-config` a `config.toml` is generated that is adequately filled in. But when I run `./listmonk --install` I get `error connecting to DB: pq: password authentication failed for user "listmonk"` and so the instructions are not working.

**Comment by knadh** [comment]
I think you're referring to the creation of the database, not **population**. You have to create a Postgres database + user using your root account and supply its username and password in the config file and listmonk will connect and **populate** the necessary tables and data for it to function.

listmonk cannot create the database as it requires root permissions to the database server.

**Comment by pepa65** [comment]
I thought as much. It just means the instructions on that page don't work, and are not suitable in their current form for "non-programmers" as intended.

What would be the command(s) to execute as root to accomplish this?

**Comment by knadh** [comment]
Will link a tutorial in the docs that shows how to create a database. There are several tutorials [like this](https://medium.com/coding-blocks/creating-user-database-and-adding-access-on-postgresql-8bfcd2f4a91e).

If your database is with a webhost, there must be a UI to create and manage databases. If you're able to use Docker, then you just have to run the `docker-compose` commands in the docs and database creation is automatically handled.

**Comment by pepa65** [comment]
OK, so this comes before `./listmonk --install`:
```
sudo -u postgres psql  # The current user needs to have sudo privileges
create database listmonk;
create user listmonk with encrypted password 'listmonk';
grant all privileges on database listmonk_db to listmonk;
```
After this, the rest works.

**Comment by pepa65** [comment]
(I already have listmonk running in the "Easy Docker installation", but because I love golang single binaries and how they make docker unnecessary, I wanted to do a "Binary" installation. Now we know how, and topping it off with another single binary Caddy reverse proxy, it is very simple..!)

**Comment by Uzay-G** [comment]
I agree, indicating this could be useful.
