### ISSUE TITLE
List Segments or Attribute Filter in Campaign

### ISSUE THREAD

**Issue by chestnutbak** [knadh/listmonk#755]
**Is your feature request related to a problem? Please describe.**
It is frustrating that there is no solution for only emailing a section of the mailing list based on attributes or other predefined terms.

**Describe the solution you'd like**
I would love to see the ability to create list segments or the ability to filter based on attributes when creating a campaign.

This is literally my only problem with this system, I absolutely love LOVE the rest of it. Coming from Mautic, which has too many features and is not user friendly, ListMonk is a breath of fresh air.

**Comment by knadh** [comment]
Tracking this feature request here https://github.com/knadh/listmonk/issues/250.

As a workaround (for now), you could create a temporary list, search / segment subscribers, add the segmented subscribers to the temporary list and send a campaign on it.

![image](https://user-images.githubusercontent.com/547147/159410736-e2180d9a-9852-4455-8d97-00c059505b50.png)
