### ISSUE TITLE
Support for S/MIME signing of messages

### ISSUE THREAD

**Issue by dieterdanger** [knadh/listmonk#756]
Hello,
first of all thank you for the wonderful tool Listmonk.

We are a public institution from the education sector that would like to use Listmonk to send emails. In this age of phishing emails, we would like to see outgoing emails signed via S/MIME. This would have the advantage that recipients can ensure that the message comes from a trusted sender.

Is such a function already integrated in Listmonk or what are the chances that it will be integrated in the future? I have searched the issue tracker and documentation but haven't found anything that points in this direction.

Best regards

**Comment by knadh** [comment]
Hi @dieterdanger. I hadn't thought of `S/MIME` but will explore it. In the meanwhile, it looks like it may be possible to do it at the SMTP level. Are you self-hosting your SMTP?

**Comment by knadh** [comment]
There doesn't seem to be a straight forward way to achieve this right now. Best bet is to check whether there is an SMTP server or a proxy that supports this. Closing the issue for now.

**Comment by cocoonkid** [comment]
@knadh  found this issue. This would be a really great addition.
zammad has implemented this very well for example.

**Comment by mc17uulm** [comment]
@knadh first off, thanks for creating Listmonk! It’s an amazing tool, and I really appreciate all the work that has gone into it.

I wanted to ask if native S/MIME signing support could be considered. S/MIME is crucial for ensuring email authenticity and preventing tampering or phishing. Relying on SMTP for signing isn’t ideal, as the signature should be applied in Listmonk before sending to guarantee integrity and consistency across different mail servers.

It would be fantastic to have built-in support for S/MIME, allowing users to configure their certificates and keys directly in Listmonk. This would make signed emails more reliable and secure for everyone. Would love to hear your thoughts—do you think this could be a valuable addition?
