### ISSUE TITLE
Table prefix configuration

### ISSUE THREAD

**Issue by calebfaruki** [knadh/listmonk#757]
In order to support having multiple applications colocated on the same database, it would be helpful to namespace tables by default as "listmonk_*". You could possibly customize it too. But having a default namespace of listmonk_* would suffice.

Alternatively, you could separate the applications into separate schemas of the same database. But having namespaced tables would still be nice-to-have.

**Comment by knadh** [comment]
Hi @calebfaruki. Bringing this to the app will complicate a lot of things. However, this is easily achievable within Postgres with Postgres schemas. Please see this https://github.com/knadh/listmonk/issues/598
