### ISSUE TITLE
Name field customization

### ISSUE THREAD

**Issue by chestnutbak** [knadh/listmonk#758]
**Is your feature request related to a problem? Please describe.**
I need to be able to use the first and last name separately.

**Describe the solution you'd like**
Create separate first and last name fields on the subscribers

**Comment by knadh** [comment]
You can store arbitrary fields in subscriber attributes. A `first_name` and `last_name` would work for you there.

https://listmonk.app/docs/querying-and-segmentation/#sample-attributes
