### ISSUE TITLE
Media uploads svg not allowed/supported

### ISSUE THREAD

**Issue by pepa65** [knadh/listmonk#759]
**Is your feature request related to a problem? Please describe.**
Trying to upload a svg as a Media resource, and it is not supported.

**Describe the solution you'd like**
Allowing uploads and use of svg files

**Comment by pepa65** [comment]
I guess the same goes for webp.

**Comment by knadh** [comment]
Most e-mail clients do not allow SVGs and webps to be embedded in e-mails, hence there's no support.

**Comment by pepa65** [comment]
What I was trying to do was to make the logo and icon locally available, and since there is no explicit webserver, I thought uploading them to the uploads area to be served might be an idea.

**Comment by pepa65** [comment]
I guess I could just "manually" put them in `uploads` and give the URL to that.

**Comment by knadh** [comment]
Yep. Will see if we can have arbitrary file uploads so that they can be linked (not embedded).
