### ISSUE TITLE
Multi-organization version

### ISSUE THREAD

**Issue by pomazanbohdan** [knadh/listmonk#76]
Is there a multi-organization version planned?

- Company1 
-- User 1
-- User 2
- Company2 
-- User 1
-- User 2

**Comment by knadh** [comment]
@pomazanbohdan multi-tenancy isn't planned, but roles and permissions are. That is, user A can manage lists 1 and 2, while user B can manage only list 3, and so on.

If you just want isolation between lists for users, this approach should work fine.
