### ISSUE TITLE
Distribute mail to list of subscribers

### ISSUE THREAD

**Issue by dblM90** [knadh/listmonk#761]
Hey everybody,

I have a short question regarding a functionality I need. Use case is that we are a small orchestra with around 20 people. I'm searching for an open source project that I can use to easily keep track of all subscribers for a mailing list. But instead of sending a mail using a gui I just wanna send a mail to my base adress (e.g. allmembers@orchestra.com) and each member of that list will receive the mail. Additionally, privacy regulations in our country forbid us to just add each recipient to the mail, because no other member should be able to see the other recipients mail adresses and also its a pain to enter all the mail addresses each time.

Does this project offer something like this?

Best regards,

Merlin

**Comment by NicoHood** [comment]
If it is just 20 people, why dont you sent it bcc?

**Comment by dblM90** [comment]
Because I'm not the only one sending mails to the other members and doing it manually each time is to much potential for forgetting one of them. I wanna have a central administration where i can add and delete members. And sending mails should be as easy as just sending an email to allmembers@...

**Comment by knadh** [comment]
> But instead of sending a mail using a gui I just wanna send a mail to my base adress (e.g. [allmembers@orchestra.com](mailto:allmembers@orchestra.com)) and each member of that list will receive the mail.

While this is not possible out of the box, it could be scripted using listmonk's APIs though.

> Additionally, privacy regulations in our country forbid us to just add each recipient to the mail, because no other member should be able to see the other recipients mail adresses and also its a pain to enter all the mail addresses each time.

listmonk has privacy features that allow subscribers to export their data, wipe their data etc.
