### ISSUE TITLE
Provide swagger for API

### ISSUE THREAD

**Issue by jirisykora83** [knadh/listmonk#764]
It will be nice to have swagger which seems like most commonly use documentation for api which enables auto generating api client.

**Comment by NicoHood** [comment]
You mean OpenApi, don't you? Swagger is just a tool.

**Comment by chrisgereina** [comment]
When this is done, I'd love to create an integration / node on [n8n](https://github.com/n8n-io/n8n) based on ListMonk's API which I feel would supercharge the functionality of the tool

**Comment by knadh** [comment]
This task is up for grabs, if anyone's interested in working on it!

**Comment by rohansh-tty** [comment]
@knadh So if I am getting this correct, we need to create a swagger collection of all listmonk APIs. If yes then, I can take up this issue. 
Thanks

**Comment by knadh** [comment]
@rohansh-tty. Yes, that would be nice. Thanks.

**Comment by knadh** [comment]
@rohansh-tty why don't you send a PR with the work you've done so far? I'm planning to merge the contents of the `listmonk-site` repo into a `docs` directory on this repo. You can put the Swagger specs in `docs/swagger` and send a PR.

**Comment by knadh** [comment]
@rohansh-tty's PR is merged. Thanks! https://github.com/knadh/listmonk/tree/master/docs/swagger

**Comment by knadh** [comment]
@rohansh-tty the Swagger site is up. Documented here: https://listmonk.app/docs/apis/apis/
