### ISSUE TITLE
bounce: pq: more than one row returned by a subquery used as an expression

### ISSUE THREAD

**Issue by charlesmudy** [knadh/listmonk#765]
**Version:**
 - listmonk: [eg: v2.0.0]
 - OS: Ubuntu 20

**Description of the bug and steps to reproduce:**
Getting bounce error sending with SendGrid SMTP `bounce.go:129: error recording bounce: pq: more than one row returned by a subquery used as an expression`

**Screenshots:**
<img width="1277" alt="Screenshot 2022-03-31 at 16 25 19" src="https://user-images.githubusercontent.com/1445007/161125603-a581bc32-3a96-44bf-ad77-dcfc964de0d4.png">

**Comment by knadh** [comment]
This is strange. I re-read the SQL query and there does not appear to be anything that could trigger this. Just to be sure, have you done any manual schema modifications on the DB?

**Comment by charlesmudy** [comment]
Yes we did, we are not making email unique in the system but rather limiting it per lists.

So the `record-bounce` seems to be returning multiple email records as the error mentioned, so we are trying to modify the code with this.. which is to limit it by campaign

`WITH sub AS (
    SELECT subscribers.id, subscribers.status
	FROM subscribers, campaigns
	WHERE $3 != '' AND campaigns.uuid = $3::UUID
	AND CASE WHEN $1 != '' THEN subscribers.uuid = $1::UUID ELSE subscribers.email = $2 END
),`

Thanks anyways.
