### ISSUE TITLE
Is personal data stored anywhere on the server with personal tracking turned off?

### ISSUE THREAD

**Issue by EzequielBruni** [knadh/listmonk#768]
For security reasons, I'm wondering if turning off individual tracking simply makes it so _you_ can't see the personal tracking data, or discards extraneous personal data altogether. I'm looking for an email solution that allows me to see how my campaigns are doing while respecting personal privacy. 

After all, in an absolute worst-case scenario, info you don't have can't get leaked or stolen.

**Comment by knadh** [comment]
Turning it off discards individual tracking data altogether. Views and clicks are stored in the database with no subscribers associated with them.

**Comment by EzequielBruni** [comment]
Thank you very much. Sounds perfect.
