### ISSUE TITLE
Security issue, split administration and subscription service

### ISSUE THREAD

**Issue by ware32** [knadh/listmonk#769]
This is a security question:
We want to split the Applicacion in two parts: administration part subscription related items, so, internally we could manage listmonk and only publish externally services to subscribe/unsubscribe.
is this possible?

Thanks

**Comment by knadh** [comment]
You can use a reverse proxy like Nginx to block admin endpoints: https://listmonk.app/docs/configuration/#public-endpoints-to-expose-to-the-internet
