### ISSUE TITLE
/listmonk : The term './listmonk' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Nezaros** [knadh/listmonk#77]
I'm trying to get run your app in my machine but it gets complicated and there's not much information to help me.
every time I run any command I see the same error
`./listmonk : The term './listmonk' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ ./listmonk
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./listmonk:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`
![Capture](https://user-images.githubusercontent.com/10624453/78193798-a23e1b00-747b-11ea-8410-972b953b9d88.PNG)

Help please. or if someone has time to give me a hand to help troth Teamviewer.
![Capture](https://user-images.githubusercontent.com/10624453/78187345-87b17500-746e-11ea-8f70-2bfce3587928.PNG)

**Comment by knadh** [comment]
On Windows `./` isn't recognised I think. Simply run `listmonk` on the terminate after `cd`ing to the directory were the binary is.

**Comment by Nezaros** [comment]
> On Windows `./` isn't recognised I think. Simply run `listmonk` on the terminate after `cd`ing to the directory were the binary is.

Hello Knadh
I did but still the same issues
![Capture](https://user-images.githubusercontent.com/10624453/78237501-b285e280-74db-11ea-90e4-8c49bdb63347.PNG)

**Comment by knadh** [comment]
Ah, looks like you're mixing standalone binary setup + Docker setup somehow. @mr-karan could you please take a look?

**Comment by Nezaros** [comment]
I mixing them just to show you that's all command not working for me.

**Comment by knadh** [comment]
Sorry, this just occurred to me. Since you're on Windows, the binary name is listmonk.exe. So you should be running `listmonk.exe` on the terminal.

**Comment by Nezaros** [comment]
I try it before the I clone the project, I sent you a message in Linkedin.
