### ISSUE TITLE
500 Internal Server Error when confirming list subscription twice

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#772]
**Version:**
 - listmonk: 2.1.0

**Description of the bug and steps to reproduce:**
A client of us triggered a very "nice" edge case bug: When you click the opt-in button twice of a mail, listmonks shows a 500 Server error. This message comes from the webserver, not listmonk itself and it **a lot confusing** for non-technical people.

It should show rather a message "You've already opted in" or so.

**Comment by NicoHood** [comment]
What would the UI now show?

**Comment by knadh** [comment]
The message remains the same. `There are no subscriptions to confirm`. The incorrect status code (500) is fixed.

**Comment by NicoHood** [comment]
Wouldn't it make sense to add a message, that the subscribtion was already confirmed? If that differenciation is not possible, maybe something like `There are no subscriptions to confirm. Maybe they have already been confirmed?` would be better?
