### ISSUE TITLE
Mark test emails as such

### ISSUE THREAD

**Issue by whysthatso** [knadh/listmonk#773]
**Is your feature request related to a problem? Please describe.**
When sending out test emails, it would be helpful to mark such an email.

**Describe the solution you'd like**
Simply prepend  [TEST] to the subject, like mailchimp is doing it.

**Comment by NicoHood** [comment]
But what if you simply manually want to resend a mail?

**Comment by whysthatso** [comment]
> But what if you simply manually want to resend a mail?

you mean you are using the feature to send a testmail for sending/resending production campaign mails?
yes, my feature request would be detrimental to such a work flow.

then again, maybe that should be its own feature?

**Comment by knadh** [comment]
The test mail feature is intended to reproduce, preview, and visualize an e-mail as-is before it is broadcast. Even small changes that differentiate them kind of defeat the ultimate purpose in my opinion. It's trivial to just add `TEST` to the subject manually. I don't think this should be an explicit feature.
