### ISSUE TITLE
Allow arbitrary emails as test email receiver.

### ISSUE THREAD

**Issue by whysthatso** [knadh/listmonk#774]
**Is your feature request related to a problem? Please describe.**
I sometimes have to send test emails to QA personal or spam testing addresses. it's cumbersome to add these to the list, and not forget to remove them after the testing.

**Describe the solution you'd like**
Allow to enter arbitrary emails as test email into the receiver field during the drafting modus.

**Comment by knadh** [comment]
Without actual an subscriber with attribs to e-mail, e-mails that use attribs and functions on top of them will break. Even a `Hello {{ .Subscriber.Name }}` will not render, breaking the preview e-mail, defying its purpose. To keep this behaviour consistent across all kinds of e-mails and tests, it's necessary to have a real subscriber.
