### ISSUE TITLE
No compaign stats here!

### ISSUE THREAD

**Issue by kdaffef** [knadh/listmonk#775]
A lot of thanks for this very nice and lightweight application !!
I make successfull install on unbuntu 20.04 vps and looks very fine,
I'm using SMTP own mail server to send emails, and get them sent fine, but there no stats : clicked and opened emails ?

For the test, i have opened all emails with images in emal client, many times and clicked on links, but still stats are empty !!!

Sorry, im new user, thank for your guidance!

![Campaigns-listmonk](https://user-images.githubusercontent.com/746103/162566501-fa6356a9-8a63-4635-8e8a-b8e55516de15.png)

**Comment by knadh** [comment]
Have you used the `{{ TrackLink }}` tag? https://listmonk.app/docs/templating/#functions

**Comment by kdaffef** [comment]
Hi @knadh , no didn't use it yet, okay think that's the reason!
will check and make feedback, +++
really great app ++++
As not experienced, is there any possibility to include basic template designer in future ??
Thank a lot

**Comment by knadh** [comment]
Thanks.

>  As not experienced, is there any possibility to include basic template designer in future ??

When it becomes technically feasible, yes: https://github.com/knadh/listmonk/issues/521

**Comment by kdaffef** [comment]
This will be great, will pay a big coffee !!

last help : how to track this button code : 
<a class="mcnButton " title="DEMANDE D ESSAI GRATUIT UNE SEMAINE" href="mailto:kdaffef@office-callservices.fr?subject=Demande%20d%20essai%20gratuit&amp;body=Bonjour%2C%0A%0ASuite%20%C3%A0%20votre%20email%2C%20je%20demande%20un%20essai%20gratuit%20d'une%20semaine%20%3A%0A%0A-%20Nom%20%26%20Pr%26nom%20%3A%20Dr%20%0A%0A-%20Activit%C3%A9%20%3A%20%0A%0A-%20Adresse%20%3A%0A%0A-%20T%C3%A9l.%20Portable%20%3A%20%0A%0A-%20Email%20pr%C3%A9f%C3%A9rentiel%20%3A%20%0A%0A-%20Vous%20pouvez%20me%20joindre%20de%20pr%C3%A9f%C3%A9rence%20pendant%20%3A%20%0A%0A-%20Je%20cherche%20%C3%A0%20changer%20de%20secr%C3%A9tariat%20%3A%20Plein%20temps%20-%20Temps%20partiel%20%0A%0A%20-%20Autre%20info%20%3A%0A%0A%0A" target="_blank" style="font-weight: bold;letter-spacing: normal;line-height: 100%;text-align: center;text-decoration: none;color: #FFFFFF;">DEMANDE D ESSAI GRATUIT UNE SEMAINE</a>
