### ISSUE TITLE
CSS inliner

### ISSUE THREAD

**Issue by IAkumaI** [knadh/listmonk#777]
**Is your feature request related to a problem? Please describe.**
Today not all email clients can show <style> css styles. Even now best is just inline all css into html style="" attribute.

**Describe the solution you'd like**
Is there any way to use css-inliner like https://github.com/aymerick/douceur or smt else?
It will be very usefull and, I think, not so hard to integrate

**Comment by knadh** [comment]
Closing this as there are no up-to-date CSS in-lining libs for Go. The linked lib has issues and hasn't been updated in several years.

Thankfully, most of the popular web and mobile e-mail clients are able to display <style> tags CSS well today.

**Comment by iloveitaly** [comment]
This could be an option, since I believe you can reach into C libraries from go: https://github.com/Stranger6667/css-inline/tree/master/bindings/c

**Comment by knadh** [comment]
CGO dependencies will open a Pandora’s box of install/run issues across environments unfortunately.
