### ISSUE TITLE
tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#779]
**Version:**
 - listmonk: 2.1.0

**Description of the bug and steps to reproduce:**
I am using mailjet (free version) to send my emails. With 2.1.0 I now switched from Starttls to TLS (just flip the config dropdown menu setting). But now i get:

```
2022/04/17 11:47:55error sending message in campaign Newsletter #22: subscriber <id>: tls: first record does not look like a TLS handshake
```

**Now I could make it work by using port `465` instead.** I'd like to know if there is anything listmonk could do to fix this? Mailjet says in their docs that `587` should work, but if not you should use 465 instead (which works). But maybe listmonk can be improved here?

**Comment by knadh** [comment]
hm, I'm not sure what's happening here. listmonk supports STARTTLS and SSL/TLS (irrespective of the ports). I looked at the Mailjet [docs](https://dev.mailjet.com/smtp-relay/configuration/) and it's confusing how SSL and TLS are listed separately while there's no mention of STARTTLS. If 465 is working with TLS turned on, then that's fine. If that port didn't support TLS, it wouldn't connect in the first place.

**Comment by NicoHood** [comment]
I've written an email to them. Will post the reply here.

**Comment by knadh** [comment]
Was this resolved @NicoHood?

**Comment by NicoHood** [comment]
Good that you ask. I got no reply yet, so I wrote another email. Lets see what they answer.

**Comment by knadh** [comment]
Closing this for now as it looks like a peculiarity with the e-mail provider.

**Comment by 1000i100** [comment]
Same issue here trying to send email with protonmail smtp (with a smtp token)
PS : listmonk 3 run inside docker-compose.yml if it can help.

**Comment by 1000i100** [comment]
solved with this config : https://proton.me/support/smtp-submission
SMTP host: smtp.protonmail.ch
Port: 587
Authentication method: PLAIN
Encryption: STARTTLS
