### ISSUE TITLE
Docs do not show media and import API

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#781]
When first opening the [docs](https://listmonk.app/docs/), they do not show the media and import api on the left:
![image](https://user-images.githubusercontent.com/6888294/163882199-686d3f53-2c8a-4af1-b7fc-af1bc34479f1.png)

After clicking on campaigns, it shows up:
![image](https://user-images.githubusercontent.com/6888294/163882244-1a053217-ac04-4f1c-9332-b3a4914aa100.png)

Returning back to home also shows all entries.

This is not a browser cache issue, whenever I start with a clear cache, the first doc page is incomplete

**Comment by knadh** [comment]
I'm unable to reproduce this on Firefox and Chromium. The docs is a static HTML page and the menu is also static HTML. Is there a browser addon that's affecting the DOM for you?

**Comment by NicoHood** [comment]
I am also not sure why this happens. I have adblocker(ublock origin) and noscript installed, but noscript is disabled currently. I was able to reproduce this 2-3 times, but did not found the pattern that triggered the bug. It was in Firefox.

**Comment by knadh** [comment]
I also have uBlock origin installed. Unable to reproduce this, hm.
