### ISSUE TITLE
Add slug to campaign API

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#782]
**Is your feature request related to a problem? Please describe.**
I am writing and updating listmonk newsletters through the api. What is currently hard for me is to identify existing campaigns. I'd need to either note the id when I first uploaded them or I need to check the name/subject, which is a human but not so good machine readable name.

**Describe the solution you'd like**
I'd like to have an id by name, maybe a slug. This `special-campaign-name` can be translated from the `Human readable name` (or better `Special Campaign Name`).

Maybe this slug could also be used for the public archive page feature:
https://github.com/knadh/listmonk/issues/540

What do you think?

**Comment by knadh** [comment]
The campaign name can be used as a slug as the subject line is what's shown to the outside world. There are also campaign tags (which cannot be queried via the API right now, but could be added).

**Comment by NicoHood** [comment]
Yeah, I also found my solution not fully thought out. Having tags in the API would be nice!
