### ISSUE TITLE
CSV Upload Not Working

### ISSUE THREAD

**Issue by infinitronic** [knadh/listmonk#783]
**Version:**
 - listmonk: [eg: v2.0.0]
 - OS: [e.g. Windows 10]

**Description of the bug and steps to reproduce:**
Tried uploading this file: 

https://www.dropbox.com/s/4ibuf52erh9rgvc/test_base.csv?dl=0

to the CSV uploader but the upload button remained deactivated making it impossible to upload the email address on the test file. I tried with the attributes field, with the name specified without the " " wrapper.... and they had no effect i.e. the Upload button remained deactivated.  

**Screenshots:**
https://www.dropbox.com/s/inaz5lwfj6vuev5/listmonk_csv_ish.png?dl=0

**Comment by knadh** [comment]
Have you selected lists to import to in the field above? That's not visible in the screenshot.

**Comment by infinitronic** [comment]
> Have you selected lists to import to in the field above? That's not visible in the screenshot.

Hello Knadh. Yes I have i.e. test_base.csv. It's there - above the greyed out Upload button. I've tried selecting it using both the drag and drop and also the file upload functionalities but have gotten the same greyed out Upload button result. Perhaps there's something I'm not getting right Knadh?

**Comment by knadh** [comment]
> Hello Knadh. Yes I have i.e. test_base.csv.

Not the file, but the lists to import subscribers to.

![image](https://user-images.githubusercontent.com/547147/165031000-e5dbaa61-491d-4239-b680-1b33da20590d.png)

**Comment by infinitronic** [comment]
Hello Knadh. I never knew so much joy could well up in the heart of a man when a greyed out button turns blue and WORKS (https://www.dropbox.com/s/5w389ias9av33f7/listmonk_csv_ish_fixed_by_knadh.png?dl=0), until now, thanks to you Knadh. Thanks a lot. Maybe a way to denote that a list to import to is required can be useful here. You're the man, Knadh.
