### ISSUE TITLE
How to add cc recipent to email?

### ISSUE THREAD

**Issue by rohanrajpal** [knadh/listmonk#784]
When I add a custom header to a campaign
```
[
    {
        "CC": "First Rohan <rohan46000@gmail.com>, Second Rohan <rohan17089@iiitd.ac.in>"
    }
]
```

and it appears in the email too:
![image](https://user-images.githubusercontent.com/7023147/164971441-d8cc5abd-6740-49e2-9987-a81882c64ce9.png)

But I don't get an email on the cc'ed ids, anything that I'm missing?

**Comment by knadh** [comment]
hm, unsure. The CC header is processed and the copy mail is sent by the SMTP server.

**Comment by rohanrajpal** [comment]
> hm, unsure. The CC header is processed and the copy mail is sent by the SMTP server.

Another thing that happens is after saving the campaign, when I refresh the page the following custom attribute changes to:
```
[
    {
        "CC": "First Rohan <rohan46000@gmail.com>, Second Rohan <rohan17089@iiitd.ac.in>, Royal Tomar <rtomar1999@gmail.com>",
        "Cc": "First Rohan <rohan46000@gmail.com>, Second Rohan <rohan17089@iiitd.ac.in>",
        "cc": "First Rohan <rohan46000@gmail.com>, Second Rohan <rohan17089@iiitd.ac.in>"
    }
]
```

I guess its ensure compatibility with all SMTP servers?

**Comment by knadh** [comment]
Sorry, confused. What changes to what? listmonk doesn't mutate custom campaign headers.

**Comment by rohanrajpal** [comment]
Steps to reproduce:

1. go to any campaign & set the following as custom attributes, save
```
[
    {
        "CC": "First Rohan <rohan46000@gmail.com>, Second Rohan <rohan17089@iiitd.ac.in>, Royal Tomar <rtomar1999@gmail.com>",
        "Cc": "First Rohan <rohan46000@gmail.com>, Second Rohan <rohan17089@iiitd.ac.in>",
        "cc": "First Rohan <rohan46000@gmail.com>, Second Rohan <rohan17089@iiitd.ac.in>"
    }
]
```
2. now override the value with this
```
[
    {
        "CC": "First Rohan <rohan46000@gmail.com>, Second Rohan <rohan17089@iiitd.ac.in>"
    }
]
```
3. when you'll save and reload the page, it will still show the value set in point 1

It should override the old value ideally, right?

**Comment by knadh** [comment]
This is expected behaviour. Headers are case-insensitive. You just need `CC`. `cc`, `Cc` etc. are superficial.

**Comment by rohanrajpal** [comment]
> This is expected behaviour. Headers are case-insensitive. You just need `CC`. `cc`, `Cc` etc. are superficial.

Cool cool, understood.

**Comment by rohanrajpal** [comment]
But still, cc is not being sent. Any logs/some other info I can provide for easier debugging?

**Comment by knadh** [comment]
CC is just a header sent by a mail client (listmonk) and is meant to be processed by the mail server. This should be investigated at the SMTP level. listmonk simply attaches the header.

**Comment by rohanrajpal** [comment]
Is your listmonk instance able to send cc email correctly?
