### ISSUE TITLE
Enable browser-bases spell checking in TinyMCE

### ISSUE THREAD

**Issue by mdehollander** [knadh/listmonk#786]
It would be nice if there is browser bases spell checking when writing a newsletter. It seems there is an option in TinyMCE to enable this: 
https://www.tiny.cloud/docs/general-configuration-guide/spell-checking/#browser-basedspellchecking 

Would adding `browser_spellcheck: true` to https://github.com/knadh/listmonk/blob/c140578c656ed1fe448c2657e396e5c2ead67e15/frontend/src/components/Editor.vue#L138 be sufficient?

**Comment by knadh** [comment]
Yep, looks like it. :+1:
