### ISSUE TITLE
Detect and log sending errors

### ISSUE THREAD

**Issue by nathanaelhoun** [knadh/listmonk#789]
**Is your feature request related to a problem? Please describe.**
When I send emails from Listmonk, sometimes errors occur (for example, the log message below show that I'm being rate limited by my SMTP provider).

```
2022/04/28 14:38:01error sending message in campaign [REDACTED]: subscriber 2572b6a1-3e78-4d9e-9494-ffcb2d9533a7: 451 4.3.0 You have reached the maximum number of sent emails within a 24-hours period. For more information: https://faq.infomaniak.com/2065
```

However, in the UI, it show me as if all the emails were sent (emphasis is mine)
![image](https://user-images.githubusercontent.com/45119518/165801287-6243e2b6-9710-4a26-b5a5-749ce602e448.png)

**Describe the solution you'd like**

Add a statistic of failed emails, like it exists for bounces.
It would be even better if we could have the list of errored emails, and with the related log.

Thanks for Listmonk btw, the UI is very sleek and all the implemented features are well-done and easy to use :-)

**Comment by radioboss** [comment]
This was a surprise for me to know that Listmonk completely ignores sending errors. For instance, I create an SMTP server and fill the details with some random invalid data. I start a campaign and send a test email - it says that the email was sent successfully while in fact of course nothing was sent.

**Comment by knadh** [comment]
> This was a surprise for me to know that Listmonk completely ignores sending errors.

It doesn't. All errors are logged in the system console. The `Maximum error threshold` setting in Settings -> Performance captures SMTP errors and automatically pauses campaigns too.

E-mails are queued sent asynchronously for performance + throughput. Depending on the network, capacity of the SMTP server, and rate settings (Settings -> Performance) an e-mail could meet with an error instantly, after seconds, minutes, or hours. Such errors can obviously only be logged.

**Comment by radioboss** [comment]
> It doesn't. All errors are logged in the system console. The `Maximum error threshold` setting in Settings -> Performance captures SMTP errors and automatically pauses campaigns too.

Yes, I've seen it in the log. It's still confusing that it shows "Email successfully sent" message while in fact it wasn't because it was unable to connect to SMTP server (and this is known immediatelty).

Another problem is with the log itself, after Listmonk is running for about 2 hours, the Log section becomes empty.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/commit/ee448170ef9ae8f315f6e55316b3f36e33fe2561 adds a new `Test connection` feature on the SMTP settings UI. This will be available in the upcoming release.
