### ISSUE TITLE
Plain text alternative for campaigns

### ISSUE THREAD

**Issue by gerricom** [knadh/listmonk#79]
Hi! Do you have plans to integrate a plain text alternative for campaigns? 
Spam filters tend to be allergic to mails without a propper plain text alternative. So I'd like to see either an automatic way to add a plain text message or a method to add your own message.
Thanks!

**Comment by knadh** [comment]
Hi @gerricom,
This is indeed on my to-do. I'll try to roll this out sometime soon. Prioritising items ad-hoc as requests come in :)

**Comment by jaredfolkins** [comment]
PR for this feature has been submitted. It takes the HTML body, removes the HTML while keeping a similar formatting. It includes the Plain Text along with the HTML body.

Thanks,
Jared

**Comment by knadh** [comment]
#80 adds this.
