### ISSUE TITLE
Listmonk Analytics is not displaying Views, Clicks, Bounces

### ISSUE THREAD

**Issue by SonalikaG** [knadh/listmonk#793]
When we trigger a campaign, the analytics display only the number of emails sent under Stats on Campaigns page. It does not give the number for Views, Clicks and Bounces.

Also it displays 0 for Views, Clicks, Bounces and Links on the Analytics page.

![image](https://user-images.githubusercontent.com/72000677/165947175-92ea1255-81d0-484c-aa4c-76881059e66e.png)

![image](https://user-images.githubusercontent.com/72000677/165947308-3b242787-e214-429a-b66c-a08341a3cbec.png)

@knadh Please let me know the reasons this issue may be occurring and how can we resolve it. Thank you.

**Comment by knadh** [comment]
Please see the "Template functions" section: https://listmonk.app/docs/templating/#functions

Your template has to have `{{ TrackView }}` and links in the e-mails should have the `Track` checkbox checked (if you're writing content using the UI), otherwise, the `TrackLink` tag as described in the documentation.

**Comment by viralpatel380** [comment]
> Please see the "Template functions" section: https://listmonk.app/docs/templating/#functions
> 
> Your template has to have `{{ TrackView }}` and links in the e-mails should have the `Track` checkbox checked (if you're writing content using the UI), otherwise, the `TrackLink` tag as described in the documentation.

Hey, @knadh Using  `{{ TrackView }}` there is no change in analytics. Link clicks as well as Mail Views.

**Comment by t3hmrman** [comment]
Hey possibly unrelated, but for the second issue (analytics page loading forever), check if you have uBlock Origin or an ad blocker installed and make sure you have it turned off for your listmonk deployment. 

I checked my network tab and the request was being blocked by uBlock origin (somehow, only one request out of many!).

**Comment by finleykjames** [comment]
I know this is ages old, but this is an issue I'm having. Even though I have `{{ TrackView }}` within the footer, it isn't tracking any views. I'm not sure how to get it to work.
