### ISSUE TITLE
error fetching campaigns: pq: cannot execute SELECT in a read-only transaction

### ISSUE THREAD

**Issue by devinellis** [knadh/listmonk#800]
- listmonk: v2.1.0
 - OS: Docker

I've noticed listmonk sometimes ends up in a bad state and returns 524s. Checking the logs, I see:

```
manager.go:464: error fetching campaigns: pq: cannot execute SELECT in a read-only transaction
subscribers.go:715: error inserting subscriber: pq: cannot execute SELECT in a read-only transaction
```

In my app, I see logs like this

```
524 GET /api/subscribers?query=email%3D%27redacted%27&per_page=all
```

And when trying to load the Listmonk Dashboard, the table's just hang.

Restarting the docker container brings it back to a healthy state.

**Comment by knadh** [comment]
Whoa, that's strange. Those queries do not even use transactions. There is no shared state between queries either, so this looks like it must have something to do with Postgres and how its handling listmonk's connections. 

Does this shed any light? 
https://stackoverflow.com/questions/54648513/error-cannot-execute-select-in-a-read-only-transaction-when-connecting-to-db

**Comment by devinellis** [comment]
Next time it happens, I'll see what those pg values are set to and report back.

But why would restarting the listmonk container (and doing nothing to the DB) make the problem go away?

**Comment by devinellis** [comment]
It happened again, and I ran the debug queries in that StackOverflow answer but they all came back negative. Restarting the Listmonk container brought it back to a healthy state.

However, looking at the Listmonk's logs, I do not see another instance of that error. In fact, there were no new logs since 9/5/4 (when I last restarted it and created this GitHub Issue). But the symptom was the same: API calls were hanging.

Is there configuration I can set to have more verbose logging, so I can help diagnose this better?

Thanks

**Comment by knadh** [comment]
I'm at a loss here, hm. I've never come across a DB error in our production listmonk instances that run in Docker containers and handle millions of DB requests.

All DB/SQL errors are printed in the log. It's verbose by default

**Comment by devinellis** [comment]
Maybe the DB transaction error is unrelated (after all, this time I did not see that log again). If the requests to Listmonk hang, and my app eventually receives a 524, shouldn't there be a corresponding log for it?

FWIW, this is running in Digital Ocean, using their managed PostgreSQL over a private VPC.

**Comment by knadh** [comment]
Yes, all errors returned by the database driver is logged, which is why I suspect this is somehow happening outside listmonk (especially because it's 524 and not 504). Could you check your Postgres instance's statement timeout setting? `SHOW statement_timeout;`.

How big is your subscribers table? Does it run into the tens of millions?

**Comment by devinellis** [comment]
SHOW statement_timeout = 0. Subscriber count is just a few thousand. Next time it happens, I'll test listmonk by cURLing it directly to rule out any proxy issues.

I don't yet have connection pooling configured. Is it possible Listmonk has lost its connection, and instead of reconnecting, it just waits and eventually some network layer times out?

**Comment by knadh** [comment]
With just a few thousand subscribers, there should ideally never be any DB timeouts. You could set `statement_timeout` to maybe 10 seconds to see if that catches this behaviour.

In config.toml, you should set `max_open` and `max_idle` to more than 1. Something like 10, 5 should be fine.

**Comment by knadh** [comment]
Hi @devinellis. Did this happen again? Were you able to figure this out?

**Comment by devinellis** [comment]
No, it hasn't happened again, but we've also not sent any campaigns since May 10. So it might be related to campaign sends...

**Comment by knadh** [comment]
Thanks for the update. Closing this issue for now. If you run into this again, please report.
