### ISSUE TITLE
How do you add 'Tracklink' tag for an attribute?

### ISSUE THREAD

**Issue by SonalikaG** [knadh/listmonk#801]
For personalization of emails, when we add URLs as attributes for each subscriber and only add the expression for the attribute in the template, how and where do we add the `Tracklink` tag? Because if we add the Tracklink alongwith the attribute expression, it displays an error.

@knadh Could you please help.

**Comment by knadh** [comment]
Please share a sample of your TrackLink code.

Also, tracking is ideally only meaningful for non-unique URLs to look at aggregate stats. If you have a URL that is unique per subscriber anyway, there is no aggregate stats.

**Comment by SonalikaG** [comment]
Here is an example of a line in a template:

`All you have to do is <a href="{{ .Subscriber.Attribs.Page }}?email={{ .Subscriber.Email }}" target="_blank">claim your page</a>.`

where {{ .Subscriber.Attribs.Page }} will capture URL that is unique for each user.

**Comment by SonalikaG** [comment]
This is how we normally use our links 
```html
<p><a href='{{ TrackLink "https://mysite.com/x/y/z" }}'>Click here</a><br><br>
```
What we are trying to do is the following:
```html
<p><a href='{{ TrackLink URL_Expression }}'>Click here</a><br><br>
```

`URL_Expression` is a dynamic URL based on the subscribers' attribute JSON: 

```html
<p><a href='{{ TrackLink .Subscriber.Attribs.trackingIndividual }}'>Click here</a><br><br>
```
`.Subscriber.Attribs.trackingIndividual` trackingIndividual is the URL.
