### ISSUE TITLE
Amazon SES integration for sending

### ISSUE THREAD

**Issue by muelli** [knadh/listmonk#802]
I know listmonk can send email via SMTP.
Using the SES API would provide benefits such as avoiding the cost involved with using the SMTP interface.
I guess listmonk could either talk to the SES API directly.
Alternatively, it should be possible to write a messenger that can on Lambda and translates from listmonk to SES.

**Comment by knadh** [comment]
Ah, a simple HTTP messenger on an AWS lamba is a nice idea. Related project: https://github.com/joeirimpan/listmonk-messenger (@joeirimpan)

**Comment by muelli** [comment]
so... has this been implemented? I can't find a commit neither here nor in in the messenger.

**Comment by pucilpet** [comment]
> I know listmonk can send email via SMTP.
> Using the SES API would provide benefits such as avoiding the cost involved with using the SMTP interface.
> I guess listmonk could either talk to the SES API directly.
> Alternatively, it should be possible to write a messenger that can on Lambda and translates from listmonk to SES.
> 

How does the SES api avoid the costs of the SMTP interface? I cant find any info online regarding this.

**Comment by knadh** [comment]
It doesn't. You've to pay SES whatever they charge. SES is one of the cheapest SMTP providers are there.

**Comment by muelli** [comment]
> How does the SES api avoid the costs of the SMTP interface? I cant find any info online regarding this.

you could host listmonk anywhere but the messenger on AWS, e.g. on Lambda. Then, the Free Tier should apply.

"When you call Amazon SES from an application hosted in Amazon EC2 or via AWS Lambda, you can send 62,000 messages per month at no charge. This Free Usage Tier benefit does not expire."

**Comment by joeirimpan** [comment]
@muelli SES messenger is available now @ https://github.com/joeirimpan/listmonk-messenger
@knadh you can close this issue
