### ISSUE TITLE
SES bounces and campaign

### ISSUE THREAD

**Issue by atoy40** [knadh/listmonk#804]
Hello,

SES bounces doesn't seem to be link to the originate campaign. Is it a limitation or is there any way to have this information ?
thks
Anthony.

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/blob/a3fd4616e3b97feb2f5f87fcd8363e64e1e5bfb3/internal/bounce/webhooks/ses.go#L130

SES bounce processor looks for campaign headers in the e-mail. I remember this correctly working in the tests as well.

**Comment by atoy40** [comment]
Thanks,

reading the code , I realized I've probably missed something on the amazon configuration ... and that's it ... i've not checked "include original headers...."

thks :)
