### ISSUE TITLE
Why AWS SES configuration not working?

### ISSUE THREAD

**Issue by maniSHarma7575** [knadh/listmonk#806]
**Version:**
 - listmonk: [eg: v1.0.0]
 - OS: [e.g. MacOS]

**Description of the bug and steps to reproduce:**

I have defined these AWS SES configuration:

```
# Amazon SES configuration

[smtp]
    [smtp.ses]
        enabled = true
        host = "*****"
        port = "587"
        auth_protocol = "plain"
        username = "****"
        password = "*****"
        send_timeout = 5000
        max_conns = 10
```
But application is not using this configuration. It's using the default configuration provided in the seeds.

Am I doing something wrong?

**Screenshots:**

**Comment by knadh** [comment]
All configuration (except for DB) is managed from the UI. Please go to the `Settings` page to set this up.

**Comment by maniSHarma7575** [comment]
@knadh Thanks!
