### ISSUE TITLE
Allow blank name

### ISSUE THREAD

**Issue by capocasa** [knadh/listmonk#807]
**Is your feature request related to a problem? Please describe.**

No, I only run a minimalistic notificatin-type newsletter service that does not ask for names for simplicity and privacy.

**Describe the solution you'd like**

I would like to be able to import subscribers with a blank name from CSV, and add subscribers with a blank name via API.

Currently I can work around this by adding '' as the subscriber name and it is sent without target name just fine, but it would be much nicer if I could just leave it out in the API or the CSV.

Not a huge issue all in all but worth considering for polish, IMHO.

**Comment by knadh** [comment]
Closing this as blank names aren't ideal for the reasons described in https://github.com/knadh/listmonk/issues/594
