### ISSUE TITLE
Can't get HTTPS or Ajax to work - Sign up form is throwing a warning

### ISSUE THREAD

**Issue by fetzsav** [knadh/listmonk#812]
When using the build in form generator code from listmonk, I am getting the following warning on my website when trying to use it:

_The information you have entered on this page will be sent over an insecure connection and could be read by a third party._

I tried enabling SSL, but the site does not goto SSL.

So, I have tried using ajax requests as well, but am getting a CORS error. Do I need to setup CORS? If so, where and how can I do that? I tried setting headers in the request but it says "CORS Request did not suceed"

The linkmonk install is on the subdomain
mailer.thedomain.com

my website is on just:
thedomain.com

**Comment by knadh** [comment]
What is the value of the `Root URL` in Settings -> General?

**Comment by fetzsav** [comment]
> What is the value of the `Root URL` in Settings -> General?

Hey, i had it set to http.

However, i changed it to https. 

ssl mode is set to “require” now in the config. site url is set to https://mailer.domain.com

i try to visit the site on https and it says it cannot connect to the server. 
i can still connect on http fine.

**Comment by fetzsav** [comment]
I am hosting on a Linode VPS by the way.

**Comment by fetzsav** [comment]
> What is the value of the `Root URL` in Settings -> General?

**Comment by fetzsav** [comment]
Did not mean to close the question.

I am home now... the domain is still not connecting on https. Is there a setup or something I need to do to get the vue http server to route through https? 
I would imagine that I need to install an SSL certificate on the VPS... but listmonk does not use apache or nginx so I am unsure where to install it?

Thanks for you awesome software and help :) hope I can get this working.

**Comment by knadh** [comment]
listmonk does not do any SSL termination at all. It'll issue redirects to whatever URL you put in settings, http or https.

If you want SSL, you should put listmonk behind a reverse proxy like Caddy or Nginx. There are plenty of Caddy tutorials that should be of help.
