### ISSUE TITLE
the possibility to expose the app port on specific network interface with docker-compose deployments

### ISSUE THREAD

**Issue by debianadmin-servusat** [knadh/listmonk#813]
I have a docker host that operates with multiple network interfaces.

In the documentation under /docs/installation/#manual-docker-install_1, on the 3rd point about changes to `config.toml` it's noted that `Port forwarding on Docker will work only if the app is advertising on all interfaces.` in parenthesis. I haven't really found any other info on this specific topic in the documentation or the example configurations.

This is proven to be true, since when I explicitly state the interface for the `app` port like so in my `docker-compose.yml`:

``` yml
x-app-defaults: &app-defaults
...
    ports:
      - "127.0.0.1:9001:9000"
...
```

the app is not reachable under `127.0.0.1:9001`. It only works when all the interfaces are used with the port. I also cannot change the first part (IP block) of the suggested `config.toml` `address` variable:

``` toml
[app]
address = "0.0.0.0:9001"
```

Is there a specific reason why this has to be like this?

Can we have the possibility to not expose the chosen port on _all_ of our network interfaces, and choose the one we'd like to? \
Or simply have it run over localhost and run it through a reverse-proxy like most docker services?

**Last but not least:** Thank you very much for all your work. We've been following listmonk at our organization as a potential alternative to Mailtrain for a while now, as their v2 resource requirements exceeds what we can provide for multiple instances. So we're really excited to see if we can adopt listmonk as our new newsletter tool moving forward.

**Comment by knadh** [comment]
Thanks @debianadmin-servusat.

`0.0.0.0:9000` runs inside the Docker container (Docker network) and not your machine's interfaces.

Non-Docker installation is as easy as downloading the binary and running `./listmonk`.

**Comment by mr-karan** [comment]
You can expose the app just on the local loopback interface simply by tweaking `9000:9000` to `127.0.0.1:9000:9000`.

```
x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  ports:
    - "127.0.0.1:9000:9000"
  networks:
    - listmonk
  environment:
    - TZ=Etc/UTC
```

On running `docker-compose up demo-app demo-db`, I can curl on `localhost`:

```bash
curl -i localhost:9000/api/health
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Mon, 16 May 2022 12:35:20 GMT
Content-Length: 14

{"data":true}
```

> Port forwarding on Docker will work only if the app is advertising on all interfaces

This line in doc refers to the app process inside the container. And yes, that's a requirement for port forwarding. The way it works is that the main process has to specify an interface it can _accept_ the connection from. If you specify only `127.0.0.1:9000` in the `config.toml`, that means the app can only accept request from _loopback_ interface _within_ the docker container. But generally, you don't want that, you want to proxy the host traffic inside docker container's network (the IP of which is not static, it's allocated from a subnet that you can see with `docker network`. To keep things simple, almost everyone suggests to bind on `0.0.0.0` so the app process can listen on all interfaces and except the traffic from outside of the container as well).

**Comment by debianadmin-servusat** [comment]
Ah! I guess I wasn't understanding the difference between the `address` variable under `config.toml` and the app's ports/address under `docker-compose.yml` until now.

So the problem with my configuration wasn't with the line `127.0.0.1:9001:9000` under `docker-compose.yml`, it was the fact that I was also changing the port under `config.toml` to read `address = 0.0.0.0:9001` and of course within docker there is no process on port `9001`.

**For anyone else who falls into the same confusion:** you should _only_ change your `docker-compose.yml` ports configuration if you want to expose on a specific interface, and leave the `config.toml` line as `address = 0.0.0.0:9000` since that has nothing to do with your host interfaces or ports.

Thanks a lot @mr-karan and @knadh. Maybe a clarification stating this difference in the docs would help others like me to not confuse the role of `config.toml` in the deployment?
