### ISSUE TITLE
ListMonk (catered for content creators)

### ISSUE THREAD

**Issue by devaayushraj** [knadh/listmonk#815]
@knadh Thank you so much for your effort.

I want your help in figuring out two things.

My usage is as follows:

**1. Use Listmonk for the x-day email course.** i.e., if someone signs up for the course, they will receive the email for x days, as with any email course. As a content creator, it is common for us to offer a free X-day email course to our subscribers. The problem now is that I want to offer more than one course. How should we go about it?

Once the user has completed the course, they should be directed to the newsletter section.

**2. Use it for a weekly newsletter.**

@knadh Have you used Mautic before? Is it possible to have a similar frontend in listmonk? It would be far better.
Can we have something like this in listmonk: https://www.youtube.com/watch?v=VZVvw6v7NV4

Also, what is the listmonk's minimum hardware requirement?

Waiting for your reply 🙏

**Comment by knadh** [comment]
Thanks @devaayushraj 

1. This can be scripted with listmonk's APIs but is not possible out of the box.
2. Mautic is a mailing automation tool while listmonk is a newsletter manager.

Both things that you are asking for require scriptability and automation, so I think Mautic is better suited for you. listmonk's hardware requirements are negligible. It will run fine on the smallest VPS you can find.

**Comment by devaayushraj** [comment]
@knadh first of all thank you so much for the response.


I am touched by your down to earth nature.

It can be implemented. WOW.
Can you guide us regarding that?

Not everyone is a programing god like you 🙏

Something on the script part can be alot of help for us.

Looking at the Listmonk's simplicity. Listmonk has my heart. If ever I use
something for newsletter it has to Listmonk.

A drip campaign feature would be a boon for all content creators worldwide.

We beg you to Please include drip campaign feature in listmonk. (Maybe in
the next release) 🙏

You are our only hope.

**Comment by knadh** [comment]
I am afraid you'll need a programmer to script the APIs to suit your requirements. "Drip campaign" is an automation feature that does not fit into listmonk right now.
