### ISSUE TITLE
Why does the REST API wrap each response in a data attribute?

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#818]
Hi!
I am designing a REST API for a totally unrelated project. So I am looking at best practices and what other projects do. Listmonk is one of the very well-designed examples I am looking at.

I am wondering why did you decide to wrap all responses inside a `data` object? In which scenarios do you have other objects next to the `data` object?

**Comment by knadh** [comment]
`{data: {}, message/error: ...}` is a convention to hard-separate fields in JSON OK and error responses. Of course, the HTTP response code is the authoritative indicator for OK and error, but this is to semantically separate data and non-data payloads and make it more readable.

For example, if `message` is the field dedicated to convey error messages and there is a `message` field in a certain OK response:

With `data` envelope:
- `{ data: { message: "good message"} }` - 200 OK
- `{ data: {}, message: "bad message" }` - 500 Error

Without `data` envelope:
- `{ message: "good message" }` - 200 OK
- `{ message: "bad message" }` - 500 Error

Thus, the envelope `data` helps keep a clear separation between data and non-data fields.

**Comment by NicoHood** [comment]
Thanks!

Is this pattern somewhere documented? I've seen a combination with `message` + `success` (as a bool) out there. I am trying to find a good pattern to start with, that will not cause problems in the long run.
