### ISSUE TITLE
View in browser template function

### ISSUE THREAD

**Issue by mdehollander** [knadh/listmonk#82]
Is there a template function to add a "view in browser" link to a campaign?

I see you can have a preview url via the api `api/campaigns/1/preview`, but that one is not publicly visible.

**Comment by knadh** [comment]
Not yet, but this is straight forward to do. Can include in the next release (~1 week).

**Comment by mdehollander** [comment]
Super. Thanks.

**Comment by mdehollander** [comment]
Hi @knadh, just a quick message to check if you are planning to create a new release with the 'view in browser' function. Thanks a lot.

**Comment by knadh** [comment]
This is actually done: https://github.com/knadh/listmonk/tree/refactor-public-links

You can pull this branch and compile to immediately start using it. Working on a couple other fixes before making a release.

**Comment by mdehollander** [comment]
Great, I will give it a try. So I can use the `{{ MessageURL }}` template? Or should there be a dot in front of it?

**Comment by knadh** [comment]
Just `{{ MessageURL }}`.

**Comment by knadh** [comment]
Available in [v0.6.0-alpha](https://github.com/knadh/listmonk/releases/tag/v0.6.0-alpha).

**Comment by mdehollander** [comment]
Thanks a lot!
