### ISSUE TITLE
When auth is disabled, hide login button and make logout link customizable

### ISSUE THREAD

**Issue by gramakri** [knadh/listmonk#821]
**Is your feature request related to a problem? Please describe.**
When admin username and password are set to null, the Login page is still shown. Clicking the login button let's us login without any password.

**Describe the solution you'd like**
Ideally, the Login page is not shown at all. I am trying to package Listmonk for Cloudron, we have a login proxy that provides the authentication for apps without user management. However, after logging in via the proxy, Listmonk still shows the Login button. Clicking the Login button does login but there are two Login clicks required now to login.

Also, the Logout button should be made customizable with a URL to logout via the proxy. Currently, it goes back to Login button view.

**Comment by knadh** [comment]
Disabling auth is meant only for backwards compatibility. A proper multi-user auth and permission system is on the todo (https://github.com/knadh/listmonk/issues/543).

> Ideally, the Login page is not shown at all.

Yep, it is just a static landing page which is a placeholder for a future login system. There's no session management right now to skip the login page. In your setup, is it possible to always route `/` to `/admin`? That'll solve the issue.

**Comment by gramakri** [comment]
@knadh Thanks for the info, I didn't realize that disabling auth was for backward compat (I guess listmonk started out with no auth at all). Routing to `/admin` should work (but I think we will probably wait for #543).
