### ISSUE TITLE
Display mailgun analytics in Listmonk

### ISSUE THREAD

**Issue by SonalikaG** [knadh/listmonk#828]
Which code should we use in Listmonk email template such that the analytics is captured in Mailgun as Mailgun is our canonical source for tracking emails? 

Does Listmonk have the ability to display the analytics from mailgun in Listmonk?

@knadh Could you please help with these questions.

**Comment by knadh** [comment]
I'm not familiar with Mailgun analytics. That said, it is not possible to plug in external analytics into listmonk. Wouldn't Mailgun's own dashboards work for this?
