### ISSUE TITLE
running listmonk as a service (ubuntu)

### ISSUE THREAD

**Issue by robert-winkler** [knadh/listmonk#829]
Hi, I just installed listmonk on my private web server (Ubuntu).
Amazing!!!!
Just a request: could you add to your documentation how to run the binary as a service?
For restarting it automatically in case of a reboot, etc.
Thanks!

**Comment by knadh** [comment]
Hi @robert-winkler. There's a sample systemd service unit file [here](https://github.com/knadh/listmonk/blob/master/listmonk%40.service). You can look up how to install it and how systemd services work. Plenty of tutorials out there.
