### ISSUE TITLE
Emails are not sent to subcribers in queue after campaign is exhausted

### ISSUE THREAD

**Issue by gurramlokesh** [knadh/listmonk#83]
When running a campaign, after enqueuing all subscribers, the campaign is exhausted. That marks the campaign as Finished and removes it from manager.camps

If the **campMsgQueue** still has elements, they won't be processed because of this check.

`
					if !m.isCampaignProcessing(msg.Campaign.ID) {
						continue
					}
`

This check helps when the campaign is paused but for a normal flow of campaigns, it will not process any emails after the last batch of subscribers are added.

**Comment by knadh** [comment]
Whoa! Can't believe I missed this race condition @gurramlokesh. Will fix this in the upcoming release.

**Comment by knadh** [comment]
This and a bunch of other SMTP improvements are available in [v0.6.0-alpha](https://github.com/knadh/listmonk/releases/tag/v0.6.0-alpha).
