### ISSUE TITLE
How can I send a test e-mail from localhost?

### ISSUE THREAD

**Issue by laupolo6** [knadh/listmonk#832]
Hi,
I'm new here and I don't know how to configure settings for sending e-mails from my laptop as a localhost to other emails. 
How should I set the settings for this? I mean what "Host", "Port", "username", "password", "Auth Protocol" , "TLS", "Skip TLS verification", etc ?
thank you,

listmonk: v2.1
OS: windows 10 64bit

**Comment by knadh** [comment]
You have to use an SMTP server. You can either install one yourself or use an existing SMTP service provider (Amazon SES, Sendgrid etc.). To test, you could even [connect a GMail SMTP](https://kinsta.com/blog/gmail-smtp-server/).
