### ISSUE TITLE
Allow configuring the URL for the logout button.

### ISSUE THREAD

**Issue by eljobe** [knadh/listmonk#835]
I was able to figure out how to configure [github.com/oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/) to provide a flow in front of the `/admin/*` `/api/*` and `/webhooks/bounce` private endpoints using nginx and oauth2-proxy. In my configuration, I am able to allow members of my Google Workspace domain to login and administer the Admin UI of our shared listmonk instance.

While this does not provide a full-fledged multi-user Roles and Permissions system, it is "good enough" for our needs.

... almost ...

The only part I couldn't figure out how to get working is the "Logout" button. Essentially, if my understanding is correct, clicking this button clears some cookie and redirects the user to the "home" page with the "Login" button.  But, when the user clicks on that page, they are able to click the "Login" button again without authenticating again.

If I could "only" cause the "Logout" button to redirect to the `/oauth2/sign_in` endpoint on the same server, the problem would be solved. That endpoint clears the user's authorized session cookie from the oauth provider and presents the user with the Oauth2 flow entry point again.

I know this works because I can navigate directly to `https://[my.domain]/oauth2/sign_in` and it has the desired behavior. So, I'd really like to just override the behavior of the "Logout" button to direct the user to `/oauth2/sign_in`.

The most simple solution I can think of is, this would be provided as a flag/environment variable that I could provide to influence where the logout button goes. Interestingly, I see calls in the nginx logs to `/api/logout` but they are greeted with a 404 return code. This makes me wonder if I could simply add a handler for `/api/logout` in a local branch of the repo and build a binary from that.  I'll give that a try while I await a response from you.

Also, I tried to configure nginx to simply redirect from `/` to `/oauth2/sign_in` since it seemed like that was where the logout button was dumping users. But, this didn't work for some reason.  My configuration looked like this:

```
location = / {
   return 301 https://$host/oauth2/sign_in;
}
```

The behavior I observed when I had this configuration in place was that I just kept being redirected back to the `/admin/` page. It is possible that I didn't bust enough caches though. I'm aware that CloudFlare, Chrome's chrome://net-internals#dns and even my Mac all have host caches that might be getting in the way of changes to the nginx config.

Sorry for the ramble. Hopefully, you aren't starving for details though.

**Comment by eljobe** [comment]
### Update with Workaround

So, it turns out that it was Chrome's local disk cache that was messing up my nginx redirect. It had cached a previous version of the 301 and that was messing things up. But, using the `Developer Tools > Network` tab in Chrome, was able to isolate the cached redirect and clear the browser cache entry using a right-click.

The next thing to do was to make the Oauth login flow actually redirect to the `/admin` endpoint after successfully logging in instead of staying at the `/` which was just redirecting back to `/oauth2/sign_in` and re-clearing the cookie we *just* got.

That nginx config ended up looking like this:
```
location = / {
    return 301 https://$host/oauth2/sign_in?rd=%2fadmin;
}
```

This has effectively allowed me to get the desired user experience without having to modify the codebase. But, it's definitely not as easy as I would like it to be to configure. So, I'll leave the feature request open and see if anyone is interested in taking it on.

**Comment by knadh** [comment]
Thanks @eljobe. The logout button currently is a hack. The app sends the request to the non-existent `/api/logout` with wrong HTTP BasicAuth credentials, tricking the browser into flushing the BasicAuth session. The app does no session or cookie management.

```javascript
export const logout = async () => http.get('/api/logout', {
  auth: { username: 'wrong', password: 'wrong' },
});
```

In the near future, we should have proper user and session management built into the app. What you've done for now is the correct approach, hijacking `/api/logout` in Nginx and pointing that to your authentication system.
