### ISSUE TITLE
Track view, view in browers not work

### ISSUE THREAD

**Issue by mannm123** [knadh/listmonk#836]
Hello and thanks if you read and respond to this post!
I'm using the project's development mode. Everything is installed and used normally when I build the project on my server
But when I send a campaign, only the unsubscribe function works, but browser view functions, trackview and tracklink are not
It returns a link with full url, campaign id, subscribers but when accessing it forces login and after login it returns 404 error
I don't feel right because when using docker or with binary it works (2 these versions only run on port 9000) but on development version it runs on 2 ports (api runs on port 9000 and the interface runs on port 9000). running on port 8080). I don't know if I installed it wrong or if there is a problem. Here is my installation:
- Download and install the environment, the listmonk project
- Run commands: make dist, make run, make run frontend
- Edit url in settings
Everything still works except for the features I mentioned above, I hope you can check it out and help me out in the future.
Wishing you a lot of health and more success with your project
Thank you so much!

**Comment by knadh** [comment]
>  but browser view functions, trackview and tracklink are no It returns a link with full url, campaign id, subscribers but when accessing it forces login and after login it returns 404

Seems like an incorrect Root URL in `Settings` or an incorrect configuration in the reverse proxy. Please share the links that are asking for login.

**Comment by mannm123** [comment]
Hello and thanks for replying so early
Here is the link to see in the browser when I submit the campaign: https://subs.hcmue.edu.vn/campaign/2597be2d-3fc9-465e-a45b-acd361b42b6b/49933370-6539-4855-becf-b7b11ea33ce7

**Comment by knadh** [comment]
The URL is correct, but the request is being incorrectly re-routed to an admin endpoint.

```
Download and install the environment, the listmonk project
Run commands: make dist, make run, make run frontend
```
You should only do this in the local development environment! For production, please download the appropriate pre-compiled binary from [here](https://github.com/knadh/listmonk/releases/tag/v2.1.0) and just run the binary after extracting it. eg: `./listmonk`. There is no need to run the frontend separately. Everything will be served from :9000.

Also, do you have a webserver that you have configured in front of the app, eg: Nginx? If yes, please share the config.

**Comment by mannm123** [comment]
yeah, it worked!
Thank you so much
