### ISSUE TITLE
Language per campaign / list

### ISSUE THREAD

**Issue by JOduMonT** [knadh/listmonk#838]
ListMonk不是唯一有这种想法的人，但是当我看到像你这样漂亮的软件不能提供双语环境时，我很难过。
我的意思是，我可以选择英语以外的其他语言，这很好，但是如果我想要一个法语的列表，一个英语的列表，一个西班牙语的列表呢？

我知道你会告诉我，只要做2或3个列表，然后在表格/填写中改变语言，但这并不专业。
作为一个用户，你是否曾经在一个不是用你的语言和/或混合2或3种语言的网站上签名？
可能没有；这扰乱了用户的信任。
想象一下，当你收到一封标题和页脚都是外语的邮件时，你会有什么感觉？
你很可能不喜欢它，你会认为它是垃圾邮件或不专业的。所以，对于非英语母语的人来说，这也是同样的事情。

--------
ListMonk ei ole selle mõtteviisiga üksi, kuid see teeb mind kurvaks, kui ma näen, et selline ilus tarkvara nagu teie ei suuda pakkuda kakskeelset keskkonda.
Ma mõtlen, et see on tore, et ma saaksin valida mõne muu keele kui inglise keele, aga mis siis, kui ma tahan nimekirja prantsuse keeles ja ühte inglise keeles ja ühte hispaania keeles?

Ma tean, et te ütlete mulle, et tehke lihtsalt 2 või 3 nimekirja ja muutke vormi/täitmise keelt, kuid see ei ole professionaalne.
Kas te olete kasutajana kunagi loginud sisse veebilehele, kus see ei ole teie keeles ja/või segada 2 või 3 keelt?
Tõenäoliselt mitte; see häirib kasutaja usaldust
kujutage ette, et saate e-kirja, mille päis ja jalus on võõrkeeles; kuidas te end selle pärast tunneksite?
Tõenäoliselt ei meeldiks see teile, te peate seda rämpspostiks või ebaprofessionaalseks. Niisiis on sama asi mitte-inglise keelt emakeelena kõnelevate inimeste puhul.

------

ListMonk is not alone in that way of thinking, but it makes me sad when I see a beautiful piece of software like your not being able to offer a bilingual environment.
I mean, it is nice I could choose another language than English, but what if I want a list in French and one in English and one in Spanish?

I know you will tell me just make 2 or 3 list and change the language in the form/fill, but this is not professional
As a user, did you ever sign in a website where it is not in your language and/or mix 2 or 3 languages?
Probably not; this disrupts the trust of the user
imagine receiving an email with the header and footer in a foreign language; how would that make you feel?
You most likely wouldn't like it, you would consider it spam or unprofessional. So, it's the same thing for non-English native.

**Comment by knadh** [comment]
Hi @JOduMonT. I understand what you're saying, but listmonk does not have multi-user support yet either, which is an important feature. I've been adding features slowly as I can. At some point, we'll get multi-lingual support as well.

Like you said, for now, it is at least possible to hack together multiple lists and forms using APIs and simulate multi-lingual support. There are many other features, like multi-user support, that are just impossible. So it is just a matter of prioritisaton based on time, effort, criticality.

**Comment by approached** [comment]
@JOduMonT 
1. try to create multiple list in different languages
2. add  a userattribute `lang`  to each user
3. change your templates with IF statement

It works great with some customizing.

**Comment by candidexmedia** [comment]
> @JOduMonT
> 
>     1. try to create multiple list in different languages
> 
>     2. add  a userattribute `lang`  to each user
> 
>     3. change your templates with IF statement
> 

This is a great start, although, I wonder if it works for email subject lines as well?
