### ISSUE TITLE
Create a subscriber with no email address

### ISSUE THREAD

**Issue by runningnoodle** [knadh/listmonk#839]
**Is your feature request related to a problem? Please describe.**
I am planning to use Listmonk to send sending both emails and text messages. I want to import some subscribers for which I do not have an email address. I would use Listmonk to send text messages only to those subscribers. However, it is not possible to import or add subscribers to Listmonk without specifying an email address. The workaround I can think of for the current version of Listmonk is to add dummy email addresses to subscribers that don't have one, and immediately add those dummy email addresses to the bounce list.

**Describe the solution you'd like**
I would like Listmonk's API, subscribers import tool and database schema to allow the creation of subscribers while only specifying attributes related to messaging, without an email address or name.

**Comment by knadh** [comment]
Hi @runningnoodle. E-mail is the primary key and primary identifier for users. It would not be possible to ignore it. You can also think of it as a unique identifier in a certain format. For your usecase, phone numbers, you could just do `123456789@sms`, a dummy e-mail like you said.

On empty names, please see this https://github.com/knadh/listmonk/issues/594.
