### ISSUE TITLE
junk signup prevention ideas

### ISSUE THREAD

**Issue by srsquare** [knadh/listmonk#840]
I just realized I originally posted these ideas on a closed issue, so I decided to open a new one.

A few suggestions to better control spam signups. Rather than a captcha which everyone will have a different preference on which one to use & is a pain for end-users....

1) change the honey pot field to type=text and use a CSS class say .hpfld that is set to hidden, most bots these days are smart enough to ignore type=hidden fields but don't parse the CSS yet

2) do something like this script does to validate new emails https://github.com/daveearley/Email-Validation-Tool and maybe have a setting for each check to determine if we want to use that rule or not. I bet you could find a library like this for written in the correct language for example https://github.com/MailboxValidator/mailboxvalidator-nodejs

Also, be nice to have an automated option that could be run, say monthly (setting), to clean the list using the same email validation rules. I am actually planning to do this with PHP via the listmonk API when I have time and do a score based on which rules fail, and if it meets the threshold then id either block or purge that email.

3) Aff a hidden field that is set to the current server timestamp on load and based on the number of seconds from page load to submit have a setting to flag it as spam. For example page load and 3 seconds later is submitted that's a bot, but a 63 seconds later is likely not a bot. If that string is not a Unix seconds timestamp, empty, too far in past or future it fails because it has been changed. The range allowed could be a setting.

4) a check to see if bot, this is far from foolproof since most bot checks are based on data that can be spoofed. If I understand right listmonk is written using go and nodejs so maybe https://pkg.go.dev/zgo.at/isbot

5) deny repeat submissions within x time may be based on IP, a cookie or a session variable, or some combination

6) for those who really want captcha, maybe have 2 settings one for the javascript/html that goes on the form and the other for a function that returns true if captcha past or false if captcha failed & thus not allowing the signup. The community could provide example code for the captcha's we use. You might want one more setting for the error message if captcha failed.

Anyway just a bunch of thoughts, keep up the good work :)

**Comment by knadh** [comment]
Thanks for the suggestions. Apart from the simple honeypot field, and maybe target domain validation, the rest are fairly easily achieved by adding a reverse proxy like HAProxy or Nginx in front of listmonk. Most installations have them already for TLS.

> 1) change the honey pot field to type=text and use a CSS class say .hpfld that is set to hidden, most bots these days are smart enough to ignore type=hidden fields but don't parse the CSS yet

This is already the case.

> 2) do something like this script does to validate new emails https://github.com/daveearley/Email-Validation-Tool and maybe have a setting for each check to determine if we want to use that rule or not. I bet you could find a library like this for written in the correct language for example https://github.com/MailboxValidator/mailboxvalidator-nodejs

Not sure how effective this would be. There's no reason why a bot won't just submit made up e-mail addresses with real domains. This is what's commonly seen. `madeupemail123@gmail.com`

> Also, be nice to have an automated option that could be run, say monthly (setting), to clean the list using the same email validation rules. I am actually planning to do this with PHP via the listmonk API when I have time and do a score based on which rules fail, and if it meets the threshold then id either block or purge that email.

Running bulk DNS validation checks within listmonk wouldn't be practical or scalable unfortunately.

> 3) Aff a hidden field that is set to the current server timestamp on load and based on the number of seconds from page load to submit have a setting to flag it as spam. For example page load and 3 seconds later is submitted that's a bot, but a 63 seconds later is likely not a bot. If that string is not a Unix seconds timestamp, empty, too far in past or future it fails because it has been changed. The range allowed could be a setting.

This would be highly prone to false positives. Browsers autofill e-mail and name fields on pageload, so legitimate users can realistically submit the form in under a second.

> 4) a check to see if bot, this is far from foolproof since most bot checks are based on data that can be spoofed. If I understand right listmonk is written using go and nodejs so maybe https://pkg.go.dev/zgo.at/isbot

This is also highly prone to false positives and blocks non-browser user agents.

> 5) deny repeat submissions within x time may be based on IP, a cookie or a session variable, or some combination

This can be configured in Nginx/HAProxy or other frontend proxies.

> 6) for those who really want captcha, maybe have 2 settings one for the javascript/html that goes on the form and the other for a function that returns true if captcha past or false if captcha failed & thus not allowing the signup. The community could provide example code for the captcha's we use. You might want one more setting for the error message if captcha failed.

I think this is the one feature that we could think of bundling in the core, an optional CAPTCHA. It still isn't straight forward as we may need to think of non-visual CAPTCHA for accessibility.

**Comment by srsquare** [comment]
For captcha, personally, something like recaptcha that does require user intervention would make the most sense to me.

As far as the rest of the items, none of them alone would be sufficient. It would take some kind of scoring system where different checks have different scores and if a certain level score is reached then it's considered bad. Nothing is foolproof, but id think something that uses multiple methods would have fewer false positives than any single check could.

**Comment by simonwiles** [comment]
> > 1. change the honey pot field to type=text and use a CSS class say .hpfld that is set to hidden, most bots these days are smart enough to ignore type=hidden fields but don't parse the CSS yet
> 
> This is already the case.

This was puzzling me, so I just want to note here that this works for the public subscription page (if enabled), but generated HTML form code for external pages doesn't have this improvement, and makes no mention of it (was confusing me as I have the main public subscription page disabled).  Gonna make the amendments manually in my external page, and hope that it helps (have *lots* of spam signups...).  Thanks!

**Comment by NicoHood** [comment]
How does the form code need to look like? I'd like to add this, if possible

**Comment by knadh** [comment]
@simonwiles ah yes. This can be added to the generated form code as well. Will do.

**Comment by knadh** [comment]
> This can be added to the generated form code as well.

https://github.com/knadh/listmonk/commit/ed8d68bd54c99943d0b1c40015e2097bd53d3ed9
