### ISSUE TITLE
Seeing HTML sections border lines while using Raw HTML content type

### ISSUE THREAD

**Issue by sheesetfs** [knadh/listmonk#841]
**Version:**
 - listmonk: 2.1.0
 - OS: Ubuntu 20.04 LTS

**Description of the bug and steps to reproduce:**
When I copy and paste the HTML code I've created elsewhere into the Raw HTML content section, it shows border lines. The same code if viewed in a browser is fine, but when imported and sent from Listmonk, shows the borders.

To replicate issue, copy HTML code that you've designed elsewhere and in the content section change input type to **Raw HTML** and paste code. If you preview the design, you should be able to see the artifacting.

**Screenshots:**
Browser view
![Browser view](https://user-images.githubusercontent.com/95902354/174437107-c5bcd553-00b3-457f-9a4c-17c3c80678c2.png)

Email view
![Email View](https://user-images.githubusercontent.com/95902354/174437119-1d5c685b-5d27-496c-8fdd-02a5df1027d9.png)

**Comment by Mattifyed** [comment]
Could you share your HTML? This seems more like broken CSS than anything else.

**Comment by sheesetfs** [comment]
The HTML code can be found here: [https://pastebin.pl/view/f675932c](https://pastebin.pl/view/f675932c)

It's not only this HTML, I've pasted different HTML codes and still getting the issue.

**Comment by Mattifyed** [comment]
I'm guessing this is HTML generated by a WYSIWYG editor of transpiled from something like MJML? Could you try writng the HTML on your own for the same template? Your HTML now is 2k lines, which is a lot more than what it should be and this could also be causing either the cellspacing or the border-collapse styles to break.

**Comment by sheesetfs** [comment]
> I'm guessing this is HTML generated by a WYSIWYG editor of transpiled from something like MJML?

Yes, most probably it was generated by a WYSIWYG editor. I downloaded it off Envato Elements. 

> Could you try writing the HTML on your own for the same template?

I can do that for one of the campaigns, but our marketing team normally selects a template off Envato and build upon it; so this process is not feasible (in the long term).

> Your HTML now is 2k lines, which is a lot more than what it should be and this could also be causing either the cell spacing or the border-collapse styles to break.

What would be the suitable length for the HTML code for it not to have issues? Also, that was just a template and we cut out a large portion of it. We've faced the same issue with lesser lines of code as well (lines of code< 300).

But, if the same HTML code is viewed on a browser directly, it loads fine. Once Listmonk processes it, the lines appear.

**Comment by Mattifyed** [comment]
> What would be the suitable length for the HTML code for it not to have issues? 

That was an off-hand comment on my part about the length of the code. Listmonk doesn't have a limit on the length of your code.

>I can do that for one of the campaigns, 

This would help confirm if the HTML itself is the issue.

> our marketing team normally selects a template off Envato and build upon it; so this process is not feasible (in the long term).

You'd simply have to look from someone on Envato who writes cleaner HTML. :-) I have had the same experience with WYSIWYG editor generated HTML in the past and not just on listmonk.

Also, one more thng you could do here is, if you have a template saved on listmonk that is applied on top of the content (templates on admin/campaigns/templates), you could check to see if there are conflicting styles.

**Comment by knadh** [comment]
> if you have a template saved on listmonk that is applied on top of the content (templates on admin/campaigns/templates)

Yes, please the template you're picking in Admin -> Campaigns -> Templates.

listmonk on its own does not touch styles in campaigns or templates, so this definitely has to be particular to the HTML+CSS you're pasting or its interaction with the default template you've saved.

**Comment by sheesetfs** [comment]
Thanks, **Mattifyed** & **knadh**, the issue was due to conflicting CSS in the admin template. Cloned the default template and modified it, and the issue was resolved.
