### ISSUE TITLE
Campaign analytics not working/displaying properly

### ISSUE THREAD

**Issue by sheesetfs** [knadh/listmonk#842]
**Version:**
 - listmonk: v2.1.0
 - OS: Ubuntu 20.04 LTS

**Description of the bug and steps to reproduce:**
- Context: I sent out an email campaign on June 14th to a list containing ~3000 subscribers, out of which ~1800 were sent as per Amazon SES. The remaining failed due to hitting the max concurrent sending limit (which I've fixed by updating the concurrency & message rate). Immediately after, I could see the number of clicks and views rise while the campaign was being sent. But once the campaign finished, the analytics wasn't loading properly.

- Issue: In "All Campaigns", I can see that _Views: 532_ & _Clicks: 330_; but on the "Analytics" page, _Views: 2_ & _Clicks: 0_. I've tried changing the dates, access the Analytics page to select the campaign manually; but it didn't work.

**Error in browser console:**

`Error: <text> attribute dx: Expected length, "NaNpx".
(anonymous) @ main.445186fc.js:3
`

**Screenshots:**

Campaign page
![chrome_eUgnyrv4Ym](https://user-images.githubusercontent.com/95902354/174493186-f52c768a-38fa-417a-93e8-c702f26c0e0e.png)

Analytics page
![listmonk tfsbs com_admin_campaigns_analytics_id=7](https://user-images.githubusercontent.com/95902354/174493197-0168005e-f0eb-4e56-af0c-008634ec4655.png)

**Comment by knadh** [comment]
This issue could be related to this open bug https://github.com/knadh/listmonk/issues/712

**Comment by knadh** [comment]
Closing this and tracking this in #712.
