### ISSUE TITLE
turn on extra logging for figureing out smtp issues

### ISSUE THREAD

**Issue by kymwatts** [knadh/listmonk#845]
Hi there,

Is there a way to turn on additional logging?
Im trying to debug why the 2 instances of list monk  (v2.0.0 & v2.1.0)will not send any emails and im not getting anything in the logs other than:
```
2022/06/21 19:16:35v2.1.0 (0ecfb89 2022-02-12T15:27:45Z)
2022/06/21 19:16:35reading config: config.toml
2022/06/21 19:16:35connecting to db: <withheld>:5432/listmonkdb
2022/06/21 19:16:35media upload provider: filesystem
2022/06/21 19:16:35loaded email (SMTP) messenger: blah@<withheld>@smtp.dreamhost.com
```

I have tried setting up subscribers that are both in our organization and a gmail one, but neither get the opt in email or the test emails in v2.1.0.

what can i do to further debug this?

Thanks

**Comment by knadh** [comment]
Hi @kymwatts. Any error or issue anywhere in the e-mail path is logged. If there's nothing showing in the logs, that means the SMTP connection was successful and the e-mail was pushed to it as well. Just to be sure, could you maybe set an incorrect password for SMTP and try and send a test mail? That should show up in the log.
