### ISSUE TITLE
Build a list based on a filter 

### ISSUE THREAD

**Issue by tttp** [knadh/listmonk#846]
Hi, I see on the end user documentation that it's possible to query subscribers to export them

![image](https://user-images.githubusercontent.com/128426/174942468-1e1e0598-521c-4676-a3f0-2fa965bb3b09.png)

would it be possible to do the same with the API and (main need) to use that to build new lists?

The aim is to automatically segment one big list based on the language of the subscriber to have multiple lists language specific

**Comment by knadh** [comment]
1. Create a new list.
2. Write a query to segment subscribers (like in the above screenshot).
3. Click on the selection checkbox in the table header to reveal the "Manage lists" option. Then bulk add the selected, segmented subscribers to your preferred lists.

**Comment by tttp** [comment]
sorry, I wasn't clear: is this possible to do these steps via the API already? I looked at the doc and didn't find options to query via sql, or bulk add the result

I might be easier to download the list, segment on the client side and build upload, but for privacy reasons, I'd rather not having to download/upload emails and other personal information if I can prevent it

**Comment by knadh** [comment]
Yes, indeed. Just realised that this needs to be documented. There are several APIs for bulk subscriber management. For now, you can also inspect (browser network tools) the API queries sent by the UI and send those requests as-is. The UI uses the exact same APIs.

Add/remove/unsubscribe subscribers to one or more lists by a query expression.

```
PUT /api/subscribers/query/lists

{
   "query": "your-segmentation-query",
   "target_list_ids": [1,2,3],
   "action": "add|remove|unsubscribe"
}
```
