### ISSUE TITLE
Welcome message/subscriber webhook

### ISSUE THREAD

**Issue by emacsen** [knadh/listmonk#848]
I'd like to send new subscribers a welcome message- distinct from the double opt-in confirmation.

I don't see a way to do this through the UI, so I thought I could do so as a webbook when someone subscribes, that I can't see that option either.

Is this an option?

**Comment by koss822** [comment]
It is doable even now, I do it through postgres event listener in NodeRed - details here [Listening for Listmonk Subscriber Confirmations in Node-RED via Postgres LISTEN/NOTIFY ](https://martinkonicek.eu/archive/listmonk-nodered-listen-tutorial/)
