### ISSUE TITLE
Adding a new list to a subscriber marks existing confirmed lists as unconfirmed

### ISSUE THREAD

**Issue by gurramlokesh** [knadh/listmonk#85]
If we try to add a new list to the subscriber who is already part of confirmed list(s), it marks them as are unconfirmed as well.

This query is updating any existing list as unconfirmed. 
https://github.com/knadh/listmonk/blob/56122c0bfe9d1efe70d4b48a04b3ac48b8743ba9/queries.sql#L108-L130

Not sure if this is a feature or bug :)

**Comment by thejaswinipathi** [comment]
Raised a PR https://github.com/knadh/listmonk/pull/84

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/pull/84 fixes this.
