### ISSUE TITLE
Can I use this library to build a closed source commercial service ? 

### ISSUE THREAD

**Issue by haikyuu** [knadh/listmonk#850]
I read a bit about AGPL, and I think the answer is no. But I'd like to hear from more knowledgeable people if it's possible or not. 
If i change the source code, i will open source it. But i don't want to open source other softwarw that talks to this via API for example 
Thanks

**Comment by knadh** [comment]
There is no restriction to building commercial services using AGPL code. AGPL stipulates that the necessary artifacts (script, config, code etc.) required to run the program should be open sourced. If you use listmonk unmodified, as-is, it is already available to everyone in the exact same manner. If you make changes to listmonk, then those changes, and the dependencies (including network) that may be required by these changes, have to be open sourced.

That is, there should be no problem in offering commercial hosting of unmodified listmonk.

**Comment by haikyuu** [comment]
Thank you for the answer.
Let me give you an example.

Say I am building an app that would let its users (say cooking content creators) manage their audience.

 I create custom email templates for them to use and add the ability to include a recipe in emails.

Afterwards I will add some automation like convertkit.

And there are other features in my service like creating a recipe and recipe videos.

And I want to have a different UI for managing an audience and sending emails.

Which of these things do I need to open source?

**Comment by knadh** [comment]
Disclaimer: Not qualified to give legal advice. 

It sounds like you'll have other systems that generate HTML templates that get pasted into listmonk and sent out. This is how pretty much how all listmonk instances run anyway. I don't think these external systems have to be open sourced (although it would be nice).
