### ISSUE TITLE
Issues with CSV import

### ISSUE THREAD

**Issue by jeff-h** [knadh/listmonk#859]
**Version:**
 - listmonk: v2.1.0
 - OS: Docker on Ubuntu

**Bug 1: Import fails:**

Attempting to import from CSV is failing for me consistently when the import contains the same email address as an existing user.

<img width="844" alt="image" src="https://user-images.githubusercontent.com/841871/176645066-fb6303af-d0dc-4361-a2f8-697f71f4dcca.png">

My working test CSV looks like this:

```
email,name,attributes
user2@abcdefghijklmn.com,"User Two",
user3@abcdefghijklmn.com,"User Three",
```

but as soon as I include an email address that is already in the database, it fails.

**Bug 2: Stop import button:**
I have to click the "stop import" button multiple times before it returns me to the Import subscribers page. Then the next CSV import I attempt results in a "stop request received" — I'm guessing one of the previous "stop" button clicks is hanging around?

The first click changes the label to "stopping", but it never returns to the main Import page until it's clicked a second time (I waited quite a long time to confirm this).

<img width="845" alt="image" src="https://user-images.githubusercontent.com/841871/176644888-eb0c8428-71c7-48a7-8fc7-1e23a816bc60.png">

**Comment by knadh** [comment]
Sorry, I missed this issue.

> but as soon as I include an email address that is already in the database, it fails.

Do you get an error? I used the CSV you shared and imported it multiple times without any failures. The importer is specifically built to work with entries that already exist in the database. The "Overwrite" toggle controls this behaviour.

**Comment by jeff-h** [comment]
No errors logged anywhere that I could see (I checked the docker container logs also) — it just stalls on the first screenshot above.

**Comment by knadh** [comment]
Would you be able to check the browser's console's network log to see if there are any requests with 500 errors? Have not seen this behaviour before and unable to reproduce this even with large files.

**Comment by jeff-h** [comment]
Wow, that's frustrating. I have just tried half a dozen or so times to replicate the previous issue but couldn't. At the time I did check the javascript console for any logs but saw nothing relevant there, but unfortunately I didn't think to check the Network requests — I will definitely do so if I see this again.

Sorry for the noise, and thanks for all your work on listmonk, it's fantastic!

**Comment by yomanmo** [comment]
Hey, I am having this issue.  There are no console errors.  Here are the har files for the requests, its sending thousands of them constantly.  There are no relevant logs in the settings menu, nor in the docker logs. Fresh install by the way, I deleted the default subscribers and added a connection to amazon ses, nothing else.   Thanks in advance, this seems like a pretty awesome project.  Merry Christmas.
[a.zip](https://github.com/knadh/listmonk/files/10299793/a.zip)
