### ISSUE TITLE
Emails cannot be sent with Amazon SES SMTP - "error sending message in campaign [...] subscriber [...] EOF"

### ISSUE THREAD

**Issue by louistiti** [knadh/listmonk#861]
Hi, thanks for providing such useful and complete service.

**Version:**
 - listmonk: `2.1.0` - `master` branch cloned from 2022-07-05
 - OS: Ubuntu 22.04

**Description of the bug and steps to reproduce:**
 I'm trying to use Listmonk from my local environment first before to use it on a remote server.
- I have created SMTP credentials for Amazon SES and I have set them up via the Listmonk configuration.
- I tried by using the port `25` and `465` and also with the `LOGIN` and `CRAM` auth protocol.
- When I hit the "Send" button, a success message shows up saying "A new campaign to try Listmonk" updated"
- None of the email are sent and the logs show:
```
2022/07/06 00:26:01start processing campaign (A new campaign to try Listmonk)
2022/07/06 00:26:01campaign (A new campaign to try Listmonk) finished
2022/07/06 00:26:32error sending message 'Finished: A new campaign to try Listmonk': EOF
2022/07/06 00:26:32error sending message in campaign A new campaign to try Listmonk: subscriber c12965bb-40cb-4de3-a97c-b6729232b884: EOF
```

Please note that I'm still in sandbox for Amazon SES, but I have whitelisted the email address so the email should be sent correctly. Let me know if you need further information.

**Screenshots:**
![image](https://user-images.githubusercontent.com/1731544/177373014-1c8d9736-21a8-4883-af8f-77ffb2ca8cef.png)
![image](https://user-images.githubusercontent.com/1731544/177373444-41af4d17-fd99-4799-a8d3-7a53526a8815.png)
![image](https://user-images.githubusercontent.com/1731544/177373670-7ac50d15-e762-4211-9056-8a6968402861.png)
![image](https://user-images.githubusercontent.com/1731544/177373915-0d459164-ec66-4e9b-b02b-fd986e2f2a05.png)
![image](https://user-images.githubusercontent.com/1731544/177374028-1d14f8f3-805f-4c2b-94c6-1aa1f4e40976.png)
![image](https://user-images.githubusercontent.com/1731544/177374510-2755b038-cf51-482f-bb9b-b9114b191d87.png)

**Comment by knadh** [comment]
The error clearly says that you haven't configured a valid "from" address. Please configure it in Settings -> General.

**Comment by louistiti** [comment]
> The error clearly says that you haven't configured a valid "from" address. Please configure it in Settings -> General.

Yes I haven't configured it from the settings, but I set it up during the campaign sending inside the "from" address field. So I felt the error message is misleading as the email correctly went through with the right "from" address. It has overwritten the default settings. Maybe a warning message could be more appropriate in this case. Just suggesting :smile:
