### ISSUE TITLE
Complete Setup Guide for Binary

### ISSUE THREAD

**Issue by itzomen** [knadh/listmonk#862]
The installation steps are pretty straight forward but they are not complete, especially for beginners:

## 1 [Installation Docs](https://listmonk.app/docs/installation)
I was able to get Listmonk up and running in 2minutes

### Questions
- How do we log in when the password is empty? e.g http://news.it-zt.at/ the pop up appears and disappears
- How is the Media upload provider configured?
- How is the SMTP server configured?

## 2 Issue #778
This issue outlines the major steps to deploy to your own server.

### Questions
- Any other considerations for the production environment?

Links to other issues can be added or I could update the installation guides once we have all the setups instructions

**Comment by knadh** [comment]
> How is the Media upload provider configured?
> How is the SMTP server configured?

These, and everything else, are on available on the admin UI that you see when you login. For example, with SMTP, you just have to copy-paste the config your SMTP host provides.

**Comment by itzomen** [comment]
Thanks for your prompt reply.
Yeah the login works with Mozilla Firefox

**Comment by MaximilianKohler** [comment]
> For Windows, you can look for tutorials for running an EXE as a background service. With the terminal window open, you're running the app in the foreground which, when you close the terminal, is killed.

And for linux we have to set it up as a service? Eg https://github.com/knadh/listmonk/issues/843 ?
