### ISSUE TITLE
Export who opened a campaign

### ISSUE THREAD

**Issue by pucilpet** [knadh/listmonk#864]
**Is your feature request related to a problem? Please describe.**
Not a problem per se, but related to a usual workflow.

I would like to export people who have opened (and the opposite - who have not opened) a campaign and import the subscribers to a new list (or a segment, if segments are added to listmonk).

It would be very useful to send a campaign to people who didn't open the previous message.

+ I think some people would like to export people who clicked/didn't click, too.

**Describe the solution you'd like**
Export people who didn't open/opened or didn't click / clicked a campaign. Export to CSV and/or straight to a new list.

**Comment by knadh** [comment]
You can already do this with SQL expressions in advanced subscriber query. Go to Admin -> Subscribers -> Advanced query and run the following query. It'll list the subscribers who don't have a view registered from a particular campaign. The results, you can export, or directly add to a new mailing list.

```sql
subscribers.id NOT IN (SELECT subscriber_id FROM campaign_views WHERE campaign_id=1)
```

PS: Replace the campaign_id value with your campaign's id.
