### ISSUE TITLE
No spellchecker in campaigns rich content editor

### ISSUE THREAD

**Issue by nkosi23** [knadh/listmonk#865]
**Version:**
 - listmonk: 2.0.0
 - OS: FreeBSD

**Description of the bug and steps to reproduce:**
When editing a campaign using the rich content editor, my web browser (Google Chrome) does not provide any spellchecking. This has always been the case since I started using listmonk (early this year or late last year). This is tricky since very often trivial typos can be difficult to identify so I need to copy-and-paste the campaign in a different application.

**Comment by knadh** [comment]
This was added earlier (https://github.com/knadh/listmonk/issues/786) and will be available in the upcoming release.
