### ISSUE TITLE
queries for update several users and select from multiple lists

### ISSUE THREAD

**Issue by badta5te** [knadh/listmonk#866]
Hello, I have 2 questions:
Question 1:
Is there a way of adding attributes to existing contacts in the list without overwriting the contacts and using the upload feature. Too risky to use overwrite, it needs to be additive.
Ideal situation: Query a portion of the list, add an attribute without overwriting other attributes.

Question 2:
Can we do queries and list management functionality across lists or are we confined to a single list at a time? i.e. Can we pull a query of how many people are on two different lists and then export whoever matches?

**Comment by knadh** [comment]
1) Merging attributes isn't possible in the importer currently. If there are strong usecases, we could consider adding this.

2) Yes, this is possible. Sample:

```sql
subscribers.id IN (SELECT subscriber_id FROM subscriber_lists where list_id=ANY('{1, 2, 3}') )
```

**Comment by badta5te** [comment]
1. Get it.
2. I need something similar to intersection, like a list of users which are in several different lists.
