### ISSUE TITLE
Configuring database port using environment variables

### ISSUE THREAD

**Issue by iwatakeshi** [knadh/listmonk#867]
Hi, is there a way to change the database port using [environment variables](https://listmonk.app/docs/configuration/#environment-variables)? For context, I'm trying out listmonk by deploying it to Digitalocean using their App platform since they support Docker. However, their managed database [doesn't allow us to change the port](https://www.digitalocean.com/community/questions/database-by-default-has-a-port-25060-i-want-to-change-it) so I thought to ask if I can do so through listmonk. 

I understand that it's not the official way to setup listmonk, but I thought to give it a try.

Thank you.

**Comment by iwatakeshi** [comment]
I think I found the [answer](https://github.com/knadh/listmonk/issues/719) I was looking for. However, it's not shown in the docs. I'll try to contribute when I find the time. Thank you.

**Comment by knadh** [comment]
Hi @iwatakeshi. This is in the docs https://listmonk.app/docs/configuration/#environment-variables

**Comment by iwatakeshi** [comment]
Hi @knadh. I looked again (with `ctrl + f`), but I'm not finding the keyword `port` in the docs:
 
The variable that I'm referring to is `LISTMONK_DB__PORT` and this is what I'm seeing:

![env-docs](https://user-images.githubusercontent.com/1505448/179060726-3556e51d-6407-4e80-826c-e22ecd6677f1.png)

**Comment by iwatakeshi** [comment]
I just created a pull request. Let me know if there's anything else I'm missing. Thank you.
