### ISSUE TITLE
Todo: Better widgets on dashboard

### ISSUE THREAD

**Issue by sachinmk27** [knadh/listmonk#88]
Hi, would like to contribute to this project. Under todo items, better widgets on dashboard has been mentioned. Can you please spec it out in some detail ?

**Comment by knadh** [comment]
Thanks. Actually, please feel free to come out with a spec yourself. Right now there are a couple stock widgets that show views and clicks on the dashboard. Eventually, there should be a reports page where it should be possible to select one or more campaigns and get visualisations.
