### ISSUE TITLE
Bind issues with installer

### ISSUE THREAD

**Issue by BCW52** [knadh/listmonk#880]
Latest version from git clone 
Ubuntu 20.04 latest

ERROR: for listmonk_app  Cannot start service app: driver failed programming external connectivity on endpoint listmonk_app (ef3388fe56359219bd8293eceaab2c269530d312f8eedf2de566c7702403c270): Error starting userland proxy: listen tcp4 0.0.0.0:9000: bind: address already in use

ERROR: for app  Cannot start service app: driver failed programming external connectivity on endpoint listmonk_app (ef3388fe56359219bd8293eceaab2c269530d312f8eedf2de566c7702403c270): Error starting userland proxy: listen tcp4 0.0.0.0:9000: bind: address already in use

**Comment by knadh** [comment]
Looks like you already have instances of the app running as the error message indicates (or there is another app running on port :9000). Try `docker ps` to see if listmonk is already running and stop any running instances.

Finally, run `docker-compose up db app`. The link you shared does not seem to be running `db` but only `app`.

**Comment by BCW52** [comment]
![image](https://user-images.githubusercontent.com/91522369/179371822-1f06f7b4-02a8-4ace-9379-9dc11fa19a79.png)
![image](https://user-images.githubusercontent.com/91522369/179371829-28cc6f73-821f-4f0d-bed4-992bf53195c9.png)


Using mailcow
smtp port 71
https port 971

**Comment by knadh** [comment]
Looks like your SMTP settings are incorrect. If you've TLS/SSL running on port 971, you've to turn that on. Maybe it's STARTTLS. Please try changing the settings to suit your mailserver's config.

**Comment by BCW52** [comment]
Can you suggest me which one should I use? SSL TlS or StartTLS

**Comment by knadh** [comment]
I wouldn't know. That depends on your SMTP server. You can try both and see which one works.
