### ISSUE TITLE
Sending Testmail from SMTP-Settings

### ISSUE THREAD

**Issue by Galileon-venta** [knadh/listmonk#881]
The workflow for setting up/changing the SMTP-Servers could be massively improved by adding an option to send a Test-Email from the configuration view directly.

**Comment by knadh** [comment]
This was merged last week https://github.com/knadh/listmonk/commit/ee448170ef9ae8f315f6e55316b3f36e33fe2561. Available in the upcoming release.

![image](https://user-images.githubusercontent.com/547147/179358649-781964be-5dad-463d-bf2d-2fc19e480212.png)
