### ISSUE TITLE
Does subscriber name have to be optional?

### ISSUE THREAD

**Issue by eljobe** [knadh/listmonk#883]
**Is your feature request related to a problem? Please describe.**
I would like to require that subscribers provide a name when they are filling in my subscriber form.
Primarily this is because we also use our listmonk database as the primary storage for all of the contact information for members of our club. It's more difficult if we have to send and email to the subscribers who don't provide a name asking them, "Who are you?"

**Workaround**
I know we can make our own subscription form and ensure that the user has provided a name (with javascript) before allowing them to submit the form.

**Describe the solution you'd like**
I'd prefer if it were possible to toggle a setting "Require Subscriber Names" which would mean that `{{ public.subName }}` would not say "Name (Optional)" but just "Name" and the form would verify that a name was provided in the same way the email field is currently verified.

**Comment by knadh** [comment]
Hi @eljobe 

1) You can customize the form and all other public pages by loading [custom static templates](https://listmonk.app/docs/templating/#system-templates).

2) Easier, change the input behaviour using Javascript. The following snippet pasted in Settings -> Appearance -> Public -> Custom Javascript works.

```javascript
const n = document.querySelector('.form input[name="name"]');
n.placeholder = "Name"
n.required = true

n.previousElementSibling.innerText = 'Your name';
```

**Comment by eljobe** [comment]
Those are both pretty good workarounds, but I think they both don't play well with i18n. This isn't really a concern for me, but I imagine other users will run into those snags.

**Comment by knadh** [comment]
Yep, the i18n choice will require the JS to be tweaked slightly. However, given that + the following, there are enough available options.
- The entire static template can be customized.
- It's possible to use APIs to easily build a custom form.
