### ISSUE TITLE
stack loading running camp

### ISSUE THREAD

**Issue by MojtabaMahdian** [knadh/listmonk#887]
I have a problem with campaign list, if we have more than 5000 items in campaign and when status was changed to running my dashboard and items stay on loading running and status doesn't change to finished.

![nn](https://user-images.githubusercontent.com/40137787/180602381-d9ecffbd-7992-4d64-9186-eea3c56b336f.png)

**Comment by knadh** [comment]
5000 concurrent campaigns? :exploding_head: It most likely is a resource constraint (number of CPU cores, RAM, Postgres setup). You'll have to debug this yourself.

That said, listmonk is a newsletter manager. A few running campaigns at a time is natural, but 5000 concurrent campaigns, pretty sure no newsletter manager is ideal for that. You'll probably have to handroll your own message queues!
