### ISSUE TITLE
Send-once feature

### ISSUE THREAD

**Issue by mohamed--abdel-maksoud** [knadh/listmonk#888]
**Is your feature request related to a problem? Please describe.**

I have a use-case where, to not spam users, we want to send them an email about a product *exactly once*.

**Describe the solution you'd like**

I'd love to have an optional field in every campaign (e.g. "Send once key" for the lack of a better name) which, when set, will make sure any subscriber who received an email with that key in the past should be excluded from the campaign.

Many thanks for this project!

**Comment by NicoHood** [comment]
I like the idea, but isnt that more an email marketing feature where you send new subscribers specific emails based on different circumstances? That does not sound right for a simple newsletter software, that is a whole email marketing feature, right?

**Comment by knadh** [comment]
Agree with @NicoHood. This sounds like an automation feature that systems like Mautic are more suitable to doing. Not natural to a mailing list manager.

**Comment by mohamed--abdel-maksoud** [comment]
I believe this feature is on a lower level than what Mautic (or similar) offers.

The feature provides strong guarantee from listmonk (as the owner of outbox functionality) that no subscriber will be spammed twice about the same topic. I didn't see this implemented anywhere.

I understand if it is a priority though, I will fork the repo and add it because I need it urgently.

**Comment by NicoHood** [comment]
I dont see why you cant do this with an email automation software. Listmonk is not the right spot for this.
