### ISSUE TITLE
How to add or remove a subscriber to a list with the REST API

### ISSUE THREAD

**Issue by amirouche** [knadh/listmonk#889]
I would like to add or remove subscribers from a list.

I looked at https://github.com/knadh/listmonk/issues/237 hence `PUT /api/subscribers/:id` but it is unclear how to add, or remove a subscriber from a list. I also looked at [`PUT /api/lists/:id`](https://listmonk.app/docs/apis/lists/#put-apilistslist_id) too, but it does not support my usecase.

It appears there is no way to manage subscriptions using the API. What I am doing wrong?

**Comment by knadh** [comment]
```shell
curl 'http://localhost:9000/api/subscribers/1' -X PUT -H 'Content-Type: application/json' \
	--data-raw '{"email": "blah@blah.com", "lists":[1, 2, 4, 5]}'
```

^ Same API. It's a bit awkward that the e-mail field has to be passed. Will look into changing this behaviour.

There's also a bulk list management API where you can change list subscriptions for multiple subscribers at once.

```shell
curl 'http://localhost:9000/api/subscribers/lists' -X PUT -H 'Content-Type: application/json' \
	--data-raw '{"action":"add", "target_list_ids":[1, 2, 3, 4], "ids":[100]}'
```

`action = add | remove | unsubscribe`

**Comment by sid-talesara** [comment]
can you guide it in detail, on how to run API in the POST method with email and name parameters? 
I tried to run this POST API in postman but couldn't able to add a new subscriber.

![image](https://user-images.githubusercontent.com/95763376/180944295-8cf4c81f-c0c6-459e-baf0-7957ee63d639.png)

**Comment by sid-talesara** [comment]
@knadh

**Comment by amirouche** [comment]
It does not work as expected:

```python
In [13]: requests.put('http://localhost:9000/api/subscribers/1', data={'email': 'john@example.com', 'lists': [1, 2, 3, 42]})
Out[13]: <Response [200]>

In [14]: _.json()
Out[14]: 
{'data': {'id': 1,
  'created_at': '2022-07-26T07:48:28.901164Z',
  'updated_at': '2022-07-26T08:56:45.256006Z',
  'uuid': 'af998463-fcd8-4828-9c17-8a3cf81da417',
  'email': 'john@example.com',
  'name': 'John Doe',
  'attribs': {'city': 'Bengaluru', 'good': True, 'type': 'known'},
  'status': 'enabled',
  'lists': [{'subscription_status': 'unconfirmed',
    'id': 1,
    'uuid': 'dc01942e-b935-4a91-a5e9-edb0529390cd',
    'name': 'Default list',
    'type': 'private',
    'optin': 'single',
    'tags': ['test'],
    'created_at': '2022-07-26T07:48:28.899954+00:00',
    'updated_at': '2022-07-26T07:48:28.899954+00:00'}]}}

In [15]: 

```

**Comment by sid-talesara** [comment]
http://sendn.labourlawadvisor.in:9000/api/subscribers/1', data={'email': 'john@example.com', 'lists': [1]}

{
    "message": "Invalid ID(s)"
}
![image](https://user-images.githubusercontent.com/95763376/180974577-e39615fb-0f54-47df-9e0c-4328b493a23e.png)

**Comment by knadh** [comment]
Hi @sid-talesara . I'm not familiar with Postman. You'll have to figure out how to translate that curl call to Postman. It's a simple HTTP call.
