### ISSUE TITLE
Tracking Issues for Todos

### ISSUE THREAD

**Issue by bramvdbogaerde** [knadh/listmonk#89]
First of all, thanks for this nice piece of software. 

I would like to contribute to the project, more specifically, I would like to help
out with the authentication/authorization part, as these features are for my use cases
quite important.

As mentioned in #88 it is not very clear what the desired elements are for each
of the todos. Most of the topics presented in that section are also quite big so I think
it would be good idea to have a tracking issue for each of them, in which the specification can
be discussed and where the topic can be subdivided into more tasks, which will make 
it easier for other people to contribute, see what things need to be done, and on
which things other people are already working.

As for an example of how this could look, I would like to refer to the tracking issues for RFC's in the Rust repository. I do not think that it is necessary to go to that level of verbosity, however I think an overview with checkboxes (for subtasks) and references to pull requests (for tracking progress on that specific task) can be useful.

**Comment by knadh** [comment]
Thanks @bramvdbogaerde. There definitely needs to be a proper structured to-do. Just that I haven't had the time to start one. Maybe you could kick start a Wiki page with some ideas?

With auth, I've looked at a few popular Go libs (authboss?), but they seem overly complex. I'd infact started writing a simple, generic auth provider for this. Roughly, the idea is:
- Auth with username + password and OAuth.
- Granular permissions per user. This can be implemented at the handler level easily. Eg, if the permission is "api.campaigns.DELETE", it can be easily checked in a auth handler by checking the request URI `DELETE /api/campaigns`.
- List permissions. Not sure how exactly this could be done (the SQL query feature may have to be disabled for such users), but would be nice to be able to let certain users manage certain lists.
- The permission list can be loaded on the frontend and UI elements toggled on/off.

**Comment by bramvdbogaerde** [comment]
The ideas for the authentication sound good, I like the idea of a generic auth provider that can be extended with other authentication mechanisms in the future (such as LDAP, which we use at our organization to manage users). 

Is this generic auth provider already in the code base? I did not yet dive in the code too deep, but I plan to do so in the future.

As for the Wiki page, I would very much like to help out, but I will familiarize myself with the code base first.

**Comment by knadh** [comment]
Cheers. The auth provider isn't in the codebase. I have a very initial draft on it locally. Will try and give it some structure and upload it.

Yes please! Would greatly appreciate an active collaboration :)

**Comment by cb3inco** [comment]
Would love to see SAML for authentication too!

**Comment by bramvdbogaerde** [comment]
Hi @knadh, did you manage to find some time to upload your initial draft for the auth provider somewhere? Contributors might then be able to draw some inspiration from it :)

**Comment by knadh** [comment]
@bramvdbogaerde I haven't had a chance to make it *compilable*. Been working on it on and off. I'll try to get it to alpha and upload soon.

**Comment by bramvdbogaerde** [comment]
I am sorry to bother you with it again. But can I already find your initial draft somewhere?

I would really like to help with this, but I would like to see what you have in mind first, before putting 
too much effort into something that would not really fit into the projects vision.

**Comment by knadh** [comment]
https://github.com/knadh/tinyauth -- this is more pseudo code than anything else.

**Comment by bramvdbogaerde** [comment]
Great! Where would be the best place to discuss it?

**Comment by knadh** [comment]
We can discuss here: https://github.com/knadh/tinyauth/issues
