### ISSUE TITLE
Per-list default from address option

### ISSUE THREAD

**Issue by flergbarn** [knadh/listmonk#890]
Listmonk lets us set up a default 'from' email address in `Settings`, and to change the from address on individual campaigns. This is great, but it means that transactional emails (subscription opt-in, etc) for all lists are sent from the same default address specified in `Settings`.

If we have multiple lists that we send emails to from addresses in different domains (eg. _List A_ emails come from noreply@_lista.com_, and _List B_ emails come from noreply@_listb.com_), it would be better if all subscription opt-in emails for _List A_ could be sent from, for example, noreply@_lista.com_, and opt-in emails for _List B_ from noreply@_listb.com_.

This might also help with some deliverability issues, since a newsletter coming from the same domain or email as the initial opt-in email might be less likely to land in spam, as it has been interacted with by the recipient already.

**Describe the solution you'd like**
Each list, in its `Edit settings` screen (where we set the list type, opt-in, and tags), should have the ability to specify a default from address for that list. All transactional emails dealing with that list (opt-in messages, etc) would then be sent from that email, and this email would also be the default 'from' address' for all campaigns sent to that list (when using the `Send Campaign` button in the list view).

**Comment by knadh** [comment]
The new tx (transactional) feature takes an arbitrary `from` email, so that wouldn't be a problem. A per-list e-mail is a nice idea, but now that we have per-campaign already, I think that may be a little clunky.

Global default -> Campaign default -> Custom per-list.

**Comment by knadh** [comment]
Per-list isn’t possible, unfortunately. You can achieve this with per-campaign.

Since a campaign can have multiple lists, it wouldn’t be possible to have a default email per campaign meaningfully. One would have to set a per-campaign email anyway.
