### ISSUE TITLE
Default text in content tab 

### ISSUE THREAD

**Issue by mandykaandorp** [knadh/listmonk#895]
**Is your feature request related to a problem? Please describe.**
We pretty much always use the same headers (and some text) in the e-mails. Right now we have to copy the text every time we start a campaign. 

**Describe the solution you'd like**
Is it possible to add a default text in the content tab when editing a campaign? So we can edit and add text where needed.

**Comment by Mattifyed** [comment]
Listmonk already offers templating where you could save your repetitive content. This would be a solution to your problem.
