### ISSUE TITLE
Transactional api sends empty subject when subject does not contain template string "{{"

### ISSUE THREAD

**Issue by eddywashere** [knadh/listmonk#898]
**Version:**
 - listmonk: 2.2.0
 - OS: Ubuntu 20
 - Mailgun smtp

**Description of the bug and steps to reproduce:**

The email subject is empty when sending transactional emails via `/api/tx` and the subject of the template does not contain a template string.

**Screenshots:**

Transactional Template **without** template string in subject

```
POST `/api/tx`

{
	"subscriber_email": "me@example.com",
	"template_id": 5
	"content_type": "html"
}
```

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/399776/183501663-8cc1f996-a82b-4014-b7b2-447ebeb20bbf.png">

<img width="595" alt="image" src="https://user-images.githubusercontent.com/399776/183501818-b93ab7fa-3cd0-42e9-82c6-1de882ca29df.png">

Transactional Template **with** template string in subject

```
POST `/api/tx`

{
	"subscriber_email": "me@example.com",
	"template_id": 5,
	"data": { "subject": "this is a custom subject2" },
	"content_type": "html"
}
```

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/399776/183501946-4a081502-27c4-4336-950f-0c2a2092ea99.png">

<img width="621" alt="image" src="https://user-images.githubusercontent.com/399776/183502044-93f32dfe-96cd-4882-9cb1-04dc2772d724.png">

**Comment by knadh** [comment]
Thanks for reporting. Will investigate this shortly.
