### ISSUE TITLE
Escape < and > in documentation of LISTMONK_from_email

### ISSUE THREAD

**Issue by asdofindia** [knadh/listmonk#90]
Currently in the [wiki](https://github.com/knadh/listmonk/wiki/Configuration) the default value of LISTMONK_from_email shows up as **"listmonk <from@mail.com>"** whereas the default actually should be displayed as **"listmonk \<from@mail.com>"**

This can be fixed by escaping the angle brackets thus: `**"listmonk \<from@mail.com>"**`

**Comment by knadh** [comment]
Fixed. Cheers.
