### ISSUE TITLE
Machine learning ideas in MLM

### ISSUE THREAD

**Issue by kartik4949** [knadh/listmonk#900]
Hi,
Great product! @knadh 

I have ideas around what ai analytics could be done in mailing list system, can help implement them :)
NOTE: May be some are already present or very common use case I'm not much aware in email marketing space.

Ideas:
* Creating smart clusters of subscribers e.g {'cluster_attrib_1': (subscriber1, subscriber2, ...), ...}
* User uploads media - AI driven content creation using the image (image to text translation). 
* AI driven email time/date optimisation. (pretty common)
* data pattern analysis of campaign views i.e month by month pattern recognition etc.
   1. forecasting view (idk might make sense)
   2. predict seasonality in data.
   3. Box-Jenkins ARIMA models might be good starting point.

General Ideas:
* campaign comparisons 
* alerting on high view counts, logging them in database as victories or custom tagging!

Thanks.

**Comment by knadh** [comment]
Thanks, but I don’t think these fit well into the core. You could always write an external app that plugs into listmonk via database tables directly or the API.
