### ISSUE TITLE
Prune unconfirmed subscriptions

### ISSUE THREAD

**Issue by gerricom** [knadh/listmonk#902]
We are using the HTML form for collecting subscriptions to our newsletter lists (they are all double opt-in). Sometimes you get some obvious spam and sometimes users simply put in their wrong addresses. So over a long period of time we collected some hundreds of pending and unconfirmed subscribers. 

This is not a serious problem but out of a cosmetic point of view it would be very convenient to have them pruned once in a while. So for example if someone does not use the double opt in within 14 days or so, they for sure never will and it might be wise to delete them.

Or may I miss some point in keeping them? Thanks!

**Comment by knadh** [comment]
Good point. Makes sense to have automated pruning as a configuration option.

**Comment by knadh** [comment]
This is merged in https://github.com/knadh/listmonk/commit/f9bc049271a1052a2c43a4deffa69a9b897e6269

![image](https://user-images.githubusercontent.com/547147/188264629-9d8c577b-0195-4057-9c4e-e26da18539f9.png)
