### ISSUE TITLE
When I query the campaign_views table, all subscriber_id field is blank

### ISSUE THREAD

**Issue by ccfiel** [knadh/listmonk#906]
**Version:**
 - listmonk: v2.2.0
 - OS: Ubuntu 20.04
 - 
**Description of the bug and steps to reproduce:**
Created a List
Created 2 Subscriber
Created a Campaign and Start Campaign 

When I query the campaign_views table, all subscriber_id field is blank. See screenshot.

**Screenshots:**
![ksnip_20220815-163203](https://user-images.githubusercontent.com/1788360/184604692-441b055f-6c39-47ae-bb35-8890463d7b31.png)

**Comment by knadh** [comment]
Please check Settings > Privacy > Individual subscriber tracking. It is off by default.

**Comment by ccfiel** [comment]
Thanks @knadh. I love the project kudos to you. 😊🍻👍
