### ISSUE TITLE
Install on Amazon ECS

### ISSUE THREAD

**Issue by intelnexoec** [knadh/listmonk#909]
Hello friend, do you have any document or link that explains how to mount listmonk in amazon ecs (docker). I try many times but its impossible for me

**Comment by intelnexoec** [comment]
Hello,

**Comment by intelnexoec** [comment]
I have not had an answer, I am very interested in your platform. I have tried by my means and I have not been able to lift the service

**Comment by knadh** [comment]
Ah, I'm not familiar with ECS to help, unfortunately. There must be numerous tutorials out there that show how to package and run a binary in ECS. @mr-karan do you know any resources off the top of your head?

**Comment by mr-karan** [comment]
I've not used ECS. Maybe the official docs will help? https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_AWSCLI_EC2.html
AWS has multiple services which integrate with ECS, like CodeDeploy: https://docs.aws.amazon.com/codedeploy/latest/userguide/tutorial-ecs-deployment.html but you need to be familiar with this ecosystem to deploy. Listmonk provides docker images, so any tutorial where you find how to deploy an app that comes with a `Dockerfile` should give you pointers.
