### ISSUE TITLE
Is there any hook to track views/clicks/unsubscribes to 3rd party analitics?

### ISSUE THREAD

**Issue by aiboost** [knadh/listmonk#911]
Hi,

We are migrating to ListMonk and wish to use Amplitude to track views/clicks/unsubscribes. So we need to send some HTTP request (or call our console command which will do this) on every desired action with paramerers: 

- campaign title or ID
- action type (view / click / unsubscribe click)
- URL (if action type is click)
- user ID (custom field from our list we import as CVS into Listmonk)

Is there any way to do this?

**Comment by knadh** [comment]
There isn't a way to do this right now. We might have a universal event/webhook system in a future version: https://github.com/knadh/listmonk/issues/658

**Comment by aiboost** [comment]
Thanks!
Universal event listener system could be useful.
