### ISSUE TITLE
Blank name: using a default name

### ISSUE THREAD

**Issue by aiboost** [knadh/listmonk#912]
Hi all,

Is there a way to import a contact without a name?
I know about #594 and the reason this field is mandatory, but I wish to substitute:

`Dear MyProduct user,`

instead of 

`Dear {{ Subscriber.Name }},
`

but when sending an e-mail Listmonk should send it just as `e@mail.com`, not as `MyProduct User <e@mail.com>`

Could you tell me, how to reach this?

**Comment by aiboost** [comment]
Also I wish to tell, that if subscriber's e-mail is `surname@example.com` or `webmaster@example.com` or `nickname@example.com`, using `surname` or `webmaster` or `nickname` is not appropriate IMO.

**Comment by knadh** [comment]
You can store these values as JSON subscriber attributes and use them in the template as `{{ .Subscriber.Attribs.product }}` (or whatever field name you prefer).

**Comment by aiboost** [comment]
knadh, thanks for the answer.

This is a solution. But will a recipient in his e-mail client see something like (probably in some situations):

From: ...
To: **user** <user@example.com>

?

I did not found this in SMTP protocol definition, but in some incoming letters I see my name near e-mail address.
I worry could this method mess up this field or not?

**Comment by knadh** [comment]
The `to` field in e-mails sent from listmonk does not contain the name, only the e-mail ID.
