### ISSUE TITLE
Emails not sent, Amazon SES Failure

### ISSUE THREAD

**Issue by uurcank** [knadh/listmonk#913]
**Version:**
 - listmonk: [eg: v2.0.0]
 - OS: Heroku deploy

**Description of the bug and steps to reproduce:**

Half of the emails are not sent via Amazon SES. I suspect that Amazon SES limits emails to 14 emails per second. So in 1 minute maximum 840 emails can be pushed to Amazon SES. Listmonk is pushing more (1000) than that and fails.

**Comment by knadh** [comment]
You can change the rate of e-mails and speed in Settings -> Performance.

**Comment by uurcank** [comment]
@knadh  thanks good to know. how about we reduce the default rate then so no one runs into this issue? 

1000 is too high considering limitations on free tier on Amazon SES.
