### ISSUE TITLE
Invitations sent prematurely

### ISSUE THREAD

**Issue by janwni** [knadh/listmonk#916]
**Version:**
 - listmonk: [2.2.0]
 - OS: [Debian 5.10]

Hi

I opened a new, empty list, changed type to Opt-in and clicked the "Send Opt-in campagne" button, to see if I can send a personalized message. I stopped at this point and saved the invitation as a draft. Then I added two to three addresses and suddenly received a bounce message for one address. I added one of my addresses to be sure and indeed received an invite. It was quite meaningless and only contained the message: "You applied for the following lists: - Private list" (in german).

I then opened a new empty opt-in list and added another of my addresses and promptly received an invitation.

This is definitely not the behavior I expected. I'd like to manage the lists without e-mails being sent automatically. I also want to be in control of the content of the invitation.

I have now no indication of how many emails were sent out without my knowledge. This is quite scary!

**Comment by knadh** [comment]
The "Send opt-in campaign" option is meant for sending an invite to existing subscribers who never confirmed their subscriptions. Otherwise, the moment a subscriber is added to an opt-in list manually from the admin, or when someone subscribers from the public form, the confirmation e-mail is sent immediately. This is the universal opt-in confirmation behaviour in mailing list programs.

**Comment by janwni** [comment]
Then it's a feature request. At least phplist can be configured so that invitations can be sent in a controlled manner.

I think that's a pretty important feature, when you need to convince people to join the list. It should at least be clear who was sent an invitation.

**Comment by janwni** [comment]
Or add a new list type "Invitation"

**Comment by knadh** [comment]
This is in `Settings` on the admin UI.

![image](https://user-images.githubusercontent.com/547147/186096203-445f1497-7a32-494d-b547-d90a40a59ba8.png)

**Comment by janwni** [comment]
Ah, I'm so sorry, thank you. I didn't see that. Shouldn't it be automatic when someone uses the public form?
