### ISSUE TITLE
Cannot add more than 30 subscribers to a list

### ISSUE THREAD

**Issue by runningnoodle** [knadh/listmonk#917]
**Version:**
 - listmonk: v2.2.0
 - OS: Ubuntu 22.04

**Description of the bug and steps to reproduce:**
Adding subscribers that are all displayed in the same page in the "All subscribers" section works as expected, even when selecting all of the 30 displayed subscribers. However, adding subscribers that are displayed on several pages to a list does not work. When using a query to narrow the number to a small number that is still higher than 30 (41 in my test), the issue persists.

Steps to reproduce:
1. Navigate to the "All subscribers" page (/admin/subscribers in the dashboard).
2. Tick the box on the left side of any subscriber in the table.
3. Click on the "Select all (whatever number of subscribers you have)" link that has just appeared on the right of the "1 subscriber(s) selected —" message.
4. Click on the "Manage lists button".
5. Choose an empty list as the target list.
6. Click on the "Save" button.

Results: An error message appears at the top of the screen: ![image](https://user-images.githubusercontent.com/94857015/186024087-77a167d1-12a2-40aa-b1b9-02f3f5c3c3c1.png)
The subscribers are not added to the target list.
An error appears in /var/syslog: `subscriptions.go:30: error adding subscriptions by query: sql: converting argument $3 type: unsupported type []int, a slice of int`

**Comment by knadh** [comment]
Hi @runningnoodle. This is a confirmed bug. Will fix this shortly. Tracking here #https://github.com/knadh/listmonk/issues/897
