### ISSUE TITLE
Send opt-in on a per-user basis

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#919]
**Is your feature request related to a problem? Please describe.**
We use listmonk also as a newsletter for our B2B communication. The businesses that we deal with are not that techy, so we usually enter their email adresses to the form manually, so they only have to accept the invitiation.

As you can expect, some of them also do not accept that invitation, so we have to resend. I do not want to resend this email to the whole list, just to specific users (as we know them all personally)

**Describe the solution you'd like**
It would be nice to have an option to reset this mail. Maybe by clicking on the button about the subscription status:
![image](https://user-images.githubusercontent.com/6888294/186747940-35d3184f-45a2-4365-8d8b-e606deda17cb.png)

**Comment by knadh** [comment]
If you click on the subscriber and open the subscriber form, there's a link to resend the opt-in mail.

![image](https://user-images.githubusercontent.com/547147/186824411-25c9688f-1178-4e07-9f77-8589f9b41b3a.png)

**Comment by NicoHood** [comment]
How could I miss this? Thanks!

**Comment by housingBerlin** [comment]
How could I resend the opt-in invitation to a specific user through the API? So, not a opt-in campaign to all list subscribers, but to one specific?

**Comment by knadh** [comment]
`POST /api/subscribers/:id/optin` will trigger an opt-in mail.
