### ISSUE TITLE
Google Forms Submission to New Subscriber via API

### ISSUE THREAD

**Issue by Harshmage** [knadh/listmonk#920]
I just spent the last 4 hours of my life building this, and I'm sure someone else has made something like it up, but the great Google was unable to share it.  So here is my ugly how-to with Google Forms and listmonk.

First, build your Google Forms ..form.  Go to the menu on the top right, and go to the Script editor.
![image](https://user-images.githubusercontent.com/1031437/186824651-c11dc3bf-47ea-468c-8738-92bcb3b43dc6.png)

Take this code, paste into the script editor, and update as appropriate for your listmonk install:

```
const POST_URL = "http://<server>:9000/api/subscribers";
const username = "<username>"
const password = "<password>"
function onSubmit(e) {
    var form = FormApp.getActiveForm();
    var formResponse = e.response;
    var itemResponses = formResponse.getItemResponses();
    var payload = {};
    for (var i=0; i<itemResponses.length; i++) {
      switch (itemResponses[i].getItem().getTitle()) {
        case "Name":   // Replace with question title for the subscribers' name
          var question = "name"
          var answer = itemResponses[i].getResponse();
          payload[question] = answer;
          break;
        case "Email":  //Replace with question title for the subscribers' email
          var question = "email"
          var answer = itemResponses[i].getResponse();
          payload[question] = answer;
          break;
      }
    }
    var question = "status"
    var answer = "enabled"
    payload[question] = answer;

    var question = "lists"
    var answer = [3]  //Subscription List is numbered by order created, not by how many there are, so if you deleted the default 2, the next one is 3
    payload[question] = answer;
  
    const authHeader = 'Basic ' + Utilities.base64Encode(username + ':' + password);
    var options = {
        headers: {Authorization: authHeader},
        "method": "post",
        "contentType": "application/json",
        "payload": JSON.stringify(payload)
    };
UrlFetchApp.fetch(POST_URL, options);
};
```

Save this, and now go to the Triggers section of the Script Editor (on the left side menu, looks like an alarm clock icon right now).
![image](https://user-images.githubusercontent.com/1031437/186824700-565fa080-1f35-44af-ad6b-b59c72cc65c1.png)

Add a trigger, choose the new "onSubmit" function, and the important part is the Select Event Type dropdown, where you select "On form submit"
![image](https://user-images.githubusercontent.com/1031437/186824203-39de24ad-36fa-4533-92ee-0225e75dc8a4.png)
Save this trigger, then go test your form!

**Comment by knadh** [comment]
Thanks for sharing this, @Harshmage. I hope this script+form is meant to be internal and not for public use as it embeds the username and password in plain text!

For public use, you can POST to `/subscription/form` with the following fields:
- `name`
- `email`
- `l` (lowercase L denoting the list UUID. Can be passed multiple times.)

**Comment by Harshmage** [comment]
@knadh Thank you!  I'm aware of the unfortunate embed, but I didn't see the `/subscription/form` documentation, so I went with what I could identify.  I'll update my script asap!
