### ISSUE TITLE
Add preview text field to campaign

### ISSUE THREAD

**Issue by teknetia** [knadh/listmonk#924]
**Is your feature request related to a problem? Please describe.**
Add an additional field to Campaigns that allows setting the preview text so that it is more relevant than the opening lines of the email. This is also shown to have positive effects on open rates, plus it just looks nicer when the preview text is sensible.

![email-preview-text-iPhone](https://user-images.githubusercontent.com/7970809/187146611-e6dbf516-2a36-4189-b08e-74991e24e50c.png)

**Describe the solution you'd like**
Add an unformatted text area to the Campaign creation page. Ideal if this can also include variables that would allow for nicer preview text on transactional emails too. This could reasonably be on either the Campaign or Content tabs.

**Comment by knadh** [comment]
Hi @teknetia. There is no `preview text` provision in the SMTP protocol. I'm assuming that these the first few lines of text in the e-mail body that mail clients pick up and show, in which case, you can just have these lines inserted into the campaign body or the campaign template.

**Comment by teknetia** [comment]
Ah sorry I should have been clearer about the use case and how this exists in other mailer solutions as it is usually inserted in an "invisible way". The reason to do it like this is so that you can have nice preview text before any standard greetings, etc. without the resulting email looking messy. This will of course only make sense with HTML formatted campaigns/templates so should be ignored for plaintext cases.

For example, right at the very top of the `<body>` before anything else in the template (headings, logos, greetings, etc.) a template can include something like:

```
<div style="display: none; max-height: 0; overflow: hidden;">
    <%= yield :preview %>
</div>
<div style="display: none; max-height: 0px; overflow: hidden;">
    &nbsp;‌&nbsp;[...trimmed for space...]‌&nbsp;‌&nbsp;‌&nbsp;
</div>
````

Doesn't impede the receiver reading the email but allows the campaign to have much nicer preview text than what an email client would otherwise determine from the text.

**Comment by candidexmedia** [comment]
Hi! How can preheader/preview text be added from the campaign settings?

Here's an example from MailChimp: 

![image](https://user-images.githubusercontent.com/95003834/225991020-f55e2eac-c7ae-4ac1-b06b-cf55d4bbdeff.png)

Here's an example from Envoke:

![image](https://user-images.githubusercontent.com/95003834/225991758-62682f86-7c82-4f1b-9db0-1b0982be82b8.png)
