### ISSUE TITLE
Add public description to List

### ISSUE THREAD

**Issue by teknetia** [knadh/listmonk#925]
**Is your feature request related to a problem? Please describe.**
Public descriptions on lists can ensure that templates include helpful subscription information to help recipients understand why they have received an email and guide them towards better subscription management than just unsubscribe (would be ideal alongside #708).

For example, this text could be something like:
> billing and plan changes

Which could them be used in the template something like:
> You are receiving this email because you have _billing and plan changes_ notifications enabled.

**Describe the solution you'd like**
Add a public description text field to the list create/manage view. Could also be a good opportunity to create a separate private one that allows the receiver to see relevant information while also giving admins more context about the specific list.

**Comment by knadh** [comment]
![image](https://user-images.githubusercontent.com/547147/199273554-46a2528a-4f6a-403e-abc1-72faef105528.png)


![image](https://user-images.githubusercontent.com/547147/199273503-bd6adadd-dfaa-40f7-a026-12980d63cf39.png)
