### ISSUE TITLE
Configuring SMTP, bounce boxes from config.toml ?

### ISSUE THREAD

**Issue by RaitoBezarius** [knadh/listmonk#926]
**Is your feature request related to a problem? Please describe.**

For unattended deployments, I would like to configure SMTP & bounce boxes & other settings directly from config.toml, I'm not certain `settings.go` read them from the initial `config.toml`.

Plus, it would be awesome to have a complete documentation on all options.

**Describe the solution you'd like**

- Read all options from `config.toml` initially (or have an "unattended" mode where the source of truth is the config file) ;
- Documentation of all options

Alternative: SQL script to initiate the database with the correct options for advanced users.

**Comment by knadh** [comment]
Loading settings from config.toml that override settings on the UI (database) is not feasible, unfortunately. Please see this thread for additional context: https://github.com/knadh/listmonk/issues/412

> Alternative: SQL script to initiate the database with the correct options for advanced users.

This is possible. There can be a .sql example in the docs.

**Comment by RaitoBezarius** [comment]
Thank you for your quick answer and the amazing piece of software, I have gone with the alternative (see https://github.com/NixOS/nixpkgs/pull/188949/files#diff-36c4bd41e92a234ff2486cbf7639ad260c2abddab4e495a65dbd2f24d3e92d84R9-R12)!
