### ISSUE TITLE
[API] Possibility to subscribe and existing user to another list

### ISSUE THREAD

**Issue by marcinkunert** [knadh/listmonk#927]
There are 2 private lists:

- `newsletter`
- `waiting list for a product`

Currently, if a user is subscribed to the `newsletter`, there is no way (at least I know of) to subscribe him to the `waiting list` without changing it directly in database or deleting the subscription and creating it again.

As of v2.2.0 sending a POST to `/api/subscribers` results in `409 Conflict: Email already exists` if the email is already in any other list. I think in this situation, the correct answer would be to adding him to the list.

**Comment by knadh** [comment]
You can use the subscription management API to manage subscriber lists. I just realised that this is not in the docs. Will add.

```
POST /api/subscribers/lists/:subscriberID
{
	"action": "add", // add | remove | unsubscribe
	"target_list_ids": [1, 2, 3],
	"status": "subscribed" // Status to use when 'add'ing.
}

POST /api/subscribers/lists
{
	"subscriber_ids": [1, 2, 3, 4]
	"action": "add", // add | remove | unsubscribe
	"target_list_ids": [1, 2, 3],
	"status": "subscribed" // Status to use when 'add'ing.
}
```

An optional `query` param can be used to pass arbitrary SQL expressions to the query (instead of `subscriber_ids: []`) to bulk select subscriber IDs. These APIs are used on the UI when using the "Manage list" option that appears on checking checkboxes next to subscribers.

**Comment by marcinkunert** [comment]
@knadh thanks for the quick reply. I assume the first mentioned API doesn't trigger opt-in send out?

**Comment by knadh** [comment]
Ah, that's right. Bulk management does not trigger opt-in e-mails. `api/subscribers/{subscriberID}/optin` only triggers opt-in for that one subscriber, so that's fine.

**Comment by eljobe** [comment]
When I attempt to send a `POST` request to `/api/subscribers/lists` with listmonk version 2.0.2, I'm getting back a 405 error:

```
405 Method Not Allowed 405 HTTP/1.1 1 1 map[Content-Length:[33] Content-Type:[application/json; charset=UTF-8] Date:[Sun, 04 Sep 2022 13:17:56 GMT]] 0xc00006a060 33 [] false false map[] 0xc00015e100 <nil>
```

Do I need to enable these endpoints?

**Comment by eljobe** [comment]
Ah. I think, according to the code. It's expecting `PUT` not `POST` requests.

**Comment by eljobe** [comment]
Oh. Also, it looks like the field that you called "subscriber_ids" above is actually just called "ids"
https://github.com/knadh/listmonk/blob/master/cmd/subscribers.go#L27

**Comment by eljobe** [comment]
And finally, it looks like `status` should be `confirmed`, `unconfirmed`, or `unsubscribed` not `subscribed`.

**Comment by eljobe** [comment]
@knadh, I thought about forking and contributing the documentation update that would advertise these API endpoints. But, I think the docs must be in another repository. Is it public?

**Comment by knadh** [comment]
Whoops. 

> I thought about forking and contributing the documentation update that would advertise these API endpoints.

That would be very helpful. The repo is at https://github.com/knadh/listmonk-site
