### ISSUE TITLE
No documentaion regarding what is "Orphans" Provided.  

### ISSUE THREAD

**Issue by hobgoblin123** [knadh/listmonk#930]
Hi Kailash,

We recently started using listmonk for our mailing list, and we noticed a bunch of our users were allocated under the orphan section on the main page. We checked for documentation regarding what orphans meant and could not find anything that explained it. Please update the documentation to include what "orphans" mean in listmonk

**Comment by knadh** [comment]
Ah, thanks for pointing this out. Will document this. These are subscribers who do not belong to any lists.

**Comment by knadh** [comment]
[Done](https://listmonk.app/docs/concepts/#subscriber).
