### ISSUE TITLE
Password doesn't save

### ISSUE THREAD

**Issue by organicnz** [knadh/listmonk#931]
Hi folks,

Could you please help, I don't quite understand how to solve the problem with saving the password? :)

<img width="1438" alt="Screen Shot 2022-08-31 at 10 27 37 AM" src="https://user-images.githubusercontent.com/4765090/187620984-4c3c1eab-936f-45b4-b8ab-8c0d51753a59.png">

<img width="1436" alt="Screen Shot 2022-08-31 at 10 27 59 AM" src="https://user-images.githubusercontent.com/4765090/187620992-1f3099fa-4634-41b6-9199-9458ba71b9b6.png">

**Comment by knadh** [comment]
Hi. The password is being served. For security reasons, on the UI, it just shows a short dummy value, that's all.

**Comment by organicnz** [comment]
Hey @knadh, thank you for the answer, mate :) 
I've already tried to configure it in config.toml, but SMTP settings haven't reflected on the UI for some reason :)

**Comment by knadh** [comment]
These options cannot be configured via the config file and have to be done via the UI. Please see the sample config to see what options are supported: https://github.com/knadh/listmonk/blob/master/config.toml.sample

**Comment by organicnz** [comment]
Thank you for the explanation, mate :)
