### ISSUE TITLE
Cloudinary API Support for Media Uploads

### ISSUE THREAD

**Issue by candideu** [knadh/listmonk#932]
**Is your feature request related to a problem? Please describe.**
I've been having a lot of trouble getting S3 compatible apps like Backblaze to work for image uploads, and have no desire to use Amazon's option. See: https://github.com/knadh/listmonk/issues/617

**Describe the solution you'd like**
I'd love to see an option to make use of Cloudinary's Upload API: https://cloudinary.com/documentation/image_upload_api_reference. Another app which makes use of this is Ghost: https://ghost.org/integrations/cloudinary/

**Comment by knadh** [comment]
@rhnvrm this commit (https://github.com/knadh/listmonk/pull/640) should've added Backblaze b2 support, right?

**Comment by candideu** [comment]
I've just tried it again today, and no luck:

![image](https://user-images.githubusercontent.com/55474996/187834862-bb0fb888-4a53-4a4a-bcb8-f0327db8b721.png)

Any time I try the s3 file upload, there's some kind of error. I usually upload my media to Cloudinary and copy the link, but it would be nice to be able to directly upload to Cloudinary from Listmonk.

**Comment by rhnvrm** [comment]
@candideu Yes, b2 should ideally work after #640

Can you share the version of listmonk you are running?

**Comment by candidexmedia** [comment]
@rhnvrm v 2.2.0, hosted on Railway.app

**Comment by rhnvrm** [comment]
Hi

I tested backblaze keys with the listmonk UI locally and it seems to have worked and successfully uploaded the file.

Here are a sample settings. 

![image](https://user-images.githubusercontent.com/952036/190901325-f43721c0-9ff6-4b60-a5fe-c4b8c56332e4.png)

And the upload page.

![image](https://user-images.githubusercontent.com/952036/190901437-97fb4334-572d-4dd3-a867-daa085ac1d0b.png)

**Comment by candideu** [comment]
Thanks for sharing these screenshots @rhnvrm! I finally got it to work today. Thanks to your screenshot, I realized that I was missing the "-002" in the `region`, the `bucket` name. Setting my `Bucket type` to "Public" (both on Backblaze and Listmonk) also helped with accessing the files.

That said, having the option to also use Cloudinary with Listmonk would also be great!
