### ISSUE TITLE
Axios Network Error when trying to view campaign analytics

### ISSUE THREAD

**Issue by candideu** [knadh/listmonk#933]
**Version:**
 - listmonk: v2.2.0
 - OS: Self-hosted on Railway.app

**Description of the bug and steps to reproduce:**
Axios Network Error when trying to view campaign analytics

**Screenshots:**
![image](https://user-images.githubusercontent.com/55474996/187789547-9cd43d76-258b-446b-bfbd-bed0ecd1f344.png)

**Comment by knadh** [comment]
Can you share a screenshot of the request on the browser's network console?

**Comment by candidexmedia** [comment]
![image](https://user-images.githubusercontent.com/95003834/187832376-ec3c88ec-0299-434f-bdc6-d7d2210ec787.png)

**Comment by candideu** [comment]
![image](https://user-images.githubusercontent.com/55474996/187832566-cff0ad00-261e-4a22-bc47-b28ab44edd8d.png)

**Comment by knadh** [comment]
Thanks. Could you also share the output from the `Network` tab?

![image](https://user-images.githubusercontent.com/547147/187832659-e6cfddaa-fa04-496d-b6b1-54566bf23a50.png)

**Comment by candideu** [comment]
I think I found the culprit:

![image](https://user-images.githubusercontent.com/55474996/187832929-2b8a4417-c7a8-4a8e-8256-cd07ab411349.png)

Looks like it's a UBlock Origin issue. When I turn off UBlock, the analytics work
