### ISSUE TITLE
Viewing list of subscribers who received newsletter

### ISSUE THREAD

**Issue by candideu** [knadh/listmonk#934]
**Is your feature request related to a problem? Please describe.**
At the moment, there's no way of checking which subscribers received a particular campaign:

![image](https://user-images.githubusercontent.com/55474996/187792981-5599ebbc-516a-4fa2-8100-36e79952a6b0.png)

Click on the bounce processing number leads to a list which displays which emails bounced, but the same isn't possible for the sent list. Knowing who the campaign was sent to is crucial for a number of reasons (ie: checking to make sure someone who was unsubscribed didn't receive the campaign, follow up on claims that an email wasn't received, etc.).

**Describe the solution you'd like**
- Clicking on the "sent" numbers displays a list of list members who received a particular campaign
- Viewing a list of campaigns sent to a particular list / Filter list of campaigns by list
- For each subscriber, via the Subscriber tab: a list of the campaigns they've received

**Comment by knadh** [comment]
This is difficult. listmonk does not record statistics per subscriber. If it did, for a list with 10 million entries, for every campaign that was sent, it'd have to create 10 million new entries (one per subscriber) somewhere, quickly running into tens/hundreds of millions of entries. This was a conscious architectural decision keeping performance and scale in mind.

**Comment by candideu** [comment]
@knadh Makes sense to not have view stats tied to subscribers.

What if it was possible to get a simple print txt list of all the email addresses that received a campaign? It would be viewable in the campaign reports, but not acting as a database entry for each subscriber. This way, the admin could still check who received which campaign.

**Comment by FelipoAntonoff** [comment]
A good idea, perhaps json or SQLite can be used, one stool for every X customers, although even if it is in the main bank, I believe that it is up to each user to have the infrastructure to meet their demand for use, perhaps it could be a resource optional to turn it off or on and only recommended for up to X thousand users, because for a small base it makes sense to use it and those who have a lot of base can make the necessary optimizations or deactivate it.

**Comment by MaximilianKohler** [comment]
>listmonk does not record statistics per subscriber

Doesn't it record campaign views per subscriber? Eg: https://github.com/knadh/listmonk/issues/686

**Comment by CodeAlDente** [comment]
> "listmonk does not record statistics per subscriber"
cf. https://github.com/knadh/listmonk/issues/934#issuecomment-1233714154

Now that we have the activity tab per subscriber and can see individual tracking information per subscriber, this could be extended to include send history as well. For tracking this, bounce information could also be used to determine whether a campaign was sent to a given subscriber / email address.

**Related issues:**
- #2185
