### ISSUE TITLE
Override opt-in on multiple users

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#935]
**Is your feature request related to a problem? Please describe.**
I started using different list for different of my clients. It turned out to be a bad idea, so I want to move them all into one, but without sending them a new confirmation email.

When Editing a single user, I can do this:
![image](https://user-images.githubusercontent.com/6888294/187838553-16166a27-5b42-426d-bc5c-d2c088bea124.png)

When selecting multiple users in an existing list, I can only do this:
![image](https://user-images.githubusercontent.com/6888294/187838615-31145c07-fe29-4548-9e7b-3e09e712181c.png)

**Describe the solution you'd like**
It would be nice to have an override feature there as well.

NOTE: I am still on 2.1, if that feature is available in the meantime, I am super sorry.

**Comment by knadh** [comment]
Makes sense. For now, you could run this query: `UPDATE subscriber_lists SET list_id=$newID WHERE list_id=$oldID`.

**Comment by knadh** [comment]
![image](https://user-images.githubusercontent.com/547147/199281401-7c5e8da7-df79-401e-b4e4-2bb4d2b5ebe6.png)
