### ISSUE TITLE
Nested map data within a campaign

### ISSUE THREAD

**Issue by lukeronalds** [knadh/listmonk#937]
Within a transactional email there is a `data` parameter exaplained as optional data in {} nested map. Available in the template as `{{ .Tx.Data.* }}`

Is it possible to pass in data in the form of a map for a regular campaign that can be accessed in the Go templating through the API?  Seems possible using the transactional API but not with the campaign API.

**Comment by knadh** [comment]
There isn't a way to pass arbitrary JSON data to a campaign right now. For campaigns, it is per-subscriber JSON attributes.

**Comment by knadh** [comment]
Closing this. Since the data in a campaign is uniform for every single subscriber, it could just be a part of the campaign content or the template. An additional data field isn't necessary.
