### ISSUE TITLE
Document Media API Breaking Change

### ISSUE THREAD

**Issue by NicoHood** [knadh/listmonk#939]
The media API upload did change. It does not return `true` anymore, but the media object itself. This is a welcome change, but should be documented, as my scripts checked for the `true` response and now all failed.

I'd expect that information here:
https://github.com/knadh/listmonk/releases/tag/v2.2.0

**Comment by knadh** [comment]
Fixed this in the release notes and [docs](https://listmonk.app/docs/apis/media/#post-apimedia).
