### ISSUE TITLE
Can it support async IO?

### ISSUE THREAD

**Issue by lovejieer** [knadh/listmonk#94]
When clicking email track links, redirect first and then write to db.
I know gin is easy to do that but not know echo.

**Comment by knadh** [comment]
Right now, link fetch + recording happens in a single DB call. Doing it async means reading the link first and then then registering the click, which would be a second call.

If the target link is embedded in the tracking URL, it still has to be validated against what's in the DB before redirection to prevent an open redirection vulnerability.

So there's no way to do this without at least one synchronous DB call.
