### ISSUE TITLE
Optin subscription - empty list 

### ISSUE THREAD

**Issue by sreimers** [knadh/listmonk#940]
**Version:**
 - listmonk: 2.2.0
 - OS: Debian

**Description of the bug and steps to reproduce:**
- Register for subscription
- Follow E-Mail subscription link (https://example.net/e995e13b-babe-41b0-8c86-423877901cc1?l=60764b9a-175c-4d3e-bfed-79b4d8aa0e86)

Subscription works, but the list shown is empty:

https://github.com/knadh/listmonk/blob/master/static/public/templates/optin.html#L11

**Comment by knadh** [comment]
Only `Public` lists are shown on the public subscription page. Are the lists that are not appearing public?

**Comment by sreimers** [comment]
Yes the list is public. The E-Mail Template shows the list correctly.

**Comment by sreimers** [comment]
Yes `/subscription/form` shows the public list:

The optin confirm page shows only this:
![Bildschirmfoto vom 2022-09-09 11-23-50](https://user-images.githubusercontent.com/296762/189318160-4aae5df3-a189-40e5-a5c6-26c456f209bf.png)

**Comment by sreimers** [comment]
> Where? On the public form? On the admin dashboard? If it's on the public form, is the list visible there?

Public form.

**Comment by knadh** [comment]
This was indeed a bug. It's now fixed. Thanks for reporting. For the time being, you can run the fixed templates with the `--static-dir` flag: https://listmonk.app/docs/templating/#system-templates

**Comment by sreimers** [comment]
Thanks!
