### ISSUE TITLE
Docker Error Upload Media

### ISSUE THREAD

**Issue by Nathan9745354** [knadh/listmonk#943]
Error uploading file: open /media/uploads/3-04.png

![image](https://user-images.githubusercontent.com/46953407/189692511-23b6c98f-18fb-4db4-8272-45508f1d95f1.png)

Changed the Path

![image](https://user-images.githubusercontent.com/46953407/189692628-8de8fa47-78c1-4582-bc31-518864cae36c.png)

Anyone can help?

**Comment by knadh** [comment]
Have you mounted the Docker volumes? Please refer to this: https://github.com/knadh/listmonk/issues/894#issuecomment-1204750659

**Comment by Nathan9745354** [comment]
> Have you mounted the Docker volumes? Please refer to this: [#894 (comment)](https://github.com/knadh/listmonk/issues/894#issuecomment-1204750659)

Thanks for your information.

I have read the #894 , but I don't know what path should me mount , because it's a lot of version.

for instance.

If I using method 2 bind mounts.

I have been create a uploads folder at /home/ubuntu/listmonk/uploads and already set the media upload path is /home/ubuntu/listmonk/uploads, what I should mount?

**Comment by mr-karan** [comment]
The path on your host machine `home/ubuntu/listmonk/uploads` should be mounted inside the docker container for the uploads to persist. 

You need to have this in your `docker-compose.yml` and revert an y settings change that you did.

```
    volumes:
      - /home/ubuntu/listmonk/uploads:/listmonk/uploads
```

**Comment by Nathan9745354** [comment]
> The path on your host machine `home/ubuntu/listmonk/uploads` should be mounted inside the docker container for the uploads to persist.
> 
> You need to have this in your `docker-compose.yml` and revert any upload path settings change that you did.
> 
> ```
>     volumes:
>       - /home/ubuntu/listmonk/uploads:/listmonk/uploads
> ```

Hi Mr-Karan , 

I want to know "/listmonk/uploads" from where? docker volumes ls ? is it docker volumes name?

**Comment by mr-karan** [comment]
No. It's a bind mount, not managed by docker. It simply mounts a path from host machine to a path inside container. 

You can exec inside the container and see `ls /listmonk/uploads`.

**Comment by Nathan9745354** [comment]
> No. It's a bind mount, not managed by docker. It simply mounts a path from host machine to a path inside container.
> 
> You can exec inside the container and see `ls /listmonk/uploads`.

It's still not working.

Let me share some information.

![image](https://user-images.githubusercontent.com/46953407/189893765-8c241135-4ed2-4796-bb62-62f046729e47.png)

![image](https://user-images.githubusercontent.com/46953407/189894039-63fed96d-a8d1-44b3-b005-748f7241646f.png)
And I also remove character "." bu no luck.

![image](https://user-images.githubusercontent.com/46953407/189894152-ba1d39b8-1a25-4705-ae33-978bb3076ae3.png)

![image](https://user-images.githubusercontent.com/46953407/189894319-56d880c0-e50d-4940-8205-fd30e7ab60f2.png)

**Comment by knadh** [comment]
1) Your Docker file should have this:

```
volumes:
      - /home/ubuntu/listmonk/uploads:/listmonk/uploads
```

2) The upload path in the settings UI should have this `/listmonk/uploads`

**Comment by Nathan9745354** [comment]
> 1. Your Docker file should have this:
> 
> ```
> volumes:
>       - /home/ubuntu/listmonk/uploads:/listmonk/uploads
> ```
> 
> 2. The upload path in the settings UI should have this `/listmonk/uploads`

Hello Knadh.

I almost crazy haha.

1. I already set this config in docker-compose.yml
![image](https://user-images.githubusercontent.com/46953407/189895348-0a230ce4-796c-4be2-84ba-d0d69258e363.png)

2. And the upload path in the settings UI is /home/ubuntu/listmonk/uploads
![image](https://user-images.githubusercontent.com/46953407/189895562-dbb5869b-6463-4b25-8a74-15cc6d227f95.png)

**Comment by mr-karan** [comment]
Your `docker-compose.yml` is invalid. `volumes` mount should be defined in the `services` section and it's not a top level key.  Please read the docs carefully, it's documented here: https://listmonk.app/docs/configuration/#media-uploads

**Comment by knadh** [comment]
This is incorrect. There should be no `.` in the config file and UI should have `/listmonk/uploads`.

**Comment by Nathan9745354** [comment]
> Your `docker-compose.yml` is invalid. `volumes` mount should be defined in the `services.app` section and it's not a top level key.  Please read the docs carefully, it's documented here: https://listmonk.app/docs/configuration/#media-uploads

I have read the doc , it's only .yml in listmonk, can you guide how to do ?

Please.

**Comment by Nathan9745354** [comment]
> This is incorrect. There should be no `.` in the config file and UI should have `/listmonk/uploads`.

Do you mean the ui path is /listmonk/uploads

Not /home/ubuntu/listmonk/uploads

Am i right?

Thanks

**Comment by mr-karan** [comment]
> I have read the doc , it's only .yml in listmonk, can you guide how to do ?

The `volumes` should be added under this line: https://github.com/knadh/listmonk/blob/master/docker-compose.yml#L48

> Do you mean the ui path is /listmonk/uploads

Yes.

**Comment by Nathan9745354** [comment]
> 

Hi Mr-Karan,

I have been recreate an docker-compose.yml and paste - /home/ubuntu/listmonk/uploads:/listmonk/uploads under the line , docker-compose up ,but still not work. please help.

`version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  ports:
    - "9000:9000"
  networks:
    - listmonk
  environment:
    - TZ=Etc/UTC

x-db-defaults: &db-defaults
  image: postgres:13
  ports:
    - "9432:5432"
  networks:
    - listmonk
  environment:
    - POSTGRES_PASSWORD=listmonk
    - POSTGRES_USER=listmonk
    - POSTGRES_DB=listmonk
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    <<: *app-defaults
    container_name: listmonk_app
    depends_on:
      - db
    volumes:
      - /home/ubuntu/listmonk/uploads:/listmonk/uploads

  demo-db:
    container_name: listmonk_demo_db
    <<: *db-defaults

  demo-app:
    <<: *app-defaults
    container_name: listmonk_demo_app
    command: [sh, -c, "yes | ./listmonk --install --config config-demo.toml && ./listmonk --config config-demo.toml"]
    depends_on:
      - demo-db

networks:
  listmonk:

volumes:
  listmonk-data:
`

![image](https://user-images.githubusercontent.com/46953407/189943260-cb8f1ffd-a482-49bb-b20e-e27e4aff2077.png)

**Comment by Nathan9745354** [comment]
I did not find the volume of this

![image](https://user-images.githubusercontent.com/46953407/189944681-019d8e5e-7976-4e5e-976f-39f72d13deed.png)

**Comment by Nathan9745354** [comment]
anyhelp? @knadh @mr-karan 

Thanks!!

**Comment by Nathan9745354** [comment]
Finally , I fixed it.

Please close the issue.

Thanks for your help.

**Comment by MaximilianKohler** [comment]
How did you fix it? I'm having the same problem.

**Comment by MaximilianKohler** [comment]
> > Do you mean the ui path is /listmonk/uploads
> 
> Yes.

The default text should be changed then as it's very misleading:
![default text](https://github.com/knadh/listmonk/assets/3606996/d081376d-ed4b-4708-a5ee-099724823a8b)

It suggests we should be using `/home/ubuntu/listmonk/uploads`, not `/listmonk/uploads`.
