### ISSUE TITLE
Timed out waiting for free conn in pool

### ISSUE THREAD

**Issue by 0x11c11e** [knadh/listmonk#945]
**Version:**
 - listmonk:  (v2.2.0)
 - OS: debian

Once the campaign is started I see this error logs non stop without anything else between lines. The email is authenticated and verified.

`2022/09/14 08:43:04error sending message in campaign Third Email Blast: subscriber 84a33edd-9435-479e-9da7-c736a41fd104: timed out waiting for free conn in pool
2022/09/14 08:43:04error sending message in campaign Third Email Blast: subscriber 108d0789-7942-4413-95d2-c933e77db40a: timed out waiting for free conn in pool
2022/09/14 08:43:04error sending message in campaign Third Email Blast: subscriber ebce09cb-af32-4b89-b79c-ca8b656cb3e5: timed out waiting for free conn in pool
2022/09/14 08:43:04error sending message in campaign Third Email Blast: subscriber b3120ce9-4ff7-4ba4-9d2f-2c73b5b6cac5: timed out waiting for free conn in pool
2022/09/14 08:43:04error sending message in campaign Third Email Blast: subscriber e27d845d-6de9-48f3-88a6-5672a6829072: timed out waiting for free conn in pool
2022/09/14 08:43:04error sending message in campaign Third Email Blast: subscriber c062936f-9a36-4e4d-acae-5caf67cfb36e: timed out waiting for free conn in pool
2022/09/14 08:43:04error sending message in campaign Third Email Blast: subscriber 1e6315e6-b1cf-4445-8568-852ee6d9b2d5: timed out waiting for free conn in pool
2022/09/14 08:43:04error sending message in campaign Third Email Blast: subscriber 7de27f4c-213d-49f7-b4ca-d88a3e6b2ca9: timed out waiting for free conn in pool
2022/09/14 08:43:04error sending message in campaign Third Email Blast: subscriber 2ea852ed-7048-4210-bef4-4ed9d89706e3: timed out waiting for free conn in pool
2022/09/14 08:43:04error sending message in campaign Third Email Blast: subscriber 3a37d330-cac5-4306-99f9-c691312b9569: timed out waiting for free conn in pool
2022/09/14 08:43:06error sending message in campaign Third Email Blast: subscriber ed97dd69-8de1-4e64-8785-0dca523f2fda: timed out waiting for free conn in pool
2022/09/14 08:43:06error sending message in campaign Third Email Blast: subscriber dd49ce43-cfac-4531-8da4-1bb2e103577c: timed out waiting for free conn in pool
2022/09/14 08:43:06error sending message in campaign Third Email Blast: subscriber 97f5a540-ab9c-4d59-b94d-c72309258c40: timed out waiting for free conn in pool
2022/09/14 08:43:06error sending message in campaign Third Email Blast: subscriber 3498656d-a2c2-4d36-acef-067cdd85b1a1: timed out waiting for free conn in pool
2022/09/14 08:43:06error sending message in campaign Third Email Blast: subscriber 49fec363-bcad-443c-857f-b9860d835139: timed out waiting for free conn in pool
2022/09/14 08:43:06error sending message in campaign Third Email Blast: subscriber 75065361-4d20-40c1-b575-4565c246205e: timed out waiting for free conn in pool
2022/09/14 08:43:06error sending message in campaign Third Email Blast: subscriber dee1207d-98a7-4b4c-afc0-6d6e737c5639: timed out waiting for free conn in pool
`

![Screenshot_20220914_014449](https://user-images.githubusercontent.com/95732859/190106725-5cf120c4-67e8-4fb3-b5f3-41ea456526ba.png)

**Comment by knadh** [comment]
> 421 4.7.0 Try again late

Looks like you're getting rate limited by Gmail.

https://stackoverflow.com/questions/45756808/bulk-emails-failed-with-421-4-7-0-try-again-later

**Comment by MaximilianKohler** [comment]
> SMTP server is slow or overloaded and listmonk's attempts to use an SMTP connection to push out an e-mail is timing out. Try increasing the `Max. connections` settings in SMTP settings and reducing `Concurrency` and `Message rate` in performance settings.

Hmm, my SMTP max connections was already raised to 40, and my performance settings aren't that high and well within the Amazon SES limits for my account, so I wouldn't want to lower them. 

`Concurrency 120, message rate 40, batch size 10,000`.

listmonk v2.5.1.

**EDIT:**
Though I see here https://github.com/knadh/listmonk/issues/734#issuecomment-1056319508 that you say SMTP max conns may need to be in the 100s.
