### ISSUE TITLE
Bounce processing

### ISSUE THREAD

**Issue by 0x11c11e** [knadh/listmonk#946]
Hi,

I am puzzled by the way bounce processing works. I have enabled the bounce processing and set bounce count to 1, and set action to delete. Also I have added a POP3 server for bounce mail box but I get this error in logs:
` bounced subscriber ( / ) not found`
My understanding is that for each bounce the software has to read the bounce mail box and automatically remove it or blacklist it from the list of subscribers. Apparently this is not happening and I get that error message. Would you please let me know how can I enable bounce processing?

**Comment by knadh** [comment]
Looks like listmonk is reading e-mails from your bounce inbox but is unable to extract identifiers (headers) from the e-mail that are needed to process the bounce. Would you be able to share the raw source for one of the bounce e-mails here?
