### ISSUE TITLE
Built-in smtp server

### ISSUE THREAD

**Issue by 0x11c11e** [knadh/listmonk#947]
Hi,

I am wondering if does listmonk have any built-in smtp server to relay the email? Almost all of the paid email providers have limitation to use their smtp. Postfix offers an option of relaying email through a local smtp without even having a valid domain and it will use hostname as domain. I was wondering if does same thing happens in listmonk?

Thanks

**Comment by knadh** [comment]
listmonk doesn't have a built-in SMTP/MTA. Please see this discussion for context https://github.com/knadh/listmonk/issues/528
