### ISSUE TITLE
How to customize email confirmation template ?

### ISSUE THREAD

**Issue by henricazottes** [knadh/listmonk#95]
Hi, I've been trying to setup a form to subscribe to a mailing list, but I don't understand where the email confirmation template comes from.

I have setup a list with following settings:
- Name: Landing page
- Type: Private
- Optin: single

And I receive this email:

![listmonk_email_confirmation](https://user-images.githubusercontent.com/5214384/81391078-c943d880-911c-11ea-9921-b5bc0d0cc71b.jpeg)

Two questions:
- where could I change it? It's not very clear to me...
- why is it stated **Private list** instead of **Landing page** for the list name ?

Thanks

**Comment by knadh** [comment]
Hi @henricazottes 
1) All e-mail templates are in `static/email-templates`: See https://github.com/knadh/listmonk/wiki/Configuration#Customization

2) Private lists, by definitions, are not available to the public to signup directly via signup forms. These are usually internal admin lists. Hence, their names are also not revealed the public. Double opt-ins are generally used with public lists.

**Comment by jeff-h** [comment]
(docs for that are now at https://listmonk.app/docs/configuration/#customizing-system-templates)
