### ISSUE TITLE
HTTP Headers for Messenger

### ISSUE THREAD

**Issue by ht512512** [knadh/listmonk#951]
Reading the docs, I do not see anyway to add HTTP headers for POSTing to the REST endpoint. Many API endpoints require additional headers to work. Is this already supported ?

**Comment by knadh** [comment]
listmonk APIs don't require any additional headers except for the BasicAuth header. Any HTTP client you use will support setting one or more headers.

**Comment by ht512512** [comment]
I am sorry I did not clearly state what I meant. To setup a messenger to call out to a Postback URL, how do I specify headers if the Postback server API requires it (for example API key)?

Thanks.

**Comment by knadh** [comment]
You can optionally enable BasicAuth when setting up messenger config in the listmonk settings UI. If this is enabled, listmonk will send an `Authorization` header to the postback URL. Apart from this, no headers can be sent.

You've to design your postback endpoint to work with the listmonk postback spec.
