### ISSUE TITLE
SMTP io/timeout with gmail, not sure which firewall rules to set

### ISSUE THREAD

**Issue by mbc3** [knadh/listmonk#952]
I'm getting an error testing out my SMTP connection to gmail: `sending SMTP test (Test connection): dial tcp 142.251.2.109:465: i/o timeout`

My own intuition and looking around for similar issues has led me to believe this is a firewall issue. I enabled both port 465 and port 587 over tcp - 

`firewall-cmd --zone=public --permanent --add-port=587/tcp`
`firewall-cmd --zone=public --permanent --add-port=465/tcp`

and reloaded the configuration, but I'm still getting the timeout error.

What's strange is I can ping and traceroute within the podman container, so the listmonk container has a network connection. Looking around the podman docs makes it seem like the default firewalld zone for podman containers is trusted, which does no filtering, so I'm not sure what my configuration problem is. Any help would be appreciated!

**Comment by mr-karan** [comment]
Can you try [`nc`](https://man.openbsd.org/nc.1) from within the container? 

```
nc -vz -w 3 142.251.2.109 465
```

This would show that a TCP connection gets established on that host/port. Some cloud providers do block outgoing SMTP ports to prevent spam, and I suspect this is what might be happening here however ICMP probes would be going through. Just a guess, based on the above command we can debug further.

**Comment by mbc3** [comment]
When I run `nc`, I get a time out error. However, I looked it up with my cloud provider and found that they block outgoing SMTP ports, and that I have to open a support ticket to ask for permission to use those ports. So it looks like that was the issue. Thank you so much for your help!
