### ISSUE TITLE
535 Incorrect authentication data

### ISSUE THREAD

**Issue by Nathan9745354** [knadh/listmonk#956]
Hi ,

Using domain try to config SMTP got 535 Incorrect authentication data , in other mail client could login success without 535 error, and if I change smtp port to 465 (following the siteground config), it's only keep loading.

Please help .

Host = Sitegroud

![image](https://user-images.githubusercontent.com/46953407/191877517-e035331d-10a1-40ef-9a23-243ab42f2402.png)

**Comment by ChrisTG742** [comment]
Maybe you're facing "my" bug #957 here, too?

**Comment by Nathan9745354** [comment]
No. Fixed it.

I just close the browser and using SSL/TLS login and worked , I think it's bug.

**Comment by knadh** [comment]
> I just close the browser and using SSL/TLS login and worked , I think it's bug.

The browser has no relation to the SMTP connection. It'd have been incorrect SMTP settings.

**Comment by Nathan9745354** [comment]
> > I just close the browser and using SSL/TLS login and worked , I think it's bug.
> 
> The browser has no relation to the SMTP connection. It'd have been incorrect SMTP settings.

I am using another host same domain but it's 535 too and can login to outlook or other client

What happen?
