### ISSUE TITLE
SMTP-passwords not fully escaped

### ISSUE THREAD

**Issue by ChrisTG742** [knadh/listmonk#957]
**Version:**
 - listmonk: 2.2.0
 - OS: Ubuntu 20 LTS

Amazom SES accounts can have several special charactes in the auto-generated password, like the slash/backslash.
These characters partially disappear when saving the password in the UI. It seems, that there is some more escaping needed there.
Example password:
`BA3IEO8Wl2Tf+z9dx2a30E0EXzfxe+efeczTf1x6gO/Q`

Current work-around is to generate new credentials until they do work for some reason (not containing any "bad" chars).

**Comment by ChrisTG742** [comment]
AFAIC there is no good way to prevent Go from adding/processing escapes in strings (at least what I've found at stackoverflow).
Maybe it would be a good idea to store such strings in an array of bytes instead of string type?

**Comment by ChrisTG742** [comment]
Yes, I know that it only displays a dummy. I rather thought about something like "escaping loss" or "double escaping" erros done by the browser itself when sending the field-value or on the receiver-side when processing the POST-vars.
I also had trouble with HTML forms containing "special" char fields in the past, so the byte-array was just a suggestion to be code-wise save that there's no further modification done inside the program.

Is there something like a debug-mode where one can see what is sent by the POST requests and what what actually gets stored inside the program?

**Comment by ChrisTG742** [comment]
*LOL* that's exactly the same query I suggested in #950 😄 

Hm, but somewhere it must have failed. I noticed that Amazon SES passwords mit slashes inside resulted in a "authentication failed".

**Comment by knadh** [comment]
Passwords are obviously not logged anywhere. I ran mailhog (dummy SMTP) server, used your sample password to send an e-mail to the dummy server, and looked up the SMTP's verbose log to see what came through.

```
2022/09/27 15:02:57 [SMTP [::1]:34182] Received 85 bytes: 'AUTH PLAIN AGF3c3VzZXIAQkEzSUVPOFdsMlRmK3o5ZHgyYTMwRTBFWHpmeGUrZWZlY3pUZjF4NmdPL1E=\r\n'
```
Base64 decoding the auth string produces `BA3IEO8Wl2Tf+z9dx2a30E0EXzfxe+efeczTf1x6gO/Q`. So, the password is hitting the SMTP server as-is without any corruption.
