### ISSUE TITLE
Tracking template expressions in links

### ISSUE THREAD

**Issue by alfturtle** [knadh/listmonk#958]
Hi Guys,

I'm pretty new here to Github, but I have been using list monk for a while.  The one issue I have been having is tracking template expressions or attributes in links.

For example I want to track: `https://mydomain.com/?utm_source=mysource&utm_medium=email&utm_campaign=mycampaign&utm_content={{ .Subscriber.UUID }}`

I also need to use the `{{ .Subscriber.UUID }}` in the newsletters for Liveintent ads within the newsletter.

If I use the link as 
`<a href="https://mydomain.com/?utm_source=mysource&utm_medium=email&utm_campaign=mycampaign&utm_content={{ .Subscriber.UUID }}@TrackLink">` 

It does not fill that info.  If I remove the tracking the info is passed.  I also tried moving `utm_content={{ .Subscriber.UUID }}` from the end of the link to make sure it wasn't breaking because it was at the end. 
-- I'm not a programmer so I have no idea how or why that would break it :) --

If I use the link as 
`<a href="{{ TrackLink "https://mydomain.com/?utm_source=mysource&utm_medium=email&utm_campaign=mycampaign&utm_content={{ .Subscriber.UUID }}" }}">` 

It also does not fill that info.

I have searched every article on here for similar issues, and I looked at the go template site for examples, and could not make heads or tails of it or find anything similar to what I want to do.

Any help with this would be greatly appreciated!

Thanks!

**Comment by knadh** [comment]
Thanks for reporting this @alfturtle. This is unfortunately because of how template expressions are processed in listmonk. This isn't a trivial fix and will hopefully land in one of the upcoming releases in the near future.

**Comment by alfturtle** [comment]
@knadh Thanks for the response.  I at least now know it wasn't me not knowing what I was doing :)
