### ISSUE TITLE
Add base templates customization directly in the webapp

### ISSUE THREAD

**Issue by henricazottes** [knadh/listmonk#96]
As stated [here](https://github.com/knadh/listmonk/wiki/Configuration#customization), you can specify a path to change default email templates. In my opinion it's a step that's very likely to happen. 

Wouldn't it be useful to be able to do it directly in the webapp as it's already possible to do so with campaign templates ? Like adding `Settings / Base templates` in the left menu, so you don't have to ssh every time you need to tweak it.

It would make it a bit more standalone :)

**Comment by knadh** [comment]
This could be useful, but editing templates on disk will not be straight forward in Docker environments. Moving static templates as settings to the DB isn't a good idea either.

Template editing is usually one-time or a very infrequent affair. It's a fair trade-off :)

**Comment by henricazottes** [comment]
Can't you use volumes to handle files in docker ?

But I agree with your points, it's not a big deal.
