### ISSUE TITLE
test-email functionality does not work

### ISSUE THREAD

**Issue by rafalsk** [knadh/listmonk#961]
**Version:**
 - listmonk:: 2.2.0
 - OS: official Docker build

**Description of the bug and steps to reproduce:**
Mails are being sent out, but the test-mail functionality does not work resulting in a `'2022/09/29 12:10:05error sending SMTP test (Test connection): 503 5.5.1 Error: nested MAIL command` 

when SMTP username is in the form of ABC@xyc.cv

**Comment by knadh** [comment]
1) Does this happen even after a restart?

2) What SMTP server are you using?

**Comment by rafalsk** [comment]
Yet another part of the bug:
![image](https://user-images.githubusercontent.com/9338163/193408963-2390870c-7eaa-4f19-a8be-f4069cde7b90.png)
The above is shown, even though the system has the password stored and seemingly available (though asterixed) within the password field, user is forced to re-type it all again anyway.
`1. Does this happen even after a restart?`
Yes.
`2. What SMTP server are you using?`
postfix. the legend sir.
poczta.put.poznan.pl 587

**Comment by knadh** [comment]
The password is stored but isn't brought to the browser's UI in plain text for obvious reasons. Also, if the stored version is picked up automatically, what if the test involved trying a new password on the UI. Hence, the need to manually enter the password.

The `nested mail` error has been non-reproducible so far. See https://github.com/knadh/listmonk/issues/337 for context. Test mail / campaign mail routines all use the same underlying mechanisms.

When you send a test mail and it fails, do the subsequent test mails work, or test mails never work at all?

**Comment by rafalsk** [comment]
Knadh, kindly thank your reply. Kindly thank you for your software.

"Hence, the need to manually enter the password."

When  there is a problem, there is a need to improve and we, developers,  might either like it or not :-)

Suggestions:

- at least ensure that password field is empty once shown to the user (currently it is not).
- personally I would decouple these two test scenarios, from the UI perspective. Make one part of the UI responsible for configuration of the SMTP server, and ANOTHER for testing of the actual e-mail deliveries to particular target mailboxes. 
- add retractable log of the process so that things can be actually debugged.

"The nested mail error has been non-reproducible so far. "

I just reported the behaviour, I certianly do not know the underlying software I do hear you though.

`2022/10/02 17:16:30messages exceeded (40) for the window (1h0m0s since 02 Oct 22 17:15 +0000). Sleeping for 59m9s.
2022/10/02 18:16:32messages exceeded (40) for the window (1h0m0s since 02 Oct 22 18:15 +0000). Sleeping for 59m7s.
2022/10/02 19:16:30messages exceeded (40) for the window (1h0m0s since 02 Oct 22 19:15 +0000). Sleeping for 59m9s.
2022/10/02 20:16:32messages exceeded (40) for the window (1h0m0s since 02 Oct 22 20:15 +0000). Sleeping for 59m8s.
2022/10/02 21:16:30messages exceeded (40) for the window (1h0m0s since 02 Oct 22 21:15 +0000). Sleeping for 59m10s.
2022/10/02 22:16:02campaign (New research paper) finished
2022/10/02 22:16:05error sending message 'Finished: New research paper': 503 5.5.1 Error: nested MAIL command
2022/10/02 22:16:06error sending message in campaign New research paper: subscriber 388f3a5e-1a6d-4ced-9739-ec5eb34dd233: 503 5.5.1 Error: nested MAIL command`

from the above log you may draw conclusions that e-mail dispatch works - of campaigns, still it can pop the nested mail error now and then, apparently. 

Forgive my ignorance, seems like there already is a log pane in the 'testing pane'. Yes, trying to send an e-mail is guaranteed to pop out '503 5.5.1 Error: nested MAIL command'. Campaigns work just fine.

**Comment by knadh** [comment]
> at least ensure that password field is empty once shown to the user (currently it is not).

Showing an empty password field is a bigger UX issue where users save the password and while all other fields look filled, password looks unfilled. That's why there's a dummy password just to indicate that it is filled.

> personally I would decouple these two test scenarios, from the UI perspective. Make one part of the UI responsible for configuration of the SMTP server, and ANOTHER for testing of the actual e-mail deliveries to particular target mailboxes.

Ideally yes, but that means replicating all the SMTP fields inside a new test UI. Now once it's tested, it has to be saved without re-entering, so now there needs to be an option to copy values from the test UI to the settings UI.

While the current implementation isn't perfect, I think is a good-enough trade-off.

**Comment by NessDan** [comment]
Bumping this, I just setup Postgres, launched the Windows binary after configuration, and after trying to send an SMTP test email, I got:

> `error sending SMTP test (Test connection): 503 5.5.1 Error: nested MAIL command`

Here are my SMTP settings:
![image](https://user-images.githubusercontent.com/304269/215248248-f34fabad-f40f-4698-b60f-3413d5515cb5.png)

**Comment by NessDan** [comment]
Update: Ditched the Windows installation and followed the steps here for production Docker with really good success: https://listmonk.app/docs/installation/
