### ISSUE TITLE
Transactional email missing subject

### ISSUE THREAD

**Issue by wehmoen** [knadh/listmonk#963]
**Version:**
 - listmonk: [eg: v2.2.0]
 - OS: Ubuntu 22.04 LTS

**Description of the bug and steps to reproduce:**
I created a transactional template **with a subject**. However when I use `POST /api/tx` the email that is send out has no subject. Campaign emails do have their subject. Checking the email headers in Outlook reveals no subject header.

**Screenshots:**
Received header:
![image](https://user-images.githubusercontent.com/6608103/193434713-659369aa-4827-48e6-900d-5700da07da93.png)
Template:
![image](https://user-images.githubusercontent.com/6608103/193434715-8fa95b68-2f84-4625-9235-dbbd90f69812.png)
![image](https://user-images.githubusercontent.com/6608103/193434720-9c7665c8-046c-41c0-9e1a-33cf7c0c1d60.png)

**Comment by wehmoen** [comment]
Maybe related to #898 ?

**Comment by knadh** [comment]
Yep, looks like it. This is already fixed and will be rolled out in the next release. For now, you can use the hack mentioned in #898.

**Comment by wehmoen** [comment]
Excellent. Thanks!
