### ISSUE TITLE
Amazon SES List Management Question

### ISSUE THREAD

**Issue by SachaG** [knadh/listmonk#965]
I just came across Listmonk and it seems like an awesome tool!

Now I understand that Listmonk can send emails via SES using SMTP. But SES now has its own list management features, so I was wondering if Listmonk could make use of them in any way? Or would that just not be compatible with the way Listmonk works?

**Comment by knadh** [comment]
Thanks @SachaG. listmonk can only use SES as an SMTP provider. Any other features SES has, listmonk cannot use.

**Comment by SachaG** [comment]
Thanks, that makes sense.
