### ISSUE TITLE
503 Issue a reset if you want to start over

### ISSUE THREAD

**Issue by makarov-ittx** [knadh/listmonk#966]
Got error in listmonk log: 503 Issue a reset if you want to start over
Approximately 10% of e-mails from a Campaign are not delivered with this error.

I am using open source mail server hmailserver
3500 users in Campaign

Performance settings:
Concurrency 5
Message rate 5
Batch size 500

SMTP settings:
Max. connections 5
Retries 2
Idle timeout 15s
Wait timeout 5s

**Comment by makarov-ittx** [comment]
Also hmailserver docs says:

https://www.hmailserver.com/documentation/v5.5/?page=reference_error_messages_smtp


503 Issue a reset if you want to start over
When an email client delivers an email message to an email server, it starts of by telling the server the senders address. After it has done this, a transaction is started which is not finished before the entire message has been delivered to the email server. If the client wishes to abort the transaction and send another message, it should issue the RSET command. If a client, in the middle of a transaction, tries to send a new email without first aborting the current transaction, hMailServer issues this error message. This indicates a bug in the SMTP client.

**Comment by knadh** [comment]
There have been a couple of reports here pointing to similar errors (https://github.com/knadh/listmonk/issues/337). I've been unable to reproduce this. listmonk uses the [smtppool](https://github.com/knadh/smtppool) lib. Will leave this issue open until the issue can be reproduced (and fixed).

**Comment by knadh** [comment]
Fixed an underlying smtp-pool lib. https://github.com/knadh/listmonk/commit/274d86422c5d44fe393d80b5bad6f19fb442fb66. This most likely should've been the issue.
