### ISSUE TITLE
use static directory with railway.app?

### ISSUE THREAD

**Issue by paulrudy** [knadh/listmonk#969]
I'm using the railway.app deploy template. Railway doesn't (yet) have persistent storage.

I'd like to edit `docker-compose.yml` in order to customize system templates as discussed [here in the docs](https://listmonk.app/docs/templating/#system-templates), but I need a local directory to point to.

Is this impossible with a Railway install, as long as Railway's storage is ephemeral? Can I point to files stored in S3 or via a CDN?

**Comment by knadh** [comment]
Hi @paulrudy. I'm not familiar with Railway. listmonk doesn't support s3 for static files out of the box. If Railway has a way to mount S3 as a filesystem, that would work.

**Comment by paulrudy** [comment]
Thanks @knadh. It looks like they don't have a way to do that. I'm going to try another platform. I appreciate the suggestion

**Comment by nickwynja** [comment]
This is possible with the Railway template. You need to copy the static directory into the image and then `RUN` using the proper arguments. My Dockerfile ended up looking like this:

```
FROM listmonk/listmonk:latest
ARG PORT ADMIN_PASSWORD ADMIN_USERNAME PGDATABASE PGHOST PGPASSWORD PGPORT PGUSER
COPY config.sh ./config.sh
COPY static/ /static/
RUN chmod +x ./config.sh && ./config.sh
RUN ./listmonk --idempotent --yes --upgrade || ./listmonk --install --yes --upgrade
CMD ./listmonk --static-dir=/static
```

**Comment by candidexmedia** [comment]
@nickwynja Thank you for sharing this! Do you know where these static files should be placed if we use your method and are hosting on Railway?

I'm trying to figure out how to add custom static files for double-opt-in on Railway, as mentioned here for Docker: https://yasoob.me/posts/setting-up-listmonk-opensource-newsletter-mailing/#custom-static-files
