### ISSUE TITLE
Add edit button on list page

### ISSUE THREAD

**Issue by henricazottes** [knadh/listmonk#97]
It would be nice to be able to edit list settings from its view page. Adding an `Edit` button next to `Add subscriber`. It's a good pattern users are used to :)

**Comment by knadh** [comment]
Ah yes, thanks. Will include this in the next release.

**Comment by knadh** [comment]
I should've remembered that this is quite tricky to implement! The subscriber lists is a whole different view/scope, so it is quite difficult to integrate the list editing view which is separate. I've added this to the to-do, albeit at the bottom. Thanks :)
