### ISSUE TITLE
Help with "panic: interface conversion" when deploying via Dockerfile?

### ISSUE THREAD

**Issue by paulrudy** [knadh/listmonk#971]
I'm trying to deploy listmonk on Fly.io with a Dockerfile, and I run into the following error that aborts deployment:

```
=> ERROR [5/5] RUN ./listmonk --idempotent --yes --upgrade || ./listmonk  0.4s
------
 > [5/5] RUN ./listmonk --idempotent --yes --upgrade || ./listmonk --install --yes --upgrade:
#8 0.365 2022/10/06 16:39:15 main.go:95: v2.2.0 (bbbf28c 2022-07-30T18:18:24Z)
#8 0.365 2022/10/06 16:39:15 init.go:128: reading config: config.toml
#8 0.368 panic: unhandled token: "user" [recovered]
#8 0.368 	panic: interface conversion: interface {} is *errors.errorString, not string
```
I see that the error in the last line comes from [go-toml](https://github.com/pelletier/go-toml), a library included in listmonk.

Is this a clue as to what information might be missing or badly formatted in my deployment command or Dockerfile?

**Comment by paulrudy** [comment]
Ok, partially figured it out. Env variables are not being successfully passed into the docker image on deploy.

**Comment by knadh** [comment]
Yep. listmonk refuses to start when mandatory config variables are not found (file or env).
