### ISSUE TITLE
Saving settings causes app to restart

### ISSUE THREAD

**Issue by paulrudy** [knadh/listmonk#973]
I'm running a new install at Flyi.io, and all operations seem so far to work well, except for saving settings.

When I edit any setting and click "save", listmonk immediately responds with “Settings saved. Reloading app.” But then it takes 10 seconds for the page then to refresh and the spinner to stop. Looking at the VM logs, it looks like the app may be restarting:

```
2022-10-08T00:18:39.753 app[9479001b] lax [info] 2022/10/08 00:18:39 init.go:736: reloading on signal ...
2022-10-08T00:18:39.754 app[9479001b] lax [info] 2022/10/08 00:18:39 init.go:711: HTTP server shut down
2022-10-08T00:18:39.874 app[9479001b] lax [info] 2022/10/08 00:18:39 main.go:95: v2.2.0 (bbbf28c 2022-07-30T18:18:24Z)
2022-10-08T00:18:39.874 app[9479001b] lax [info] 2022/10/08 00:18:39 init.go:128: reading config: config.toml
2022-10-08T00:18:39.875 app[9479001b] lax [info] 2022/10/08 00:18:39 init.go:255: connecting to db: mb-newsletter-db.internal:5433/mb_newsletter
2022-10-08T00:18:40.311 app[9479001b] lax [info] 2022/10/08 00:18:40 init.go:566: media upload provider: filesystem
2022-10-08T00:18:40.318 app[9479001b] lax [info] 2022/10/08 00:18:40 init.go:490: loaded email (SMTP) messenger: username@smtp.yoursite.com
2022-10-08T00:18:40.320 app[9479001b] lax [info] ⇨ http server started on [::]:9000
```

This behavior only seems to happen when saving settings, not when adding/editing campaigns, subscribers, etc.

Any ideas on troubleshooting would be welcomed!

**Comment by knadh** [comment]
This is by design. listmonk has to reload settings and reinitialize a number of controllers and clients, which is best done with a restart.

**Comment by paulrudy** [comment]
That makes sense, and the fact that it says "reloading app" should have been a clue for me.

But any ideas about what is causing it to take ten seconds to finish? On Railway it takes 30-60 ms.

**Comment by knadh** [comment]
The delay, it must be a Fly.io thing. Best to ask them. The restart otherwise is instant and seamless.

**Comment by paulrudy** [comment]
> The delay, it must be a Fly.io thing. Best to ask them. The restart otherwise is instant and seamless.

Thanks @knadh I appreciate you taking the time to help me. I'll check with them.

**Comment by paulrudy** [comment]
@knadh Aftersettings are saved and listmonk restarts itself, it then seems to repeatedly call `/api/health` (presumably to check when everything is running).

On Railway, for me this produces one error followed by a success a few ms later, hence the instant reload.

On Fly.io:

> Even outside of the configured health checks, we also have “passive” health checks. If our proxy can’t connect to your app when you make a request (such as when it’s restarting), this marks it as unhealthy for a few seconds. 10s to be precise, that matches what you’re seeing.
>
>This is meant to detect struggling instances and route around them.

So that explains the 10.something second reload.

I realize this is all very minor, but I wonder if it's possible to delay the first call to `/api/health` to allow a few more ms of time for the app to restart?

**Comment by knadh** [comment]
> I realize this is all very minor, but I wonder if it's possible to delay the first call to /api/health to allow a few more ms of time for the app to restart?

The app restart instantly, when the "Save" button is pressed. `/api/health` is polled by the UI simply to refresh the page once the app is back online.

It would be possible to address Railway's behaviour from within the app. Maybe they'll have a setting to reduce the `10s` poll time further.
