### ISSUE TITLE
A dropdown for placeholders

### ISSUE THREAD

**Issue by satyamskillz** [knadh/listmonk#974]
**Problem**
Hey guys, I have subscribers with a lot of attributes so whenever I create an email template, it takes time because I can't remember the attributes. I think, adding attributes to emails makes them more personalized, and increases the conversion rate therefore we need to build such a kinda feature.

**Solution**
I think a dynamic dropdown can do the job. The dropdown can appear either when the user enters `{{}}` in the rich text editor or choose the dropdown option in the menu bar.

I can build such a kinda feature but I need little help. I hope, I am not asking for too much 🙂

**Comment by knadh** [comment]
This is not possible, unfortunately because every subscriber can have completely different, arbitrarily nested attributes.
