### ISSUE TITLE
./listmonk --install not creating database

### ISSUE THREAD

**Issue by paulrudy** [knadh/listmonk#975]
In a new install, I'm running into the following error:

```
 > [2/2] RUN ./listmonk --config="" --idempotent --yes --upgrade || ./listmonk --config="" --install --yes --upgrade:
#5 0.241 2022/10/10 22:42:09 main.go:95: v2.2.0 (bbbf28c 2022-07-30T18:18:24Z)
#5 0.241 2022/10/10 22:42:09 init.go:255: connecting to db: listmonk-db:5433/test
#5 0.273 2022/10/10 22:42:09 init.go:259: error connecting to DB: pq: database "test" does not exist
#5 0.279 2022/10/10 22:42:09 main.go:95: v2.2.0 (bbbf28c 2022-07-30T18:18:24Z)
#5 0.280 2022/10/10 22:42:09 init.go:255: connecting to db: listmonk-db:5433/test
#5 0.313 2022/10/10 22:42:09 init.go:259: error connecting to DB: pq: database "test" does not exist
```

It's my understanding that the install script is supposed to create the database, so I'm confused about why it's complaining that the database does not exist. Any thoughts about how I can troubleshoot this?

**Comment by knadh** [comment]
listmonk doesn't create the database as that would require DB credentials with superadmin DB privileges, which is not ideal for an app. It only sets up the necessary tables and schema on an existing database.

**Comment by paulrudy** [comment]
I see, thank you!
