### ISSUE TITLE
Basic questions about SSL mode

### ISSUE THREAD

**Issue by paulrudy** [knadh/listmonk#977]
The documentation doesn't currently include any details about the `ssl_mode` setting. I'd like to just get a clearer understanding about it.

When does this mode apply and what does it do?

On a server that already redirects all incoming :80 traffic to :443, does `ssl_mode` offer anything additional?

(The infrastructure I'm using (Dockerfile-based VM on Fly.io), the auto-generated certs files are not available to me, and I want to understand what, if anything, further I should do to keep listmonk secure.)

**Comment by knadh** [comment]
listmonk does not have TLS/SSL support built in for its HTTP interface. That's expected to be handled by a reverse proxy in front of it, like HAProxy, Nginx, Caddy, or by service providers like Cloudflare, Fly.io, Heroku etc.

**Comment by paulrudy** [comment]
Thanks. So I don't currently have a reverse proxy configured, but my deployment forces an https connection, and listmonk still works. How does that differ from enabling SSL in listmonk with a reverse proxy set up?

**Comment by knadh** [comment]
Your deployment is on Fly.io? That means Fly.io itself is acting as a reverse proxy and terminating TLS in front of listmonk.

**Comment by paulrudy** [comment]
Thanks. Yes, it's on Fly.io. I think I understand the concept of reverse proxy in general terms now.

So if https works with a reverse proxy enabled, but `ssl_mode` disabled in listmonk... when would someone need to enable `ssl_mode`?

**Comment by paulrudy** [comment]
> That means Fly.io itself is acting as a reverse proxy and terminating TLS in front of listmonk.

I'm pretty sure that Flyi.io is [not acting as a reverse proxy](https://community.fly.io/t/ssl-for-custom-domains/1221) and only doing an https redirect. So I'm continuing to be confused about use of `ssl_mode` and the need for a reverse proxy, given that Listmonk appears to be working over https. Obviously I'm missing something...

**Comment by knadh** [comment]
Ah, I just realised you're referring to the `ssl_mode` setting in config.toml. This has nothing to do with the SSL over HTTP and is for enabling SSL on internal connections to the Postgres database.

As to how listmonk is running on https://, clearly something is terminating TLS in front of listmonk! Why don't you check the certificate details on the browser (the lock icon on the URL bar). That'll show what TLS/SSL certificate is being served and possibly who's serving it.

**Comment by knadh** [comment]
> What's the purpose of SSL on internal connections to the Postgres database? Is this in case of other processes or users with access to the server attempting to snoop?

That's right.

> For this internal SSL mode to work, are normal SSL certs required, like those from certbot? Can the certs be self-signed and non-expiring since they are not public?

Self-signed certs are fine for internal usecases like this.

**Comment by paulrudy** [comment]
Thanks very much for the clarification!
