### ISSUE TITLE
Question: Can i use my own translation?

### ISSUE THREAD

**Issue by approached** [knadh/listmonk#978]
Hi @ all,

Can i use my own translation? I use listmonk in a docker container. Me need just to customize one key `subscribers.optinSubject`:
https://github.com/knadh/listmonk/blob/c38100427dbf880e6acaa4caf61ce39fd0b62156/cmd/subscribers.go#L636

What is the best way?

**Comment by knadh** [comment]
Yes, this is possible. Please see https://listmonk.app/docs/i18n/

The existing language file you would like to customise, you can download from here https://github.com/knadh/listmonk/tree/master/i18n
