### ISSUE TITLE
which web hosting service is best for listmonk?

### ISSUE THREAD

**Issue by 1mkluzz** [knadh/listmonk#979]
Hi, 

I have been using Listmonk for some time now and must give it the highest praise for the great service it provides.

Regarding my questions: 
1- I was wondering what your advice is for the best service to host/deploy listmonk?
2- I was searching and fly.io seems a good solution, do you recommend another one?
3- Can we use MochaHost or Interserver to host listmonk?

Thank you for your attention.
Best regards

**Comment by NicoHood** [comment]
I am using the shared hosting of uberspace. It works great and I use it for all my hosting stuff. You do not need to worry about maintaining updates (to the server software itself), have automated backups and can pay what you want. They have awesome documentation and you are so free in your hosting, even if it is shared. Just a personal recommendation.

Oh and I use mailjet for sending the emails, as they have a large free tear.

**Comment by candideu** [comment]
I use Railway.app (referall code is: [7ENqQl](https://railway.app?referralCode=7ENqQl)), and recently migrated from Heroku. If you connect your credit card, you get 5$ of usage free every month.

I can't say whether or not this is the best one, but it's the most affordable one for me, since I haven't officially launched my newsletter yet. As someone who's not the most tech-savvy, it's also very easy to set up. If you'd like more info, let me know.

I've also been eyeing Pikapods, but there's no way of accessing the database as of yet. That said, hosting is very easy (1-click), and they offer templates for a number of other open-source apps.

SMTP-wise, I use a combination of Sendpulse, Mailgun, and Mailersend (GitHub student promo), as they have some of the most generous free tiers I've encountered.

**Comment by knadh** [comment]
A $5 (VPS) instance on DigitalOcean or any similar provider should do. You can run not only listmonk, but other websites or apps on the same instance.

**Comment by candideu** [comment]
> I'm using [Fly.io](https://fly.io)—similar to Railway, but offers persistent storage, which you need if you want to customize [listmonk's system templates](https://listmonk.app/docs/templating/#system-templates). It took me a few days to figure out how to set it up, but now that I have, it's pretty easy. Works on their free tier, as well.

Do you know of any tutoria's for this? I've been keen on editing the system templates, and wish it was possible to do from the app itself....

**Comment by paulrudy** [comment]
> Do you know of any tutoria's for this? I've been keen on editing the system templates, and wish it was possible to do from the app itself....

If you mean tutorials about editing templates, I don't know. If you know how to write HTML and CSS, you should be good to go. The link to the listmonk docs I included has links for the Go template expressions and Sprig functions that let you create slots for plugging in content in your template.

**Comment by candideu** [comment]
> If you mean tutorials about editing templates, I don't know. If you know how to write HTML and CSS, you should be good to go. The link to the listmonk docs I included has links for the Go template expressions and Sprig functions that let you create slots for plugging in content in your template.

Not to edit the themes, but how to set up Listmonk on fly.io and use its persistent storage to override the systen templates. I'm already familiar with HTML + CSS editing (the latter being possible inside the app), but I'm more curious about how to use fly.io and change its static directory.

**Comment by paulrudy** [comment]
I'd be happy to share what I've learned. I'll write up a step by step tomorrow.

**Comment by knadh** [comment]
> I've been keen on editing the system templates, and wish it was possible to do from the app itself....

This thread has a detailed discussion on why this isn't practical: https://github.com/knadh/listmonk/pull/438

**Comment by paulrudy** [comment]
@candideu I've created [a repo with instructions for deploying listmonk on Fly.io](https://github.com/paulrudy/listmonk-on-fly)

**Comment by candideu** [comment]
> @candideu I've created [a repo with instructions for deploying listmonk on Fly.io](https://github.com/paulrudy/listmonk-on-fly)

This is amazing!! Thanks for sharing

**Comment by paulrudy** [comment]
> This is amazing!! Thanks for sharing

Sure, happy to help!
