### ISSUE TITLE
Make subsrcibe and unsubscibe views customizable

### ISSUE THREAD

**Issue by henricazottes** [knadh/listmonk#98]
The page displayed in after subscribing/unsubscribing isn't customizable but hardcoded in `public.go`. Would be useful to make it editable in the same way base templates are.

**Comment by knadh** [comment]
Hi, are you referring to the English strings, success and error messages? Yes, these need to be pulled out into templates.

The actual templates are all in `/static` though, and not hardcoded.

**Comment by henricazottes** [comment]
I was referencing strings yes :)
