### ISSUE TITLE
POST /api/subscribers which is supposed to create new subscriber not working

### ISSUE THREAD

**Issue by hjasti** [knadh/listmonk#980]
Deployed through Railwayapp and was trying to use.

The api to create subscriber as per documentation is POST /api/subscriber. But using the sample request data from the documentation and calling the API, the response is the list of all existing subscribers (which should have been the response from GET call). 
The new subscriber data is not updated through POST call either. 
![image](https://user-images.githubusercontent.com/10722063/195510586-8e01a46a-c3b1-4376-8bff-2c2ac4090de9.png)

Please let me know if I am missing anything. I am fairly new to this.

**Comment by hjasti** [comment]
I took it from the sample in documentation. 
{"email":"subsriber@domain.com","name":"The Subscriber","status":"enabled","lists":[1],"attribs":{"city":"Bengaluru","projects":3,,"stack":{"languages":["go","python"]}}}

**Comment by hjasti** [comment]
Sorry, wrongly marked as closed. Hence, reopening.

**Comment by knadh** [comment]
Please share how you're sending the request. curl? Have you written code? If you're getting the list of subscribers in return, that means you're not sending a POST request. It must be going as GET somehow.

**Comment by hjasti** [comment]
I am using postman to make that POST call. Thought the screenshot shared in the first post would make it clear. 
By the way, for the same request, I got the code snippet from Postman with curl as follows. Even this shows it as POST.
While running this curl on terminal, its returning "Invalid Email".  

curl --location --request POST 'listmonk.intworks.com/api/subscribers' \
--header 'Authorization: Basic aGFyc2hhOiFudHdvcmtzIQ==' \
--header 'Content-Type: application/json' \
--data-raw '{"email":"subsriber@domain.com","name":"The Subscriber","status":"enabled","lists":[1],"attribs":{"city":"Bengaluru","projects":3,,"stack":{"languages":["go","python"]}}}'

**Comment by knadh** [comment]
The JSON in your payload is invalid. You have two commas after the `projects` key. Fixing that, the request works fine.

```shell
$ curl -X POST 'localhost:9000/api/subscribers' \
      -H 'Content-Type: application/json' \
      -d '{"email":"subsriber@domain.com","name":"The Subscriber","status":"enabled","lists":[1],"attribs":{"city":"Bengaluru","projects":3,"stack":{"languages":["go","python"]}}}'


{"data":{"id":6,"created_at":"2022-10-13T09:01:38.875514Z","updated_at":"2022-10-13T09:01:38.875514Z","uuid":"7807993a-7876-4e09-8f30-e2376a1c2a4d","email":"subsriber@domain.com","name":"The Subscriber","attribs":{"city":"Bengaluru","projects":3,"stack":{"languages":["go","python"]}},"status":"enabled","lists":[{"subscription_status":"unconfirmed","id":1,"uuid":"c6ddeefd-5dee-4251-a319-2750b9a7e5d6","name":"Default list","type":"private","optin":"single","tags":["test"],"created_at":"2022-10-13T06:58:27.197627+00:00","updated_at":"2022-10-13T06:58:27.197627+00:00"}]}}

```
