### ISSUE TITLE
Bounce handling (webhook) support for Elastic Email

### ISSUE THREAD

**Issue by binaryfire** [knadh/listmonk#981]
@knadh Hey mate, just discovered Listmonk. Nice work!

Would it be possible to add bounce handling support for Elastic Email?

https://help.elasticemail.com/en/articles/4804685-notification-settings

**Comment by knadh** [comment]
Thanks. listmonk only has webhook support for widely used platforms. Have never heard of Elastic Email. Will check it out.

In the meanwhile, if it's feasible, you can write a webhook endpoint that receives POSTs from Elastic Email, parses it, transforms the payload to listmonk's [generic webhook format](https://listmonk.app/docs/bounces/#webhook-api), and POST that to listmonk.

**Comment by binaryfire** [comment]
Hey! Thanks for the suggestion, will look into an API gateway as a workaround. But would be great to get a native integration at some point of course :)

I had another question re: tracking abuse reports from providers- will open a separate issue

**Comment by knadh** [comment]
Hi @binaryfire. Closing this issue for now. If there is enough demand for ElasticMail, we can reconsider this.
