### ISSUE TITLE
Improve documentation on transactional messages

### ISSUE THREAD

**Issue by emacsen** [knadh/listmonk#983]
The documentation on transactional messages simply says:

> A transactional message is an arbitrary message sent to a subscriber using the transactional message API.

That's accurate, but it would be better if it talked about what a transactional message is used for and or provide an example of using it to solve a problem.

I'd offer a suggestion in wording, but I don't know what transactional messages are for.

**Comment by knadh** [comment]
Done. https://github.com/knadh/listmonk-site/commit/ca1b4f77d6a70b4b91c6fb148d4b61bb53040b2d

Thanks
