### ISSUE TITLE
Transactional IDs, custom identificator

### ISSUE THREAD

**Issue by chladog** [knadh/listmonk#986]
There is no UX friendly way to get the transactional ID from UI. Currently only way to find out template IDs is by API call or in DB.

Some kind of user-defined unique identificator would be even better for transactional email template lookup, so it would be possible to switch templates via listmonk UI when needed without changing the backend code.

E.g. user-defined template property ```slug: string```.
```api/tx``` params that require either ```template_id``` or ```slug```.

**Comment by weese** [comment]
I'm also looking for a way to have a stable identifier for templates that can be used when sending a tx template via API call. In a typical setup the sender/user of the API needs to configure the id of a template somewhere and hence it would be good to have one or both:
1. see the id in the UI
2. have some alternative like a named identifier/slug that can be defined and is shown for a template

**Comment by knadh** [comment]
![image](https://user-images.githubusercontent.com/547147/197337826-c033507a-06ec-4319-9baf-a2cce24f0998.png)
![image](https://user-images.githubusercontent.com/547147/197337847-cc136605-6e8f-4779-b4c3-6eed5254f0e0.png)
