### ISSUE TITLE
problem to access the dashboard

### ISSUE THREAD

**Issue by udaemon** [knadh/listmonk#987]
**Version:**
 - listmonk: 2.2.0
 - OS: CentOS Linux Server (7.9.2009)

**Description of the bug and steps to reproduce:**
hi, surely this is not a bug, but I need some help anyway. 
I've just installed listmonk on a CentOS driven webspace server. there was even a very helpful guide I could follow provided by the server provider uberspace (https://lab.uberspace.de/guide_listmonk/). so, everything is up and running and no error to be seen, but still I can't access the proper dashboard. the only thing I get to see is, I assume, a representation of the (empty) database, cf. the screenshot attached.
I tried accessing with different browsers, but no difference. I'm sure it doesn't have to do with the firewall of the server or so, since, here, I followed the guide of my provider. furthermore, I doublechecked that. 
can someone please point me to problem? thank you so much!

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/55142697/196242851-2431f3d3-101a-423f-8d54-819e901cda35.png)

**Comment by knadh** [comment]
I'm not familiar with uberspace, but it seems like this is an issue with URL routing via `uberspace`. listmonk throws a 404 when it receives a request on a URI it doesn't recognize. If you run the binary and access :9000, it should work out of the box, which means something in `uberspace` is changing the routing incorrect. Probably best to speak to them.

**Comment by udaemon** [comment]
thanks so much, @knadh for your quick reply!!
i guess it was my own confusion that kept it from working like expected. i've solved it and have even set it up working already. 
they have this web backend-option on uberspace with which you can access a program from outside and what I did was to set the web backend with port 9000 open as a subdomain (listmonk.domain.xy) instead of a domain path (domain.xy/listmonk). that's all. but it took me a while to grasp. 
so this issue can be mark solved.
thanks again!
