### ISSUE TITLE
Cannot use API from Nextjs app

### ISSUE THREAD

**Issue by davidfoxio** [knadh/listmonk#988]
Hello

I've Created a Listmonk instance on Railway today. I'm trying to use the API to list subscribers, but am getting a 401 error in the console. I've tried with the same username and password in postman and it's working, so it's not an issue with the creds. Is there a problem with the code I've written?

PS - I know that this will all need to be moved to the backend before going into production (so the username and password is not publicly exposed), I'm just trying to get things working before I do all of that.

```
const onSubmit = async (data) => {
    fetch(`${process.env.NEXT_PUBLIC_LISTMONK_URL}/api/subscribers`, {
      mode: 'no-cors',
      method: 'GET',
      headers: new Headers({
        'Content-Type': 'application/json',
        "Authorization": `Basic ${encode(`${process.env.NEXT_PUBLIC_USERNAME}:${process.env.NEXT_PUBLIC_PASSWORD}`)}`,
      }),
    }).then(response => console.log(response));
```

**Comment by knadh** [comment]
Since the the request from Postman is working and you're logging into listmonk just fine, it's not an issue with your installation, but this particular request. The code snippet you shared looks fine. Maybe the environment variables in the code are empty? Have you tried `console.log()`ing them?

**Comment by davidfoxio** [comment]
@knadh yes, I've checked the variables and they do exist.

Something I forgot to mention in the OP is that my nextjs site is on a different origin (hosted with Netlify). Is this an issue? I was getting a CORS error before adding `mode: 'no cors'` which I assumed solved any issues around that, but perhaps not?

**Comment by knadh** [comment]
A CORS issue shouldn't throw 401. I'm not sure what's happening here. Something to do with the way NextJS is handling the request.

Tweaked your script a bit and tried it from the browser and it works as accepted.

```javascript
fetch(`http://localhost:9000/api/subscribers`, {
  mode: 'no-cors',
  method: 'GET',
  headers: new Headers({
    'Content-Type': 'application/json',
    "Authorization": `Basic ${btoa("listmonk:listmonk")}`,
  }),
}).then(response => console.log(response));
```

![image](https://user-images.githubusercontent.com/547147/196444039-6459d46b-236e-4b0d-ae45-85f90fcf4268.png)

**Comment by knadh** [comment]
> In this window (GitHub), I get "VM1398:1 Refused to connect to 'https://[railway app name].up.railway.app/api/subscribers' because it violates the document's Content Security Policy."

This is CORS and is expected.

> In my localhost:3000 window (running my Nextjs project), I still get a 401 error

I am not sure what's happening here. 401 isn't a CORS issue. listmonk just accepts BasicAuth over HTTP and there's nothing else to configure.

**Comment by davidfoxio** [comment]
@knadh I'm also getting a 401 error in an empty Chrome tab. Are you able to replicate that on your end, or is this working for you?

**Comment by knadh** [comment]
![image](https://user-images.githubusercontent.com/547147/196461843-707a5584-5e70-47bf-b785-2c60b8513c02.png)

Ah, I got a 401 and checked the trace and it shows a CORS error. So it was CORS after all! My bad. It looks like it's the pre-flight CORS OPTION check that is failing.

You can either setup a CORS proxy if you really want to test APIs from the browser console on a different domain (Nginx with the right CORS headers), or you can just test from a non-browser JS console.

**Comment by davidfoxio** [comment]
@knadh Thanks for confirming :)

I was getting the pre-flight issue from my nextjs localhost:3000 before I added "mode: 'no-cors'" to the request too.

Given that my API requests to the Listmonk Railway app will be coming from a different domain in production, does this mean I'll have to set up a CORS proxy? The request won't be made in the browser, but from a serverless API in my nextjs site.

**Comment by knadh** [comment]
CORS is only an issue in browsers. Your requests from Railway servers should be fine.

**Comment by davidfoxio** [comment]
@knadh - all working now in a serverless API, thanks for your help!
