### ISSUE TITLE
Can't change password using config.toml 

### ISSUE THREAD

**Issue by Jay991** [knadh/listmonk#989]
I successfully installed Listmonk through docker, but I can't seem to change the default username and password from `config.toml` file.
 Whenever I change the credentials in the file, I still login with the default credentials and the new ones don't apply.
I tried restarting Listmonk as a service `listmonk.service` was not found. How can I do this ?

**Comment by knadh** [comment]
Seems like your Docker config is not picking up the config file you're editing. @mr-karan ?

**Comment by mr-karan** [comment]
> Listmonk as a service listmonk.service was not found

If you're running with docker, `listmonk.service` won't be there on your system.

> Whenever I change the credentials in the file, I still login with the default credentials and the new ones don't apply

https://listmonk.app/docs/installation/#mounting-a-custom-configtoml

**Comment by Jay991** [comment]
> > Listmonk as a service listmonk.service was not found
> 
> If you're running with docker, `listmonk.service` won't be there on your system.
> 
> > Whenever I change the credentials in the file, I still login with the default credentials and the new ones don't apply
> 
> https://listmonk.app/docs/installation/#mounting-a-custom-configtoml

I restarted the listmonk docker container and the new config.toml applied.
