### ISSUE TITLE
Docs: Function for UnsubscribeURL wrongly documented

### ISSUE THREAD

**Issue by ChristianHuff-DEV** [knadh/listmonk#99]
The [docs](https://listmonk.app/docs/templating/) documenting the functions that can be used in templates mention `{{ .UnsubscribeURL }}` to include an unsubscribe URL.

As of [v0.4.0-alpha](https://github.com/knadh/listmonk/releases/tag/v0.4.0-alpha) the "." should not be used anymore.

PS: Thank you for this tool!

**Comment by knadh** [comment]
Fixed. Thank you.
