### ISSUE TITLE
Are throttled emails resent?

### ISSUE THREAD

**Issue by SathyaBhat** [knadh/listmonk#992]
Some of the emails that were scheduled to be sent went over the SES quota. Does listmonk attempt to resend the emails?  

I notice that in the campaign stats, it marks them as sent while the logs mention it was throttled.

**Comment by knadh** [comment]
Hi @SathyaBhat. If the SMTP server accepts the e-mail without errors, it is considered as `sent` by listmonk. Any error that the SMTP throws during sending, listmonk retries (Settings -> Peformance).

If SES accepts the mail and then queues and throttles, listmonk doesn't get to know and doesn't resend.

**Comment by SathyaBhat** [comment]
Thanks @knadh - this is what the logs say

```
2022/10/21 00:26:49 manager.go:391: error sending message in campaign xxx: subscriber d1e39d69-4da8-4168-8516-47bf53c1f0c5: 454 Throttling failure: Maximum sending rate exceeded.
```

I think SES did accept the batch and then was rejected as the sending rate exceeded the quotas set on SES.
