### ISSUE TITLE
Bulk endpoint for transactional emails 

### ISSUE THREAD

**Issue by weese** [knadh/listmonk#994]
**Is your feature request related to a problem? Please describe.**
I need to send transactional emails to multiple recipients at once and currently have to issue tausends of requests to `/api/tx` that only differ in the email address. The commercial solutions offer a to-array for multiple recipients.

- https://developers.sendinblue.com/reference/sendtransacemail
- https://dev.mailjet.com/email/guides/send-api-v31/

**Describe the solution you'd like**
I'd like to have a bulk endpoint for sending transactional emails that uses an array of email addresses.

**Comment by simenghe** [comment]
I would like this feature too!
