### ISSUE TITLE
Edit subscriber via API

### ISSUE THREAD

**Issue by ilyakonovalenko** [knadh/listmonk#995]
Hello,

Can you please let me know how to edit subscriber via API? It is not currently documentated and I was not able to find a way.

I tried to use PUT method with attribs to change, however, API always returns:
```
Unmarshal type error: expected=models.SubscriberAttribs, got=array, field=attribs, offset=12
```

I also tried to pass double-quoted json raw data (as used in import), but it also fails with:
```
Unmarshal type error: expected=models.SubscriberAttribs, got=string, field=attribs, offset=32
```

**Comment by knadh** [comment]
Looks like this is indeed missing in the docs. You can send the [same payload as subscriber creation](https://listmonk.app/docs/apis/subscribers/#post-apisubscribers) and send a PUT request to  `/api/subscribers/:id`

**Comment by ilyakonovalenko** [comment]
That is what I tried as well. Creation API works fine, but edit API returns an error I mentioned. I also tried to skip attribs parameter, however, it does not work as well :-(

**Comment by knadh** [comment]
`attribs` should always be a map, not an array. Here, it should be:

`{"attribs": {"cid":"123"}, "name":"Name Lastname"}`

**Comment by ilyakonovalenko** [comment]
> `attribs` should always be a map, not an array. 

Yeah. Changed it already. It seems the endpoint needs all params to be passed. Can you please implement PATCH endpoint or adjust PUT endpoint to only edit data passed in payload?

**Comment by knadh** [comment]
Ah yes, that's correct.

> Can you please implement PATCH endpoint or adjust PUT endpoint to only edit data passed in payload?

Will look into this.

**Comment by Pseudoman21** [comment]
> That is what I tried as well. Creation API works fine, but edit API returns an error I mentioned. I also tried to skip attribs parameter, however, it does not work as well :-(
> 
> Full payload is:
> 
> ```
> {"attribs":[{"cid":"123"}],"name":"Name Lastname"}
> ```

Hi! I know this is a long time ago but I can I ask help on adding subscriber using the API? Thank you so much!

**Comment by ilyakonovalenko** [comment]
> Hi! I know this is a long time ago but I can I ask help on adding subscriber using the API? Thank you so much!

Hello! Can you please share what your issue is?

**Comment by Pseudoman21** [comment]
> > Hi! I know this is a long time ago but I can I ask help on adding subscribers using the API? Thank you so much!
> 
> Hello! Can you please share what your issue is?

Hi! I am trying to add a subscriber using Postman before implementing it in the backend but it always responds with an unauthorized error.

**Comment by Pseudoman21** [comment]
> > Hi! I know this is a long time ago but I can I ask help on adding subscriber using the API? Thank you so much!
> 
> Hello! Can you please share what your issue is?

I am trying to test it using Thunder client: 
![image](https://user-images.githubusercontent.com/48127785/234157867-845df605-6a84-41ab-91f4-9e3ddb8e560c.png)

Do I need to supply the password and username of my ListMonk instance?

**Comment by knadh** [comment]
https://listmonk.app/docs/apis/subscribers/#put-apisubscriberssubscriber_id
