### ISSUE TITLE
Added-to List doesn't display on opt-in confirmation page. Syntax issue?

### ISSUE THREAD

**Issue by michaelbutler** [knadh/listmonk#996]
**Version:**
 - listmonk: v.2.2.0 (via official docker image)
 - OS: [e.g. Fedora]

**Description of the bug and steps to reproduce:**
Issue: opt-in page doesn't show the list I subscribed to, though the email DOES.

Installed yesterday. I tested the double opt-in subscribe form.

Email shows as follows (all good): 

![Screenshot_20221022_183813](https://user-images.githubusercontent.com/521702/197365052-cbd474a0-621e-4d4e-ad63-df2386ef6808.png)

After clicking confirm and going to my listmonk app page, it shows this:

![Screenshot_20221022_183827](https://user-images.githubusercontent.com/521702/197365061-2647d640-e183-4e17-bd1c-acab5b18098e.png)

Note the lack of **Weekly Newsletter**.

**Screenshots:**

Included above.

# Possible Solution

I looked at the github templates and compared the email template to the web page template and noticed some differences in syntax, but I don't know enough about Golang templates to know if there is something wrong (I didn't modify any of listmonk's code)

Email (working):

```
<ul>
    {{ range $i, $l := .Lists }}
        {{ if eq .Type "public" }}
            <li>{{ .Name }}</li>
        {{ else }}
            <li>{{ L.Ts "email.optin.privateList" }}</li>
        {{ end }}
    {{ end }}
</ul>
```
https://github.com/knadh/listmonk/blob/master/static/email-templates/subscriber-optin.html

Web (not working):

```
 <ul>
    {{ range $i, $l := .Data.Lists }}
        <input type="hidden" name="l" value="{{ $l.UUID }}" />
        {{ if eq $l.Type "public" }}
            <li>{{ $l.Name }}</li>
        {{ else }}
            <li>{{ L.Ts "public.subPrivateList" }}</li>
        {{ end }}
    {{ end }}
</ul>
```
https://github.com/knadh/listmonk/blob/master/static/public/templates/optin.html

~~If I had to guess, I would say that the web template needs to be `{{ if eq .Type "public" }}` and `<li>{{ .Name }}</li>`.  Assuming of course that something else isn't wrong with my installation or configuration! I got no errors in the logs.~~

**Comment by michaelbutler** [comment]
Actually I did it again just to check the HTML source and here is what was on the web page:

```
<section>
    <h2>Confirm</h2>
    <p>
        You have been added to the following lists:
    </p>

    <form method="post">
        <ul>
            
        </ul>
        <p>
            <input type="hidden" name="confirm" value="true" />
            <button type="submit" class="button" id="btn-unsub">
                Confirm subscription
            </button>
        </p>
    </form>
</section>
```

So even the hidden input field isn't rendering, which would imply a problem with the `range` line.

**Comment by paulrudy** [comment]
I just found this issue after encountering the same bug.

**Comment by knadh** [comment]
Investigating this.

**Comment by knadh** [comment]
Had forgotten about this. This issue was already fixed last month and will be available in the upcoming release. Please see https://github.com/knadh/listmonk/issues/940 (a temporary workaround is also described)
